### ISSUE TITLE
Go to position

### ISSUE THREAD

**Issue by benep** [mrbungle64/ioBroker.ecovacs-deebot#100]
**Describe the solution you'd like**
Manchmal wäre es super, wenn man den Roboter nur an eine bestimmte stelle in der Karte schicken könnte und er dort stoppt. Ein Beispiel wäre das ausleeren der Dustbox, dafür fährt er selbständig neben den Mülleimer.

Da das von Ecovacs nicht vorgesehen ist und über das manuelle move wegen Hindernissen eher blöd ist, könnte ich mir vorstellen, dass in der Software eine kleine CustomArea gesetzt wird. Dann der Roboter zum Saugen losgeschickt wird und die deebotPosition geprüft wird bis beides etwa übereinstimmt. Dann wird das Saugen abgebrochen.

**Deebot model** (please complete the following information):
Deebot T8 TrueDetect

**Comment by mrbungle64** [comment]
@benep 

Ja die Funktion vermisse ich selbst. An so einen Workaround hatte ich auch schon gedacht.
Ich mache mir mal Gedanken dazu, ob das ohne größeren Aufwand möglich ist zu implementieren.

**Comment by ds-1982** [comment]
Mein Deebot 920 parkt unter der Couch. Hätte auch Verwendung für diese Funktion.

**Comment by mrbungle64** [comment]
@benep @ds-1982 

Ich habe eine erste Version von der Funktion implementiert ("control.goToPosition").
Wenn Ihr möchtet könnt Ihr das ja schon mal testen.

Aber bitte immer bedenken, dass je nach Zeitpunkt der Installation von GitHub da auch mal eine "faule" Version dabei sein kann, wenn ein Entwickler gerade was committet hat, was gerade vielleicht nicht vollständig funktioniert.
Der aktuelle Stand (Sa. 15 Uhr) sollte aber soweit keine Probleme machen.

**Comment by ds-1982** [comment]
@mrbungle64 

Sieht schon mal sehr gut aus. Funktioniert, für meine Anforderungen perfekt.

**Comment by mrbungle64** [comment]
> @mrbungle64
> 
> Sieht schon mal sehr gut aus. Funktioniert, für meine Anforderungen perfekt.

@ds-1982 

Freut mich. Danke für die Rückmeldung 👍🏻

**Comment by benep** [comment]
Erstmal vielen Dank fürs Einbauen und vor allem so schnelle Einbauen der Funktion.

Funktioniert super mit dem T8 TrueDetect.

Ich hoffe ich nerve dich nicht damit, aber ich habe noch ein Überlegungen dazu.

- Gibt es einen Grund dafür, dass der Roboter beim Einfahren in die Position in "Pause" und nicht in "Stop"?
- Könnte man die Saugstärke beim Losfahren noch auf ganz klein stellen, damit er nicht so laut ist?
- Die Werte `ecovacs-deebot.0.map.lastUsedCustomAreaValues_*` finde ich hierfür auch interessant. Also dann als `lastUsedGoToPositionValues_*` zum Wiederholen.
- Ein "Nice to Have" wäre auch noch ein Sound beim Stoppen. Die Sounds 0=Chime, 17=Beep und 30=AmHere kommen mir da in den Sinn. Vielleicht mit default=30 oder als optionalen dritten Inputwert.

**Comment by mrbungle64** [comment]
> Erstmal vielen Dank fürs Einbauen und vor allem so schnelle Einbauen der Funktion.
> 
> Funktioniert super mit dem T8 TrueDetect.

Hi @benep, das freut mich. Danke für die Rückmeldung 👍🏻 

> 
> Ich hoffe ich nerve dich nicht damit, aber ich habe noch ein Überlegungen dazu.
> 
> * Gibt es einen Grund dafür, dass der Roboter beim Einfahren in die Position in "Pause" und nicht in "Stop"?

Ich hatte erst "Stop" - dann dachte ich es wäre vielleicht besser "Pause" zu nehmen, weil dann der Reinigungsvorgang nicht sofort als beendet gewertet wird. Aber da man im Endeffekt auch keine praktische Möglichkeit hat diesen Reinigungsdurchgang fortzuführen hat das keinen Vorteil.
Du hast also Recht: "Stop" hat im Zweifelsfall mehr Vorteile als "Pause". Werde ich also ändern.

> * Könnte man die Saugstärke beim Losfahren noch auf ganz klein stellen, damit er nicht so laut ist?

Ja, das ist eine gute Idee 👍🏻
Werde ich mal einplanen.

> * Die Werte `ecovacs-deebot.0.map.lastUsedCustomAreaValues_*` finde ich hierfür auch interessant. Also dann als `lastUsedGoToPositionValues_*` zum Wiederholen.

Ja, an sich auch ein gute Idee, aber der Aufwand ist wahrscheinlich zu hoch, da die Ecovacs API hierbei die gleichen Events meldet wie bei der normalen CustomArea Reinigung. Die kann man nicht so einfach unterscheiden, wenn die über die Library reinkommen.

> * Ein "Nice to Have" wäre auch noch ein Sound beim Stoppen. Die Sounds 0=Chime, 17=Beep und 30=AmHere kommen mir da in den Sinn. Vielleicht mit default=30 oder als optionalen dritten Inputwert.

Hatte ich auch schon dran gedacht - mein Favorit wäre 30 "I am here".
Werde ich ggf. als Option anbieten (am besten inkl. wählbarer Sounds), weil das bestimmt nicht jeder haben will.

**Comment by mrbungle64** [comment]
Du hast mich übrigens auf noch ein paar Ideen gebracht mit diesem Issue.
In der aktuellen Version 1.0.8-alpha.1 sind noch weitere "verwandte" Funktionen im "control" channel vorhanden:
* pauseBeforeDockingChargingStation: Bot geht auf Pause kurz bevor er auf die Ladestation fahren würde
* pauseWhenEnteringSpotArea: Bot geht auf Pause, wenn er in der gewünschten SpotArea eintrift
* pauseWhenLeavingSpotArea: Bot geht auf Pause, wenn er aus der gewünschten SpotArea wieder raus fährt

@benep @ds-1982 
Vieleicht sind die ja für Euch auch interessant. Müssen unter "Experimental" -> "Einige weitere experimentelle Features im control Kanal" freigeschaltet werden.

**Comment by benep** [comment]
> noch weitere "verwandte" Funktionen 

Siehe dazu #109

**Comment by mrbungle64** [comment]
@benep @ds-1982 

Schon mal zur Info:
Ab der nächsten Version wird es unter "control" einen Unterordner "extended" geben.
Ich habe sämtliche Funktionen die in letzter Zeit hinzugekommen sind (wie "goToPosition") dorthin umgezogen.

**Comment by benep** [comment]
Das funktioniert jetzt super. Das Stoppen an der Position finde ich viel besser.

Ich hab mir damit ein Blockly geschrieben, das den Roboter nach jeder Reinigung im Schlafzimmer zur Tür schickt, weil er da wegen einer großen Stufe nicht allein raus kommt. Sonst bleibt er regelmäßig unterm Bett stehen, weil er nicht raus findet. Jetzt steht er brav an der Tür bereit zum Abholen. Fehlt nur noch der richtige Sound. Wenn dir mal langweilig sein sollte, kannst du ja mal noch die Sound-Id übergebbar machen.

Auch das Issue wäre damit für mich erledigt. Danke für die Umsetzung!

**Comment by benep** [comment]
> > * Könnte man die Saugstärke beim Losfahren noch auf ganz klein stellen, damit er nicht so laut ist?
> 
> Ja, das ist eine gute Idee 👍🏻
> Werde ich mal einplanen.

Das hatte ich noch vergessen. Das geht bei mir nooch nicht.

**Comment by mrbungle64** [comment]
> Werde ich mal einplanen.

Ja, ich hatte ja auch nur geschrieben, dass ich es mal einplanen werde ;)

Von daher lassen wir den Issue noch mal offen.

**Comment by mrbungle64** [comment]
Go to position ist grundsätzlich umgesetzt.
Dass die Saugstärke beim Losfahren auf leise gestellt wird, wird aktuell nicht umgesetzt.

**Comment by mrbungle64** [comment]
Hi @m1k3f15h 

ja, das ist nicht so ganz eindeutig gekennzeichnet. Hier geht es nur darum, ob die "native" Funktion benutzt werden soll.
Die Funktion an sich wird über "Einige weitere experimentelle Features (control.extended Kanal)" aktiviert.

Ich muss die Einstellungen mal wieder überarbeiten 😉

**Comment by m1k3f15h** [comment]
Hy @mrbungle64 
Danke für die schnelle Rückmeldung :)

"Einige weitere experimentelle Features ("control.extended" Kanal)" hab ich auch aktiviert

mfg
Mike

**Comment by mrbungle64** [comment]
@m1k3f15h 

Welches Modell ist das?

**Comment by m1k3f15h** [comment]
@mrbungle64 
DEEBOT T9

**Comment by mrbungle64** [comment]
@m1k3f15h 

> @mrbungle64 DEEBOT T9

Was steht im Datenpunkt "info.deviceClass"?

**Comment by m1k3f15h** [comment]
@mrbungle64 
ucn2xe

**Comment by mrbungle64** [comment]
@m1k3f15h 

Wie schaut es mit den anderen Datenpunkten im "control.extended" Kanal aus?
Kannst du mal einen Screenshot von den Datenpunkten in dem Kanal posten?

**Comment by m1k3f15h** [comment]
@mrbungle64 

Im Anhanf der screenshot vom Control Kanal.
Brauchst du alle oder reicht das so?

mfg
Mike

![Screenshot 2022-12-12 174639](https://user-images.githubusercontent.com/26365771/207103812-d3e2a4bd-32d2-45d1-8dda-e0bf9d538476.jpg)

**Comment by mrbungle64** [comment]
@m1k3f15h 

Der Datenpunkt "goToPosition" ist aber doch da 😉 
Mitten im "control.extended" Kanal ...

**Comment by m1k3f15h** [comment]
@mrbungle64 
Verd....mt..
Kannst mir noch einen guten Optiker empfehlen? 
sorry für das und danke für die Hilfe :)
mfg
Mike
