### ISSUE TITLE
Dustbox Auslastung in %

### ISSUE THREAD

**Issue by benep** [mrbungle64/ioBroker.ecovacs-deebot#101]
**Describe the solution you'd like**
Ich würde gerne etwa wissen wie voll meine Dustbox ist, um dadurch neue Aktionen oder eine eigene Warnung auszugeben.
Leider konnte ich dazu nichts finden, obwohl die Software von Ecovacs diese Warnung ja schon aus gibt.

Falls das mit Boardmitteln umgesetzt werden muss könnte ich mir vorstellen das über die gereinigten Quadratmeter umzusetzen. Also ein Wert, der die gereinigten qm seit der letzten Leerung zählt. Und eine Einstellung der Quadratmeter bei welcher die Box voll sein müsste.

**Deebot model** (please complete the following information):
 Deebot Ozmo T8 TrueDetect ohne +

**Comment by mrbungle64** [comment]
@benep 

Spontan ist meine Meinung dazu, dass mir das zu ungenau wäre.
Da müsste man wahrscheinlich zu oft nachjustieren bis es dann mal halbwegs stimmt.

Ich denke wenn man dazu nichts in der API entdecken kann sollte man lieber auf die Funktion verzichten.

**Comment by benep** [comment]
Da das Thema im anderen Issue untergegangen ist, hier die Infos zur Dokumentation.
Siehe dazu auch: https://github.com/mrbungle64/ioBroker.ecovacs-deebot/issues/99#issuecomment-738959048

Zumindest die Zeit der letzten Entfernung der DustBox wäre interessant als Wert.

Das Event für "DustBox entfernt" sieht folgendermaßen aus:
```
[EcovacsMQTT_JSON] _handle_command() command onFwBuryPoint received event: {"resultCode":"0","resultCodeMessage":"ok","resultData":{"content":"{"rn":"bd_errorcode","d":{"header":{"pri":1,"tzm":480,"ts":"1607107256490","ver":"0.0.1","fwVer":"1.6.3","hwVer":"0.1.1"},"body":{"data":{"d_id":"739675","d_sum":1,"d_seq":0,"d_val":"{"gid":"G1606997682093","information":0,"index":"0000001036","code":110,"state":1,"ldsinfo":1,"content":"","occurrenceTime":"1607107256483"}"}}}}"}}
```
Relevant ist: `command = onFwBuryPoint`, `rn = bd_errorcode`, `code = 110`, `state = 1`

Das Event für das Einsetzen der DustBox:
```
[EcovacsMQTT_JSON] _handle_command() command onFwBuryPoint received event: {"resultCode":"0","resultCodeMessage":"ok","resultData":{"content":"{"rn":"bd_errorcode","d":{"header":{"pri":1,"tzm":480,"ts":"1607107259140","ver":"0.0.1","fwVer":"1.6.3","hwVer":"0.1.1"},"body":{"data":{"d_id":"975281","d_sum":1,"d_seq":0,"d_val":"{"gid":"G1606997682093","information":0,"index":"0000001037","code":110,"state":0,"ldsinfo":0,"content":"","occurrenceTime":"1607107259122"}"}}}}"}}
```
Relevant ist: `command = onFwBuryPoint`, `rn = bd_errorcode`, `code = 110`, `state = 0`

**Comment by mrbungle64** [comment]
> Da das Thema im anderen Issue untergegangen ist, hier die Infos zur Dokumentation.
> Siehe dazu auch: [#99 (comment)](https://github.com/mrbungle64/ioBroker.ecovacs-deebot/issues/99#issuecomment-738959048)
> 
> Zumindest die Zeit der letzten Entfernung der DustBox wäre interessant als Wert.
> 
> Das Event für "DustBox entfernt" sieht folgendermaßen aus:
> 
> ```
> [EcovacsMQTT_JSON] _handle_command() command onFwBuryPoint received event: {"resultCode":"0","resultCodeMessage":"ok","resultData":{"content":"{"rn":"bd_errorcode","d":{"header":{"pri":1,"tzm":480,"ts":"1607107256490","ver":"0.0.1","fwVer":"1.6.3","hwVer":"0.1.1"},"body":{"data":{"d_id":"739675","d_sum":1,"d_seq":0,"d_val":"{"gid":"G1606997682093","information":0,"index":"0000001036","code":110,"state":1,"ldsinfo":1,"content":"","occurrenceTime":"1607107256483"}"}}}}"}}
> ```
> 
> Relevant ist: `command = onFwBuryPoint`, `rn = bd_errorcode`, `code = 110`, `state = 1`
> 
> Das Event für das Einsetzen der DustBox:
> 
> ```
> [EcovacsMQTT_JSON] _handle_command() command onFwBuryPoint received event: {"resultCode":"0","resultCodeMessage":"ok","resultData":{"content":"{"rn":"bd_errorcode","d":{"header":{"pri":1,"tzm":480,"ts":"1607107259140","ver":"0.0.1","fwVer":"1.6.3","hwVer":"0.1.1"},"body":{"data":{"d_id":"975281","d_sum":1,"d_seq":0,"d_val":"{"gid":"G1606997682093","information":0,"index":"0000001037","code":110,"state":0,"ldsinfo":0,"content":"","occurrenceTime":"1607107259122"}"}}}}"}}
> ```
> 
> Relevant ist: `command = onFwBuryPoint`, `rn = bd_errorcode`, `code = 110`, `state = 0`

@benep 

Alles klar. Danke für die Infos :+1: 
Werde ich demnächst dann mal implementieren.

> Ich würde gerne etwa wissen wie voll meine Dustbox ist, um dadurch neue Aktionen oder eine eigene Warnung auszugeben.
> Leider konnte ich dazu nichts finden, obwohl die Software von Ecovacs diese Warnung ja schon aus gibt.

Hierzu würde mich interessieren, wie das beim T8 aussieht.
Ist das einfach nur die Warnung in der Art "Staubbox ist voll und muss geleert werden" oder sieht man zusätzlich noch irgendwo was der aktuelle Stand ist, bevor da eine Warnung ausgegeben wird?

Evtl. findet sich dazu ja auch irgendwo was in den Events.

**Comment by benep** [comment]
Ich bin mir tatsächlich gerade nicht mehr 100% sicher, ob der T8 das wirklich sagt oder ob ich es falsch in Erinnerung habe und es nur das Filter Reinigen war. Normalerweise leere ich die Box inzwischen täglich nach der Reinigung, auch wenn sie fast leer ist.

Dann jedenfalls kommt nach der Reinigung in der App ein Popup mit der Info "Filter reinigen", das kann ich bestätigen oder mir Infos dazu anzeigen, wie das geht.

Ich hab seit den Test oben am Samstag die Box extra nicht mehr entfernt und warte jetzt, was passiert. Ich melde mich dann.

**Comment by benep** [comment]
Also nun die Info zu Staubbox und Filter. Es ist leider nur eine kombinierte Info für beides, die nach einiger Zeit nach einer Reinigung, beim starten den Ladevorgangs in den Roboter-Messages angezeigt wird. Leider hatte ich bisher die Logs nicht laufen, während die Nachricht kam.

![Screenshot_20201212-155100](https://user-images.githubusercontent.com/237102/102013771-6e2d3080-3d52-11eb-8941-bb99e97c450c.png)

Hast du an `ecovacs-deebot.0.info.dustbox` was geändert? Konnte nix in dem Commits finden. Das ist bei mir immer true, auch wenn ich die entnehme.

**Comment by mrbungle64** [comment]
@benep 

> Also nun die Info zu Staubbox und Filter

Das bezieht sich aber doch gar nicht auf die Staubbox, sondern nur auf die Filter. Die Werte zu Filter (und Bürsten) sind unter "consumable" zu finden.
Oder übersehe ich etwas?

> Hast du an ecovacs-deebot.0.info.dustbox was geändert? Konnte nix in dem Commits finden. Das ist bei mir immer true, auch wenn ich die entnehme.

Nein, da habe ich mich leider noch nicht mit beschäftigt.

**Comment by benep** [comment]
> Das bezieht sich aber doch gar nicht auf die Staubbox

Hm, also ich verstehe das so, dass man die Staubbox **leeren** soll. Wird auch etwa alle 3 kompletten Reinigungen angezeigt.

> Die Werte zu Filter (und Bürsten) sind unter "consumable" zu finden.

Der Wert ist doch für das **Austauschen** und nicht das Reinigen, wie im Screenshot.

**Comment by mrbungle64** [comment]
> > Das bezieht sich aber doch gar nicht auf die Staubbox
> 
> Hm, also ich verstehe das so, dass man die Staubbox **leeren** soll. Wird auch etwa alle 3 kompletten Reinigungen angezeigt.

Ja, aber das ist ja keine konkrete Meldung, sondern nur ein recht allgemein gehaltener Hinweis.
Da kann ich jetzt erst mal nicht viel mit anfangen (um da was in der Library oder dem Adapter zu implementieren).

> 
> > Die Werte zu Filter (und Bürsten) sind unter "consumable" zu finden.
> 
> Der Wert ist doch für das **Austauschen** und nicht das Reinigen, wie im Screenshot.

Ja, das ist korrekt ;)

**Comment by benep** [comment]
> Ja, aber das ist ja keine konkrete Meldung, sondern nur ein recht allgemein gehaltener Hinweis.

Ich denke schon, dass der je nach Benutzung des Saugers gesteuert wird. Kommt wie gesagt nach 2-3 Komplettreinigungen.
Um da sinnvoll zu verwenden könnte es ein Object `lastEmptyDustBinMessage` mit dem letzten Datum der Meldung geben. Kombiniert mit einem Objekt `lastRemovedDustBin` mit dem Datum. Dann könnte ich meine Automatisierungen darüber steuer statt über eine Prozent-Anzeige.

**Comment by mrbungle64** [comment]
> > Ja, aber das ist ja keine konkrete Meldung, sondern nur ein recht allgemein gehaltener Hinweis.
> 
> Ich denke schon, dass der je nach Benutzung des Saugers gesteuert wird. Kommt wie gesagt nach 2-3 Komplettreinigungen.
> Um da sinnvoll zu verwenden könnte es ein Object `lastEmptyDustBinMessage` mit dem letzten Datum der Meldung geben. Kombiniert mit einem Objekt `lastRemovedDustBin` mit dem Datum. Dann könnte ich meine Automatisierungen darüber steuer statt über eine Prozent-Anzeige.

Du meinst anhand der Meldung diese Datenpunkte zu befüllen?

Falls ja: bisher habe ich mich noch nicht damit beschäftigt, wie man über die API diese Meldungen bekommt. Leider gibt es ja keine öffentlich zugängliche Doku von Ecovacs...

Anonsten könnte ich ja den Statuswechsel von `info.dustbox` in `lastRemovedDustBin` festhalten, falls Dir das schon hilft. Muss `info.dustbox` natürlich auch erst mal für den T8 zum Laufen bringen ;)

**Comment by boriswerner** [comment]
Hi, vielleicht kann ich da zumindest ein bisschen Licht ins Dunkel bringen:
info.dustbox: Die Implementierung ist auf Basis des 950 (der heißt mittlerweile übrigens auch T5, oder?) geschehen und der gibt kein Event für das Entfernen/Einsetzen der DustBox. Stattdessen gibt er nur den Fehler 110 aus, wenn die Dustbox nicht eingesetzt ist und man eine Reinigung startet, oder wenn man sie ihm während der Reinigung entnimmt. Ich hatte irgendwann mal geplant den errorcode zu nutzen um die info.dustbox zu setzen, aber anscheinend bin ich davon abgekommen...
Mit dem neuen Event, was @benep oben beschreibt, könnte man dann ja in der Tat den state setzen, allerdings gibt es den wie beschrieben nicht für den 950.

Zu der Meldung: hier gibt es meist eine onEvt message. Das sind allerdings nur 4-stellige Codes. Das müsste man durch Protokollierung und Beobachtung irgendwie in Zusammenhang bringen. Ich hab schonmal versucht das für einige Events zu dokumentieren, z.B: ist 

onEvt | {"code":1021} | Reinigung abgeschlossen, kehre zur Ladestation zurück
Wenn man herausbekommt, welchen event code die o.g. Meldung hat, könnte man das natürlich auch ausgeben. Ich bekomme die Meldung aber nicht (ich meine mich zu erinnern, dass ich sie mal bekommen hatte, aber nicht regelmäßig. @benep bekommst du die wirklich regelmäßig?)

**Comment by benep** [comment]
>  benep bekommst du die wirklich regelmäßig?

Ja, genau, im Moment des Rausziehens und Reinsetzens. Auch wenn man das öfter wiederholt. Ist perfekt reproduzierbar.

Warum das `onFwBuryPoint` heißt, weiß ich nicht, aber da steken sehr viele verschiedene Infos drinen. Ich hab mal ein paar gespeichert. Von Positionsmeldungen, über AI-Einstellungen und Prozesser und Speicher-Infos des Bots, bis zu deinen Event-Meldungen und Fehlern.

Hier mal paar Beispiele:

```
[EcovacsMQTT_JSON] _handle_command() command onFwBuryPoint received event: {"resultCode":"0","resultCodeMessage":"ok","resultData":{"content":"{"rn":"bd_sysinfo","d":{"header":{"pri":1,"tzm":480,"ts":"1607249360551","ver":"0.0.1","fwVer":"1.6.3","hwVer":"0.1.1"},"body":{"data":{"d_id":"737418","d_sum":3,"d_seq":0,"d_val":"[{"signal":-61,"uptime":" 09:55:20 up 20:00,  0 users,  load average: 3.48, 3.17, 2.35\\\\n","meminfo":"160980,72016","pos":"-5642,-1017","isvalid":1,"mapid":0,"ts":"1607248520"},{"signal":-61,"uptime":" 09:56:20 up 20:01,  0 users,  load average: 3.31, 3.16, 2.40\\\\n","meminfo":"160900,72096","pos":"-5683,-1129","isvalid":1,"mapid":0,"ts":"1607248580"},{"signal":-62,"uptime":" 09:57:20 up 20:02,  0 users,  load average: 3.89, 3.34, 2.51\\\\n","meminfo":"163160,69836","pos":"-4819,-751","isvalid":1,"mapid":0,"ts":"1607248640"},{"signal":-63,"uptime":" 09:58:20 up 20:03,  0 users,  load average: 3.00, 3.19, 2.51\\\\n","meminfo":"161392,71604","pos":"-5563,-1384","isvalid":1,"mapid":0,"ts":"1607248700"},{"signal":-68,"uptime":" 09:59:20 up 20:04,  0 users,  load average: 3.37, 3.27, 2.58\\\\n","meminfo":"165040,67956","pos":"-5124,-1842","isvalid":1,"mapid":0,"ts":"1607248760"},{"signal":-67,"uptime":" 10:00:20 up 20:05,  0 users,  load average: 3.32, 3.28, 2.63\\\\n","meminfo":"161052,71944","pos":"-4541,-1959","isvalid":1,"ma"}}}}"}}
[EcovacsMQTT_JSON] _handle_command() command onFwBuryPoint received event: {"resultCode":"0","resultCodeMessage":"ok","resultData":{"content":"{"rn":"bd_sysinfo","d":{"header":{"pri":1,"tzm":480,"ts":"1607249360553","ver":"0.0.1","fwVer":"1.6.3","hwVer":"0.1.1"},"body":{"data":{"d_id":"737418","d_sum":3,"d_seq":1,"d_val":"pid":0,"ts":"1607248820"},{"signal":-63,"uptime":" 10:01:20 up 20:06,  0 users,  load average: 2.83, 3.15, 2.63\\\\n","meminfo":"165488,67508","pos":"-6400,-2376","isvalid":1,"mapid":0,"ts":"1607248880"},{"signal":-62,"uptime":" 10:02:20 up 20:07,  0 users,  load average: 3.83, 3.39, 2.75\\\\n","meminfo":"161108,71888","pos":"-5967,-2358","isvalid":1,"mapid":0,"ts":"1607248940"},{"signal":-66,"uptime":" 10:03:20 up 20:08,  0 users,  load average: 4.30, 3.57, 2.85\\\\n","meminfo":"163608,69388","pos":"-4938,-2382","isvalid":1,"mapid":0,"ts":"1607249000"},{"signal":-64,"uptime":" 10:04:20 up 20:09,  0 users,  load average: 3.28, 3.41, 2.83\\\\n","meminfo":"163836,69160","pos":"-7157,-2460","isvalid":1,"mapid":0,"ts":"1607249060"},{"signal":-65,"uptime":" 10:05:20 up 20:10,  0 users,  load average: 2.95, 3.29, 2.83\\\\n","meminfo":"160956,72040","pos":"-7303,-1637","isvalid":1,"mapid":0,"ts":"1607249120"},{"signal":-56,"uptime":" 10:06:20 up 20:11,  0 users,  load average: 3.27, 3.26, 2.85\\\\n","meminfo":"160736,72260","pos":"-4"}}}}"}}
[EcovacsMQTT_JSON] _handle_command() command onFwBuryPoint received event: {"resultCode":"0","resultCodeMessage":"ok","resultData":{"content":"{"rn":"bd_sysinfo","d":{"header":{"pri":1,"tzm":480,"ts":"1607249360554","ver":"0.0.1","fwVer":"1.6.3","hwVer":"0.1.1"},"body":{"data":{"d_id":"737418","d_sum":3,"d_seq":2,"d_val":"540,-205","isvalid":1,"mapid":0,"ts":"1607249180"},{"signal":-63,"uptime":" 10:07:20 up 20:12,  0 users,  load average: 3.10, 3.25, 2.87\\\\n","meminfo":"160744,72252","pos":"-6362,-2030","isvalid":1,"mapid":0,"ts":"1607249240"},{"signal":-65,"uptime":" 10:08:20 up 20:13,  0 users,  load average: 2.95, 3.19, 2.87\\\\n","meminfo":"160844,72152","pos":"-7117,-1955","isvalid":1,"mapid":0,"ts":"1607249300"},{"signal":-65,"uptime":" 10:09:20 up 20:14,  0 users,  load average: 3.13, 3.22, 2.91\\\\n","meminfo":"160924,72072","pos":"-5735,-1907","isvalid":1,"mapid":0,"ts":"1607249360"}]"}}}}"}}
[EcovacsMQTT_JSON] _handle_command() command onFwBuryPoint received event: {"resultCode":"0","resultCodeMessage":"ok","resultData":{"content":"{"rn":"bd_task","d":{"header":{"pri":1,"tzm":480,"ts":"1607249900558","ver":"0.0.1","fwVer":"1.6.3","hwVer":"0.1.1"},"body":{"data":{"d_id":"720852","d_sum":1,"d_seq":0,"d_val":"{"gid":"G1607176517169","index":"0000000173","act":"start","mid":"1398486614","taskType":"return","subTask":"normal","content":"34,-334","count":"","occurrenceTime":"1607249900484"}"}}}}"}}
[EcovacsMQTT_JSON] _handle_command() command onFwBuryPoint received event: {"resultCode":"0","resultCodeMessage":"ok","resultData":{"content":"{"rn":"bd_task","d":{"header":{"pri":1,"tzm":480,"ts":"1607249900557","ver":"0.0.1","fwVer":"1.6.3","hwVer":"0.1.1"},"body":{"data":{"d_id":"720852","d_sum":1,"d_seq":0,"d_val":"{"gid":"G1607176517169","index":"0000000172","act":"stop","mid":"1398486614","taskType":"clean","subTask":"spotarea","count":"1","content":"3","time":29,"area":9,"aiavoidtype":"","aiavoidcnt":"","occurrenceTime":"1607249900483"}"}}}}"}}
[EcovacsMQTT_JSON] _handle_command() command onFwBuryPoint received event: {"resultCode":"0","resultCodeMessage":"ok","resultData":{"content":"{"rn":"bd_basicinfo","d":{"header":{"pri":1,"tzm":480,"ts":"1607249900681","ver":"0.0.1","fwVer":"1.6.3","hwVer":"0.1.1"},"body":{"data":{"d_id":"720852","d_sum":1,"d_seq":0,"d_val":"{"gid":"G1607176517169","index":"0000000174","battery":75,"waterbox":0,"sleep":0,"charge":0,"robotstate":1,"robotPos":"-4257,-2242","chargePos":"34,-334","occurrenceTime":"1607249900486"}"}}}}"}}
[EcovacsMQTT_JSON] _handle_command() command onFwBuryPoint received event: {"resultCode":"0","resultCodeMessage":"ok","resultData":{"content":"{"rn":"bd_basicinfo","d":{"header":{"pri":1,"tzm":480,"ts":"1607249900683","ver":"0.0.1","fwVer":"1.6.3","hwVer":"0.1.1"},"body":{"data":{"d_id":"720852","d_sum":1,"d_seq":0,"d_val":"{"gid":"G1607176517169","index":"0000000176","battery":75,"waterbox":0,"sleep":0,"charge":0,"robotstate":1,"robotPos":"-4257,-2242","chargePos":"34,-334","occurrenceTime":"1607249900492"}"}}}}"}}
[EcovacsMQTT_JSON] _handle_command() command onFwBuryPoint received event: {"resultCode":"0","resultCodeMessage":"ok","resultData":{"content":"{"rn":"bd_setting","d":{"header":{"pri":1,"tzm":480,"ts":"1607249900682","ver":"0.0.1","fwVer":"1.6.3","hwVer":"0.1.1"},"body":{"data":{"d_id":"720852","d_sum":1,"d_seq":0,"d_val":"{"gid":"G1607176517169","index":"0000000175","simpleMode":0,"AI":1,"isPressurized":1,"multiMap":1,"fanspeed":1,"continue":1,"waterAmount":1,"DND":1,"mopremind":1,"mopmode":0,"occurrenceTime":"1607249900490"}"}}}}"}}
[EcovacsMQTT_JSON] _handle_command() command onFwBuryPoint received event: {"resultCode":"0","resultCodeMessage":"ok","resultData":{"content":"{"rn":"bd_setting","d":{"header":{"pri":1,"tzm":480,"ts":"1607249900683","ver":"0.0.1","fwVer":"1.6.3","hwVer":"0.1.1"},"body":{"data":{"d_id":"720852","d_sum":1,"d_seq":0,"d_val":"{"gid":"G1607176517169","index":"0000000177","simpleMode":0,"AI":1,"isPressurized":1,"multiMap":1,"fanspeed":1,"continue":1,"waterAmount":1,"DND":1,"mopremind":1,"mopmode":0,"occurrenceTime":"1607249900492"}"}}}}"}}
[EcovacsMQTT_JSON] _handle_command() command onFwBuryPoint received event: {"resultCode":"0","resultCodeMessage":"ok","resultData":{"content":"{"rn":"bd_trigger","d":{"header":{"pri":1,"tzm":480,"ts":"1607249900684","ver":"0.0.1","fwVer":"1.6.3","hwVer":"0.1.1"},"body":{"data":{"d_id":"720852","d_sum":1,"d_seq":0,"d_val":"{"gid":"G1607176517169","index":"0000000178","triggerType":"workcomplete","occurrenceTime":"1607249900492"}"}}}}"}}
[EcovacsMQTT_JSON] _handle_command() command onFwBuryPoint received event: {"resultCode":"0","resultCodeMessage":"ok","resultData":{"content":"{"rn":"bd_trigger","d":{"header":{"pri":1,"tzm":480,"ts":"1607249900685","ver":"0.0.1","fwVer":"1.6.3","hwVer":"0.1.1"},"body":{"data":{"d_id":"720852","d_sum":1,"d_seq":0,"d_val":"{"gid":"G1607176517169","index":"0000000179","triggerType":"workcomplete","occurrenceTime":"1607249900492"}"}}}}"}}
```

**Comment by mrbungle64** [comment]
@benep 

Den Event hätten die eher `logorrhea` nennen sollen :D

**Comment by boriswerner** [comment]
Das sieht echt aus, als ob die vergessen haben die debug Option auszuschalten... :-D 

Ich meinte aber eigentlich ob du die Robotmessage regelmäßig bekommst (die aus dem Screenshot, "reinigen sie regelmäßig ihren Staubbehälter...", den du zum Vergleich nutzen willst)

**Comment by benep** [comment]
> Stattdessen gibt er nur den Fehler 110 aus, wenn die Dustbox nicht eingesetzt ist und man eine Reinigung startet, oder wenn man sie ihm während der Reinigung entnimmt.

Die gibt es überigens zusätzlich noch.

**Comment by mrbungle64** [comment]
> Das sieht echt aus, als ob die vergessen haben die debug Option auszuschalten... :-D

Ja da könntest Du sogar recht haben.
Wir sollten da zumindest mal 1-2 Firmware Updates abwarten, ob das dann noch so drin steckt.

Den Event für die Dustbox kann ich ja "zum Spaß" mal versuchen anhand dieses Events umzusetzen, aber man sollte darauf nicht setzen, dass der Event so bestehen bleibt. Da deutet auch die Bezeichnung `onFwBuryPoint` drauf hin.

**Comment by benep** [comment]
> Ich meinte aber eigentlich ob du die Robotmessage regelmäßig bekommst (die aus dem Screenshot, "reinigen sie regelmäßig ihren Staubbehälter...", den du zum Vergleich nutzen willst)

Achso, ja genau. Im Screenshot `11. Dez 15:00`. Inwischen wieder am `14. Dez 11:03` also nach 3x ca. 70qm saugen.

Dafür habe ich noch kein Event in der JS-App beobachtet.

**Comment by mrbungle64** [comment]
Die Dustbox Auslastung in % wird aktuell nicht umgesetzt (falls überhaupt möglich)
