### ISSUE TITLE
spotArea Buttons mit Raumname

### ISSUE THREAD

**Issue by benep** [mrbungle64/ioBroker.ecovacs-deebot#102]
**Describe the solution you'd like**
Ich finde die spotAreaButton super und arbeite fast nur noch damit. Leider weiß ich in der Objekt-Liste nie welcher Spot welcher Raum ist. Könnte man da beim anlegen nicht den spotAreaName mit in den Namen des Buttons schreiben?

**Deebot model** (please complete the following information):
 Deebot Ozmo T8 TrueDetect

**Comment by mrbungle64** [comment]
@benep 

Unter "map.[MapId].spotAreas.[number].spotAreaName" findest Du den Namen bereits.
Du meinst aber wahrscheinlich die Buttons unter "control", oder?
Dafür könnte ich das noch in die Funktion integrieren, welche die Buttons mit den SpotAreas unter "map" synchronisiert.

**Comment by benep** [comment]
Genau das meine ich. Danke!

**Comment by ds-1982** [comment]
@mrbungle64 

Hallo Sascha, blöde Frage: Was ist der Unterschied zwischen den Buttons spotArea unter control und cleanSpotArea unter Maps? Irgendwie blicke ich da gerade nicht so richtig durch.

**Comment by mrbungle64** [comment]
> @mrbungle64
> 
> Hallo Sascha, blöde Frage: Was ist der Unterschied zwischen den Buttons spotArea unter control und cleanSpotArea unter Maps? Irgendwie blicke ich da gerade nicht so richtig durch.

Hallo Daniel,

das ist eine berechtigte Frage (keine "blöde) ;)

Eigentlich gibt es pro Button von der Funktionalität her betrachtet keinen wirklichen Unterschied.
Die Buttons unter "control" war die ursprüngliche Implementierung - die unter "map" kam später dazu und erstellt diese dann pro Map automatisch (inkl. der korrekten spotAreaID). Die ursprüngliche Implementierung hatte per inzwischen ausgebauter Option in den Einstellungen das einfach von 0 bis zu der gewählten Anzahl hochgezählt und die Buttons erstellt.
Die aktuellere und bessere Variante ist also die unter "map".

In den Einstellungen gibt es allerdings noch die Option "spotArea Buttons im control Kanal synchronisieren".
Wer möchte kann dort einstellen, dass die Buttons von der aktuellen Map damit automatisch "synchronisiert" werden.
Vielleicht hast Du das ja so eingestellt.

Ob man im Endeffekt mit Variante A oder B - oder mit beiden arbeiten möchte, bleibt einem also selbst überlassen.

Das Synchronisieren ist übrigens noch relativ neu. Habe da bisher noch kein Feedback wie gut das funktioniert.
Aber vielleicht kannst Du mir ja nun Feedback geben ;)

**Comment by ds-1982** [comment]
Alles klar :-D Danke für die Infos!

Wie kann ich die Option "spotArea Buttons im control Kanal synchronisieren" testen? Doch nur, ob der Button auch die Area reinigt mit der er bezeichnet ist? Das könnte aber doch auch zufällig richtig sein.

**Comment by mrbungle64** [comment]
> Alles klar :-D Danke für die Infos!
> 
> Wie kann ich die Option "spotArea Buttons im control Kanal synchronisieren" testen? Doch nur, ob der Button auch die Area reinigt mit der er bezeichnet ist? Das könnte aber doch auch zufällig richtig sein.

@ds-1982 
Mir würde es reichen wenn Du das mal aus- und wieder einschalten würdest und dann schaust ob alle SpotAreas aus der aktiven Map mit der richtigen Nummer erscheinen.
Falls Du mehrere Karten benutzt, wäre das natürlich auch interessant, ob der das dann beim Wechsel jeweils korrekt synchronisiert.

**Comment by ds-1982** [comment]
> Mir würde es reichen wenn Du das mal aus- und wieder einschalten würdest und dann schaust ob alle SpotAreas aus der aktiven Map mit der richtigen Nummer erscheinen.
Falls Du mehrere Karten benutzt, wäre das natürlich auch interessant, ob der das dann beim Wechsel jeweils korrekt synchronisiert.

@mrbungle64 
Habe nur eine Karte. Es werden alle SpotAreas korrekt synchronisiert.

**Comment by mrbungle64** [comment]
@benep @ds-1982 

Die Raumnamen werden nun ab der aktuellen GitHub Version in den Namen des Buttons geschrieben, wenn die Option zum Synchonisieren der SpotAreas auf "Voll synchronisieren" steht.

Zusätzlich kann man nun wählen, ob man die Namen in Deutsch oder Englisch haben möchte.

Freue mich über Feedback von Euch :)

**Comment by benep** [comment]
Sehr gut, endlich muss ich mir die Raumnamen nicht mehr merken. Übersetzung klappt auch. 

Für mich wäre das Issue damit abgeschlossen.

**Comment by mrbungle64** [comment]
@benep 

Alles klar. Danke für das Feedback 👍🏻
