### ISSUE TITLE
1.0.7 beta0 - virtualboundaries

### ISSUE THREAD

**Issue by krobipd** [mrbungle64/ioBroker.ecovacs-deebot#105]
hey, wie immer vielen dank für eure mühen und tolle arbeit.

habe entdeckt das immer wieder diese meldung im log steht

> 

(9805) [processVirtualBoundaries] mapID is not a number: undefined
--

**Comment by mrbungle64** [comment]
> hey, wie immer vielen dank für eure mühen und tolle arbeit.
> 
> habe entdeckt das immer wieder diese meldung im log steht
> 
> > 
> 
> ## (9805) [processVirtualBoundaries] mapID is not a number: undefined

Hi @krobipd 

ja, das ist eine Warnung, dass beim Verarbeiten der Events zu den virtual boundaries eine ungültige MapID rein kommt.
Das gehört zu dem neuen Feature, welches aber noch nicht fertig implementiert ist. Das wird noch gefixt.

Wie oft kommt denn die Meldung bei Dir?
Bei mir kommt die aktuell nur bei bestimmten Status-Wechseln (z.B. von cleaning auf stop)

**Comment by mrbungle64** [comment]
@krobipd 

Mit der 1.0.7-beta.1 sollte die Meldung nicht mehr kommen.
Bitte geb mir mal kurz Rückmeldung, ob Du das bestätigen kannst.

**Comment by krobipd** [comment]
Tausend dank ist weg 👍
