### ISSUE TITLE
immer unknown bei "deebotPositionCurrentSpotAreaID"

### ISSUE THREAD

**Issue by hme0354** [mrbungle64/ioBroker.ecovacs-deebot#107]
Adapter Version: 1.0.7-beta.1 von github

hab 2 Deebots:
- Ozmo T8 AIVI
- Ozmo 950

Bei der "deebotPositionCurrentSpotAreaID" wird bei mir immer unknown angezeigt.

**Comment by mrbungle64** [comment]
Hallo @hme0354 

ich vermute mal, dass bei Dir die canvas library noch nicht installiert ist:
https://github.com/mrbungle64/ioBroker.ecovacs-deebot#installation

**Comment by hme0354** [comment]
hatte ich auch nicht, aber macht keinen unterschied

**Comment by mrbungle64** [comment]
> hatte ich auch nicht, aber macht keinen unterschied

@hme0354 
Ich habe gerade mal 2 Geräte gestartet - bei beiden wird die korrekte "deebotPositionCurrentSpotAreaID" angezeigt.

Hattest Du alle Schritte (inkl.) Neustart soweit durchgeführt?

**Comment by hme0354** [comment]
ja, sogar das gerät stromfrei gemacht

**Comment by mrbungle64** [comment]
Welches Betriebsystem (inkl. Version) und Node.js-Version hast Du installiert?

**Comment by hme0354** [comment]
Raspbian GNU/Linux 10
Linux version 5.4.51-V71+ #1333
gcc version 4.9.3
![Info](https://user-images.githubusercontent.com/58149131/101923048-33e75600-3bcf-11eb-8a13-83fe4ad12396.PNG)

**Comment by mrbungle64** [comment]
@hme0354 

ok, mit Node.js 14 habe ich den ioBroker Adapter bzw. die Library noch nicht getestet - fällt mir gerade auf...
Das sollte ich wohl mal tun ;)

Ich hätte aber noch ein paar Fragen:
* Hast Du unter "Weiteres ..." -> "Wert "unknown im Datenpunkt map.deebotPositionCurrentSpotAreaID unterdrücken" angehakt?
* Wird die "map.deebotPosition" korrekt ausgegeben und beim Reinigen aktualisiert?
* Werden unterhalb von "map" und dem Ordner mit der MapID die jeweiligen Ordner für die SpotAreas korrekt erstellt?

**Comment by mrbungle64** [comment]
ok, danke.

Ich installiere gerade eine ioBroker Instanz mit Node.js zum testen. Ich melde mich dann wieder.

**Comment by mrbungle64** [comment]
Die 1.0.7-beta.2 zeigt nun im Datenpunkt "info.canvasModuleIsInstalled" an, ob die Library das Canvas Modul erfolgreich laden konnte. Tu mir doch bitte noch den Gefallen und schaue mal was dort dann ausgegeben wird.

**Comment by hme0354** [comment]
steht auf false

**Comment by mrbungle64** [comment]
> steht auf false

Dann scheint sich da mit Node.js 14 etwas geändert zu haben. Bei meiner neuen Installation mit Node.js 14 ist es nämlich genauso. Bei allen anderen Installationen wird `true` ausgegeben.

Ich werde mich dann jetzt wohl mal schlau machen müssen, was sich da geändert hat...

**Comment by hme0354** [comment]
ich weiß auch nicht wieso ich node.js 14 drauf hab jetzt. bin leider nicht so fit in Linux.

**Comment by mrbungle64** [comment]
@hme0354 
Das Problem war ein anderes (nicht Node.js 14).

Probier mal bitte die 1.0.7-beta.3
Ich habe bei der Library nun canvas als optionale Abhängigkeit aufgenommen - bedeutet: wenn alle Abhängigkeiten für canvas erfüllt sind wird es autom. installiert - ansonsten nicht.
Ich erwarte nun, dass canvas bei Dir mit dem Adapter korrekt mitinstalliert wird - und man sich die manuelle Installation damit sparen kann.

"info.canvasModuleIsInstalled" sollte dann `true` anzeigen und "deebotPositionCurrentSpotAreaID" sollte während der Reinigung kein "unknown" mehr anzeigen, wenn "unknown im Datenpunkt map.deebotPositionCurrentSpotAreaID unterdrücken" angehakt ist. Der Haken ist optional - falls Du das nicht anhakst wird der trotzdem manchmal noch "unknown" anzeigen, wenn der Roboter sich an der Grenze zwischen 2 SpotAreas befindet und es nicht eindeutig ist, welche jetzt die "richtige" ist. In dem anderen Fall wechselt der den Wert einfach nicht, so lange die SpotArea nicht eindeutig gewechselt hat.
Das ist eher Geschmackssache was man da für sich als das bessere Verhalten ansieht.

**Comment by hme0354** [comment]
funktioniert perfekt
