### ISSUE TITLE
Mistory Maps

### ISSUE THREAD

**Issue by benep** [mrbungle64/ioBroker.ecovacs-deebot#108]
**Adapter version and source** (please complete the following information):
1.0.8-alpha.1 (0.5.2-alpha.0)

**Deebot model** (please complete the following information):
T8 TrueDetect

**Describe the bug**
Leider werden bei mir immer mehr Maps angezeigt, die ich nicht angelegt habe und vieles schwieriger machen (Rote Pfeile). Diese werden in der MobileApp nicht angezeigt. Auch wenn ich Multi-Map akiviert habe, benutze ich nur eine Map (Grüner Pfeil). Multi-Map ist aktiviert, weil der Roboter ab und an die Map "verliert". Dann wird nur ein neues Geschoss gestartet und man verliert sein haupt App nicht.

Auch wenn die in der MobileApp nicht sichtbar sind, stehen sie hier auf `mapIsAvailable = true` (Orange Pfeile).

Die Maps 0 und 18xxx sind schon länger da. Die "undefined" erst seit einem der letzten Updates. Die 0 bin ich mir nicht sicher.

Leider werden of die virtualBoundaries gelöscht und wieder eigefügt.

![1](https://user-images.githubusercontent.com/237102/102014561-e3026980-3d56-11eb-86ac-f52bfbdbba50.png)

**Comment by mrbungle64** [comment]
@benep 

Bitte lösche mal alle Maps die nicht aktuell bzw. gültig sind. Ich habe da gerade in den letzten Tagen versucht solche "mistery" Maps abzufangen.

Alles was danach noch auftaucht melde uns dann hier bitte.

**Comment by benep** [comment]
Ok, gemacht und wird beobachtet.

**Comment by benep** [comment]
Also die Maps 0 und 18xxx oben aus dem Screenshot sind leider gerade beim Start eines CustomAreaCleans wieder entstanden.

**Comment by mrbungle64** [comment]
> Also die Maps 0 und 18xxx oben aus dem Screenshot sind leider gerade beim Start eines CustomAreaCleans wieder entstanden.

Ist das auch wieder wie im Screenshot, das im Channel "0" auch der Channel "virtualBoundaries" vorhanden ist - beim Channel "18xxx" aber nicht?

**Comment by benep** [comment]
> Ist das auch wieder wie im Screenshot, dass im Channel "0" auch der Channel "virtualBoundaries" vorhanden ist - beim Channel "18xxx" aber nicht?

Ja, genau.

**Comment by mrbungle64** [comment]
@benep 
Spontan würde ich zu der "18xxx" Map sagen, dass das grundsätzlich damit zusammenhängt, dass Du Multimap angeschaltet hast und da wohl mal was "hängengeblieben" ist auf Ecovacs Seite, was vorher mal angelegt war.

Die Map "0" ist ganz klar ein Fehlverhalten - das müssen wir dann mal genauer untersuchen. Ich persönlich hatte bisher beim Ozmo 920 (auch ein 950er basiertes Gerät) noch keine Map mit der ID "0".
Nur "null" und "undefined" (wie bei Dir) - beides sollte jetzt aber nicht mehr auftreten.

@boriswerner 
Hast Du zu den Maps "0" und "18xxx" eine Idee oder eine Erklärung?

**Comment by boriswerner** [comment]
Ich habe bei mir im iobroker insgesamt 3 maps. Die beiden, die in der App auch angezeigt wird und dann gibt es immer noch eine "temporäre" Map. Die wird erstellt, wenn der Bot eine neue Umgebung erkennt und man den Bot aber nicht zurück zur Ladestation fahren lässt. Ich habe so meinen dritten Wohnbereich mit abgedeckt, der nur aus einem Raum besteht und daher dort auch keine spotAreas benötigt werden. Man kann aber trotzdem (auch in der App, wenn er die Karte gerade benutzt) virtualBoundaries erstellen.
Zu den Maps 0 und undefined kann ich mir höchstens vorstellen, dass das passiert, wenn man die Karte neu erstellt. 
@benep wie gehst du denn generell vor bzw. wie äußert es sich, wenn er "die Karte verliert"? Du meinst nur, dass er die aktuelle Position nicht in deiner Hauptkarte vermutet und dann eine neue Kartierung startet, oder? Dann passt das zu meiner Vermutung, dass die 18xx die temporäre Karte sein könnte.
Es gibt noch ein flag in den Karteninfos, der im Moment nicht ausgegeben wird (isBuilt). Der zeig an, ob es sich um eine der beiden in der App auch bearbeitbaren Karten handelt. Das könnte ich mal einbauen.

Zum Thema
"Leider werden of die virtualBoundaries gelöscht und wieder eigefügt."
Das feature steckt gerade noch in der Entwicklung. Es ist im Moment so, dass eigentlich nur die boundaries gelöscht werden sollten, die nicht mehr vorhanden sind. Wie verhält es sich bei dir genau? Wird der gesamte Ordner gelöscht? Dann aber auch wieder neu erstellt?

Zur map mit ID 0 wäre ein detaillierteres Debugging der Messages mit der js-App in der library gut. Auf welcher Platform (linux?) betreibst du den iobroker und bist du ein wenig mit der Kommandozeile vertraut? Dann würde die Tage ich eine App mit den notwendigen Befehlen zusammenstellen.

**Comment by benep** [comment]
> wie äußert es sich, wenn er "die Karte verliert"? Du meinst nur, dass er die aktuelle Position nicht in deiner Hauptkarte vermutet und dann eine neue Kartierung startet, oder? 

Ja das passiert am häufigsten, wie du beschreibst. Das letzte Softwareupdate hat bei vielen aber während des Updates den Unbekannte-Umgebung-Mechanismus ausgelöst und dabei die Hauptmap komplett gelöscht, wenn sie Multimap aus hatten.

> Dann passt das zu meiner Vermutung, dass die 18xx die temporäre Karte sein könnte.

Das ist schwer genau zu sagen. Allerdings haben sowohl die 0 als auch die 18xx alle Räume der Hauptmap. Die virtualBoundaries sind nur in der 0 vorhanden, aber exakt die gleichen, wie die Hauptmap.
Eine null Map ist inzwischen auch wieder vorhanden und hat nur teilweise Räume und virtualBoundaries, aber dann exakt wie in der Hauptmap.
Ich habe gerade eine Reinigung an einem Punkt gestartet, ab dem sich der Roboter nicht orientieren kann, also eine neue Map startet. Bei `map.currentMapIndex` wird dann 0 angezeigt.

> Es gibt noch ein flag in den Karteninfos, der im Moment nicht ausgegeben wird (isBuilt). Der zeig an, ob es sich um eine der beiden in der App auch bearbeitbaren Karten handelt. Das könnte ich mal einbauen.

Wenn das geht, könnte man das ja auch vielleicht in der Konfiguration nutzen. À la "Show only isBuilt maps" true|false.

> Das feature steckt gerade noch in der Entwicklung. Es ist im Moment so, dass eigentlich nur die boundaries gelöscht werden sollten, die nicht mehr vorhanden sind. Wie verhält es sich bei dir genau? Wird der gesamte Ordner gelöscht? Dann aber auch wieder neu erstellt?

Ja, genau. Hatte das grade wieder bei einer Ortung.

> Zur map mit ID 0 wäre ein detaillierteres Debugging der Messages mit der js-App in der library gut.

Hab ein Raspbian am laufen und hab das mit der JS-App letztens schon mit mrbungle gemacht. Wenn ich dir da helfen kann also gerne.

**Comment by boriswerner** [comment]
@benep ich melde mich spätestens am Wochenende nochmal zum Debugging, muss ich mir vorher nochmal im Code und in den API messages genauer ansehen.
Komisch ist, dass die 0-map auch Räume hat (du meinst spotArea Datenpunkte, richtig?)
Was ich mir vorstellen könnte ist, dass das die Standard-Map ID ist, wenn man MultiMap deaktiviert hat. Ich habe gleich von Beginn an die MultiMap Funktion aktiviert und daher keine Karte im anderen Modus erstellen lassen.
currentMapIndex ist aber etwas anderes als currentMapID. Der mapIndex der einzelnen Maps wird derzeit nicht als state angezeigt, weiß ich garnicht, warum ich das für die currentMap eingebaut hab.
currentMapIndex=0 müsste aber dann eine der bekannten sein (bei mir zeigt er auch gerade currentMapIndex=0 and und in currentMapID 1260001067, welches meiner Karte vom Erdgeschoss entspricht). Was zeigt er denn in dem state an, wenn er in einem unbekannten Bereich fährt?

Dass die Boundaries komplett gelöscht werden wundert mich ein wenig. Aber da werkeln wir wie gesagt gerade noch ziemlich dran herum und haben auch noch nicht alles durchgetestet (bei den Boundaries verhält sich die API auch etwas komisch ;-)

**Comment by mrbungle64** [comment]
@benep @boriswerner 

Wie ist denn hier nun der Stand?

**Comment by Snago636** [comment]
@mrbungle64 

Also ich hatte die selben Probleme auch. Null und undefined Map. Ich weiß nicht seit wann es weg ist. Aber bei mir tauchen die auch nicht mehr auf.

**Comment by mrbungle64** [comment]
> @mrbungle64
> 
> Also ich hatte die selben Probleme auch. Null und undefined Map. Ich weiß nicht seit wann es weg ist. Aber bei mir tauchen die auch nicht mehr auf.

@Snago636 
Das freut mich! Danke für die Info 👍🏻

**Comment by mrbungle64** [comment]
Ich schließe den Issue jetzt mal.
Falls solche Ordner mit einer aktuellen Version wieder auftauchen sollten können wir den ja wieder öffnen.

**Comment by benep** [comment]
Gerade mit 1.2.0-alpha.5 getestet. Leider immer noch. Ich habe die falschen existierenden frisch gelöscht. Dann mache ich ein Relocate und schon sind sie wieder da.
Ein Map 0 und eine mit 10stelliger Zahl. Beide haben alle meine Räume.
