### ISSUE TITLE
Pause before/when Event

### ISSUE THREAD

**Issue by benep** [mrbungle64/ioBroker.ecovacs-deebot#109]
Followup von [#100](https://github.com/mrbungle64/ioBroker.ecovacs-deebot/issues/100#issuecomment-744012866): 

Die Funktion finde ich schon spannen. Vor allem wenn man noch dabei ist alles Einzurichten. Leider konnte ich sie nicht zum Laufen bekommen. 

Ich hab die Werte auf true gesetzt und einen SpotClean ausgelöst. `map.deebotPositionCurrentSpotAreaID` wird richtig ausgefüllt, aber von der Pause habe ich nichts gemerkt. Wie lange ist die denn, kann man die übersehen/überhören?

Vielleicht könnte man das um einen Sound (Bsp. 17:Beep) erweitern oder neue Objekte dafür ergänzen. Ich würde tatsächlich einen kurzen Beep dauerhaft aktiviert lassen, eine Pause nur temporär.

**Comment by mrbungle64** [comment]
> Followup von [#100](https://github.com/mrbungle64/ioBroker.ecovacs-deebot/issues/100#issuecomment-744012866):
> 
> Die Funktion finde ich schon spannen. Vor allem wenn man noch dabei ist alles Einzurichten. Leider konnte ich sie nicht zum Laufen bekommen.
> Ich hab die Werte auf true gesetzt und einen SpotClean ausgelöst. `map.deebotPositionCurrentSpotAreaID` wird richtig ausgefüllt, aber von der Pause habe ich nichts gemerkt. 

@benep 

Was hast Du genau gemacht bzw. erwartet?
Bei den "when" Events musst Du die SpotArea Nummer eintragen - nur bei der "pauseBeforeDockingChargingStation" ist es ein boolean (`true`/`false`).

>  Wie lange ist die denn, kann man die übersehen/überhören?

Der führt dann wirklich den "Pause" Befehl aus. Also dauerhaft - so lange nichts anderes ausgeführt wird.

> 
> Vielleicht könnte man das um einen Sound (Bsp. 17:Beep) erweitern oder neue Objekte dafür ergänzen. Ich würde tatsächlich einen kurzen Beep dauerhaft aktiviert lassen, eine Pause nur temporär.

Hmm, das habe ich noch nicht richtig verstanden worauf Du hinaus möchtest, sorry ;)

**Comment by benep** [comment]
Ah OK, ich dachte es wird zwischen zwei Spots 1-2 Sekunden pausiert, wenn mehrere Spots gereinigt werden. Eigentlich hast du das auch gut im Objekt-Namen gut beschrieben, aber ich habs überlesen. Maximal könnte man vielleicht noch erwähnen dass es einmalig ist.

So hat das jetzt funktioniert. Allerdings hat er auch pausiert, wenn er an einer Türschwelle beim Umranden zu weit in den nächsten Spot fährt.
`pauseBeforeDockingChargingStation` bekomme ich nicht zum laufen. Ich mache: Setezn auf `true`, starten customArea, warten. Er fährt dannach zum Dock und startet zu laden.

Mein Usecase ist, dass ich grade viel zuhause bin und damit der Sauger unterwegs ist, wenn ich arbeite. Wenn er jetzt im Gang fertig ist und ins Schlafzimmer fährt, würde ich gerne die Tür zu machen, damit ich meine Ruhe habe. Ich merke aber oft nicht wenn er in den nächsten Raum fährt. Ich dachte du adressierst das Problem. Dann wäre aber ein Beep wenn er Spot/Raum wechselt super.

**Comment by mrbungle64** [comment]
> Ah OK, ich dachte es wird zwischen zwei Spots 1-2 Sekunden pausiert, wenn mehrere Spots gereinigt werden. Eigentlich hast du das auch gut im Objekt-Namen gut beschrieben, aber ich habs überlesen. Maximal könnte man vielleicht noch erwähnen dass es einmalig ist
> 
> So hat das jetzt funktioniert.

ok gut 👍🏻 

> Allerdings hat er auch pausiert, wenn er an einer Türschwelle beim Umranden zu weit in den nächsten Spot fährt.

Ja das kann leider passieren...
Evtl. kann ich das noch einbauen, dass das erst nach ein paar wiederholten Events ausgeführt wird. Ob das dann viel besser wird müsste man dann in der Praxis schauen. Ich werde mir noch mal Gedanken dazu machen.

> `pauseBeforeDockingChargingStation` bekomme ich nicht zum laufen. Ich mache: Setezn auf `true`, starten customArea, warten. Er fährt dannach zum Dock und startet zu laden.

Bei mir hat der jetzt mehrfach direkt vor Ladestation halt gemacht - eben war das sogar so knapp, dass ich dann vergessen hatte dass der dort angehalten hatte und dachte dass der schon die ganze Zeit lädt ;)
Ich werde da den Radius größer machen (ggf. auch einstellbar) dann klappt es hoffentlich auch bei Dir dann.

> 
> Mein Usecase ist, dass ich grade viel zuhause bin und damit der Sauger unterwegs ist, wenn ich arbeite. Wenn er jetzt im Gang fertig ist und ins Schlafzimmer fährt, würde ich gerne die Tür zu machen, damit ich meine Ruhe habe. Ich merke aber oft nicht wenn er in den nächsten Raum fährt. Ich dachte du adressierst das Problem. Dann wäre aber ein Beep wenn er Spot/Raum wechselt super.

ok, danke für die Erklärung. Ich mache mir mal Gedanken dazu, ob ich für diesen Use Case auch was einbauen kann, was dann auch in der Praxis funktionieren kann. Ich denke das Problem haben aktuell noch mehr User (inkl. mir selbst)

**Comment by mrbungle64** [comment]
@benep 

> pauseBeforeDockingChargingStation bekomme ich nicht zum laufen. Ich mache: Setezn auf true, starten customArea, warten. Er fährt dannach zum Dock und startet zu laden.

Ich habe in der 1.0.8-alpha.2 den Radius ein bisschen vergrößert. Du kannst ja bei Gelegenheit mal testen, ob er damit nun vor der Ladestation rechtzeitig halt macht ;)

**Comment by mrbungle64** [comment]
@benep 

> Ich habe in der 1.0.8-alpha.2 den Radius ein bisschen vergrößert. Du kannst ja bei Gelegenheit mal testen, ob er damit nun bei Dir rechtzeitig vor der Ladestation halt macht ;)

Hattest Du schon mal die Gelegenheit das zu testen?

**Comment by benep** [comment]
@mrbungle64 

Leider klappt das nun (1.0.9-alpha.0 (0.5.2)) überhaupt nicht mehr. Weder vorm Laden, noch beim Spotwechsel, der schon mal funktioniert hat. Geht das nur in einem bestimmten Reinigungsmodus?

**Comment by mrbungle64** [comment]
@benep 

Ich habe gerade noch mal alle 3 Funktionen getestet - dabei hat alles wie erwartet funktoniert.
Eigentlich sollte es mit jedem Reinigungsmodus Modus gehen welcher die gesetzten Spot Areas einschließt.
Auch das Pausieren vor dem Laden sollte immer funktionieren (so lange der beim Zurückfahren den Status "returning" hat)

Kannst Du mal bitte kurz beschreiben in welcher Reihenfolge Du das ausgeführt hast?

**Comment by mrbungle64** [comment]
@benep 

Was noch zu bedenken ist:

Am Wochenende gab es ja mehrere Ausälle bei den Ecovacs Servern.
Das scheint zwar weitgehend wieder zu funktionieren - aber evtl. noch nicht 100% stabil:
https://www.roboter-forum.com/index.php?thread/48649-ecovacs-server-sind-down-26-12-27-12-2020/&pageNo=7

**Comment by benep** [comment]
Also ich stell den Roboter 2 Meter vor die Ladestation. Orte ihn. Stelle `control.pauseBeforeDockingChargingStation` auf `true`. Klicke `control.charge`. Er fährt los, dockt und sagt "Begin des Ladevorgangs".

Roboter läd im Wohnzimmer. Ich stelle `control.pauseWhenEnteringSpotArea` auf 2 (Gang) und `control.pauseWhenLeavingSpotArea` auf 0 (Wohnzimmer). Dann klicke ich `control.spotArea_2`. Er fährt los und saugt den Gang.

Die Goto-Funktion läuft ohne Probleme, auch mit mehrfach hin und her schicken. Deshalb dürfte es nicht an dem Serverproblem liegen.

**Comment by mrbungle64** [comment]
@benep 

In welcher Frequenz ändert sich denn die Position ("map.deebotPosition") bei Dir?
Beim OZMO 920 passiert das i.d.R. jede Sekunde - manchmal sind es auch 2 Sekunden.
Je seltener das aktualisiert wird desto unzuverlässiger wird es dann ja auch.

**Comment by benep** [comment]
Das passiert auch so alle 1-2 Sekunden.

**Comment by mrbungle64** [comment]
> Das passiert auch so alle 1-2 Sekunden.

ok, ich schaue mir nachher noch mal den Code an, ob es da noch "Schlupflöcher" gibt ;)

Btw: Stimmt bei Dir die Angabe in dem Datenpunkt "map.deebotDistanceToChargePosition" so auf ca. 10-20 Zentimeter genau?

**Comment by mrbungle64** [comment]
@benep 

Schau doch mal bitte, ob jeweils der entsprechende Eintrag im Log auftaucht, wenn Du das in die Datenpunkte einträgst.

- "Pause when entering spotArea [spotAreaNumber]"
- "Pause when leaving spotArea [spotAreaNumber]"
- "Pause before docking onto charging station"

Ansonsten wäre die Eintellung "Wert unknown im Datenpunkt map.deebotPositionCurrentSpotAreaID unterdrücken" in dem Zusammenhang interessant. Je nach dem ob bei Dir öfter noch "unknown" als deebotPositionCurrentSpotAreaID gesetzt ist oder gesetzt werden würde.
Beim Spotwechsel muss sich "deebotPositionCurrentSpotAreaID" natürlich auch entsprechend ändern.
Ich denke mal, dass Du das schon berücksichtigt hast - aber ich wollte es trotzdem noch mal anmerken. Manchmal geht es dann doch unter beim testen oder auch in der Praxis.

**Comment by benep** [comment]
Also ich bekomme schon beim Setzen folgende Warnings:

```
Unhandled control state: pauseBeforeDockingChargingStation - ecovacs-deebot.0.control.pauseBeforeDockingChargingStation
Unhandled control state: pauseWhenLeavingSpotArea - ecovacs-deebot.0.control.pauseWhenLeavingSpotArea
Unhandled control state: pauseWhenEnteringSpotArea - ecovacs-deebot.0.control.pauseWhenEnteringSpotArea
```

`deebotPositionCurrentSpotAreaID` und `deebotPositionCurrentSpotAreaName` werden beim Raumwechsel korrekt und in 1-2 Sekunden geändert.

Das Unterdrücken hatte ich auch probiert, hat aber nichts geholfen.

**Comment by mrbungle64** [comment]
@benep 

Setzt Du die Haken bzw. Werte mit Bestätigt bzw `ack=true`?
Probier mal bitte ohne ... Da muss ich wohl noch was fixen, dass das in beiden Fällen funktioniert.

**Comment by benep** [comment]
Wenn ich im Dialog den Haken "Bestätigt" setze, dann bekomm ich die Fehlermeldung nicht. Es funktioniert aber trotzdem nicht. Habe es auch nochmal ohne Haken versucht. Dann gibts die Fehlermeldung `Unhandled control state: pauseBeforeDockingChargingStation - ecovacs-deebot.0.control.pauseBeforeDockingChargingStation` und es funktioniert auch nicht.

**Comment by mrbungle64** [comment]
@benep 

ok, irgendwie ist das komisch... Kannst Du bitte mal die 1.0.8 aus dem Latest Repo installieren?
Das geht am schnellsten mit dem "+"-Symbol im "Expertenmodus" unter "Adapter".

**Comment by mrbungle64** [comment]
@benep 

Kann es sein, dass Du das hier überlesen hattest ;)
https://github.com/mrbungle64/ioBroker.ecovacs-deebot/issues/100#issuecomment-748594511

**Comment by benep** [comment]
> Kann es sein, dass Du das hier überlesen hattest ;)

Oh nein. Ja, das hab ich übergesehen. Hab die alten gleich gelöscht. Ich hoffe das betrifft die Nicht-Beta-Tester nicht.

Ich bin jetzt nach wie vor bei `1.0.9-alpha.0 (0.5.2)`. In den Logs wird das Einstellen korrekt bestätigt, wenn ich ack nicht auswähle.  Pause when entering/leaving funktioniert dann auch wieder, wie bei den 1.0.8-alphas. Die PauseBeforeDocking geht trotz Bestätigung der Einstellung in den Logs nicht. Er fährt an die Station und sagt "Beginn des Ladevorgangs", läd also definitiv.

Auch das war in der 1.0.8-alpha so. Es macht also mMn keine Sinn das mit der 1.0.8 zu testen, oder?

**Comment by mrbungle64** [comment]
> > Kann es sein, dass Du das hier überlesen hattest ;)
> 
> Oh nein. Ja, das hab ich übersehen. Hab die alten gleich gelöscht. Ich hoffe das betrifft die Nicht-Beta-Tester nicht.
> 
> Ich bin jetzt nach wie vor bei `1.0.9-alpha.0 (0.5.2)`. In den Logs wird das Einstellen korrekt bestätigt, wenn ich ack nicht auswähle. Pause when entering/leaving funktioniert dann auch wieder, wie bei den 1.0.8-alphas. Die PauseBeforeDocking geht trotz Bestätigung der Einstellung in den Logs nicht. Er fährt an die Station und sagt "Beginn des Ladevorgangs", läd also definitiv.
> 
> Auch das war in der 1.0.8-alpha so. Es macht also mMn keine Sinn das mit der 1.0.8 zu testen, oder?

Nein, die 1.0.8 brauchst Du jetzt nicht mehr installieren. Zu dem Zeitpunkt als ich das vorgeschlagen hatte, hatte ich die Vermutung dass etwas mit der Installation nicht stimmt.

Hattest Du mal geschaut, ob die Angabe im Datenpunkt "map.deebotDistanceToChargePosition" relativ genau ist?
Evtl. muss man die Entfernung beim T8 anders umrechnen als bei meinen Geräten.
1 Meter sollte recht genau 1000 Einheiten/Punkten bei den Koordinaten entsprechen.

**Comment by benep** [comment]
`map.deebotDistanceToChargePosition` ist recht genau. 1m = 1000 Einheiten stimt auch. Ich hab den Roboter jetzt einaml rückwärts fahren lassen, Dann steht in `map.deebotDistanceToChargePosition = 0,7 m`. Wenn ich dann von der senkrechten Wand der Ladestation bis zum Roboter messe, komme ich auch ca. 77cm.

**Comment by mrbungle64** [comment]
> `map.deebotDistanceToChargePosition` ist recht genau. 1m = 1000 Einheiten stimt auch. Ich hab den Roboter jetzt einmal rückwärts fahren lassen, Dann steht in `map.deebotDistanceToChargePosition = 0,7 m`. Wenn ich dann von der senkrechten Wand der Ladestation bis zur Spitze des Roboters messe, komme ich auf ca. 77cm, bis Mitte Turm 88cm und bis Mitte des Roboters 95cm.

@benep 
Vielen Dank für die Rückmeldung und das Nachmessen 👍🏻 
Dann scheint das Problem wo anders zu liegen - muss ich wohl mal weiter suchen, wo das Problem versteckt ist ;)

**Comment by mrbungle64** [comment]
@benep 

Kann es sein, dass der T8 beim "info.chargestatus" nicht auf "returning" geht, wenn der zur Ladestation zurückkehrt?
Das würde es erklären...

Falls das so sein sollte: geht "status.device" auf "returning", wenn der zur Ladestation zurückkehrt?

**Comment by benep** [comment]
Es gehen alle drei auf `returning`
```
info.chargestatus
info.cleanstatus
status.device
```
Aber beim Wegfahren von der Station gehen beide `info.*` auf `idle`, aber `status.device` bleibt auf `charging` und ich bekomme das Warning `Unhandled cleanstatus: undefined`

**Comment by mrbungle64** [comment]
> Es gehen alle drei auf `returning`
> 
> ```
> info.chargestatus
> info.cleanstatus
> status.device
> ```
> 
> Aber beim Wegfahren von der Station gehen beide `info.*` auf `idle`, aber `status.device` bleibt auf `charging` und ich bekomme das Warning `Unhandled cleanstatus: undefined`

@benep 

Ich dachte dass "info.cleanstatus" nun funktioniert ... siehe [hier](https://github.com/mrbungle64/ioBroker.ecovacs-deebot/issues/99#issuecomment-739549461)

Hatte sich das zwischendurch wieder geändert oder hatte ich das falsch verstanden?

**Comment by benep** [comment]
`info.cleanstatus `springt auch instant auf `idle`, aber `status.device `bleibt auf `charging `.

**Comment by mrbungle64** [comment]
@benep 

In der aktuellen Version von GitHub ist eine Einstellung unter "Weiteres" dazu gekommen:
* Größe des Bereichs für "pauseBeforeDockingChargingStation" (experimentell)

Stell die doch bitte mal auf "2000 x 2000". Bisher waren das hard-codiert "500 x 500".

**Comment by mrbungle64** [comment]
@benep 

Hast Du es mal probiert, ob es damit funktioniert?

**Comment by mrbungle64** [comment]
> Es gehen alle drei auf `returning`
> 
> ```
> info.chargestatus
> info.cleanstatus
> status.device
> ```
> 
> Aber beim Wegfahren von der Station gehen beide `info.*` auf `idle`, aber `status.device` bleibt auf `charging` und ich bekomme das Warning `Unhandled cleanstatus: undefined`

Hallo @benep,

kannst Du mal bitte Version 1.0.12-alpha.0 (oder ggf. neuer) von GitHub ausprobieren?
Ich denke, dass ich das Problem gefunden habe ...

**Comment by benep** [comment]
Der Roboter bleibt leider immer noch nicht stehen, auch bei 1x1m nicht. Aber ich konnte beobachten, dass der Wert von `control.extended.pauseBeforeDockingChargingStation` von true auf false geändert wird, immer genau wenn er in den Bereich rein fährt.

**Comment by mrbungle64** [comment]
> Der Roboter bleibt leider immer noch nicht stehen, auch bei 1x1m nicht. Aber ich konnte beobachten, dass der Wert von `control.extended.pauseBeforeDockingChargingStation` von true auf false geändert wird, immer genau wenn er in den Bereich rein fährt.

Danke für die Info - dann wird der Bereich auch erkannt, aber der "pause" Befehl nicht (korrekt) ausgelöst...
Hängt vielleicht auch damit zusammen, dass die Status beim T8 noch nicht in allen Fällen sauber gesetzt werden ...
Es bleibt spannend 😉

**Comment by mrbungle64** [comment]
> > Es gehen alle drei auf `returning`
> > ```
> > info.chargestatus
> > info.cleanstatus
> > status.device
> > ```
> > 
> > 
> > Aber beim Wegfahren von der Station gehen beide `info.*` auf `idle`, aber `status.device` bleibt auf `charging` und ich bekomme das Warning `Unhandled cleanstatus: undefined`
> 
> Hallo @benep,
> 
> kannst Du mal bitte Version 1.0.12-alpha.0 (oder ggf. neuer) von GitHub ausprobieren?
> Ich denke, dass ich das Problem gefunden habe ...

Hallo @benep 

hattest Du mal geschaut, ob die Status mit der 1.0.12 nun passen?

**Comment by mrbungle64** [comment]
Hallo @benep 

> hattest Du mal geschaut, ob die Status mit der 1.0.12 nun passen?

wäre cool, wenn Du mal kurz zu den Status Rückmeldung geben könnest 😉
