### ISSUE TITLE
resume command missing

### ISSUE THREAD

**Issue by B0F1B0** [mrbungle64/ioBroker.ecovacs-deebot#11]
**`clean --> pause --> clean != clean --> pause --> "resume"`**

Hi, ich teste gerade die Commands mit dem deebot Ozmo 950 in IObroker ( 0.3.9 )

Wenn ich auf Clean drücke, beginnt die Reinigung. Wenn ich auf Pause drücke hält der Robot auch an. Wenn ich dann aber wieder auf Clean drücke beginnt die Reinigung von vorne. Der Robot hat quasi den "Faden" verloren. 

Wenn ich, nach dem ich auf Pause gedrückt habe in der "Android App" auf "Play" klicke macht der Robot weiter und hat nicht den "Faden" verloren.

Es fehlt somit ein "Resume / Play" Command. 

zur Info: die Lade-Station findet der Robot auch wenn er den "Faden" verloren hat.

""THERE WE HAVE THE SALAD""

B0F1B0

**Comment by mrbungle64** [comment]
Hi @B0F1B0 

daran hatte ich gestern auch schon mal gedacht.

Das Kommando selbst wurde in den letzten Tage grundsätzlich schon mal in die Library eingebaut - sollte also nicht mehr allzu lange dauern bis es im Adapter landet :)

**Comment by sync85** [comment]
auch wenn anderes Thema hoffe ich es ist ok das ich hier kurz frage für den Deebot Ozmo 950.
Und zwar versteh ich das mit den spot areas nicht. Ich lese immer etwas von 0-9 sei valid und in der Ecovacs app zu finden. Allerdings wenn ich in der App schaue hab ich nur buchstaben für die Bereiche.
Ich versuche halt meine Bereiche die ich per app leicht starten kann über alexa anzustoßen: zum Beispiel. Alexa saug die Küche (wäre dann als Beispiel Bereich F). Nur wie geb ich das an wenn ich nur zahlen von 0-9 nutzen kann. Hatte schonmal mit den Zahlen rumgetestet aber da verhält sich der Bot recht seltsam. Zbs bei 1 fährt er aus der station dreht den Sauger auf und bleibt so stehen?! Oder einmal mit F versucht, startet er sogar aber saugt dann anscheinend das Wohnzimmer.

Alles etwas sehr seltsam. Hoffe mir kann jemand helfen und ich störe nicht mit meiner Frage hier.

**Comment by mrbungle64** [comment]
> vorweg, ich find es genial wie aktiv an dem Adapter gearbeitet wird und hoffe meine Frage ist ok :)
> 
> auch wenn anderes Thema hoffe ich es ist ok das ich hier kurz frage für den Deebot Ozmo 950.
> Und zwar versteh ich das mit den spot areas nicht. Ich lese immer etwas von 0-9 sei valid und in der Ecovacs app zu finden. Allerdings wenn ich in der App schaue hab ich nur buchstaben für die Bereiche.
> Ich versuche halt meine Bereiche die ich per app leicht starten kann über alexa anzustoßen: zum Beispiel. Alexa saug die Küche (wäre dann als Beispiel Bereich F). Nur wie geb ich das an wenn ich nur zahlen von 0-9 nutzen kann. Hatte schonmal mit den Zahlen rumgetestet aber da verhält sich der Bot recht seltsam. Zbs bei 1 fährt er aus der station dreht den Sauger auf und bleibt so stehen?! Oder einmal mit F versucht, startet er sogar aber saugt dann anscheinend das Wohnzimmer.
> 
> Alles etwas sehr seltsam. Hoffe mir kann jemand helfen und ich störe nicht mit meiner Frage hier.

Hallo @sync85,

wir beantworten gerne Deine Fragen, aber bitte erstelle dafür einen neuen Issue, da das mit 'resume command missing' nicht mehr viel zu tun hat :)

**Comment by sync85** [comment]
hallo @mrbungle64 
habe ich soeben getan, hoffe ist richtig so :)

**Comment by boriswerner** [comment]
@B0F1B0 die neueste Version hier auf GitHub unterstützt nun u.a. auch das resume für den 950.
Du darfst sehr gerne testen wenn du magst :-)

**Comment by B0F1B0** [comment]
Die neue Version (0.5.2) läuft wie geschmiert.... :-)

resume command funktioniert sehr gut.
