### ISSUE TITLE
Übersetzung der Raumnamen

### ISSUE THREAD

**Issue by Snago636** [mrbungle64/ioBroker.ecovacs-deebot#110]
Hallo,
erstmal wollte ich sagen das ich dieses Projekt hier Spitze finde. Ich nutze es schon sehr lange und bin begeistert. Ich hab ein Ozmo 950.
Hatte mir mal ein Script gebastelt welches die Raumnamen übersetzt, damit ich immer sehen kann in welchem Raum er gerade ist. Hab es dann aber gelöscht weil ich gesehen habe das es eingebaut wurde und auch funktioniert hat. Aber seit einiger Zeit funktioniert dies nicht mehr. Leider weiß ich auch nicht bei welcher Version es bei mir funktioniert hatte. Ich installiere eigentlich immer die neuesten Alpha und Beta Versionen von Github wegen der neuen Funktionen.
Kann mir jemand sagen ob es an falschen Einstellungen oder so liegt oder ob es wieder deaktiviert wurde? Als Ländercode habe ich natürlich Germany ausgewählt.

gruß Andy

**Comment by mrbungle64** [comment]
@Snago636 
> Hallo,
> erstmal wollte ich sagen das ich dieses Projekt hier Spitze finde. Ich nutze es schon sehr lange und bin begeistert. Ich hab ein Ozmo 950.

Hallo Andy, danke für das Feedback 👍🏻 

> Hatte mir mal ein Script gebastelt welches die Raumnamen übersetzt, damit ich immer sehen kann in welchem Raum er gerade ist.

Was meinst Du damit genau? Dass der Datenpunkte "map.xxxxxxxxx.spotAreas.x.spotAreaName" den Namen des Raums als Wert hat oder dass die auch direkt in Deutsch übersetzt werden?

> Hab es dann aber gelöscht weil ich gesehen habe das es eingebaut wurde und auch funktioniert hat. Aber seit einiger Zeit funktioniert dies nicht mehr. Leider weiß ich auch nicht bei welcher Version es bei mir funktioniert hatte. Ich installiere eigentlich immer die neuesten Alpha und Beta Versionen von Github wegen der neuen Funktionen.

Wenn Du das immer von GitHub installierst besteht natürlich die Gefahr, dass da mal eine "faule" Version dabei sein kann, weil die nicht für den "Endbenutzer" freigegeben sind. Die sollten eigentlich nur in Absprache oder auf Empfehlung des Entwicklers installiert werden, wenn z.B. ein Bug gefixt wurde von dem man betroffen ist oder ein Feature was man sich gewünscht hat getestet werden muss.
Im Latest Repo sind die freigegebenen Beta Versionen. Die sind schon besser getestet und eben auch freigeben. 

> Kann mir jemand sagen ob es an falschen Einstellungen oder so liegt oder ob es wieder deaktiviert wurde? Als Ländercode habe ich natürlich Germany ausgewählt.
> 
> gruß Andy

**Comment by Snago636** [comment]
> Was meinst Du damit genau? Dass der Datenpunkte "map.xxxxxxxxx.spotAreas.x.spotAreaName" den Namen des Raums als Wert hat oder dass die auch direkt in Deutsch übersetzt werden?

In dem Datenpunkt "map.xxxxxxxxx.spotAreas.x.spotAreaName" stand meiner Meinung mal eine weile der deutsche Name des Raumes als Wert. Quasi anstatt Kitchen stand da Küche drinnen.

> Wenn Du das immer von GitHub installierst besteht natürlich die Gefahr, dass da mal eine "faule" Version dabei sein kann, weil die nicht für den "Endbenutzer" freigegeben sind. Die sollten eigentlich nur in Absprache oder auf Empfehlung des Entwicklers installiert werden, wenn z.B. ein Bug gefixt wurde von dem man betroffen ist oder ein Feature was man sich gewünscht hat getestet werden muss.

Das ist mir bewusst. Wenn ich ein Fehler in diesen Versionen hatte bin ich auch immer auf die freigegebene Version zurück geswitcht. Mich stört es nicht wenn mal was nicht geht. Aber das mit dem übersetzen bekomme ich auch mit einer normalen Version nicht behoben. 
Oder war das vielleicht garnicht vorgesehen und ich hab ausversehen immer den spotAreaName mit meinem Script überschrieben?

Mein vorgehen war.
Anhand von ecovacs-deebot.0.map.currentMapMID und ecovacs-deebot.0.map.deebotPositionCurrentSpotAreaID hab ich von der entsprechenden Map und SpotArea den spotAreaName (ist jetzt immer Englisch) abgefragt und mit nem kleinen if else in ein eigenes Object bei ioBroker auf deutsch schreiben und übersetzen lassen.

**Comment by mrbungle64** [comment]
@Snago636 
> 
> In dem Datenpunkt "map.xxxxxxxxx.spotAreas.x.spotAreaName" stand meiner Meinung mal eine weile der deutsche Name des Raumes als Wert. Quasi anstatt Kitchen stand da Küche drinnen.

Ich wüsste jetzt nichts davon, dass dort mal die deutschen Namen drin waren.

Wir können das aber mal als Feature Request aufnehmen. Das macht ja so oder so Sinn ;)

**Comment by Snago636** [comment]
In der "https://github.com/mrbungle64/ecovacs-deebot.js/blob/master/library/mapTemplate.js" sind aber auch diese Übersetzungen hinterlegt. Kann es vielleicht damit zusammenhängen? Ich muß dazu sagen das ich davon keine Ahnung habe wie das alles miteinander funktioniert.

**Comment by mrbungle64** [comment]
> In der "https://github.com/mrbungle64/ecovacs-deebot.js/blob/master/library/mapTemplate.js" sind aber auch diese Übersetzungen hinterlegt. Kann es vielleicht damit zusammenhängen? Ich muß dazu sagen das ich davon keine Ahnung habe wie das alles miteinander funktioniert.

Ja die sind in der Library hinterlegt - werden aber bisher nur in Englisch an den Adapter herausgegeben, da die API der Library noch keine Sprache entgegen nimmt (nur das Land). Das wäre ein Teil dessen was noch umgesetzt werden muss.

**Comment by Snago636** [comment]
Ok dann war das wohl mein Fehler sorry.

**Comment by mrbungle64** [comment]
@Snago636
> Ok dann war das wohl mein Fehler sorry.

Kein Problem. Das Feature ist ja so oder so sinnvoll.

**Comment by mrbungle64** [comment]
Hallo @Snago636 

ab der aktuellen GitHub Version kann man nun die Sprache für die SpotArea Bezeichnungen in den Adapter Einstellungen auswählen (Englisch, Deutsch).

Freue mich über eine Rückmeldungen ob sich alles wie erwartet verhält :)

**Comment by Snago636** [comment]
Hallo @mrbungle64 

ich kann nur sagen super. Es funktioniert einwandfrei. Und den Zusatz mit deebotPositionCurrentSpotAreaName ersparrt mir auch mein Script. :)

Vielen Dank

**Comment by mrbungle64** [comment]
@Snago636 

Das freut mich. Danke für das Feedback 👍🏻 

Ich schließe den Issue dann mal ;)
