### ISSUE TITLE
Connection-Error: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by do1osc** [mrbungle64/ioBroker.ecovacs-deebot#111]
It think, there is a change in the API.

I tried it with Version 1.0.7 and 1.0.8

**Comment by mrbungle64** [comment]
@do1osc 

The Ecovacs servers are currently not reachable

**Comment by do1osc** [comment]
Okay. Thanks. 
Please close the ticket.

**Comment by ds-1982** [comment]
@mrbungle64 
Gibt es bei Dir auch noch Probleme mit dem Server?

**Comment by mrbungle64** [comment]
@ds-1982 

Jap, es gibt wieder Probleme. Die hatten das gestern behoben aber es berichten einige Leute von erneuten Problemen ...

https://www.roboter-forum.com/index.php?thread/48649-ecovacs-server-sind-down-26-12-2020/
