### ISSUE TITLE
spotArea nicht editierbar

### ISSUE THREAD

**Issue by ho11yw** [mrbungle64/ioBroker.ecovacs-deebot#113]
**Software version and sources** (please complete the following information):
 - Adapter version: 1.0.3
 - Source/Repo: ioBroker Stable
 - Node.js version: v10.23.0
 - JS controller version:  [e.g. "3.1.6"]
 - Operating system: Linux
 - Hardware: Raspberry Pi 3

**Deebot model** (please complete the following information):
 - Model name: Deebot Ozmo 950

**Describe the bug**
My Deebot for some reason created zones with many blanks in the numbering. My zones are 0,5,6,10,11,17, so I cannot name the existing zones (I only have spotArea_0 to spotArea_6), nore can I add more zones as they are deleted once the adapter resets. I can also not edit the exitsting ones (i.e. ecovacs-deebot.0.control.spotArea_1 to ecovacs-deebot.0.control.spotArea_17) as new ID gets created instead and also deleted after adapter reset. 

**Additional context**

**Comment by mrbungle64** [comment]
Hello @ho11yw 

this is already fixed. Please try Version 1.0.8 from Latest Repo.
I hope that I can also update the stable version soon.

**Comment by mrbungle64** [comment]
@ho11yw 

I forgot to mention, that you also have to enable synchronization in version 1.0.8:
"Synchronize spotArea buttons in the control channel" / "spotArea Buttons im control Kanal synchronisieren"

**Comment by mrbungle64** [comment]
@ho11yw 

Have you already tried version 1.0.8?
Can we close this issue?

**Comment by ho11yw** [comment]
Hi

To be honest I did not manage to update to 1.0.8 yet. ioBroker only shows all versions up to 1.0.3. Is there a manual page describing how to migrate to versions which are not yet listed in ioBroker?
However I am certain the fix will work and this issue can be closed.

Thank you for your assistance.

**Comment by mrbungle64** [comment]
@ho11yw 

One option is to temporarily switch to Latest Repo:
- System settings -> active repository -> beta (latest)
- Adapters -> update adapter information
- Version 1.0.8 should be available

After installing version 1.0.8:
- System settings -> active repository -> switch back to stable (default)

**Comment by ho11yw** [comment]
Yes that worked! Thank you so much for your patience.
