### ISSUE TITLE
Map Name in Adapter und App

### ISSUE THREAD

**Issue by Snago636** [mrbungle64/ioBroker.ecovacs-deebot#115]
Habe nur ich ein Fehler und daher das Problem, dass der Map Name (ecovacs-deebot.0.map.currentMapName) nicht mehr gefüllt wird? In der App von Ecovacs kann ich diesen auch nicht mehr bearbeiten. Kommt dann immer der Fehler.

> Zeitüberschreitung bei Datenerfassung. Bitte beenden und erneut versuchen.

Liegt der Fehler bei mir oder hat es noch jemand? Eventuell wird ja ecovacs-deebot.0.map.currentMapName nicht mehr befüllt weil bei der Ecovacs App ein Fehler vorliegt. Im 

Gruß Andy

Achja... Habe den Ozmo 950 und das Problem besteht bei der Version 1.0.9-Alpha.4 aber auch dem normalen release 1.0.8.

**Comment by mrbungle64** [comment]
@Snago636 

Bekommst Du ansonsten auch diesen Fehler in der App ("Zeitüberschreitung bei Datenerfassung. Bitte beenden und erneut versuchen")?

Benutzt Du zufällig eine Fritz!Box mit Repeater?

**Comment by Snago636** [comment]
@mrbungle64 

> Bekommst Du ansonsten auch manchmal diesen Fehler in der App ("Zeitüberschreitung bei Datenerfassung. Bitte beenden und erneut versuchen")?

Sonst ging es immer. Wollte nur heute mal den Namen testweise ändern, in der Hoffnung das der Adapter den Namen dann wieder erhält.

> Benutzt Du zufällig eine Fritz!Box mit Repeater?

Ja benutze ich schon immer. Fritz!Box + 2x Repeater.

**Comment by mrbungle64** [comment]
> @mrbungle64
> 
> > Bekommst Du ansonsten auch manchmal diesen Fehler in der App ("Zeitüberschreitung bei Datenerfassung. Bitte beenden und erneut versuchen")?
> 
> Sonst ging es immer. Wollte nur heute mal den Namen testweise ändern, in der Hoffnung das der Adapter den Namen dann wieder erhält. Aktuell ist es auch immernoch mit dem Fehler der App.

Das passiert also auschließlich beim Ändern der Namen in der App?

> 
> > Benutzt Du zufällig eine Fritz!Box mit Repeater?
> 
> Ja benutze ich schon immer. Fritz!Box + 2x Repeater.

Ich hatte AVM das Problem gemeldet, dass ich mit der Ecovacs Mobile App öfter genau diesen Fehler bekomme - ebenso wie dass ich mit meiner Library Probleme mit Timeouts habe.
Inzwischen hat der AVM Support bestätigt, dass es in diesem Zusammenhang Probleme gibt, wenn man Repeater einsetzt.
Du kannst das ja noch mal 1 oder 2 Tage beobachten.

**Comment by Snago636** [comment]
@mrbungle64 

> Das passiert also auschließlich beim Ändern der Namen in der App?

Also das die App sich manchmal schwer startet kenne ich. Aber habe ich bisher auf die Ecovacs Server geschoben. Konnte ich aber durch erneutes Laden fast immer beheben.
Aber die besagte Meldung beim Namen ändern der Map habe ich jetzt jedes mal. Virtuelle Grenzen kann ich normal setzen ohne Fehler.

> Du kannst das ja noch mal 1 oder 2 Tage beobachten.

Werde ich machen. Aber wenn es bei sonst keinem ist muß es wohl bei mir liegen. Ich werde mal auf meinem ioBroker schauen ob ich da vielleicht ein Problem finde.

**Comment by mrbungle64** [comment]
> @mrbungle64
> 
> > Das passiert also auschließlich beim Ändern der Namen in der App?
> 
> Also das die App sich manchmal schwer startet kenne ich. Aber habe ich bisher auf die Ecovacs Server geschoben. Konnte ich aber durch erneutes Laden fast immer beheben.
> Aber die besagte Meldung beim Namen ändern der Map habe ich jetzt jedes mal. Virtuelle Grenzen kann ich normal setzen ohne Fehler.

Du kannst mal probieren, ob der Fehler nch auftritt, wenn (testweise) Du in der Fritz!Box die Hardware-Beschleunigung ausschaltest:

* Unten links in der Fritz!Box Oberffläche "Inhalt" wählen
* in der nächsten Ansicht ganz nach unten scrollen und "Fritz!Box Support" wählen
* dann unter "Paketbeschleunigung" den Punkt "Hardware-Beschleunigung aktiv" abwählen und "Einstellung übernehmen"

Wenn das Problem das weg ist wird es wohl das gleiche Problem sein wie bei mir (also die Kombination mit dem Repeater)

> 
> > Du kannst das ja noch mal 1 oder 2 Tage beobachten.
> 
> Werde ich machen. Aber wenn es bei sonst keinem ist muß es wohl bei mir liegen. Ich werde mal auf meinem ioBroker schauen ob ich da vielleicht ein Problem finde.
> 
> PS: Gibt es eigentlich eine Möglichkeit das ich sehen kann was so von den Ecovacs Servern kommt? Bin manchmal son kleiner Hobby Coder der sich immer freut logs zu durchstöbern in der Hoffnung was interesanntes zu finden was man irgendwie sinnvoll verwerten kann.

Ja gerne 👍🏻 
Du kannst Dir die Library installieren und damit "rumspielen".
[Hier](https://github.com/mrbungle64/ioBroker.ecovacs-deebot/issues/83#issuecomment-662408755) habe ich das z.B. beschrieben.

So bekommst Du die kompletten Debug Ausgaben:
```
NODE_ENV=dev node app2.js
```

Kannst dann ja auch selbst Debug Ausgaben einbauen :)

**Comment by mrbungle64** [comment]
@Snago636 

Hast Du schon neue Erkenntnisse gewinnen können?
Würde mich nämlich mal interessieren, ob das auch mit den Fritz!Box Komponenten zusammenhängt.

**Comment by Snago636** [comment]
@mrbungle64 
Habe jetzt leider noch nicht so viel testen können da Frau und Kind immer zu Hause sind. Da ist das meckern groß wenn ich mit dem Staubsauger rumspiele. :)

Aber die Funktion habe ich in der Fritz!Box schon ausgeschalten. Jedoch konnte ich den Namen der Map trotzdem nicht ändern. Habe dann aber festgestellt, das ich den Namen für die andere Etage ändern konnte. Also hat Ecovacs vermutlich irgend ein Fehler mit der gespeicherten Map. Habe diese jetzt gelöscht. Konnte aber noch keine neue Map erstellen lassen da ich für die erste erstellung immer alles fein freiräume. Mach ich aber heut Abend mal. Dann geb ich Feedback ob der Mapname dann wieder angezeigt wird.

**Comment by mrbungle64** [comment]
@Snago636 
ok, alles klar 👍🏻 

Hier ist ein Tipp der Dir vielleicht das Neuerstellen der Map etwas erleichtert:
https://www.roboter-forum.com/index.php?thread/47031-pro-tip-erstkartierung-geht-auch-ohne-komplette-autoreinigung-der-gesamten-etage/
Hab es selbst aber noch nicht getestet.

**Comment by Snago636** [comment]
@mrbungle64 
Also neue Map ist erstellt und eingerichtet. ecovacs-deebot.0.map.currentMapName wird wieder korrekt gefüllt. Muss wohl echt ein Fehler in der gespeichertet Map bei Ecovacs gewesen sein.

Danke dir für die Unterstützung.

Werd jetzt aber trotzdem mal mit der Hardware-Beschleunigung in der FB ab und an ein bissel rumspielen um zu sehen ob ich Änderungen feststellen kann.
