### ISSUE TITLE
lastCleaningMapimageURL wird in Vis nicht dargestellt

### ISSUE THREAD

**Issue by senger1985** [mrbungle64/ioBroker.ecovacs-deebot#116]
**Software version and sources**:
 - Adapter version: 1.0.9

 - Node.js version: v12.19.1
 - JS controller version: 3.1.6
 - Operating system: Linux
 - Hardware: Intel Nuc

**Deebot model**
 - Model name: [e.g. "Deebot Ozmo T8 AIVI"]

- Please enter the following values:
    - "info.deviceClass": x5d34r
    - "info.canvasModuleIsInstalled": true
    - "info.communicationProtocol": MQTT

**Describe the bug**
Mir ist es mit keinem Widget möglich, den Inhalt, von dem Datenpunkt:
"ecovacs-deebot.0.cleaninglog.lastCleaningMapImageURL"
in der Vis darzustellen.

Wenn ich den Link in einem Browser, wie Chrome aufrufe, möchte er ein Image runterlagen.

**Comment by mrbungle64** [comment]
Hallo @senger1985 

wenn im Datenpunkt "ecovacs-deebot.0.cleaninglog.lastCleaningMapImageURL" eine korrekte URL eingetragen ist und der Browser dann ein Image runterlädt was die letzte Reinigungskarte enthält verhält es sich erst mal korrekt.

Wie Du das in VIS integrieren kannst bin ich leider erst mal überfragt, da ich den VIS Adapter nicht benutze.

**Comment by Snago636** [comment]
@senger1985 
also ich lasse es mir mit dem Widget anzeigen.

`[{"tpl":"tplValueStringImg","data":{"oid":"ecovacs-deebot.0.cleaninglog.lastCleaningMapImageURL","g_fixed":false,"g_visibility":false,"g_css_font_text":false,"g_css_background":false,"g_css_shadow_padding":false,"g_css_border":false,"g_gestures":false,"g_signals":false,"g_last_change":false,"visibility-cond":"==","visibility-val":1,"visibility-groups-action":"hide","refreshInterval":"0","signals-cond-0":"==","signals-val-0":true,"signals-icon-0":"/vis/signals/lowbattery.png","signals-icon-size-0":0,"signals-blink-0":false,"signals-horz-0":0,"signals-vert-0":0,"signals-hide-edit-0":false,"signals-cond-1":"==","signals-val-1":true,"signals-icon-1":"/vis/signals/lowbattery.png","signals-icon-size-1":0,"signals-blink-1":false,"signals-horz-1":0,"signals-vert-1":0,"signals-hide-edit-1":false,"signals-cond-2":"==","signals-val-2":true,"signals-icon-2":"/vis/signals/lowbattery.png","signals-icon-size-2":0,"signals-blink-2":false,"signals-horz-2":0,"signals-vert-2":0,"signals-hide-edit-2":false,"lc-type":"last-change","lc-is-interval":true,"lc-is-moment":false,"lc-format":"","lc-position-vert":"top","lc-position-horz":"right","lc-offset-vert":0,"lc-offset-horz":0,"lc-font-size":"12px","lc-font-family":"","lc-font-style":"","lc-bkg-color":"","lc-color":"","lc-border-width":"0","lc-border-style":"","lc-border-color":"","lc-border-radius":10,"lc-zindex":0},"style":{"left":"2px","top":"-69px","width":"427px","height":"352px"},"widgetSet":"basic"}]`

**Comment by senger1985** [comment]
Solved & closed
