### ISSUE TITLE
LastCleaningMapImageURL wird nicht gefüllt

### ISSUE THREAD

**Issue by Dragon0501** [mrbungle64/ioBroker.ecovacs-deebot#117]
Habe heute auf einen Deebot 901 umgestellt. Vorher lief der Adapter mit einem N79T. Habe den Adapter angehalten und die Objekte gelöscht. Nachdem der neue Sauger mit dem Ecovacs Konto verbunden war den Adapter wieder angeschaltet und schon wurde das neue Gerät übernommen. Es werden auch alle Objekte gefüllt bis auf die Info zur Map. 
AdapterVersion ist die 1.0.9

![Screenshot 2021-01-08 at 11 59 14](https://user-images.githubusercontent.com/59663011/104818056-70891b80-5825-11eb-80b8-1dc6aca7ac09.png)

**Comment by mrbungle64** [comment]
Hi @Dragon0501 

hast Du mit dem neuen Gerät schon mal eine vollständige Reinigung durchgeführt?

**Comment by Dragon0501** [comment]
Jap. Schon die zweite...

**Comment by mrbungle64** [comment]
> Jap. Schon die zweite...

Sind die anderen "cleaninglog" Datenpunkte alle befüllt?
Evtl. musst Du auch noch "Zeige sämtliche Werte vom Reinigungsprotokoll (cleaninglog)" in den Einstellungen aktivieren.

**Comment by Dragon0501** [comment]
Fällt mir grad auf:
![Screenshot 2021-01-16 at 18 49 36](https://user-images.githubusercontent.com/59663011/104819114-b812a600-582b-11eb-8bfb-52690a4c22d7.png)

**Comment by mrbungle64** [comment]
@Dragon0501 

Zeigt die Mobile App die 2 Reinigungen im Reinigungsprotokoll an?

**Comment by Dragon0501** [comment]
Nein nur eine

**Comment by mrbungle64** [comment]
> Nein nur eine

Manchmal dauert das einen Augenblick bis die Reinigungsprotokolle abgerufen werden können.
Hast Du den Adapter schon mal neugestartet?

**Comment by Dragon0501** [comment]
Mehrfach

**Comment by Dragon0501** [comment]
Dann warte ich erstmal bis morgen früh. Vll hilft ja die Zeit über Nacht...

**Comment by mrbungle64** [comment]
> Dann warte ich erstmal bis morgen früh. Vll hilft ja die Zeit über Nacht...

Ja, machmal kommen die ein bisschen verzögert rein - es sollte aber eigentlich problemlos funktionieren - ich habe ja auch einen Deebot 901. 
Habe gerade noch mal auf 2 Systemen die Datenpunkte gelöscht und gestestet - auf beiden wurden die Werte wieder korrekt und auch recht zügig neu befüllt.

Wir können dann morgen ja weiterschauen, falls die Werte immer noch fehlen.

**Comment by Dragon0501** [comment]
So machen wir das. Vielen Dank!

**Comment by Dragon0501** [comment]
Guten Morgen
Keine cleaning Logs und keine MapURL
Adapter neu gestartet. Selber Problem besteht weiterhin... Bin echt ratlos...

**Comment by mrbungle64** [comment]
@Dragon0501 

Schau doch bitte noch mal nach, ob Du ""Zeige sämtliche Werte vom Reinigungsprotokoll (cleaninglog)" in den Einstellungen ("Experimental") auf "Vorauswahl verwenden" oder "aktivieren" stehen hast.

**Comment by Dragon0501** [comment]
Auf deinen Hinweis gestern hab ich es auf aktiviert gestellt.

**Comment by mrbungle64** [comment]
> Auf deinen Hinweis gestern hab ich es auf aktiviert gestellt.

ok, wollte nur sicher gehen, dass Du es nicht aus Versehen auf "deaktivieren" gestellt hast - hätte ja sein können ;)
Auch noch mal zur Sicherheit: unter "info.deviceClass" müsste folgendes eingetragen sein: "ls1ok3"
Finde das weiterhin komisch, da ich gerade beim Deebot 901 (habe den seit Frühjahr 2020) bisher keine Probleme feststellen konnte.

Wie schaut es in der Mobile App nun aus? Werden da jetzt alle Reinigungen angezeigt?

**Comment by Dragon0501** [comment]
Nein hatte es noch mal überprüft. Es steht auf aktivieren. device class ist "Is1ok3"

Es werden noch immer nicht alle in der App angezeigt. Die Erste zum erstellen der Karte wird noch immer nicht angezeigt. Es wird quasi eine weniger angezeigt als im Adapter geführt.

**Comment by Dragon0501** [comment]
Auch die Reinigung von heute wird angezeigt.

**Comment by mrbungle64** [comment]
> Nein hatte es noch mal überprüft. Es steht auf aktivieren. device class ist "Is1ok3"

Danke, dass Du es noch mal geprüft hast 👍🏻 

> 
> Es werden noch immer nicht alle in der App angezeigt. Die Erste wird noch immer nicht angezeigt. Es wird quasi eine weniger angezeigt als im Adapter geführt.

Das ist der Grund, warum der Cleaninglog-Channel bei den meisten Modellen noch nicht standardmäßig eingeschaltet ist bzw. noch unter "Experimental" geführt wird - da offensichtlich nicht mal die Mobile App von Ecovacs das zuverlässig abruft (bzw. der Roboter die ggf. nicht richtig übermittelt). Da gibt es vor allem beim OZMO 950 [diverse Berichte](https://www.roboter-forum.com/index.php?thread/40009-reinigungsprotokoll-wird-nicht-gespeichert) (unabhängig vom ioBroker Adapter), dass da immer mal wieder welche fehlen.

Ich kontrolliere die bei meine Geräten jetzt natürlich nicht regelmäßig auf Vollständigkeit, aber wenn ich die Datenpunkte bzw. den Channel lösche werden die wieder zuverlässig erstellt und wieder mit Daten befüllt.

Da Ecovacs API ja nicht öffentlich zugänglich dokumentiert ist kann ich leider auch nicht prüfen, ob die Daten im Adapter 100%ig korrekt abgefragt werden. Evtl. gibt es da ja Unterschiede im Detail die bei manchen Geräten/Modellen eben den Unterschied machen ... Aber das scheint Ecovacs ja selbst nicht mal 100%ig im Griff zu haben ;)

**Comment by mrbungle64** [comment]
> Auch die Reinigung von heute wird angezeigt.

Stell das Log für die Adapter Instanz doch bitte mal auf debug. 
Da sollten dann regelmäßig folgender Aufruf kommen:

```
[commandQueue] startNextItemFromQueue: GetLogApiCleanLogs
```

**Comment by Dragon0501** [comment]
Müsste es denn nicht eig funktionieren wenn du auch einen 901 hast und es bei dir funzt? Device Model steht auf "Deebot 900 Series" ist das richtig so?

**Comment by mrbungle64** [comment]
> Müsste es denn nicht eig funktionieren wenn du auch einen 901 hast und es bei dir funzt? Device Model steht auf "Deebot 900 Series" ist das richtig so?

Ja das hatte ich ja schon geschrieben. Wir hatten das mit der "info.deviceClass" (= "ls1ok3") schon geprüft.

**Comment by Dragon0501** [comment]
Die Cleaning Log Abfrage ist nur in der ersten Runde nach dem Adapterstart vorhanden. Danach wird er nicht mehr abgefragt.

**Comment by mrbungle64** [comment]
> Die Cleaning Log Abfrage ist nur in der ersten Runde nach dem Adapterstart vorhanden. Danach wird er nicht mehr abgefragt.

Starte mal bitte einen beliebigen Reinigungsvorgang

**Comment by Dragon0501** [comment]
Habe ich getan

**Comment by mrbungle64** [comment]
> Habe ich getan

Kommt nun wieder eine Cleaning Log Abfrage?

**Comment by mrbungle64** [comment]
Die Cleaning Log Abfragen kommen jeweils 1x 
* beim Start/Neustart der Adapter Instanz
* beim Start des Ladevorgangs
* beim Start eines beliebigen Reinigungsvorgangs

**Comment by Dragon0501** [comment]
Beim Start des Reinigungsvorganges wird er nicht gesendet. Beim Start des Ladevorganges wird er auch nicht gesendet

**Comment by mrbungle64** [comment]
> Beim Start des Reinigungsvorganges wird er nicht gesendet. Beim Start des Ladevorganges wird er auch nicht gesendet

Die müssten mit dem nächsten Intervall ausgeführt werden.
Auf wieviel Sekunden steht "Abfrage Intervall (Sekunden)" unter "weiteres..."?
Geht "info.deviceStatus" auf "cleaning" wenn Du eine Reinigung startest?

**Comment by mrbungle64** [comment]
Welche Firmware-Version hast Du installiert? Bei mir ist es 2.1.9

**Comment by Dragon0501** [comment]
Intervall sind 60Sekunden
deviceStatus ändert sich.
Nun sind die Abfragen aufgetaucht. Vll einfach nur schneller aus dem Log gerutscht als ich sie anzeigen konnte.
Die Firmwareversion ist die gleiche.

**Comment by mrbungle64** [comment]
@Dragon0501 

Installier bitte mal die Version 1.0.3 (also die letzte Stable).
Würde mich interessieren, ob es damit bei Deinem Gerät funktioniert.

**Comment by Dragon0501** [comment]
Habe die Version 1.0.3 installiert.
"Zeige sämtlich Werte..." einmal aktiviert, einmal "Vorauswahl verwenden", jeweils ein neustart des Adapter und einmal Start eines Reinigungsvorganges. Mit der Adapter Version kann ich "[commandQueue] startNextItemFromQueue: GetLogApiCleanLogs" überhaupt nicht mehr finden im Log. Die drei Datenpunkte werden auch nicht gefüllt.

**Comment by Snago636** [comment]
@Dragon0501 
Ich würde mal versuchen den Adapter zu löschen und nochmal erneut einzurichten.

**Comment by Dragon0501** [comment]
@Snago636 
Bitte nicht böse sein, aber ich warte erstmal ab was mit der Entwickler des Adapters vorschlägt.

**Comment by mrbungle64** [comment]
> @Dragon0501
> Ich würde mal versuchen den Adapter zu löschen und nochmal erneut einzurichten.

Ja das ist eine gute Idee @Snago636, denn die Instanz ist ja noch vom N79 übernommen worden, wenn ich es richtig verstanden habe. Sollte eigentlich auch funktionieren, aber wer weiß ...

**Comment by mrbungle64** [comment]
> @Snago636
> Bitte nicht böse sein, aber ich warte erstmal ab was mit der Entwickler des Adapters vorschlägt.

@Dragon0501 
Das passt schon. Bitte probier' das mal.

**Comment by Dragon0501** [comment]
Welchen soll ich denn nehmen die 3 oder die 9?

**Comment by mrbungle64** [comment]
> Welchen soll ich denn nehmen die 3 oder die 9?

Kannst direkt die 1.0.9 nehmen.

**Comment by Dragon0501** [comment]
Habe den Adapter gelöscht und neu installiert. Dann habe ich wieder die experimentelle Funktion aktiviert und es werden wieder alle Daten punkte befüllt außer die drei altbekannten. Beim Starten der Reinigung gibt er eine Warnung aus:
`

ecovacs-deebot.0 | 2021-01-17 12:04:47.910 | warn | (8634) Unhandled cleanstatus: undefined
-- | -- | -- | --


`

**Comment by mrbungle64** [comment]
> Habe den Adapter gelöscht und neu installiert. Dann habe ich wieder die experimentelle Funktion aktiviert und es werden wieder alle Daten punkte befüllt außer die drei altbekannten. Beim Starten der Reinigung gibt er eine Warnung aus:
> `
> 
> ecovacs-deebot.0	2021-01-17 12:04:47.910	warn	(8634) Unhandled cleanstatus: undefined
> `

Welche Reinigung hast Du gestartet?

**Comment by Dragon0501** [comment]
Den button clean habe ich genutzt. Der Robi reagiert auch adäquat, macht seine Durchsage und beginnt mit der Reinigung. Die Anzahl der Reinigungsvorgänge wird aber jedesmal erhöht. Die Anfrage scheint also zu funktionieren. lediglich die Antwort vom Server passt nicht. In der App kann ich die Reinigungskarten sehen, heist sie werden auch erstellt. Ich denke ja mal sie werden in der Cloud erstellt und in die App geladen, oder sehe ich das falsch und es wäre möglich, dass die App auf der App existiert aber nicht in die Cloud synchronisiert wird?

**Comment by mrbungle64** [comment]
> Habe die Version 1.0.3 installiert.
> "Zeige sämtlich Werte..." einmal aktiviert, einmal "Vorauswahl verwenden", jeweils ein neustart des Adapter und einmal Start eines Reinigungsvorganges. Mit der Adapter Version kann ich "[commandQueue] startNextItemFromQueue: GetLogApiCleanLogs" überhaupt nicht mehr finden im Log. Die drei Datenpunkte werden auch nicht gefüllt.

Schau bitte noch mal nach der Meldung

```
[intervalQueue] startNextItemFromQueue: GetLogApiCleanLogs
```

**Comment by mrbungle64** [comment]
> und es wäre möglich, dass die App auf der App existiert aber nicht in die Cloud synchronisiert wird?

Was meinst Du damit? Ich denke da hast Du Dich 1x bei "App" vertan ;)

**Comment by Dragon0501** [comment]
Ja stimmt. 
... und es wäre möglich, dass die Karte in der App existiert aber nicht in die Cloud synchronisiert wird.

**Comment by Dragon0501** [comment]
> [intervalQueue] startNextItemFromQueue: GetLogApiCleanLogs

Soll ich danach in der aktuellen 1.0.9 Instanz suchen?

**Comment by mrbungle64** [comment]
> > [intervalQueue] startNextItemFromQueue: GetLogApiCleanLogs
> 
> Soll ich danach in der aktuellen 1.0.9 Instanz suchen?

Ja genau

**Comment by mrbungle64** [comment]
> Ja stimmt.
> ... und es wäre möglich, dass die Karte in der App existiert aber nicht in die Cloud synchronisiert wird.

Die Mobile App bezieht (soweit ich weiß) alles aus der Cloud - nicht direkt vom Roboter.
Das gleiche gilt für den Adapter (bzw. die verwendete Library). Auch die Anzahl der Reinigungen kommt aus der Cloud.

**Comment by Dragon0501** [comment]
`[intervalQueue] startNextItemFromQueue: GetLogApiCleanLogs`

wird bei Reinigungsbeginn und bei Ladebeginn gesendet.

**Comment by Dragon0501** [comment]
Was mir jetzt noch einfallen würde wäre:
Schau doch mal ob sich die URL ändert wenn du eine neue Reinigung startest. Vll war irgendwann mal zufällig der richtige Befehl dabei und so wurde in der Cloud etwas ausgelöst was dir immer die gleiche Karte zur Verfügung stellt und nicht immer die der letzten Reinigung.

**Comment by mrbungle64** [comment]
> Was mir jetzt noch einfallen würde wäre:
> Schau doch mal ob sich die URL ändert wenn du eine neue Reinigung startest. Vll war irgendwann mal zufällig der richtige Befehl dabei und so wurde in der Cloud etwas ausgelöst was dir immer die gleiche Karte zur Verfügung stellt und nicht immer die der letzten Reinigung.

@Dragon0501 
Das Bild (die Map) hinter der URL stimmt bei mir exakt mit dem aus der Mobile App überein.

Ich habe aber (hoffentlich) das Problem gefunden:
Die Anzahl der Reinigungen wird bei einer Anzahl von < 20 ggf. falsch ermittelt.
Bei welcher Anzahl sind wir denn gerade aktuell bei Dir?

**Comment by Dragon0501** [comment]
Durch die ein Quadratmeter Reinigungen grad bei 12. Davon werden aber nur drei im Cleanlog angezeigt. Weiß also nicht ob die drei die Zahl ist oder die zwölf...

**Comment by mrbungle64** [comment]
> Davon werden aber nur drei im Cleanlog angezeigt.

Von welchem Cleanlog sprichst Du (Adapter oder Mobile App)?

**Comment by Dragon0501** [comment]
Im Cleanlog der mobile App werden drei Reinigungen angezeigt. Im Datenpunkt des Adapters werden 15 angezeigt.

**Comment by Dragon0501** [comment]
![Screenshot_2021-01-17-13-01-27-559_com eco global app](https://user-images.githubusercontent.com/59663011/104839858-3c186c80-58c4-11eb-9d43-d205a94165c1.jpg)

**Comment by Dragon0501** [comment]
Die Zahl stimmt mit dem Adapter überein. Die Protokolle unten mit den Karten leider nicht...

**Comment by mrbungle64** [comment]
> Die Zahl stimmt mit dem Adapter überein. Die Protokolle unten mit den Karten leider nicht...

Ja ok, ich meine aber die Anzahl die in "intern" der Library ermittelt wird.

Ich bin gerade dabei den Bug zu fixen.

**Comment by Dragon0501** [comment]
Das ist super toll! Ich bin sowas von begeistert. Die Devs der Adapter und des Brokers sind sowas von hilfsbereit und flexibel. Ist einfach toll!

**Comment by mrbungle64** [comment]
> Das ist super toll! Ich bin sowas von begeistert. Die Devs der Adapter und des Brokers sind sowas von hilfsbereit und flexibel. Ist einfach toll!

Freut mich :D Aber warten wir erst mal ab, ob es auch wirklich funktioniert ;)

Probier' mal bitte die 1.0.10-alpha.1 von GitHub.

**Comment by Dragon0501** [comment]
Ähm, wie installiere ich die Alpha?

**Comment by Dragon0501** [comment]
hab es geschafft sie zu installieren

**Comment by Dragon0501** [comment]
Leider keine Besserung

**Comment by mrbungle64** [comment]
> Leider keine Besserung

Das ist sch.......

Meinst Du dass Du mal folgendes auf Deinem Raspberry Pi durchführen kannst?

1) Im Home-Verzeichnis direkt nach dem Anmelden (nicht im ioBroker-Verzeichnis):
```bash
git clone https://github.com/mrbungle64/ecovacs-deebot.js.git
cd ecovacs-deebot.js
npm install
cd example
```

2) Email und Passwort in der Datei `app2.js` anpassen

3) Die app ausführen 
```bash
NODE_ENV=dev node app2.js | grep Logs
```

4) laufen lassen (so 30-60 Sek.) und anschließend die Ausgabe posten.

**Comment by Dragon0501** [comment]
natürlich mache ich das. mom
Habe da noch eine Testinstanz auf der ich das mache

**Comment by Dragon0501** [comment]
Einfach laufen lassen oder iwas machen währenddessen? Also reinigung starten oder sowas?

**Comment by mrbungle64** [comment]
> Einfach laufen lassen oder iwas machen währenddessen? Also reinigung starten oder sowas?

Einfach laufen lassen - musst sonst nix machen

**Comment by Dragon0501** [comment]
Da hängt es seit einiger Zeit. Kann mir nicht vorstellen, dass das richtig ist...

![Screenshot 2021-01-17 at 14 31 20](https://user-images.githubusercontent.com/59663011/104844498-df6f7e80-58d0-11eb-9203-9f46dc96cbed.png)

**Comment by Dragon0501** [comment]
Hups... hat nur ewig gedauert

**Comment by Dragon0501** [comment]
finde ich die Ausgabe in der Console? Oder gibts eine Datei die ich posten muss?

**Comment by Dragon0501** [comment]
wie stoppe ich die ausführung?

**Comment by Dragon0501** [comment]
Eine Ausgabe in der Console erfolgt nicht.

**Comment by mrbungle64** [comment]
@Dragon0501 

Mach mal bitte noch mal einen Screenshot oder poste mal was Du zuletzt gemacht hast

**Comment by Dragon0501** [comment]
![Screenshot 2021-01-17 at 14 46 21](https://user-images.githubusercontent.com/59663011/104844878-e7302280-58d2-11eb-929e-2daafe4bf770.png)

**Comment by Dragon0501** [comment]
so bleibt die anzeige
kann auch nichts daran ändern. ctrl und c beendet es nicht

**Comment by mrbungle64** [comment]
@Dragon0501 

Führe mal bitte folgendes aus:

```
NODE_ENV=dev node app2.js
```

Wenn da ein haufen Zeugs kommt (ohne das es mit Fehler abbricht) dann würde ich sagen dass der Ecovacs Server "stumm" bleibt bei den Cleaning Logs ...

Bitte aber nicht diese Ausgabe posten - da sind sensible Informationen dabei

**Comment by Dragon0501** [comment]
Da wird ein Haufen Zeugs gepostet unter anderem Lifespan FIlter und solche Sachen

**Comment by mrbungle64** [comment]
> Da wird ein Haufen Zeugs gepostet unter anderem Lifespan FIlter und solche Sachen

Ersetze in der app2.js mal bitte in der Zeile 87 mal das `GetNetInfo` durch `GetLogApiCleanLogs`.
Du kannst auch die Zeile 83 mit `vacbot.run('Clean');` mal löschen, wenn Du nicht möchtest, dass der jedes mal startet.

**Comment by Dragon0501** [comment]
welchen Befehl dann wieder zum ausführen? den ersten oder den zweiten?

**Comment by mrbungle64** [comment]
> welchen Befehl dann wieder zum ausführen? den ersten oder den zweiten?

```
NODE_ENV=dev node app2.js | grep Logs
```

**Comment by Dragon0501** [comment]
Da gibt es eine Ausgabe. Hier posten oder sind da auch sensible Daten drin?

**Comment by Dragon0501** [comment]
Da ist auch ein Link zu einer Karte enthalten und dieser funktioniert auch. Kann damit manuell eine Karte herunterladen.

**Comment by mrbungle64** [comment]
> Da gibt es eine Ausgabe. Hier posten oder sind da auch sensible Daten drin?

Da sind (im Optimalfall) die URLs der Maps dabei - wir versuchen erst erst mal ohne...

Eine Ausgabe müsste mit `Logs: {"event":"CleanLogs","attrs":{"count":20} ...` anfangen.
Welcher Wert steht bei Dir bei count?

Führ das dann noch mal folgendermaßen aus:

```
NODE_ENV=dev node app2.js | grep imageUrl
```

Die Anzahl der Zeilen sollte dann mit dem Wert unter `count` übereinstimmen

**Comment by Dragon0501** [comment]
Hups posts haben sich überschitten

**Comment by mrbungle64** [comment]
> Hups posts haben sich überschitten

Ja, aber führ das bitte trotzdem mal aus was ich geschrieben hatte

**Comment by Dragon0501** [comment]
Beim ersten steht count:20

**Comment by Dragon0501** [comment]
Die Ausgabe gleicht bis auf kleine Abweichungen der ersten Ausgabe

**Comment by mrbungle64** [comment]
> Beim ersten steht count:20

Starte jetzt bitte mal den Adapter neu und schau mal ob die Werte nun kommen

**Comment by Dragon0501** [comment]
Nein, die Werte kommen nicht

**Comment by mrbungle64** [comment]
> Nein, die Werte kommen nicht

@Dragon0501 

In der Ausgabe hast Du quasi in jeder Zeile einen Wert zu dem Attribut "id". Da sollte 2x ein "@"Zeichen drin sein.
Ersetze den Wert links vor dem 1. "@" mal in der Ausgabe durch z.B. "xxx" und poste dann mal die so angepasste Ausgabe.

Das sieht dann als Beispiel so aus:
```
{"id":"xxx@1687625294@KeTC","timestamp":1610801876,"date":"2021-01-16T12:57:56.000Z","lastTime":936,"totalTimeString":"0h 15m 36s","squareMeters":17,"imageUrl":"https://portal-eu.ecouser.net/api/lg/image/xxx@1687625294@KeTC","type":"auto"}
```

**Comment by Dragon0501** [comment]
`{"event":"CleanLogs","attrs":{"count":20},"children":[{"ts":1610891607,"last":242,"area":2,"id":"xxx@1280388115@Eyuh","imageUrl":"https://portal-eu.ecouser.net/api/lg/image/c1f9ec1e-ef8d-45e3-bc47-694cfbead687@1280388115@Eyuh","type":"auto","aiavoid":0,"aitypes":[]},`

**Comment by Dragon0501** [comment]
sehe grad das Problem...

**Comment by Dragon0501** [comment]
`dragon@ioBrokerVM:~/ecovacs-deebot.js/example$ NODE_ENV=dev node app2.js | grep imageUrl
[EcovacsMQTT] Logs: {"event":"CleanLogs","attrs":{"count":20},"children":[{"ts":1610891607,"last":242,"area":2,"id":"XXX@1280388115@Eyuh","imageUrl":"https://portal-eu.ecouser.net/api/lg/image/XXX@1280388115@Eyuh","type":"auto","aiavoid":0,"aitypes":[]},{"ts":1610891171,"last":256,"area":1,"id":"XXX@565469127@Eyuh","imageUrl":"https://portal-eu.ecouser.net/api/lg/image/XXX@565469127@Eyuh","type":"auto","aiavoid":0,"aitypes":[]},{"ts":1610890967,"last":6,"area":0,"id":"XXX@1202488776@Eyuh","imageUrl":"https://portal-eu.ecouser.net/api/lg/image/XXX@1202488776@Eyuh","type":"auto","aiavoid":0,"aitypes":[]},{"ts":1610890940,"last":28,"area":0,"id":"XXX@156191686@Eyuh","imageUrl":"https://portal-eu.ecouser.net/api/lg/image/XXX@156191686@Eyuh","type":"auto","aiavoid":0,"aitypes":[]},{"ts":1610890738,"last":201,"area":2,"id":"XXX@143232621@Eyuh","imageUrl":"https://portal-eu.ecouser.net/api/lg/image/XXX@143232621@Eyuh","type":"auto","aiavoid":0,"aitypes":[]},{"ts":1610889540,"last":261,"area":4,"id":"XXX@38138667@Eyuh","imageUrl":"https://portal-eu.ecouser.net/api/lg/image/XXX@38138667@Eyuh","type":"SpotArea","aiavoid":0,"aitypes":[]},{"ts":1610888376,"last":238,"area":4,"id":"XXX@476548702@Eyuh","imageUrl":"https://portal-eu.ecouser.net/api/lg/image/XXX@476548702@Eyuh","type":"SpotArea","aiavoid":0,"aitypes":[]},{"ts":1610887953,"last":277,"area":4,"id":"XXX@833557280@Eyuh","imageUrl":"https://portal-eu.ecouser.net/api/lg/image/XXX@833557280@Eyuh","type":"SpotArea","aiavoid":0,"aitypes":[]},{"ts":1610887243,"last":168,"area":1,"id":"XXX@431953779@Eyuh","imageUrl":"https://portal-eu.ecouser.net/api/lg/image/XXX@431953779@Eyuh","type":"auto","aiavoid":0,"aitypes":[]},{"ts":1610886970,"last":110,"area":1,"id":"XXX@2135505508@Eyuh","imageUrl":"https://portal-eu.ecouser.net/api/lg/image/XXX@2135505508@Eyuh","type":"auto","aiavoid":0,"aitypes":[]},{"ts":1610884073,"last":2391,"area":30,"id":"XXX@479459368@Eyuh","imageUrl":"https://portal-eu.ecouser.net/api/lg/image/XXX@479459368@Eyuh","type":"auto","aiavoid":0,"aitypes":[]},{"ts":1610877407,"last":107,"area":1,"id":"XXX@1039841003@Eyuh","imageUrl":"https://portal-eu.ecouser.net/api/lg/image/XXX@1039841003@Eyuh","type":"auto","aiavoid":0,"aitypes":[]},{"ts":1610873016,"last":2228,"area":30,"id":"XXX@1603343687@Eyuh","imageUrl":"https://portal-eu.ecouser.net/api/lg/image/XXX@1603343687@Eyuh","type":"auto","aiavoid":0,"aitypes":[]},{"ts":1610816485,"last":2314,"area":30,"id":"XXX@1841847020@Eyuh","imageUrl":"https://portal-eu.ecouser.net/api/lg/image/XXX@1841847020@Eyuh","type":"auto","aiavoid":0,"aitypes":[]},null,null,null,null,null,null]}
^C
dragon@ioBrokerVM:~/ecovacs-deebot.js/example$

`

Das Ende ist die Krux

**Comment by mrbungle64** [comment]
@Dragon0501 

> Das Ende ist Interessant denke ich

Ja das wird das Problem verursachen. Ich versuche das mal zu fixen.
Bitte starte jetzt mal keine Reinigung, so dass Du weiterhin unter 20 bleibst damit Du das dann testen kannst.
Ich versuche das direkt zu fixen.

**Comment by Dragon0501** [comment]
Klar kein Problem

**Comment by mrbungle64** [comment]
@Dragon0501 

So, dann probier mal bitte die 1.0.10-alpha.3 vom Adapter ;)

**Comment by Dragon0501** [comment]
Sie werden gefüllt! Wo kann ich dir ein Bier ausgeben?
Vielen vielen Dank!

**Comment by mrbungle64** [comment]
> Das was mich natürlich jetzt noch interessiert wäre wieso klappte das bei dir, aber bei mir nicht? Lag das echt an den "Null" am Ende?

Ja genau 👍🏻 

> Sie werden gefüllt! Wo kann ich dir ein Bier ausgeben?

Alles gut 👍🏻  Lass uns einfach virtuell auf eine gute Zusammenarbeit anstoßen 🍻 

Bin ja froh, dass der Bug gefixt ist. Das Problem tritt halt (wahrscheinlich) nur auf, wenn man noch keine 20 Reinigungen hat.
Daher konnte ich den Fehler auch nicht nachstellen 😉

**Comment by Dragon0501** [comment]
So machen wir das! Das war toll, dass es tatsächlich eine Lösung gibt... Vielen Dank! Prost!
