### ISSUE TITLE
The adapter does not start anymore

### ISSUE THREAD

**Issue by senger1985** [mrbungle64/ioBroker.ecovacs-deebot#118]
**Software version and sources**:
 - Adapter version: 1.0.10 (0.5.4)
 - Source/Repo: Latest, I guess
 - Node.js version: v12.19.1
 - JS controller version:  3.2.3
 - Operating system: Linux (Proxmox)
 - Hardware: Intel NUC

**Deebot model**
 - Model name: Deebot Ozmo T8 AIVI

- Please enter the following values:
    - "info.deviceClass": x5d34r
    - "info.canvasModuleIsInstalled": true
    - "info.communicationProtocol": MQTT

**Describe the bug**
The adapter does not start anymore after the update to version 1.0.10

ecovacs-deebot.0 | 2021-01-21 08:23:13.021 | error | (14261) unhandled promise rejection: The id is empty! Please provide a valid id.
-- | -- | -- | --
ecovacs-deebot.0 | 2021-01-21 08:23:13.021 | error | (14261) Unhandled promise rejection. This error originated either by  throwing inside of an async function without a catch block, or by  rejecting a promise which was not handled with .catch().
ecovacs-deebot.0 | 2021-01-21 08:23:13.017 | error | (14261) The id is empty! Please provide a valid id.

**Comment by mrbungle64** [comment]
@senger1985 

Have you already restarted the adapter instance after this error occurred?
If the error persists, please install an older version (e.g. 1.0.9) and check if the error also occurs with that version.

**Comment by mrbungle64** [comment]
@senger1985 

Please also update to the latest version of js-controller first!
You are currently running a test version (v3.2.3)

**Comment by senger1985** [comment]
Sorry, I made a typing mistake.
My js-controller have the latest version 3.2.7.

Downgrade to an older version, the error persists.

**Comment by mrbungle64** [comment]
> Sorry, I made a typing mistake.
> My js-controller have the latest version 3.2.7.
> 
> Downgrade to an older version, the error persists.

I guess you have to delete the adapter instance and reinstall it.

**Comment by senger1985** [comment]
Deleting the instance helped that the adapter v1.0.9 is running

**Comment by mrbungle64** [comment]
> Deleting the instance helped that the adapter v1.0.9 is running

ok, that's good 👍🏻 
Now you can also update to 1.0.10 again.

**Comment by senger1985** [comment]
It seems that deleting the instance fixed the problem.
I'll watch it and give you feedback, if the problem is coming back.
