### ISSUE TITLE
curstom area still available, status wird nicht geändert?

### ISSUE THREAD

**Issue by krobipd** [mrbungle64/ioBroker.ecovacs-deebot#119]
serwus

also modul 1.0.10 release
ozmo 950 ;-)

ich habs mal als frage gemacht da ich selbst nicht ganz sicher bin ob es ein fehler ist oder einfach von ecovacs so gemeint ist.

jedenfalls ich möchte mir gerne ein automatisiertes skript basteln womit ich feststellen kann ob ein raum erreichbar ist oder nicht bzw eben aktualisieren und dann einen custom auftrag geben kann wo der roboter alles hin soll.

beim testen ist mir jetzt folgendes aufgefallen wenn ich die türe zu mache und den roboter vor die türe schicke dann wird auf der karte eingezeichnet das die türe zu ist - soweit so gewollt.

aber im modul wird die spotarea die quasi hinter der türe wäre nicht als false deklariert. wenn ich den roboter in diese - nicht  mehr erreichbare - area schicke dann steht er vor der türe, versucht herum und bricht es irgendwann ab mit "weg blockiert".

selbst dann wird die area nicht als nicht mehr erreichbar deklariert.

finde ich sehr eigenartig, jetzt ist natürlich die frage ist es ein fehler im modul oder sind die werte vom ozmo nicht klar?
er lässt mich ja nachwievor die area - die nicht mehr erreichbar ist - auswählen und ich kann ihn sagen er soll dahin reinigen - steht dann eben vor der türe und bricht es irgendwann ab.

ist das so nicht möglich? bekommst du da nicht die meldung das die area nicht mehr erreichbar ist oder denke ich hier falsch?

**Comment by mrbungle64** [comment]
Hallo @krobipd 

da muss ich Dich leider enttäuschen - das war so nie gedacht ...
Der Datenpunkt heißt ja auch "spotAreaIsAvailable" und nicht "spotAreaIsAccessible" oder "spotAreaIsReachable" 😉 
Als Beschreibung heißt es ja auch "Is the SpotArea still available?" (bedeutet so viel wie "Ist die SpotArea noch verfügbar/gültig?")

Der Wert wird initial auf `true` gesetzt - und wenn die SpotArea irgendwann nicht mehr gültig ein sollte würde das auf `false` gesetzt werden. Ich gebe zu: der praktische Nutzen hällt sich so in Grenzen, aber wir haben das ja auch nie als Feature "verkauft" 😉 

> er lässt mich ja nachwievor die area - die nicht mehr erreichbar ist - auswählen und ich kann ihn sagen er soll dahin reinigen - steht dann eben vor der türe und bricht es irgendwann ab.

Das ist doch mit der Mobile App das gleiche ... Nur mit dem Unterschied, dass dort die Karte an der Stelle angepasst wird und man die Tür erkennen kann. Der Bereich ist aber ja weiterhin eingezeichnet und auch verfügbar.
Wäre ja auch schlimm, wenn der das nächste mal sich weigern würde den Bereich anzufahren, nur weil mal die Tür zu war.

Versteh mich nicht falsch - ich finde die Idee sehr interessant und kann den Use Case absolut nachvollziehen.
Wir können das als Feature Request aufnehmen - nur würde ich spontan die Wahrscheinlichkeit als eher gering ansehen, dass da mal was praktisch umgesetzt wird. Mir ist bisher nämlich nicht bekannt, dass einem die Ecovacs API da was "an die Hand" gibt.

**Comment by krobipd** [comment]
serwus

vielen dank für deine flotte und ausführliche antwort.

ok :-( ok sehr schade, du hast natürlich recht das es der app auch egal ist und er den roboter hinschickst obwohl er nicht hin kann.

dann muss ich diese idee momentan mal begraben, sehr schade.
