### ISSUE TITLE
Gesonderten Bereich Reinigen

### ISSUE THREAD

**Issue by Obelix411** [mrbungle64/ioBroker.ecovacs-deebot#121]
Guten Tag ist es möglich den Sauger zu einer Position zu schicken und ihn dort einen Bereich reinigen zu lassen ?
MFG

**Comment by mrbungle64** [comment]
> Guten Tag ist es möglich den Sauger zu einer Position zu schicken und ihn dort einen Bereich reinigen zu lassen ?
> MFG

Hallo @Obelix411 

Ja, aber das ist natürlich auch vom Modell abhängig.
Auf welches Modell bezieht sich denn die Frage?

Es gibt auch verschiedene Möglichkeiten das zu machen.
Geht es darum einen definierten Bereich aus der Ecovacs zu reinigen oder wirklich darum eine Position zu bestimmen und um diese eine Spot Reinigung zu starten?

**Comment by Obelix411** [comment]
Das Modell ist  Ozmo 900 und ich würde ihn gerne zu einem Bereich schicken und den dann reinigen

**Comment by mrbungle64** [comment]
@Obelix411 

Es gibt unter "control" den Datenpunkt "spotArea". Dort kannst Du - beginnend mit der Nummer 0 - die vordefinierten Bereiche ansteuern.

Mir war aber gar nicht mehr bewusst, dass für den OZMO 900 der "map" Channel gar nicht freigegeben ist.
Dort sind sämtliche Informationen und Befehle für die Bereiche und anderes bzgl. der Karte versammelt.
Ich werde das mit der nächsten Version dann mal für den OZMO 900 freigeben.
Bis dahin kannst Du es aber wie gesagt auch schon über den Datenpunkt "control.spotArea" steuern.

Es ist auch möglich mehrere Bereiche am Stück reinigen zu lassen und dabei die Reihenfolge zu bestimmen.
Als Beispiel: "5, 3, 9, 11, 0". Also Komma-separiert als Wert in den Datenpunkt eintragen.

Welche Nummer zu welchem Bereich aus der App passt müsstest Du ausprobieren.
Der Bereich mit der Ladestation sollte aber die Nummer 0 sein. Dort könnest Du beginnen das mal anzutesten.

**Comment by Obelix411** [comment]
Das mit den Spot area ist bei mir Schönborn betrieb ich möchte jetzt das ich ihn z.b unterm Wohnzimmertisch saugen lasse momentan mach ich das ja über die App ( benutzerdefinierte Reinigung )

**Comment by Obelix411** [comment]
Der map Channel ist freigegeben aber Go top Position finde ich da nirgends

**Comment by mrbungle64** [comment]
> Der map Channel ist freigegeben aber Go top Position finde ich da nirgends

Eigentlich dürfte der "map" Channel beim OZMO 900 gar nicht freigeben sein 🤔 

Eine benutzerdefinierte Reinigung kannst Du auch starten wenn Du die Koordinaten vom Bereich kennst ...
Hast Du den Datenpunkt "map.lastUsedCustomAreaValues_save"?

**Comment by Obelix411** [comment]
das sehe ich bei map
![image](https://user-images.githubusercontent.com/69235992/105590444-5a81da80-5d92-11eb-8f76-63a7334492c8.png)

**Comment by Obelix411** [comment]
sehe also nur meine vw mehr nicht

**Comment by mrbungle64** [comment]
> das sehe ich bei map
> ![image](https://user-images.githubusercontent.com/69235992/105590444-5a81da80-5d92-11eb-8f76-63a7334492c8.png)

Ah ok, Du hast "Erzeuge Datenpunkte für virtuelle Begrenzungen" aktiviert...
Da fehlt aber eine ganze Menge vom "map" Channel.

Welche Version vom Adapter hast Du aktuell installiert?

**Comment by Obelix411** [comment]
1.0.10 (0.5.4)

**Comment by mrbungle64** [comment]
> 1.0.10 (0.5.4)

ok, hast Du heute ein bisschen Zeit die Funktionen zu testen?
Dann würde ich direkt eine Version auf GitHub veröffentlichen wo die Funktionen für den OZMO 900 freigeben sind.

**Comment by Obelix411** [comment]
ja gerne

**Comment by mrbungle64** [comment]
> ja gerne

ok, mit der 1.0.11-alpha.0 von GitHub sollten jetzt eine ganze Menge Datenpunkte mehr unter "map" erscheinen.

Wenn Du jetzt z.B. vorhast unter dem Wohnzimmertisch regelmäßig gesondert saugen zu lassen, dann starte einmalig den Bereich von der Map aus.
Dann erscheinen die Koordinaten unter "map.lastUsedCustomAreaValues". Diese kannst Du Dir entweder merken/notieren oder mit "map.lastUsedCustomAreaValues_save" speichern.
Der gepeicherte Bereich erscheint dann unter "map.savedCustomAreas" als Button - so dass Du das immer direkt wieder starten kannst.

**Comment by Obelix411** [comment]
super werde es jetzt mal testen Vielen dank für den super support und die schnelle hilfe weiter so

**Comment by Obelix411** [comment]
So erster Test erfolgreich läuft genau so wie ich mir das vorgestellt habe
