### ISSUE TITLE
Control problem with Deebot Ozmo 900

### ISSUE THREAD

**Issue by rebel1985** [mrbungle64/ioBroker.ecovacs-deebot#123]
Software version (please complete the following information):

    Library version:
    Source: "npm", 7.5.3
    Node.js version: 10.23.3
    Adapter  1.1.0
    Operating system: raspian
    Hardware: Raspberry Pi 4

Deebot model (please complete the following information):

    Model name: Deebot Ozmo 900
    Deebot ozmo 900

Describe the bug
control problem with deebot Ozmo 900
vor 3-6 wochen oder so ging alles über den adapter wunderbar mittlerweile oft probleme

Additional context
kann starten aber nicht stoppen, mehrfach den adapter neu gestartet, und auch neu angemeldet.
der fehler ist manchmal da oft passiert es auch das dann nach dem betätigen eines objekt z.b. clean dann der deebot nicht mehr im wlan ist oder über die handy app erreichbar ist... dann ein hardware reset am bot selbst hilft dann läuft es mal wieder
und dann hakt es mal wieder mit den objekt verknüpfungen....
ist da vllt. was mit der handy app bzw. deebot server und iobroker adapter nicht ganz okay, also die verbindung?

**Comment by mrbungle64** [comment]
@rebel1985 

> ist da vllt. was mit der handy app bzw. deebot server und iobroker adapter nicht ganz okay, also die verbindung?

Das sieht stark danach aus als hätte der Adapter damit nichts zu tun...
Also wenn der Deebot auch für die Mobile App nicht mehr erreichbar ist musst Du woanders nach einem Fehler schauen.
Ich befürchte, dass ich Dir da nicht helfen kann.

**Comment by mrbungle64** [comment]
@rebel1985 

Ich habe mir das noch mal in Ruhe durchgelesen - das ist gar nicht so einfach weil da viele Satzzeichen fehlen ;)

Heißt das, dass die Probleme mit der Mobile App bzw. die Verbindungsprobleme nur auftreten, wenn Du einen Befehl aus dem Adapter raus abgesetzt hast?

**Comment by mrbungle64** [comment]
@rebel1985 

> vor 3-6 wochen oder so ging alles über den adapter wunderbar

Erinnerst Du Dich noch was das für eine Version gewesen ist?

**Comment by mrbungle64** [comment]
@rebel1985 

Sind die Datenpunkte des Adapters noch alle wie der Adapter die erstellt hat?
Ich bitte um weitere Infos  - ich kann so nur spekulieren, was da bei Dir schief läuft ...

**Comment by mrbungle64** [comment]
@rebel1985 

Ich ändere mal den Titel in "Control problem with Deebot Ozmo 900" (kommmt aus Deiner Beschreibung), da Du ja schon direkt danach fragst, ob es sich um Probleme mit der Verbindung handeln könnte (und dann eben nicht um Bugs).

**Comment by mrbungle64** [comment]
@rebel1985 

Der Issue wird nun erst mal geschlossen.
Wenn man ein Problem meldet sollte man sich auch die Zeit nehmen Rückfragen zu beantworten...
Solltest Du dazu bereit sein kannst Du den Issue gerne wieder öffnen und um die notwendigen Infos ergänzen.

**Comment by rebel1985** [comment]
hi sorry aber hatte nen stressigen arbeitstag und heute noch nciht die zeit gefunden sinngemäß darauf zu antworten. da auch noch wo anders ein problem im smarthome hängt

**Comment by mrbungle64** [comment]
@mrbungle64 

Die aktuell installierte Version kannst Du mir ja zumindest schon mal verraten, oder? 😉 

Und bei folgender Frage reicht auch ein "ja" oder "nein":
> Heißt das, dass die Probleme mit der Mobile App bzw. die Verbindungsprobleme nur auftreten, wenn Du einen Befehl aus dem Adapter raus abgesetzt hast?

**Comment by rebel1985** [comment]
hi,
ja bis lang trat das problem zu 90% auf nach dem ich (wir) über den adapter (iqontrol felder , verlinkung) den deebot gestartet hatten und dann merkten irgendwie will er nicht oder beim 2. versuch nimmt er nichts an. alexa steuerung komischer weise (sprache) ging dann wieder mal.
auch das skript bzgl. der auto steuerung (keiner zu hause bzw. keiner im wlan) sollte den starten über den button so wie es auch letztes jahr immer funktionierte, klappt mittlerweile nicht.
adapter version ist 1.1.0
wie ist das mit der libary  (das was über die bash installiert wird , komando zeile) kann ich mir da ein fehler eingefangen haben bei einem manuellem update?

die datenpunkte sind auch alle da, bzw. es sind ja auch mehr geworden. aber die grundfunktionen sind da und als button hinterlegt zum drücken.
naja nur die reinigungs map is nicht immer passend zur reinigung (is nicht wichtig)

die alten versionen weis ich nciht mehr aber glaube was mit 0.9.x

ja copy paste war mir gerade danacht... die issue seite hatte mich dann doch etwas überfordert mit den fragen und angeben  ;-)

**Comment by mrbungle64** [comment]
> hi,
> ja bis lang trat das problem zu 90% auf nach dem ich (wir) über den adapter (iqontrol felder , verlinkung) den deebot gestartet hatten und dann merkten irgendwie will er nicht oder beim 2. versuch nimmt er nichts an. alexa steuerung komischer weise (sprache) ging dann wieder mal.

Wird der Befehl an den Roboter bei der Alexa Steuerung auch über den ioBroker (Adapter) ausgeführt?

> auch das skript bzgl. der auto steuerung (keiner zu hause bzw. keiner im wlan) sollte den starten über den button so wie es auch letztes jahr immer funktionierte, klappt mittlerweile nicht.

Ich dachte der Start der Reinigung würde funktionieren ("kann starten aber nicht stoppen"), oder hatte ich da was falsch verstanden?

> adapter version ist 1.1.0
> wie ist das mit der libary (das was über die bash installiert wird , komando zeile) kann ich mir da ein fehler eingefangen haben bei einem manuellem update?

Was hast Du genau getan und warum führst Du ein manuelles Update der Library durch? 🤔 

> 
> die datenpunkte sind auch alle da, bzw. es sind ja auch mehr geworden. aber die grundfunktionen sind da und als button hinterlegt zum drücken.
> naja nur die reinigungs map is nicht immer passend zur reinigung (is nicht wichtig)
> 
> die alten versionen weis ich nciht mehr aber glaube was mit 0.9.x

Eine 0.9.x gab es nicht. Ich frag mal anders:
Welches ioBroker Repo (siehe "Aktiver Verwahrungsort") verwendest Du?
* Stable (default)
* Beta (latest)

> 
> ja copy paste war mir gerade danacht... die issue seite hatte mich dann doch etwas überfordert mit den fragen und angeben ;-)

Tjo, dann hab ich halt umso mehr Arbeit und es dauert länger bis wir herausfinden was das Problem ist ...

**Comment by rebel1985** [comment]
> 
> 
> > hi,
> > ja bis lang trat das problem zu 90% auf nach dem ich (wir) über den adapter (iqontrol felder , verlinkung) den deebot gestartet hatten und dann merkten irgendwie will er nicht oder beim 2. versuch nimmt er nichts an. alexa steuerung komischer weise (sprache) ging dann wieder mal.
> 
> Wird der Befehl an den Roboter bei der Alexa Steuerung auch über den ioBroker (Adapter) ausgeführt?
> 
> > auch das skript bzgl. der auto steuerung (keiner zu hause bzw. keiner im wlan) sollte den starten über den button so wie es auch letztes jahr immer funktionierte, klappt mittlerweile nicht.
> 
> Ich dachte der Start der Reinigung würde funktionieren ("kann starten aber nicht stoppen"), oder hatte ich da was falsch verstanden?
> 
> > adapter version ist 1.1.0
> > wie ist das mit der libary (das was über die bash installiert wird , komando zeile) kann ich mir da ein fehler eingefangen haben bei einem manuellem update?
> 
> Was hast Du genau getan und warum führst Du ein manuelles Update der Library durch? 🤔
> 
> > die datenpunkte sind auch alle da, bzw. es sind ja auch mehr geworden. aber die grundfunktionen sind da und als button hinterlegt zum drücken.
> > naja nur die reinigungs map is nicht immer passend zur reinigung (is nicht wichtig)
> > die alten versionen weis ich nciht mehr aber glaube was mit 0.9.x
> 
> Eine 0.9.x gab es nicht. Ich frag mal anders:
> Welches ioBroker Repo (siehe "Aktiver Verwahrungsort") verwendest Du?
> 
>     * Stable (default)
> 
>     * Beta (latest)
> 
> 
> > ja copy paste war mir gerade danacht... die issue seite hatte mich dann doch etwas überfordert mit den fragen und angeben ;-)
> 
> Tjo, dann hab ich halt umso mehr Arbeit und es dauert länger bis wir herausfinden was das Problem ist ...

stand auf beta, grad umgeändert auf stable 
warum kp. sollte eig stable immer gewesen sein.
ne alexa macht das übers alexa plugin
dachte versuch es mal als problem lösung aber hmm unverändert....
hast ja 2 treads hier. adapter und dann die andere variante libary dings da...

start ja und danach gibts ja dann die probs...
dann mach ich nen robo reset oder neustart...
dann läufts erst wieder...
ja der skript start muss ich noch mal gucken.... bis lang lief der... aber vllt. kann das skript den button nciht.
aber der direkte datenpunkt butten start läuft aber dann ja wie oben....

**Comment by mrbungle64** [comment]
> 
> stand auf beta, grad umgeändert auf stable
> warum kp. sollte eig stable immer gewesen sein.
> ne alexa macht das übers alexa plugin
> dachte versuch es mal als problem lösung aber hmm unverändert....
> hast ja 2 treads hier. adapter und dann die andere variante libary dings da...
> 
> start ja und danach gibts ja dann die probs...
> dann mach ich nen robo reset oder neustart...
> dann läufts erst wieder...
> ja der skript start muss ich noch mal gucken.... bis lang lief der... aber vllt. kann das skript den button nciht.
> aber der direkte datenpunkt butten start läuft aber dann ja wie oben....

@rebel1985 

Deine Antwort frustriert mich einfach nur ...

**Comment by mrbungle64** [comment]
@rebel1985 

Ich sehe gerade, dass ich nicht der einzige bin:
https://forum.iobroker.net/topic/41655/zigbee-bleibt-rot

Ich schließe den Issue jetzt wieder. Du kannst gerne einen neuen Issue erstellen, wenn Du Dein System wieder sauber aufgesetzt hast (siehe auch "zigbee-bleibt-rot" Topic) und dann bereit bist die Leute - welche Du um Hilfe bittest - dabei zu unterstützen Dir überhaupt helfen zu können...

**Comment by rebel1985** [comment]
wieso schon wieder geschlossen? gab doch noch keine lösung...
zigbee ist nicht  gleich deebot adapter, zigbee läuft wieder und falls du node.js und npm meinst das is auch gerade gezogen.
war aber vorher nicht bestandteil, es leif die letzten monate (ca. 12 + ) so wie es war. erst dieses jahr ggf. mit nem update von allem inkl. diesen adapter tauchten die probleme auf. ich nutze iqontrol als direkte verknüpfung zum datenpunkt. wenn danach dann der deebot zicken macht hat es nichts mit zigbee zu tuhn. une meine antwortzeiten sind halt so wegen meinen arbeitszeit von früh morgens bis spät abends in der maschinen industrie und dann gibts noch andere verpflichtungen zu hause das man nicht immer jeden tag oder stunde zeit hat zu antworten. der text ist ja geduldig.
bis lang gabs keine lösungs ansätze nur fragen.
kurzfassung
debot saugt ober datenpunkt steuerung und hinterher fliegt er ausm wlan oder reagiert nicht mehr. verfängt sich beim neustarten usw. wlan ist unverändert und läuft stabiel wien schweizer uhrwerk (aka fritzbox) deeboit steuerung via alexa klappt da gibts keine ausfälle (zumindest keine bakennten) mein skript ist mehr als einfach und lief über 6 monate zuverlässig mit der autosteuerung wenn keiner zu hause ist das automatisch gesaugt wird (besser als das in der app) mittlerweile läufts nicht mehr bzw. regiert aber die adapter / datenpunkt ansteuerung klappt anscheinend nicht.... warum auch was da nun anders ist.

**Comment by mrbungle64** [comment]
@rebel1985 
Du bist also der Meinung, dass Du ein Anrecht auf eine Lösung hast?
Glaubst Du, dass Du jetzt eine Art Gewohnheitsrecht darauf hast, weil der Adapter bei Dir nun mehr als 6 Monate seinen Dienst zuverlässig verrichtet hat? Software, welche in meiner Freizeit entstanden ist und zur kostenfreien Benutzung bereit steht.

Noch ein paar Anmerkungen:
- Ich besitze keinen Deebot OZMO 900 - deshalb ist der Deebot OZMO 900 auch nicht bei den supporteten Modellen gelistet
- Es ist im Übrigen meine eigene Entscheidung, wieviel Zeit ich dafür investiere ein gemeldetes Problem zu lösen
- Dass man die Ecovacs Saugroboter überhaupt per ioBroker Adapter (und anderer Open Source Software) steuern kann ist nur möglich, weil ich und andere Entwickler viel (Frei-)Zeit dafür aufwenden, um so was wie eine "libary dings da" (sic) zu entwickeln

**Comment by rebel1985** [comment]
naja ein problem ist problem, und zudem habe ich am anfang ja auch oft in meiner freizeit daten geliefert um das zum laufen zu bekommen das du das programmieren kannst. also hätte ich theoretisch auch das recht für eine problem lösung was nun nicht mehr so läuft was verändert worden ist oder so....
und in der freizeit zu programmiert war mir schon klar.
daher sollte das eig verständlich sein das ich auch nur in meiner freizeit (coroan hin oder her) auch antworte oder es einfach mal 1-2 tage nicht schaffe.
mehr als ständig das problem dar legen kann ich nciht oder was ich selber schon vorab in eigen regier versucht habe zu probieren kann ich nciht da ich es ja nciht geschrieben habe das programm.

**Comment by mrbungle64** [comment]
> und zudem habe ich am anfang ja auch oft in meiner freizeit daten geliefert um das zum laufen zu bekommen das du das programmieren kannst. also hätte ich theoretisch auch das recht für eine problem lösung was nun nicht mehr so läuft was verändert worden ist oder so....

Mal langsam: Du hast Daten geliefert, damit Dein (!) Deebot OZMO 900 ebenfalls funktioniert.

**Comment by rebel1985** [comment]
> 
> 
> > und zudem habe ich am anfang ja auch oft in meiner freizeit daten geliefert um das zum laufen zu bekommen das du das programmieren kannst. also hätte ich theoretisch auch das recht für eine problem lösung was nun nicht mehr so läuft was verändert worden ist oder so....
> 
> Mal langsam: Du hast Daten geliefert, damit Dein (!) Deebot OZMO 900 ebenfalls funktioniert.

ja ist mir bewust und den adapter hab ich oft durch getestet damit der 900 und 901 läuft und evtl. auch andere ein nutzen haben.
das tut aber ja nun nicht zur sache was er wie wo getahn und mehr oder weniger usw. das ist nur eine diskussion drum rum.
antworten kommen so wie ich es sehe(mail) und zeit habe und das kann auch mal dauern da arbeit und schlaf die meiste zeit am tag verbrauchen.
das problem ist da und es ist im zusammen hang mit dem adapter bzw. dessen steuerung (wird zu 80% darüber gesteuert und fällt einfach auf "mir und meiner partnerin") und irgendwas muss ja anders sein.
das problem ist nun 3 mal beschrieben und noch ungelöst.
der code von der SW ist auch nur so gut wie die rückmeldungen bzw. problem meldungen kommen und behoben werden.

**Comment by mrbungle64** [comment]
@rebel1985 

> das problem ist nun 3 mal beschrieben und noch ungelöst.

Glaubst Du immer noch, dass Du ein Anrecht auf eine Lösung hast?

**Comment by mrbungle64** [comment]
@rebel1985 

Welche Datenpunkte steuerst Du über iQontrol bzw. Dein Skript eigentlich an?
Falls das immer SpotAreas sind (also einzelne Bereiche) kannst Du mal versuchen, ob es was bringt, wenn Du den "map" Ordner löschst. Diese Datenpunkte werden dann neu erstellt. Vielleicht hängt da aktuell was quer.

**Comment by rebel1985** [comment]
moin
ich hatte gestern nachgmittag den adapter owntracks und ecovacs gelöscht, konnts aber noch nicht testen.
70% wird clean angesteuert 20% spot area 10% alexa plugin
umgeändert hab ich auch die skript ansteuerung des clean datenpunktes von (steuere zu aktualisiere)
vorher hat es so immer geklappt gehabt mittlerweile ist der button ein button der fix ist , vllt. klappt so dann die auto ansteuerung des clean datenpunktes .. (hat letztes jahr bis dez. vllt. auch nopch funktioniert gehabt) das skript wurde nie verändert.
maschienenbau und inbetriebnahme regel nummer 1 dont touch a running system.
ps. bin selber im industrie maschienen bau tätig und inbetriebnahme , sind alles maschinen für die produktion

**Comment by mrbungle64** [comment]
@rebel1985 

ok, wenn Du den Adapter schon neu installiert hast werden die Datenpunkte i.d.R. ja neu erstellt.
Dann warten wir mal ab, was Deine Tests ergeben.

**Comment by mrbungle64** [comment]
@rebel1985 
Gibt's was Neues?

**Comment by rebel1985** [comment]
die buttons lassen sich nciht richtig steuern, oder reagieren nciht mehr nach dem clean gestartet wurde.
über umwegen und mit kompletter zugriffsrechter verteilung auf alle ist es irgendwie möglich das die skript engine mit dem skript den roboter wieder steuern kann. vorher hat ich nciht solche sorgen, verknüpfen , testen , und rdy .

**Comment by mrbungle64** [comment]
@rebel1985 

> vorher hat ich nciht solche sorgen, verknüpfen , testen , und rdy .

So sollte es auch sein.

> die buttons lassen sich nciht richtig steuern, oder reagieren nciht mehr nach dem clean gestartet wurde.
über umwegen und mit kompletter zugriffsrechter verteilung auf alle ist es irgendwie möglich das die skript engine mit dem skript den roboter wieder steuern kann.

Welche Zugriffsrechte hast Du modifiziert?

**Comment by mrbungle64** [comment]
@rebel1985 

> die buttons lassen sich nciht richtig steuern, oder reagieren nciht mehr nach dem clean gestartet wurde.
> über umwegen und mit kompletter zugriffsrechter verteilung auf alle ist es irgendwie möglich das die skript engine mit dem skript den roboter wieder steuern kann. vorher hat ich nciht solche sorgen, verknüpfen , testen , und rdy .

Offensichtlich hast Du einen anderen Weg gefunden den Roboter zu steuern.
Somit ist der Adapter hier nicht mehr relevant und dieser Issue auch endgültig geschlossen.
