### ISSUE TITLE
Adapter - Datenpunkt - Control Button _ Deebot OZMO 900

### ISSUE THREAD

**Issue by rebel1985** [mrbungle64/ioBroker.ecovacs-deebot#124]
@rebel1985 

> vorher hat ich nciht solche sorgen, verknüpfen , testen , und rdy .

So sollte es auch sein.

> die buttons lassen sich nciht richtig steuern, oder reagieren nciht mehr nach dem clean gestartet wurde.
über umwegen und mit kompletter zugriffsrechter verteilung auf alle ist es irgendwie möglich das die skript engine mit dem skript den roboter wieder steuern kann.

Welche Zugriffsrechte hast Du modifiziert?
Wenn Du Zugriffsrechte modifizieren musst, damit Adapter "korrekt" funktionieren, dann stimmt was anderes nicht.

_Originally posted by @mrbungle64 in https://github.com/mrbungle64/ioBroker.ecovacs-deebot/issues/123#issuecomment-784339320_

**Comment by rebel1985** [comment]
Objekt bearbeiten ecovacs-deebot.0.control.charge
zugriff auf admin und zugriff auf rechte zusätzlich auf jeder.

**Comment by rebel1985** [comment]
![Unbenannt](https://user-images.githubusercontent.com/59134497/108889044-2f4a0f80-760c-11eb-81e8-0efe7181a30d.JPG)

**Comment by mrbungle64** [comment]
> Objekt bearbeiten ecovacs-deebot.0.control.charge
> zugriff auf admin und zugriff auf rechte zusätzlich auf jeder.

Warum machst Du das?

**Comment by rebel1985** [comment]
las test obs dann funktioniert, da bis lang nicht anderes hilft oder half ... irgendwas muss ja in updates anders gelaufen sein, npm usw. war ja vorher angeblich auch falsch aber es funktionierte trotzdem

**Comment by mrbungle64** [comment]
> las test obs dann funktioniert, da bis lang nicht anderes hilft oder half ... irgendwas muss ja in updates anders gelaufen sein, npm usw. war ja vorher angeblich auch falsch aber es funktionierte trotzdem

Nein, das bedeutet eher, dass Du irgendwas in Deinem System vorher schon modifiziert hast und damit die Stabilität Deines Systems auf's Spiel gesetzt hast ...

> und weils möglich ist und ich es vom system her machen kann ;-)

Ja so bekommt man funktionierende Software kaputt 😉

**Comment by rebel1985** [comment]
> 
> 
> > las test obs dann funktioniert, da bis lang nicht anderes hilft oder half ... irgendwas muss ja in updates anders gelaufen sein, npm usw. war ja vorher angeblich auch falsch aber es funktionierte trotzdem
> 
> Nein, das bedeutet eher, dass Du irgendwas in Deinem System vorher schon modifiziert hast und damit die Stabilität Deines Systems auf's Spiel gesetzt hast ...
> 
> > und weils möglich ist und ich es vom system her machen kann ;-)
> 
> Ja so bekommt man funktionierende Software kaputt 😉


und was oder in welche richtung soll das gehen?

zugriffsrechte auf was bezogen?
naja sicherheit des systems in einem heimnetz bzw. unter heimnetz abgesichert mit pihole und passwörtern ist erstmal 2. ranging.
wichtiger ist. was wie wo wurde geändert und welche code zeilen passen nciht zusammen oder machen einen fehler, auch entwicklungssoftware funktioniert nicht reibungslos, kenne ich von meiner arbeit mit entwicklungssystemen das jeder software schreiber auch fehler macht oder es zu fehlern kommen kann im code 


naja das was möglich ist ist aktiviert und kurztest heute funktionierte....

**Comment by mrbungle64** [comment]
@rebel1985 

> naja das was möglich ist ist aktiviert und kurztest heute funktionierte....

Können wir den Issue dann jetzt schließen?

**Comment by mrbungle64** [comment]
@rebel1985 

> zugriffsrechte auf was bezogen?

Das musst Du mir erklären. Ich habe niemals gesagt, dass irgendwelche Zugriffsrechte hier relevant sind.

**Comment by rebel1985** [comment]
naja ich hab ja am zugriff was gemacht auf jeder und iqontroll auch noch mal schreiben erlaubt...
hast du die button funktion vllt. verändern oder eingeschränkt?
um die gehts nähmlich mit dem ansteuern....

**Comment by rebel1985** [comment]
> 
> 
> @rebel1985
> 
> > naja das was möglich ist ist aktiviert und kurztest heute funktionierte....
> 
> Können wir den Issue dann jetzt schließen?

nachm test und vllt. einer lösung der ursache und nicht nur das ist was anderes.... is nur ein abschieben und das problem ist ja dann laut deiner aussage immer noch da

**Comment by rebel1985** [comment]
wie gesagt vorher lief alles wunderbar und wir waren voll happy und habs auch immer positiv erwähnt und versucht anzupreisen das das mit dem skript - deinem adapter - und ggf. owntracks eine top sache ist ohne das man die handy app braucht....

**Comment by mrbungle64** [comment]
> > @rebel1985
> > > naja das was möglich ist ist aktiviert und kurztest heute funktionierte....
> > 
> > 
> > Können wir den Issue dann jetzt schließen?
> 
> nachm test und vllt. einer lösung der ursache und nicht nur das ist was anderes.... is nur ein abschieben und das problem ist ja dann laut deiner aussage immer noch da

"is nur ein abschieben" ist wieder nicht besonders freundlich.
Dir ist schon klar, dass ich den Issue trotzdem jederzeit schließen kann?
Ich erinnere daran, dass ich nicht verpflichtet bin Dein Problem zu lösen...

**Comment by mrbungle64** [comment]
> hast du die button funktion vllt. verändern oder eingeschränkt?

Seit der Version 1.0.8 wird der Wert der Buttons "control.charge", "control.pause", "control.stop" und "control.clean" autom. anhand "this.deviceStatus" gesetzt.
Wenn Dein Skript darauf triggered oder die Werte ebenfalls modifiziert, dann kann es da Wechselwirkungen geben.
Da solltest Du Dein Skript mal drauf prüfen.

**Comment by rebel1985** [comment]
> 
> 
> > > @rebel1985
> > > > naja das was möglich ist ist aktiviert und kurztest heute funktionierte....
> > > 
> > > 
> > > Können wir den Issue dann jetzt schließen?
> > 
> > 
> > nachm test und vllt. einer lösung der ursache und nicht nur das ist was anderes.... is nur ein abschieben und das problem ist ja dann laut deiner aussage immer noch da
> 
> "is nur ein abschieben" ist wieder nicht besonders freundlich.
> Dir ist schon klar, dass ich den Issue trotzdem jederzeit schließen kann?
> Ich erinnere daran, dass ich nicht verpflichtet bin Dein Problem zu lösen...

naja immer schliesen und nicht versuchen zu klären ist auch nciht freundlich, das ist nur eine tatsache.

**Comment by mrbungle64** [comment]
> > > > @rebel1985
> > > > > naja das was möglich ist ist aktiviert und kurztest heute funktionierte....
> > > > 
> > > > 
> > > > Können wir den Issue dann jetzt schließen?
> > > 
> > > 
> > > nachm test und vllt. einer lösung der ursache und nicht nur das ist was anderes.... is nur ein abschieben und das problem ist ja dann laut deiner aussage immer noch da
> > 
> > 
> > "is nur ein abschieben" ist wieder nicht besonders freundlich.
> > Dir ist schon klar, dass ich den Issue trotzdem jederzeit schließen kann?
> > Ich erinnere daran, dass ich nicht verpflichtet bin Dein Problem zu lösen...
> 
> naja immer schliesen und nicht versuchen zu klären ist auch nciht freundlich, das ist nur eine tatsache.

Das ist eine Unterstellung und keine Tatsache.

**Comment by rebel1985** [comment]
> 
> 
> > hast du die button funktion vllt. verändern oder eingeschränkt?
> 
> Seit der Version 1.0.8 wird der Wert der Buttons "control.charge", "control.pause", "control.stop" und "control.clean" autom. anhand "this.deviceStatus" gesetzt.
> Wenn Dein Skript darauf triggered oder die Werte ebenfalls modifiziert, dann kann es da Wechselwirkungen geben.
> Da solltest Du Dein Skript mal drauf prüfen.

das skript geht direkt auf die buttons mit 
steuere ... mit ... mit verzögerung
"steuere clean mit wahr an"

**Comment by rebel1985** [comment]
> 
> 
> > > > > @rebel1985
> > > > > > naja das was möglich ist ist aktiviert und kurztest heute funktionierte....
> > > > > 
> > > > > 
> > > > > Können wir den Issue dann jetzt schließen?
> > > > 
> > > > 
> > > > nachm test und vllt. einer lösung der ursache und nicht nur das ist was anderes.... is nur ein abschieben und das problem ist ja dann laut deiner aussage immer noch da
> > > 
> > > 
> > > "is nur ein abschieben" ist wieder nicht besonders freundlich.
> > > Dir ist schon klar, dass ich den Issue trotzdem jederzeit schließen kann?
> > > Ich erinnere daran, dass ich nicht verpflichtet bin Dein Problem zu lösen...
> > 
> > 
> > naja immer schliesen und nicht versuchen zu klären ist auch nciht freundlich, das ist nur eine tatsache.
> 
> Das ist eine Unterstellung und keine Tatsache.

ansichtssache und sichtweise

**Comment by mrbungle64** [comment]
> > > hast du die button funktion vllt. verändern oder eingeschränkt?
> > 
> > 
> > Seit der Version 1.0.8 wird der Wert der Buttons "control.charge", "control.pause", "control.stop" und "control.clean" autom. anhand "this.deviceStatus" gesetzt.
> > Wenn Dein Skript darauf triggered oder die Werte ebenfalls modifiziert, dann kann es da Wechselwirkungen geben.
> > Da solltest Du Dein Skript mal drauf prüfen.
> 
> das skript geht direkt auf die buttons mit
> steuere ... mit ... mit verzögerung
> "steuere clean mit wahr an"

Exportiere bitte mal das Skript und häng es als Datei hier an.
Dann schaue ich es mir mal an.

**Comment by rebel1985** [comment]
[Status_saugroboter.txt](https://github.com/mrbungle64/ioBroker.ecovacs-deebot/files/6031649/Status_saugroboter.txt)
[Deebot_Autostart.txt](https://github.com/mrbungle64/ioBroker.ecovacs-deebot/files/6031650/Deebot_Autostart.txt)

nachm anpassen auf jeder, gabs auch eine ansteuerung des robos wo freundin später nach hause kahm
das der Maldung vom deebot: "deebot ist  schon in der ladestation"

vor musste ich nur den passenden blockly block finden und es lief alles, naja die datenpunkte setzten und die abfragen dahinter.

**Comment by mrbungle64** [comment]
@rebel1985 

> [Status_saugroboter.txt](https://github.com/mrbungle64/ioBroker.ecovacs-deebot/files/6031649/Status_saugroboter.txt)
> [Deebot_Autostart.txt](https://github.com/mrbungle64/ioBroker.ecovacs-deebot/files/6031650/Deebot_Autostart.txt)

Die Skripte sehen ja soweit in Ordnung aus. Ich verstehe zwar nicht so ganz, warum Du noch mal "stop" kurz vor "charge" ausführst, aber das hat mit der Problematik hier eher nichts zu tun.

> 
> nachm anpassen auf jeder, gabs auch eine ansteuerung des robos wo freundin später nach hause kahm
> das der Maldung vom deebot: "deebot ist schon in der ladestation"

Was möchtest Du mir damit sagen?

> 
> vor musste ich nur den passenden blockly block finden und es lief alles, naja die datenpunkte setzten und die abfragen dahinter.

Auch das verstehe ich nicht ... Heißt das, dass heute alles soweit funktioniert hat?

**Comment by mrbungle64** [comment]
@rebel1985

> > > > > > @rebel1985
> > > > > > > naja das was möglich ist ist aktiviert und kurztest heute funktionierte....
> > > > > > 
> > > > > > 
> > > > > > Können wir den Issue dann jetzt schließen?
> > > > > 
> > > > > 
> > > > > nachm test und vllt. einer lösung der ursache und nicht nur das ist was anderes.... is nur ein abschieben und das problem ist ja dann laut deiner aussage immer noch da
> > > > 
> > > > 
> > > > "is nur ein abschieben" ist wieder nicht besonders freundlich.
> > > > Dir ist schon klar, dass ich den Issue trotzdem jederzeit schließen kann?
> > > > Ich erinnere daran, dass ich nicht verpflichtet bin Dein Problem zu lösen...
> > > 
> > > 
> > > naja immer schliesen und nicht versuchen zu klären ist auch nciht freundlich, das ist nur eine tatsache.
> > 
> > 
> > Das ist eine Unterstellung und keine Tatsache.
> 
> ansichtssache und sichtweise

"und nicht versuchen zu klären" ist eine Unterstellung. Punkt.

Ich hatte Dir im [anderen Issue](https://github.com/mrbungle64/ioBroker.ecovacs-deebot/issues/123) vor einigen Tagen den [Thread](https://forum.iobroker.net/topic/41655/zigbee-bleibt-rot) vom ioBroker Forum verlinkt, wo Dein Verhalten ebenfalls mehreren Leuten sauer aufgestoßen war. Bitte überdenke mal Dein Verhalten. So verärgerst Du nur die Leute, die eigentlich gewillt sind Dir gerne zu helfen.

Ich weiße Dich jetzt also ein letztes Mal darauf hin, dass
- der Deebot OZMO 900 nicht zu den supporteten Modellen gehört
- und Du unabhängig davon auch kein Anrecht darauf hast, dass ich Dein Problem löse

Ich bin gerne weiterhin bereit es trotzdem zu versuchen, aber das geschieht weiterhin freiwillig und ist weiterhin abhängig davon, ob mich Dein Verhalten dazu motiviert oder vielleicht auch nicht.

**Comment by rebel1985** [comment]
> 
> 
> @rebel1985
> 
> > [Status_saugroboter.txt](https://github.com/mrbungle64/ioBroker.ecovacs-deebot/files/6031649/Status_saugroboter.txt)
> > [Deebot_Autostart.txt](https://github.com/mrbungle64/ioBroker.ecovacs-deebot/files/6031650/Deebot_Autostart.txt)
> 
> Die Skripte sehen ja soweit in Ordnung aus. Ich verstehe zwar nicht so ganz, warum Du noch mal "stop" kurz vor "charge" ausführst, aber das hat mit der Problematik hier eher nichts zu tun.

das habe ich gestern geändert gehabt weil der button charge nicht funktioniert hatte. also versuche ich mir irgendwie selber zu helfen mit ich versuche was ähnlich wie try and error
normal steht im skript start clean und go to charge
jenach ob wer zu hause ist oder nicht.

> 
> > nachm anpassen auf jeder, gabs auch eine ansteuerung des robos wo freundin später nach hause kahm
> > das der Maldung vom deebot: "deebot ist schon in der ladestation"
> 
> Was möchtest Du mir damit sagen?

ja das was schon bekannt ist das ich den zugriff auf jeder gesetz habe (bei den buttons für die steuerung) wie oben schon geschrieben
und dann kahm freundin nach hause, und vom deebot kahm dann die meldung (so wie es eigentlich war)
aber laut deinen äußerungen und deiner ausdrucksweise ist es ja der falsche weg um das problem zu lösen bzw zu beheben.
sprich es ist nur eine funktionale nutzung (wieder nutzbar machen) aber keine lösung und beseitigung des haupt problems warum es (pauschal seit diesem jahr) nicht mehr funktioniert

> 
> > vor musste ich nur den passenden blockly block finden und es lief alles, naja die datenpunkte setzten und die abfragen dahinter.
> 
> Auch das verstehe ich nicht ... Heißt das, dass heute alles soweit funktioniert hat?

wie oben gesagt steuern die skripte autonom, aber wenn alle zuhause sind ist es umständlich dies zu testen.
sowas braucht halt mal ein paar tage um zu wissen obs läuft damit man sich wieder drauf verlassen kann

laut meiner aktuellen meldung funktionierte mit dem bekannten umstellungen nun der clean (start)

mal sehen was ist wenn ich zu hause bin später (grad at work)

**Comment by rebel1985** [comment]
so wieder das problem, komme nach hause und der robo sagt nichts.
ich teste das skript und die buttons ... er fährt los und jetzt null reaktion vom adapter egal welchen knopf ich in iqontrol öffne oder welchen button ich im datenpunkt öffne es passiert nichts.....
zugriffskontrolle ist alles aktiviert.
alexa adapter sagt auch ncihts auser deebot währe offline
die app sagt nun deebot ist offline fährt aber durch die wohnung...
komisch, übern adapter gestartet und dann komplett weg das ding.... und das problem ich ich letztes jahr nicht so...
und gesaugt hatte er heute morgen schon durch die auto steuerung mit owntracks

**Comment by rebel1985** [comment]
> 
> 
> @rebel1985
> 
> > > > > > > @rebel1985
> > > > > > > > naja das was möglich ist ist aktiviert und kurztest heute funktionierte....
> > > > > > > 
> > > > > > > 
> > > > > > > Können wir den Issue dann jetzt schließen?
> > > > > > 
> > > > > > 
> > > > > > nachm test und vllt. einer lösung der ursache und nicht nur das ist was anderes.... is nur ein abschieben und das problem ist ja dann laut deiner aussage immer noch da
> > > > > 
> > > > > 
> > > > > "is nur ein abschieben" ist wieder nicht besonders freundlich.
> > > > > Dir ist schon klar, dass ich den Issue trotzdem jederzeit schließen kann?
> > > > > Ich erinnere daran, dass ich nicht verpflichtet bin Dein Problem zu lösen...
> > > > 
> > > > 
> > > > naja immer schliesen und nicht versuchen zu klären ist auch nciht freundlich, das ist nur eine tatsache.
> > > 
> > > 
> > > Das ist eine Unterstellung und keine Tatsache.
> > 
> > 
> > ansichtssache und sichtweise
> 
> "und nicht versuchen zu klären" ist eine Unterstellung. Punkt.
> 
> Ich hatte Dir im [anderen Issue](https://github.com/mrbungle64/ioBroker.ecovacs-deebot/issues/123) vor einigen Tagen den [Thread](https://forum.iobroker.net/topic/41655/zigbee-bleibt-rot) vom ioBroker Forum verlinkt, wo Dein Verhalten ebenfalls mehreren Leuten sauer aufgestoßen war. Bitte überdenke mal Dein Verhalten. So verärgerst Du nur die Leute, die eigentlich gewillt sind Dir gerne zu helfen.
> 
> Ich weiße Dich jetzt also ein letztes Mal darauf hin, dass
> 
>     * der Deebot OZMO 900 nicht zu den supporteten Modellen gehört
> 
>     * und Du unabhängig davon auch kein Anrecht darauf hast, dass ich Dein Problem löse
> 
> 
> Ich bin gerne weiterhin bereit es trotzdem zu versuchen, aber das geschieht weiterhin freiwillig und ist weiterhin abhängig davon, ob mich Dein Verhalten dazu motiviert oder vielleicht auch nicht.

sag mal was ist dein problem mit dem anderen forum beitrag wo der eine user nciht freundlich zu mir war und mich angegriffen hat und mich dann noch diste bzw. anmachte wie ich im forum schreibe ob klein oder groß.... und zu dem soll ich dann noch mit flower power antworten....? 
dann sags doch gleich wenn du kein bock dazu hast und ich dir versuche zu helfen um deinen adapter weiter besser zu supporten und eine breite akzeptanz zu geben wie ende 2019 mit den ganzen logs und tests was mir half aber auch dir um deinen code zu schreiben. und nur auf andere zeigen brauch man auch nicht gerade so wie du es verlangst oder meinst es von mir zu verlangen bist du aber auch nicht allein damit das du was aufgegriffen hast was hier nicht zur sache gehört und dann immer was erfragst dann antworte ich nicht schnell genug und schon ist das thema geschlossen... ist jetzt auch nciht so freundlich, und das sieht meine partnerin auch so .... und wie gesagt las das was bei zigbee war bei zigbee und roll nciht ständig was auf was uns und dem problem hier garnicht betraf denn das ist auch nciht freundlich sondern provokannt anstatt es einfach in frieden zu lassen?
würdest du bestimmt auch nciht geil finden. und wenn betragchte beide seiten und was wie geschrieben wurde. meinen und schreiben und auffassen sind unterschiedliche sachen. die person war nicht freundlich bzw. gleich schlecht von der seite angemacht und dann noch in die richtung mich verbal angegriffen. ich schrieb um hilfe und das da null plan von habe und nciht weis was los ist und selber was versuchte und gleich negative von der seite angekackt zu werden ist alles andere als schön und auch nicht das was ich erhoft hatte also gabs dann auch eine negative retour kutsche...

habe ich dich in irgeneiner form schriftlich angegriffen? beleidigt? das du mich immer so fragst und mir das vorhälst....
sprich doch sonst einfach klartext dann weis man was ist oder versuch zu helfen da es von dir ist.... und deboot hin oder her. er funktionierte und wird erkannt und es wird alles ausgelesen was das neue auch sein soll bzw wofür das gut ist... aber wenn die datenpunkte nach neuinstallation nciht funktionieren bzw. der debott dann die verbindung verliert ist schon sehr komisch....
ich mags dann eher so never touch a running system weil es auch verschlimmberssert werden kann.

**Comment by mrbungle64** [comment]
> dann sags doch gleich wenn du kein bock dazu hast und ich dir versuche zu helfen um deinen adapter weiter besser zu supporten

@rebel1985 
Wo und wann habe ich Dich um Hilfe gebeten?
Und jetzt komm mir nicht mit Ende 2019 - damals ging es darum den OZMO 900 (!) zum Laufen zu bringen.
Und seit dem hast Du (!) einen Nutzen davon.

**Comment by rebel1985** [comment]
> 
> 
> > dann sags doch gleich wenn du kein bock dazu hast und ich dir versuche zu helfen um deinen adapter weiter besser zu supporten
> 
> @rebel1985
> Wo und wann habe ich Dich um Hilfe gebeten?
> Und jetzt komm mir nicht mit Ende 2019 (oder wann auch immer das war)

jop da hast du mich öfters gefragt gehabt... nicht nur robo testen auch knöpfe und ausgaben usw. und hast auch andere gefragt gehabt, hattest da einige mit denen du es abgeglichen hattest.

> Damals ging es darum den OZMO 900 (!) zum Laufen zu bringen.
> Und seit dem hast Du (!) einen Nutzen davon.

und andere auch mit anderen modellen, naja nutzen is grad relativ gesehen.

**Comment by mrbungle64** [comment]
Hier sind sämtliche Issues, an welchen Du beteiligt warst. Kann sich jeder selbst ein Bild von machen, ob ich Dich da "öfters gefragt" habe. Klingt ja fast so als hätte ich darum gebettelt...

* https://github.com/mrbungle64/ioBroker.ecovacs-deebot/issues/5
* https://github.com/mrbungle64/ioBroker.ecovacs-deebot/issues/7
* https://github.com/mrbungle64/ioBroker.ecovacs-deebot/issues/14
* https://github.com/mrbungle64/ioBroker.ecovacs-deebot/issues/76

@rebel1985 
Ich nehme mir jetzt erst mal einen Auszeit was diesen Issue hier betrifft und auch ggf. ebenfalls was den Adapter betrifft.
Wenn mir das jetzt so ausgelegt wird, als würde ich bei Dir und bei anderen in der Schuld stehen, dann ist das nur noch frustrierend. Meine Motivation an dem Adapter zu arbeiten und diesen weiterzuentwickeln ist gerade auf dem Nullpunkt angelangt ...

**Comment by rebel1985** [comment]
> 
> 
> Hier sind sämtliche Issues, an welchen Du beteiligt warst. Kann sich jeder selbst ein Bild von machen, ob ich Dich da "öfters gefragt" habe. Klingt ja fast so als hätte ich darum gebettelt...
> 
>     * #5
> 
>     * #7
> 
>     * #14
> 
>     * #76
> 
> 
> @rebel1985
> Ich nehme mir jetzt erst mal einen Auszeit was diesen Issue hier betrifft und auch ggf. ebenfalls was den Adapter betrifft.
> Wenn mir das jetzt so ausgelegt wird, als würde ich bei Dir und bei anderen in der Schuld stehen, dann ist das nur noch frustrierend. Meine Motivation an dem Adapter zu arbeiten und diesen weiterzuentwickeln ist gerade auf dem Nullpunkt angelangt ...

gebettelt hat keiner gesagt, und wie gesagt ist mal eine gegen erwähnung weil du immer nur mich betohnst und immer mit freundlichkeit von meiner seite ankomms und zudem mit anderen foren beiträgen die hier nicht zu tuhn haben.
da brauchst du mich auch nicht beschuldigen wenn du immer mit solch anderen unfreundlichen und themen fernen sachen ankommst. und ausgelegt wird es dir nicht so aber man kann es sich so hindrehen, sind halt mal gegen hinweise das dir auch schon geholfen wurde und auch interesse von mehreren ist bzgl. hilfe der entwicklung. gegenseitiges geben und nehmen. wozu ich immer bereit war wenn ich gefragt wurde (4mal als normaler user "nicht software entwickler") dieses betoihnen und drum herum usw... ist für mich nicht freundlich sondern schon eine richtung provokant.
mir ist der adapter wichtig und finde es gut das einer den geschrieben hat und wenn ein peoblem auftritt versuche ich es mit zu lösen was in diesem zusammenhang steht. sollte es nicht die ursache sein müste schon eine richtung gesagt werden wohin und was das man überhaupt weiterkommt.
interesse war ja immer da sonst währ ja nicht gefragt worden aber man sollte auch auf antwort warten oder auch das getestet wurde mit klaren ergebnissen.

>> habe ich dich in irgeneiner form schriftlich angegriffen? beleidigt oder so?

**Comment by mrbungle64** [comment]
Der Issue wird nun geschlossen.

Für den Fall, dass Du weiterhin mit Deiner Installation Probleme hast und es wirklich an einer der in den letzten Monaten veröffentlichten Version liegen sollte, kannst Du jederzeit auf die älteren Versionen zurückgehen.

Hier findest Du eine Anleitung dazu (Abschnitt "Downgrade eines Adapters"):
https://www.iobroker.net/#de/documentation/tutorial/adapter.md

Ich gehe allerdings weiterhin davon aus, dass es sich um einen Einzelfall bzw. ein Problem mit der Installation gehandelt hat, da mir weiterhin keine Codeänderung bewusst ist, die zu diesem Problem geführt haben sollte und mir auch kein weiterer Fall gemeldet wurde.
