### ISSUE TITLE
Use with local bumper server - unable to verify the first certificate

### ISSUE THREAD

**Issue by slev1n** [mrbungle64/ioBroker.ecovacs-deebot#126]
**Describe the bug**
To use the local bumper server a certificate is needed, so the following error appers:

ecovacs-deebot.0 | 2021-03-07 13:56:26.754 | error | (17905) unable to verify the first certificate
-- | -- | -- | --
ecovacs-deebot.0 | 2021-03-07 13:56:26.716 | info | (17905) Reconnecting (4) ...
ecovacs-deebot.0 | 2021-03-07 13:56:20.712 | error | (17905) unable to verify the first certificate
ecovacs-deebot.0 | 2021-03-07 13:56:20.669 | info | (17905) Reconnecting (3) ...
ecovacs-deebot.0 | 2021-03-07 13:56:14.657 | error | (17905) unable to verify the first certificate
ecovacs-deebot.0 | 2021-03-07 13:56:14.599 | info | (17905) Reconnecting (2) ...
ecovacs-deebot.0 | 2021-03-07 13:56:08.592 | error | (17905) unable to verify the first certificate
ecovacs-deebot.0 | 2021-03-07 13:56:08.555 | info | (17905) Reconnecting (1) ...
ecovacs-deebot.0 | 2021-03-07 13:56:02.548 | error | (17905) unable to verify the first certificate

**Additional context**
What i tried:
* add bumpers bumper.crt and ca.crt to iobroker-> settings -> certificates
* convert to ,pem and add bumpers bumper.pem and ca.pem to iobroker-> settings -> certificates

Pls help to add the certificate or add an option for verify_ssl=false from the sucks documentation.
Greets 
Matthias

**Comment by mrbungle64** [comment]
@slev1n 
This is not a bug. You have created a feature request.
I will think about adding an option for `verify_ssl=false`

**Comment by mrbungle64** [comment]
@slev1n 
One option for now is to replace the `key.pem` file in `/opt/iobroker/node_modules/ecovacs-deebot/` directory (assuming that you have ioBroker installed in this directory). You can try if it works.
But you have to make sure to use the correct owner and permissions so that the next update can complete correctly.

**Comment by mrbungle64** [comment]
@slev1n 

> add an option for verify_ssl=false from the sucks documentation

Please post the link to this documentation?
Btw.: I'm not using the sucks library.

**Comment by slev1n** [comment]
@mrbungle64 Thx for your quick reply. 
Unfortunately replace the key.pem in /opt/iobroker/node_modules/ecovacs-deebot with same owner and permission dont work. 
Hmm i thought i read something from using sucks under the hood. Here is the documentation https://bumper.readthedocs.io/en/latest/Use_With_Sucks/

**Comment by mrbungle64** [comment]
@slev1n 
Some additional information:
I never added support for bumper server so I don't think it's worth investing time in trying to make it work...
The deebot-ecovacs.js library was originally a fork of the sucks.js library (js port of the sucks library), but the library has developed significantly since then and is no longer a fork.
With version 0.6.0-alpha.3 parts of the login process also changed.
This version is used by the ioBroker adapter since version 1.1.1.

What version are you using?

**Comment by mrbungle64** [comment]
@slev1n 
What version of the adapter are you using?

**Comment by slev1n** [comment]
@mrbungle64 version 1.1.1

**Comment by mrbungle64** [comment]
> @mrbungle64 version 1.1.1

ok, you can try if it works with 1.1.0 because the login process changed with version 1.1.1

**Comment by mrbungle64** [comment]
@slev1n 
Have you already tried if it works with version 1.1.0?
Btw.: What model do you own?

**Comment by slev1n** [comment]
I try 1.1.0 and also 1.1.2, but both give me the same error.

**Comment by slev1n** [comment]
So i fixed the problem. Iobroker did not use system variables if it is used as a service.
The solution is to override the service enviroment:
` sudo systemctl edit iobroker` 
with 
`[Service]
Environment="NODE_EXTRA_CA_CERTS=/path/to/cert/mycert.crt"`

**Comment by mrbungle64** [comment]
@slev1n 
I'm glad to hear that I was wrong 😉 

What model are you using? Can you please post about whether it works properly?

**Comment by slev1n** [comment]
Im using the Deebot 901 and everything (state, history, actions) seems to work.

**Comment by mrbungle64** [comment]
> Im using the Deebot 901 and everything (state, history, actions) seems to work.

ok, thanks for the info 👍🏻 
I'll add this to the FAQ.

**Comment by slev1n** [comment]
@mrbungle64 No Problem
May i have a problem with the topic transfer to node red. I only see the info node with some attributes:
![image](https://user-images.githubusercontent.com/8486977/110845664-2f543b80-82ab-11eb-87e6-d9aad7e8bb65.png)

**Comment by mrbungle64** [comment]
@slev1n 
> I only see the info node with some attributes

There's maybe a filter active. In my installation this works without any problems.

**Comment by slev1n** [comment]
@mrbungle64 My fault, had to restart node red. Now everything works like a charme.

**Comment by guillaume042** [comment]
> So i fixed the problem. Iobroker did not use system variables if it is used as a service. The solution is to override the service enviroment: ` sudo systemctl edit iobroker` with `[Service] Environment="NODE_EXTRA_CA_CERTS=/path/to/cert/mycert.crt"`

Hello,
2 years after trying to do the same thing but with io broker in docker :)
