### ISSUE TITLE
Deebot 710/711 mit Version 0.3.10

### ISSUE THREAD

**Issue by capitaenz** [mrbungle64/ioBroker.ecovacs-deebot#13]
@mrbungle64 
Der Adapter läuft, hier der Status:
**control**
- charge = OK
- clean = OK
- edge = OK
- pause = keine Funktion!
- play Sound = Start Ton, jedoch nicht "Roboter ist hier". Also fehlerhaft
- spot = OK
- stop = OK

**info**
- battery = wird angezeigt und aktualisiert
- charge status = OK
- cleanstatus = OK
- connection = OK
- deviceStatus = OK

**consumable**
- filter = wird nicht angezeigt
- main_brusch = wird nicht angezeigt
- side_brush = wird nicht angezeigt

**Comment by mrbungle64** [comment]
@capitaenz 

Vielen Dank für die detaillierte Rückmeldung :+1: 

> ...
> * play Sound = Start Ton, jedoch nicht "Roboter ist hier". Also fehlerhaft
> ...

das ist das was "playSound" tun sollte - einen Ton bzw. Sound abspielen ;)
Wie man die Sprachausgabe explizit ansteuert, habe ich bisher noch nicht herausgefunden.

**Comment by mrbungle64** [comment]
@capitaenz 

Die aktuelle Version auf GitHub sollte nun auch die Verbrauchmaterialwerte anzeigen :)

> play Sound = Start Ton, jedoch nicht "Roboter ist hier". Also fehlerhaft

Btw: @boriswerner hat inzwischen herausgefunden, wie man die verschiedenen Sounds und Sprachausgaben direkt ansteuern kann. Das ist aber im Adapter noch nicht implementiert.

**Comment by capitaenz** [comment]
Danke @mrbungle64 und @boriswerner für die super Arbeit! Ich test morgen und werde berichten.

**Comment by boriswerner** [comment]
@capitaenz hehe, zum Glück nicht :-D

**Comment by mrbungle64** [comment]
> Danke @mrbungle64 und @boriswerner für die super Arbeit! Ich teste morgen und werde berichten.
> Nur so am Rande... Wenn der Adapter hier fertig ist: Ihr habt nicht zufällig einen Tesvor X500 Saugroboter und wollt dann mit dem Adapter weitermachen? * hust * =)

@capitaenz 
nee nur einen Xiaomi Mi Robot 1st Gen. ;)

**Comment by mrbungle64** [comment]
Wird in einem [neuen Issue](https://github.com/mrbungle64/ioBroker.ecovacs-deebot/issues/18) fortgeführt

**Comment by mrbungle64** [comment]
Wird in einem [neuen Issue](https://github.com/mrbungle64/ioBroker.ecovacs-deebot/issues/18) fortgeführt
