### ISSUE TITLE
Datenpunkt aus ecovacs-deebot.0.cleaninglog.last20Logs

### ISSUE THREAD

**Issue by chris76e** [mrbungle64/ioBroker.ecovacs-deebot#130]
Hi, 
ist es möglich das folgende Datenpunkte erstellt werden mit dem inhalt der letzten Reinigung? Die Daten sind ja in last20Logs vorhanden.

- timestamp
- date
- totalTimeString
- squareMeters

Model name: ["Deebot 901"]

**Comment by mrbungle64** [comment]
@chris76e 

Ja, das könnte man mal machen.

Für den timestamp gibt es aber schon einen Datenpunkt: "cleaninglog.lastCleaningTimestamp" 😉

**Comment by chris76e** [comment]
stimmt, der ist ja schon vorhanden. 

Vielen Dank für den tollen Adapter

**Comment by chris76e** [comment]
hey, das ging ja super schnell. Vielen Dank für die schnelle umsetzung

**Comment by mrbungle64** [comment]
> hey, das ging ja super schnell. Vielen Dank für die schnelle umsetzung

Hehe, ja wollte dir gerade schreiben 😉

**Comment by mrbungle64** [comment]
@chris76e 

Hast du die entsprechende Version (aktuell 1.1.2-alpha.9) eigentlich schon bei dir im Einsatz?

**Comment by chris76e** [comment]
habe ich gestern direkt installiert und funktioniert auch

**Comment by mrbungle64** [comment]
@chris76e 

> habe ich gestern direkt installiert und funktioniert auch

Gut 👍🏻  dann schließe ich mal den Issue
