### ISSUE TITLE
Frage zum cleaninglog

### ISSUE THREAD

**Issue by chris76e** [mrbungle64/ioBroker.ecovacs-deebot#131]
Hi,

mir ist aufgefallen das in last20Logs die neue Daten als letztes eingefügt werden. Nach einem neustart vom Adapter sind die dann in der richtigen reihenfolge. Kann man das ändern?
Und es wäre toll wenn du noch im cleaninglog die letzte gereinigte SpotArea einfügen könntest.

Danke

![Ashampoo_Snap_Mittwoch, 31  März 2021_06h43m21s_001_](https://user-images.githubusercontent.com/81479633/113576409-d06eb180-961f-11eb-8931-8f25e2fadbb1.png)

![Ashampoo_Snap_Mittwoch, 31  März 2021_06h44m58s_002_](https://user-images.githubusercontent.com/81479633/113576428-d5cbfc00-961f-11eb-8a6e-24cd8c7b4ed6.png)

**Comment by mrbungle64** [comment]
> Hi,
> 
> mir ist aufgefallen das in last20Logs die neue Daten als letztes eingefügt werden. Nach einem neustart vom Adapter sind die dann in der richtigen reihenfolge. Kann man das ändern?

Hi @chris76e 

das war mir noch gar nicht bewusst, dass sich das bei manchen Modellen so verhält.
Ich habe den Fehler aber direkt gefunden - der steckt in der Library.
Werde das in der Library noch rechtzeitig bis zur Fertigstellung der Version 1.12 vom Adapter beheben können, denke ich 😉 

> Und es wäre toll wenn du noch im cleaninglog die letzte gereinigte SpotArea einfügen könntest.

Da bin ich bis jetzt noch nicht so begeistert von. Ich möchte da jetzt nicht für sämtliche Informationen die auch schon in `last20Logs` stecken noch extra Datenpunkte anlegen.
Du kannst aber gerne noch einen Feature Request [erstellen](https://github.com/mrbungle64/ioBroker.ecovacs-deebot/issues/new?assignees=&labels=Enhancement%2C+Verification&template=feature_request.md) und dort den Use Case dafür beschreiben und welche Werte Du da genau benötigst. Vielleicht sehe ich dann ja auch einen angemessenen Mehrwert darin 😉

**Comment by chris76e** [comment]
hmm, bei mir steht in den last20logs keine SpotAreaID bzw. Name

{"id":"xxxx","timestamp":1617629073,"date":"2021-04-05T13:24:33.000Z","lastTime":475,"totalTimeString":"0h 07m 55s","squareMeters":8,"imageUrl":"https://portal-eu.ecouser.netxxxx,"type":"SpotArea"}]

**Comment by mrbungle64** [comment]
> hmm, bei mir steht in den last20logs keine SpotAreaID bzw. Name
> 
> {"id":"xxxx","timestamp":1617629073,"date":"2021-04-05T13:24:33.000Z","lastTime":475,"totalTimeString":"0h 07m 55s","squareMeters":8,"imageUrl":"[https://portal-eu.ecouser.netxxxx,"type":"SpotArea"}]](https://portal-eu.ecouser.netxxxx,%22type%22:%22SpotArea%22%7D%5D)

Ach so, Du meinst die SpotAreaID und den Namen ...
Im Datenpunkt `last20logs` sind allerdings nur Daten die von der Ecovacs API geliefert werden - und das ist da leider nicht enthalten.

Du kannst aber trotzdem einen Feature Request dafür erstellen, dass die zuletzt vom Adapter registierte SpotArea in einem Datenpunkt festgehalten wird. Wüsste da trotzdem noch gerne den Use Case für 😉

**Comment by mrbungle64** [comment]
@chris76e 
Der Fehler sollte ab der 1.1.2-alpha.16 behoben sein.
Du kannst ja noch mal Rückmeldung geben - dann könnten wir den Issue auch direkt schon schließen 😉

**Comment by chris76e** [comment]
Funktioniert. Vielen Dank
