### ISSUE TITLE
Reinigungskarte Automode Deebot 950

### ISSUE THREAD

**Issue by andre-bu** [mrbungle64/ioBroker.ecovacs-deebot#133]
Hallo,
seit einiger Zeit wird unter dem Datenpunkt:

> ecovacs-deebot.0.cleaninglog.lastCleaningMapImageURL

nur noch die Karte der letzen Bereichsreinigung angezeigt.
Wenn die letzte Reingung im Automode erfolgte bleibt dort der Link von der letzten Bereichsreinigung stehen.
Die Karte von der letzten Reinigung im Automode finde ich leider nicht.

Das gleiche ist beim Datenpunkt 

> ecovacs-deebot.0.cleaninglog.lastCleaningTimestamp

Auch hier wird nur der State der letzten Bereichsreinigung angezeigt.

Liegt das an den Updates von Ecovacs oder nutze ich die falschen Datenpunkte?

Großes Danke an die Entwickler für den Adapter. 

Deebot 950
Adapter Version 1.1.1
Node js. v12.20.2

**Comment by mrbungle64** [comment]
Hallo @andre-bu 

hast Du "Alternativen API Befehl für lastCleaningMapImageURL und lastCleaningTimestamp nutzen (OZMO 920/950/T8 Serie)" aktiviert?

**Comment by andre-bu** [comment]
Hallo,
nein ist nicht aktiviert. Habe auch alle anderen Einstellungen auf "Vorauswahl verwenden" gelassen.

**Comment by mrbungle64** [comment]
Benutzt Du den "Stable" oder "Beta (Latest)" als Repository in ioBroker?

**Comment by mrbungle64** [comment]
@andre-bu 

Ich habe auf meinem Testsystem noch mal die 1.1.1 installiert und alle Datenpunkte gelöscht - dort habe ich dann die gleichen Werte wie auch mit der aktuellen 1.1.2-alpha. Meine letzte Reinung war ein Autoclean und die wird bei den beiden Datenpunkten auch ausgegeben.

**Comment by andre-bu** [comment]
@mrbungle64 

nutze "Stable"
Ich habe jetzt den Adapter mal neu gestartet. Jetzt hat sich der Link und die Uhrzeit geändert. Es wird jetzt die Karte und die Uhrzeit der gestrigen Automode Reinigung angezeigt.

**Comment by andre-bu** [comment]
Update Intervall steht auf "60"

**Comment by mrbungle64** [comment]
> Update Intervall steht auf "60"

Das Intervall bezieht sich nicht auf alle Zustände. Es macht ja z.B. wenig Sinn das Reinigungsprotokoll alle 60 Sekunden abzufragen, während der Saugroboter in der Ladestation steht.

Das Reinigungsprotokoll wird abgefragt, wenn
- der Adapter gestartet wird
- eine Reinigung gestartet wird ("device.status" wechselt auf `cleaning`)
- ein Ladevorgang gestartet wird ("device.status" wechselt auf `charging`)

Dabei wird über das Intervall jeweils so lange angefordert, bis der Reinigunsprotokoll von der Ecovacs API rein kommt.

> seit einiger Zeit wird unter dem Datenpunkt:
> ecovacs-deebot.0.cleaninglog.lastCleaningMapImageURL
> nur noch die Karte der letzen Bereichsreinigung angezeigt.

Was verstehst Du unter "seit einiger Zeit"?

**Comment by andre-bu** [comment]
Kann ich leider so genau nicht sagen. Nutze den Automode recht sellten. Aufgefallen ist es mir das erste mal vor ca. 4 Wochen.

> Das Reinigungsprotokoll wird abgefragt, wenn
>
> der Adapter gestartet wird
> eine Reinigung gestartet wird ("status.device" wechselt auf cleaning)
> ein Ladevorgang gestartet wird ("status.device" wechselt auf charging)
> Dabei wird über das Intervall jeweils so lange angefordert, bis der Reinigunsprotokoll von der Ecovacs API rein kommt.

Kann es evtl sein das es zu lange dauert bist die Karte/der Link auf dem Server verfügbar ist. Es dauert nämlich beim Automode auch relativ lange bis die Karte in der App zu sehen ist.

**Comment by mrbungle64** [comment]
@andre-bu 

> Kann es evtl sein das es zu lange dauert bist die Karte/der Link auf dem Server verfügbar ist. Es dauert nämlich beim Automode auch relativ lange bis die Karte in der App zu sehen ist.

Ja das ist ein guter Hinweis. Ecovacs und die Reinigungsprotokolle sind so eine Sache 😉 
Ich mache mir mal Gedanken, wie man das noch optimieren kann.

**Comment by andre-bu** [comment]
@mrbungle64
Ich werde das mal weiter beobachten und öfter mal im Automode reinigen.

**Comment by andre-bu** [comment]
@mrbungle64 das Problem tritt auch nach der Bereichsreinigung auf. Zwar nicht ganz so häufig aber auch immer wieder mal. Aufgefallen ist mir aber noch was.  Wenn die Karte mal wieder nicht aktualisiert wurde und ich ihn dann starte, aktualisiert er die Karte und zeigt mir dann die Karte der letzten Reinigung an.

**Comment by mrbungle64** [comment]
@andre-bu 

Danke für die Info 👍🏻 

Ich hatte vor ein paar Tagen schon eine Optimierung eingebaut - das wird allerdings noch einen Augenblick dauern, bis das in Stable landet.
Du kannst natürlich auch mal die aktuelle Version hier von GitHub probieren - bei mir läuft die eigentlich stabil.
Will dich jetzt aber nicht dazu überreden, da es trotzdem noch eine Alpha-Version ist.

**Comment by andre-bu** [comment]
@mrbungle64 oh super.
Ich würde aufs Stable warten. Hab aktuell keine Testumgebung am laufen.

**Comment by andre-bu** [comment]
@mrbungle64 Hallo, nachdem die Karte in letzter Zeit Problemlos angezeigt wurde ist es seit gestern so das die Karte nur noch als Fragment angezeigt wird.  In der App wird die Karte korrekt angezeigt.
![30e113b3-6737-4007-a5ea-2efb50e51823@221168637@Ja3s](https://user-images.githubusercontent.com/83392498/124507506-2fce9000-ddce-11eb-9817-45560871a230.jpg)

**Comment by andre-bu** [comment]
@mrbungle64 super, genau in dem Moment wo ich den Post abschicke funktioniert die Karte wieder.

**Comment by mrbungle64** [comment]
> @mrbungle64 oh super.
> Ich würde aufs Stable warten. Hab aktuell keine Testumgebung am laufen.

@andre-bu 
Ab heute ist die Stable verfügbar. Würde mich über Feedback freuen, ob das Problem nun behoben ist.

**Comment by andre-bu** [comment]
Super, vielen Dank. Ich werd auf jeden Fall berichten ob es nun läuft.

Grüße

Sascha ***@***.***> schrieb am Sa., 7. Aug. 2021, 10:24:

**Comment by andre-bu** [comment]
@mrbungle64 so wie es aussieht scheint das Problem mit der Karte jetzt behoben zu sein. Nach jeder Reinigung war sie jetzt zu sehen.
Vielen Dank für deine Mühe.

**Comment by mrbungle64** [comment]
> @mrbungle64 so wie es aussieht scheint das Problem mit der Karte jetzt behoben zu sein. Nach jeder Reinigung war sie jetzt zu sehen.
> Vielen Dank für deine Mühe.

Das freut mich 👍🏻
