### ISSUE TITLE
js-controller 3.3.x

### ISSUE THREAD

**Issue by arteck** [mrbungle64/ioBroker.ecovacs-deebot#134]
![grafik](https://user-images.githubusercontent.com/6681528/116655771-eb68e300-a98b-11eb-8903-a6459181e04e.png)

**Comment by mrbungle64** [comment]
@arteck 

Bitte die 4 aufgeführten Datenpunkte mal löschen und den Adapter neu starten.
Mich wundert das stark, dass die bei Dir den type "string" haben ...
"map.deebotDistanceToChargePosition" hatte von Anfang an den type "number" und die anderen 3 haben diesen seit dem 1.5.2020 (war vorher "integer").

**Comment by mrbungle64** [comment]
@arteck 
 
> Du könnest vor dem Löschen auch mal schauen, ob die bei Dir wirklich den type "string" haben. Kann ja auch sein, dass die Warnungen noch ein Fehler im js-controller 3.3.x sind.

Das scheint auch genau in diese Richtung zu gehen:
https://forum.iobroker.net/post/622273

**Comment by mrbungle64** [comment]
@arteck 

Ich muss mich korrigieren - habe den die Meldungen im Screenshot falsch gelesen.
Werde mir das entsprechend anschauen und fixen.

Bitte das nächste mal nicht (ausschließlich) als Screenshot bzw. mal mit ein bisschen Kontext.

**Comment by arteck** [comment]
ich hab gerade 10 issues in die richtung angelegt.. wenn ich noch kontex schreiben sollte.. sry...
aber ich spiele den Ball zurück.. typisiere ordentlich von anfang an..

**Comment by mrbungle64** [comment]
> ich hab gerade 10 issues in die richtung angelegt.. wenn ich noch kontex schreiben sollte.. sry...
> aber ich spiele den Ball zurück.. typisiere ordentlich von anfang an..

Was soll das mit dem Ball und dem erhobenen Zeigefinger? Als ob ich total unfähig wäre ...
Ich habe Dich nur um etwas gebeten. Das darf ich doch, oder?

**Comment by arteck** [comment]
sry hast mich auf falschen Fuss erwischt.. mit den ersten 3 Postings

**Comment by mrbungle64** [comment]
Die oben aufgeführten Warnings sollten bereits mit dem Commit vom 30. April gefixt sein.
Diese und weitere Änderungen bzgl. js-controller 3.3.x sind mit der Version 1.2.0 seit heute auch in Beta/Latest verfügbar.
