### ISSUE TITLE
DEEBOT OZMO 900 funktioniert nicht richtig

### ISSUE THREAD

**Issue by Bandit2001** [mrbungle64/ioBroker.ecovacs-deebot#14]
Der DEEBOT OZMO 900 funktioniert mit dem Adapter nicht richtig.
Vor allem die Verbrauchswerte werden nicht angezeigt:
![grafik](https://user-images.githubusercontent.com/20992568/74869282-f5d72800-5357-11ea-810a-fcefb3a67ac9.png)

Buttons wie Reinigen, Pause, Bereich etc. funktionieren aktuell mit der Version 0.3.10.

Falls ich bei der Lösung behilflich sein kann bitte melden.

**Comment by mrbungle64** [comment]
Hi @Bandit2001

> Der DEEBOT OZMO 900 funktioniert mit dem Adapter nicht richtig.
> Vor allem die Verbrauchswerte werden nicht angezeigt:
> ![grafik](https://user-images.githubusercontent.com/20992568/74869282-f5d72800-5357-11ea-810a-fcefb3a67ac9.png)
> 
> Buttons wie Reinigen, Pause, Bereich etc. funktionieren aktuell mit der Version 0.3.10.

Danke für die Infos!

> Falls ich bei der Lösung behilflich sein kann bitte melden.

Ja sehr gerne :+1:

Hast Du die Möglichkeit die Library mal auf der Konsole auszuführen (z.B. auf einem Linux System)?

Ansonsten hätte ich noch ein paar Fragen:
- Funktioniert die "waterLevel" Einstellung?
- Bekommst Du unter "waterbox" angezeigt, ob der Wasserbehälter eingesetzt ist?
- Funktioniert "playSound"?

**Comment by Bandit2001** [comment]
Hi,
mal kurz die ersten Antworten auf die schnelle:


> Hast Du die Möglichkeit die Library mal auf der Konsole auszuführen (z.B. auf einem Linux System)?

Ja, sollte gehen, ich habe noch ein paar RasPi hier liegen

> Ansonsten hätte ich noch ein paar Fragen:
>     * Funktioniert die "waterLevel" Einstellung?
>     * Bekommst Du unter "waterbox" angezeigt, ob der Wasserbehälter eingesetzt ist?

Muss ich beides erst noch testen


>     * Funktioniert "playSound"?

Ja, Sound geht

**Comment by mrbungle64** [comment]
> 
> > Hast Du die Möglichkeit die Library mal auf der Konsole auszuführen (z.B. auf einem Linux System)?
> 
> Ja, sollte gehen, ich habe noch ein paar RasPi hier liegen
> 

ok, dann wäre es gut, wenn Du folgendes durchführen könntest:

```bash
git clone https://github.com/mrbungle64/ecovacs-deebot.js.git
cd ecovacs-deebot.js
npm install
cd example
```

in der Datei `app2.js` Email und Passwort anpassen und die Datei dann ausführen

```bash
NODE_ENV=dev node app2.js | grep -E 'Battery|LifeSpan'
```

Dann möglichst eine Reinigung starten (per Mobile App oder ioBroker) und mir die Ausgabe schicken, wenn da was mit "Battery" und/oder "LifeSpan" kommt.

Falls der Fehler 'Failure code 0002' kommt bitte "einfach" so lange die `app2.js` neu ausführen, bis der Fehler nicht mehr kommt. Das ist irgendwie eine Eigenart der Ecovacs Server.

**Comment by Bandit2001** [comment]
Hi,
ich habe das vorhin mal laufen lassen, hier das Ergebnis:
[DeebotOzmo_900.txt](https://github.com/mrbungle64/ioBroker.ecovacs-deebot/files/4231973/DeebotOzmo_900.txt)

Falls noch etwas fehlt einfach melden, dann mache ich noch einen Durchgang.

**Comment by mrbungle64** [comment]
Hallo @Bandit2001

Vielen Dank. Also eigentlich müsste der Adapter zumindest den Wert unter "battery" anzeigen.

Ist das in der aktuellen Version 0.4.0 immer noch leer im Adapter?

**Comment by Bandit2001** [comment]
Ups, 0.4.0, seit wann gibt es die denn schon?

Ok, Battery bekomme ich jetzt damit angezeigt, einzig die "Zubehörnutzung" fehlt noch.

**Comment by mrbungle64** [comment]
Seit gestern :)

Die Verbrauchmaterialwerte sind generell noch etwas schwierig - aber darum kümmere ich mich die nächsten Tage mal.

**Comment by mrbungle64** [comment]
@Bandit2001 

Die aktuelle Version auf GitHub sollte nun auch die Verbrauchmaterialwerte anzeigen :)

**Comment by Bandit2001** [comment]
Ich habe es ausprobiert, leider keine Veränderung, d.h. ich sehe immer noch keine Verbrauchmaterialwerte. Ist jetzt für mich aber auch nicht so schlimm.

**Comment by AudidriverA4** [comment]
Hab auch gerade mal kurz aktualisiert und bei mir wird auch noch kein Verbrauchsmaterial angezeigt beim Deebot 900.
<img width="1157" alt="Screenshot 2020-02-23 19 32 12" src="https://user-images.githubusercontent.com/46032677/75117605-4067e580-5673-11ea-90ca-bef6675390b2.png">
und irgendwie Zeigt bei mir der Akkustand nie 100% an heute stand er in ganzen Tag auf der Ladestation und Auch steht nur bei 45% ???
<img width="1153" alt="Screenshot 2020-02-23 19 32 24" src="https://user-images.githubusercontent.com/46032677/75117649-a5bbd680-5673-11ea-9cda-dcdb8be8f120.png">
Letzte Woche mal stand da 34% da hat er aber auch geladen, muss ich mal in nächster Zeit beobachten.
<img width="1246" alt="Screenshot 2020-02-19 17 24 15" src="https://user-images.githubusercontent.com/46032677/75117662-c71cc280-5673-11ea-9461-2c7755b7b060.png">

**Comment by AudidriverA4** [comment]
Hab mal schnell gestartet und dann springt der Akku auf 99% im Broker.

<img width="1159" alt="Screenshot 2020-02-23 19 40 41" src="https://user-images.githubusercontent.com/46032677/75117777-ca647e00-5674-11ea-92ae-20286048c77c.png">

**Comment by mrbungle64** [comment]
> Hab mal schnell gestartet und dann springt der Akku auf 99% im Broker.
> 
> <img alt="Screenshot 2020-02-23 19 40 41" width="1159" src="https://user-images.githubusercontent.com/46032677/75117777-ca647e00-5674-11ea-92ae-20286048c77c.png">

Hallo @AudidriverA4 

danke für die Infos? Hat es dann nun soweit funktioniert?

Btw.: Der Deebot 900 ist leider nicht das gleiche Modell wie der Deebot OZMO 900 (um den es in diesem Issue geht)

**Comment by mrbungle64** [comment]
> Ich habe es ausprobiert, leider keine Veränderung, d.h. ich sehe immer noch keine Verbrauchmaterialwerte. Ist jetzt für mich aber auch nicht so schlimm.

Hallo @Bandit2001 

ich habe gerade gesehen, dass in der hier verwendeten Version der Library noch ein weiterer Fehler war ...
Der ist in der neusten Version behoben - allerdings ist die noch nicht in der aktuellen ioBroker Adapter Version eingebunden.

Ein bisschen dauert es also leider noch - aber dann sollte es endlich soweit sein :)

**Comment by AudidriverA4** [comment]
@mrbungle64 

Wie oben beschrieben ist DEEBOT auf ladeschale gefahren hat geladen dann ist der Akku stand im Broker von 98% auf 90% gesunken nach kurzer Zeit.
Hab leider vergessen am Morgen nochmal zu kucken was dann im Broker stand. 
Jetzt Aktuell steht Akku auf 34% im Broker obwohl er seit gestern Mittag auf der Station steht.
In der App sieht Akku aber voll aus.

**Comment by mrbungle64** [comment]
> @mrbungle64
> 
> Wie oben beschrieben ist DEEBOT auf ladeschale gefahren hat geladen dann ist der Akku stand im Broker von 98% auf 90% gesunken nach kurzer Zeit.
> Hab leider vergessen am Morgen nochmal zu kucken was dann im Broker stand.
> Jetzt Aktuell steht Akku auf 34% im Broker obwohl er seit gestern Mittag auf der Station steht.
> In der App sieht Akku aber voll aus.

Hmm, das klingt sehr komisch für mich, da der Adapter nicht selbständig den Wert von "battery" verringert. Das bedeutet für mich, dass der Ecovacs Server zwischendurch mal 34% gemeldet haben müsste - auch wenn das inzwischen wieder bei quasi 100% angelagt ist.

Meine Vermutung ist im Moment, dass der Adapter immer mal wieder stoppt bzw. die Verbindung verliert. Woher das kommt kann ich leider nicht sagen.

Hast du die Möglichkeit den Verlauf von "battery" über den History Adapter (o.ä.) zu speichern - damit man mal die Sprünge im Verlauf genauer betrachten könnte?

**Comment by AudidriverA4** [comment]
> > @mrbungle64
> > Wie oben beschrieben ist DEEBOT auf ladeschale gefahren hat geladen dann ist der Akku stand im Broker von 98% auf 90% gesunken nach kurzer Zeit.
> > Hab leider vergessen am Morgen nochmal zu kucken was dann im Broker stand.
> > Jetzt Aktuell steht Akku auf 34% im Broker obwohl er seit gestern Mittag auf der Station steht.
> > In der App sieht Akku aber voll aus.
> 
> @AudidriverA4
> 
> Hmm, das klingt sehr komisch für mich, da der Adapter nicht selbständig den Wert von "battery" verringert. Das bedeutet für mich, dass der Ecovacs Server zwischendurch mal 34% gemeldet haben müsste - auch wenn das inzwischen wieder bei quasi 100% angelagt ist.
> 
> Meine Vermutung ist im Moment, dass der Adapter immer mal wieder stoppt bzw. die Verbindung verliert. Woher das kommt kann ich leider nicht sagen.
> 
> Hast du die Möglichkeit den Verlauf von "battery" über den History Adapter (o.ä.) zu speichern - damit man mal die Sprünge im Verlauf genauer betrachten könnte?
> 
> Btw.: Es wäre gut, wenn Du einen neuen Issue dafür erstellten könntest, da es hier ja eigenlich um den OZMO 900 geht ... Danke :)

Hab mal History gestartet muss ich da was einstellen ausser aktivieren und muss mal kucken wo ich Daten Auslesen kann.

Heute hat der Deebot mal seine Ladeschale verschoben und konnte nicht Laden er war ziemlich leer.  Hab alles wieder richtig aufgestellt und Deebot auf Ladeschale das war so ca 15.30 Uhr.
Eben gerade hab ich mal im Broker gekuckt das steht 4% laut App Akku voll.
Kann es sein das er irgendwie in letzten stand vorm Laden im Broker schreibt ?
Jetzt hab ich mal Deebot gestartet und nach ca nach einer Minute im Betrieb stand dann 99% im Broker.
Jetzt ist er wieder auf Ladeschale und zeigt 98% und Aufladen.

**Comment by AudidriverA4** [comment]
> > @mrbungle64
> > Wie oben beschrieben ist DEEBOT auf ladeschale gefahren hat geladen dann ist der Akku stand im Broker von 98% auf 90% gesunken nach kurzer Zeit.
> > Hab leider vergessen am Morgen nochmal zu kucken was dann im Broker stand.
> > Jetzt Aktuell steht Akku auf 34% im Broker obwohl er seit gestern Mittag auf der Station steht.
> > In der App sieht Akku aber voll aus.
> 
> @AudidriverA4
> 
> Hmm, das klingt sehr komisch für mich, da der Adapter nicht selbständig den Wert von "battery" verringert. Das bedeutet für mich, dass der Ecovacs Server zwischendurch mal 34% gemeldet haben müsste - auch wenn das inzwischen wieder bei quasi 100% angelagt ist.
> 
> Meine Vermutung ist im Moment, dass der Adapter immer mal wieder stoppt bzw. die Verbindung verliert. Woher das kommt kann ich leider nicht sagen.
> 
> Hast du die Möglichkeit den Verlauf von "battery" über den History Adapter (o.ä.) zu speichern - damit man mal die Sprünge im Verlauf genauer betrachten könnte?
> 
> Btw.: Es wäre gut, wenn Du einen neuen Issue dafür erstellten könntest, da es hier ja eigenlich um den OZMO 900 geht ... Danke :)

Hab mal neues aufgemacht :-)

**Comment by rebel1985** [comment]
hi, braucht ihr noch meine hilfe beim testen?

**Comment by mrbungle64** [comment]
> hi, braucht ihr noch meine hilfe beim testen?

Hi @rebel1985 

Du kannst natürlich gerne die aktuelle Version vom Adapter auf GitHub (oder der Library - da wurde intern einiges umgebaut) testen.

Die neue Version der Library wollten wir aber die Tage auch in den Adapter integrieren und auch veröffentlichen. Dann macht es aktuell am meisten Sinn, denke ich ...
Wir sagen Dir dann bescheid :)

**Comment by mrbungle64** [comment]
@Bandit2001  @rebel1985 

Version 0.5.0 steht auf GitHub bereit :)

**Comment by Bandit2001** [comment]
@mrbungle64 
Sorry, irgendwas ist da faul.
Mit der Version 0.5.0 / 0.5.1 funktioniert bei mir aktuell kein einziger Tastendruck.
Wie komme ich wieder auf die 0.4.2 zurück? Da hatte alles funktioniert.

**Comment by mrbungle64** [comment]
@Bandit2001

Ist der Adapter auch vollständig connected?

https://www.iobroker.net/docu/index-23.htm?page_id=8511&lang=de#Downgrade_eines_Adapters

**Comment by Bandit2001** [comment]
@mrbungle64 
Ja, war laut Log Connected.
Habe von dem Adapter die Konfiguration gespeichert, gelöscht, neu installiert (0.4.0), Konfiguration geladen und es geht wieder.
Dann noch einmal auf die 0.5.1 aktualisiert, selbes Ergebnis nichts funktioniert mehr. Also wieder zurück zur 0.4.0.
Hier noch die Screeshots der Logs:

![Debot_20200301_01](https://user-images.githubusercontent.com/20992568/75630783-cb099100-5bed-11ea-9722-7f390ea2608b.png)

![Debot_20200301_02](https://user-images.githubusercontent.com/20992568/75630784-d066db80-5bed-11ea-9897-d719f8c31119.png)

**Comment by mrbungle64** [comment]
@Bandit2001 
Danke für die Infos, in den Screenshots sieht aber erst mal alles sauber aus (was aber nicht heißen muss, dass es kein Problem gibt)

Ich habe noch 2 Fragen:
- Hast du noch andere Buttons als "playSound" probiert?
- Wieso bist du zur Version 0.4.0 und nicht zur 0.4.2 zurück? Du sagtest, "Da hatte alles funktioniert"

**Comment by Bandit2001** [comment]
@mrbungle64 

> Hast du noch andere Buttons als "playSound" probiert?

Ja, hatte alle Buttons getestet, wie Clean, SpotArea, Pause etc., der Deebot hatte auf keinen Befehl reagiert.

> Wieso bist du zur Version 0.4.0 und nicht zur 0.4.2 zurück?

Wie gesagt, hatte die Instanz gelöscht und neu installiert, und da bekomme ich nur eine 0.4.0.
![Debot_20200301_03](https://user-images.githubusercontent.com/20992568/75632503-efb93500-5bfc-11ea-964e-ce3e9b29c45b.png)

**Comment by mrbungle64** [comment]
> @mrbungle64
> 
> > Hast du noch andere Buttons als "playSound" probiert?
> 
> Ja, hatte alle Buttons getestet, wie Clean, SpotArea, Pause etc., der Deebot hatte auf keinen Befehl reagiert.

ok, dann schaue ich mir das nachher oder morgen mal an, was da zwischen der 0.4.2 und der 0.5.0 in Bezug auf den Ozmo 900 passiert ist. 
Wir sind beim Sprung auf die 0.5.0 auf eine stark veränderte Library gewechselt und beide Entwickler haben ja leider keinen Ozmo 900 zum Testen. Sollte aber lösbar sein, das Problem :)

> 
> > Wieso bist du zur Version 0.4.0 und nicht zur 0.4.2 zurück?
> 
> Wie gesagt, hatte die Instanz gelöscht und neu installiert, und da bekomme ich nur eine 0.4.0.
> ![Debot_20200301_03](https://user-images.githubusercontent.com/20992568/75632503-efb93500-5bfc-11ea-964e-ce3e9b29c45b.png)

Ah ok, aber in dem Link den ich Dir gepostet hatte war ja in dem Screencast gezeigt wie Du eine beliebige Version installieren kannst:
https://www.iobroker.net/docu/index-23.htm?page_id=8511&lang=de#Downgrade_eines_Adapters
Darüber kannst du u.a. die 0.4.2 installieren.

**Comment by mrbungle64** [comment]
@Bandit2001 

Ich habe den Fehler gefunden - ich werde heute im Laufe des Tages einen neuen Release zur Verfügung stellen.

**Comment by mrbungle64** [comment]
@Bandit2001 

Version 0.5.2 steht auf GitHhub zur Verfügung :)

**Comment by mrbungle64** [comment]
@Bandit2001 

Hattest Du noch mal die Gelegenheit zu testen? Aktuell ist die Version 0.5.3 auf GitHub.

**Comment by Bandit2001** [comment]
@mrbungle64 
Hi, die 0.5.2 habe ich kurz getestet, da hatte wiede alles funktioniert.
Die 0.5.3 werde ich mir mal am WE anschauen.

Vielen Dank für deine Mühen!

**Comment by mrbungle64** [comment]
@Bandit2001 
Kannst Du das bitte noch mal mit der aktuellen Version (entweder 0.5.5 aus der Latest Repo oder der 0.5.7 von GitHub) testen und Feedback geben?
Wüsste gerne, was beim Ozmo 900 inzwischen funktioniert (und ggf. was noch nicht)

**Comment by rebel1985** [comment]
![Unbenannt](https://user-images.githubusercontent.com/59134497/76700043-9ac4f680-66b3-11ea-8005-bcd3c5d3c054.JPG)

**Comment by mrbungle64** [comment]
> ![Unbenannt](https://user-images.githubusercontent.com/59134497/76700043-9ac4f680-66b3-11ea-8005-bcd3c5d3c054.JPG)
> 
> cool die anzeige für filter usw. geht nun auch klasse, thumbs up

Ja cool :+1: 

Funktioniert der Rest auch soweit nun beim Ozmo 900?

**Comment by rebel1985** [comment]
![Unbenannt](https://user-images.githubusercontent.com/59134497/76702117-84289a80-66c7-11ea-8189-3504e9ac5aa0.JPG)

**Comment by mrbungle64** [comment]
> ![Unbenannt](https://user-images.githubusercontent.com/59134497/76702117-84289a80-66c7-11ea-8189-3504e9ac5aa0.JPG)
> 
> das rot makierte funktioniert beim 900 nicht, restliche tasten schon und was cool ist die direkte spot reinigung.
> 
> was soll das rot makierte bewirken?

Dort musst Du 4 Positionswerte (x1,y1,x2,y2) eintragen: z.B. -3975,2280,-1930,4575.
x1,y1 = Pos. links oben. x2,y2 = Pos. rechts unten
links von der "Mitte" sind es negative Werte.
unterhalb der "Mitte" sind es ebenfalls negative Werte.
Dann kannst Du wie in der App einen benutzerdef. Bereich reinigen lassen.
1000 entspricht ungefähr 1 Meter und das ist relativ zur "Mitte" vom Grundriss (0,0,0,0)
Die Pos. der Ladestation sollte ungefähr die Mitte darstellen - so ist es zumindest bei mir.

"control.waterLevel" scheint ja nicht zu funktionieren, oder?
Wenn Du da etwas auswählst erscheint das als Wassermenge in der App und umgekehrt?
Bis es im Adapter angezeigt wird dauert es ggf. bis zu einer Minute und in der App aktualisert es sich auch nur, wenn man die Ansicht neu aufruft.

Ändert sich "info.waterbox" wenn Du den Wasserbehälter einsetzt bis herausnimmst?

**Comment by Bandit2001** [comment]
@mrbungle64 
Ich komme leider aktuell nicht wirklich zum Testen.
Aber nach dem Update uf die 0.5.7 bekomme ich die Verbrauchswerte (Filter, Bürste, ..) immer noch nicht angezeigt. Oder muss ich noch etwas anderes aktualisieren?

**Comment by mrbungle64** [comment]
Hi  @Bandit2001 
> @mrbungle64
> Ich komme leider aktuell nicht wirklich zum Testen.

kein Problem ;)

> Aber nach dem Update uf die 0.5.7 bekomme ich die Verbrauchswerte (Filter, Bürste, ..) immer noch nicht angezeigt. Oder muss ich noch etwas anderes aktualisieren?

Nein, das sollte "einfach so" funktionieren. Es kann aber sein, dass es eine Weile dauert - ggf. wird das erst erscheinen, wenn sich einer der Verbrauchswerte verändert hat. Evtl. schickt der Roboter bzw. der Ecovacs Server erst dann die Werte...

**Comment by rebel1985** [comment]
> 
> 
> > ![Unbenannt](https://user-images.githubusercontent.com/59134497/76702117-84289a80-66c7-11ea-8189-3504e9ac5aa0.JPG)
> > das rot makierte funktioniert beim 900 nicht, restliche tasten schon und was cool ist die direkte spot reinigung.
> > was soll das rot makierte bewirken?
> 
> @rebel1985
> Dort musst Du 4 Positionswerte (x1,y1,x2,y2) eintragen: z.B. -3975,2280,-1930,4575.
> x1,y1 = Pos. links oben. x2,y2 = Pos. rechts unten
> links von der "Mitte" sind es negative Werte.
> unterhalb der "Mitte" sind es ebenfalls negative Werte.
> Dann kannst Du wie in der App einen benutzerdef. Bereich reinigen lassen.
> 1000 entspricht ungefähr 1 Meter und das ist relativ zur "Mitte" vom Grundriss (0,0,0,0)
> Die Pos. der Ladestation sollte ungefähr die Mitte darstellen - so ist es zumindest bei mir.

**okay, boar einerseitz umständlich, da muss man ja alle eckwerte wissen usw... andersrum eine coole sache das anzeigen zu lassen**

> "control.waterLevel" scheint ja nicht zu funktionieren, oder?
> Wenn Du da etwas auswählst erscheint das als Wassermenge in der App und umgekehrt?
> Bis es im Adapter angezeigt wird dauert es ggf. bis zu einer Minute und in der App aktualisert es sich auch nur, wenn man die Ansicht neu aufruft.

**Waterlevel funtkioniert und geht auch gleich in der app aktuell**


> Ändert sich "info.waterbox" wenn Du den Wasserbehälter einsetzt bis herausnimmst?

nein , wischplatte ist untergesetz und es ändert sich nichts. ggf. ist das ein versteckter wert in der app? denn dort find ich jetzt auch nicht das die wisch platte unter gesetz ist...
außer das in der karten ansicht links oben nun wischen steht über dem status.

**Comment by mrbungle64** [comment]
> > 
> > @rebel1985
> > Dort musst Du 4 Positionswerte (x1,y1,x2,y2) eintragen: z.B. -3975,2280,-1930,4575.
> > x1,y1 = Pos. links oben. x2,y2 = Pos. rechts unten
> > links von der "Mitte" sind es negative Werte.
> > unterhalb der "Mitte" sind es ebenfalls negative Werte.
> > Dann kannst Du wie in der App einen benutzerdef. Bereich reinigen lassen.
> > 1000 entspricht ungefähr 1 Meter und das ist relativ zur "Mitte" vom Grundriss (0,0,0,0)
> > Die Pos. der Ladestation sollte ungefähr die Mitte darstellen - so ist es zumindest bei mir.
> 
> **okay, boar einerseitz umständlich, da muss man ja alle eckwerte wissen usw... andersrum eine coole sache das anzeigen zu lassen**

Ja das ist nicht ganz einfach ;)

> 
> > "control.waterLevel" scheint ja nicht zu funktionieren, oder?
> > Wenn Du da etwas auswählst erscheint das als Wassermenge in der App und umgekehrt?
> > Bis es im Adapter angezeigt wird dauert es ggf. bis zu einer Minute und in der App aktualisert es sich auch nur, wenn man die Ansicht neu aufruft.
> 
> **Waterlevel funtkioniert und geht auch gleich in der app aktuell**

Sehr gut :+1: 

> 
> > Ändert sich "info.waterbox" wenn Du den Wasserbehälter einsetzt bis herausnimmst?
> 
> nein , wischplatte ist untergesetz und es ändert sich nichts. ggf. ist das ein versteckter wert in der app? denn dort find ich jetzt auch nicht das die wisch platte unter gesetz ist...
> außer das in der karten ansicht links oben nun wischen steht über dem status.

Ja wenn links oben die Wassermenge in der App angezeigt wird sollte dann Wert von "info.waterbox" true sein und ansonsten "false".
Aber schade, dann funktioniert das wohl noch nicht so ganz beim Ozmo 900...

**Comment by rebel1985** [comment]
> 
> 
> > > @rebel1985
> > > Dort musst Du 4 Positionswerte (x1,y1,x2,y2) eintragen: z.B. -3975,2280,-1930,4575.
> > > x1,y1 = Pos. links oben. x2,y2 = Pos. rechts unten
> > > links von der "Mitte" sind es negative Werte.
> > > unterhalb der "Mitte" sind es ebenfalls negative Werte.
> > > Dann kannst Du wie in der App einen benutzerdef. Bereich reinigen lassen.
> > > 1000 entspricht ungefähr 1 Meter und das ist relativ zur "Mitte" vom Grundriss (0,0,0,0)
> > > Die Pos. der Ladestation sollte ungefähr die Mitte darstellen - so ist es zumindest bei mir.
> > 
> > 
> > **okay, boar einerseitz umständlich, da muss man ja alle eckwerte wissen usw... andersrum eine coole sache das anzeigen zu lassen**
> 
> Ja das ist nicht ganz einfach ;)
> 
> > > "control.waterLevel" scheint ja nicht zu funktionieren, oder?
> > > Wenn Du da etwas auswählst erscheint das als Wassermenge in der App und umgekehrt?
> > > Bis es im Adapter angezeigt wird dauert es ggf. bis zu einer Minute und in der App aktualisert es sich auch nur, wenn man die Ansicht neu aufruft.
> > 
> > 
> > **Waterlevel funtkioniert und geht auch gleich in der app aktuell**
> 
> Sehr gut 👍
> 
> > > Ändert sich "info.waterbox" wenn Du den Wasserbehälter einsetzt bis herausnimmst?
> > 
> > 
> > nein , wischplatte ist untergesetz und es ändert sich nichts. ggf. ist das ein versteckter wert in der app? denn dort find ich jetzt auch nicht das die wisch platte unter gesetz ist...
> > außer das in der karten ansicht links oben nun wischen steht über dem status.
> 
> Ja wenn links oben die Wassermenge in der App angezeigt wird sollte dann Wert von "info.waterbox" true sein und ansonsten "false".
> Aber schade, dann funktioniert das wohl noch nicht so ganz beim Ozmo 900...

ich mein in der app steht links oben immer der status der aufgabe und dort steht wenn die wischplatte untergbaut ist wischen

![IMG-20191205-WA0000](https://user-images.githubusercontent.com/59134497/76704059-b097e300-66d6-11ea-883f-049997e63aaf.jpg)
![Screenshot_20191206-193729_ECOVACS HOME](https://user-images.githubusercontent.com/59134497/76704060-b1307980-66d6-11ea-8fa8-2caef0112295.jpg)

sonst eben reinigen oder aufladen

**Comment by mrbungle64** [comment]
@rebel1985 

> > > > Ändert sich "info.waterbox" wenn Du den Wasserbehälter einsetzt bis herausnimmst?
> > > 
> > > 
> > > nein , wischplatte ist untergesetz und es ändert sich nichts. ggf. ist das ein versteckter wert in der app? denn dort find ich jetzt auch nicht das die wisch platte unter gesetz ist...
> > > außer das in der karten ansicht links oben nun wischen steht über dem status.
> > 
> > 
> > Ja wenn links oben die Wassermenge in der App angezeigt wird sollte dann Wert von "info.waterbox" true sein und ansonsten "false".
> > Aber schade, dann funktioniert das wohl noch nicht so ganz beim Ozmo 900...
> 
> ich mein in der app steht links oben immer der status der aufgabe und dort steht wenn die wischplatte untergbaut ist wischen
> 
> sonst eben reinigen oder aufladen

Ja daran kann man das ebenfalls sehen ;)

**Comment by mrbungle64** [comment]
DEEBOT OZMO 900 scheint inzwischen grundsätzlich zu funktonieren.
Ich schließe den Issue daher.
