### ISSUE TITLE
Error: The module '/opt/iobroker/node_modules/canvas/build/Release/canvas.node' was compiled against a different Node.js

### ISSUE THREAD

**Issue by Planetus88** [mrbungle64/ioBroker.ecovacs-deebot#141]
Hallo,
kann mir jemand helfen? Ich bekomme diesen Fehler nicht behoben.
Habe es mit:

npm install canvas
npm rebuild canvas --build-from-source
curl -sL https://iobroker.net/fix.sh | bash -

versucht, aber es bringt nichts.

![ecovacs-deebot 0](https://user-images.githubusercontent.com/54700080/118390688-af42ad00-b630-11eb-8e4e-a3705340edc7.jpg)

Bitte HELP :)

Gruß
Tom

**Comment by mrbungle64** [comment]
@Planetus88 

Versuch es bitte mal so:

```bash
cd /opt/iobroker/node_modules
npm rebuild canvas
```

**Comment by Planetus88** [comment]
Hi, habs versucht.....hat leider nichts gebracht.
Ich habe zwei Instanzen von dem Ecovacs Adapter auf einem IOBroker am Laufen, die zweite Instanz läuft komischerweise. 

![2021-05-16 12_44_08-mRemoteNG - confCons xml - IOBroker - 0 (ESXi)](https://user-images.githubusercontent.com/54700080/118394423-e91dae80-b644-11eb-854b-2cd77cb38223.jpg)

![2021-05-16 12_45_23-logs - ioBroker](https://user-images.githubusercontent.com/54700080/118394424-ed49cc00-b644-11eb-9205-a6b390c3a3ac.jpg)

![2021-05-16 12_46_13-logs - ioBroker](https://user-images.githubusercontent.com/54700080/118394429-f76bca80-b644-11eb-91b4-58b04a99df72.jpg)

![2021-05-16 12_47_30-instances - ioBroker](https://user-images.githubusercontent.com/54700080/118394432-fa66bb00-b644-11eb-8627-7fa1fd339ec2.jpg)

**Comment by mrbungle64** [comment]
@Planetus88 

Ich nehme mal an, dass du kürzlich ein Update von Node.js gemacht hast, richtig?

Kannst Du bitte das noch nachholen das Formular auszufüllen - dafür habe ich es ja gemacht 😉 
Mir fehlen sämtliche Information zum eingesetzten System.
Und bitte keine Screenshots vom Log oder der Konsoleausgabe.
Dafür gibt es [Code Blocks](https://docs.github.com/en/github/writing-on-github/basic-writing-and-formatting-syntax#quoting-code).

**Comment by Planetus88** [comment]
Jaap, da hast du recht....hab Update von Node.js 10 auf 12 gemacht. Die Adapter liefen zwei Wochen, heute wieder so fehler. 
Die anderen Adapter die Probleme machten konnte ich reparieren, nur der eine funktioniert nicht richtig :(

Sorry, das ist mein erstes Ticket bei github :)
Llibrary kein Plan wo das steht.

**Software version and sources**:
 - Adapter version: "1.1.1"
 - Source/Repo: "ioBroker Stable" 4.2.1
 - Node.js version ioBroker Master: v12.22.1 
 - Node.js version ioBroker 1: v12.22.1
 - Node.js version ioBroker 2: v12.22.1
 - Node.js version ioBroker 3: v14.16.1
 - JS controller version:  3.2.16
 - Operating system: Debian
 - Hardware: VM on ESXi

**Deebot model**
 - Model name: ecovacs-deebot.0 - DEEBOT OZMO/PRO 930 Series -  ioBroker Master
 - Model name: ecovacs-deebot.1 - DEEBOT OZMO 950 Series -  ioBroker Master

**Comment by mrbungle64** [comment]
@Planetus88 

Welche davon ist die betroffene und was bedeutet das eigentlich, dass du 3 Installationen aufführst? 😉 
```
Node.js version ioBroker 1: v12.22.1
Node.js version ioBroker 2: v12.22.1
Node.js version ioBroker 3: v14.16.1
```

**Comment by mrbungle64** [comment]
@Planetus88 

Im Endeffekt bedeutet der Fehler, das das canvas Modul noch mit Node.js 10 kompiliert wurde und der Adapter nun unter Node.js 12 läuft.

Probier bitte noch mal:
```bash
cd /opt/iobroker/node_modules
npm uninstall canvas
npm install canvas
```

**Comment by mrbungle64** [comment]
@Planetus88 

Dieses How-to ist übrigens sehr hilfreich bei einem Update von Node.js:
https://forum.iobroker.net/topic/22867/how-to-node-js-f%C3%BCr-iobroker-richtig-updaten

**Comment by Planetus88** [comment]
@mrbungle64

Hat wohl funktioniert, Adapter sind Grün...keine Fehler im Log :-) 
Danke!!!!! :-)

Ja die Seite kenne ich, hab ich in den Favoriten abgespeichert.....braucht man immer wieder :-)

iobroker rebuild ecovacs-deebot 
und 
iobroker rebuild ecovacs-deebot --install 
brachte nichts, nur die Neuinstallation von canvas ist wohl die Lösung.

Danke dir für den Sonntagssupport :-)

**Comment by mrbungle64** [comment]
@Planetus88 

> Hat wohl funktioniert, Adapter sind Grün...keine Fehler im Log :-)

ok gut, das freut mich 👍🏻 

> iobroker rebuild ecovacs-deebot
> und
> iobroker rebuild ecovacs-deebot --install
> brachte nichts, nur die Neuinstallation von canvas ist wohl die Lösung.

Es gibt leider keine pauschale Lösung für das Problem. Es kommt halt immer auch drauf an, wie canvas installiert wurde.
Ich werde die verschiedenen Lösungswege aber nun mal in die FAQs aufnehmen.

**Comment by Planetus88** [comment]
@mrbungle64

Mich freut es auch, glaub mir :-D

Tue das, ein Version Check Befehl für Canvas wäre gut.....aber finde nichts im Web.
