### ISSUE TITLE
Received disconnect event from library

### ISSUE THREAD

**Issue by fabianbmann** [mrbungle64/ioBroker.ecovacs-deebot#142]
Hallo,

immer wieder trennt sich mein Ozmo T8 und baut keine neue Verbindung auf. Woran könnte das liegen?

Kann leider nicht genau sagen, was der Grund für die regelmäßige Trennung ist.

Adapter Version: `1.2.0`

Fehler im Log: `(8385) Received disconnect event from library`

Wäre cool wenns einen Tipp geben würde (oder eine kurze Anleitung) wie man den Fehler beheben kann.

Lieben Dank! Und gute Arbeit!

**Comment by mrbungle64** [comment]
Hallo  @fabianbmann 

> immer wieder trennt sich mein Ozmo T8 und baut keine neue Verbindung auf.

wie oft kommt das vor?

> Adapter Version: 1.2.0

Meinst du die 1.2.0-alpha.x von GitHub?

**Comment by fabianbmann** [comment]
Hey @mrbungle64,

heute zwei mal. Einmal um 11:35 Uhr und um 14:08 Uhr.

Ja, die Version meine ich. Ich dachte vielleicht nehme ich mal die neuste Version und der Fehler ist weg... leider ist dem nicht so.

Danke für deine schnelle Antwort ;-)

**Comment by fabianbmann** [comment]
Hier mal die Logs. Vielleicht bringt dir das was.

> 2021-05-19 10:14:03.984 - info: admin.0 (9222) Request actual repository...
> 2021-05-19 10:14:04.697 - info: host.____home Updating repository "stable" under "http://download.iobroker.net/sources-dist.json"
> 2021-05-19 10:14:06.437 - info: admin.0 (9222) Repository received successfully.
> 2021-05-19 10:17:38.743 - info: admin.0 (9222) Adapter rating updated
> 2021-05-19 11:35:18.906 - info: ecovacs-deebot.0 (25283) cleaned everything up...
> 2021-05-19 11:35:18.920 - error: ecovacs-deebot.0 (25283) Received disconnect event from library

> 2021-05-19 14:08:33.724 - info: ecovacs-deebot.0 (8385) cleaned everything up...
> 2021-05-19 14:08:33.726 - error: ecovacs-deebot.0 (8385) Received disconnect event from library

**Comment by mrbungle64** [comment]
@fabianbmann 

> heute zwei mal. Einmal um 11:35 Uhr und um 14:08 Uhr.

Das kann schon mal vorkommen - z.B. weil die Verbindung zu den Ecovacs Servern weg war.

Was steht im Datenpunkt "info.error" wenn der Fehler auftritt?

> Ja, die Version meine ich. Ich dachte vielleicht nehme ich mal die neuste Version und der Fehler ist weg... leider ist dem nicht so.

Das heißt, dass Du vorher die 1.1.0 oder 1.1.1 benutzt hast und dass das Fehler damit auch aufgetreten ist?

**Comment by fabianbmann** [comment]
> Was steht im Datenpunkt "info.error" wenn der Fehler auftritt?

Sind die Logs von eben ok? "info.error" steht da leider sonst nirgends. 

Genau, vorher die 1.1.1

**Comment by mrbungle64** [comment]
> Hier mal die Logs. Vielleicht bringt dir das was.
> 
> > 2021-05-19 10:14:03.984 - info: admin.0 (9222) Request actual repository...
> > 2021-05-19 10:14:04.697 - info: host.____home Updating repository "stable" under "http://download.iobroker.net/sources-dist.json"
> > 2021-05-19 10:14:06.437 - info: admin.0 (9222) Repository received successfully.
> > 2021-05-19 10:17:38.743 - info: admin.0 (9222) Adapter rating updated
> > 2021-05-19 11:35:18.906 - info: ecovacs-deebot.0 (25283) cleaned everything up...
> > 2021-05-19 11:35:18.920 - error: ecovacs-deebot.0 (25283) Received disconnect event from library
> 
> > 2021-05-19 14:08:33.724 - info: ecovacs-deebot.0 (8385) cleaned everything up...
> > 2021-05-19 14:08:33.726 - error: ecovacs-deebot.0 (8385) Received disconnect event from library

Du solltest das Log Level mal auf Debug stellen.

**Comment by mrbungle64** [comment]
> "info.error"

Ich meine den Datenpunkt.

**Comment by fabianbmann** [comment]
Log Level vom Ecovacs-Adapter umgestellt auf Debug.

Da steht nichts drin sehe ich gerade. Überall...


<img width="1237" alt="Bildschirmfoto 2021-05-19 um 20 20 22" src="https://user-images.githubusercontent.com/56969243/118863959-c78c2380-b8df-11eb-8643-317b7b566040.png">
<img width="1308" alt="Bildschirmfoto 2021-05-19 um 20 21 01" src="https://user-images.githubusercontent.com/56969243/118863972-cb1faa80-b8df-11eb-892a-7ed4ec4cd2a6.png">

**Comment by mrbungle64** [comment]
> Da steht nichts drin sehe ich gerade. Überall...

War das mit der Version 1.1.1 auch schon so?

Bitte mal ausfüllen:

 - Node.js version: [e.g. "v10.23.0"]
 - JS controller version:  [e.g. "3.1.6"]
 - Operating system: [e.g. "Linux", "Windows 10"]
 - Hardware: [e.g. "Raspberry Pi 4"]

**Comment by mrbungle64** [comment]
> Wenn ich mich nicht irre, war es da nicht so. Kann gerne nochmal downgraden wenn es helfen könnte.
> 
> - Node.js version: [v12.22.1]
> - JS controller version: [3.3.10]
> - Operating system: [RaspbianOs]
> - Hardware: [Raspberry Pi 4]

Benutzt du beim Admin Adapter auch eine beta?

**Comment by fabianbmann** [comment]
Ja, hatte das letzte Woche umgestellt und jetzt wieder auf "Stable". Weil die iobroker Oberfläche garnicht mehr zu erreichen war.
Ich glaube ich sollte das alles mal wieder zurück setzen oder?

**Comment by mrbungle64** [comment]
> Ja, hatte das letzte Woche umgestellt und jetzt wieder auf "Stable". Weil die iobroker Oberfläche garnicht mehr zu erreichen war.
> Ich glaube ich sollte das alles mal wieder zurück setzen oder?

Ja bitte alles zurück auf die Stable Versionen.
Und den Ecovacs Deebot Adapter mal komplett inkl Datenpunkte löschen (die scheinen ja eh gerade nicht mehr korrekt befüllt zu sein) und dann auch die Stable Version installieren.

**Comment by fabianbmann** [comment]
Werde ich machen und berichten! Danke für deine Hilfe!
Wünsche dir einen schönen Abend!

**Comment by fabianbmann** [comment]
Alles klar! Nie wieder Beta "testen". Klappt wieder. Ich hab keine Ahnung was es war, hoffe es konnte dir auch helfen bei der Entwicklung. Nochmals, vielen Dank für deine tolle Arbeit hier! Wünsch dir was!

PS: Alle Infos wieder da. Hoffe das disconnect Problem hat sich dann auch erledigt.

<img width="1308" alt="Bildschirmfoto 2021-05-19 um 21 50 39" src="https://user-images.githubusercontent.com/56969243/118875722-b09ffe00-b8ec-11eb-85ce-dd4656e61d15.png">

**Comment by mrbungle64** [comment]
@fabianbmann 

> Alles klar! Nie wieder Beta "testen". Klappt wieder. Ich hab keine Ahnung was es war, hoffe es konnte dir auch helfen bei der Entwicklung. Nochmals, vielen Dank für deine tolle Arbeit hier! Wünsch dir was!

Freut mich, das alles wieder suaber läuft 👍🏻 

> PS: Alle Infos wieder da. Hoffe das disconnect Problem hat sich dann auch erledigt.

Dass der Adapter bzw. die Library ab und zu mal kurz disconnected sind ist leider normal, da die Verbdindung zu den Ecovacs Servern nicht die stabilste ist. Das merkt man ja auch in der offiziellen Ecovacs App.
Worauf du achten solltest ist, ob der Adapter sich dann autom. neu verbindet.
Sollte das nicht der Fall sein oder nicht klappen melde dich bitte wieder und schau mal, was in dem Moment im Log steht und was im Datenpunkte "info.error" steht.
Aber hoffen wir mal, dass es nun weitgehend stabil durchläuft 😉

**Comment by mrbungle64** [comment]
Ich schließe den Issue jetzt erst mal. Falls du erneut Probleme haben solltest kannst du den wieder öffnen.
