### ISSUE TITLE
Letzte "Anwesenheit" des Roboters pro Raum

### ISSUE THREAD

**Issue by benep** [mrbungle64/ioBroker.ecovacs-deebot#144]
Hallo Sascha,

ich hab heute mal nach langer Zeit wieder eine Alpha-Version von deinem Adapter für meinen T8 installiert und mich sehr über einige Ergänzungen gefreut. Vor allem die `lastTimeDustboxRemoved`, `lastSquareMeters `und die `savedCustomSports`.

Seit einiger Zeit nutze ich auch intensiv den Datenpunkt `map.deebotPositionCurrentSpotAreaID` und da hätte ich eine Ergänzung.
Ich habe mir ein Blockly geschrieben, das bei Änderung des Datenpunkts, wenn gesaugt wird und nach einem Timeout von momentan 3 Minuten das aktuelle Datum in `map.xyz.spotAreas.abc.spotAreaLastCleaning` und falls die Waterbox installiert ist auch `map.xyz.spotAreas.abc.spotAreaLastMopping` schreibt. Der Timeout ist wichtig, weil die CurrentSpotAreaID an den Raumgrenzen gerne hin- und herspringt, bzw. ein durchfahren ja nicht als "Reinigung" gezählt werden soll. Bei mir braucht er für den kleinsten Raum 3,5 Minuten, daher verwende ich 3 Minuten. Den könnte man vielleicht konfigurierbar machen.

Dadurch weiß ich wann welcher Raum gesaugt bzw. gewischt wurde. Statt einer Auto-Reinigung starte ich jetzt immer ein "Smart-Reinigung", die nur Räume ansteuert, die die letzten 12 Stunden nicht gesaugt wurden. Das hat sich als sehr praktisch erwiesen, weil bei mir machmal die Türen zu sind, der Sauger sich zufällig nicht über meine 2cm-Türschwellen traut, er aus den Räumen mit 3cm-Schwellen nicht mehr raus kommt oder ich die Reinigung zum telefonieren beende.

Ich glaube die Werte sind allgemein sehr spannend. Beispielsweise könnte auch #132 dadurch gelöst werden. Indem @chris76e einfach vergleicht welche lastPresence-Werte der Räume nach `history.timestampOfLastStartCharging` liegen.

Leider sind die Blocklys immer recht anfällig, desshalb würde ich mich sehr freuen, wenn du das in den Adapter aufnehmen könntest. Ich glaube das ist auch gar nicht so kompliziert. Gerne kann ich da mein Blockly zur Verfügung stellen, falls das hilft.

**Comment by mrbungle64** [comment]
Hallo @benep 

das klingt sinnvoll 👍🏻 
Ich das mal für demnächst ein 😉

**Comment by mrbungle64** [comment]
@benep @chris76e
Kurzes Update:
Ich habe letztens was eingebaut, was bei mir auch schon ganz gut funktioniert hat.
Allerdings habe ich dabei festgestellt, dass ich in der Ecke mal ein bisschen den bestehenden Code aufäumen sollte, bevor ich da neue Features einbaue. Daher ist das Feature in der aktuellen Version noch nicht enthalten.

**Comment by benep** [comment]
Du machst das schon richtig. Sag bescheid, wenn ich beim Testen helfen kann. Danke, dass du dich drum kümmerst!

**Comment by krobipd** [comment]
Sehr coole Idee, wäre echt praktisch da man den ja nicht sonderlich glauben darf ob er wirklich überall gesaugt hat usw. hab auch schon mit der Idee gespielt wie ich so eine „war er wirklich in den Raum“ Überwachung mache.

**Comment by mrbungle64** [comment]
@krobipd 

> Sehr coole Idee

Ja finde ich auch, aber ich bin leider noch nicht dazu gekommen den betreffenden Teil mal aufzuräumen.
Wenn die Sache nicht wäre, dass der Bot immer mal wieder knapp die Schwelle zu einem anderen Bereich überschreiten würde wäre es ja recht schnell eingebaut 😉

**Comment by mrbungle64** [comment]
@benep @krobipd

Man kann den "Schwellenwert" nun auch einstellen (unter "Experimental" unten rechts).
Aktuell hat man 10, 20, 30, 60, 120 und 180 Sekunden zur Auswahl.
Falls Euch da noch was fehlt kann ich das gerne noch hinzufügen.

@benep 
Ein Datenpunkt für "LastMopping" werde ich auch noch einbauen.

**Comment by chris76e** [comment]
@mrbungle64 das mit dem Schwellenwert ist bei mir nicht vorhanden mit der Version 1.3.5-alpha.0

**Comment by mrbungle64** [comment]
@chris76e 

> @mrbungle64 das mit dem Schwellenwert ist bei mir nicht vorhanden mit der Version 1.3.5-alpha.0

Du musst mit folgendem Link installieren (siehe auch [hier](https://github.com/mrbungle64/ioBroker.ecovacs-deebot/issues/144#issuecomment-1055792395))
https://github.com/mrbungle64/ioBroker.ecovacs-deebot/tree/feature/spotareas/lastPresence

Btw.: Ich dachte Du wärst bei GitHub der Benutzer krobipd 😉

**Comment by chris76e** [comment]
@mrbungle64 

jetzt klappt es, danke

**Comment by benep** [comment]
Sau gut! Vielen Dank @mrbungle64 .

Hat bei mir auch funktioniert wie erwartet. Es läuft auch viel besser, als meine bisherige Blockly-Version. Bei der aller ersten Reinigung wurde der erste Raum trotz deutlich überschrittenem Schwellwert nicht erkannt. Entered und Persence sind leer geblieben, nur der Leaved wurde gesetzt. Die weiteren Räume bei der gleichen Reinigung gingen ohne Probleme. Das konnte ich aber bei weiteren Reinigung nicht mehr reproduzieren, da hat alles funktioniert.

Ich habe meine Scripte darauf umgebaut und werde das die nächsten Tage beobachten. Das Mopping wäre noch ein Traum, dann kann ich wieder ein Blockly rauswerfen.

Allerdings wollte ich zum testen eine savedCustomArea starten, das ging mit dieser Version leider nicht.

host.raspberrypi |   | 2022-03-02 18:56:49.568 | info | instance system.adapter.ecovacs-deebot.0 started with pid 25107
-- | -- | -- | -- | --
host.raspberrypi |   | 2022-03-02 18:56:19.549 | info | Restart adapter system.adapter.ecovacs-deebot.0 because enabled
host.raspberrypi |   | 2022-03-02 18:56:19.549 | error | instance system.adapter.ecovacs-deebot.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
host.raspberrypi |   | 2022-03-02 18:56:19.545 | error | Caught by controller[0]: (Use `node --trace-warnings ...` to show where the warning was created)
host.raspberrypi |   | 2022-03-02 18:56:19.544 | error | Caught  by controller[0]: (node:25062) Warning: Accessing non-existent property  'startCustomAreaCleaning' of module exports inside circular dependency
ecovacs-deebot.0 | 25062 | 2022-03-02 18:56:18.912 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
ecovacs-deebot.0 | 25062 | 2022-03-02 18:56:18.910 | info | terminating
ecovacs-deebot.0 | 25062 | 2022-03-02 18:56:18.908 | info | cleaned everything up...
ecovacs-deebot.0 | 25062 | 2022-03-02 18:56:18.901 | error | commands.startCustomAreaCleaning is not a function
ecovacs-deebot.0 | 25062 | 2022-03-02 18:56:18.899 | error | TypeError:  commands.startCustomAreaCleaning is not a function    at  /opt/iobroker/node_modules/iobroker.ecovacs-deebot/lib/mapHelper.js:393:26
ecovacs-deebot.0 | 25062 | 2022-03-02 18:56:18.898 | error | unhandled promise rejection: commands.startCustomAreaCleaning is not a function
ecovacs-deebot.0 | 25062 | 2022-03-02 18:56:18.896 | error | Unhandled  promise rejection. This error originated either by throwing inside of  an async function without a catch block, or by rejecting a promise which  was not handled with .catch().

**Comment by mrbungle64** [comment]
@benep 

> Hat bei mir auch funktioniert wie erwartet. Es läuft auch viel besser, als meine bisherige Blockly-Version.

Danke schon mal für das (positive) Feedback soweit 👍🏻 

> Bei der aller ersten Reinigung wurde der erste Raum trotz deutlich überschrittenem Schwellwert nicht erkannt.

Ist das der Raum, wo auch die Ladestation ist bzw. wo die Reinigung startet?

> Allerdings wollte ich zum testen eine savedCustomArea starten, das ging mit dieser Version leider nicht.

Der Fehler ist behoben.

Bitte so lange ich nichts anderes sage wieder mit dem Link installieren:
https://github.com/mrbungle64/ioBroker.ecovacs-deebot/tree/feature/spotareas/lastPresence

**Comment by mrbungle64** [comment]
@benep 

> Das Mopping wäre noch ein Traum, dann kann ich wieder ein Blockly rauswerfen.

Habe das eben ebenfalls noch implementiert

* lastTimeMoppingTimestamp
* lastTimeMoppingDateTime

**Comment by Snago636** [comment]
Hallo Sascha,

so ich habe das ganze jetzt mal getestet. Bei mir scheint alles wunderbar zu klappen. Vielen Dank.

> 
>     Bei der aller ersten Reinigung wurde der erste Raum trotz deutlich überschrittenem Schwellwert nicht erkannt.
> 
> Ist das der Raum, wo auch die Ladestation ist bzw. wo die Reinigung startet?

Da war es bei mir umgekehrt. Beim ersten Test hab ich den Raum wo die Ladestation steht nicht reinigen lassen, Aber wurde als gereinigt erkannt. Aber beim zweiten test lief es Problemlos und hat erkannt wo er gereinigt hat.
Mopping muß ich noch testen.

gruß Andy

**Comment by mrbungle64** [comment]
> Hallo Sascha,
> 
> so ich habe das ganze jetzt mal getestet. Bei mir scheint alles wunderbar zu klappen. Vielen Dank.
> 

Danke für das Feedback 👍🏻 

> Da war es bei mir umgekehrt. Beim ersten Test hab ich den Raum wo die Ladestation steht nicht reinigen lassen, Aber wurde als gereinigt erkannt. Aber beim zweiten test lief es Problemlos und hat erkannt wo er gereinigt hat.

Ja, das müssen wir jetzt mal beobachten.

Die Spot Area wo die Ladestation steht bedarf sicherlich noch mal besonderem Fokus und ein Relocate muss auch noch behandelt werden - Stop und Pause eigentlich auch.

**Comment by mrbungle64** [comment]
@chris76e 

> @mrbungle64
> 
> jetzt klappt es, danke

Konntest Du schon ein bisschen testen?

**Comment by chris76e** [comment]
@mrbungle64 

beim reinigen vom Raum wo die Ladestation steht bekomme ich keine Daten in lastTimePresence. In den anderen Räume klappt es.

**Comment by krobipd** [comment]
hey 👋
@mrbungle64  vielen dank das du dieses echt tolle feature eingebaut hast bzw dabei bist
bin natürlich auch beim testen ;-) wenn ich mir die Daten so ansehen scheint alles zu funktionieren - mopping noch nicht probiert - aber in den räumen wo er schon war gibt es Daten.

werde mir das mal die tage genau ansehen, wenn ich daheim bin und live sehen kann was der Roboter und der adapter macht.

**Comment by mrbungle64** [comment]
@benep @krobipd @Snago636 @chris76e 

Danke schon mal für das Feedback 👍🏻 

Ich muss noch den Reinigungsmodus (+ ggf die gewählten Spot Areas bzw. die Custom Area) abfragen - damit dabei berücksichtigt wird, ob der Raum wo die Ladestation steht auch direkt gezählt werden muss.
Zusätzlich müsste noch bei "Relocate", "Stop", "Pause" und "Resume" noch was passieren (wo oben schon geschrieben).

Ich melde mich wenn ich dazu was eingebaut habe.

**Comment by benep** [comment]
Also ich verwende das seit einiger Zeit und bin immer noch begeistert, weil dich dadurch täglich viel weniger einstellen muss und die offizielle App fast gar nicht mehr brauche. Mein einziges Problem damit, ist der Raum in dem der Roboter gestartet wird (unabhängig von der Ladestation). Dieser wird nicht erkannt. Ich könnte mir auch vorstellen, dass das das Ladestations-Problem löst. Wäre ein Traum, wenn du @mrbungle64 da nochmal drüber schauen könntest.

**Comment by mrbungle64** [comment]
@benep 

> Also ich verwende das seit einiger Zeit und bin immer noch begeistert, weil dich dadurch täglich viel weniger einstellen muss und die offizielle App fast gar nicht mehr brauche. Mein einziges Problem damit, ist der Raum in dem der Roboter gestartet wird (unabhängig von der Ladestation). Dieser wird nicht erkannt. Ich könnte mir auch vorstellen, dass das das Ladestations-Problem löst. Wäre ein Traum, wenn du @mrbungle64 da nochmal drüber schauen könntest.

Freut mich, dass du die Funktion so ausführlich nutzt. Danke für das Feedback 👍🏻 
Das geschilderte Problem schaue ich mir an.

**Comment by mrbungle64** [comment]
@benep 

> Mein einziges Problem damit, ist der Raum in dem der Roboter gestartet wird (unabhängig von der Ladestation). Dieser wird nicht erkannt

Ich kann das bei mir leider nicht nachstellen. Beim mir funktioniert das eigentlich soweit.
Ich kann mir aber vorstellen, dass es sich beim T8 anders verhält als beim OZMO 920/950. In ein paar Tagen habe ich die Möglichkeit das mit einem T8 zu testen - mal schauen ob ich das dann nachstellen kann.

> Ich könnte mir auch vorstellen, dass das das Ladestations-Problem löst.

Was meinst du damit? Ich kann es gerade nicht einordnen ...

**Comment by benep** [comment]
>    Ich könnte mir auch vorstellen, dass das das Ladestations-Problem löst.
> Was meinst du damit? Ich kann es gerade nicht einordnen ...

Naja, wenn generell der Startraum nicht gezählt wird, dann schließt das ja den Raum mit der Ladestation ein. Aber scheinbar ist es bei mir ja ein anderes Problem.

> Ich kann das bei mir leider nicht nachstellen. Beim mir funktioniert das eigentlich soweit.

Vielleicht noch als Ergänzung. Der Roboter war bei mir immer nicht lokalisiert. Also manuell in einen Raum stellen, orten, erfolgreich geortet und dann starten. Dann schreibt er das Datum für den Raum nicht.

**Comment by mrbungle64** [comment]
@benep 

> Vielleicht noch als Ergänzung. Der Roboter war bei mir immer nicht lokalisiert. Also manuell in einen Raum stellen, orten, erfolgreich geortet und dann starten. Dann schreibt er das Datum für den Raum nicht.

Das ist evtl. der entscheidende Punkt. Wie (also mit welcher Funktion) startest du den dann?

**Comment by benep** [comment]
> Wie (also mit welcher Funktion) startest du den dann?

Also meist muss ich mehrfach orten, bevor er seine Position erkennt. Dann nutze ich deinen Datenpunk `ecovacs-deebot.0.control.spotArea`

**Comment by mrbungle64** [comment]
@benep 

Sollte mit der Version 1.4.1-alpha.1 (GitHub) gefixt sein.
Problem war, dass beim orten der Event über die geänderte Spot Area empfangen wird, bevor der Reinigungsvorgang gestartet wird. In dem Fall blieb der dann intern noch der vorherigen Spot Area zugeordnet.
Freue mich über Feedback 😉 

Btw.: Was ich noch fixen muss ist, dass wenn man Spot Areas reinigen lässt, welche nicht die mit der Ladestation enthalten, aber von der Ladestation gestartet wird. Dann ist der Status nämlich direkt "cleaning" (und nicht erst wenn die erste zu reinigende Spot Area erreicht wird)

**Comment by benep** [comment]
Wow so schnell, Danke.

Ich hab die Alpha ausprobiert und es scheint zu funktionieren. Ich beobachte weiter.

**Comment by mrbungle64** [comment]
> Btw.: Was ich noch fixen muss ist, dass wenn man Spot Areas reinigen lässt, welche nicht die mit der Ladestation enthalten, aber von der Ladestation gestartet wird. Dann ist der Status nämlich direkt "cleaning" (und nicht erst wenn die erste zu reinigende Spot Area erreicht wird)

Mit der Version 1.4.1-alpha.2 wird nun im Falle eine Spot Area Reinigung auch berücksichtigt, welche Spot Areas enthalten sind. Die o.g. genannte Problematik sollte also gelöst sein.

**Comment by chris76e** [comment]
Super, funktioniert bei mir. Vielen Dank.

Ist es auch möglich das du die beiden Punkte lastSquareMeters und lastTotalTimeString in den SportAreas reinmachst?

**Comment by mrbungle64** [comment]
@chris76e 

> Super, funktioniert bei mir. Vielen Dank.

Danke für das Feedback 👍🏻 

> 
> Ist es auch möglich das du die beiden Punkte lastSquareMeters und lastTotalTimeString in den SportAreas reinmachst?

Du meinst, dass man pro Spot Area die tatsächlich gereinigte Fläche und die Reinigungszeit jeweils als Datenpunkt hat?
Die tatsächlich gereinigte Fläche pro Spot Area könnte aber ggf. schwierig werden ...

**Comment by chris76e** [comment]
Ja, das meinte ich., obwohl,wenn ich jetzt darüber nachdenke, ist auch nicht so wichtig, denn die Fläche ändert sich ja im normalfall nicht....

Nochwas anderes was ich immer mal fragen wollte. Kann man unter spotAreaName selber einen Namen der Area vergeben? Mir werden die immer durch A, B usw. ersetzt.

**Comment by mrbungle64** [comment]
> Ja, das meinte ich., obwohl,wenn ich jetzt darüber nachdenke, ist auch nicht so wichtig, denn die Fläche ändert sich ja im normalfall nicht....

Ja, ich denke auch, dass sich der Nutzen davon in Grenzen halten würde. Man müsste dann halt auch z.B. von der Zeit abziehen, wenn der Reinigungsvorgang unterbrochen wird - oder eine neue Ortung (relocate) müsste berücksichtigt werden etc....

> 
> Nochwas anderes was ich immer mal fragen wollte. Kann man unter spotAreaName selber einen Namen der Area vergeben? Mir werden die immer durch A, B usw. ersetzt.

Welches Modell hast du noch mal? Je nach Modell gibt es da andere Einschränkungen

**Comment by chris76e** [comment]
Deebot 901

**Comment by mrbungle64** [comment]
@chris76e 

> Deebot 901

Wenn Du den "spotAreaName" überschreibst, wird das wieder mit dem Wert der von der Ecovacs API kommt überschrieben. Das ist leider bei den älteren Modellen (dazu gehört der Deebot 901) dann immer A, B, C, etc.
Ich könnte eine Option anbieten dass man das ausstellen kann, dass die Werte per API aktualisiert werden.
Könntest Du dafür einen separaten Issue erstellen?

**Comment by chris76e** [comment]
erledigt

**Comment by mrbungle64** [comment]
@benep 

> Wow so schnell, Danke.
> 
> Ich hab die Alpha ausprobiert und es scheint zu funktionieren. Ich beobachte weiter.

Könntest Du mir noch mal (abschließendes) Feedback geben?
Ich würde den Issue gerne schließen.

**Comment by mrbungle64** [comment]
Anmerkungen:

* Die Version 1.4.0 ist seit heute im Stable Repo (mit dieser Version wurde die Funktion eingeführt)
* Mit der Version 1.4.1 (noch Latest/Beta Repo) wurden die Optimierungen released

**Comment by benep** [comment]
Ich teste gerade mit der 1.4.2. Der Startraum mit der Station funktioniert jetzt.

Aber, ich lassen den Roboter oft am Wochenende während dem Frühstück das Schlafzimmer saugen. Da funktioniert das Update der entered- und presence-Werte nicht. Übrigens auch nicht im vorherigen Raum für leaved. Dafür nehme ich den Roboter aus seiner Ladestation, trage ihn ins Schlafzimmer, lasse ihn orten (meist braucht er mehrere Versuche dafür) und wenn er sich lokalisiert hat, dann starte ich eine Spot-Reinigung, nur im Schlafzimmer.

Hab das auch grad nochmal in einem anderen Raum getestet, auch da geht es nicht, wenn ich den Roboter reinstelle, orte und starte.

Die Mopping-Werte habe ich bisher leider immer noch nicht getestet.

**Comment by mrbungle64** [comment]
@benep 

> dann starte ich eine Spot-Reinigung, nur im Schlafzimmer

Über welchen Datenpunkt startest du die Reinigung? Mit "Spot"-Reinigung meinst du eine "Spot Area"-Reinigung?
Eine "Spot"-Reinigung gibt es nämlich (nur) bei Modellen ohne Laser-Navigation.

> Übrigens auch nicht im vorherigen Raum für leaved

Meinst du den Raum wo du den Roboter nimmst und dann in ein anderes Zimmer trägst?

**Comment by mrbungle64** [comment]
@benep 

Was ist der Unterschied zwischen dem aktuell beschriebenen Szenario und dem welches [hier](https://github.com/mrbungle64/ioBroker.ecovacs-deebot/issues/144#issuecomment-1114191281) beschrieben ist.
Das hatte ich ja eigentlich schon [behoben](https://github.com/mrbungle64/ioBroker.ecovacs-deebot/issues/144#issuecomment-1114222510) (dachte ich zumindest)

**Comment by benep** [comment]
>  Mit "Spot"-Reinigung meinst du eine "Spot Area"-Reinigung?

Ja, richtig. Ich denk da immer nicht dran, weil der T8 das ja gar nicht kann.

> Über welchen Datenpunkt startest du die Reinigung? 

Meistens über `ecovacs-deebot.0.control.spotArea_2` aber auch `ecovacs-deebot.0.control.spotArea` = 2 oder über die Ecovacs-App.

> Meinst du den Raum wo du den Roboter nimmst und dann in ein anderes Zimmer trägst?

Genau.

> Was ist der Unterschied zwischen dem aktuell beschriebenen Szenario und dem welches https://github.com/mrbungle64/ioBroker.ecovacs-deebot/issues/144#issuecomment-1114191281 beschrieben ist.
Das hatte ich ja eigentlich schon https://github.com/mrbungle64/ioBroker.ecovacs-deebot/issues/144#issuecomment-1114222510 (dachte ich zumindest)

Stimmt ist das gleiche. Ich befürchte da war ich vorschnell mit meiner Antwort. Das hat danach nie mehr funktioniert. Wahrscheinlich hatte ich da was falsch getestet.

**Comment by mrbungle64** [comment]
@benep 

> Aber, ich lassen den Roboter oft am Wochenende während dem Frühstück das Schlafzimmer saugen. Da funktioniert das Update der entered- und presence-Werte nicht. Übrigens auch nicht im vorherigen Raum für leaved. Dafür nehme ich den Roboter aus seiner Ladestation, trage ihn ins Schlafzimmer, lasse ihn orten (meist braucht er mehrere Versuche dafür) und wenn er sich lokalisiert hat, dann starte ich eine Spot-Reinigung, nur im Schlafzimmer.

Schau mal bitte, ob es mit der aktuellen Version (GitHub) besser funktioniert.

**Comment by benep** [comment]
Woran sehe ich denn, ob er die Version von GitHub übernommen hat? Das Installieren über den GitHub-Tab hat jetzt zweimal ewig gedauert. Im Log steht dann non-npm
`starting. Version 1.4.2 (non-npm: mrbungle64/ioBroker.ecovacs-deebot) in /opt/iobroker/node_modules/iobroker.ecovacs-deebot, node: v14.19.2, js-controller: 4.0.23`

Wenn das geklappt hat, dann befürchte ich nicht. 

`ecovacs-deebot.0.map.deebotPositionCurrentSpotAreaID` wird korrekt auf 2 geändert und laufend aktualisiert.
`ecovacs-deebot.0.map.relocationState` wird auf ok geändert.
`ecovacs-deebot.0.map.deebotPositionIsInvalid` is korrekt auf false.

Aber:
`ecovacs-deebot.0.map.1524493950.spotAreas.2.lastTimePresenceDateTime` bleibt auf dem alten Wert.

**Comment by benep** [comment]
Ich hab grad noch bissl rum gespielt. Vielleicht stimmt auch was mit der Lokalisierung nicht. Wenn ich den Roboter hoch hebe, dann springt `ecovacs-deebot.0.map.relocationState` auf required, aber `ecovacs-deebot.0.map.deebotPositionIsInvalid` bleibt auf false.

**Comment by mrbungle64** [comment]
> Ich hab grad noch bissl rum gespielt. Vielleicht stimmt auch was mit der Lokalisierung nicht. Wenn ich den Roboter hoch hebe, dann springt `ecovacs-deebot.0.map.relocationState` auf required, aber `ecovacs-deebot.0.map.deebotPositionIsInvalid` bleibt auf false.

Das sollte hier eigentlich ausreichen, da ich nur auf `relocationState` schaue.

**Comment by benep** [comment]
Ah, außer wenn der Roboter am Reinigen ist, dann wird der `ecovacs-deebot.0.map.deebotPositionIsInvalid` Wert auf true gesetzt.

Und zuletzt noch. Wenn ich den Roboter ins Zimmer stelle und nur die SpotArea-Reinigung starte, er also selbstständig eine Lokalisierung startet, dann wird `ecovacs-deebot.0.map.1524493950.spotAreas.2.lastTimePresenceDateTime` korrekt upgedated.

**Comment by benep** [comment]
Jetzt habe ich den Roboter nur bissl durch die Gegend getragen.

- Der Sauger ist lokalisiert und steht in Raum A. Entered und Leaved sind falsch. 
- Ich trage den Roboter in Raum B. In Raum A wird dabei Leaved korrekt gesetzt. 
- Nun klicke ich auf Lokalisieren. Sofort wird in Raum A!!! Entered aktualisiert. Nach paar Sekunden wird in Raum B Entered aktualisiert.
- Ich trage den Roboter weiter in Raum C. In Raum B wird Leaved korrekt gesetzt.
- Ich klicke wieder auf Lokalisieren. Sofort wird in Raum B!!! Entered aktualisiert. Entered in Raum C wird nicht aktualisiert, obwohl die Lokalisierung erfolgreich war.
- Weiter in Raum D tragen. Leaved in C wird wieder richtig gesetzt.
- Ich klicke wieder auf Lokalisieren. Sofort wird in Raum C!!! Entered aktualisiert. Entered in Raum D wird auch nicht aktualisiert, obwohl die Lokalisierung wieder erfolgreich war.
- Zurück nach A tragen. Leaved in D wird wieder richtig gesetzt.
- Ich klicke wieder auf Lokalisieren. Sofort wird in Raum D!!! Entered aktualisiert. Entered in Raum A wird auch nicht aktualisiert, obwohl die Lokalisierung wieder erfolgreich war.

**Comment by benep** [comment]
Ok hab das Update. Wieder ewige Installation, aber jetzt gibts ja ne neue Versionsnummer. Es hat also zumindest funktioniert.

Nach dem Neustart des Adapter wurde Entered in Raum A korrekt dann aktualisiert. Das Trage-Spiel läuft genau gleich ab, trotz anderer Reihenfolge. Entered wird immer bei Start der Lokalisierung falsch im vorherigen Raum gesetzt. Beim ersten Mal wird dann Entered im neuen Raum korrekt gesetzt, bei allen weiteren Versuchen in anderen Räumen dann nicht mehr.

**Comment by mrbungle64** [comment]
@benep 

Danke für die vielen Infos 👍🏻 

Ich habe noch eine weitere Änderung vorgenommen.
Meine Hoffnung ist, dass es bei dir nun die Zustände korrekt verarbeitet 😉 
(Version ist noch die 1.4.3-alpha.0)

**Comment by mrbungle64** [comment]
> Tatsächlich habe ich es jetzt weiter getestet und die letzten 4 Male hat er den Entered-Wert im neuen Raum immer korrekt gesetzt. Dann hat auch das Presence-Update beim Renigen funktioniert. Komisch ich habe nichts anders gemacht.

Ich denke das liegt daran, dass die Messages wo ich die Behandlung eingebaut habe, nicht immer in der gleichen Reihenfolge kommen. Dann kann das mal passen - mal nicht.

Aber mit der letzten Änderung sollte es hoffentlich in den meisten Fällen passen.

> 
> Im alten Raum wird der Entered-Wert allerdings immer noch konstant falsch gesetzt.

Das verstehe ich leider nicht. Meinst du den "Leaved" Wert?

> 
> Teste jetzt nächste Version.

👍🏻

**Comment by benep** [comment]
> Das verstehe ich leider nicht. Meinst du den "Leaved" Wert?

Ich trag den Sauger von Raum A in Raum B. Dann klicke ich Lokalisieren. 200 Millisecunden später wird in Raum A der Wert `ecovacs-deebot.0.map.x.spotAreas.0.lastTimeEnteredTimestamp` auf die aktuelle Zeit gesetzt.

**Comment by mrbungle64** [comment]
> > Das verstehe ich leider nicht. Meinst du den "Leaved" Wert?
> 
> Ich trag den Sauger von Raum A in Raum B. Dann klicke ich Lokalisieren. 200 Millisecunden später wird in Raum A der Wert `ecovacs-deebot.0.map.x.spotAreas.0.lastTimeEnteredTimestamp` auf die aktuelle Zeit gesetzt.

Der Fehler sollte mit dem Update von 16 Uhr bereits gefixed sein

**Comment by benep** [comment]
> Der Fehler sollte mit dem Update von 16 Uhr bereits gefixed sein

Hab ich aktuell immer noch. Allerdings dauer es jetzt deutlich länger, so eine Sekunde.

**Comment by mrbungle64** [comment]
@benep 

Kurze Zwischeninfo:
Das Verhalten wird von Ecovacs Seite ausgelöst, weil im quasi exakt gleichen Moment die alte und auch die neue Position bzw. Spot Area gemeldet wird. Daher bekommt auch die alte Spot Area noch ein Entered Wert verpasst, da ich zu dem Zeitpunkt schon eine geänderte Spot Area erwarte ... Recht knifflig das Ganze ....

**Comment by mrbungle64** [comment]
@benep 

Mit der 1.4.3-alpha.1 funktioniert es nun hoffentlich 😉 

2 Infos dazu:
* Der "lastTimeEnteredTimestamp" wird nur noch während einer laufenden Reinigung gesetzt
* "lastTimeLeavedTimestamp" habe ich entfernt (war meiner Meinung nach mehr oder weniger nutzlos)

**Comment by mrbungle64** [comment]
@benep 

> > Der Fehler sollte mit dem Update von 16 Uhr bereits gefixed sein
> 
> Hab ich aktuell immer noch. Allerdings dauer es jetzt deutlich länger, so eine Sekunde. Auch das schau ich mir morgen nochmal genauer an.

Konntest du es inzwischen mal testen?

**Comment by benep** [comment]
Ich hatte bisher keine Probleme mehr im normalen Betrieb. Wegen mir könntest du das Issue schließen.
