### ISSUE TITLE
Timeout für goToPosition

### ISSUE THREAD

**Issue by benep** [mrbungle64/ioBroker.ecovacs-deebot#145]
Das goToPosition-Feature nutze ich inzwischen täglich. Zum Beispiel, damit der Sauger in Räumen mit hohen Schwellen, aus denen er wegen nicht raus kommt, nicht verzweifelt oder unterm Bett stehen bleibt. 

Ein Problem ist mir damit aufgefallen, wenn man die Funktion auslöst, aber der Sauger diesen Punkt nicht erreicht. Später wenn er dann über eine normale Spot-Reinigung an den Punkt kommt, dann bricht er die Reinigung ab.

Evtl. könnte da ein Timeout oder ein Abbruch bei Statusänderung helfen.

**Comment by mrbungle64** [comment]
Hallo @benep 

das Problem sollte mit der aktuellen GitHub Version nicht mehr auftreten.
Der Datenpunkt und der interne Trigger werden bei verschiedenen Befehlen nun gelöscht (z.B. bei "stop", "clean" oder "charge").

**Comment by benep** [comment]
Top. Ich konnte den Fehler jetzt nicht mehr reproduzieren. Ich gehe davon aus, dass das damit gelöst ist.
