### ISSUE TITLE
CurrentMapID oder CurrentMapMID änderbar?

### ISSUE THREAD

**Issue by thoerb** [mrbungle64/ioBroker.ecovacs-deebot#146]
Ich habe einen Deebot OZMO 930, der sich ja bekannterweise keine Etagen merkt. Allerdings sind die Etagen und die dazugehörigen Maps dennoch im Deebot gespeichert. Ich habe mittlerweile knapp 10 Karten, die im ioBroker unter dem Unterordner ‚maps‘ aufgeführt werden.  

**Ist es möglich, dass man die Variable „currentMapIndex“ oder „currentMapMID“ im Bot selbst ändert und dadurch beim Wechsel der Etage im ioBroker die richtige Etagenkarte aufrufen könnte?** Das wäre ein unglaublicher Sprung bei der Nutzung des 930er.

**Comment by mrbungle64** [comment]
Hallo @thoerb

> Ich habe einen Deebot OZMO 930, der sich ja bekannterweise keine Etagen merkt. Allerdings sind die Etagen und die dazugehörigen Maps dennoch im Deebot gespeichert. Ich habe mittlerweile knapp 10 Karten, die im ioBroker unter dem Unterordner ‚maps‘ aufgeführt werden.

die MapID ändert sich von Zeit zu Zeit beim OZMO 930 - keine Ahnung wann genau und warum das passiert ...
Das passiert aber auf jeden Fall irgendwo auf Ecovacs Seite ...

Im Endeffekt sind alle Map-Channels die im Datenpunkt "map.[MapID].mapIsAvailable" den Wert `false` haben wertlos geworden. Die können gelöscht werden (das passiert aber nicht autom.).

> 
> **Ist es möglich, dass man die Variable „currentMapIndex“ oder „currentMapMID“ im Bot selbst ändert und dadurch beim Wechsel der Etage im ioBroker die richtige Etagenkarte aufrufen könnte?** Das wäre ein unglaublicher Sprung bei der Nutzung des 930er.

Das wäre in der Tat ein tolles Feature für den OZMO 930 (und andere ältere Modelle) aber die Ecovacs API stellt da meines Wissens nach keine Möglichkeit bereit. Ab der Generation vom OZMO 950 gibt es da mehr Möglicheiten - aber auch diese sind zum einen undokumentiert (bedeutet es gibt keine öffnetlich zugängliche Dokumentation der API) und auch immer in dem Rahmen wie Ecovacs dies bereitstellt.

Ich denke die Wahrscheinlichkeit lässt sich leider mit ziemlich genau 0 beziffern, dass das möglich ist.
