### ISSUE TITLE
Deebot Ozmo 950: Name des aktiven Stockwerks/Karte

### ISSUE THREAD

**Issue by Opa0815** [mrbungle64/ioBroker.ecovacs-deebot#15]
Der Ozmo 950 unterstützt ja mehrere Etagen/Karten (bis zu 3).
Ist es möglich den Namen und/oder die Nummer aktiven Karte abzufragen/anzuzeigen?

Danke schon mal im Voraus.
Super Arbeit!

**Comment by boriswerner** [comment]
Hi @Opa0815 auch das habe ich bereits herausgefunden. Man bekommt auch die verfügbaren spotAreas heraus, inkl. der ggf. vergebenen Symbole (Wohnzimmer, Esszimmer, ...) in der App.
Allerdings unterstützt der 950 soweit ich weiß nur 2 Karten.
(Ggf. bekommt man es aber auch durch die Set-Funktionen hin die Karten zu sichern und wiederherzustellen. Das ist aber noch ein weiter Weg. Ich wäre schonmal froh, wenn ich in den bestehenden Karten die No-Go-Areas aktivieren und deaktivieren könnte. Auslesen kann ich die auch bereits).

Die technischen Infos der verfügbaren Funktionen hab ich schonmal hier grob dokumentiert (die Tabelle ist recht breit, daher am besten einmal kopieren und in Excel einfügen um alles zu sehen):
https://github.com/boriswerner/ecovacs-API-docs/wiki/commands-toAPI-Deebot-Ozmo-950

**Comment by Opa0815** [comment]
Super, danke

**Comment by sourex** [comment]
falls Ihr an der Stelle weiter kommt, wäre es auch interessant unterschiedlich viele SpotAreas für die Aktive Karte einzupflegen.

Super Arbeit ! Endlich eine Prozentuale Akkuanzeige !!

**Comment by boriswerner** [comment]
@Opa0815 @sourex die neueste Version hier auf GitHub unterstützt nun auch die Netzwerk Informationen, die auch in der App zu sehen sind (IP, MAC, WLAN Name und WLAN Signalstärke). Dazu noch einige Infos zur aktuellen Karte (aktuelle Karte: Name, Index und interne Map ID) und Position (inkl. Relocate) und die Steuerung der Saugkraft.
Weitere Funktionen für die Map sind in Arbeit (Anzeige der verfügbaren Maps inkl. der verfügbaren SpotAreas).
Das ist allerdings etwas zeitaufwendiger

**Comment by Opa0815** [comment]
super

**Comment by boriswerner** [comment]
@Opa0815 der Request hier kann dann zu oder? 
Name des Stockwerks, der Karte ist ja nun da für den 950.
Für weitere Wünsche dann bitte ein neues Issue aufmachen.

**Comment by Opa0815** [comment]
Jap, Danke!
