### ISSUE TITLE
Canvas

### ISSUE THREAD

**Issue by skydiver66** [mrbungle64/ioBroker.ecovacs-deebot#150]
Hello... i
wie stürzt jetzt mein Node Red ständig ab, habe zwar ein Bild der Karte bekommen, aber das nützt mir nicht so viel weil sich Node Red ständig neu startet.... Ich kriege bald nen Nervenzusammenbruch....

Ich kopiere mal die Shell vom Installieren der Canvas Lib, iwie sieht das auch nicht gesund aus. 
Vielleicht kannst Du mir ja nochmal einen Tipp geben ohne dass ich wieder das Backup zücken muss.

VG Tom

[sudo] Passwort für openhabian: 

> canvas@2.8.0 install /home/openhabian/node_modules/canvas
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v83-linux-glibc-arm.tar.gz 
node-pre-gyp WARN Pre-built binaries not installable for canvas@2.8.0 and node@14.17.2 (node-v83 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v83-linux-glibc-arm.tar.gz 
make: Verzeichnis „/home/openhabian/node_modules/canvas/build“ wird betreten
  SOLINK_MODULE(target) Release/obj.target/canvas-postbuild.node
  COPY Release/canvas-postbuild.node
  CXX(target) Release/obj.target/canvas/src/backend/Backend.o
  CXX(target) Release/obj.target/canvas/src/backend/ImageBackend.o
  CXX(target) Release/obj.target/canvas/src/backend/PdfBackend.o
  CXX(target) Release/obj.target/canvas/src/backend/SvgBackend.o
  CXX(target) Release/obj.target/canvas/src/bmp/BMPParser.o
../src/bmp/BMPParser.cc: In member function ‘void BMPParser::Parser::parse(uint8_t*, int, uint8_t*)’:
../src/bmp/BMPParser.cc:186:16: warning: comparison of integer expressions of different signedness: ‘int’ and ‘unsigned int’ [-Wsign-compare]
   E(ptr - data > imgdOffset, "image data overlaps with another structure");
     ~~~~~~~~~~~^~~~~~~~~~~~
../src/bmp/BMPParser.cc:10:25: note: in definition of macro ‘E’
 #define E(cond, msg) if(cond) return setErr(msg)
                         ^~~~
../src/bmp/BMPParser.cc:201:27: warning: comparison of integer expressions of different signedness: ‘uint32_t’ {aka ‘unsigned int’} and ‘int’ [-Wsign-compare]
   E(ptr - data + imgdSize > len, "not enough image data");
     ~~~~~~~~~~~~~~~~~~~~~~^~~~~
../src/bmp/BMPParser.cc:10:25: note: in definition of macro ‘E’
 #define E(cond, msg) if(cond) return setErr(msg)
                         ^~~~
  CXX(target) Release/obj.target/canvas/src/Backends.o
  CXX(target) Release/obj.target/canvas/src/Canvas.o
  CXX(target) Release/obj.target/canvas/src/CanvasGradient.o
  CXX(target) Release/obj.target/canvas/src/CanvasPattern.o
  CXX(target) Release/obj.target/canvas/src/CanvasRenderingContext2d.o
  CXX(target) Release/obj.target/canvas/src/closure.o
  CXX(target) Release/obj.target/canvas/src/color.o
  CXX(target) Release/obj.target/canvas/src/Image.o
  CXX(target) Release/obj.target/canvas/src/ImageData.o
  CXX(target) Release/obj.target/canvas/src/init.o
  CXX(target) Release/obj.target/canvas/src/register_font.o
  SOLINK_MODULE(target) Release/obj.target/canvas.node
  COPY Release/canvas.node
make: Verzeichnis „/home/openhabian/node_modules/canvas/build“ wird verlassen
npm WARN saveError ENOENT: no such file or directory, open '/home/openhabian/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/home/openhabian/package.json'
npm WARN openhabian No description
npm WARN openhabian No repository field.
npm WARN openhabian No README data
npm WARN openhabian No license field.

+ canvas@2.8.0
added 62 packages from 29 contributors and audited 62 packages in 62.697s

5 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

openhabian@openhabian:~ $

**Comment by mrbungle64** [comment]
@skydiver66 

Die Installation von Canvas sieht soweit "normal" aus (im Sinne das das bei der Canvas Installation leider so aussieht 😉)

Du solltest das Laden der Map vorerst deaktivieren/ausschalten.
Falls Du in der "Ecovacs Deebot Node" den Haken "Beim Starten Map Objekt abfragen ..." gesetzt hast dann entferne den bitte.
Und natürlich jegliche Node welche die Map lädt.

Ich hatte das auch schon, dass sich Node-RED beim Abfragen der Map aufgehängt hat - deswegen habe ich den o.g. Haken eingebaut. Hatte das bei mir auf die knappen Ressourcen meines Test-Systems geschoben (Raspberry Pi 3B mit 1GB und versch. Test-Instanzen von z.B. Node-RED und ioBroker).

Die Map-Funktion ist ja noch relativ frisch - da arbeiten wir also noch dran. Werde das dann in nächster Zeit mal versuchen zu analysieren, was da genau passiert in Node-RED beim Abrufen der Map.
Wenn ich die Map direkt über die Library abrufe oder in ioBroker (dort ist die Library integriert) dann ist das bisher ziemlich stabil.

**Comment by mrbungle64** [comment]
@skydiver66 

Dies hier ist das Repository vom ioBroker Adapter.
Bitte erstelle das noch mal im korrekten Repository. Danke 😉
