### ISSUE TITLE
Auto Empty Station steuern

### ISSUE THREAD

**Issue by aquachris2** [mrbungle64/ioBroker.ecovacs-deebot#151]
Hallo,

leider bietet die App von ecovacs nur die Möglichkeit nach dem Reinigungsvorgang automatisch den Schmutzbehälter von der Auto Empty Station entleeren zu lassen. Da diese sehr laut ist und man ggf. gerne in der Nacht den Robbi laufen lassen will wäre es super dann im Laufe des Tages per Script oder Auswahlmöglichkeit die Entleerung separat ansteuern zu können.
Grüße Aqua

**Comment by mrbungle64** [comment]
Hallo @aquachris2,

welches Modell hast Du?

**Comment by aquachris2** [comment]
Hallo Sascha,

ich habe den ecovacs ozmo t8 aivi

Gruß

**Comment by mrbungle64** [comment]
Hallo @aquachris2 

ich plane das mal ein, nachdem ich die nächste Stable Version veröffentlicht habe.
Ich kann aber nicht garantieren, dass es dann auch für Dein Modell funktioniert. Ich habe nämlich keinen T8 (AIVI) hier zum testen (eine öffentlich zugängliche Doku der Ecovacs API, wo man das nachschauen könnte, gibt es ja leider nicht).

**Comment by jipijajay** [comment]
Hi,
ich kann mich @aquachris2 nur anschließen, genau das hatte ich mir auch überlegt. Mit Abwesenheitserkennung verknüpfen und dann eben entleeren wenn man weg ist. 
Also wäre wirklich sehr cool die Funktion.
Bei mir reinigt der ecovacs ozmo t8+.

Gruß
Manuel

**Comment by mrbungle64** [comment]
@aquachris2 @jipijajay 

Ich habe nun (endlich) mal 2 Funktionen für die Auto Empty Station implementiert.

Dafür benötigt Ihr die 1.3.4-alpha.0 von GitHub und Ihr müsst die Funktionen über die Adapter Einstellungen -> Experimental ->  "Einige Funktionen für die Automatische Absaugstation (e.g. T8+ and T9+)" freischalten.

Dann habt Ihr 2 neue Datenpunkte:
- `control.extended.autoEmpty` (Auto empty ein- und ausschalten)
- `control.extended.emptyDustBin` (Entleerung auslösen)

Bin gespannt auf Euer Feedback. Ich kann es ja leider nicht testen, da ich kein Modell mit Auto Empty Station hier habe.

**Comment by jipijajay** [comment]
Oh wie cool :)
Also das Entleeren funktioniert schonmal und umschalten von automatisch Entleeren wird zumindest in der App auch übernommen. Denke das wird klappen.
Ich lasse es heute nacht mal laufen, wie ich mir das überlegt habe. Morgen weiss ich vielleicht mehr.

Vielen Dank für die Erwiterung.

**Comment by mrbungle64** [comment]
@jipijajay 
 
> Funktioniert hervorragend!

ok, super - das freut mich 👍🏻

**Comment by mrbungle64** [comment]
@aquachris2 

Hattest Du auch schon die Möglichkeit das mal zu testen?
