### ISSUE TITLE
Deebot Ozmo 950: Button für Repositionierung/Relocation

### ISSUE THREAD

**Issue by Opa0815** [mrbungle64/ioBroker.ecovacs-deebot#16]
Nachdem der 950 angehoben wurde führt er, wenn er eine neue Aufgabe bekommt, eine erneute Positionserkennung durch. Allerdings erst dann.
In der App gibt es hierfür einen Butten um das manuell anzustoßen (z.B. nach einem Etagenwechsel).
Dieser Button wäre auch im ioBroker hilfreich um eine Kartenerkennung durchzuführen.

Danke schon mal!

**Comment by boriswerner** [comment]
Hi @Opa0815 , ich hab viel mit der API getestet und das Relocating habe ich auch schon herausgefunden. Wir bauen im Moment einiges an der Library um, dann werde ich aber nach und nach mehr Funktionen einbauen.
Die technischen Infos der verfügbaren Funktionen hab ich schonmal hier grob dokumentiert (die Tabelle ist recht breit, daher am besten einmal kopieren und in Excel einfügen um alles zu sehen):
https://github.com/boriswerner/ecovacs-API-docs/wiki/commands-toAPI-Deebot-Ozmo-950

**Comment by Opa0815** [comment]
Super, danke

**Comment by boriswerner** [comment]
@Opa0815 die neueste Version hier auf GitHub unterstützt nun auch die Netzwerk Informationen, die auch in der App zu sehen sind (IP, MAC, WLAN Name und WLAN Signalstärke). Dazu noch einige Infos zur aktuellen Karte (aktuelle Karte: Name, Index und interne Map ID) und Position (inkl. Relocate) und die Steuerung der Saugkraft.
Du darfst sehr gerne testen wenn du magst :-)

**Comment by Opa0815** [comment]
Repositionierung funktioniert.
IP, MAC, WLAN Name und WLAN Signalstärke passen
Karte passt.
Saugkraft, Wasserdurchfluß, geht.
Perfect.
Gute Arbeit
