### ISSUE TITLE
Meldungen im Log: "ecovacs-deebot.0.history.timestampOfLastStateChange" has to be type "integer" but received type "number"

### ISSUE THREAD

**Issue by manoloxxl** [mrbungle64/ioBroker.ecovacs-deebot#166]
### Is there an existing issue for this?

- [X] I have searched the existing issues and no issue is describing my issue

### The problem

Hi,

das Log wirft beim Fahren des Bots leider massenhaft Meldungen zum timestampOfLastStateChange

ioBroker erwartet einen Int, gesendet wird jedoch eine number

Grüße

Manuel

### With which model does the problem occur?

Deebot OZMO 950

### From which source you have installed the adapter?

Stable (default)

### Version of the ioBroker adapter ("info.version")

1.2.1

### Version of the ecovacs-deebot.js library ("info.library.version")

0.6.1

### Version of the JS controller

3.3.18

### Version of Node.js

12.21.0

### Operating system

Other

### Ecovacs device class ("info.deviceClass")

null

### Communication protocol ("info.library.communicationProtocol")

MQTT

### Is the canvas module installed? ("info.library.canvasModuleIsInstalled")

yes (true)

**Comment by mrbungle64** [comment]
@manoloxxl 

Bitte den Datenpunkt löschen und die Instanz neu starten

**Comment by mrbungle64** [comment]
https://forum.iobroker.net/topic/46758/js-controller-3-3-jetzt-im-stable

_"Falls nach dem Update dennoch einzelne Adapter Info-Meldungen ins Log schreiben, bitte zuerst versuchen die gemeldeten Objekt-IDs via Admin zu löschen und den Adapter neu zu starten..."_

**Comment by mrbungle64** [comment]
Bitte wieder öffnen, falls das Problem doch noch bestehen sollte.
