### ISSUE TITLE
domain.enter is not a function

### ISSUE THREAD

**Issue by volkerverkamp** [mrbungle64/ioBroker.ecovacs-deebot#17]
Ich habe gerade erstmals den Adapter (v0.4.0) installiert, erhalte aber die folgende Fehlermeldung beim Starten der Instanz:

`
ecovacs-deebot.0 | 2020-02-20 16:41:36.987 | error | at EcovacsMQTT.emit (events.js:199:12)
-- | -- | -- | --
ecovacs-deebot.0 | 2020-02-20 16:41:36.987 | error | (7357) TypeError: domain.enter is not a function
ecovacs-deebot.0 | 2020-02-20 16:41:36.981 | error | (7357) uncaught exception: domain.enter is not a function
ecovacs-deebot.0 | 2020-02-20 16:41:33.872 | info | (7357) Successfully connected to Ecovacs server

`

**Comment by mrbungle64** [comment]
Hallo @volkerverkamp,

Das Problem tritt bei bestimmten älteren nodejs Versionen auf:

https://github.com/mrbungle64/ioBroker.ecovacs-deebot/issues/10

**Comment by volkerverkamp** [comment]
Danke - update von node.js hat geholfen ;-)
