### ISSUE TITLE
Deebot 710/711 - Version 0.4.2 - "charge" nur noch eingeschränkt nutzbar

### ISSUE THREAD

**Issue by capitaenz** [mrbungle64/ioBroker.ecovacs-deebot#18]
@mrbungle64 
Habe die neue Version installiert und jetzt funktioniert folgendes nicht mehr:
Zur Ladestation fährt der Robotoer nur noch, wenn man erst STOP und dann Charge drückt... dies ging vorher auch ohne STOP.
Das Verbrauchsmaterial wird weiterhin noch nicht angezeigt.

**Comment by mrbungle64** [comment]
> @mrbungle64
> Habe die neue Version installiert und jetzt funktioniert folgendes nicht mehr:
> Zur Ladestation fährt der Robotoer nur noch, wenn man erst STOP und dann Charge drückt... dies ging vorher auch ohne STOP.

@capitaenz 

Ist das reproduzierbar so?

> Das Verbrauchsmaterial wird weiterhin noch nicht angezeigt.

Ja beim Verbrauchsmaterial war noch ein weiterer Bug vorhanden - der wird wahrscheinlich mit der nächsten Version behoben sein.

**Comment by capitaenz** [comment]
@mrbungle64 
echt doof... konnte es jetzt nicht reproduzieren.
Hatte es gemerkt weil ich nach hause gekommen bin und der Sauger war noch nicht fertig und wenn die Anwesenheit gesetzt wird, soll er zum laden fahren und abbrechen.
Dies hat er nicht gemacht, sondern weitergereinigt. Ich habe dann schnell den ioBroker gestartet und wollte den Roboter über die Objekte zur Ladestation schicken, dies hat aber nur funktioniert, nachdem ich "stop" gedrückt habe.
Ich bleibt wohl wirklich nur beobachten und/oder einen Workaround mit stop.

**Comment by mrbungle64** [comment]
@capitaenz 

Ja bitte beobachte das mal. Bei mir funktioniert "charge" weiterhin ohne Probleme. Im Code sehe ich auch nichts, was auffällig ist.

Man muss auch immer beachten: der Adapter kommuniziert mit den Ecovacs Servern und nicht direkt mit dem Bot. Da gibt es mehr als nur den Adapter als potentielle Quelle für Fehlfunktionen.
In der Mobile App gibt es bei mir auch immer mal wieder nervige Aussetzer.

**Comment by capitaenz** [comment]
@mrbungle64 
Habe es nun noch ein paar Mal getestet und es funktioniert. War nur auffällig, dass dies direkt nach dem aktualisieren des Adapters aufgetreten ist.
Danke für deine Arbeit!

**Comment by mrbungle64** [comment]
@capitaenz 
Danke für das Feedback - das hört sich gut an :+1: 

Welche Version benutzt Du aktuell?

**Comment by capitaenz** [comment]
@mrbungle64 
Ich habe den Überblick verloren und nutze noch die 0.4.2

**Comment by mrbungle64** [comment]
@capitaenz 

ok, ich schließe dann diesen Issue mal, da es sich ja offensichtlich um ein temproräres Problem gehandelt hat :+1:

**Comment by mrbungle64** [comment]
@capitaenz 

ok, ich schließe dann diesen Issue mal, da es sich ja offensichtlich um ein temproräres Problem gehandelt hat :+1:
