### ISSUE TITLE
Abfrage ob Staubbox eingesetzt - Erweiterung möglich?

### ISSUE THREAD

**Issue by capitaenz** [mrbungle64/ioBroker.ecovacs-deebot#19]
Ist eine Abfrage der Staubbox möglich?
Ich habe das Problem, das der Roboter sporadisch meint, dass der Staubbehälter nicht eingesetzt wäre.
Dann muss man ein weiteres Mal die Reinigung starten.
Kann man den Status vielleicht über den Adapter (MQTT) abfragen?

**Comment by mrbungle64** [comment]
@capitaenz 
Es gibt Hoffnung :)
Bei meinem Deebot Ozmo 930 bekomme ich diese Information.

@boriswerner
Beim Ozmo 930 lässt sich der Wert über `DustCaseST` beziehen - ist in der Library nun auch grundsätzlich implementiert für XMPP-Geräte.
Liefert der Ozmo 950 das ebenfalls darüber?

**Comment by boriswerner** [comment]
Ist mir noch nicht begegnet, ich teste das aber Mal

**Comment by boriswerner** [comment]
Der 950 liefert nur eine Fehlermeldung (Code 110) wenn er etwas tun soll und die Box nicht eingesetzt ist.
Vielleicht kann man trotzdem den gleichen State nutzen und im Fehlerfall auf false setzen. Ist dann allerdings etwas unscharf... Man bräuchte sonst noch den State 'unknown' oder so.

**Comment by mrbungle64** [comment]
@capitaenz @capitaenz 

Beim Ozmo 930 werden sowohl der Wert "info.dustbox" als auch der Fehlerstatus dazu ad-hoc im Adapter angezeigt.

Ich vergebe für den Issue mal die Labels für die MQTT basierten Geräte.

**Comment by mrbungle64** [comment]
Ich schließe den Issue mal weil es ja inzwischen implementiert wurde und ja auch grundsätzlich funktioniert.

Dass der Wert beim Deebot 710 von Ecovacs invertiert wird ist ja wieder eine andere Geschichte ...
