### ISSUE TITLE
Ecovacs DEEBOT T9 AIVI

### ISSUE THREAD

**Issue by nicoh88** [mrbungle64/ioBroker.ecovacs-deebot#196]
Hi Sascha, ich mal wieder.

Könntest du den Support `T9 AIVI` hinzufügen? 
Beim Erstellen meiner Aliases für HomeKit sind mir folgende fehlende Datenpunkt aufgefallen:

```
info.network.wifiSignal
cleaninglog.totalSquareMeters
```

Dies ist nur ein Auszug, fehlen bestimmt noch mehr.

### Which model do you own?

Deebot T9 AIVI

### Which version of the ioBroker adapter are you currently using?

1.3.0-alpha.0

### 1.3.0-alpha.0
`[vacbot] product name: DEEBOT T9 AIVI`

`Device[1]: {"did":"4f87f842-1ee7-4ffc-9986-3f7acf37xxxx","name":"E09F14462C09HKE6xxxx","class":"659yh8","resource":"guUg","nick":null,"company":"eco-ng","bindTs":1636992058600,"service":{"jmq":"jmq-ngiot-eu.dc.ww.ecouser.net","mqs":"api-ngiot.dc-as.ww.ecouser.net"},"deviceName":"DEEBOT T9 AIVI","icon":"https://portal-ww.ecouser.net/api/pim/file/get/603f5147c811510008xxxxxxxx","ota":true,"UILogicId":"T9_AF_G","materialNo":"110-2011-0101","pid":"60361d6134bf63000xxxxxxx,"product_category":"DEEBOT","model":"T9_AIVI_INT","updateInfo":{"needUpdate":false,"changeLog":""},"status":1,"offmap":true,"deviceNumber":1}`

### 1.2.4
`[vacbot] product name: 659yh8`

`Device[1]: {"did":"4f87f842-1ee7-4ffc-9986-3f7acf37xxxx","name":"E09F14462C09HKE6xxxx","class":"659yh8","resource":"guUg","nick":null,"company":"eco-ng","bindTs":1636992058600,"service":{"jmq":"jmq-ngiot-eu.dc.ww.ecouser.net","mqs":"api-ngiot.dc-as.ww.ecouser.net"}}`

**Comment by mrbungle64** [comment]
@nicoh88 

Hi Nico,

habe den DEEBOT T9 AIVI mit der class `659yh8` (sowie ein paar weitere T8 und T9 Modelle) zur Config hinzugefügt.
Habe gerade die 1.3.0-alpha.1 released - die sollte den nun (er)kennen 😉

**Comment by mrbungle64** [comment]
@nicoh88 

Gibt es schon Feedback? 😉 

Habe gesehen, dass es heute eine nicht ganz eindeutige Bewertung des Adapters in Bezug auf den DEEBOT T9 AIVI und die Version 1.2.4 gab:

"Deebpt T9 AVI fehlt die richt API :)" (4/5 Sterne)

Würde ganz gerne wissen, wie der DEEBOT T9 AIVI nun mit der 1.3.0 funktioniert

**Comment by nicoh88** [comment]
Sorry für meine späte Antwort.

Ich möchte mich ganz klar von dieser Bewertung distanzieren. 😄 

--

```
[vacbot] product name: DEEBOT T9 AIVI
Using device Device[1]
Device[1]: {"did":"4f87f842-1ee7-4ffc-9986-3f7acf372655","name":"E09F14462C09HKE60173","class":"659yh8","resource":"guUg","nick":null,"company":"eco-ng","bindTs":1636992058600,"service":{"jmq":"jmq-ngiot-eu.dc.ww.ecouser.net","mqs":"api-ngiot.dc-as.ww.ecouser.net"},"deviceName":"DEEBOT T9 AIVI","icon":"https://portal-ww.ecouser.net/api/pim/file/get/603f5147c8115100083364bc","ota":true,"UILogicId":"T9_AF_G","materialNo":"110-2011-0101","pid":"60361d6134bf63000719d2e1","product_category":"DEEBOT","model":"T9_AIVI_INT","updateInfo":{"needUpdate":false,"changeLog":""},"status":1,"offmap":true,"deviceNumber":1}
Successfully connected to Ecovacs server
starting. Version 1.3.0-alpha.1 in /opt/iobroker/node_modules/iobroker.ecovacs-deebot, node: v12.22.7, js-controller: 3.3.18
```

Sieht gut aus.

```
info.network.wifiSignal
cleaninglog.totalSquareMeters
```

Sind jetzt auch vorhanden.
