### ISSUE TITLE
Allow disabling spot area name translations

### ISSUE THREAD

**Issue by agross** [mrbungle64/ioBroker.ecovacs-deebot#202]
### The feature request

I don't want my spot areas to be translated. The adapter should use the names I entered in the Ecovacs app.

### Which model do you own?

Deebot T9+

### Which version of the ioBroker adapter are you currently using?

1.2.0-alpha.3

### Additional information

Translations might work in most cases, but I don't like that the built-in translation service changes e.g. the case of my labels. E.g. `Living Room` -> `Living room`. I want to title use title-case on my custom UI without needing to patch things manually.

<strike>Also, I do not want my strings being sent to a third-party translation service.</strike>

**Comment by mrbungle64** [comment]
@agross 

> Which model do you own

"Deebot OZMO 950" => "Deebot T9 series", right 😉

**Comment by agross** [comment]
The model probably doesn't matter, right? I couldn't find the T9 in the model list. Perhaps I didn't look close enough.

**Comment by mrbungle64** [comment]
> The model probably doesn't matter, right? I couldn't find the T9 in the model list. Perhaps I didn't look close enough.

For the OZMO 950 the names are predefined. That's why the names in the library are also predefined so far 😉

**Comment by mrbungle64** [comment]
> That's why the names in the library are also predefined so far

I forgot that I already implemented handling custom names in the libary 😅 
Probably because I can't use it myself ...
I'll have to take a closer look at how I implemented that some months ago 😉

**Comment by mrbungle64** [comment]
These are the predefined area names for 950 type models:

```js
const SPOTAREA_SUBTYPE_NAMES = {
    'living room': {'en': 'Living room', 'de': 'Wohnzimmer'},
    'dining room': {'en': 'Dining room', 'de': 'Esszimmer'},
    'bedroom': {'en': 'Bedroom', 'de': 'Schlafzimmer'},
    'study': {'en': 'Study', 'de': 'Büro'},
    'kitchen': {'en': 'Kitchen', 'de': 'Küche'},
    'bathroom': {'en': 'Bathroom', 'de': 'Badezimmer'},
    'laundry': {'en': 'Laundry', 'de': 'Waschküche'},
    'lounge': {'en': 'Lounge', 'de': 'Lounge'},
    'storeroom': {'en': 'Storeroom', 'de': 'Lagerraum'},
    'kids room': {'en': 'Kids room', 'de': 'Kinderzimmer'},
    'sunroom': {'en': 'Sunroom', 'de': 'Wintergarten'},
    'corridor': {'en': 'Corridor', 'de': 'Flur'},
    'balcony': {'en': 'Balcony', 'de': 'Balkon'},
    'gym': {'en': 'Gym', 'de': 'Fitnessstudio'}
}
```

These should also be the only names that are translated. There's no other built-in translation service.

**Comment by agross** [comment]
Yes, I know that this is the list. One of the entries matches one of my
rooms (Living Room). I'd like the R to stay capitalized, though.

**Comment by mrbungle64** [comment]
@agross 

I added a new option to "Language for spot area labels"/"Sprache für die Beschriftung der Bereiche".
Please have a look if the behavior is according to your request.

**Comment by agross** [comment]
Excellent, this is just what I wanted!
