### ISSUE TITLE
Keine Funktion mehr mit der Version 1.2.4 und dem Deebot 710

### ISSUE THREAD

**Issue by capitaenz** [mrbungle64/ioBroker.ecovacs-deebot#204]
### Is there an existing issue for this?

- [X] I have searched the existing issues and no issue is describing my issue

### The problem

Moin zusammen,
ich habe bis vor ein paar Tagen noch die Version 0.5.8 ohne Probleme genutzt.
Ich habe dann ein Update des js-Controllers und ein Update von Node.js von 12.x auf 14.x vorgenommen.
Nun wird der Adapter zwar grün, aber der Roboter lässt sich nicht mehr starten...

`<html><body>

ecovacs-deebot.0 | 2021-12-05 14:07:29.665 | debug | [commandQueue] startNextItemFromQueue: GetCleanSpeed
-- | -- | -- | --
ecovacs-deebot.0 | 2021-12-05 14:07:29.408 | debug | [commandQueue] startNextItemFromQueue: GetSleepStatus
ecovacs-deebot.0 | 2021-12-05 14:07:29.151 | debug | [commandQueue] startNextItemFromQueue: GetLifeSpan, filter
ecovacs-deebot.0 | 2021-12-05 14:07:28.895 | debug | [commandQueue] startNextItemFromQueue: GetLifeSpan, side_brush
ecovacs-deebot.0 | 2021-12-05 14:07:28.640 | debug | [commandQueue] startNextItemFromQueue: GetLifeSpan, main_brush
ecovacs-deebot.0 | 2021-12-05 14:07:28.384 | debug | [commandQueue] startNextItemFromQueue: GetBatteryState
ecovacs-deebot.0 | 2021-12-05 14:07:28.129 | debug | [commandQueue] startNextItemFromQueue: GetChargeState
ecovacs-deebot.0 | 2021-12-05 14:07:27.872 | debug | [commandQueue] startNextItemFromQueue: GetCleanState
ecovacs-deebot.0 | 2021-12-05 14:07:22.018 | info | State  value to set for "ecovacs-deebot.0.history.timestampOfLastStateChange"  has to be type "integer" but received type "number"
ecovacs-deebot.0 | 2021-12-05 14:07:22.017 | info | State  value to set for "ecovacs-deebot.0.history.timestampOfLastStateChange"  has to be type "integer" but received type "number"
ecovacs-deebot.0 | 2021-12-05 14:07:22.014 | debug | state change info.connectionUptime => 0
ecovacs-deebot.0 | 2021-12-05 14:07:22.009 | debug | state change info.connection => true
ecovacs-deebot.0 | 2021-12-05 14:07:21.945 | info | [vacbot] product name: DEEBOT 710
ecovacs-deebot.0 | 2021-12-05 14:07:21.941 | info | DEEBOT_710 instance successfully connected
ecovacs-deebot.0 | 2021-12-05 14:07:21.633 | info | Using device Device[0]
ecovacs-deebot.0 | 2021-12-05 14:07:21.633 | info | Device[0]:   {"did":"73405b80-1bb8-4795-8fef-56474167db2d","name":"E0001209318604870530","class":"uv242z","resource":"uYyu","nick":"DEEBOT_710","company":"eco-ng","bindTs":1568983549228,"service":{"jmq":"jmq-ngiot-eu.dc.ww.ecouser.net","mqs":"api-ngiot.dc-as.ww.ecouser.net"}}
ecovacs-deebot.0 | 2021-12-05 14:07:21.632 | debug | Devices:[{"did":"73405b80-1bb8-4795-8fef-56474167db2d","name":"E0001209318604870530","class":"uv242z","resource":"uYyu","nick":"DEEBOT_710","company":"eco-ng","bindTs":1568983549228,"service":{"jmq":"jmq-ngiot-eu.dc.ww.ecouser.net","mqs":"api-ngiot.dc-as.ww.ecouser.net"}}]
ecovacs-deebot.0 | 2021-12-05 14:07:21.631 | info | Number of devices: 1
ecovacs-deebot.0 | 2021-12-05 14:07:21.630 | info | Successfully connected to Ecovacs server
ecovacs-deebot.0 | 2021-12-05 14:07:19.040 | debug | Schedule restart: * 1 * * *
ecovacs-deebot.0 | 2021-12-05 14:07:18.955 | info | starting. Version 1.2.4 in /opt/iobroker/node_modules/iobroker.ecovacs-deebot, node: v14.18.1, js-controller: 3.3.20
ecovacs-deebot.0 | 2021-12-05 14:07:14.339 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
ecovacs-deebot.0 | 2021-12-05 14:07:14.332 | info | terminating
ecovacs-deebot.0 | 2021-12-05 14:07:14.331 | info | cleaned everything up...
ecovacs-deebot.0 | 2021-12-05 14:07:14.327 | info | Got terminate signal TERMINATE_YOURSELF

</body>
</html>`

Eine Idee?
VG
Leif

### With which model does the problem occur?

Deebot 710/711/711s

### From which source you have installed the adapter?

Stable (default)

### Version of the ioBroker adapter ("info.version")

1.2.4

### Version of the ecovacs-deebot.js library ("info.library.version")

0.6.8

### Version of the JS controller

3.3.20

### Version of Node.js

14.18.1

### Operating system

Linux

### Communication protocol ("info.library.communicationProtocol")

MQTT

**Comment by mrbungle64** [comment]
Hi @capitaenz 

Ist das Log vollständig? Ich sehe keinen Eintrag wo ein Befehl zum Reinigen auftaucht ...

**Comment by capitaenz** [comment]
Sorry, hier ein Reinigungs**versuch**:

`<html><body>


ecovacs-deebot.0 | 2021-12-05 14:45:24.256 | debug | state change control.clean => false
-- | -- | -- | --
ecovacs-deebot.0 | 2021-12-05 14:45:24.157 | info | Run: clean
ecovacs-deebot.0 | 2021-12-05 14:45:24.157 | debug | state change control.clean => true
ecovacs-deebot.0 | 2021-12-05 14:44:46.660 | debug | [intervalQueue] startNextItemFromQueue: GetCleanSpeed
ecovacs-deebot.0 | 2021-12-05 14:44:46.592 | debug | state change info.connectionUptime => 35
ecovacs-deebot.0 | 2021-12-05 14:44:46.404 | debug | [intervalQueue] startNextItemFromQueue: GetSleepStatus
ecovacs-deebot.0 | 2021-12-05 14:43:46.660 | debug | [intervalQueue] startNextItemFromQueue: GetCleanSpeed
ecovacs-deebot.0 | 2021-12-05 14:43:46.602 | debug | state change info.connectionUptime => 34
ecovacs-deebot.0 | 2021-12-05 14:43:46.405 | debug | [intervalQueue] startNextItemFromQueue: GetSleepStatus
ecovacs-deebot.0 | 2021-12-05 14:42:47.359 | debug | state change info.connectionUptime => 33
ecovacs-deebot.0 | 2021-12-05 14:42:46.661 | debug | [intervalQueue] startNextItemFromQueue: GetCleanSpeed
ecovacs-deebot.0 | 2021-12-05 14:42:46.405 | debug | [intervalQueue] startNextItemFromQueue: GetSleepStatus
ecovacs-deebot.0 | 2021-12-05 14:41:46.657 | debug | [intervalQueue] startNextItemFromQueue: GetCleanSpeed
ecovacs-deebot.0 | 2021-12-05 14:41:46.570 | debug | state change info.connectionUptime => 32
ecovacs-deebot.0 | 2021-12-05 14:41:46.400 | debug | [intervalQueue] startNextItemFromQueue: GetSleepStatus
ecovacs-deebot.0 | 2021-12-05 14:40:46.659 | debug | [intervalQueue] startNextItemFromQueue: GetCleanSpeed
ecovacs-deebot.0 | 2021-12-05 14:40:46.600 | debug | state change info.connectionUptime => 31
ecovacs-deebot.0 | 2021-12-05 14:40:46.404 | debug | [intervalQueue] startNextItemFromQueue: GetSleepStatus


</body>
</html>`

**Comment by mrbungle64** [comment]
@capitaenz 

Ansonsten ist es ja leider so:
Der Deebot 710 funktioniert ja leider nur bis zur Version 0.5.8.
Das habe ich ja unter "Known Issues" ja auch vermerkt:
> Some cleaning functions may not work with Deebot 710/711/711s. Please use version 0.5.8 for now.

Ich weiß leider immer noch nicht welche Änderung (wahrscheinlich in der Library) dazu geführt hat, dass es beim Deebot 710 Probleme mit den Reinigungsfunktionen gibt.

Ich kann Dir anbieten, dass Du mir Dein Gerät mal für 1 Stunde oder so zur Verfügung stellst und ich schaue ob ich das zum Laufen bekomme. Würde bedeuten, dass Du Dein Passwort temporär mal änderst und es mir per Mail schickst.
In der Zeit würde das Gerät dann halt im Optimalfall auch mal loslegen 😉

**Comment by capitaenz** [comment]
Wann passt es dir und unter welcher Mailadresse, Telegram oder Whatsapp kann ich dich erreichen?

**Comment by mrbungle64** [comment]
> Wann passt es dir und unter welcher Mailadresse, Telegram oder Whatsapp kann ich dich erreichen?

Ich hätte jetzt mind. 1 Stunde Luft dafür.

Email-Adresse ist mrb1232@posteo.de
Falls die Email-Adresse für den Ecovacs Account von der Absender-Adresse Deiner Mail abweicht bräuchte ich die dann auch noch.

**Comment by mrbungle64** [comment]
@capitaenz 

Der Bot sollte eben gereinigt haben und nun pausiert sein.

**Comment by capitaenz** [comment]
Ja, er lief grad los und macht jetzt Pause!

**Comment by mrbungle64** [comment]
@capitaenz 

> Ja, er lief grad los und macht jetzt Pause!

ok, dann habe ich herausgefunden, was dem Deebot 710 gefehlt hat 😉 
Ich muss jetzt mal schauen wir ich das am besten einbaue, so dass es für alle Modelle funktioniert.
Ich melde mich dann wenn ich eine Version vom ioBroker Adapter fertig habe die dann die geänderte Version der Library verwendet. Ich weiß nicht ob ich es heute noch schaffe, aber es sollte spätestens in den nächsten Tagen soweit sein.

Kann der Deebot 710 Edge und Spot Reinigung? Dann würde ich das gerade noch testen

**Comment by capitaenz** [comment]
Super!  =)

> Btw.: Kann der Deebot 710 Edge und Spot Reinigung? Dann würde ich das gerade noch testen
Ja kann er

**Comment by mrbungle64** [comment]
> Super! =)
> 
> > Btw.: Kann der Deebot 710 Edge und Spot Reinigung? Dann würde ich das gerade noch testen
> 
> Ja kann er

ok, er sollte eben für 1 Minute Spot Reinigung gemacht haben und nun eine Edge Reinigung ausführen.

Kannst du das bestätigen?

**Comment by capitaenz** [comment]
Also Edge kann ich 100% bestätigen, Spot kann ich nur vermuten, da er oben im Schlafzimmer saugt, aber er lief grad (Spot)!

**Comment by mrbungle64** [comment]
> Also Edge kann ich 100% bestätigen, Spot kann ich nur vermuten, da er oben im Schlafzimmer saugt, aber er lief grad (Spot)!

ok, super. Dann kannst du nun das Passwort wieder ändern und ich melde mich dann 😉

**Comment by capitaenz** [comment]
DANKE!  =)
Einen schönen 2. Advend noch!

**Comment by mrbungle64** [comment]
@capitaenz 

Probier mal bitte die aktuelle Version von GitHub (Version 1.3.1-alpha.0)

**Comment by capitaenz** [comment]
Juhu! Scheint zu funktionieren, ich teste und werde berichten!
Danke und einen schönen Abend!

Kannst du mit ein zwei sätzen erklärten was es war oder ist es zu komplziert zu beschreiben?

VG
Leif

**Comment by mrbungle64** [comment]
> Juhu! Scheint zu funktionieren, ich teste und werde berichten! Danke und einen schönen Abend!

Sehr gut 👍🏻  Dir auch einen schönen Abend!

> 
> Kannst du mit ein zwei sätzen erklärten was es war oder ist es zu komplziert zu beschreiben?

Der Deebot 710 möchte bei den Clean Befehlen noch die Saugstärke mit übergeben bekommen.
Das ist normalerweise ohne Effekt (bzw. nutzlos bei den anderen Modellen) - deswegen hatte ich das im Frühjahr 2020 aus der Library entfernt.

**Comment by mrbungle64** [comment]
@capitaenz 

Ich habe inzwischen auch die Version 1.3.1 (über das Beta/Latest Repo) veröffentlicht.
Du solltest jetzt dann nach der Installation der 1.3.1 keine GitHub Version mehr installieren (müssen).

Wenn alles soweit passt schließe bitte diesen Issue.

**Comment by capitaenz** [comment]
Mit der Version 1.3.1-alpha.0 kann ich soweit keine Probleme feststellen, der 710 läuft damit wieder!
Danke! =)
