### ISSUE TITLE
seit Version 1.3.1 werden die Daten von meinem Deebot OZMO 900 nicht mehr in den iobroker übertragen

### ISSUE THREAD

**Issue by mandre1904** [mrbungle64/ioBroker.ecovacs-deebot#218]
### Is there an existing issue for this?

- [X] I have searched the existing issues and no issue is describing my issue

### The problem

Hallo,

ich habe die Tage ein umfangreiches Update gefahren ua incl Update des Adapters. Bisher war es so, dass wenn der Datenpunkt Cleaning multiple spot areas geändert wurde ich eine Info per Telegram erhalten habe, welchen Raum der Bot gerade reinigt. Dies passiert nicht mehr.

Ich teste gerade:
Ich wähle in der App aus, welcher Raum gereinigt werden soll und starte --> der Staus wird nicht übertragen
Auch wird der Status nicht übertragen, wenn der Bot wieder zur Station fährt und dann lädt. Das hat bisher wunderbar funktioniert.

Habe im Adapter geschaut: natürlich ist er mit dem Konto verbunden.

Hat noch jemand das Problem? Habe gerade keine Idee.

### With which model does the problem occur?

Deebot OZMO 900

### From which source you have installed the adapter?

Stable (default)

### Version of the ioBroker adapter ("info.version")

1.3.1

### Version of the ecovacs-deebot.js library ("info.library.version")

null

### Version of the JS controller

null

### Version of Node.js

v12.22.8

### Operating system

Linux

### Anything in the logs that might be useful?

```txt
Adapter verbunden, aber keine weiteren Einträge vorhanden wenn der Bot seine Aktivität ändern wie aufladen, einen Raum reinigen etc.
```

**Comment by mrbungle64** [comment]
Hallo @mandre1904 

ich habe selbst u.a. einen Deebot 901 - da funktioniert eigentlich alles wie gehabt.
Nur zur Sicherheit: ist es ein Deebot 900 oder ein Deebot OZMO 900?

Kannst Du bitte die Datenpunkte benennen (wie z.B. "control.spotArea"), welche bei Dir nicht mehr übertragen werden?
Oder bekommst Du nur keine Meldung mehr per Telegram?

**Comment by mandre1904** [comment]
Hallo @mrbungle64 

es ist ein Ozmo 900, sorry.
Ich habe eben die Version 1.2.4 wieder installiert. Damit wird sofort alles übertragen. Dann wieder zurück auf 1.3.1 und siehe da: es werden wieder fast alle Daten übertragen.

Aber wenn ich den Bot mit der App in einen bestimmten Raum schicke ändert sich weder der Eintrag ecovacs-deebot.0.control.spotArea noch ecovacs-deebot.0.control.spotArea_cleanings. Die Räume sind in der App ja unterschiedlichen Nummern zugeordnet. Ich habe den Bot in unterschiedliche Räume geschickt und der Eintrag ecovacs-deebot.0.control.spotArea bleibt leer, ecovacs-deebot.0.control.spotArea_cleanings bleibt auf 1, egal welchen Raum ich wähle.

Charging wird jedoch nun wieder korrekt übertragen. Soll ich den Adapter noch einmal neu installieren?

**Comment by mrbungle64** [comment]
@mandre1904 

Also wenn das nur "control.spotArea" und "control.spotArea_cleanings" betrifft muss ich sagen, dass mir das gar nicht bekannt ist, dass das übernommen wird, wenn man von der Ecovacs Mobile App aus Bereiche startet ...
Bist du dir sicher, dass das bei Dir mit der 1.2.4 funktioniert hat?

**Comment by mandre1904** [comment]
@mrbungle64 
Ich meine es jedenfalls so in Erinnerung zu haben. Wenn du als Entwickler allerdings sagst, dass das noch nie so war, dann werde ich nicht dagegen wetten. Dann kannst du den Thread schließen. Sorry für die Umstände und vielen Dank für deine Arbeit.

Frohes Neues
