### ISSUE TITLE
Please also add your adapter to the stable repository once ready

### ISSUE THREAD

**Issue by ioBrokerChecker** [mrbungle64/ioBroker.ecovacs-deebot#22]
Your adapter is already in ioBroker latest repository available to be used by testwilling users. In order to make your adapter also available for the wide user base which uses the stable repository you should also add your adapter to the stable repository. Please see instructions at https://github.com/ioBroker/ioBroker.repositories#requirements-for-adapter-to-get-added-to-the-stable-repository

Thank you for your support.

**Comment by Sacred-Shadow** [comment]
Wär ich auch mal für ;)

**Comment by mrbungle64** [comment]
> Wär ich auch mal für ;)

Hi @Sacred-Shadow 

setzt Du den Adapter bereits ein oder wartest Du auf die Stable?

Falls Du den Adapter bereits einsetzt:
* welches Modell hast Du?
* hast Du eine GitHub Version im Einsatz oder die aus der Latest Repo?

**Comment by Sacred-Shadow** [comment]
Nein, ich nutze den Adapter noch nicht. 
Warte auf die Stable ;)

**Comment by mrbungle64** [comment]
> Nein, ich nutze den Adapter noch nicht.
> Warte auf die Stable ;)

ok :+1: 

Würde mich trotzdem interessieren welches Modell Du benutzt.

**Comment by Sacred-Shadow** [comment]
Bei mir werkelt ein Ecovacs Deebot Ozmo 900.
Zumindest, wenn er dann aus der Wasserpumpen Reperatur zurück ist. :D

**Comment by mrbungle64** [comment]
Für den Deebot Ozmo 900 bräuchten wir mal wieder jemanden der uns Feedback gibt :D
Kannst es Dir ja mal überlegen ;)

**Comment by Grizzelbee** [comment]
Falls Input zum Deebot Ozmo 900 benötigt wird, kann ich auch gerne helfen. ;)

**Comment by mrbungle64** [comment]
> Falls Input zum Deebot Ozmo 900 benötigt wird, kann ich auch gerne helfen. ;)

Hi @Grizzelbee 
sehr gerne :+1: 
Folgendes würde mich im speziellen interessieren:

Der Verbindungsaufbau nach dem Start/Neustart des Adapters sollte inzwischen wesentlich schneller gehen und das "reconnecting ..." sollte nicht mehr vorkommen.
- Ist das bei Dir auch so?
- Wird die Verbindung anschließend stabil aufgebaut und bleibt diese stabil bei Dir?

In den AdapterEinstellungen gibt es inzwischen den Tab "Features".
Hast Du dort schon mal die unteren Punkte auf "aktivieren" gestellt?
- Reinigungsprotokoll
- Staubbox
- Manuelles steuern

Bei der Staubbox sollte der state auf `false` gehen, wenn die Staubbox herausgenommen wird - und umgekehrt. Falls das nicht funktionieren sollte, würde das darauf hindeuten, dass der Ozmo 900 die gleiche Basis hat wie der 900/901 - nur halt mit zusätzlich einer Wischfunktion.
Beim Deebot 901 wird (mit der aktuellen Firmware) nämlich definitv kein Event gesendet - nicht mal ein Error wird gemeldet ...

Bei den Move Befehlen ist es bei allen bisher getesteten Modellen so, dass man nur 1-2x den gleichen Befehl hintereinander ausführen kann. Dann muss man zwingend einen anderen ausführen, bevor man den nächsten davon ausführen kann.
Also z.B. forward => stop => forward
Das ist wohl eine absichtliche Beschränkung von Ecovacs ...
Ist das bei dem Ozmo 900 auch so?
Bzw. funktionieren die Move Befehle überhaupt?
Die Buttons sollten nach dem  Freischalten unter "control.move" zu finden sein.

Es wäre natürlich immer interessant, ob die bereits freigeschalteten Funktionen auch alle soweit funktionieren.

Vielen Dank schon mal :+1:

**Comment by Grizzelbee** [comment]
Sooooo ... Ein paar erste Infos gibt es:
* Der **Connect** klappt seit einigen Versionen **wunderbar, schnell und auch stabil*. Bei den ersten Versionen brauchte der Adapter beim Neustart ca. 20 Connectversuche - das ist definitiv weg.

* Neue Funktionen: Habe ich mal aktiviert und flink gestestet - Was ich schon sagen kann:
* Staubbox bleibt immer auf `false` - auch wenn ich die Box entferne.
* Es gibt jetzt ein lustiges Total-Cleanings-Log mit Stunden, Quadratmetern, etc. Witzig!

* Diesen seltsamen Akku verlauf konnte ich bei mir noch nicht feststellen - habe aber auch noch nicht so penibel darauf geachtet.

Ich habe gerade mal `backwart` ohne eingesetzte Staubbox angeklickt - Der Bot beschwert sich mittels Spache, dass die Box nicht eingestezt ist, im Adapter findet sich aber nichts entsprehendes wieder. `Dustbox` bleibt auf `false` und kein `Errorcode`. Mit eingesetzter Staubbox haben die Tasten unter `Move` aber keine weitere Funktion. Der Bot rührt sich nicht unnd stellt sich auch sonst tot.

Die anderen (alten) Funktionen finktionieren aber (soweit ich sie getestet habe) einwandfrei. Incl. der Start, Pause, Finde-Spachmeldung, ... Tasten.

**Comment by mrbungle64** [comment]
> Sooooo ... Ein paar erste Infos gibt es:
> 
> * Der **Connect** klappt seit einigen Versionen *_wunderbar, schnell und auch stabil_. Bei den ersten Versionen brauchte der Adapter beim Neustart ca. 20 Connectversuche - das ist definitiv weg.

Das freut mich :+1: 

> * Neue Funktionen: Habe ich mal aktiviert und flink gestestet - Was ich schon sagen kann:
> * Staubbox bleibt immer auf `false` - auch wenn ich die Box entferne.

Das verhält sich dann wohl wie beim Deebot 900/901 ...
Wenn die API nix liefert kann man da wohl nicht viel machen ...

> * Es gibt jetzt ein lustiges Total-Cleanings-Log mit Stunden, Quadratmetern, etc. Witzig!
> * Diesen seltsamen Akku verlauf konnte ich bei mir noch nicht feststellen - habe aber auch noch nicht so penibel darauf geachtet.
> 
> Ich habe gerade mal `backwart` ohne eingesetzte Staubbox angeklickt - Der Bot beschwert sich mittels Spache, dass die Box nicht eingestezt ist, im Adapter findet sich aber nichts entsprehendes wieder. `Dustbox` bleibt auf `false` und kein `Errorcode`. Mit eingesetzter Staubbox haben die Tasten unter `Move` aber keine weitere Funktion. Der Bot rührt sich nicht unnd stellt sich auch sonst tot.
> 

Wieso hast Du es direkt ohne eingesetzte Staubbox getestet?
Kannst Du das noch mal nach einem Adapter-Neustart "normal" testen?
Evtl. hat der sich daran "verschluckt". Das machen die Deebots manchmal wenn die einen Befehl bekommen haben den die nicht richtig verarbeiten können ;)

> Die anderen (alten) Funktionen finktionieren aber (soweit ich sie getestet habe) einwandfrei. Incl. der Start, Pause, Finde-Spachmeldung, ... Tasten.

Das ist erfreulich :+1: 

> 
> Btw: sollen wir das vielleicht in einen Deebot (Ozmo) 900 Thread verlagern?

Eher nicht - der Issue bleibt dann ewig offen ;)
Du kannst natürlich jederzeit für Fehler, Fragen oder Feature-Requests gerne Issues erstellen.
Oder meinst Du einen Thread im ioBroker Forum?

**Comment by Grizzelbee** [comment]
> Wieso hast Du es direkt ohne eingesetzte Staubbox getestet?
Kannst Du das noch mal nach einem Adapter-Neustart "normal" testen?
Evtl. hat der sich daran "verschluckt". Das machen die Deebots manchmal wenn die einen Befehl bekommen haben den die nicht richtig verarbeiten können ;)

Das war eigentlich Zufall, weil noch draußen lag. Habe das aber noch einmal nachgetestet.
* Die Befehle unter `move` funktionieren. Aber auch incl. dieses komischen Ich-wiederhole-die-Moves-nicht-beliebig-oft-Bugs.
Also im Grunde alles Gut an dieser Stelle bzw. so wie bei allen anderen auch.

**Comment by mrbungle64** [comment]
Test Adapter ecovacs-deebot v0.6.x Latest:
https://forum.iobroker.net/topic/33177/test-adapter-ecovacs-deebot-v0-6-x-latest

**Comment by mrbungle64** [comment]
> Test Adapter ecovacs-deebot v0.6.x Latest:
> https://forum.iobroker.net/topic/33177/test-adapter-ecovacs-deebot-v0-6-x-latest

Hallo @Grizzelbee 

falls Du schon die Version 0.6.x im Einsatz hast wäre es cool, wenn Du im Forum kurz Feedback geben könntest :)

**Comment by Apollon77** [comment]
Ok, hinzugefügt, Bitte aber über Unterstützung des Compact mode nachdenken :-)

**Comment by mrbungle64** [comment]
> Ok, hinzugefügt, Bitte aber über Unterstützung des Compact mode nachdenken :-)

Vielen Dank! Den Compact mode support hatte ich kurzfristig noch mal entfernt, weil der (zumindest) bei mehreren Instanzen noch Probleme gemacht hat.
Wir haben es aber mit relativ hoher Priorität (8/10) auf unserer Liste ;)
https://github.com/mrbungle64/ioBroker.ecovacs-deebot/wiki/Feature-requests

**Comment by mrbungle64** [comment]
> Ok, hinzugefügt, Bitte aber über Unterstützung des Compact mode nachdenken :-)

@Apollon77
Compact mode support wird mit der Version 1.0.1 ab morgen über die Latest Repo verfügbar sein :)
