### ISSUE TITLE
Deebot N8 Pro+, keine Karten-spezifische Informationen

### ISSUE THREAD

**Issue by smarteshome2020** [mrbungle64/ioBroker.ecovacs-deebot#223]
### The question

Hi, ich würde gerne den Deebot im ioBroker einbinden was soweit auch gelang. Leider fehlen aber alle Karten-spezifische Informationen wie z.B. deebotPositionCurrentSpotAreaID. Siehst du eine Möglichkeit die zur Verfügung zu stellen oder ist dies Modelbedingt nicht möglich?

### Which model do you own?

Deebot N8 series

### Which version of the ioBroker adapter are you currently using?

1.3.1

**Comment by mrbungle64** [comment]
@smarteshome2020 

Welche Werte haben folgende Datenpunkte:

- "info.deviceClass"
- "info.library.canvasModuleIsInstalled"

**Comment by smarteshome2020** [comment]
@mrbungle64 

    "info.deviceClass" = "ifbw08"
    "info.library.canvasModuleIsInstalled" = "true"

hoffe das hilft dir weiter.

**Comment by mrbungle64** [comment]
@smarteshome2020 

Probier mal bitte die 1.3.2-alpha.0 von GitHub. Ich habe das Model der Konfig hinzugefügt.

**Comment by smarteshome2020** [comment]
@mrbungle64 
Super! Die DP sind jetzt vorhanden und ich teste das morgen mal genauer. Aber noch eine Frage. Bei "ecovacs-deebot.0.map.deebotPositionCurrentSpotAreaID" steht gerade "unknown". Muss ich in der Instand unter "weiteres" die Einstellung "Wert "unknown" im Datenpunkt ".... aktivieren?

**Comment by mrbungle64** [comment]
@smarteshome2020 

> Super! Die DP sind jetzt vorhanden und ich teste das morgen mal genauer.

Alles klar 👍🏻 

> Aber noch eine Frage. Bei "ecovacs-deebot.0.map.deebotPositionCurrentSpotAreaID" steht gerade "unknown". Muss ich in der Instand unter "weiteres" die Einstellung "Wert "unknown" im Datenpunkt ".... aktivieren?

Das kannst Du aktivieren - kann u.U. auch helfen. Falls der Roboter aber gerade nicht reinigt wird das eher der Grund sein.

**Comment by smarteshome2020** [comment]
@mrbungle64 

ich hatte noch nciht viel Zeit zum testen, aber ich kann die spotAreas nicht mhr starten.
Bekomme jetzt folgende Meldung:

failed start cleaning spot area: 0 - position invalid

Zusätzlich sehe ich aber noch folgendes:

`Error message received: Error: The module '/opt/iobroker/node_modules/canvas/build/Release/canvas.node' was compiled against a different Node.js version using NODE_MODULE_VERSION 72. This version of Node.js requires NODE_MODULE_VERSION 83. Please try re-compiling or re-installing the module (for instance, using `npm rebuild` or `npm install`).`

bzw. 

failed start cleaning spot area: 0 - position invalid

**Comment by mrbungle64** [comment]
@smarteshome2020 

> 'failed start cleaning spot area: 0 - position invalid'

Hast den Bot per Hand an eine andere Position gesetzt?
Versuch mal "control.relocate"

> Zusätzlich sehe ich aber noch folgendes:

Du hast wohl ein Node.js Update gemacht
Lösung steht in den FAQ:
https://github.com/mrbungle64/ioBroker.ecovacs-deebot/wiki/FAQ#nodejs-upgrade

**Comment by mrbungle64** [comment]
@smarteshome2020 

> Folgende Meldung bekomme ich wenn ich "cleansporAres" = true setzte

Welchen Datenpunkt meinst Du?

**Comment by smarteshome2020** [comment]
@mrbungle64 

Danke, mir fehlen die Worte!

> > 'failed start cleaning spot area: 0 - position invalid'

Gefunden. war mein Fehler. Da gibt es jetzt neue/andere DP unter Controll und ich habe die falschen verwendet.

> Du hast wohl ein Node.js Update gemacht Lösung steht in den FAQ: https://github.com/mrbungle64/ioBroker.ecovacs-deebot/wiki/FAQ#nodejs-upgrade

Schaue ich mir an.
