### ISSUE TITLE
Akkuanzeige bei Deebot 900

### ISSUE THREAD

**Issue by AudidriverA4** [mrbungle64/ioBroker.ecovacs-deebot#23]
Hier nochmal kurz der Text aus der anderen Issues:

@mrbungle64
Wie oben beschrieben ist DEEBOT auf ladeschale gefahren hat geladen dann ist der Akku stand im Broker von 98% auf 90% gesunken nach kurzer Zeit.
Hab leider vergessen am Morgen nochmal zu kucken was dann im Broker stand.
Jetzt Aktuell steht Akku auf 34% im Broker obwohl er seit gestern Mittag auf der Station steht.
In der App sieht Akku aber voll aus.
@AudidriverA4

Hmm, das klingt sehr komisch für mich, da der Adapter nicht selbständig den Wert von "battery" verringert. Das bedeutet für mich, dass der Ecovacs Server zwischendurch mal 34% gemeldet haben müsste - auch wenn das inzwischen wieder bei quasi 100% angelagt ist.

Meine Vermutung ist im Moment, dass der Adapter immer mal wieder stoppt bzw. die Verbindung verliert. Woher das kommt kann ich leider nicht sagen.

Hast du die Möglichkeit den Verlauf von "battery" über den History Adapter (o.ä.) zu speichern - damit man mal die Sprünge im Verlauf genauer betrachten könnte?

Btw.: Es wäre gut, wenn Du einen neuen Issue dafür erstellten könntest, da es hier ja eigenlich um den OZMO 900 geht ... Danke :)
Hab mal History gestartet muss ich da was einstellen ausser aktivieren und muss mal kucken wo ich Daten Auslesen kann.

Heute hat der Deebot mal seine Ladeschale verschoben und konnte nicht Laden er war ziemlich leer. Hab alles wieder richtig aufgestellt und Deebot auf Ladeschale das war so ca 15.30 Uhr.
Eben gerade hab ich mal im Broker gekuckt das steht 4% laut App Akku voll.
Kann es sein das er irgendwie in letzten stand vorm Laden im Broker schreibt ?
Jetzt hab ich mal Deebot gestartet und nach ca nach einer Minute im Betrieb stand dann 99% im Broker.
Jetzt ist er wieder auf Ladeschale und zeigt 98% und Aufladen.

**Comment by mrbungle64** [comment]
@AudidriverA4 

> Hab mal History gestartet muss ich da was einstellen ausser aktivieren und muss mal kucken wo ich Daten Auslesen kann.

Ja Du musst das unter "Objekte" ganz rechts bei "battery" über das Schraubenschlüssel-Symbol aktivieren:
"Einstellungen für history.0" => "Aktiviert" setzen
Am besten auch "log changes only" setzen
Dann kannst Du dort später über "Grafik" den Verlauf sehen.

> 
> Heute hat der Deebot mal seine Ladeschale verschoben und konnte nicht Laden er war ziemlich leer. Hab alles wieder richtig aufgestellt und Deebot auf Ladeschale das war so ca 15.30 Uhr.
> Eben gerade hab ich mal im Broker gekuckt das steht 4% laut App Akku voll.
> Kann es sein das er irgendwie in letzten stand vorm Laden im Broker schreibt ?
> Jetzt hab ich mal Deebot gestartet und nach ca nach einer Minute im Betrieb stand dann 99% im Broker.
> Jetzt ist er wieder auf Ladeschale und zeigt 98% und Aufladen.

Schmeißt der Adapter im Log irgendwelche Fehler?
Irgendwas muss ja dazu führen, dass der aufhört die Events vom Ecovacs Server zu verabeiten (so dass der Wert auf z.B. den 4% stehen bleibt).

**Comment by AudidriverA4** [comment]
Lese heut nochmal die LOG aus wenn er gelaufen ist und History läuft mal.

**Comment by AudidriverA4** [comment]
Hab gerade mal gekuckt hat doch was nicht geklappt, aber nochmal probiert und folgendes festgestellt.

**Im LOG:**
2020-02-26 16:57:17.473  - [34mdebug[39m: ecovacs-deebot.0 (18633) state change: [object Object]
2020-02-26 16:57:17.476  - [34mdebug[39m: ecovacs-deebot.0 (18633) state change: [object Object]
2020-02-26 16:57:17.478  - [34mdebug[39m: ecovacs-deebot.0 (18633) state change: [object Object]
2020-02-26 16:57:17.481  - [34mdebug[39m: ecovacs-deebot.0 (18633) state change: [object Object]
2020-02-26 16:57:17.501  - [34mdebug[39m: ecovacs-deebot.0 (18633) state change: [object Object]
2020-02-26 16:57:17.508  - [34mdebug[39m: ecovacs-deebot.0 (18633) state change: [object Object]
2020-02-26 16:57:17.516  - [34mdebug[39m: ecovacs-deebot.0 (18633) state change: [object Object]
2020-02-26 16:57:17.665  - [32minfo[39m: ecovacs-deebot.0 (18633) Unhandled chargestatus: null
2020-02-26 16:57:17.671  - [34mdebug[39m: ecovacs-deebot.0 (18633) state change: [object Object]
2020-02-26 16:57:17.683  - [34mdebug[39m: ecovacs-deebot.0 (18633) state change: [object Object]
2020-02-26 16:57:40.000  - [34mdebug[39m: ecovacs-deebot.0 (18633) system.adapter.admin.0: logging false
2020-02-26 16:58:05.284  - [34mdebug[39m: ecovacs-deebot.0 (18633) system.adapter.admin.0: logging true
2020-02-26 16:58:14.717  - [34mdebug[39m: ecovacs-deebot.0 (18633) state change: [object Object]
2020-02-26 16:58:14.728  - [34mdebug[39m: ecovacs-deebot.0 (18633) state change: [object Object]
2020-02-26 16:58:15.738  - [34mdebug[39m: ecovacs-deebot.0 (18633) state change: [object Object]
2020-02-26 16:58:15.749  - [34mdebug[39m: ecovacs-deebot.0 (18633) state change: [object Object]
2020-02-26 16:58:57.226  - [34mdebug[39m: ecovacs-deebot.0 (18633) system.adapter.admin.0: logging false
2020-02-26 17:00:15.697  - [34mdebug[39m: ecovacs-deebot.0 (18633) state change: [object Object]
2020-02-26 17:00:15.708  - [34mdebug[39m: ecovacs-deebot.0 (18633) state change: [object Object]
2020-02-26 17:00:16.697  - [34mdebug[39m: ecovacs-deebot.0 (18633) state change: [object Object]
2020-02-26 17:00:16.753  - [34mdebug[39m: ecovacs-deebot.0 (18633) state change: [object Object]
2020-02-26 17:00:20.697  - [34mdebug[39m: ecovacs-deebot.0 (18633) state change: [object Object]
2020-02-26 17:00:20.711  - [34mdebug[39m: ecovacs-deebot.0 (18633) state change: [object Object]
2020-02-26 17:02:17.713  - [34mdebug[39m: ecovacs-deebot.0 (18633) state change: [object Object]
2020-02-26 17:02:17.730  - [34mdebug[39m: ecovacs-deebot.0 (18633) state change: [object Object]
2020-02-26 17:02:35.011  - [34mdebug[39m: ecovacs-deebot.0 (18633) system.adapter.admin.0: logging true
--------------------------------------------
**In der History:**
90 | true | ecovacs-deebot.0 | 2020-02-26 18:02:17.707 |  
96 | true | ecovacs-deebot.0 | 2020-02-26 18:00:20.693 |  
95 | true | ecovacs-deebot.0 | 2020-02-26 18:00:16.693 |  
90 | true | ecovacs-deebot.0 | 2020-02-26 18:00:15.693 |  
95 | true | ecovacs-deebot.0 | 2020-02-26 17:58:15.734 |  
90 | true | ecovacs-deebot.0 | 2020-02-26 17:58:14.713 |  
95 | true | ecovacs-deebot.0 | 2020-02-26 17:56:15.581 |  
95 | true | ecovacs-deebot.0 | 2020-02-26 17:56:15.580 |  
95 | true | ecovacs-deebot.0 | 2020-02-26 17:56:15.579 |  
95 | true | ecovacs-deebot.0 | 2020-02-26 17:56:15.578 |  
90 | true | ecovacs-deebot.0 | 2020-02-26 17:56:12.971 |  
90 | true | ecovacs-deebot.0 | 2020-02-26 17:56:12.971 |  
90 | true | ecovacs-deebot.0 | 2020-02-26 17:56:12.971 |  
90 | true | ecovacs-deebot.0 | 2020-02-26 17:56:12.971 |  
95 | true | ecovacs-deebot.0 | 2020-02-26 17:53:18.390 |  
95 | true | ecovacs-deebot.0 | 2020-02-26 17:53:18.390 |  
95 | true | ecovacs-deebot.0 | 2020-02-26 17:53:18.390 |  
95 | true | ecovacs-deebot.0 | 2020-02-26 17:53:18.389 |  
96 | true | ecovacs-deebot.0 | 2020-02-26 17:52:11.363 |  
96 | true | ecovacs-deebot.0 | 2020-02-26 17:52:11.363 |  
96 | true | ecovacs-deebot.0 | 2020-02-26 17:52:11.363 |  
96 | true | ecovacs-deebot.0 | 2020-02-26 17:52:11.363 |  
97 | true | ecovacs-deebot.0 | 2020-02-26 17:51:07.393 |  
97 | true | ecovacs-deebot.0 | 2020-02-26 17:51:07.393 |  
97 | true | ecovacs-deebot.0 | 2020-02-26 17:51:07.393 |  
97 | true | ecovacs-deebot.0 | 2020-02-26 17:51:07.393 |  
98 | true | ecovacs-deebot.0 | 2020-02-26 17:50:02.420 |  
98 | true | ecovacs-deebot.0 | 2020-02-26 17:50:02.416 |  
98 | true | ecovacs-deebot.0 | 2020-02-26 17:50:02.416 |  
98 | true | ecovacs-deebot.0 | 2020-02-26 17:50:02.415 |  
99 | true | ecovacs-deebot.0 | 2020-02-26 17:49:01.411 |  
99 | true | ecovacs-deebot.0 | 2020-02-26 17:49:01.411 |  
99 | true | ecovacs-deebot.0 | 2020-02-26 17:49:01.411 |  
99 | true | ecovacs-deebot.0 | 2020-02-26 17:49:01.410


Hab mal Sauger kurz laufen lassen auf 95% Akku runter dann zum Aufladen geschickt eine Zeit lang hat sich der Prozentsatz nach oben bewegt und dann gin nix mehr .

Zeit ist in der Log um eine Stunde versetzt, nach dieser Meldung passiert nix mehr in der Historie:
LOG: 2020-02-26 17:02:35.011  - [34mdebug[39m: ecovacs-deebot.0 (18633) system.adapter.admin.0: logging true

HISTORY: 90 | true | ecovacs-deebot.0 | 2020-02-26 18:02:17.707 |  

Hoff es hilft euch weiter, werd jetzt nochmal Neu installieren und schauen ob sich nochmal was ändert wenn er morgen saugt.

**Comment by mrbungle64** [comment]
@AudidriverA4 

> **In der History:**
> 90 | true | ecovacs-deebot.0 | 2020-02-26 18:02:17.707 |  
> 96 | true | ecovacs-deebot.0 | 2020-02-26 18:00:20.693 |  
> 95 | true | ecovacs-deebot.0 | 2020-02-26 18:00:16.693 |  
> 90 | true | ecovacs-deebot.0 | 2020-02-26 18:00:15.693 |  
> 95 | true | ecovacs-deebot.0 | 2020-02-26 17:58:15.734 |  
> 90 | true | ecovacs-deebot.0 | 2020-02-26 17:58:14.713 |  
> 95 | true | ecovacs-deebot.0 | 2020-02-26 17:56:15.581 |  
> 95 | true | ecovacs-deebot.0 | 2020-02-26 17:56:15.580 |  
> 95 | true | ecovacs-deebot.0 | 2020-02-26 17:56:15.579 |  
> 95 | true | ecovacs-deebot.0 | 2020-02-26 17:56:15.578 |  
> 90 | true | ecovacs-deebot.0 | 2020-02-26 17:56:12.971 |  
> 90 | true | ecovacs-deebot.0 | 2020-02-26 17:56:12.971 |  
> 90 | true | ecovacs-deebot.0 | 2020-02-26 17:56:12.971 |  
> 90 | true | ecovacs-deebot.0 | 2020-02-26 17:56:12.971 |  
> 95 | true | ecovacs-deebot.0 | 2020-02-26 17:53:18.390 |  
> ...
> 99 | true | ecovacs-deebot.0 | 2020-02-26 17:49:01.410
> 

Der Verlauf ist ziemlich weird: 95 => 90 => 95 => 90 ... => 95 => 96 => 90

Ist der Akku vielleicht nicht mehr ganz in Ordnung?

> ...
> Hoff es hilft euch weiter, werd jetzt nochmal Neu installieren und schauen ob sich nochmal was ändert wenn er morgen saugt.

In der aktuellen Version auf GutHub ist das Logging noch mal verbessert. Es wäre gut, wenn Du diese Version dann vorher installieren könntest :)

**Comment by AudidriverA4** [comment]
Kann schon sein das der Akku nicht mehr volle Leistung hat . Er hat ja schon über ein Jahr hinter sich. 
Ich lade heut Abend mal neu 👍🏻

**Comment by AudidriverA4** [comment]
Heute Vormittag hat er gesucht ab 10 Uhr für 48min nur die Akkuaufzeichnung in der History geht immer nur ein paar Minuten und hört dann auf.
Eigentlich müsste die Aufzeichnung um 10 Uhr starten und enden bis Akku wieder geladen ist. 
<img width="898" alt="Screenshot 2020-02-27 15 26 18" src="https://user-images.githubusercontent.com/46032677/75454574-ee2a0b80-5975-11ea-91f2-1953987fe4b5.png">

Kann man da noch was einstellen das ich evtl was falsch mache?
Hier mal noch ein Screen von der Einstellung:
<img width="1216" alt="Screenshot 2020-02-27 15 29 43" src="https://user-images.githubusercontent.com/46032677/75454638-06018f80-5976-11ea-9161-41d91470a927.png">

hab eben nochmal neu Installiert und geb wenn ich dazu komme morgen wieder Info.

Ist etz aber alles kein grosses Problem für mich, bin voll zufrieden wie alles Funktioniert :-) und Beineide euch wie ihr das alles so hin bekommt.

**Comment by mrbungle64** [comment]
> <img alt="Screenshot 2020-02-27 15 26 18" width="898" src="https://user-images.githubusercontent.com/46032677/75454574-ee2a0b80-5975-11ea-91f2-1953987fe4b5.png">
> 

@AudidriverA4 
Irgendwas stimmt da nicht... Entweder ist der Akku wirklich fehlerhaft oder da "funkt" etwas dazwischen ...

@boriswerner: Ich würde gerne den ioBroker Adapter mit der Version 0.3.0 der Library auf GitHub veröffentlichen. Ist das für Dich ok?

> Kann man da noch was einstellen das ich evtl was falsch mache?
> Hier mal noch ein Screen von der Einstellung:
> <img alt="Screenshot 2020-02-27 15 29 43" width="1216" src="https://user-images.githubusercontent.com/46032677/75454638-06018f80-5976-11ea-9161-41d91470a927.png">

@AudidriverA4 
Das sieht aber soweit gut aus :+1:

**Comment by boriswerner** [comment]
> Ich würde gerne den ioBroker Adapter mit der Version 0.3.x der Library auf GitHub veröffentlichen. Ist das für Dich ok?

Klar!

**Comment by mrbungle64** [comment]
@AudidriverA4 

Version 0.5.0 steht auf GitHub bereit :)

**Comment by mrbungle64** [comment]
@AudidriverA4 

Hattest Du noch mal die Gelegenheit zu testen? Aktuell ist die Version 0.5.3 auf GitHub.

**Comment by AudidriverA4** [comment]
@mrbungle64 
Sorry bin die Woche nicht viel dazu gekommen.
Kuck mal heut Abend das ich zum install komme 
Danke 😊

**Comment by mrbungle64** [comment]
@AudidriverA4 

Es gibt inzwischen einen weiteren Bericht, dass die Akkuwerte beim Deebot 900 manchmal komisch sind.

https://forum.iobroker.net/topic/31060/ecovacs-deebot-adapter/10

Es scheint dann doch nicht der Akku zu sein. Ich bin an der Sache dran :)

**Comment by helfi9999** [comment]
Hallo zusammen,
nach dem ich die Version 0.5.6. geupdatet habe läuft mein Akkustand weiter. Vor der Version ist der auch immer stehen geblieben.

**Comment by AudidriverA4** [comment]
> @AudidriverA4
> 
> Es gibt inzwischen einen weiteren Bericht, dass die Akkuwerte beim Deebot 900 manchmal komisch sind.
> 
> https://forum.iobroker.net/topic/31060/ecovacs-deebot-adapter/10
> 
> Es scheint dann doch nicht der Akku zu sein. Ich bin an der Sache dran :)

Super komm momentan nicht viel zum probieren leider es läuft alles und macht seine Arbeit. Werd dann mal neusten stand installieren und wenn ich dazu komme mal kucken 👍🏻

**Comment by helfi9999** [comment]
Muss leider sagen das es das auch nicht wahr. Akkustand ist bei 78 Prozent stehen geblieben. Auch ein rebooten des Adapters zeigt nicht den aktuellen Stand an obwohl der Sauger voll geladen ist laut App.

**Comment by mrbungle64** [comment]
> Muss leider sagen das es das auch nicht wahr. Akkustand ist bei 78 Prozent stehen geblieben. Auch ein rebooten des Adapters zeigt nicht den aktuellen Stand an obwohl der Sauger voll geladen ist laut App.

Ich gehe mal davon aus, dass beim Deebot 900 ein anderer Event "dazwischenfunkt" ...
Grundsätzlich gibt es bei den aktuellen Modellen (nach meinem Stand) 3 Gerätegruppen - aber auch innerhalb dieser hat Ecovacs leider ein paar Sachen im Detail unterschiedlich implementiert. Dazu gibt es aber keine öffentlich zugängliche Doku.

Von daher würde ich vorschlagen, dass wenn die anderen Status wie z.B. cleanstatus und chargestatus weiterhin aktualisiert werden und die Reinigungsfunktionen auch ohne Neustart weiterhin gestartet werden können, den Akkuwert erst mal (ohne Neustart) zu beobachten.

**Comment by helfi9999** [comment]
> 
> 
> > Muss leider sagen das es das auch nicht wahr. Akkustand ist bei 78 Prozent stehen geblieben. Auch ein rebooten des Adapters zeigt nicht den aktuellen Stand an obwohl der Sauger voll geladen ist laut App.
> 
> @helfi9999 @AudidriverA4
> Ich gehe mal davon aus, dass beim Deebot 900 ein anderer Event "dazwischenfunkt" ...
> Grundsätzlich gibt es bei den aktuellen Modellen (nach meinem Stand) 3 Gerätegruppen - aber auch innerhalb dieser hat Ecovacs leider ein paar Sachen im Detail unterschiedlich implementiert. Dazu gibt es aber keine öffentlich zugängliche Doku.
> 
> Von daher würde ich vorschlagen, dass wenn die anderen Status wie z.B. cleanstatus und chargestatus weiterhin aktualisiert werden und die Reinigungsfunktionen auch ohne Neustart weiterhin gestartet werden können, den Akkuwert erst mal (ohne Neustart) zu beobachten.

Kein Problem.
Wäre nur noch das Problem mit den Verbrauchsmaterialen

**Comment by AudidriverA4** [comment]
@mrbungle64 

Kein Problem ist ja nicht es wichtigste 👍🏻 Hauptsache es läuft über die Vis 😊

**Comment by mrbungle64** [comment]
> @mrbungle64
> 
> Kein Problem ist ja nicht es wichtigste 👍🏻 Hauptsache es läuft über die Vis

Na ja, ich würde es schon gerne lösen ;)
Ich gehe mal davon aus, dass der Akkuwert ja auch über die VIS angezeigt werden soll, oder?

**Comment by Grizzelbee** [comment]
Habe gerade die aktuelle GitHub Version getestet: (V0.5.7 mit Lib 0.3.8 - Admin zeigt aber noch 0.5.6).
In der Kombination zeigt mein Deebot Ozmo 900 nicht mehr diese kruden 63% Akku an, sondern die korrekten 100%!

Das ist doch ein Erfolg!

**Comment by mrbungle64** [comment]
Hi @Grizzelbee 

> Habe gerade die aktuelle GitHub Version getestet: (V0.5.7 mit Lib 0.3.8 - Admin zeigt aber noch 0.5.6).

Zeigt der noch die 0.5.6 als "Installierte Version" an, wenn Du die Ansicht aktualisierst (Symbol "Adapterinformationen aktualisieren")?

> In der Kombination zeigt mein Deebot Ozmo 900 nicht mehr diese kruden 63% Akku an, sondern die korrekten 100%!

Hat der vorher immer genau 63% angezeigt?
Zeigt der auch die Werte nun korrekt an, wenn der am saugen ist?

> 
> Das ist doch ein Erfolg!

:+1:

**Comment by Grizzelbee** [comment]
> Zeigt der noch die 0.5.6 als "Installierte Version" an, wenn Du die Ansicht aktualisierst (Symbol "Adapterinformationen aktualisieren")?
Japp. Tut er.
Wenn ich das richtig im Kopf habe, ist dafür der eintrag in der io-package.json verantwortlich.

> Hat der vorher immer genau 63% angezeigt?
Ja. Bei voller Ladung hat der bei mir (reproduzierbar) immer ganau 63% angezeigt.

> Zeigt der auch die Werte nun korrekt an, wenn der am saugen ist?
Das werde ich heute mal testen, wenn es Familienkompatibel ist. ;)

**Comment by mrbungle64** [comment]
> > Zeigt der noch die 0.5.6 als "Installierte Version" an, wenn Du die Ansicht aktualisierst (Symbol "Adapterinformationen aktualisieren")?
> 
> Japp. Tut er.
> Wenn ich das richtig im Kopf habe, ist dafür der Eintrag in der io-package.json verantwortlich.
> 

Ja da ist auch die 0.5.7 eingetragen:
https://github.com/mrbungle64/ioBroker.ecovacs-deebot/blob/master/io-package.json

Und ebenfalls in der package.json:
https://github.com/mrbungle64/ioBroker.ecovacs-deebot/blob/master/package.json

**Comment by Grizzelbee** [comment]
> Zeigt der auch die Werte nun korrekt an, wenn der am saugen ist?

Japp tut er. Sieht bisher sehr gut aus.

**Comment by mrbungle64** [comment]
Akkuanzeige scheint beim Deebot 900 inzwischen grundsätzlich zu funktionieren.
Ich schließe den Issue daher.

**Comment by mrbungle64** [comment]
Akkuanzeige scheint beim Deebot 900 inzwischen grundsätzlich zu funktionieren.
Ich schließe den Issue daher.
