### ISSUE TITLE
Keine Reaktion nach ca. 24 Stunden

### ISSUE THREAD

**Issue by Denkra** [mrbungle64/ioBroker.ecovacs-deebot#24]
Habe das Problem, nach ca. 24 Stunden nicht saugen der Adapter nicht mehr reagiert bzw nichts mehr an den Staubsauger weiterleitet. Sobald ich den Adapter neu starte funktioniert es wieder super.

**Comment by mrbungle64** [comment]
> Habe das Problem, nach ca. 24 Stunden nicht saugen der Adapter nicht mehr reagiert bzw nichts mehr an den Staubsauger weiterleitet. Sobald ich den Adapter neu starte funktioniert es wieder super.

Hallo @Denkra 

Danke für das Feedback. Um welches Modell handelt es sich?

Falls Du weitere Infos hast, in welchem Umfang Dein Gerät funktoniert wäre das toll :)

**Comment by Denkra** [comment]
Hi. Also es ist der Ozmo 930.

Funktionieren tut eigentlich soweit fast alles. Ich kann ihn suchen also das er einen Ton abspielt, Pause, fortsetzen funktioniert, Einzelne Räume reinigen funktioniert auch also eigentlich keine einschränkungen bis halt auf das, das der Adapter teilweise neu gestartet werden muss damit es funktioniert.

**Comment by Denkra** [comment]
![Screenshot_279](https://user-images.githubusercontent.com/47492483/75436089-451ee900-5954-11ea-9dd4-e736798426f6.jpg)
 Hier mal ein Bild vom Adapter was er alles anzeigt. Also alle Werte die da zu sehen sind, sind auch richtig und können benutzt werden.

**Comment by mrbungle64** [comment]
@Denkra 
> Hi. Also es ist der Ozmo 930.
> 
> Funktionieren tut eigentlich soweit fast alles. Ich kann ihn suchen also das er einen Ton abspielt, Pause, fortsetzen funktioniert, Einzelne Räume reinigen funktioniert auch also eigentlich keine einschränkungen bis halt auf das, das der Adapter teilweise neu gestartet werden muss damit es funktioniert.

ah ok, ich habe auch einen Ozmo 930 :)

Bei mir werden aber über Nacht ein paar Adapter, welche nachts keinen Sinn machen zu laufen, gestoppt und am Morgen wieder gestartet. Ich werde den mal da raus nehmen und testen ob das bei mir auch so ist, dass der Adapter nach 24 Stunden nicht mehr korrekt arbeitet.

Das wäre aber ein Workaround für Dich, den nachts automatisiert neu zu starten zu lassen.

**Comment by Denkra** [comment]
Ja das habe ich jetzt auch so eingestellt das er um 23 Uhr Uhr neu startet. So muss ich dann nicht immer den PC an machen und den Adapter manuell neu starten.

**Comment by mrbungle64** [comment]
> Ja das habe ich jetzt auch so eingestellt das er um 23 Uhr Uhr neu startet. So muss ich dann nicht immer den PC an machen und den Adapter manuell neu starten.

ok, ich werde das bei mir mal beobachten, wie es sich ohne den Neustart verhält.

**Comment by Denkra** [comment]
Okay super. Vielen dank

**Comment by boriswerner** [comment]
Man könnte vielleicht vor dem Senden eines Befehls noch den Verbindungsstatus prüfen und ggf wiederverbinden.
Zeigt der Adapter denn noch an, dass er verbunden sei?

**Comment by Denkra** [comment]
Der Adapter ist grün. Nimmt nur keine Befehle mehr an.

**Comment by DonToben** [comment]
Gleiches Problem habe ich auch. Obwohl Adapter grün, keine Reaktion. Erst wieder nach Neustart im io Broker. Ozmo 930 Adapter 4.2

**Comment by Denkra** [comment]
@DonToben dann bin ich wenigstens nicht der einzige. Momentan habe ich das auch so wie @mrbungle64 geschrieben hat... Adapter einfach jeden Nacht einmal neu starten.

**Comment by mrbungle64** [comment]
@DonToben @Denkra 

Ich werde mal einen reconnect über Nacht (z.B. 3 Uhr) einbauen.

Das Problem scheint entweder expilizit den Ozmo 930 zu betreffen oder die XMPP basierten Geräte. Ich habe solche Geräte zwar hier, aber als Entwickler starte ich den Adpater so oft neu, dass der Effekt bei mir wahrscheinlich sehr selten auftritt ;)

**Comment by mrbungle64** [comment]
> Ich werde mal einen reconnect über Nacht (z.B. 3 Uhr) einbauen.

@DonToben @Denkra 
Ich habe das mal eingebaut. Leider habe ich beim Testen festgestellt, dass der die bestehende Verbindung nicht sauber trennt. Da ich noch nicht weiß woran es liegt, habe ich das Problem mal als "Known Issue" in die Readme bzw. Doku aufgenommen.

Ein zeitgesteuerter Neustart (in den Instanzen unter "Neu starten") ist ja erst mal ein vernünftiger Workaround ohne viel Aufwand.

Btw.: Spätestens morgen wird die neue Version 0.5.5 verfügbar sein :)
Wer sie bereits jetzt nutzen will - die ist (Stand jetzt noch) identisch mit der Version auf GitHub.
