### ISSUE TITLE
OZMO 950:  Datenpunkte leer und Verbindung Adapter mal gelb mal grün.

### ISSUE THREAD

**Issue by smarteule** [mrbungle64/ioBroker.ecovacs-deebot#26]
Hallo, 
ich habe mir einen OZMO 950 mit Firmware 1.7.6 gegönnt. Ich weiß es wird noch am Adapter gearbeitet, aber ich wollte Euch hiermit meine Hilfe anbieten. Soweit sie benötigt wird und ich mit meinen bescheidenden Kenntnissen helfen kann.
Angezeigt wird nur:

![image](https://user-images.githubusercontent.com/61357030/75481628-a4581a00-59a3-11ea-8144-7ab1546a1607.png)

Gr
Smarteule

**Comment by mrbungle64** [comment]
Hallo @smarteule 

hast Du die Version aus der Latest Repo oder von GitHub installiert?

> Hallo,
> ich habe mir einen OZMO 950 mit Firmware 1.7.6 gegönnt. Ich weiß es wird noch am Adapter gearbeitet, aber ich wollte Euch hiermit meine Hilfe anbieten. Soweit sie benötigt wird und ich mit meinen bescheidenden Kenntnissen helfen kann.

Möchtest Du eher Testen oder an der Entwicklung des Adapters (oder der Library) mitwirken?

> ...
> Gr
> Smarteule

**Comment by smarteule** [comment]
Ja natürlich. Immer von GitHub, ist bekanntlich schneller als ioBroker.

Was die Mitwirkung angeht, kann ich sagen, ich habe einen Raspberry Pi 4 4GB mit Raspbian Booster und ich möchte gerne am Adapter helfen, dass dieser ebenso gut, wie der roomba Adapter wird. Also Testen, usw. ist kein Problem. Eventuell mit Hilfestellung, was entsprechend zu tun ist.

**Comment by mrbungle64** [comment]
> Ja natürlich. Immer von GitHub, ist bekanntlich schneller als ioBroker.

Das ist aber nicht immer sinnvoll, wenn man ein stabiles System haben möchte ;)
In diesem Fall macht es aber Sinn :+1: 

> 
> Was die Mitwirkung angeht, kann ich sagen, ich habe einen Raspberry Pi 4 4GB mit Raspbian Booster und ich möchte gerne am Adapter helfen, dass dieser ebenso gut, wie der roomba Adapter wird. Also Testen, usw. ist kein Problem. Eventuell mit Hilfestellung, was entsprechend zu tun ist.

Ich veröffentliche gleich mal eine neue Version auf GitHub (wenn nix dabei schief geht) - evtl. kannst Du dann ja gleich mal Testen :D

**Comment by smarteule** [comment]
okay, kann ich testen.

**Comment by mrbungle64** [comment]
> okay, kann ich testen.

@smarteule 
Sehr gut, danke :+1: 
Version 0.5.0 ist über GitHub verfügbar :)

**Comment by smarteule** [comment]
Also der Start des Adapters ging innerhalb von zwei, drei Sekunden auf grün.
Der Datenpunkt ecovacs-deebot.0.consumable ist vollständig ausgefüllt.
Ich teste morgen gleich alle weiteren Punkte.

![image](https://user-images.githubusercontent.com/61357030/75486165-4ed43b00-59ac-11ea-8207-c6291f2da1c3.png)

**Comment by mrbungle64** [comment]
> Also der Start des Adapters ging innerhalb von zwei, drei Sekunden auf grün.
> Der Datenpunkt ecovacs-deebot.0.consumable ist vollständig ausgefüllt.
> Ich teste morgen gleich alle weiteren Punkte.
> 
> ![image](https://user-images.githubusercontent.com/61357030/75486165-4ed43b00-59ac-11ea-8207-c6291f2da1c3.png)

Das sieht doch schon mal gut aus :+1:

**Comment by boriswerner** [comment]
@smarteule Super, vielen Dank für's testen. Was fehlt dir denn vor allem noch so an Features beim Adapter im Gegensatz zum roomba?
Wenn der Adapter auf gelb ist mal ins Log schauen, ob es viele "reconnecting (x)" Einträge gibt. die Server von Ecovacs stellen sich mit der Authentifizierung oft an (was man auch in der App merkt)

**Comment by smarteule** [comment]
Hallo,
ich habe gerade meinen Test mit der neuen Adapterversion abgeschlossen.
Zur obigen Frage "reconnecting" hänge ich unten einen kleinen Log mit an.
Im Prinzip war der Adapter immer grün. Einmal musste ich ihn aus einem anderen Grund ausschalten, daraus entstand der unten aufgelistete Log.

_Die Befehle:_
"charge" funktioniert
"clean" funktioniert
"customArea_cleanings" noch nicht getestet
"pause" funktioniert
"playSound" funktioniert
"SpotArea" noch nicht getestet
"stop" funktioniert
"waterLevel" funktioniert, aber kommt verzögert

_Die Infos:_
Bei den Infos fehlen gegenüber dem Roomba Adapter einige Werte. Ich weiß allerdings nicht, ob diese von diesem Gerät gesendet werden. 
Das ist:
- aktuelle IP Adresse
- Errormeldung, wenn Gerät ein Problem hat
- Statusmeldung / Gerätestatus **- wäre sehr wichtig-** , was wird gerade gemacht (charge, clean,...)
- gefahrene Strecke
- Wegskizze bzw. die gespeicherten Pläne **- wäre auch sehr wichtig-**

Hier der Log:
`ecovacs-deebot.0	2020-02-28 10:31:43.494	debug	(20048) system.adapter.admin.0: logging true
ecovacs-deebot.0	2020-02-28 10:31:41.904	debug	(20048) state change info.waterbox => true
ecovacs-deebot.0	2020-02-28 10:31:41.820	debug	(20048) state change consumable.main_brush => 99
ecovacs-deebot.0	2020-02-28 10:31:41.819	debug	(20048) state change consumable.side_brush => 98
ecovacs-deebot.0	2020-02-28 10:31:41.817	debug	(20048) state change consumable.filter => 98
ecovacs-deebot.0	2020-02-28 10:31:41.816	debug	(20048) state change info.chargestatus => not charging
ecovacs-deebot.0	2020-02-28 10:31:41.813	debug	(20048) state change consumable.main_brush => 99
ecovacs-deebot.0	2020-02-28 10:31:41.809	debug	(20048) state change consumable.side_brush => 98
ecovacs-deebot.0	2020-02-28 10:31:41.807	debug	(20048) state change consumable.filter => 98
ecovacs-deebot.0	2020-02-28 10:31:41.801	debug	(20048) state change consumable.main_brush => 99
ecovacs-deebot.0	2020-02-28 10:31:41.797	debug	(20048) state change consumable.side_brush => 98
ecovacs-deebot.0	2020-02-28 10:31:41.795	debug	(20048) state change consumable.filter => 98
ecovacs-deebot.0	2020-02-28 10:31:41.783	info	(20048) Unhandled chargestatus: not charging
ecovacs-deebot.0	2020-02-28 10:31:41.763	debug	(20048) state change info.battery => 85
ecovacs-deebot.0	2020-02-28 10:31:41.525	debug	(20048) state change info.communicationProtocol => MQTT
ecovacs-deebot.0	2020-02-28 10:31:41.520	debug	(20048) state change info.deviceClass => yna5xi
ecovacs-deebot.0	2020-02-28 10:31:41.516	debug	(20048) state change info.deviceName => Saugwischsklave
ecovacs-deebot.0	2020-02-28 10:31:41.513	debug	(20048) state change info.connection => true
ecovacs-deebot.0	2020-02-28 10:31:41.494	info	(20048) [vacbot] name: DEEBOT OZMO 950 Series
ecovacs-deebot.0	2020-02-28 10:31:41.491	info	(20048) Saugwischsklave successfully connected
ecovacs-deebot.0	2020-02-28 10:31:40.236	info	(20048) Successfully connected to Ecovacs server
ecovacs-deebot.0	2020-02-28 10:31:40.235	info	(20048) Using device Device[0]
ecovacs-deebot.0	2020-02-28 10:31:40.235	info	(20048) Device[0]: {"did":"5244bd2f-4d20-4fa4-b732-e3e630e8f634","name":"E0001279619602180472","class":"yna5xi","resource":"jUkk","nick":"Saugwischsklave","company":"eco-ng","bindTs":1582731615593}
ecovacs-deebot.0	2020-02-28 10:31:40.234	info	(20048) Number of devices: 1
ecovacs-deebot.0	2020-02-28 10:31:40.233	debug	(20048) Devices:[{"did":"5244bd2f-4d20-4fa4-b732-e3e630e8f634","name":"E0001279619602180472","class":"yna5xi","resource":"jUkk","nick":"Saugwischsklave","company":"eco-ng","bindTs":1582731615593}]
ecovacs-deebot.0	2020-02-28 10:31:38.495	debug	(20048) state change info.error =>
ecovacs-deebot.0	2020-02-28 10:31:38.442	info	(20048) reconnecting (1) ...
ecovacs-deebot.0	2020-02-28 10:31:32.439	debug	(20048) state change info.error => reconnecting
ecovacs-deebot.0	2020-02-28 10:31:32.418	debug	(20048) state change info.connection => false
ecovacs-deebot.0	2020-02-28 10:31:32.267	debug	(20048) state change info.error =>
ecovacs-deebot.0	2020-02-28 10:31:32.266	debug	(20048) state change info.connection => false
ecovacs-deebot.0	2020-02-28 10:31:32.118	info	(20048) starting. Version 0.5.0 in /opt/iobroker/node_modules/iobroker.ecovacs-deebot, node: v10.19.0
ecovacs-deebot.0	2020-02-28 10:31:31.220	debug	(20048) statesDB connected
ecovacs-deebot.0	2020-02-28 10:31:31.219	debug	(20048) States connected to redis: 0.0.0.0:9000
ecovacs-deebot.0	2020-02-28 10:31:31.205	debug	(20048) States create System PubSub Client
ecovacs-deebot.0	2020-02-28 10:31:31.202	debug	(20048) States create User PubSub Client
ecovacs-deebot.0	2020-02-28 10:31:31.193	debug	(20048) Redis States: Use Redis connection: 0.0.0.0:9000
ecovacs-deebot.0	2020-02-28 10:31:31.190	debug	(20048) objectDB connected
ecovacs-deebot.0	2020-02-28 10:31:31.184	debug	(20048) Objects connected to redis: 0.0.0.0:9001
ecovacs-deebot.0	2020-02-28 10:31:31.169	debug	(20048) Objects client initialize lua scripts
ecovacs-deebot.0	2020-02-28 10:31:31.168	debug	(20048) Objects create User PubSub Client
ecovacs-deebot.0	2020-02-28 10:31:31.167	debug	(20048) Objects create System PubSub Client
ecovacs-deebot.0	2020-02-28 10:31:31.162	debug	(20048) Objects client ready ... initialize now
ecovacs-deebot.0	2020-02-28 10:31:31.122	debug	(20048) Redis Objects: Use Redis connection: 0.0.0.0:9001
ecovacs-deebot.0	2020-02-28 10:31:23.447	debug	(19875) state change info.connection => false
ecovacs-deebot.0	2020-02-28 10:31:23.437	info	(19875) Terminated (START_IMMEDIATELY_AFTER_STOP): Without reason
ecovacs-deebot.0	2020-02-28 10:31:23.435	info	(19875) terminating
ecovacs-deebot.0	2020-02-28 10:31:23.434	info	(19875) cleaned everything up...
ecovacs-deebot.0	2020-02-28 10:31:23.430	info	(19875) Got terminate signal TERMINATE_YOURSELF
ecovacs-deebot.0	2020-02-28 10:31:22.485	debug	(19875) state change info.error => reconnecting
ecovacs-deebot.0	2020-02-28 10:31:22.481	debug	(19875) state change info.connection => false
ecovacs-deebot.0	2020-02-28 10:31:22.078	debug	(19875) state change info.error =>
ecovacs-deebot.0	2020-02-28 10:31:22.037	info	(19875) reconnecting (16) ...
ecovacs-deebot.0	2020-02-28 10:31:16.032	debug	(19875) state change info.error => reconnecting
ecovacs-deebot.0	2020-02-28 10:31:16.025	debug	(19875) state change info.connection => false
ecovacs-deebot.0	2020-02-28 10:31:15.636	debug	(19875) state change info.error =>
ecovacs-deebot.0	2020-02-28 10:31:15.608	info	(19875) reconnecting (15) ...
ecovacs-deebot.0	2020-02-28 10:31:09.607	debug	(19875) state change info.error => reconnecting
ecovacs-deebot.0	2020-02-28 10:31:09.605	debug	(19875) state change info.connection => false
ecovacs-deebot.0	2020-02-28 10:31:09.534	debug	(19875) state change info.error =>
ecovacs-deebot.0	2020-02-28 10:31:09.427	info	(19875) reconnecting (14) ...
ecovacs-deebot.0	2020-02-28 10:31:03.423	debug	(19875) state change info.error => reconnecting
ecovacs-deebot.0	2020-02-28 10:31:03.417	debug	(19875) state change info.connection => false
ecovacs-deebot.0	2020-02-28 10:31:03.008	debug	(19875) state change info.error =>
ecovacs-deebot.0	2020-02-28 10:31:02.966	info	(19875) reconnecting (13) ...
ecovacs-deebot.0	2020-02-28 10:30:56.964	debug	(19875) state change info.error => reconnecting
ecovacs-deebot.0	2020-02-28 10:30:56.959	debug	(19875) state change info.connection => false
ecovacs-deebot.0	2020-02-28 10:30:56.580	debug	(19875) state change info.error =>
ecovacs-deebot.0	2020-02-28 10:30:56.516	info	(19875) reconnecting (12) ...
ecovacs-deebot.0	2020-02-28 10:30:50.514	debug	(19875) state change info.error => reconnecting
ecovacs-deebot.0	2020-02-28 10:30:50.511	debug	(19875) state change info.connection => false
ecovacs-deebot.0	2020-02-28 10:30:50.105	debug	(19875) state change info.error =>
ecovacs-deebot.0	2020-02-28 10:30:50.064	info	(19875) reconnecting (11) ...
ecovacs-deebot.0	2020-02-28 10:30:44.063	debug	(19875) state change info.error => reconnecting
ecovacs-deebot.0	2020-02-28 10:30:44.061	debug	(19875) state change info.connection => false
ecovacs-deebot.0	2020-02-28 10:30:43.618	debug	(19875) state change info.error =>
ecovacs-deebot.0	2020-02-28 10:30:43.575	info	(19875) reconnecting (10) ...
ecovacs-deebot.0	2020-02-28 10:30:37.573	debug	(19875) state change info.error => reconnecting
ecovacs-deebot.0	2020-02-28 10:30:37.567	debug	(19875) state change info.connection => false
ecovacs-deebot.0	2020-02-28 10:30:37.159	debug	(19875) state change info.error =>
ecovacs-deebot.0	2020-02-28 10:30:37.124	info	(19875) reconnecting (9) ...
ecovacs-deebot.0	2020-02-28 10:30:31.119	debug	(19875) state change info.error => reconnecting
ecovacs-deebot.0	2020-02-28 10:30:31.117	debug	(19875) state change info.connection => false
ecovacs-deebot.0	2020-02-28 10:30:30.675	debug	(19875) state change info.error =>
ecovacs-deebot.0	2020-02-28 10:30:30.632	info	(19875) reconnecting (8) ...
ecovacs-deebot.0	2020-02-28 10:30:24.631	debug	(19875) state change info.error => reconnecting
ecovacs-deebot.0	2020-02-28 10:30:24.629	debug	(19875) state change info.connection => false
ecovacs-deebot.0	2020-02-28 10:30:24.478	debug	(19875) state change info.error =>
ecovacs-deebot.0	2020-02-28 10:30:24.454	info	(19875) reconnecting (7) ...
ecovacs-deebot.0	2020-02-28 10:30:18.452	debug	(19875) state change info.error => reconnecting
ecovacs-deebot.0	2020-02-28 10:30:18.450	debug	(19875) state change info.connection => false
ecovacs-deebot.0	2020-02-28 10:30:18.067	debug	(19875) state change info.error =>
ecovacs-deebot.0	2020-02-28 10:30:18.024	info	(19875) reconnecting (6) ...
ecovacs-deebot.0	2020-02-28 10:30:12.022	debug	(19875) state change info.error => reconnecting
ecovacs-deebot.0	2020-02-28 10:30:12.019	debug	(19875) state change info.connection => false
ecovacs-deebot.0	2020-02-28 10:30:11.630	debug	(19875) state change info.error =>
ecovacs-deebot.0	2020-02-28 10:30:11.605	info	(19875) reconnecting (5) ...
ecovacs-deebot.0	2020-02-28 10:30:05.603	debug	(19875) state change info.error => reconnecting
ecovacs-deebot.0	2020-02-28 10:30:05.599	debug	(19875) state change info.connection => false
ecovacs-deebot.0	2020-02-28 10:30:05.212	debug	(19875) state change info.error =>
ecovacs-deebot.0	2020-02-28 10:30:05.177	info	(19875) reconnecting (4) ...
ecovacs-deebot.0	2020-02-28 10:29:59.175	debug	(19875) state change info.error => reconnecting
ecovacs-deebot.0	2020-02-28 10:29:59.174	debug	(19875) state change info.connection => false
ecovacs-deebot.0	2020-02-28 10:29:59.062	debug	(19875) state change info.error =>
ecovacs-deebot.0	2020-02-28 10:29:59.041	info	(19875) reconnecting (3) ...
ecovacs-deebot.0	2020-02-28 10:29:53.039	debug	(19875) state change info.error => reconnecting
ecovacs-deebot.0	2020-02-28 10:29:53.037	debug	(19875) state change info.connection => false
ecovacs-deebot.0	2020-02-28 10:29:52.608	debug	(19875) state change info.error =>
ecovacs-deebot.0	2020-02-28 10:29:52.567	info	(19875) reconnecting (2) ...
ecovacs-deebot.0	2020-02-28 10:29:46.565	debug	(19875) state change info.error => reconnecting
ecovacs-deebot.0	2020-02-28 10:29:46.557	debug	(19875) state change info.connection => false
ecovacs-deebot.0	2020-02-28 10:29:46.158	debug	(19875) state change info.error =>
ecovacs-deebot.0	2020-02-28 10:29:46.117	info	(19875) reconnecting (1) ...
ecovacs-deebot.0	2020-02-28 10:29:40.114	debug	(19875) state change info.error => reconnecting
ecovacs-deebot.0	2020-02-28 10:29:40.110	debug	(19875) state change info.connection => false
ecovacs-deebot.0	2020-02-28 10:29:39.637	debug	(19875) state change info.error =>
ecovacs-deebot.0	2020-02-28 10:29:39.634	debug	(19875) state change info.connection => false
ecovacs-deebot.0	2020-02-28 10:29:39.453	info	(19875) starting. Version 0.5.0 in /opt/iobroker/node_modules/iobroker.ecovacs-deebot, node: v10.19.0
ecovacs-deebot.0	2020-02-28 10:29:38.768	debug	(19875) statesDB connected
ecovacs-deebot.0	2020-02-28 10:29:38.768	debug	(19875) States connected to redis: 0.0.0.0:9000
ecovacs-deebot.0	2020-02-28 10:29:38.753	debug	(19875) States create System PubSub Client
ecovacs-deebot.0	2020-02-28 10:29:38.750	debug	(19875) States create User PubSub Client
ecovacs-deebot.0	2020-02-28 10:29:38.738	debug	(19875) Redis States: Use Redis connection: 0.0.0.0:9000
ecovacs-deebot.0	2020-02-28 10:29:38.732	debug	(19875) objectDB connected
ecovacs-deebot.0	2020-02-28 10:29:38.721	debug	(19875) Objects connected to redis: 0.0.0.0:9001
ecovacs-deebot.0	2020-02-28 10:29:38.684	debug	(19875) Objects client initialize lua scripts
ecovacs-deebot.0	2020-02-28 10:29:38.683	debug	(19875) Objects create User PubSub Client
ecovacs-deebot.0	2020-02-28 10:29:38.682	debug	(19875) Objects create System PubSub Client
ecovacs-deebot.0	2020-02-28 10:29:38.677	debug	(19875) Objects client ready ... initialize now
ecovacs-deebot.0	2020-02-28 10:29:38.641	debug	(19875) Redis Objects: Use Redis connection: 0.0.0.0:9001
ecovacs-deebot.0	2020-02-28 10:29:35.187	debug	(17133) state change info.connection => false
ecovacs-deebot.0	2020-02-28 10:29:35.183	info	(17133) Terminated (START_IMMEDIATELY_AFTER_STOP): Without reason
ecovacs-deebot.0	2020-02-28 10:29:35.182	info	(17133) terminating
ecovacs-deebot.0	2020-02-28 10:29:35.182	info	(17133) cleaned everything up...
ecovacs-deebot.0	2020-02-28 10:29:35.180	info	(17133) Got terminate signal TERMINATE_YOURSELF
ecovacs-deebot.0	2020-02-28 10:28:42.340	info	(17133) run: stop
ecovacs-deebot.0	2020-02-28 10:28:42.339	debug	(17133) state change control.stop => true
ecovacs-deebot.0	2020-02-28 10:28:28.938	debug	(17133) state change info.chargestatus => not charging
ecovacs-deebot.0	2020-02-28 10:28:28.935	debug	(17133) state change info.chargestatus => not charging
ecovacs-deebot.0	2020-02-28 10:28:28.930	info	(17133) Unhandled chargestatus: not charging
ecovacs-deebot.0	2020-02-28 10:28:28.930	info	(17133) Unhandled chargestatus: not charging
ecovacs-deebot.0	2020-02-28 10:28:20.949	info	(17133) run: clean
ecovacs-deebot.0	2020-02-28 10:28:20.948	debug	(17133) state change control.clean => true
ecovacs-deebot.0	2020-02-28 10:28:10.283	info	(17133) run: charge
ecovacs-deebot.0	2020-02-28 10:28:10.282	debug	(17133) state change control.charge => true`

**Comment by boriswerner** [comment]
@smarteule die neueste Version hier auf GitHub unterstützt nun auch die Netzwerk Informationen, die auch in der App zu sehen sind (IP, MAC, WLAN Name und WLAN Signalstärke). Dazu noch einige Infos zur aktuellen Karte und Position (inkl. Relocate) und die Steuerung der Saugkraft.
Du darfst sehr gerne testen wenn du magst :-)
Das Thema
"waterLevel" funktioniert, aber kommt verzögert
Sollte auch gelöst sein, es wird jetzt direkt nach dem setzen der neue Status am den iobroker geliefert, wenn erfolgreich.
Deine anderen Themen sind auch oben auf der Liste, benötigen aber etwas mehr Zeit

**Comment by smarteule** [comment]
SUPER !!!
Es ist gut, dass es so findige Programmierer gibt und das noch in Deiner Freizeit.
Ich Danke Dir hochachtungsvoll für viele Nutzer hier.

Natürlich werde ich die Version morgen oder am Mittwoch testen. Ich hoffe, dass mein defekter Ozmo 950 bis morgen repariert wieder zurück ist. Er hatte nach wenigen Tagen ein Problem mit dem linken Antrieb. Er wollte nicht mehr.
Ich gebe umgehend meinen Bericht ab.

Gr

**Comment by smarteule** [comment]
Hallo,
gestern kam endlich mein guter Saugsklave, somit konnte ich endlich Deine neue Version testen. Die Verbindung erfolgte innerhalb von 2-3 Sekunden spitze.

- Netzwerkinformationen sind da, funktioniert super.
- Kartendaten, Position werden eingetragen, allerdings ist beim Roomba eine Image auslesbar, die dann im VIS eingebunden werden konnte. Ich schätze das sendet der Ozmo 950 wohl nicht?
- Die Steuerung der Saugkraft wird angezeigt und ist auswählbar bzw. funktioniert.

Hier wieder ein Abbild der Datenpunkte:
![image](https://user-images.githubusercontent.com/61357030/76108357-b442b000-5fda-11ea-9df9-f3b381df2b4b.png)

Nochmal zur Map:
Beim Roomba kam ja der Saugweg, siehe dieses Bild zum Beispiel.
![image](https://user-images.githubusercontent.com/61357030/76108621-36cb6f80-5fdb-11ea-95d7-5e6bb23daf90.png)

In der App (Ozmo 950) ist ja die Quadratmeterzahl, die entsprechende Zeit und die jeweilige Karte auch ersichtlich.

Meine Frage:
Ist diese vielleicht abrufbar, um sie dann vielleicht im VIS zu nutzen?

![image](https://user-images.githubusercontent.com/61357030/76109154-32ec1d00-5fdc-11ea-8d9e-afa93d87fcf5.png)

**Comment by boriswerner** [comment]
@smarteule ist alles möglich, aber alles auch aufwändiger zu implementieren. Das kann also noch eine Weile dauern, bis das funktioniert. Steht aber alles irgendwo auf der Roadmap ;-)

**Comment by smarteule** [comment]
Okay, wenn ich Dir irgendwie dabei helfen kann, gib Bescheid.

**Comment by smarteule** [comment]
Erst einmal Danke für die Version 0.5.5, du warst ja wieder sehr fleißig. Da funktioniert ja schon wieder sehr sehr viel, sogar die Erroranzahl wird u.a. mit angezeigt.
Ich hoffe Du steinigst mich nicht, wenn ich bescheiden anfrage. 

Für die Zukunft - ist es möglich den genauen Fehlerinhalt (Errormeldungen des Roboters)  mit zu implementieren?

**Comment by boriswerner** [comment]
Im Moment gebe ich das nur 1zu1 den Fehlercode weiter, einen Text gibt es da leider nicht. 
In irgendeiner Doku habe ich glaube ich aber Mal eine Liste der Codes gesehen. Im Moment komme ich leider zu wenig, vielleicht macht eine Roadmap Sinn. Am Wochenende kann ich Mal wieder was tun

**Comment by smarteule** [comment]
Hallo,
ich habe leider noch ein neues Problem gefunden. Die Verknüpfung des Datenpunktes "CleanSpeed" in VIS mit Widget "materialdesign-Select" funktioniert einwandfrei. Eine Auswahl von "low bis veryhigh" und anschließenden bestätigen, setzt den Wert entsprechend am Ozmo, aber
der Datenpunkt "WaterLevel" mit dem gleichen Widget "materialdesign-Select" setzt keinen Wert am Ozmo. 

Woran liegt das?

**Comment by boriswerner** [comment]
@smarteule was für Werte setzt das Widget? Numerische oder die Texte? Kannst du die Logeinträge posten, die erscheinen wenn du (erfolglos) die Werte in der VIS setzt?

**Comment by smarteule** [comment]
Numerische 1 - 4
Log bei waterLevel:
`ecovacs-deebot.0 | 2020-03-12 19:05:15.053 | info | (12145) set water level: 3
-- | -- | -- | --
ecovacs-deebot.0 | 2020-03-12 19:05:15.045 | debug | (12145) state change control.waterLevel => 3
ecovacs-deebot.0 | 2020-03-12 19:05:14.301 | info | (12145) set water level: 1
ecovacs-deebot.0 | 2020-03-12 19:05:14.294 | debug | (12145) state change control.waterLevel => 1
ecovacs-deebot.0 | 2020-03-12 19:05:10.376 | info | (12145) set water level: 3
ecovacs-deebot.0 | 2020-03-12 19:05:10.374 | debug | (12145) state change control.waterLevel => 3
ecovacs-deebot.0 | 2020-03-12 19:05:08.693 | info | (12145) set water level: 0
ecovacs-deebot.0 | 2020-03-12 19:05:08.688 | debug | (12145) state change control.waterLevel => 0
`
Log bei waterLevel:
`
ecovacs-deebot.0 | 2020-03-12 19:08:31.225 | info | (12145) set Clean Speed: 3
-- | -- | -- | --
ecovacs-deebot.0 | 2020-03-12 19:08:31.220 | debug | (12145) state change control.cleanSpeed => 3
ecovacs-deebot.0 | 2020-03-12 19:08:30.787 | info | (12145) set Clean Speed: 3
ecovacs-deebot.0 | 2020-03-12 19:08:30.782 | debug | (12145) state change control.cleanSpeed => 3
ecovacs-deebot.0 | 2020-03-12 19:08:27.576 | info | (12145) set Clean Speed: 1
ecovacs-deebot.0 | 2020-03-12 19:08:27.573 | debug | (12145) state change control.cleanSpeed => 1
ecovacs-deebot.0 | 2020-03-12 19:08:26.905 | info | (12145) set Clean Speed: 1
ecovacs-deebot.0 | 2020-03-12 19:08:26.898 | debug | (12145) state change control.cleanSpeed => 1

`

**Comment by mrbungle64** [comment]
> Hallo,
> ich habe leider noch ein neues Problem gefunden. Die Verknüpfung des Datenpunktes "CleanSpeed" in VIS mit Widget "materialdesign-Select" funktioniert einwandfrei. Eine Auswahl von "low bis veryhigh" und anschließenden bestätigen, setzt den Wert entsprechend am Ozmo, aber
der Datenpunkt "WaterLevel" mit dem gleichen Widget "materialdesign-Select" setzt keinen Wert am Ozmo.

Hallo @smarteule 
ich denke, dass wir das in einem neuen Issue behandeln sollten. Das Thema "Verknüpfung von Datenpunkten" ist auch eher unabhängig vom Modell und dieser Issue hier ist ja bisher auf den Ozmo 950 bezogen gewesen.

**Comment by smarteule** [comment]
okay

**Comment by mrbungle64** [comment]
@smarteule 
Ja genau :+1:

**Comment by mrbungle64** [comment]
@smarteule  @boriswerner 
Diesen hier können wir ja jetzt schließen, oder?

**Comment by smarteule** [comment]
ja
