### ISSUE TITLE
gotoposition funktioniert nicht mehr am 950iger

### ISSUE THREAD

**Issue by krobipd** [mrbungle64/ioBroker.ecovacs-deebot#262]
### Is there an existing issue for this?

- [X] I have searched the existing issues and no issue is describing my issue

### The problem

hallo

ich habe seit kurzem das problem das die "gotoposition" Funktion nicht mehr funktioniert.
da mein Roboter unter der Essbank "parkt" hab ich mir ein Skript geschrieben das ihn zum Mistkübel fährt, über die gotoposition, damit ich ihn dort bequem entleeren kann.

dieses Skript hat immer funktioniert, auch der gespeicherten position habe ich nichts geändert aber jetzt funktioniert es nicht mehr. Kann es am neuen js-controller liegen?

> Error while handling state change for id ecovacs-deebot.0.control.extended.goToPosition with value -5900,-1100

auch wenn ich einen dritten wert anhängt kommt folgende Fehlermeldung

> Invalid input for go to position: -5900,-1100,0

ich weiß das es sich hier um ein experimentelle Funktion handelt, aber scheinbar - wie man ja im anderen bug-report sieht - dürfte hier an der gesamten Ansteuerung etwas gedreht worden sein. meine Vermutung. 

### With which model does the problem occur?

Deebot OZMO 950

### From which source you have installed the adapter?

Beta (latest)

### Version of the ioBroker adapter ("info.version")

1.3.4

### Version of the ecovacs-deebot.js library ("info.library.version")

0.7.2-beta.0

### Version of the JS controller

4.0.15

### Version of Node.js

16.14

### Operating system

Linux

### Communication protocol ("info.library.communicationProtocol")

MQTT

### Is the canvas module installed? ("info.library.canvasModuleIsInstalled")

yes (true)

**Comment by mrbungle64** [comment]
@krobipd 

> wie man ja im anderen bug-report sieht

Welchen anderen Bug Report meinst du?

**Comment by krobipd** [comment]
entschuldige war eine Anspielung auf diesen thread https://github.com/mrbungle64/ioBroker.ecovacs-deebot/issues/260

**Comment by mrbungle64** [comment]
> entschuldige war eine Anspielung auf diesen thread #260

ok, die Warnungen bzw. Fehlermeldungen sollten damit nichts zu tun haben. Hatte die ja in diesem Issue eben auch erklärt.

An der GoTo Funktion selbst habe ich nichts geändert, aber da könnte bei einem Refactoring was "kaputt" gegangen sein. Ich schaue nachher mal danach.

> auch wenn ich einen dritten wert anhängt kommt folgende Fehlermeldung
> >  Invalid input for go to position: -5900,-1100,0

Das ist korrekt, weil eine Position aus nur aus x und y Koordinaten besteht.

**Comment by krobipd** [comment]
war nur mal ein Gedanke von mir, puh das Skript nutze ich so sicher schon über ein halbes Jahr. gab nie eine Fehlermeldung und hat auch immer - früher oder später, da er doch manchmal sehr doof ist - seinen platz gefunden.
aber wie du siehst bekomme ich ja auch einen Fehler mit 3 Koordinaten. 
oder wenn ich Koordinaten aus dem adapter nehme und die bei goto position eingebe bekomme ich einen Fehler. (invalid input)

**Comment by mrbungle64** [comment]
> ... aber wie du siehst bekomme ich ja auch einen Fehler mit 3 Koordinaten.

Du meinst 2 Koordinaten?

> oder wenn ich Koordinaten aus dem adapter nehme und die bei goto position eingebe bekomme ich einen Fehler. (invalid input)

Ja, das Problem schaue ich mir ja auch an. Wollte nur erklären, dass eine Eingabe mit 3 Koordinaten nicht valide ist 😉

**Comment by krobipd** [comment]
kein stress und vielen lieben dank für deine harte Arbeit.

nur um das ganz klar zu stellen ich sende an gotoposition "-5900,-1100"
das ergibt seit neuesten einen Fehler. ging aber natürlich vorher sonst würde ich das so nicht tun ;-)

wenn ich aus dem Datenpunkt "deebotposition" die position rauskopiere zB "-1950,-400,-2" und diese in die "gotopositon" reinkopiere ergibt das auch eine Fehlermeldung.

**Comment by mrbungle64** [comment]
> kein stress und vielen lieben dank für deine harte Arbeit.

Ist mit der 1.3.5-alpha.0 gefixt 😅  Müsstest Du aktuell aber von GitHub installieren.

> 
> nur um das ganz klar zu stellen ich sende an gotoposition "-5900,-1100" das ergibt seit neuesten einen Fehler. ging aber natürlich vorher sonst würde ich das so nicht tun ;-)

Ja, hatte das schon verstanden. Hatte den Fehler ja auch schon bestätigt  😉

> 
> wenn ich aus dem Datenpunkt "deebotposition" die position rauskopiere zB "-1950,-400,-2" und diese in die "gotopositon" reinkopiere ergibt das auch eine Fehlermeldung.

Das ist nicht wirklich eine Fehlermeldung sondern ein Hinweis, dass die Eingabe nicht valide war.
Aber du hast schon recht - es ist verwirrend, wenn man das aus dem Datenpunkt "deebotposition" raus kopiert.
Der 3. Wert ist da Winkel (siehe Name vom Datenpunkt: "Bot position (x, y, angle)") - der hat halt bei der GoToPosition Funktion keine Auswirkung und wird daher "angemeckert". Aber ich könnte den 3. Wert eigentlich auch einfach autom. abschneiden. Das werde ich mal machen 😉

**Comment by krobipd** [comment]
vielen Dank für deinen schnellen fix.
leider werde ich erst in ca 2-3 tagen dazu kommen das ganze komplett zu testen. musste leider heute die ganze map neu machen und daher einiges geändert und da sind die koordinaten jetzt auch anders :-/ zumindest hatte ich jetzt mal keine Fehlermeldung. 🥳

**Comment by krobipd** [comment]
sorry hat etwas gedauert bis jetzt endlich mal dazu kam das zu testen, funktioniert wieder einwandfrei (hab aber den last presence build)
