### ISSUE TITLE
Deebot T8 - Dustbox Removed

### ISSUE THREAD

**Issue by pansenerna** [mrbungle64/ioBroker.ecovacs-deebot#278]
### Is there an existing issue for this?

- [X] I have searched the existing issues and no issue is describing my issue

### The problem

Hallo Sascha,

bei meinem Modell (Ozmo T8) wird der Datenpunkt info.dustbox nicht aktualisiert und steht immer auf true.
Somit werden auch 
history.dateOfLastTimeDustboxRemoved
und
history.timestampOfLastTimeDustboxRemoved
nie aktualisiert.

Ist kein mega priores Thema, aber ist mir gerade aufgefallen, beim erstellen eines Node-Red-Flows.

Viele Grüße,
Flo

### With which model does the problem occur?

Deebot T8 series

### From which source you have installed the adapter?

GitHub

### Version of the ioBroker adapter ("info.version")

1.3.5-alpha.1

### Version of the ecovacs-deebot.js library ("info.library.version")

0.8.0-alpha.5

### Version of the JS controller

3.3.22

### Version of Node.js

v14.19.0

### Operating system

Windows

### Ecovacs device class ("info.deviceClass")

h18jkh

### Communication protocol ("info.library.communicationProtocol")

MQTT

### Is the canvas module installed? ("info.library.canvasModuleIsInstalled")

yes (true)

**Comment by mrbungle64** [comment]
@pansenerna 

Hallo Flo,

dann wird das leider nicht funktionieren mit deinem Modell.
Ich kenne bisher auch leider nur wenige Modelle, wo das funktioniert (OZMO 930, Deebot 710) - daher muss man das auch extra in den Adapter Einstellungen aktivieren.

Ich muss das in den Einstellungen mal besser kennzeichnen 😉

**Comment by mrbungle64** [comment]
Wenn du möchtest kannst du dir mal die Library installieren und dann schauen, ob der Bot was sendet wenn die Dustbox ein- und ausgesetzt wird.

https://github.com/mrbungle64/ecovacs-deebot.js/wiki/Example-apps

```bash
cd example
NODE_ENV=dev node ./app2.js
```

**Comment by pansenerna** [comment]
@mrbungle64 

Ich weiß nicht, ob ich alles richtig gemacht habe, aber ich konnte auf der Console Eingaben sehen und auch mit einem App-Befehl (TrueDetect On/Off verifizieren) --> d.h. der Output sollte passen.

Ich bekomme folgendes angezeigt:

Roboter steht in Ladestation:

Staubbehälter entnehmen:
`[EcovacsMQTT_JSON] Unknown command received: onFwBuryPoint`

Staubbehälter wieder einsetzen:
`[EcovacsMQTT_JSON] Unknown command received: onFwBuryPoint
[VacBot] *** errorCode = 0
[VacBot] *** errorDescription = NoError: Robot is operational
Error: NoError: Robot is operational
[VacBot] *** currentSpotAreaID = void
[VacBot] *** deebotPosition = {"x":-550,"y":50,"a":179,"isInvalid":false,"currentSpotAreaID":"void","currentSpotAreaName":"unknown","changeFlag":true,"distanceToChargingStation":0.1}
DeebotPosition: -550,50,179
CurrentSpotAreaID: void
[VacBot] Sending command `getSleep` with id 10422313
[VacBot] Sending command `getWaterInfo` with id 01107957
[VacBot] Sending command `getSpeed` with id 85620535
[VacBot] Sending command `getVolume` with id 75626852
[VacBot] Sending command `getAdvancedMode` with id 27005376
[EcovacsMQTT] got {"ret":"ok","resp":{"header":{"pri":1,"tzm":480,"ts":"1650108368896","ver":"0.0.1","fwVer":"1.7.1","hwVer":"0.1.1"},"body":{"code":0,"msg":"ok","data":{"total":10,"volume":0}}},"id":"X2RB"}
[VacBot] *** volume = 0
Volume: 0
[EcovacsMQTT] got {"ret":"ok","resp":{"header":{"pri":1,"tzm":480,"ts":"1650108368899","ver":"0.0.1","fwVer":"1.7.1","hwVer":"0.1.1"},"body":{"code":0,"msg":"ok","data":{"enable":0,"amount":1,"type":0,"sweepType":1}}},"id":"BgxN"}
[VacBot] *** waterboxInfo = 0
[VacBot] *** waterLevel = 1
waterBoxInfo: 0
water level: 1
[EcovacsMQTT] got {"ret":"ok","resp":{"header":{"pri":1,"tzm":480,"ts":"1650108368932","ver":"0.0.1","fwVer":"1.7.1","hwVer":"0.1.1"},"body":{"code":0,"msg":"ok","data":{"speed":1000}}},"id":"aeDz"}
[VacBot] *** cleanSpeed = 1
CleanSpeed: 1
[EcovacsMQTT] got {"ret":"ok","resp":{"header":{"pri":1,"tzm":480,"ts":"1650108368954","ver":"0.0.1","fwVer":"1.7.1","hwVer":"0.1.1"},"body":{"data":{"enable":1},"code":0,"msg":"ok"}},"id":"WmDq"}
[VacBot] *** advancedMode = 1
[EcovacsMQTT] got {"ret":"ok","resp":{"header":{"pri":1,"tzm":480,"ts":"1650108368972","ver":"0.0.1","fwVer":"1.7.1","hwVer":"0.1.1"},"body":{"code":0,"msg":"ok","data":{"enable":0}}},"id":"li0w"}
[VacBot] *** sleepStatus = 0
`

Vielleicht kannst du damit etwas anfangen.


Kann ich die Lib einfach so "installiert" lassen, oder ist da mit Querwirkungen zu rechnen. Habe vorher einen Snapshot des Containers gemacht und könnte zur Not reverten.

Grüße,
Flo

**Comment by mrbungle64** [comment]
@pansenerna 

`onFwBuryPoint` kannte ich schon. Das scheint eine Ansammlung von Debug Messages zu sein. Ich bin mir nicht mal sicher, ob das Absicht ist, dass die gesendet werden 😉  Wenn man "(on) bury point" übersetzt kommt da was wenig ernst zunehmendes bei raus 😉  Eine Info zur Dustbox habe ich da bisher auch noch nicht drin finden können.

> Kann ich die Lib einfach so "installiert" lassen, oder ist da mit Querwirkungen zu rechnen

Nein, so lange du das nach Anleitung gemacht hast, ist das eine autarke Installation. Auf den ioBroker hätte es nur eine Auswirkung, wenn du das `ecovacs-deebot` Verzeichnis unterhalb vom `node_modules` Verzeichnis im ioBroker Verzeichnis überschrieben hättest.

**Comment by pansenerna** [comment]
@mrbungle64 

Ok, schade, aber habe ich mir bei diesem log schon fast gedacht.

Falls ich ansonsten diesbezüglich nochmal was mitloggen kann, einfach Bescheid sagen.

**Comment by benep** [comment]
Hallo zusammen,

das Issue ist leider irgendwie an mir vorbei gegangen. Ich habe aber auch gerade ein Problem damit. Allerdings muss das in zwei Teile aufgeteilt werden.

1. Die Fehlererkennung
Die Fehler wurden bisher vom Adaper richtig erkannt und bei Nummer 110 wurde auch korrekt der `dateOfLastTimeDustboxRemoved` Wert aktualisiert. Diese Fehler werden auch in der App von Ecovacs angezeigt. Allerdings wurde das nur ausgelöst, wenn man während einer Reinigung die Box aus dem T8 zieht. Das habe ich jetzt ewig so verwendet und mir eine Funktion gebaut, die mich anhand von dem Wert auch noch die Reinigungs-Dauer und Reinigungs-m2 seit dem Remove errechnet und dann erinnert die Box zu leeren. Wichtig: Das funktioniert seit dem letzten Update seit paar Tagen leider nicht mehr, weil der Wert nicht upgedated wird.

2. Die onFwBuryPoints
Das hatten wir in #101 schon mal analysiert. Darin wird neben viel anderem auch der Fehler 110 ausgegeben (https://github.com/mrbungle64/ioBroker.ecovacs-deebot/issues/101#issuecomment-739852983), egal was der Roboter gerade macht, solage er verbunden ist. Diese Fehler werden nicht in der offiziellen App angezeigt. In dem Event stecken noch super viel mehr Infos, die man künftig auch abfangen und nutzen könnte. https://github.com/mrbungle64/ioBroker.ecovacs-deebot/issues/101#issuecomment-745477675

Es wäre super, wenn zumindest der Weg über 1. wieder funktioniert, wie in der Vorversion. Wenn @mrbungle64 die onFwBuryPoints auch noch abfangen würde und darüber zusätzlich die Fehler an die bestehen Fehler-Message-Funktion übergibt wäre das natürlich ein Traum.

**Comment by mrbungle64** [comment]
> Hallo zusammen,

Hallo @benep 

> 
> das Issue ist leider irgendwie an mir vorbei gegangen. Ich habe aber auch gerade ein Problem damit. Allerdings muss das in zwei Teile aufgeteilt werden.
> 
> 1. Die Fehlererkennung
>    Die Fehler wurden bisher vom Adaper richtig erkannt und bei Nummer 110 wurde auch korrekt der `dateOfLastTimeDustboxRemoved` Wert aktualisiert. Diese Fehler werden auch in der App von Ecovacs angezeigt. Allerdings wurde das nur ausgelöst, wenn man während einer Reinigung die Box aus dem T8 zieht. Das habe ich jetzt ewig so verwendet und mir eine Funktion gebaut, die mich anhand von dem Wert auch noch die Reinigungs-Dauer und Reinigungs-m2 seit dem Remove errechnet und dann erinnert die Box zu leeren. Wichtig: Das funktioniert seit dem letzten Update seit paar Tagen leider nicht mehr, weil der Wert nicht upgedated wird.

Sorry, das hatte ich in einem unbedachten Moment ausgebaut (weil es bei mir nicht funktioniert hat).
Ich habe es gerade wieder eingebaut 😉 

> 2. Die onFwBuryPoints
>    Das hatten wir in [Dustbox Auslastung in % #101](https://github.com/mrbungle64/ioBroker.ecovacs-deebot/issues/101) schon mal analysiert. Darin wird neben viel anderem auch der Fehler 110 ausgegeben ([Dustbox Auslastung in % #101 (comment)](https://github.com/mrbungle64/ioBroker.ecovacs-deebot/issues/101#issuecomment-739852983)), egal was der Roboter gerade macht, solage er verbunden ist. Diese Fehler werden nicht in der offiziellen App angezeigt. In dem Event stecken noch super viel mehr Infos, die man künftig auch abfangen und nutzen könnte. [Dustbox Auslastung in % #101 (comment)](https://github.com/mrbungle64/ioBroker.ecovacs-deebot/issues/101#issuecomment-745477675)

`onFwBuryPoint` kann ich mir in nächster Zeit mal genauer anschauen, da mir in ein paar Tagen voraussichtlich ein T8 zur Verfügung steht.

> 
> Es wäre super, wenn zumindest der Weg über 1. wieder funktioniert, wie in der Vorversion. Wenn @mrbungle64 die onFwBuryPoints auch noch abfangen würde und darüber zusätzlich die Fehler an die bestehen Fehler-Message-Funktion übergibt wäre das natürlich ein Traum.

_"und darüber zusätzlich die Fehler an die bestehen Fehler-Message-Funktion übergibt"_
Was meinst du damit genau?

**Comment by benep** [comment]
> Sorry, das hatte ich in einem unbedachten Moment ausgebaut (weil es bei mir nicht funktioniert hat).
> Ich habe es gerade wieder eingebaut 

Super, vielen Dank.

> "und darüber zusätzlich die Fehler an die bestehen Fehler-Message-Funktion übergibt"
> Was meinst du damit genau?

Ohne den Code geprüft zu haben, denke ich, dass du eine Handler für die Fehlercodes hast. In `onFwBuryPoint `gibt es verschiedene möglich Returns. Eins davon sind die Error Codes, die du dann vermutlich einfach an den bestehenden Handler weitergeben kannst, weil die Fehlernummern gleich sind.

Beispiel für Dustbox: command = onFwBuryPoint, rn = bd_errorcode, code = 110, state = 0

War allerdings nur ne Vermutung.

**Comment by benep** [comment]
> Sorry, das hatte ich in einem unbedachten Moment ausgebaut (weil es bei mir nicht funktioniert hat).
Ich habe es gerade wieder eingebaut 😉

Hab grad die Alpha ausprobiert und es funktioniert wieder wie erwartet. Vielen Dank!

> onFwBuryPoint kann ich mir in nächster Zeit mal genauer anschauen, da mir in ein paar Tagen voraussichtlich ein T8 zur Verfügung steht.

Ich bin gespannt was du draus machst. Sind ja wirklich viele Infos drinnen.

**Comment by mrbungle64** [comment]
@benep @pansenerna 

Mit der Version 1.4.2 (heute in Latest/Beta released) wird nun `onFwBuryPoint` für Dustbox Removed verwendet.

Einige andere Zustände im ioBroker sollten sich nun auch durch Verwendung von `onFwBuryPoint` ad hoc ändern, wenn z.B. die Wasserstärke in der App verändert wurde. Da bin ich aber noch am optimieren 😉

**Comment by pansenerna** [comment]
@mrbungle64 

Super, danke.
Gerade mal getestet. Der Wert von Dustbox (true/false) funktioniert gut (entfernen des Behälters, beim Laden, reinigen und pausiert).

date-/ und timestamp-/ OfLastTimeDustboxRemoved wird nur aktualisiert, wenn man dem T8 **während** der Reinigung den Behälter entfernt. Sobald er pausiert ist, oder in der Ladestation steht, wird dieser Wert nicht aktualisiert.

**Comment by mrbungle64** [comment]
@pansenerna 

> @mrbungle64
> 
> Super, danke. Gerade mal getestet. Der Wert von Dustbox (true/false) funktioniert gut (entfernen des Behälters, beim Laden, reinigen und pausiert).
> 
> date-/ und timestamp-/ OfLastTimeDustboxRemoved wird nur aktualisiert, wenn man dem T8 **während** der Reinigung den Behälter entfernt. Sobald er pausiert ist, oder in der Ladestation steht, wird dieser Wert nicht aktualisiert.

Fehler ist (mit der aktuellen GitHub Version) behoben 😉

**Comment by benep** [comment]
Sehr schön!

Ich habe das vorher mit der 1.4.2 auch getestet, allerdings nur den true/false Wert. Das hat perfekt funktioniert. Super, dass du das eingebaut hast. Damit wird mein Dusbox-Reminder immer praktikabler. Und ohne dich drängen zu wollen, eine kleine Anregung wie ich es weiter umgesetzt habe.

Ich habe jetzt noch ein Script, das wenn `ecovacs-deebot.0.cleaninglog.lastSquareMeters` aktualisiert wird folgende Werte schreibt bzw. erhöht.

`ecovacs-deebot.0.history.cleaningsSinceLastDustboxRemoved`
`ecovacs-deebot.0.history.m2SinceLastDustboxRemoved`
`ecovacs-deebot.0.history.secondsSinceLastDustboxRemoved`
`ecovacs-deebot.0.history.timeSinceLastDustboxRemoved`

Wenn die Dustbox entfernt wird, dann werden alle wieder auf 0 gesetzt.

Übrigens gibt es unter `ecovacs-deebot.0.cleaninglog` die Werte `currentSeconds `und `totalSeconds`, aber keine `lastSeconds`. Das kann man zwar errechnen, aber wäre noch eine logische Ergänzung. Ich brauch die Sekunden für die Berechnung der Werte oben, muss die aber momentan aus dem timeString berechnen.

**Comment by mrbungle64** [comment]
@benep 

> Sehr schön!

Zuerst natürlich danke für das Feedback 👍🏻 

> 
> Ich habe das vorher mit der 1.4.2 auch getestet, allerdings nur den true/false Wert. Das hat perfekt funktioniert. Super, dass du das eingebaut hast. Damit wird mein Dusbox-Reminder immer praktikabler. Und ohne dich drängen zu wollen, eine kleine Anregung wie ich es weiter umgesetzt habe.
> 
> Ich habe jetzt noch ein Script, das wenn `ecovacs-deebot.0.cleaninglog.lastSquareMeters` aktualisiert wird folgende Werte schreibt bzw. erhöht.
> 
> `ecovacs-deebot.0.history.cleaningsSinceLastDustboxRemoved` `ecovacs-deebot.0.history.m2SinceLastDustboxRemoved` `ecovacs-deebot.0.history.secondsSinceLastDustboxRemoved` `ecovacs-deebot.0.history.timeSinceLastDustboxRemoved`

Bitte keine selbst erstellten Datenpunkte in die Kanäle der Adapter packen!
Das geht zwar i.d.R. - kann aber u.U. Probleme bereiten - vor allem durch die Skripte welche die Datenpunkte beschreiben.
Die gehören aber unabhängig davon einfach nicht dahin. Für solche Zwecke gibt es im ioBroker den "0_userdata" Kanal ...

> 
> Wenn die Dustbox entfernt wird, dann werden alle wieder auf 0 gesetzt.

Kannst du bitte das Skript posten (oder mir per Mail schicken)?

> 
> Übrigens gibt es unter `ecovacs-deebot.0.cleaninglog` die Werte `currentSeconds `und `totalSeconds`, aber keine `lastSeconds`. Das kann man zwar errechnen, aber wäre noch eine logische Ergänzung. Ich brauch die Sekunden für die Berechnung der Werte oben, muss die aber momentan aus dem timeString berechnen.

Du meinst "cleaninglog.lastTotalTimeString" in Sekunden umgerechnet?

**Comment by benep** [comment]
> Du meinst "cleaninglog.lastTotalTimeString" in Sekunden umgerechnet?

Ja genau.

> Kannst du bitte das Skript posten (oder mir per Mail schicken)?

Gerne, hoffe du kannst was damit anfangen. Sonst einfach fragen. Die zwei Helper-Funktionen oben brauchst du wahrscheinlich nicht, die sind nur zur Umrechnung. Und "Leerung anfordern" kannst du ignorieren.

```
var timeString, seconds, minutes, hours;

// Beschreibe diese Funktion …
async function toSeconds(timeString) {
  seconds = parseFloat((timeString.slice(7, 9)));
  minutes = parseFloat((timeString.slice(3, 5)));
  hours = parseFloat((timeString.slice(0, 1)));
  seconds = (typeof seconds == 'number' ? seconds : 0) + parseFloat(minutes) * 60;
  seconds = (typeof seconds == 'number' ? seconds : 0) + parseFloat(hours) * 3600;
  return seconds;
}

// Beschreibe diese Funktion …
async function s2hms(seconds) {
    var seconds = parseInt(seconds, 10)
    var h = Math.floor(seconds / 3600);
    seconds %= 3600;
    var m = Math.floor(seconds / 60);
    var s = seconds % 60;
    return h + 'h ' + m + 'm ' + s + 's';
}

// Dustbox ausleeren
on({id: "ecovacs-deebot.0.history.timestampOfLastTimeDustboxRemoved"/*Timestamp of last time dustbox was removed*/, change: "ne", ack: true}, async function (obj) {
  setState("ecovacs-deebot.0.history.cleaningsSinceLastDustboxRemoved"/*cleaningsSinceLastDustboxRemoved*/, 0, true);
  setState("ecovacs-deebot.0.history.m2SinceLastDustboxRemoved"/*m2SinceLastDustboxRemoved*/, 0, true);
  setState("ecovacs-deebot.0.history.secondsSinceLastDustboxRemoved"/*secondsSinceLastDustboxRemoved*/, 0, true);
  setState("ecovacs-deebot.0.history.timeSinceLastDustboxRemoved"/*timeSinceLastDustboxRemoved*/, (await s2hms(0)), true);
});

// Reinigung abgeschlossen
on({id: "ecovacs-deebot.0.cleaninglog.lastSquareMeters"/*Total square meters of the last cleaning*/, change: "ne", ack: true}, async function (obj) {
  seconds = await toSeconds(getState("ecovacs-deebot.0.cleaninglog.lastTotalTimeString").val);
  if (seconds > 100) {
    setState("ecovacs-deebot.0.history.cleaningsSinceLastDustboxRemoved"/*cleaningsSinceLastDustboxRemoved*/, (parseFloat(getState("ecovacs-deebot.0.history.cleaningsSinceLastDustboxRemoved").val) + 1), true);
  }
  seconds = (typeof seconds == 'number' ? seconds : 0) + getState("ecovacs-deebot.0.history.secondsSinceLastDustboxRemoved").val;
  setState("ecovacs-deebot.0.history.secondsSinceLastDustboxRemoved"/*secondsSinceLastDustboxRemoved*/, seconds, true);
  setState("ecovacs-deebot.0.history.timeSinceLastDustboxRemoved"/*timeSinceLastDustboxRemoved*/, (await s2hms(seconds)), true);
  setState("ecovacs-deebot.0.history.m2SinceLastDustboxRemoved"/*m2SinceLastDustboxRemoved*/, (parseFloat(getState("ecovacs-deebot.0.history.m2SinceLastDustboxRemoved").val) + (obj.state ? obj.state.val : "")), true);
});

// Leerung anfordern
on({id: "ecovacs-deebot.0.status.device"/*Device status*/, change: "ne", ack: true}, async function (obj) {
  if ((obj.state ? obj.state.val : "") == 'returning') {
    if (getState("ecovacs-deebot.0.history.m2SinceLastDustboxRemoved").val > 120) {
      console.log((['Leerung bald fällig! Aktuel: ',getState("ecovacs-deebot.0.history.m2SinceLastDustboxRemoved").val,'m²'].join('')));
      setState("ecovacs-deebot.0.control.playSoundId"/*Play sound by id of the message*/, 172);
      if (getState("ecovacs-deebot.0.history.m2SinceLastDustboxRemoved").val > 150 && getState("ecovacs-deebot.0.map.deebotDistanceToChargePosition").val < 1) {
        console.log((['Leerung sofort fällig! Aktuel: ',getState("ecovacs-deebot.0.history.m2SinceLastDustboxRemoved").val,'m²'].join('')));
        if (!getState("ecovacs-deebot.0.map.deebotPositionIsInvalid").val) {
          setState("ecovacs-deebot.0.control.extended.goToPosition"/*Go to position*/, '600,-4000');
        } else {
          console.log('Leerung nicht möglich, da Position ungültig!');
        }
      }
    }
  }
});
```

**Comment by mrbungle64** [comment]
@benep 

> Übrigens gibt es unter ecovacs-deebot.0.cleaninglog die Werte currentSeconds und totalSeconds, aber keine lastSeconds. Das kann man zwar errechnen, aber wäre noch eine logische Ergänzung. Ich brauch die Sekunden für die Berechnung der Werte oben, muss die aber momentan aus dem timeString berechnen.

Der Datenpunkt "cleaninglog.lastTotalSeconds" ist jetzt da 😉

**Comment by mrbungle64** [comment]
@benep 

In folgendem branch habe ich das implementiert (das ist die Version 1.4.4 + diese Funktionalität):
https://github.com/mrbungle64/ioBroker.ecovacs-deebot/tree/alpha/1.4.5
(Achtung die Installation per GitHub URL dauert aktuell sehr lange)

Die Datenpunkte habe ich aber bis auf "history.cleaningsSinceLastDustboxRemoved" anders benannt.
Vielleicht kannst du es ja mal parallel zu deinem Skript laufen lassen 😉

**Comment by benep** [comment]
Cool, ich installiere es grad.

Tatsächlich warte ich auf Änderungen. Also gleiche Fläche, keine Erhöhung.

Spontan könnte ich mir aber vorstellen, dass das mit dem `cleaninglog.lastCleaningTimestamp` als Auslöser gehen müsste. Der muss sich ja auch bei gleicher Fläche ändern.

Sonst hab ich noch die 100 Sekunden als Zeitsperre für Anzahl der Cleanings drin. Sonst werden beispielsweise die GoTos mitgezählt. Vielleicht wäre da der 'Schwellenwert für die "Letzte Anwesenheit"' als Zahl nicht schlecht.

**Comment by mrbungle64** [comment]
> Cool, ich installiere es grad.
> 
> Tatsächlich warte ich auf Änderungen. Also gleiche Fläche, keine Erhöhung.
> 
> Spontan könnte ich mir aber vorstellen, dass das mit dem `cleaninglog.lastCleaningTimestamp` als Auslöser gehen müsste. Der muss sich ja auch bei gleicher Fläche ändern.

Ja, so was in der Art müsste funktionieren.

> 
> Sonst hab ich noch die 100 Sekunden als Zeitsperre für Anzahl der Cleanings drin. Sonst werden beispielsweise die GoTos mitgezählt. Vielleicht wäre da der 'Schwellenwert für die "Letzte Anwesenheit"' als Zahl nicht schlecht.

Hab ich bereits verwendet 😃

**Comment by mrbungle64** [comment]
@benep 

Ich habe nun noch mal ein paar Verbesserungen eingebaut - habe aber (erst mal) den Datenpunkt "cleaningsSinceLastDustboxRemoved" entfernt, weil das zu viel Ärger gemacht hat (wenn es möglichst exakt stimmen soll).

Es werden aktuell folgende Datenpunkte behandelt:
- "history.cleaningTimeSinceLastDustboxRemoved"
- "history.cleaningTimeSinceLastDustboxRemovedString"
- "history.squareMetersSinceLastDustboxRemoved"

Dabei wird nun immer jeweils der Diff zum vorherigen Wert bei Änderung von "cleaninglog.current.cleanedArea" und "cleaninglog.current.cleanedSeconds" hochgezählt. Bedeutet, dass man nun (hoffentlich) die exakte Anzahl jeweils bekommt - auch wenn man z.B. mitten im Reinigungsvorgang den Staubbehälter leert.

Verfügbar wieder über den gleichen [branch](https://github.com/mrbungle64/ioBroker.ecovacs-deebot/tree/alpha/1.4.5).

**Comment by mrbungle64** [comment]
@benep 

> Cool, ich installiere es grad.

Gibt es auch Feedback dazu? 😉

**Comment by mrbungle64** [comment]
@pansenerna 
Ich schließe den Issue nun, da ich davon ausgehe, dass das Problem "Deebot T8 - Dustbox Removed" gelöst ist.

@benep 
Die Funktion für die Datenpunkte "history.[...]SinceLastDustboxRemoved" ist im aktuellen Branch enthalten und kann getestet werden. Falls es damit Probleme gibt bitte ich um einen separaten Issue.
