### ISSUE TITLE
Wechsel von 0.4.2 auf 0.5.1 - Keine Funktionen mehr möglich (Deebot 710)

### ISSUE THREAD

**Issue by capitaenz** [mrbungle64/ioBroker.ecovacs-deebot#28]
Ich habe heute den Adapter auf die neue Version aktualisiert und kann keine Reinigung mehr starten mit dem Deebot 710.
Wenn ich per App vom Handy eine Reinigung starte, dann geht der Adapter auf rot und startet neu.

> 

ecovacs-deebot.0 | 2020-03-02 09:58:16.522 | info | (26708) [vacbot] name: DEEBOT 710
-- | -- | -- | --
ecovacs-deebot.0 | 2020-03-02 09:58:16.520 | info | (26708) DEEBOT_710 successfully connected
ecovacs-deebot.0 | 2020-03-02 09:58:14.776 | info | (26708) Using device Device[0]
ecovacs-deebot.0 | 2020-03-02 09:58:14.775 | info | (26708)  Device[0]:  {"did":"73405b80-1bb8-4795-8fef-56474167db2d","name":"E0001209318604870530","class":"uv242z","resource":"uYyu","nick":"DEEBOT_710","company":"eco-ng","bindTs":1568983549228}
ecovacs-deebot.0 | 2020-03-02 09:58:14.775 | info | (26708) Number of devices: 1
ecovacs-deebot.0 | 2020-03-02 09:58:14.773 | info | (26708) Successfully connected to Ecovacs server
ecovacs-deebot.0 | 2020-03-02 09:58:13.358 | info | (26708) reconnecting (5) ...
ecovacs-deebot.0 | 2020-03-02 09:58:07.079 | info | (26708) reconnecting (4) ...
ecovacs-deebot.0 | 2020-03-02 09:58:00.806 | info | (26708) reconnecting (3) ...
ecovacs-deebot.0 | 2020-03-02 09:57:54.475 | info | (26708) reconnecting (2) ...
ecovacs-deebot.0 | 2020-03-02 09:57:48.192 | info | (26708) reconnecting (1) ...
ecovacs-deebot.0 | 2020-03-02 09:57:41.781 | info | (26708) starting. Version 0.5.1 in /opt/iobroker/node_modules/iobroker.ecovacs-deebot, node: v10.19.0
ecovacs-deebot.0 | 2020-03-02 09:57:09.875 | info | (24062) Terminated (NO_ERROR): Without reason
ecovacs-deebot.0 | 2020-03-02 09:57:09.874 | info | (24062) terminating
ecovacs-deebot.0 | 2020-03-02 09:57:09.864 | info | (24062) cleaned everything up...
ecovacs-deebot.0 | 2020-03-02 09:57:09.860 | error | at writeOrBuffer (/opt/iobroker/node_modules/readable-stream/lib/_stream_writable.js:417:5)
ecovacs-deebot.0 | 2020-03-02 09:57:09.860 | error | at doWrite (/opt/iobroker/node_modules/readable-stream/lib/_stream_writable.js:428:64)
ecovacs-deebot.0 | 2020-03-02 09:57:09.860 | error | at Writable.writable._write (/opt/iobroker/node_modules/iobroker.ecovacs-deebot/node_modules/mqtt/lib/client.js:294:5)
ecovacs-deebot.0 | 2020-03-02 09:57:09.860 | error | at work (/opt/iobroker/node_modules/iobroker.ecovacs-deebot/node_modules/mqtt/lib/client.js:283:12)
ecovacs-deebot.0 | 2020-03-02 09:57:09.860 | error | at MqttClient._handlePacket (/opt/iobroker/node_modules/iobroker.ecovacs-deebot/node_modules/mqtt/lib/client.js:351:12)
ecovacs-deebot.0 | 2020-03-02 09:57:09.860 | error | at MqttClient._handlePublish (/opt/iobroker/node_modules/iobroker.ecovacs-deebot/node_modules/mqtt/lib/client.js:1162:12)
ecovacs-deebot.0 | 2020-03-02 09:57:09.860 | error | at MqttClient.emit (events.js:198:13)
ecovacs-deebot.0 | 2020-03-02 09:57:09.860 | error | at MqttClient.EcovacsMQTT.client.on  (/opt/iobroker/node_modules/iobroker.ecovacs-deebot/node_modules/ecovacs-deebot/library/ecovacsMQTT.js:82:18)
ecovacs-deebot.0 | 2020-03-02 09:57:09.860 | error | at EcovacsMQTT._handle_message  (/opt/iobroker/node_modules/iobroker.ecovacs-deebot/node_modules/ecovacs-deebot/library/ecovacsMQTT.js:296:28)
ecovacs-deebot.0 | 2020-03-02 09:57:09.860 | error | at EcovacsMQTT._message_to_dict  (/opt/iobroker/node_modules/iobroker.ecovacs-deebot/node_modules/ecovacs-deebot/library/ecovacsMQTT.js:315:9)
ecovacs-deebot.0 | 2020-03-02 09:57:09.860 | error | (24062) ReferenceError: xml is not defined
ecovacs-deebot.0 | 2020-03-02 09:57:09.859 | error | (24062) uncaught exception: xml is not defined

Musste den Adapter nun löschen, da es sich ständig neu verbunden hat...

**Comment by mrbungle64** [comment]
> Ich habe heute den Adapter auf die neue Version aktualisiert und kann keine Reinigung mehr starten mit dem Deebot 710.
> Wenn ich per App vom Handy eine Reinigung starte, dann geht der Adapter auf rot und startet neu.

Hallo @capitaenz 

sorry, es hatten sich für MQTT Geräte (welche ich ja nicht selbst testen kann) leider 2 Fehler eingeschlichen - beide sollten mit dem nächsten Update behoben sein.

Ich sage bescheid, wenn die neue Version veröffentlicht wurde.

**Comment by capitaenz** [comment]
gibt es eine Möglichkeit auf die alte Verison zurück zu kommen?
Ich kann die alten Versionen per .zip laden, aber ich ich hätte gerne einen link, damit ich dies nicht umständlich über das Dateisystem machen muss.

**Comment by mrbungle64** [comment]
@capitaenz 
> gibt es eine Möglichkeit auf die alte Verison zurück zu kommen?
> Ich kann die alten Versionen per .zip laden, aber ich ich hätte gerne einen link, damit ich dies nicht umständlich über das Dateisystem machen muss.

Das wird hier in dem Screencast gezeigt:
https://www.iobroker.net/docu/index-23.htm?page_id=8511&lang=de#Downgrade_eines_Adapters

Falls Du das gerade machen möchtest könnte ich noch alternativ anbieten, dass ich jetzt direkt einen Release mit dem Bugfix mache - würde ungefähr 30 Min. dauern.

**Comment by capitaenz** [comment]
Ist nicht lebenswichtig, aber danke =) Starte dann eben heute per Hand

**Comment by capitaenz** [comment]
nur als Info, klappt nicht:

$ ./iobroker upgrade ecovacs-deebot@0.4.2
Adapter "ecovacs-deebot" is not in the repository and cannot be updated.
process exited with code 0

**Comment by mrbungle64** [comment]
> nur als Info, klappt nicht:
> 
> $ ./iobroker upgrade ecovacs-deebot@0.4.2
> Adapter "ecovacs-deebot" is not in the repository and cannot be updated.
> process exited with code 0
@capitaenz 
Sorrry, mein Fehler ...

Ich habe jetzt die Version 0.5.2 auf GitHub released - da sollten die o.g. Probleme behoben sein.
Ebenfalls ist auch die Liste der verfügbaren älteren Versionen aufgeräumt.

**Comment by capitaenz** [comment]
@mrbungle64 
Stürzt nicht mehr ab und hab mal kurz auf cleam und stop gedrückt (im Adapter) und dies klappt auch wieder!
Danke!

**Comment by mrbungle64** [comment]
@capitaenz 
Sehr gut! Danke für die schnelle Rückmeldung :+1:
