### ISSUE TITLE
Info ok but no control with Ozmo 950

### ISSUE THREAD

**Issue by Wox1** [mrbungle64/ioBroker.ecovacs-deebot#3]
Hello,

thanks for the adaper for the Ecovacs Deebot series. I have the Ozmo 950. Under Adapter all lights  green. Under Instans i have Infos and so on, but the control don't work. If i press the start clean button nothing happens? Have you an Idee what the problem?

Sincerely
Wox

**Comment by mrbungle64** [comment]
Thanks for your feedback :)

> Under Adapter all lights green.

The status green indicates that the adapter is connected to the cloud.

> If i press the start clean button nothing happens? Have you an Idee what the problem?

The adapter uses the library [sucks.js](https://github.com/joostth/sucks.js). This library currently [doesn't support the D900-series](https://github.com/ioBroker/AdapterRequests/issues/76#issuecomment-559780463). Maybe there's only the option but to create a fork.

Do the states 'info.cleanstatus' and 'info.chargestatus' display correct information when you control the device app/manually?

**Comment by Wox1** [comment]
Hello,
there is no value by info.cleanstatus  and no by chargestatus.
info.connection = true
info.devicename = DEEBOT OZMO 950 Series
I don't know that 950 is not suported. :(
Thanks for Infos

**Comment by Wox1** [comment]
Kurze Frage noch dazu:
Ist mal in absehbarer Zeit geplant den 950 zu integrieren, oder funktioniert das generell nicht?
Falls ich mit etwas helfen kann....

Gruß

**Comment by mrbungle64** [comment]
Grundsätzlich wäre das schon das Ziel - es ist nur nicht ganz so einfach ;)

Stand jetzt unterstützt die verwendete Bibliothek (sucks.js) dieses Modell nicht. Für die offizielle API ist keine öffentlich zugängliche Dokumentation verfügbar und ich habe auch persönlich auch keinen Deebot Ozmo 950 hier, um gezielt daran arbeiten zu können.

Aktuell habe ich hier einen Deebot Slim 2 - welcher einen eher überschaubaren Funktionsumfang hat - und einen Xiaomi Roborock 1st Gen.
Den Slim 2 möchte ich möglichst bald durch den Roborock ersetzen und den Roborock dann durch einen Saugwischrobotor - wo dann der Deebot Ozmo 950 in der engeren Auswahl käme. Bis dahin habe ich aber nur eingeschränkte Möglichkeiten.

Plan für die nächsten Tage ist es erst mal das Logging soweit zu erweitern, dass man mir mehr Infos bereitsstellen kann welche Events bei den anderen Modellen ausgelöst - aber nicht (korrekt) behandelt werden.

**Comment by mrbungle64** [comment]
Hallo @Wox1,

ich schließe diesen Issue als 'duplicate'. [Dieser Issue](https://github.com/mrbungle64/ioBroker.ecovacs-deebot/issues/7) ist zwar der neuere, aber dort ist inzwischen einiges an Informationen zusammen gekommen. Wir setzen das dann dort fort.
