### ISSUE TITLE
Image Url not shown in objects

### ISSUE THREAD

**Issue by mmeglitsch** [mrbungle64/ioBroker.ecovacs-deebot#302]
### Is there an existing issue for this?

- [X] I have searched the existing issues and no issue is describing my issue

### The problem

There should be a data point called cleaninglog.lastCleaningMapImageURL

I am using iobroker adapter with all options active and deebot 930, but I can't find this data point. Map is being displayed correctly at the original app. 

### With which model does the problem occur?

Deebot OZMO 930

### From which source you have installed the adapter?

Stable (default)

### Version of the ioBroker adapter ("info.version")

1.4.0

### Version of the ecovacs-deebot.js library ("info.library.version")

1.4.0

### Version of the JS controller

4.0.23

### Version of Node.js

latest

### Operating system

Windows

**Comment by mrbungle64** [comment]
@mmeglitsch 

The "lastCleaningMapImageURL" is the latest url of the cleaning log (see also "cleaninglog.last20Logs").

Unfortunately there's no image in the cleaning log of the OZMO 930.
You can also see this in the Ecovacs mobile app.

**Comment by mmeglitsch** [comment]
@mrbungle64 
there is no such Url in the "cleaninglog.last20Logs"

`[{"timestamp":1653553815,"date":"2022-05-26T08:30:15.000Z","lastTime":2330,"totalTime":2330,"totalTimeString":"0h 38m 50s","totalTimeFormatted":"0h 38m 50s","squareMeters":32,"stopReason":"clean_successful","trigger":"schedule_from_app"},{"timestamp":1653467415,"date":"2022-05-25T08:30:15.000Z","lastTime":5080,"totalTime":5080,"totalTimeString":"1h 24m 40s","totalTimeFormatted":"1h 24m 40s","squareMeters":54,"trigger":"schedule_from_app"},{"timestamp":1653391473,"date":"2022-05-24T11:24:33.000Z","lastTime":297,"totalTime":297,"totalTimeString":"0h 04m 57s","totalTimeFormatted":"0h 04m 57s","squareMeters":5,"stopReason":"stopped_by_app","trigger":"app"},{"timestamp":1653381015,"date":"2022-05-24T08:30:15.000Z","lastTime":1728,"totalTime":1728,"totalTimeString":"0h 28m 48s","totalTimeFormatted":"0h 28m 48s","squareMeters":32,"stopReason":"clean_successful","trigger":"schedule_from_app"},{"timestamp":1653294615,"date":"2022-05-23T08:30:15.000Z","lastTime":1909,"totalTime":1909,"totalTimeString":"0h 31m 49s","totalTimeFormatted":"0h 31m 49s","squareMeters":33,"stopReason":"clean_successful","trigger":"schedule_from_app"},{"timestamp":1653280117,"date":"2022-05-23T04:28:37.000Z","lastTime":4125,"totalTime":4125,"totalTimeString":"1h 08m 45s","totalTimeFormatted":"1h 08m 45s","squareMeters":61,"stopReason":"clean_successful","trigger":"app"},{"timestamp":1653280110,"date":"2022-05-23T04:28:30.000Z","lastTime":4,"totalTime":4,"totalTimeString":"0h 00m 04s","totalTimeFormatted":"0h 00m 04s","squareMeters":0,"stopReason":"stopped_by_app","trigger":"app"},{"timestamp":1652949015,"date":"2022-05-19T08:30:15.000Z","lastTime":1904,"totalTime":1904,"totalTimeString":"0h 31m 44s","totalTimeFormatted":"0h 31m 44s","squareMeters":32,"stopReason":"clean_successful","trigger":"schedule_from_app"},{"timestamp":1652884870,"date":"2022-05-18T14:41:10.000Z","lastTime":5844,"totalTime":5844,"totalTimeString":"1h 37m 24s","totalTimeFormatted":"1h 37m 24s","squareMeters":87,"stopReason":"clean_successful","trigger":"button"},{"timestamp":1652862615,"date":"2022-05-18T08:30:15.000Z","lastTime":1719,"totalTime":1719,"totalTimeString":"0h 28m 39s","totalTimeFormatted":"0h 28m 39s","squareMeters":32,"trigger":"schedule_from_app"},{"timestamp":1652776215,"date":"2022-05-17T08:30:15.000Z","lastTime":2395,"totalTime":2395,"totalTimeString":"0h 39m 55s","totalTimeFormatted":"0h 39m 55s","squareMeters":34,"stopReason":"clean_successful","trigger":"schedule_from_app"},{"timestamp":1652722534,"date":"2022-05-16T17:35:34.000Z","lastTime":446,"totalTime":446,"totalTimeString":"0h 07m 26s","totalTimeFormatted":"0h 07m 26s","squareMeters":8,"stopReason":"stopped_by_app","trigger":"button"},{"timestamp":1652717809,"date":"2022-05-16T16:16:49.000Z","lastTime":2598,"totalTime":2598,"totalTimeString":"0h 43m 18s","totalTimeFormatted":"0h 43m 18s","squareMeters":39,"stopReason":"stopped_by_app","trigger":"app"},{"timestamp":1652689815,"date":"2022-05-16T08:30:15.000Z","lastTime":1976,"totalTime":1976,"totalTimeString":"0h 32m 56s","totalTimeFormatted":"0h 32m 56s","squareMeters":33,"stopReason":"clean_successful","trigger":"schedule_from_app"},{"timestamp":1652430533,"date":"2022-05-13T08:28:53.000Z","lastTime":1628,"totalTime":1628,"totalTimeString":"0h 27m 08s","totalTimeFormatted":"0h 27m 08s","squareMeters":29,"stopReason":"stopped_by_app","trigger":"app"},{"timestamp":1652428955,"date":"2022-05-13T08:02:35.000Z","lastTime":510,"totalTime":510,"totalTimeString":"0h 08m 30s","totalTimeFormatted":"0h 08m 30s","squareMeters":8,"stopReason":"clean_successful","trigger":"app"},{"timestamp":1652344215,"date":"2022-05-12T08:30:15.000Z","lastTime":1425,"totalTime":1425,"totalTimeString":"0h 23m 45s","totalTimeFormatted":"0h 23m 45s","squareMeters":24,"stopReason":"stopped_by_app","trigger":"schedule_from_app"},{"timestamp":1652336116,"date":"2022-05-12T06:15:16.000Z","lastTime":5835,"totalTime":5835,"totalTimeString":"1h 37m 15s","totalTimeFormatted":"1h 37m 15s","squareMeters":85,"stopReason":"clean_successful","trigger":"schedule_from_app"},{"timestamp":1652249715,"date":"2022-05-11T06:15:15.000Z","lastTime":6276,"totalTime":6276,"totalTimeString":"1h 44m 36s","totalTimeFormatted":"1h 44m 36s","squareMeters":87,"stopReason":"clean_successful","trigger":"schedule_from_app"},{"timestamp":1652166282,"date":"2022-05-10T07:04:42.000Z","lastTime":497,"totalTime":497,"totalTimeString":"0h 08m 17s","totalTimeFormatted":"0h 08m 17s","squareMeters":8,"stopReason":"clean_successful","trigger":"app"}]`

**Comment by mrbungle64** [comment]
@mmeglitsch 

> there is no such Url in the "cleaninglog.last20Logs"

That's what I man 😉 

_"Unfortunately there's no image in the cleaning log of the OZMO 930.
You can also see this in the Ecovacs mobile app."_

**Comment by mrbungle64** [comment]
@mmeglitsch 

> any chance to render the image from the spotAreaBoundaries?

Can you please further explain that?

There's already a function to create an image of the map: "map.[mapID].loadMapImage" and "cleaninglog.lastCleaningMapImageURL" points to an image stored on the Ecovacs servers (but unfortunately not for the OZMO 930).

**Comment by mrbungle64** [comment]
@mmeglitsch 

I'll close this issue now. Feel free to [create](https://github.com/mrbungle64/ioBroker.ecovacs-deebot/issues/new?assignees=&labels=Enhancement%2CVerification&template=feature-request.yml) an issue for your feature request.
