### ISSUE TITLE
OZMO 950 firmware 1.7.9

### ISSUE THREAD

**Issue by volkerverkamp** [mrbungle64/ioBroker.ecovacs-deebot#31]
Hallo zusammen,
mir wird seid heute morgen das FW-Update auf die v1.7.9 (von v1.7.6) angeboten. Der erste Versuch zur Installation ist bei mir fehlgeschlagen. Hat schon jemand Erfahrungen gesammelt, inwiefern die Funktionalität des Adapters durch das Update beeinflusst wird?

Danke

**Comment by mrbungle64** [comment]
Hallo @volkerverkamp,

Meinst du die Installation des Adapters oder die der Firmware, welche fehlgeschlagen ist?

**Comment by volkerverkamp** [comment]
Die der Firmware ;-) Der Adapter läuft super (mit der v1.7.6).

**Comment by mrbungle64** [comment]
> Die der Firmware ;-) Der Adapter läuft super (mit der v1.7.6).

ok, gut :+1: 

Hatte die Frage gerade gelöscht ;)

**Comment by boriswerner** [comment]
Vielleicht speichert der Bot jetzt wieder die Reinigungsprotokolle... Bei mir war die Aktualisierung erfolgreich, ich kann nur gerade nicht testen. Hab leider zu spät dran gedacht Mal mitzuloggen, was da so für Nachrichten übertragen werden beim Update...

**Comment by Opa0815** [comment]
Macht er nicht :(
Ich habe bisher keinen Unterschied feststellen können.

**Comment by volkerverkamp** [comment]
[Gerüchteweise](https://www.roboter-forum.com/index.php?thread/40977-firmwareaktualisierungen-ozmo-950/&postID=548828#post548828) soll es morgen (06.03.) eine neue App geben, ggf. dann mit neuen Features (und erweiterter API?).

**Comment by mrbungle64** [comment]
@volkerverkamp 

Konntest das Update der Firmware inzwischen erfolgreich durchführen?
Den Issue könnten wir dann ja eigentlich schließen, oder?
Es gab ja bisher keine negative Meldungen :)

**Comment by volkerverkamp** [comment]
Jo - Update wurde durchgeführt und bisher keine Probleme!

Am Sa., 7. März 2020 um 12:28 Uhr schrieb Sascha <notifications@github.com>:
