### ISSUE TITLE
Bitte readme anpassen, npm nicht mit sudo einleiten

### ISSUE THREAD

**Issue by Grothesk242** [mrbungle64/ioBroker.ecovacs-deebot#313]
### Is there an existing issue for this?

- [X] I have searched the existing issues and no issue is describing my issue

### The problem

In der Readme steht:

``sudo npm install canvas``

das führt zu falschen Berechtigungen. Besser:

```
cd /opt/iobroker
npm install canvas [Optionen]
```

### With which model does the problem occur?

Other model (Please fill out the fields at the bottom of the form)

### From which source you have installed the adapter?

GitHub

### Version of the ioBroker adapter ("info.version")

Xxx

### Version of the ecovacs-deebot.js library ("info.library.version")

Xxx

### Version of the JS controller

Xxx

### Version of Node.js

Xxx

### Operating system

Linux

**Comment by mrbungle64** [comment]
@Grothesk242 

Danke für den Hinweis 👍🏻 
Habe die Readme angepasst.
