### ISSUE TITLE
Berechnung Dustbox Quadratmeter fehlerhaft

### ISSUE THREAD

**Issue by benep** [mrbungle64/ioBroker.ecovacs-deebot#314]
### Is there an existing issue for this?

- [X] I have searched the existing issues and no issue is describing my issue

### The problem

Hallo Sascha,

wie von dir schon vermutet passen die Quadratmeter seit Entfernung der Dustbox noch nicht. Leider bin ich grad zu viel unterwegs, um das wirklich durch zu testen, möchte aber ein kurzes Feedback geben. Ich habe das SQL-Logging deiner und meiner Werte (mit meiner alten Berechnung) aktiviert. Was ich dadurch sagen kann ist, dass bei meinen Wert manchmal Reinigungen fehlen und bei deinen eher doppelt so viel raus kommt, wie es sein sollte.

Hier ein leider nicht sehr schönes Diagramm um das zu verdeutlichen. Grün sind deine Werte, blau meine und rot sind die einzelnen Reinigungen. Ich hoffe das ist verständlich.
![Screenshot 2022-07-01 124116](https://user-images.githubusercontent.com/237102/176879529-7f303120-438e-45b4-875c-4c396a8e3fe2.jpg)

Scheibar machst du die Berechnung auch während der Reinigung. Es wird also bei jedem Quadratmeter der Wert einzeln erhöht. Manchmal gibt es da aber große Sprünge und ich vermute, dass die es sind, die den Wert verfälschen.
![Screenshot 2022-07-01 123555](https://user-images.githubusercontent.com/237102/176880153-6966460e-e9e1-43b5-b706-3de071bd9591.jpg)

Hoffentlich hilft dir das wenigsten ein bissl, auch wenn ich die nächsten zwei Wochen schon wieder weg bin und wahrscheinlich nicht groß testen kann.

### With which model does the problem occur?

Deebot T8 series

### From which source you have installed the adapter?

GitHub

### Version of the ioBroker adapter ("info.version")

1.4.5-alpha.5

### Version of the ecovacs-deebot.js library ("info.library.version")

0.8.3-alpha.7

### Version of Node.js

v14.19.3

### Operating system

Linux

Edit: gekürzt von @mrbungle64

**Comment by mrbungle64** [comment]
@benep 

Kurze Frage erst mal dazu:
passen die Werte von "cleaningTimeSinceLastDustboxRemoved" Deiner Meinung nach, oder hast Du die einfach nicht so im Auge wie die Quadratmeter?

**Comment by benep** [comment]
Die hab ich leider nicht im Blick. Aber aktuell sind es bei dir (4h 17m 37s) auch etwa doppelt so viel, wie bei mir (2h 18m 30s).

**Comment by mrbungle64** [comment]
@benep 

> Scheibar machst du die Berechnung auch während der Reinigung

Ja, ich nehme nicht mehr die Werte der gesamten Reinigung (weil schwierig über die verschiedenen Modelle zu handeln), sondern quasi die Werte unter "cleaninglog.current" und nehme dann immer die Differenz zum letzten bekannten Wert. Das passiert dann jedes Mal, wenn Werte rein kommen.
Es scheint hier, als würde am Ende der Reinigung der Reset einen Augenblick zu früh geschehen und dann noch mal die Differenz zum Start der Reinigung (weil ja inzwischen zurückgesetzt) aufaddiert zu werden.

In der 1.4.5-alpha.6 habe ich noch mal ein paar Verbesserungen vorgenommen.
Hoffentlich sieht es dann bei dir besser aus 😉

**Comment by mrbungle64** [comment]
@benep 

Die Optimierte Variante ist nun auch in der 1.4.5 (Beta/Latest Repo)

**Comment by mrbungle64** [comment]
@benep 

Hattest Du inzwischen mal die Möglichkeit zu testen?

**Comment by benep** [comment]
Ich kann dir leider nur meine Beobachtungen geben und keine konkreten Gründe.

Deine Änderungen haben es für mich deutlich verbessert. Allerdings gibt es immer noch einen Unterschied. Manchmal zählt er immer noch während der Reinigung nicht einzelne m2, sondern große Werte. Gefühlt sind die "großen" Werte größer, wenn die vorherige Reinigung auch größer war, aber auch nicht genau der Wert der vorherigen Reinigung. Und mir kommt es vor, als ob das das nicht mehr so oft passiert, wie in der alpha.

Die Zeitwerte sind besser, aber auch nicht immer gleich. 

![Screenshot 2022-07-21 092524](https://user-images.githubusercontent.com/237102/180156355-5e0be293-ac1c-4a9f-8b48-ddd3e6ff132d.jpg)

Blau sind m2. Grün die Reinigungszeit. Hell sind jeweils deine Werte und dunkel die von meinem Script.

**Comment by mrbungle64** [comment]
@benep 

Mit der Version 1.4.6-alpha.x könnte das bei Dir nun besser funktionieren 😉

**Comment by benep** [comment]
Also es sieht jetzt viel besser aus. Die restliche Diskrepanz könnte an der Berechungsmethode liegen. Beipielsweise wie wird der Rückweg nach der Reinigung gezählt. Oder es könnten Rundungsunterschiede sein.

![Screenshot 2022-08-06 115251](https://user-images.githubusercontent.com/237102/183243937-2078565c-446a-45ad-8bb4-f44a00f8e8c3.jpg)

Nachdem ich die gereinigten QM von Ecovacs selbst nicht als allzu genau werte, reicht mit der Wert jetzt so für meine Leerungserinnerung.

Danke nochmal, dass du das so eingebau hast und auch so lange dran geblieben bist.

Von mir aus kannst du das jetzt schließen.

**Comment by mrbungle64** [comment]
@benep 

> Also es sieht jetzt viel besser aus. Die restliche Diskrepanz könnte an der Berechungsmethode liegen. Beipielsweise wie wird der Rückweg nach der Reinigung gezählt. Oder es könnten Rundungsunterschiede sein.

Danke für das Feedback 👍🏻 
Ja, die Unterschiede werden durch die unterschiedlichen Berechungsmethoden kommen.
Wie die schon gesagt hast wird es eh nicht (für jeden Fall) perfekt werden 😉
