### ISSUE TITLE
Komisches Verhalten 

### ISSUE THREAD

**Issue by Obelix411** [mrbungle64/ioBroker.ecovacs-deebot#315]
### The question

Mahlzeit 
Ich habe heute bemerkt das mein deebot 900 permanent die Karte aktualisiert und Probleme beim positionieren hat dann habe ich zum Testen mal den Adapter angehalten und die Probleme waren weg nach dem Neustart des Adapters fing er wieder an sich komisch zu verhalten 

Mit freundlichen Grüßen
Stefan 

### Which model do you own?

Deebot 900/901

**Comment by mrbungle64** [comment]
@Obelix411 

Moin,
leider hast du das falsche Template ("Question") benutzt und nicht mal die (weil falsches Template) wenigen Felder ausgefüllt ...

Ich tippe aber sowieso eher auf ein Blockly oder so.
Hast du da was für den Saugroboter am laufen?

Falls nicht benötige ich noch folgende Infos (werden eigentlich bereits im Issue Template abgefragt):
- Version des Adapters ("info.version")
- Version der ecovacs-deebot.js library ("info.library.version")
- Version JS controller
- Version Node.js

Und möglichst ein Auszug aus dem Log mit Einträgen während sich der Deebot komisch verhält.

Auch bin ich mir nicht sicher, was genau mit "permanent die Karte aktualisiert" und "Probleme beim positionieren hat" genau gemeint ist ...

**Comment by mrbungle64** [comment]
@Obelix411 

Hat sich das Problem erledigt?
