### ISSUE TITLE
Mehrfache Einträge im Log

### ISSUE THREAD

**Issue by krobipd** [mrbungle64/ioBroker.ecovacs-deebot#323]
### Is there an existing issue for this?

- [X] I have searched the existing issues and no issue is describing my issue

### The problem

hey 👋

ich habe jetzt testweise meine raum-skript abgeschaltet und nutze nun die integrierte Funktion bzgl Saugstärke pro raum.

möchte das er die Küche in Saugstufe 3 saugt, den rest aber mit 2. mir jetzt gerade im log aufgefallen das er sehr oft den speed ändern möchte bzw wenn e schon richtig ist deswegen ein senden Signal sendet.

auch ist mir aufgefallen das einpaar andere Sachen mehrfach im log stehen, finde ich etwas komisch
<img width="1118" alt="Bildschirmfoto 2022-07-19 um 22 32 32" src="https://user-images.githubusercontent.com/27220902/179843765-cc047142-c547-4643-b9b1-2ceb06b2cf59.png">

### With which model does the problem occur?

Deebot OZMO 950

### From which source you have installed the adapter?

Beta (latest)

### Version of the ioBroker adapter ("info.version")

1.4.5

### Version of the ecovacs-deebot.js library ("info.library.version")

0.8.3-beta.0

### Version of the JS controller

6

### Version of Node.js

16.16.0

### Operating system

Linux

### Ecovacs device class ("info.deviceClass")

yna5xi

### Communication protocol ("info.library.communicationProtocol")

MQTT

### Is the canvas module installed? ("info.library.canvasModuleIsInstalled")

yes (true)

**Comment by krobipd** [comment]
ich sags mal so, jein.

also er hat zwar in der Küche auf 3 hochgeschalten aber scheinbar dann nicht mehr richtig "Resetet" (auf 2, den Standardwert).

hab nur eingestellt das er in der Küche auf 3 schalten soll, in allen anderen räumen hab ich nichts geändert und auch die Standardeinstellung ist 2.

also mein Gedanke ist - er schaltet in der Küche auf 3 und sonst immer auf 2 bzw reduziert halt wenn wo anders hinfährt (auf 2).

und ich denke ich sehe da im log noch einen Fehler, der Roboter steht in der Küche - die mit 3 gesaugt werden soll - aber wenn er zurück fährt soll er ja wieder auf 2 reseten.
<img width="231" alt="Bildschirmfoto 2022-07-19 um 23 26 00" src="https://user-images.githubusercontent.com/27220902/179851434-0bee6236-5540-4855-be35-bdd5e84f9735.png">

**Comment by krobipd** [comment]
dazu hier noch die room-ids wo er heute in der zeit war - room id 0 = Küche
<img width="230" alt="Bildschirmfoto 2022-07-19 um 23 28 19" src="https://user-images.githubusercontent.com/27220902/179851700-3be67ac7-0e5c-41df-87a4-6bd3f6f85fd0.png">

**Comment by mrbungle64** [comment]
@krobipd 

Wo war er denn um 20:31 Uhr, als das erste mal auf 3 gestellt wurde?

**Comment by mrbungle64** [comment]
@krobipd 

Es wäre mir übrigens lieber, wenn du das aus dem Log als Text kopieren würdest (anstatt Screenshots) - dann könnte ich mir das so sortieren wie es gerade am hilfreichsten ist 😉

**Comment by krobipd** [comment]
sorry für die screenshot, ist am Mac halt einfach zu komfortabel das so zu machen. das mitn kopieren mag mein safari wohl irgendwie nicht so sonderlich.

habs jetzt mal als cdv exportiert - leider sind im export wohl die Zeiten falsch oder gmt und nicht gmt+2.

Cleanspeed
timestamp | value | acknowledged | from |  
2022-07-19T18:31:35.986Z | 1 | false | javascript.0 |  
2022-07-19T18:31:59.653Z | 3 | true | ecovacs-deebot.0 |  
2022-07-19T18:32:36.640Z | 2 | false | javascript.0 |  
2022-07-19T18:32:55.375Z | 2 | true | ecovacs-deebot.0 |  
2022-07-19T18:46:43.320Z | 3 | false | ecovacs-deebot.0 |  
2022-07-19T18:47:28.394Z | 3 | true | ecovacs-deebot.0 |  
2022-07-19T19:18:52.873Z | 2 | true | ecovacs-deebot.0 |  
2022-07-19T19:21:11.365Z | 3 | false | ecovacs-deebot.0 |  


spotarea-id
2022-07-19T18:35:02.282Z | 1 | true | ecovacs-deebot.0
2022-07-19T18:35:15.298Z | 4 | true | ecovacs-deebot.0
2022-07-19T18:46:31.309Z | 1 | true | ecovacs-deebot.0
2022-07-19T18:46:43.310Z | 0 | true | ecovacs-deebot.0
2022-07-19T18:56:17.319Z | 1 | true | ecovacs-deebot.0
2022-07-19T18:56:34.324Z | 6 | true | ecovacs-deebot.0
2022-07-19T18:58:49.326Z | 1 | true | ecovacs-deebot.0
2022-07-19T18:58:57.328Z | 5 | true | ecovacs-deebot.0
2022-07-19T19:10:50.349Z | 1 | true | ecovacs-deebot.0
2022-07-19T19:11:27.361Z | 3 | true | ecovacs-deebot.0
2022-07-19T19:19:22.365Z | 1 | true | ecovacs-deebot.0
2022-07-19T19:21:11.359Z | 0 | true | ecovacs-deebot.0


das javascript was auf 1 schaltet ist meines und so gewollt - entleeren ;-)
das was auf 2 schaltet ist mir noch ein Rätsel aber werde mal mein haufen von Skripten nochmal durchforsten.

jedenfalls folgender ablauf
in der Küche ist seine homebase - die fahrt war genau wie folgt.
start (Küche, nicht gereinigt), Flur (keine Reinigung dient nur zur durchfahrt), Esszimmer, Flur, Küche, Flur, Eingang, Flur, wohnzimmer, Flur, Schlafzimmer - fertig.

**Comment by mrbungle64** [comment]
@krobipd 

> das javascript was auf 1 schaltet ist meines und so gewollt - entleeren ;-)
> das was auf 2 schaltet ist mir noch ein Rätsel aber werde mal mein haufen von Skripten nochmal durchforsten.

Zur Fehlersuche wäre es hilfreich, wenn Du die Deine Skripte so lange mal pausieren würdest.

Was ich auch noch nicht so ganz verstanden habe ist, warum Du das Log nach "Cleanspeed" und "spotarea-id" auftrennst 😉

**Comment by krobipd** [comment]
ich könnte auch direkt die räume hernehmen 🙈
aber so sieht du ja wann der Roboter wo war und welchen speed er hatte. naja auftrennen ist gut gesagt sind ja zwei verschiedene Datenpunkte für diese Auswertung.

wie gesagt speed 1 wird nur getriggert beim entleeren, da soll er auch nix saugen nur zum Mistkübel fahren und dann deiner tollen Funktion kann er das ja auch - was die app nicht kann :-)

**Comment by krobipd** [comment]
so hab mir nochmal meine skripte durchgeschaut, hab in letzter zeit einiges umgestellt/aufgeräumt usw
und sind halt mit der zeit einige skripte da verliert man gern mal die Übersicht.
jedenfalls es ist nur eines was den speed ändert und das ist mein entleeren skript
beim starten schaltet es auf 1 und beim beenden wieder auf 2.

heißt wenn ich der Schalter (HomeKit) true dann speed 1 und auf Position fahren und wenn false dann speed 2 und zurück zur Ladestation. alles andere habe ich entfernt.

**Comment by mrbungle64** [comment]
@krobipd 

> naja auftrennen ist gut gesagt sind ja zwei verschiedene Datenpunkte für diese Auswertung.

Ja schon, aber ich meine dass die ja eigentlich im selben Log bzw. in der selben Datei stehen 😉
Es ist für mich halt deutlich einfacher, wenn ich das alles gleich in der Abfolge sehe wie es auch eingetreten ist.

**Comment by mrbungle64** [comment]
> jedenfalls es ist nur eines was den speed ändert und das ist mein entleeren skript

Ich würde dann jetzt mal abwarten wie es sich verhält, wenn das Skript nicht läuft welches auch die Saugstärke verändert.

**Comment by krobipd** [comment]
zu dem Thema habe ich jetzt nochmal einen eigenen bug Report aufgemacht - https://github.com/mrbungle64/ioBroker.ecovacs-deebot/issues/325

beim heutigen saugen ist mir soweit keine auffällig bzgl doppelter eintrage aufgefallen, außer das er 2 mal auf speed gestellt hatte - was die frage aufgeworfen hat ob der adapter nicht checkt welcher speed den eingestellt ist (siehe anderer thread). soweit würde ich das hier mal closed ansehen.

**Comment by krobipd** [comment]
oh sorry zu früh gefreut

beim saugen war alles ok aber jetzt wo er fertig war folgende Meldungen

ecovacs-deebot.0 | 2022-07-23 18:05:59.657 | info | Reset current cleaninglog stats
-- | -- | -- | --
ecovacs-deebot.0 | 2022-07-23 18:05:59.657 | info | Reset current cleaninglog stats
ecovacs-deebot.0 | 2022-07-23 18:05:34.225 | info | Set Clean Speed: 3
ecovacs-deebot.0 | 2022-07-23 18:05:34.208 | info | Set clean speed to 3 for spot area 0
ecovacs-deebot.0 | 2022-07-23 18:03:39.894 | info | Set Clean Speed: 2
ecovacs-deebot.0 | 2022-07-23 18:03:39.890 | info | Set Clean Speed: 2
ecovacs-deebot.0 | 2022-07-23 18:03:39.884 | info | Set Clean Speed: 2
ecovacs-deebot.0 | 2022-07-23 18:03:39.879 | info | Set Clean Speed: 2

**Comment by mrbungle64** [comment]
@krobipd 

Hattest du dabei jetzt eigentlich deine Skripte deaktiviert?
