### ISSUE TITLE
Deebot X1 goToPosition funktioniert nicht richtig

### ISSUE THREAD

**Issue by rassel2000** [mrbungle64/ioBroker.ecovacs-deebot#324]
### Is there an existing issue for this?

- [X] I have searched the existing issues and no issue is describing my issue

### The problem

Hallo,
ich wollte das Leeren des Staubbehälters meines Deebot X1 Turbo etwas einfacher gestalten, indem ich ihn auf Zuruf (Alexa) in die Küche zum Mülleimer fahren lasse. Dazu habe ich ein Skript angelegt, dass die passenden Koordinaten in den Datepunkt "goToPosition" schreibt. Den Datenpunkt habe ich voher in der Adapterkonfiguration aktiviert. Der Roboter interpretiert die von meinem Skript gesendeten Koordinaten nur scheinbar falsch.
Wenn ich die Koordinaten in den Datenpunkt "goToPosition" eingebe, kommt sofort die Sprachansage "Bereichsreinigung gestartet". Der Roboter fährt dann die gewünschte Position an, reinigt einige Male um diesen Punkt herum und fährt anschließend wieder zurück zur Ladestation.
Ich hatte anhand der Beschreibung des Datenpunktes hier auf GitHub vermutet, dass sich der Roboter genauso verhält, als wenn man im Videomanager der Ecovacs Home APP ihn zu einer bestimmten Position fahren lässt, sprich ohne Reinigungsvorgang und Rückfahrt zur Ladstation.

Muss ich vielleicht noch etwas an der Adapterkonfiguration ändern oder versteht der X1 diesen Befehl einfach als Aufforderung zur Bereichsreinigung?

Vielen Dank!

### With which model does the problem occur?

Deebot X1 series

### From which source you have installed the adapter?

Beta (latest)

### Version of the ioBroker adapter ("info.version")

1.4.5

### Version of the ecovacs-deebot.js library ("info.library.version")

0.8.3-beta.0

### Version of the JS controller

4.0.23

### Version of Node.js

14.19.3

### Operating system

Linux

### Anything in the logs that might be useful?

```txt
-
```

### Ecovacs device class ("info.deviceClass")

2o4lnm

### Communication protocol ("info.library.communicationProtocol")

MQTT

### Is the canvas module installed? ("info.library.canvasModuleIsInstalled")

yes (true)

**Comment by mrbungle64** [comment]
Hallo @rassel2000 

> Ich hatte anhand der Beschreibung des Datenpunktes hier auf GitHub vermutet, dass sich der Roboter genauso verhält, als wenn man im Videomanager der Ecovacs Home APP ihn zu einer bestimmten Position fahren lässt, sprich ohne Reinigungsvorgang und Rückfahrt zur Ladstation.

Leider (noch) nicht. Das ist eine Implementierung auf Basis [dieses](https://github.com/mrbungle64/ioBroker.ecovacs-deebot/issues/100) Feature Requests.

Es steht aber ja eigentlich auch, dass es die Funktion nur simuliert ("Diese Funktion erwartet x,y-Koordinaten und simuliert eine GoTo-Funktion")

Ich schaue mir das aber im Laufe des Wochenendes noch mal genauer an woran das Fehlverhalten bei Dir liegen könnte.

**Comment by rassel2000** [comment]
@mrbungle64 Huch, das Feature Request hab ich völlig übersehen.
Danke für deine Anwort!

**Comment by mrbungle64** [comment]
@rassel2000 

Die Version 1.4.6-alpha.1 (GitHub) kann nun auch die native Funktion aus dem Videomanager.

Wichtig ist, dass in den Einstellungen "V2 Clean Befehl für neuere Modelle nutzen (z.B. T8 und T9 Serie)" auf "Vorauswahl verwenden" oder "aktiviert" steht.

Ich hatte mit meinem T8 AIVI vor einigen Wochen schon mal einen Versuch unternommen dies zu implementieren - der war aber fehlgeschlagen. Jetzt weiß ich was da "falsch" gemacht hatte 😉

**Comment by rassel2000** [comment]
@mrbungle64 funktioniert bei mir leider nicht. Der Roboter sagt wieder "Bereichsreinigung gestartet", schaltet den Sauger ein aber bewegt sich diesmal kein Stück.
Hab den Adapter schon komplett neu installiert (sowohl mit alpha1 als auch mit alpha2) und die von Dir genannte Option aktiviert. Klappt leider trotzdem nicht.
Der kleine ist aber auch widerspenstig :)

Seit dem Installieren der Github Version stürzt mir der Adapter alle paar Minuten ab mit der Fehlermeldung vom ioBroker "... terminated due to SIGSEGV" oder auch "...due to SIGABRT". Sonst steht im Log soweit nichts.

**Comment by rassel2000** [comment]
@mrbungle64 habs gerade nochmal ausprobiert. Der Adapter stürzt immer dann ab, wenn ich ein goToPosition-Kommando gebe und vorher in der Ecovacs Home App die "Individuelle Reinigung" beendet/abgebrochen habe.

**Comment by mrbungle64** [comment]
@rassel2000 

Schick mir doch bitte mal den Output vom Log, so dass ich sehe kann was da in welcher Abfolge passiert.
Am besten vorher den Debug Level aktivieren (für die Adapter Instanz und auch im Log)

**Comment by rassel2000** [comment]
@mrbungle64 reicht dir ein Screenshot oder brauchst du die TXT, die ich über den Admin herunterladen kann? Hab mich mit den Logs noch nicht so häufig beschäftigt.
![deebot](https://user-images.githubusercontent.com/60787668/180656741-f6370abf-882c-48b7-bbe3-3e4949eb3b78.JPG)

**Comment by mrbungle64** [comment]
@rassel2000 

Hast du ein 32-Bit System und Canvas installiert?

**Comment by rassel2000** [comment]
@mrbungle64 Canvas ist installiert und Raspbian läuft als 32bit Version

**Comment by mrbungle64** [comment]
> @mrbungle64 Canvas ist installiert und Raspbian läuft als 32bit Version

Ich kenne diese Abstürze in Verbindung mit Canvas auf 32-Bit Systemen.
Im Log war jetzt auch nichts zu sehen davon, dass da die GoToPosition Funktion aufgerufen wurde.

Bist du Dir sicher, dass das erst seit der Alpha Version auftritt und dass das mit der Funktion in Verbindung steht?

**Comment by rassel2000** [comment]
@mrbungle64 ich habe eben den Fehler wie folgt simuliert:
-> goToPosition Kommando abgeschickt
-> Bereichsreinigung in der Ecovacs App gestoppt
-> wenn ich jetzt ein Kommando über den Adapter abschicke (Clean, Charge und andere) kommen die oben genannten Fehlermeldungen. Allerdings auch nicht immer, sondern nur ab und zu. Dann aber auf jeden Fall in Verbindung mit dem Kommando. 


Aufgefallen sind mir die Abstürze erst seit der Installation der Alpha-Versionen. Kann aber auch schon davor aufgetreten sein, da bin ich mir nicht sicher.

**Comment by mrbungle64** [comment]
@rassel2000 

Wird zufällig beim Stoppen der Reinigung per Skript das Laden der Map getriggert?

**Comment by rassel2000** [comment]
@mrbungle64 nein, die Map lasse ich nicht per Skript triggern.
Aber jetzt hast du mich auf ne Idee gebracht :)

**Comment by mrbungle64** [comment]
> @mrbungle64 nein, die Map lasse ich nicht per Skript triggern. Aber jetzt hast du mich auf ne Idee gebracht :)

Hehe, aber da würde ich dir empfehlen erst auf 64-Bit zu gehen.
Canvas läuft auf 32-Bit Systemen nicht mehr stabil. Die stellen für aktuelle Node.js Versionen keine Binaries mehr zur Verfügung und das was da kompiliert wird läuft leider nicht sauber. Das gleiche Problem betrifft z.B. auch den mihome-vacuum Adapter:
https://github.com/iobroker-community-adapters/ioBroker.mihome-vacuum/issues/487
Die empfehlen auch auf 64-Bit zu gehen.

**Comment by mrbungle64** [comment]
@rassel2000 

Du solltest übrigens dringend das Node.js auf 14.20.0 updaten:
https://www.heise.de/news/Sicherheitsluecken-in-node-js-abgedichtet-7167912.html

Vielleicht sind dann ja auch die Abstürze weg 😉 
Ich wüsste bisher echt nicht wie ich mit den letzten Codeänderungen diese Abstürze hinbekommen haben soll 😉

**Comment by rassel2000** [comment]
@mrbungle64 danke für den Hinweis bezüglich Node.js!
Ich hatte sowieso schon vor, den RasPi auf 64Bit umzustellen. Jetzt habe ich nen Grund das mal anzugehen.
Ich melde mich nach der (hoffentlich erfolgreichen) Umstellung des RasPi, ob ich noch Fehlermeldungen bekomme.

Bis dahin erstmal vielen Dank für deinen Support!

**Comment by rassel2000** [comment]
Nabend, sorry für die späte Rückmeldung.

Ich hab mein System auf 64Bit umgestellt und seitdem keinerlei Fehlermeldungen vom Adapter mehr bekommen.

Ob die "goToPosition"-Funktion jetzt richtig funktioniert kann ich, mangels Zeit, erst morgen testen. Melde mich dann nochmal.

**Comment by benep** [comment]
Also mein T8 ohne AIVI kann die neue native GoTo-Funktion ohne Probleme. Das ist super, weil es viel leiser ist als die #100-Lösung. Ich finde das auch spannend, weil diese Funktion die Ecovacs-App nicht bietet und eigentlich nur für die T8 Version mit AIVI vorgesehen ist.

Wenn du da nochmal dran bist, könntest du vielleicht auch mal die Bewegungs-Funktion anschaun. Rechts/Links drehen geht mit dem Adapter bei meinem T8 bisher nicht, sollte aber doch dann auch gehen. Das ist aber recht unwichtig. In 2 Jahren mit dem Roboter ist mir das vielleicht 5 mal abgegangen. Vorwärts/Rückwärts geht ja und das brauch ich häufig.

Spannender könnte die Gegensprechfunktion sein, um sie für eigene Sprachmeldungen zweckzuentfremden. Evtl. wurde so auch das ["Marco Polo"](https://github.com/mrbungle64/ecovacs-deebot.js/wiki/playSound#misc) so ungesetzt.

**Comment by mrbungle64** [comment]
@benep 

> Also mein T8 ohne AIVI kann die neue native GoTo-Funktion ohne Probleme. Das ist super, weil es viel leiser ist als die #100-Lösung. Ich finde das auch spannend, weil diese Funktion die Ecovacs-App nicht bietet und eigentlich nur für die T8 Version mit AIVI vorgesehen ist.

Gut zu wissen, dass das nicht nur bei den AIVI Modellen funktioniert. Ich hatte das schon ein bisschen vermutet - aber gut dass du das nun bestätigt hast 👍🏻 

> 
> Wenn du da nochmal dran bist, könntest du vielleicht auch mal die Bewegungs-Funktion anschaun. Rechts/Links drehen geht mit dem Adapter bei meinem T8 bisher nicht, sollte aber doch dann auch gehen. Das ist aber recht unwichtig. In 2 Jahren mit dem Roboter ist mir das vielleicht 5 mal abgegangen. Vorwärts/Rückwärts geht ja und das brauch ich häufig.
> 
> Spannender könnte die Gegensprechfunktion sein, um sie für eigene Sprachmeldungen zweckzuentfremden. Evtl. wurde so auch das ["Marco Polo"](https://github.com/mrbungle64/ecovacs-deebot.js/wiki/playSound#misc) so ungesetzt.

Ich muss mal schauen womit ich als nächstes weiter mache - das entscheide ich oft recht spontan ...
Aktuell mache ich insgesamt nicht so viel - das wird im Herbst bestimmt wieder mehr 😉

**Comment by mrbungle64** [comment]
@rassel2000 

> Nabend, sorry für die späte Rückmeldung.
> 
> Ich hab mein System auf 64Bit umgestellt und seitdem keinerlei Fehlermeldungen vom Adapter mehr bekommen.
> 
> Ob die "goToPosition"-Funktion jetzt richtig funktioniert kann ich, mangels Zeit, erst morgen testen. Melde mich dann nochmal.

Konntest du die "goToPosition" Funktion inzwischen testen?

**Comment by rassel2000** [comment]
@mrbungle64 tut mir leid, dass ich mich solange nicht gemeldet habe :(
Ich bin gerade beruflich viel unterwegs, da ist mir das durch die Lappen gegangen.

Ich bin aktuell leider nicht zuhause, werde es morgen Nachmittag aber direkt ausprobieren (habs in meinen Kalender eingetragen:wink:)  und dann berichten.

Danke dass du soviel Geduld mit mir hast :)

**Comment by mrbungle64** [comment]
@rassel2000 

Alles klar 👍🏻  Kein Problem

**Comment by rassel2000** [comment]
@mrbungle64 so, habe wie versprochen die Funktion getestet.
Leider möchte der Bot noch nicht so wie ich.
Sobald ich die Koordinaten eingebe, sagt er "Bereichsreinigung wird gestartet" und schaltet die Saugfunktion ein. Er bewegt sich aber kein bisschen und bleibt einfach stur stehen.
Die Funktionen "control.extended", "V2 Clean Befehle" und "Native goToPosition Funktion benutzen" habe ich aktiviert.
Für mich als Laien wirkt das so, als ob der Bot den falschen Befehl bekommt. Wenn ich in der Ecovacs App die Funktion "Auf Befehl ankommen" benutze, sagt er auch "Ziel wird angesteuert".
Adapterversion: 1.4.7

**Comment by mrbungle64** [comment]
@rassel2000 

> Wenn ich in der Ecovacs App die Funktion "Auf Befehl ankommen" benutze, sagt er auch "Ziel wird angesteuert".

Ist diese Funktion Teil des Videomanagers?

**Comment by rassel2000** [comment]
@mrbungle64 genau

**Comment by mrbungle64** [comment]
@rassel2000 

Bei meinem T8 AIVI gibt es dort keine speziell benannte Funktion - ich kann da halt in der Karte ein Ziel anlegen und dann über einen Button dorthin schicken. Wenn ich über die "native" GoToPosition Funktion im Adapter ein Ziel ansteuere verhält es sich dann genau so wie über den Videomanager.

Was den X1 betrifft vermute ich im Endeffekt das gleiche wie du - nämlich dass der Befehl für den X1 (ggf. nur im Detail) anders aufgebaut ist. Da es aber dazu keine öffentlich zugängliche Doku gibt kann ich da gerade auch nur spekulieren.

Dann müssen wir mal schauen wie wir an die Informationen kommen 😉

**Comment by rassel2000** [comment]
@mrbungle64 bei mir habe ich unten rechts den Button "Auf Befehl ankommen". Wenn ich den drücke, öffnet sich die Karte, ich wähle das Ziel und drücke unten Links auf "Los".

Dass es keine offene Doku gibt habe ich schon befürchtet. Habe mich schon von Anfang gewundert, dass Ecovacs überhaupt eine API bietet, da die App quasie die Tuya App mit ein paar kosmetischen Veränderung ist. Für die Smart Life App ist mir so eine Schnittstelle nicht bekannt.

Kann ich dir beim Beschaffen der Infos irgendwie behilflich sein (Logs etc.)?

**Comment by mrbungle64** [comment]
@rassel2000 

> Kann ich dir beim Beschaffen der Infos irgendwie behilflich sein (Logs etc.)?

Bei Befehlen muss man i.d.R. den Netzwerkverkehr mitschneiden. Da wäre [mitmproxy](https://mitmproxy.org/) wohl das gängigste Werkzeug für. Allerdings ist das nur mit iOS halbwegs praktikabel, da man dort das notwendige Zertifikat eintragen kann (unter Android geht das nur über Umwege) und in meinem Fall hatte das beim Videomanager nicht funktioniert. Dass ich den Befehl für diese Funktion herausgefunden hatte war glaub ich eher Zufall.

Ich weiß also nicht, ob sich das für dich lohnt den Aufwand zu betreiben und dann im Endeffekt auch das gleiche Problem zu haben, dass es beim Videomanager nicht funktioniert.

**Comment by rassel2000** [comment]
@mrbungle64 hört sich ziemlich komplex an und mangels iOS-Gerät für mich schwierig umzusetzen.
Da die Funktion ja nur ein "nice to have" ist, belasse ich es bei der aktuellen Funktionalität. Der X1 ist ja auch noch nicht so weit verbreitet, so dass der Personenkreis, der die Funktion nutzen würde, wahrscheinlich relativ klein ist. Vielleicht ergibt sich ja mit der Zeit etwas (du hattest den Befehl für die anderen Modelle ja auch durch Zufall gefunden 😃). Sonst ist der Adapter aber wirklich große Klasse!

Vielen Dank für deine Mühe!!

**Comment by mrbungle64** [comment]
@rassel2000 

> Sonst ist der Adapter aber wirklich große Klasse!

Danke für das Feedback 👍🏻 

> Vielleicht ergibt sich ja mit der Zeit etwas

Es besteht noch Hoffnung: https://github.com/mrbungle64/ioBroker.ecovacs-deebot/issues/270#issuecomment-1218451229 😉

**Comment by mrbungle64** [comment]
@rassel2000 

Möchtest du die goToPosition Funktion mal mit der Version >= 1.4.9-alpha.2 probieren?
Ich verwende da nun einen anderen Befehl welcher beim T9 funktioniert.

**Comment by rassel2000** [comment]
@mrbungle64 hört sich interessant an!
Werde das morgen direkt mal ausprobieren...

**Comment by mrbungle64** [comment]
@rassel2000 

> @mrbungle64 hört sich interessant an! Werde das morgen direkt mal ausprobieren...

Ich bin gespannt auf Dein Feedback 😃

**Comment by bernd-c3pb** [comment]
@mrbungle64
Das Warten hat sich gelohnt! Es funktioniert!!!!
Der Robbi plappert "Ziel wird angefahren", denkt sich einige Sekunden lang die beste Route aus und fährt dann die Position an. Angekommen bleibt er stehen und gibt "Zielposition erreicht" von sich. GENIAL!

Vielen Dank für deine Arbeit und das Bescheid geben!!!

**Comment by mrbungle64** [comment]
@bernd-c3pb 

> @mrbungle64 Das Warten hat sich gelohnt! Es funktioniert!!!! Der Robbi plappert "Ziel wird angefahren", denkt sich einige Sekunden lang die beste Route aus und fährt dann die Position an. Angekommen bleibt er stehen und gibt "Zielposition erreicht" von sich. GENIAL!
> 
> Vielen Dank für deine Arbeit und das Bescheid geben!!!

Sehr gut! Danke für das Feedback 👍🏻

**Comment by mrbungle64** [comment]
@bernd-c3pb 

Nur zur Sicherheit: Ist das bei dir auch ein X1?
