### ISSUE TITLE
clean speed for spot area reset problem

### ISSUE THREAD

**Issue by krobipd** [mrbungle64/ioBroker.ecovacs-deebot#325]
### Is there an existing issue for this?

- [X] I have searched the existing issues and no issue is describing my issue

### The problem

hey

das ganze ist jetzt etwas bezugnehmend auf meinen vorherigen thread - https://github.com/mrbungle64/ioBroker.ecovacs-deebot/issues/323

ich habe ja die Küche auf stufe drei eingestellt über deine "Clean speed for the spot area" Funktion.
die anderen räume habe ich auf "no change/standard".

jetzt ist mir aufgefallen das er brav auf stufe 3 in der Küche schaltet aber wenn er dann die Küche verlässt - somit nicht in der Küche (stufe 3) ist - nicht zurückschaltet (also auf Standard, stufe 2).

ist das jetzt ein Einstellungsfehler meinerseits? muss ich jeden raum über deine Funktion manuell mitteilen das er auf stufe 2 schalten soll? (ist die Standardstufe).

ich bin davon ausgegangen das der adapter das selbstständig ändern/einstellt und dementsprechend checkt was beim Roboter eingestellt ist und dementsprechend das ändert? kann es sein das du grundsätzlich einfach sagst stellt auf stufe xy egal was eingestellt ist und wenn "standard/no change" drin ist einfach nix gemacht wird?

### With which model does the problem occur?

Deebot OZMO 950

### From which source you have installed the adapter?

Beta (latest)

### Version of the ioBroker adapter ("info.version")

1.4.5

### Version of the ecovacs-deebot.js library ("info.library.version")

0.8.3-beta.0

### Version of the JS controller

 4.0.23

### Version of Node.js

v16.16.0

### Operating system

Linux

### Is the canvas module installed? ("info.library.canvasModuleIsInstalled")

yes (true)

**Comment by mrbungle64** [comment]
@krobipd 

> ist das jetzt ein Einstellungsfehler meinerseits? muss ich jeden raum über deine Funktion manuell mitteilen das er auf stufe 2 schalten soll? (ist die Standardstufe).

Nein, deine Annahme war soweit richtig - der sollte autom. auf die als Standard eingestellt Saugstärke gehen. Das scheint dann nicht richtig zu funktionieren.

> ich bin davon ausgegangen das der adapter das selbstständig ändern/einstellt und dementsprechend checkt was beim Roboter eingestellt ist und dementsprechend das ändert? kann es sein das du grundsätzlich einfach sagst stellt auf stufe xy egal was eingestellt ist und wenn "standard/no change" drin ist einfach nix gemacht wird?

Ich glaube hier vermischt du die Dinge ein wenig - aber wie auch immer - das oben beschriebene Fehlverhalten werde ich prüfen und auch soweit fixen.

**Comment by mrbungle64** [comment]
@krobipd 

Mir der Version 1.4.6-alpha.2 (GitHub) sollte das nun alles funktionieren 😉

**Comment by mrbungle64** [comment]
@krobipd 

Wartest du auf die Beta?

**Comment by mrbungle64** [comment]
@krobipd 

Version 1.4.6 ist released
