### ISSUE TITLE
"undefined is not a valid" für 2 Datenpunkte

### ISSUE THREAD

**Issue by krobipd** [mrbungle64/ioBroker.ecovacs-deebot#326]
### Is there an existing issue for this?

- [X] I have searched the existing issues and no issue is describing my issue

### The problem

hey

mir ist aufgefallen das im log immer und immer wieder folgende Fehler auftauchen

> 2022-07-23 16:23:12.829 - info: ecovacs-deebot.0 (1407) undefined is not a valid state value for id "ecovacs-deebot.0.cleaninglog.current.cleanedArea"
2022-07-23 16:23:12.830 - info: ecovacs-deebot.0 (1407) undefined is not a valid state value for id "ecovacs-deebot.0.cleaninglog.current.cleanedSeconds"

es sind aber korrekte Daten in den jeweiligen Datenpunkten drin.

### With which model does the problem occur?

Deebot OZMO 950

### From which source you have installed the adapter?

Beta (latest)

### Version of the ioBroker adapter ("info.version")

1.4.5

### Version of the ecovacs-deebot.js library ("info.library.version")

0.8.3-beta.0

### Version of the JS controller

4.0.23

### Version of Node.js

16.16.0

### Operating system

Linux

### Communication protocol ("info.library.communicationProtocol")

MQTT

### Is the canvas module installed? ("info.library.canvasModuleIsInstalled")

yes (true)

**Comment by mrbungle64** [comment]
@krobipd 

Die Fehlermeldung sollte mit der nächsten Version verschwunden sein.

**Comment by mrbungle64** [comment]
Version 1.4.6 ist released
