### ISSUE TITLE
OZMO 950: customArea_cleanings (v0.5.4)

### ISSUE THREAD

**Issue by volkerverkamp** [mrbungle64/ioBroker.ecovacs-deebot#33]
Gehe ich richtig in der Annahme, dass der Datenpunkt "customArea_cleanings" die Anzahl der Reinigungsvorgänge für eine Bereichsreinigung (customArea) angibt? 

Wenn ich diesen vor Ausführung einer Bereichsreinigung auf "2" setze, wird jedoch trotzdem nur ein Reinigungsvorgang ausgeführt.

**Comment by boriswerner** [comment]
Stand denn im Log die richtige Anzahl? Da müsste ein Eintrag gewesen sein
start cleaning custom area: x1,y1,x2,y2 (2x)
Stand da 1x oder 2x in Klammern?

**Comment by volkerverkamp** [comment]
Da steht 2x in Klammern, allerdings steht zwei Log-Einträge vorher auch noch 1x

![image](https://user-images.githubusercontent.com/51383556/76064281-a44eb000-5f89-11ea-9bf2-4a1cb5a2dd64.png)

Das Blockly dazu sieht so aus:
![image](https://user-images.githubusercontent.com/51383556/76064444-f42d7700-5f89-11ea-8ca1-a4cb4dffe977.png)

**Comment by mrbungle64** [comment]
@volkerverkamp 

Passiert im Blockly Skript vorher noch was anderes mit "customArea"?
Sieht mir danach aus, als würde das zuerst mit einem ungültigen Wert (wird wohl als `true` gewertet) ausgelöst werden, bevor die eigentlich korrekt aussehenden Befehle ausgeführt werden.

**Comment by volkerverkamp** [comment]
Ja - das könnte das Problem sein, ich habe verschiedene Datenpunkte (true/false) unter "customArea" angelegt, die ich mittels Alexa/iot-Adapter setze und auf die das Blockly Skript triggert:

![image](https://user-images.githubusercontent.com/51383556/76066852-ab2bf180-5f8e-11ea-896c-b8572c0a4a97.png)

Ich nutze ioBroker noch nicht so lange und das erschien mir als der sinnvollste Weg, mir war aber nicht wirklich klar, dass der (von außen gesetzte) Wert eines Datenpunktes an den übergeordneten DP "hochgereicht" wird.

**Comment by mrbungle64** [comment]
@boriswerner 

Wir könnten die Anzahl noch als optionalen Wert am Ende erlauben, so dass man nur den einen Befehl absetzen muss. Was hältst Du davon?

Evtl. sogar unter "info" die Werte für "customArea" (z.B. als "lastCustomArea") und "customArea_cleanings" (z.B. als "lastCustomArea_cleanings") noch mal als read only. Dann wäre "CustomArea_cleanings" unter "control" sogar eigentlich überflüssig.

Beispiel
```
-3900,3600,-1000,4800     // 1x reinigen, wenn wir control.customArea_cleanings streichen
-3900,3600,-1000,4800,c   // Wert aus control.customArea_cleanings, wenn wir es behalten
-3900,3600,-1000,4800,1   // 2x reinigen
-3900,3600,-1000,4800,2   // 2x reinigen
```

**Comment by mrbungle64** [comment]
> @mrbungle64
> Ja - das könnte das Problem sein, ich habe verschiedene Datenpunkte (true/false) unter "customArea" angelegt, die ich mittels Alexa/iot-Adapter setze und auf die das Blockly Skript triggert:
> 
> ![image](https://user-images.githubusercontent.com/51383556/76066852-ab2bf180-5f8e-11ea-896c-b8572c0a4a97.png)
> 

@volkerverkamp 
Ist das direkt im ecovacs-deebot Adapter?
Also unter "ecovacs-deebot.0.control.customArea"?

**Comment by boriswerner** [comment]
@mrbungle64 klingt gut und macht es einfacher zu bedienen.
Der 950 unterstützt übrigens auch 2 fache Reinigung bei der spotArea. Im Moment ist das in der library aber noch hart auf 1 gesetzt.

**Comment by volkerverkamp** [comment]
> @volkerverkamp
> Ist das direkt im ecovacs-deebot Adapter?
> Also unter "ecovacs-deebot.0.control.customArea"?

Ja:
![image](https://user-images.githubusercontent.com/51383556/76100648-4fcd2400-5fcd-11ea-811f-0cb21de2df70.png)

**Comment by mrbungle64** [comment]
> > @volkerverkamp
> > Ist das direkt im ecovacs-deebot Adapter?
> > Also unter "ecovacs-deebot.0.control.customArea"?
> 
> Ja:
> ![image](https://user-images.githubusercontent.com/51383556/76100648-4fcd2400-5fcd-11ea-811f-0cb21de2df70.png)

Das ist keine gute Idee und führt u.U. zu solchen Fehlfunktionen.
Dieser Bereich wird vom Adapter erstellt und verwaltet.

Es gibt z.B. unter "0_userdata.0" die Möglichkeit individuelle Datenpunkte zu erstellen.
Du könntest da ggf. im ioBroker Forum mal nachfragen, was für Deine Zwecke am sinnvollsten sein könnte.

**Comment by mrbungle64** [comment]
@boriswerner 

Ich habe da mal was in der `onStateChange()` eingebaut:

```javascript
case 'customArea':
    let cleanings = this.cleanings;
    let customAreaValues = state.val.replace(/ /g,'');
    // Without number of cleanings
    let pattern = /^-?[0-9]+\.?[0-9]*,-?[0-9]+\.?[0-9]*,-?[0-9]+\.?[0-9]*,-?[0-9]+\.?[0-9]*$/;
    if (customAreaValues.split(',').length === 5) {
        // Including number of cleanings
        pattern = /^-?[0-9]+\.?[0-9]*,-?[0-9]+\.?[0-9]*,-?[0-9]+\.?[0-9]*,-?[0-9]+\.?[0-9]*,[1-2]$/;
        cleanings = customAreaValues.split(',')[4];
        this.setState('control.customArea_cleanings', cleanings, true);
    }
    if (pattern.test(customAreaValues)) {
        this.vacbot.run(stateName, 'start', customAreaValues, cleanings);
        this.log.info('start cleaning custom area: ' + state.val + ' (' + cleanings + 'x)');
    }
    break;
```

Soll ich da mal einen Commit machen?

**Comment by volkerverkamp** [comment]
> @volkerverkamp
> Das ist keine gute Idee und führt u.U. zu solchen Fehlfunktionen.
> Dieser Bereich wird vom Adapter erstellt und verwaltet.
> 
> Es gibt z.B. unter "0_userdata.0" die Möglichkeit individuelle Datenpunkte zu erstellen.
> Du könntest da ggf. im ioBroker Forum mal nachfragen, was für Deine Zwecke am sinnvollsten sein könnte.
> 
> Ich würde Dir jetzt empfehlen den Channel 'control' vom ecovacs-deebot Adapter manuell zu löschen - dann werden die notwendigen Datenpunkte beim nächsten Neustart des Adapters neu erstellt.

Das war mich nicht klar - danke für den Hinweis!

**Comment by mrbungle64** [comment]
@volkerverkamp  @boriswerner 

Die Anzahl kann nun mit der aktuellen Version von GitHub als optionaler Wert direkt genutzt werden.

Beispiel: `-3900,3600,-1000,4800,2`

https://github.com/mrbungle64/ioBroker.ecovacs-deebot/wiki/customArea

**Comment by volkerverkamp** [comment]
Habs gerade getestet, Anzeige im Log ist zwar korrekt, aber der Bot reinigt den Bereich trotzdem nur einmal (mit Firmware v1.7.9):
![image](https://user-images.githubusercontent.com/51383556/76141967-206bf500-6069-11ea-9a27-fd73fd646dc5.png)

**Comment by mrbungle64** [comment]
> Habs gerade getestet, Anzeige im Log ist zwar korrekt, aber der Bot reinigt den Bereich trotzdem nur einmal (mit Firmware v1.7.9):
> ![image](https://user-images.githubusercontent.com/51383556/76141967-206bf500-6069-11ea-9a27-fd73fd646dc5.png)

Hattest Du die Datenpunkte unter "control" mal alle komplett gelöscht?

**Comment by boriswerner** [comment]
Vielleicht übergebe ich aber auch einfach den Parameter falsch in der library. Möchte ich nicht ausschließen und würde ich mir bei Gelegenheit Mal anschauen

**Comment by volkerverkamp** [comment]
> > Habs gerade getestet, Anzeige im Log ist zwar korrekt, aber der Bot reinigt den Bereich trotzdem nur einmal (mit Firmware v1.7.9):
> > ![image](https://user-images.githubusercontent.com/51383556/76141967-206bf500-6069-11ea-9a27-fd73fd646dc5.png)
> 
> Hattest Du die Datenpunkte unter "control" mal alle komplett gelöscht?

Ja, hab ich.

**Comment by boriswerner** [comment]
@mrbungle64 @volkerverkamp 
Also, ich hab das gerade alles mal mit meinem 950 und der Adapter v0.5.5 durchgespielt.
Der Wert in customArea_cleanings wird bei mir sauber übergeben und er führt auch 2 Reinigungen durch, wenn ich das gesetzt habe und nur die 4 Koordinaten an den customArea Befehl übergebe.

Die neue Syntax (Bsp. -3900,3600,-1000,4800,2) funktioniert bei mir nicht so ganz. Sie führt dazu, dass die customArea_cleanings zwar auf den Wert gesetzt werden im ioBroker, allerdings wird der Wert nicht sauber an die Library übergeben, hier wird immer nur einmal gereinigt, auch egal, was in den customArea_cleanings vorher stand.
Entferne ich den 5ten Wert wieder aus dem customArea Kommando, berücksichtigt er wieder den Wert aus customArea_cleanings.

Fazit: alte Funktion ist voll gegeben, der neue Parameter funktioniert noch nicht wie gewollt.

**Comment by mrbungle64** [comment]
@boriswerner 

Was steht denn im Log, wenn Du die neue Syntax verwendest?
In beiden Fällen sollte eigentlich das, was mit "(1x)" oder "(2x)" im Log steht an die Library übergeben werden:

```javascript
    const patternWithCleanings = /^-?[0-9]+\.?[0-9]*,-?[0-9]+\.?[0-9]*,-?[0-9]+\.?[0-9]*,-?[0-9]+\.?[0-9]*,[1-2]$/;
    const patternWithoutCleanings = /^-?[0-9]+\.?[0-9]*,-?[0-9]+\.?[0-9]*,-?[0-9]+\.?[0-9]*,-?[0-9]+\.?[0-9]*$/;
    if (patternWithCleanings.test(customAreaValues))  {
        let cleanings = customAreaValues.split(',')[4];
        customAreaValues = customAreaValues.split(',',4).toString();
        this.startCustomArea(customAreaValues, cleanings);
        this.setState('control.customArea_cleanings', cleanings, true);
    } else if (patternWithoutCleanings.test(customAreaValues)) {
        this.startCustomArea(customAreaValues, this.cleanings);
    }

   ...

    startCustomArea(areaValues, cleanings) {
        this.vacbot.run('customArea', 'start', areaValues, cleanings);
        this.log.info('start cleaning custom area: ' + areaValues + ' (' + cleanings + 'x)');
    }
```

Vielleicht greift auch das `patternWithCleanings` Pattern nicht, bei den Werten mit denen Du es getestet hast ...

**Comment by boriswerner** [comment]
@volkerverkamp auch das hier bitte Mal mit der neuesten GitHub Version testen. Das müsste jetzt mit beiden Möglichkeiten funktionieren

**Comment by volkerverkamp** [comment]
Jup - funktioniert auch (mal abgesehen davon, dass der Deebot seit dem letzten Firmware-Update generell Probleme mit der Spot-/Bereichsreinigung zu haben scheint, auch wenn man diese per App auslöst).
