### ISSUE TITLE
Map Speicherung als .png

### ISSUE THREAD

**Issue by Rushmed** [mrbungle64/ioBroker.ecovacs-deebot#332]
### The feature request

Hallo,

I`m unsing HabPanel for visualization which is not able to show map64 data.
I would love to have an actual map stored as .png- file on the system
For example the  [mihome-vacuum](https://github.com/iobroker-community-adapters/ioBroker.mihome-vacuum) adapter is providing the DP mihome-vacuum.0.cleanmap.mapURL and stores the file at /mihome-vacuum.admin/actualMap_0.png.

**Comment by mrbungle64** [comment]
@Rushmed 

First, I need to make some changes to the underlying library. I will schedule that though.

**Comment by Rushmed** [comment]
Thanks in further!

**Comment by mrbungle64** [comment]
@Rushmed 

I just realized that you may mean the map stored in "map.[ampID].map64" ...

**Comment by Rushmed** [comment]
Hi. I own a DEEBOT OZMO 950 Series.
Yes I just need tha latest data of ecovacs-deebot.0.map.[mapID].map64 stored as a .png file.

**Comment by mrbungle64** [comment]
@Rushmed 

Please try version 1.4.9-alpha.9

The file is automatically stored as `currentMap[MapId].png` in `ecovacs-deebot.[x]` directory.

**Comment by Rushmed** [comment]
Ok, installed 1.4.9-alpha.9 and activated.
![image](https://user-images.githubusercontent.com/59259796/207508523-6149cf5f-38aa-4cb1-b58d-6b97007c9704.png)
Will test today.

How often will the map be stored?
![image](https://user-images.githubusercontent.com/59259796/207508694-e71c89b6-7edf-44a0-9da9-e46cbe3bfc39.png)
Sounds as it will only be saved after complete cleaning?

I was hoping for a file that will be updated every maybe five seconds while cleaning.

**Comment by mrbungle64** [comment]
@Rushmed 

> Ok, installed 1.4.9-alpha.9 and activated. Will test today.
> How often will the map be stored? ![image]

It will be stored every time `map.[mapId].loadMapImage` is triggered.
You don't have to activate it first.

> (https://user-images.githubusercontent.com/59259796/207508694-e71c89b6-7edf-44a0-9da9-e46cbe3bfc39.png) Sounds as it will only be saved after complete cleaning?

That's the other function I implemented first ("Automatisches Herunterladen vom Bild der letzten Reinigung").
But you told me that this is not what you wanted.

> 
> I was hoping for a file that will be updated every maybe five seconds while cleaning.

You hoped that, but you haven't told me yet 😉
But I will not implement that for now. I have to optimize the map creation first.
However, you can already realize this yourself now by creating a Blockly script (for example).

> 
> Looks good so far, implemented the picture im my HabPanel but I did not ran a cleaning yet.

That is because it's an image of the last cleaning ("Automatisches Herunterladen vom Bild der letzten Reinigung").

**Comment by mrbungle64** [comment]
@Rushmed 

> Unfortunately the image of current map does not look that good as last cleaning map. Maybe thats what you ment opimization of map creation.

Yes, the map creation function needs some optimization.
Feel free to create a new issue for that.

**Comment by Rushmed** [comment]
No thanks. Spend your time in more important things!
