### ISSUE TITLE
N8 Pro problems on the newest iobroker adapter version 1.4.4

### ISSUE THREAD

**Issue by MirkoHuf** [mrbungle64/ioBroker.ecovacs-deebot#338]
### Is there an existing issue for this?

- [X] I have searched the existing issues and no issue is describing my issue

### The problem

Hi

After updating to the latest stable iobroker adapter version (1.4.4) there are a lot of problems now.

Log output:
![image](https://user-images.githubusercontent.com/7764831/184482623-570c1358-5959-4a5c-aac9-5050666347b2.png)

Looks fine so far.
Adapter is green:
![image](https://user-images.githubusercontent.com/7764831/184482868-f94ce955-988b-4421-8ed8-5a29ad952053.png)

But nearly all values are empty or null:
![image](https://user-images.githubusercontent.com/7764831/184483115-a633c64e-9f83-46e0-a65d-d6ce1ac92de0.png)

Never had any problems like that before. 
I have already deleted the adapter once (including the data points) and completely recreated it.
Any idear?

### With which model does the problem occur?

Deebot N8 series

### From which source you have installed the adapter?

Stable (default)

### Version of the ioBroker adapter ("info.version")

1.4.4

### Version of the ecovacs-deebot.js library ("info.library.version")

not sure

### Version of the JS controller

4.0.23

### Version of Node.js

v12.22.5

### Operating system

Linux

**Comment by mrbungle64** [comment]
@MirkoHuf 

I think that this is a display issue in ioBroker admin view.
Have you already tried if it's working when you refresh the objects tab or the browser tab?

**Comment by MirkoHuf** [comment]
Yes. browser refresh, iobroker restart, access the values via VIS dashboard - it always the same.

**Comment by mrbungle64** [comment]
@MirkoHuf 

Please set log level to debug and post the output after restart of the adapter instance.

**Comment by MirkoHuf** [comment]
Sorry about that - no idea why. But I deleted the adapter again and set up a new one - to start this one with DEBUG as log value - and now everything works again.

Have a nice weekend!
(Sometimes it helps to just talk about it)
