### ISSUE TITLE
OZMO 950: adapter v0.5.6 einige Datenpunkte wieder leer

### ISSUE THREAD

**Issue by smarteule** [mrbungle64/ioBroker.ecovacs-deebot#36]
Hallo,
bei der v0.5.6 sind einige Datenpunkte leer, Bei  v0.5.5 war alles Okay.

- ecovacs-deebot.0.info.ip
- ecovacs-deebot.0.info.mac
- ecovacs-deebot.0.info.wifiSSID
- ecovacs-deebot.0.info.wifiSignal

![image](https://user-images.githubusercontent.com/61357030/76601376-146cb100-6509-11ea-98e1-461351f04722.png)

**Comment by mrbungle64** [comment]
@smarteule 

Es gab seit der v0.5.5 keine Änderungen die den Ozmo 950 betreffen.

Hattest Du die Datenpunkte vor der Installation der v0.5.6 gelöscht?
Oder sind die geleert worden nach der Installation (von der v0.5.6)?

**Comment by smarteule** [comment]
Hattest Du die Datenpunkte vor der Installation der v0.5.6 gelöscht?   Ja

**Comment by mrbungle64** [comment]
@smarteule 

Ich bin die letzten Änderungen noch mal durchgegangen - ich finde da wirklich nichts, was das Verhalten erklären würde (wenn es vorher bereits funktioniert hat).

Kannst Du das bitte noch mal prüfen, ob die Werte inzwischen aufgetaucht sind?
Falls nicht: bitte den Adapter mal neu starten und ggf. ein paar Minuten warten.

**Comment by smarteule** [comment]
Kann es möglich sein, dass die Cloud manchmal etwas nicht sendet?

Ich habe gestern auf die neue Version geupdated und vorher alle Datenpunkte gelöscht (mache ich eigentlich immer so, um zu sehen, ob alles korrekt eingelesen wird). Danach den Adapter neu gestartet und das Ganze mehrfach, alles ohne Erfolg. Jetzt starte ich den Adapter neu und die Daten sind wieder da. Also ist alles Paletti, es scheint woanders zu liegen.

Mein Problem ist hiermit abgeschlossen.
Danke.

**Comment by mrbungle64** [comment]
> Kann es möglich sein, dass die Cloud manchmal etwas nicht sendet?

Ja, die Dienste von Ecovacs machen nicht den zuverlässigsten Eindruck ;)
Man merkt es ja leider auch immer wieder in der Mobile App ...
