### ISSUE TITLE
Custom Area on yeedi vac hybrid

### ISSUE THREAD

**Issue by guitarhead** [mrbungle64/ioBroker.ecovacs-deebot#386]
### The question

Hi there,
I tried to clean a custom area by setting up a button in iobroker vis with coordinates, like stated in the manual (values x1,y1x2,y2).
I tried several values, like 0,1000,1000,1000 and several variations. All the robot does is starting the cleanup and immediately returning to it's base after the initial starting sequence.
Any advise would be really helpful.

Kind regards and thanks for your amazing work.

Guitarhead

### Which model do you own?

Other model

### Which version of the ioBroker adapter are you currently using?

1.4.8 (alpha)

**Comment by mrbungle64** [comment]
@guitarhead 

Please start a custom area cleaning from the Ecovacs app.
The coordinates should appear in the "map.currentUsedCustomAreaValues" state.
You can also check the coordinates of the last cleaning in "map.lastUsedCustomAreaValues".

Please check if these coordinates work with your device.

**Comment by guitarhead** [comment]
> @guitarhead
> 
> Please start a custom area cleaning from the Ecovacs app. The coordinates should appear in the "map.currentUsedCustomAreaValues" state. You can also check the coordinates of the last cleaning in "map.lastUsedCustomAreaValues".
> 
> Please check if these coordinates work with your device.

Unfortunately the robot doesn't fill the mentioned states. Anything I can do about that?

**Comment by mrbungle64** [comment]
@guitarhead 

> Unfortunately the robot doesn't fill the mentioned states. Anything I can do about that?

You can try this (see "For yeedi models"):
https://github.com/mrbungle64/ecovacs-deebot.js/wiki/Retrieve-coordinates-from-log-output

**Comment by guitarhead** [comment]
> @guitarhead
> 
> Please start a custom area cleaning from the Ecovacs app. The coordinates should appear in the "map.currentUsedCustomAreaValues" state. You can also check the coordinates of the last cleaning in "map.lastUsedCustomAreaValues".
> 
> Please check if these coordinates work with your device.

Unfortunately the robot doesn't fill the states. Anything I can do about that?

> @guitarhead
> 
> > Unfortunately the robot doesn't fill the mentioned states. Anything I can do about that?
> 
> You can try this (see "For yeedi models"): https://github.com/mrbungle64/ecovacs-deebot.js/wiki/Retrieve-coordinates-from-log-output

I tried but this is the error I get, credentials are correct:
`node ./mapInfosYeedi.js | grep 'Last used area values'
(node:1098) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'company' of undefined
    at EcovacsAPI.getVacBot (/home/pi/ecovacs-deebot.js/index.js:456:62)
    at EcovacsAPI.getVacBotObj (/home/pi/ecovacs-deebot.js/index.js:441:17)
    at /home/pi/ecovacs-deebot.js/example/mapInfosYeedi.js:28:26
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1098) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1098) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by mrbungle64** [comment]
@guitarhead 

I think you must set `exports.AUTH_DOMAIN = 'yeedi.com'` in settings.js file

**Comment by guitarhead** [comment]
> 

That did the trick.
Unfortunately the map command times out, but I'll retry tomorrow:

> Current custom area values (x1,y1,x2,y2):
Current spot areas:
Error: Request Timeout (command 'getCachedMapInfo')
