### ISSUE TITLE
"deebotPositionCurrentSpotAreaID" unknown

### ISSUE THREAD

**Issue by Domi920** [mrbungle64/ioBroker.ecovacs-deebot#387]
### Is there an existing issue for this?

- [X] I have searched the existing issues and no issue is describing my issue

### The problem

Hallo,
Seit 17.09.2022 wird der Datenpunkt: ecovacs-deebot.0.map.deebotPositionCurrentSpotAreaID nicht mehr aktualisiert.
Der Datenpunkt hat den Wert "unknown", der auch nicht aktualisiert wird.

Von Github konnte ich nicht installieren.

Gruß Dominik

### With which model does the problem occur?

Deebot OZMO 930

### From which source you have installed the adapter?

Stable (default)

### Version of the ioBroker adapter ("info.version")

1.4.4

### Version of the ecovacs-deebot.js library ("info.library.version")

0.8.2

### Version of the JS controller

4.0.23

### Version of Node.js

v16.17.0

### Operating system

Linux

### Ecovacs device class ("info.deviceClass")

115

### Communication protocol ("info.library.communicationProtocol")

XMPP

### Is the canvas module installed? ("info.library.canvasModuleIsInstalled")

yes (true)

**Comment by mrbungle64** [comment]
@Domi920 

Was war denn am 17.09.2022? 😉 
Ich habe auch noch einen OZMO 930 - bei mir wird der Datenpunkt noch aktualisiert.
Hast du canvas korrekt installiert? Welchen Wert hat der Datenpunkt "info.library.canvasModuleIsInstalled?"

**Comment by Domi920** [comment]
Keine Ahnung was an diesem Datum war, ich sehe nur dass an diesen Datum der Datenpunkt das letzte mal aktualisiert wurde.

Wie installiert man den canvas? 
Mir ist nichts bekannt dass ich speziell dieses Paket installiert habe.

ecovacs-deebot.1.info.library.canvasModuleIsInstalled = true

**Comment by mrbungle64** [comment]
@Domi920 

> ecovacs-deebot.0.info.library.canvasModuleIsInstalled = true
Das sieht schon mal so aus, als wäre canvas schon grundsätzlich installiert

Wie viele Ordner mit einer 9-10 stelligen Nummer hast du im "map" Ordner?

**Comment by Domi920** [comment]
> Wie viele Ordner mit einer 9-10 stelligen Nummer hast du im "map" Ordner?

16 Stück ....
Davon ist aber nur 1 aktiv.
Wenn man den Roboter von der Ladestation runterhebt z. B. zum Reinigen kanns passieren, dass ein neuer Order im Map Verzeichnis angelegt wird.

**Comment by mrbungle64** [comment]
@Domi920 

In dem aktiven Map Ordner sollte in jeder SpotArea (im "spotAreas" Ordner) im Datenpunkt "spotAreaBoundaries" Koordinaten eingetragen sein.

**Comment by Domi920** [comment]
Habe alle Maps Ordner gelöscht, die nicht verwendet werden.
Aber der Standort wird immer noch nicht übermittelt.

im Datenpunkt "spotAreaBoundaries" steht nirgendwo was drin.

**Comment by Domi920** [comment]
Jetzt stehen wieder Daten drin :-)
Aber leider wird "ecovacs-deebot.0.map.deebotPositionCurrentSpotAreaID" immner noch nicht aktualisiert

**Comment by Domi920** [comment]
Wollte kurz nachfragen ob es schon neue Erkenntnisse gibt?

**Comment by mrbungle64** [comment]
@Domi920 

> Wollte kurz nachfragen ob es schon neue Erkenntnisse gibt?

Nein, leider nicht wirklich...

Wird "map.deebotPosition" während der Reinigung aktualisert?

**Comment by Domi920** [comment]
Ja, der Datenpunkt "map.deebotPosition" wird aktualisiert.

Leider wurde schon wieder eine neue Karte angelegt. Und bei dieser neuen Karte ist der Datenpunkt "spotAreaBoundaries" wieder leer.

**Comment by Domi920** [comment]
Habe soeben auch nochmal den Kompletten Order gelöscht & die Instanz wieder gestartet.
Hilft auch nichts. Der Datenpunkt "spotAreaBoundaries" wird nicht mehr beschrieben.

Hilft dir ein Log-Protokoll weiter?

**Comment by mrbungle64** [comment]
@Domi920 

Probier bitte erst mal folgendes:

Erst noch mal alle "map"-Ordner" löschen

Dann
```bash
cd /opt/iobroker/node_modules/
npm rebuild canvas --update-binary
```

und anschließend Instanz neu starten

**Comment by mrbungle64** [comment]
@Domi920 

Dann stell mal den Log-Level auf "silly" bzw "Alles" und filter mal auf "DeebotPositionCurrentSpotAreaID"

**Comment by Domi920** [comment]
<html>
<body>


ecovacs-deebot.0 | 2022-11-17 22:01:05.251 | debug | state change map.deebotPositionCurrentSpotAreaID => unknown
-- | -- | -- | --



</body>
</html>

**Comment by Domi920** [comment]
Jetzt klappts doch wieder?!

<html>
<body>


ecovacs-deebot.0 | 2022-11-17 22:02:00.622 | debug | state change map.deebotPositionCurrentSpotAreaID => 0
-- | -- | -- | --



</body>
</html>

**Comment by Domi920** [comment]
Klappt nun wieder bei beiden 930ern Robotern (2 Instanzen)

**Comment by Domi920** [comment]
> @Domi920
> 
> Probier bitte erst mal folgendes:
> 
> Erst noch mal alle "map"-Ordner" löschen
> 
> Dann
> 
> ```shell
> cd /opt/iobroker/node_modules/
> npm rebuild canvas --update-binary
> ```
> 
> und anschließend Instanz neu starten

Dem Anschein nach hatte das doch geholfen.

Sollte es wieder Probleme geben melde ich mich.

Danke für die Unterstützung!


Gruß Dominik
