### ISSUE TITLE
Failure code 0005: Parameter error. Please try again later.

### ISSUE THREAD

**Issue by ghooser83** [mrbungle64/ioBroker.ecovacs-deebot#392]
### Is there an existing issue for this?

- [X] I have searched the existing issues and no issue is describing my issue

### The problem

Hi there,

since some month my ioBroker can't connect to my Ozmo 950.
Every time i get this Error:

`ecovacs-deebot.0 | 2022-11-18 17:31:20.681 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
-- | -- | -- | --
ecovacs-deebot.0 | 2022-11-18 17:31:20.680 | info | terminating
ecovacs-deebot.0 | 2022-11-18 17:31:20.680 | info | Got terminate signal TERMINATE_YOURSELF
ecovacs-deebot.0 | 2022-11-18 17:31:00.094 | error | Failure code 0005: Parameter error. Please try again later.
ecovacs-deebot.0 | 2022-11-18 17:30:59.919 | info | Reconnecting (4) ...
ecovacs-deebot.0 | 2022-11-18 17:30:53.912 | error | Failure code 0005: Parameter error. Please try again later.
ecovacs-deebot.0 | 2022-11-18 17:30:53.742 | info | Reconnecting (3) ...
ecovacs-deebot.0 | 2022-11-18 17:30:47.735 | error | Failure code 0005: Parameter error. Please try again later.
ecovacs-deebot.0 | 2022-11-18 17:30:47.509 | info | Reconnecting (2) ...
ecovacs-deebot.0 | 2022-11-18 17:30:41.503 | error | Failure code 0005: Parameter error. Please try again later.
ecovacs-deebot.0 | 2022-11-18 17:30:41.322 | info | Reconnecting (1) ...
ecovacs-deebot.0 | 2022-11-18 17:30:35.315 | error | Failure code 0005: Parameter error. Please try again later.
ecovacs-deebot.0 | 2022-11-18 17:30:34.950 | info | starting. Version 1.4.4 in /opt/iobroker/node_modules/iobroker.ecovacs-deebot, node: v14.19.3, js-controller: 4.0.23`

I checkt my login credentials, search online, but didn't find an solution.
The strange thing is, that it worked befor flawlessly.

Does anybody has an idea to this Problem.

Thank you in advance.

### With which model does the problem occur?

Deebot OZMO 950

### From which source you have installed the adapter?

Stable (default)

### Version of the ioBroker adapter ("info.version")

1.4.4

### Version of the ecovacs-deebot.js library ("info.library.version")

0.8.2

### Version of the JS controller

4.0.23

### Version of Node.js

v14.19.3

### Operating system

Linux

**Comment by mrbungle64** [comment]
@ghooser83 

Did you change your password around the time the error messages first appeared?

**Comment by ghooser83** [comment]
No i didn't changed the password, at this time.
I actually changed it today to another password, only consisting of charakters and numbers.
Error stays the same.

Does Error 0005 means "Authentication Error"?

**Comment by mrbungle64** [comment]
@ghooser83 

Are you using the country setting where your account is registered?

**Comment by ghooser83** [comment]
yes i did its germany

**Comment by mrbungle64** [comment]
@ghooser83 

Do you know the date when the error messages first appeared?

**Comment by ghooser83** [comment]
The credentials should be right. I even retypt them in the config fields and also tried to login in the app, which worked.

No i dont have the info when this happend first. I only can tell that this happend approximatly 1-2 month ago

**Comment by ghooser83** [comment]
And as far as i can remember i didn't changed a thing on iobroker or the comlete server it is running on (in this time period).

**Comment by ghooser83** [comment]
Both didn't worked. Here is the resault after deleting the adapter and installing 1.4.8, as discribed:
`
ecovacs-deebot.0 | 2022-11-18 20:03:45.276 | error | Failure code 0005: Parameter error. Please try again later.
-- | -- | -- | --
ecovacs-deebot.0 | 2022-11-18 20:03:45.066 | info | Using login: ecovacs.com
ecovacs-deebot.0 | 2022-11-18 20:03:45.057 | info | Reconnecting (4) ...
ecovacs-deebot.0 | 2022-11-18 20:03:39.050 | error | Failure code 0005: Parameter error. Please try again later.
ecovacs-deebot.0 | 2022-11-18 20:03:38.840 | info | Using login: ecovacs.com
ecovacs-deebot.0 | 2022-11-18 20:03:38.829 | info | Reconnecting (3) ...
ecovacs-deebot.0 | 2022-11-18 20:03:32.821 | error | Failure code 0005: Parameter error. Please try again later.
ecovacs-deebot.0 | 2022-11-18 20:03:32.618 | info | Using login: ecovacs.com
ecovacs-deebot.0 | 2022-11-18 20:03:32.608 | info | Reconnecting (2) ...
ecovacs-deebot.0 | 2022-11-18 20:03:26.602 | error | Failure code 0005: Parameter error. Please try again later.
ecovacs-deebot.0 | 2022-11-18 20:03:26.166 | info | Using login: ecovacs.com
ecovacs-deebot.0 | 2022-11-18 20:03:26.155 | info | Reconnecting (1) ...
ecovacs-deebot.0 | 2022-11-18 20:03:20.146 | error | Failure code 0005: Parameter error. Please try again later.
ecovacs-deebot.0 | 2022-11-18 20:03:19.667 | info | Using login: ecovacs.com
ecovacs-deebot.0 | 2022-11-18 20:03:19.516 | info | starting. Version 1.4.8 in /opt/iobroker/node_modules/iobroker.ecovacs-deebot, node: v14.19.3, js-controller: 4.0.23
`

**Comment by mrbungle64** [comment]
@ghooser83 

I found [this issue](https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/issues/177), but there's no solution because the user didn't provide enough information ...

Are you using a Germanic Umlaut in your email address?

**Comment by ghooser83** [comment]
@mrbungle64 
There is no Germanic Umlaut in my email adress. Also not in the password ...

Is there any log or something which could provide further information.

**Comment by mrbungle64** [comment]
@ghooser83 

You can install the library and use the example app to provide log output:
https://github.com/mrbungle64/ecovacs-deebot.js/wiki/Example-apps

Please use the following command:
```bash
NODE_ENV=dev node ./app2.js
```

**Comment by ghooser83** [comment]
I have installed the Exampe-apps and this is the output:

`[EcovacsAPI] Setting up EcovacsAPI instance
[EcovacsAPI] Calling main api user/login with {"account":"...@googlemail.com","password":"..."}
[EcoVacsAPI] callUserAuthApi calling https://gl-de-api.ecovacs.com/v1/private/DE/EN/29365581224dd02b2f41fdfc85646c4a/global_e/2.2.3/google_play/1/user/login
[EcoVacsAPI] callUserAuthApi config account=...%40googlemail.com&password=...&authTimespan=1668955218080&requestId=14042c47ed08753344b56934212268de&authTimeZone=GMT-8&authAppkey=1520391301804&authSign=6b9b91754570ed7680687759c911c831
[EcoVacsAPI] callUserAuthApi data: {"code":"0005","msg":"Parameter error. Please try again later.","time":1668945119064}
[EcoVacsAPI] callUserAuthApi error: Error: Failure code 0005: Parameter error. Please try again later.
Failure in connecting: Failure code 0005: Parameter error. Please try again later.
`
I changed the mail address and pw to ...

:-/

**Comment by ghooser83** [comment]
When i deaktivate the instance there is the following message in the log:


ecovacs-deebot.0 | 2022-11-24 01:02:29.609 | warn | Terminated (NO_ADAPTER_CONFIG_FOUND): Without reason
-- | -- | -- | --
ecovacs-deebot.0 | 2022-11-24 01:02:29.518 | error | adapter disabled

Is this normal?

**Comment by mrbungle64** [comment]
@ghooser83 

> When i deaktivate the instance

What do you mean by "deaktivate"?

**Comment by ghooser83** [comment]
When i pause the app in "Instances"

**Comment by mrbungle64** [comment]
@ghooser83 

I checked my log and found 2 entries for other adapter instances where this message also appeared.
It doesn't seem to be a big problem.

**Comment by mrbungle64** [comment]
@ghooser83 

Btw.: I'm pretty sure that the "Failure code 0005: Parameter error" has something to do with this call:

```
[EcoVacsAPI] callUserAuthApi calling https://gl-de-api.ecovacs.com/v1/private/DE/EN/29365581224dd02b2f41fdfc85646c4a/global_e/2.2.3/google_play/1/user/login
[EcoVacsAPI] callUserAuthApi config account=...%40googlemail.com&password=...&authTimespan=1668955218080&requestId=14042c47ed08753344b56934212268de&authTimeZone=GMT-8&authAppkey=1520391301804&authSign=6b9b91754570ed7680687759c911c831
```

But I still don't know this works for 99,9% accounts, but not for your account...

**Comment by ghooser83** [comment]
@mrbungle64 
i now tried also setting up a new account and couldn't connect. Getting the same error.
Is there a http:// request address i could check with my browser. 

Also tried to connect with ecovacs Id. Didn't work :-/

**Comment by ghooser83** [comment]
@mrbungle64 
error still exists after installing version 1.4.11.

Is it possible that ecovacs refused especially my connection. Maybe due to to much readouts or what ever.

**Comment by mrbungle64** [comment]
@ghooser83 

> @mrbungle64 error still exists after installing version 1.4.11.

This is actually no surprise, since nothing has changed in the authentication process...
Unfortunately, since there is no documentation on this, I still can't say anything about what's going wrong here. And there are also still no further reports of such issues.

> Is it possible that ecovacs refused especially my connection. Maybe due to to much readouts or what ever.

This is possible by all means, but this is pure speculation ...

**Comment by ghooser83** [comment]
@mrbungle64 
I appriciate your help. Is there a spacial port needed for the communication, cause i let   iobroker run in docker container and have several other running parallel. Nextcloud for example with ports 80 and 443 in use.

**Comment by mrbungle64** [comment]
> I have installed the Exampe-apps and this is the output:
> 
> ```
> [EcovacsAPI] Setting up EcovacsAPI instance
> [EcovacsAPI] Calling main api user/login with {"account":"...@googlemail.com","password":"..."}
> [EcoVacsAPI] callUserAuthApi calling https://gl-de-api.ecovacs.com/v1/private/DE/EN/29365581224dd02b2f41fdfc85646c4a/global_e/2.2.3/google_play/1/user/login
> [EcoVacsAPI] callUserAuthApi config account=...%40googlemail.com&password=...&authTimespan=1668955218080&requestId=14042c47ed08753344b56934212268de&authTimeZone=GMT-8&authAppkey=1520391301804&authSign=6b9b91754570ed7680687759c911c831
> [EcoVacsAPI] callUserAuthApi data: {"code":"0005","msg":"Parameter error. Please try again later.","time":1668945119064}
> [EcoVacsAPI] callUserAuthApi error: Error: Failure code 0005: Parameter error. Please try again later.
> Failure in connecting: Failure code 0005: Parameter error. Please try again later.
> ```
> 
> I changed the mail address and pw to ...
> 
> :-/

Have you already tried to run the example app on a system other than your ioBroker docker container?

**Comment by ghooser83** [comment]
@mrbungle64 
No i didn't tried this. Good tip i will test it. Tanks.

**Comment by mrbungle64** [comment]
@ghooser83 

> @mrbungle64 No i didn't tried this. Good tip i will test it. Tanks.

Have you already tried it?

**Comment by ghooser83** [comment]
I turned of the reverse proxy and tried to use it in the iobroker container witch is in docker network_mode host. There wasn't any difference.

Do you need port forwarding in your router that your application works?

**Comment by mrbungle64** [comment]
@ghooser83 

> Do you need port forwarding in your router that your application works?

No

**Comment by ghooser83** [comment]
@mrbungle64 than it shouldtn't have to do with reverse proxy for my understanding. It should only handle incomming connections....

**Comment by ghooser83** [comment]
I could solve the issue coincidentally, cause i get problems with other iobroker adapters. My iobroker runs as a docker container in an vm which is hosted on an privat home server. I recognized that the Time in the logs of ioboker is off by two hours. So my system time wasnt right caused by an issue between the server and the vm.

I hope that helps others. Took a long time to find the problem.

**Comment by mrbungle64** [comment]
@ghooser83 

> I could solve the issue coincidentally, cause i get problems with other iobroker adapters. My iobroker runs as a docker container in an vm which is hosted on an privat home server. I recognized that the Time in the logs of ioboker is off by two hours. So my system time wasnt right caused by an issue between the server and the vm.

I'm glad to hear that you could finally solve the problem.

> I hope that helps others. Took a long time to find the problem.

Thanks for sharing the information 👍🏻
