### ISSUE TITLE
Map creating X1 OMNI (cleaninglog.lastCleaningMapImageURL)

### ISSUE THREAD

**Issue by senger1985** [mrbungle64/ioBroker.ecovacs-deebot#394]
### The question

Is it possible, that the adapter create a map, from the X1 OMNI?
I see the old map, from my old T8 and the state will not be updated.

### Which model do you own?

Deebot X1 series

### Which version of the ioBroker adapter are you currently using?

1.4.8

**Comment by mrbungle64** [comment]
@senger1985 

This is a [known issue](https://github.com/mrbungle64/ioBroker.ecovacs-deebot#known-issues).
It seems that Ecovacs changed some parts of the API for the X1 series.
We will have to wait until I have access to such a device or until someone else has implemented the map image functionality for the X1 series.

Deebot 4 Home Assistant has also a [similar problem](https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/issues/268).

**Comment by senger1985** [comment]
Can I help to sent you some informations, oder debugs?

**Comment by mrbungle64** [comment]
@senger1985 

You can install the library and use the example app to check if there is still a response to the commands to retrieve the map data: https://github.com/mrbungle64/ecovacs-deebot.js/wiki/Example-apps

Please use `mapDataObject.js` instead of `app2.js`

```bash
NODE_ENV=dev node ./mapDataObject.js
```

**Comment by mrbungle64** [comment]
@senger1985 

Starting with version 1.4.9-alpha.4 the values of the cleaning log should now work completely for the X1 OMNI (incl. "cleaninglog.lastCleaningMapImageURL")

**Comment by senger1985** [comment]
@mrbungle64 
Thx, for your efforts
I will report tomorrow

**Comment by djalexz** [comment]
> @senger1985
> 
> Starting with version 1.4.9-alpha.4 the values of the cleaning log should now work completely for the X1 OMNI (incl. "cleaninglog.lastCleaningMapImageURL")

Hi, there is an error on open the Image URL of the last cleaning:

`{"code":3001,"message":"sign check unpassed or userid was empty"}`

Thank you

**Comment by senger1985** [comment]
Fixed in 1.4.9-alpha.8

**Comment by mrbungle64** [comment]
> > @senger1985
> > Starting with version 1.4.9-alpha.4 the values of the cleaning log should now work completely for the X1 OMNI (incl. "cleaninglog.lastCleaningMapImageURL")
> 
> Hi, there is an error on open the Image URL of the last cleaning:
> 
> `{"code":3001,"message":"sign check unpassed or userid was empty"}`
> 
> Thank you

You cannot open the URL directly. With version 1.4.9-alpha.7 I implemented an option to automatically download the last cleaning map image as a png file.

The path to the latest image file is stored in the state "cleaninglog.lastCleaningMapImageFile".

But you have to enable the function in the settings first ("experimental" tab).

**Comment by djalexz** [comment]
Works very well. Many thanks.
Very cool adapter.

Here´s what i do with it:

![image](https://user-images.githubusercontent.com/11389551/207523648-b456e6fa-9492-40e4-b43b-df573d1765e1.png)

**Comment by mrbungle64** [comment]
@djalexz 

Thanks for your feedback!
Your implementation looks great 👍🏻
