### ISSUE TITLE
Issue with Ozmo 610

### ISSUE THREAD

**Issue by NoOne86** [mrbungle64/ioBroker.ecovacs-deebot#4]
ecovacs-deebot.0 | 2019-12-10 14:50:48.204 | error | (18659) Failure in connecting!
-- | -- | -- | --
ecovacs-deebot.0 | 2019-12-10 14:50:47.649 | info | (18659) reconnecting ...
ecovacs-deebot.0 | 2019-12-10 14:50:17.623 | error | (18659) Failure in connecting!
ecovacs-deebot.0 | 2019-12-10 14:50:16.961 | info | (18659) starting. Version 0.2.0 in /opt/iobroker/node_modules/iobroker.ecovacs-deebot, node: v10.17.0
ecovacs-deebot.0 | 2019-12-10 14:50:12.351 | info | (18640) Terminated (START_IMMEDIATELY_AFTER_STOP): Without reason
ecovacs-deebot.0 | 2019-12-10 14:50:12.349 | info | (18640) terminating

**Comment by mrbungle64** [comment]
Hi @NoOne86,

this message ("Failure in connecting!") indicates an error when connecting to the cloud/server.
Have you already checked the adapter configuration (email, password and country code)?

It also may help to increase the value in "Max. auto retries if connection fails" because sometimes there's no connection even if the settings are correct.

**Comment by NoOne86** [comment]
Yes the information are correct i checked it twice with the app.
The Max auto retries is 10.
If i change to a false email i become this error

ecovacs-deebot.0 | 2019-12-10 20:29:09.686 | error | (20277) Failure in connecting!
-- | -- | -- | --
ecovacs-deebot.0 | 2019-12-10 20:29:09.199 | info | (20277) starting. Version 0.2.0 in /opt/iobroker/node_modules/iobroker.ecovacs-deebot, node: v10.17.0
host.iobroker | 2019-12-10 20:29:07.081 | info | instance system.adapter.ecovacs-deebot.0 started with pid 20277
host.iobroker | 2019-12-10 20:29:05.029 | info | instance system.adapter.ecovacs-deebot.0 terminated with code 156 (156)
host.iobroker | 2019-12-10 20:29:05.028 | error | Caught by controller[0]: [EcoVacsAPI] incorrect email or password

**Comment by NoOne86** [comment]
ähhhhm ????? gerade ist das scheis ding einfach auf grün gesprungen als ich auf den debug schalten wollte um das log file anzuschauen

**Comment by mrbungle64** [comment]
ok, das ist ja schon mal gut ;)
Kannst du deinen Ozmo 610 über die Buttons unter 'control' steuern und sind die states wie z.B. 'info.battery' mit Werten befüllt?

**Comment by NoOne86** [comment]
chargecontent_copy | go back to charging station | state | button |   |   | room_service | editdeletebuild
-- | -- | -- | -- | -- | -- | -- | --
clean | start automatic cleaning | state | button |   |   | room_service | editdeletebuild
edge | start edge cleaning | state | button |   |   | room_service | editdeletebuild
spot | start spot cleaning | state | button |   |   | room_service | editdeletebuild
stop | stop cleaning | state | button |   |   | room_service | editdeletebuild
history |   |   |   |   |   |   | delete
dateOfLastStartCharging | Human readable timestamp of last start charging | state | value.datetime |   |   |   | editdeletebuild
dateOfLastStartCleaning | Human readable timestamp of last start cleaning | state | value.datetime |   |   |   | editdeletebuild
dateOfLastStateChange | Human readable timestamp of last state change | state | value.datetime |   |   | 10.12.2019 21:24:12 | editdeletebuild
timestampOfLastStartCharging | Timestamp of last start charging | state | value.datetime |   |   |   | editdeletebuild
timestampOfLastStartCleaning | Timestamp of last start cleaning | state | value.datetime |   |   |   | editdeletebuild
timestampOfLastStateChange | Timestamp of last state change | state | value.datetime |   |   | 1576009452 | editdeletebuild
info |   |   |   |   |   |   | delete
battery | Battery status | state | value.battery |   |   | 35 % | editdeletebuild
chargestatus | Charge status | state | indicator.status |   |   |   | editdeletebuild
cleanstatus | Clean status | state | indicator.status |   |   |   | editdeletebuild
connection | Connection status | state | indicator.connected |   |   | true | editdeletebuild
deviceName | Name of the device | state | text |   |   |   | editdeletebuild
error | Error messages | state | indicator.error |   |   |

**Comment by NoOne86** [comment]
Das sind die aktuellen Werte :-)
Buttons gehen und Akku passt perfekt (er arbeitet gerade sehr schwer der arme Kerl)
Also Perfekt sozusagen

**Comment by mrbungle64** [comment]
Ja super :)

Was mich aber wundert ist, dass unter 'deviceName', 'cleanstatus', 'timestampOfLastStartCleaning' und 'dateOfLastStartCleaning' noch keine Werte sind.

Hat der Saugroboter in der App einen Namen?
Der müsste dann eigentlich auch unter 'deviceName' stehen ...

**Comment by NoOne86** [comment]
Ja es kommen nicht alle Werte an.
Hab ihm jetzt in der App einen Namen verpasst dann taucht der Name auch auf.

**Comment by NoOne86** [comment]
Kann ich irgendwo einsehen welche Daten von Ecovacs kommen ?

**Comment by mrbungle64** [comment]
> Ja es kommen nicht alle Werte an.
> Hab ihm jetzt in der App einen Namen verpasst dann taucht der Name auch auf.

ok, dann habe ich auch schon eine Vermutung.
Evtl. heißt der Event ("CleanReport"), bei welchem div. Werte gesetzt werden anders bei diesem Modell. Leider gibt es ja keine offizielle API-Dokumentation wo man mal nachschauen könnte...

**Comment by NoOne86** [comment]
Kann ich dir die Werte irgendwie zur Verfügung stellen ?

**Comment by mrbungle64** [comment]
> Kann ich irgendwo einsehen welche Daten von Ecovacs kommen ?
Nicht direkt, aber bei den States sind das folgende:
* deviceName
* battery
* cleanstatus
* chargestatus

Eine offizielle API-Dokumentation gibt es leider nicht

**Comment by mrbungle64** [comment]
> Kann ich dir die Werte irgendwie zur Verfügung stellen ?

Vielen Dank für Dein Angebot :)
Ich müsste mal ein bisschen mehr Debug-Code einbauen.
Ich melde mich bei Dir wenn es entsprechend eine neue Version gibt, okay?

**Comment by mrbungle64** [comment]
Noch eine Frage:
Wird 'chargestatus' während des Ladens befüllt?

**Comment by NoOne86** [comment]
Nein leider auch nicht den er lädt gerade :-) und die einzigen werte sind


chargecontent_copy | go back to charging station | state | button |   |   | room_service | editdeletebuild
-- | -- | -- | -- | -- | -- | -- | --
clean | start automatic cleaning | state | button |   |   | room_service | editdeletebuild
edge | start edge cleaning | state | button |   |   | room_service | editdeletebuild
spot | start spot cleaning | state | button |   |   | room_service | editdeletebuild
stop | stop cleaning | state | button |   |   | room_service | editdeletebuild
history |   |   |   |   |   |   | delete
dateOfLastStartCharging | Human readable timestamp of last start charging | state | value.datetime |   |   |   | editdeletebuild
dateOfLastStartCleaning | Human readable timestamp of last start cleaning | state | value.datetime |   |   |   | editdeletebuild
dateOfLastStateChange | Human readable timestamp of last state change | state | value.datetime |   |   | 10.12.2019 22:00:11 | editdeletebuild
timestampOfLastStartCharging | Timestamp of last start charging | state | value.datetime |   |   |   | editdeletebuild
timestampOfLastStartCleaning | Timestamp of last start cleaning | state | value.datetime |   |   |   | editdeletebuild
timestampOfLastStateChange | Timestamp of last state change | state | value.datetime |   |   | 1576011611 | editdeletebuild
info |   |   |   |   |   |   | delete
battery | Battery status | state | value.battery |   |   | 38 % | editdeletebuild
chargestatus | Charge status | state | indicator.status |   |   |   | editdeletebuild
cleanstatus | Clean status | state | indicator.status |   |   |   | editdeletebuild
connection | Connection status | state | indicator.connected |   |   | true | editdeletebuild
deviceName | Name of the device | state | text |   |   | Supersaugi | editdeletebuild

**Comment by mrbungle64** [comment]
> Nein leider auch nicht den er lädt gerade :-) und die einzigen werte sind

Ich habe noch mal anhand des [Ozmo python scripts](https://github.com/Ligio/ozmo) versucht ein paar Werte zu erraten, welche von Ecovacs kommen.

Es steht eine neue Version bereit ;)
Einfach noch mal per "Installieren aus eigener URL" => "beliebig":
https://github.com/mrbungle64/ioBroker.ecovacs-deebot.git

**Comment by NoOne86** [comment]
Schlechte Nachrichten jetzt startet er nicht mehr und die Akku Anzeige sagt nur noch %


controlcontent_copy |   |   |   |   |   |   | delete
-- | -- | -- | -- | -- | -- | -- | --
charge | go back to charging station | state | button | Küche |   | room_service | editdeletebuild
clean | start automatic cleaning | state | button |   |   | room_service | editdeletebuild
edge | start edge cleaning | state | button |   |   | room_service | editdeletebuild
spot | start spot cleaning | state | button |   |   | room_service | editdeletebuild
stop | stop cleaning | state | button | Küche |   | room_service | editdeletebuild
history |   |   |   |   |   |   | delete
dateOfLastStartCharging | Human readable timestamp of last start charging | state | value.datetime |   |   |   | editdeletebuild
dateOfLastStartCleaning | Human readable timestamp of last start cleaning | state | value.datetime |   |   |   | editdeletebuild
dateOfLastStateChange | Human readable timestamp of last state change | state | value.datetime |   |   | 11.12.2019 00:15:17 | editdeletebuild
timestampOfLastStartCharging | Timestamp of last start charging | state | value.datetime |   |   |   | editdeletebuild
timestampOfLastStartCleaning | Timestamp of last start cleaning | state | value.datetime |   |   |   | editdeletebuild
timestampOfLastStateChange | Timestamp of last state change | state | value.datetime |   |   | 1576019717 | editdeletebuild
info |   |   |   |   |   |   | delete
battery | Battery status | state | value.battery |   |   | % | editdeletebuild
chargestatus | Charge status | state | indicator.status |   |   |   | editdeletebuild
cleanstatus | Clean status | state | indicator.status |   |   |   | editdeletebuild
connection | Connection status | state | indicator.connected |   |   | true | editdeletebuild
deviceName | Name of the device | state | text |   |   | Supersaugi | editdeletebuild
error | Error messages | state | indicator.error |   |   |   | editdeletebuild

**Comment by mrbungle64** [comment]
> Schlechte Nachrichten jetzt startet er nicht mehr und die Akku Anzeige sagt nur noch %

Hmm, das wundert mich jetzt ein bisschen, dass er gar nicht mehr startet, weil ich diesbezüglich eigentlich nichts geändert hatte - aber es kann ja trotzdem bei deinem Device einen Seiteneffekt haben ...

Ich habe noch mal eine Version mit kleineren Änderungen bereitgestellt und die eigentliche Änderung wieder rückgängig gemacht. Dabei habe ich aber das Logging ein klein wenig erweitert.

**Comment by NoOne86** [comment]
controlcontent_copy |   |   |   |   |   |   | delete
-- | -- | -- | -- | -- | -- | -- | --
charge | go back to charging station | state | button | Küche |   | room_service | editdeletebuild
clean | start automatic cleaning | state | button |   |   | room_service | editdeletebuild
edge | start edge cleaning | state | button |   |   | room_service | editdeletebuild
spot | start spot cleaning | state | button |   |   | room_service | editdeletebuild
stop | stop cleaning | state | button | Küche |   | room_service | editdeletebuild
history |   |   |   |   |   |   | delete
dateOfLastStartCharging | Human readable timestamp of last start charging | state | value.datetime |   |   | 11.12.2019 16:15:42 | editdeletebuild
dateOfLastStartCleaning | Human readable timestamp of last start cleaning | state | value.datetime |   |   | 11.12.2019 12:42:31 | editdeletebuild
dateOfLastStateChange | Human readable timestamp of last state change | state | value.datetime |   |   | 11.12.2019 21:33:56 | editdeletebuild
timestampOfLastStartCharging | Timestamp of last start charging | state | value.datetime |   |   | 1576077342 | editdeletebuild
timestampOfLastStartCleaning | Timestamp of last start cleaning | state | value.datetime |   |   | 1576064551 | editdeletebuild
timestampOfLastStateChange | Timestamp of last state change | state | value.datetime |   |   | 1576096436 | editdeletebuild
info |   |   |   |   |   |   | delete
battery | Battery status | state | value.battery |   |   | 99 % | editdeletebuild
chargestatus | Charge status | state | indicator.status |   |   | charging | editdeletebuild
cleanstatus | Clean status | state | indicator.status |   |   |   | editdeletebuild
connection | Connection status | state | indicator.connected |   |   | true | editdeletebuild
deviceName | Name of the device | state | text |   |   | Supersaugi | editdeletebuild
error | Error messages | state | indicator.error |   |   |   | editdeletebuild

**Comment by NoOne86** [comment]
Na das nenne ich doch 99 % erfolg 
alle Daten scheinen nun anzukommen leider geht das fern Starten noch nicht :-)

**Comment by mrbungle64** [comment]
> Na das nenne ich doch 99 % erfolg
> alle Daten scheinen nun anzukommen 

sehr gut :)

> leider geht das fern Starten noch nicht :-)

"fern Starten" bedeutet über die Buttons unter 'control'?

**Comment by NoOne86** [comment]
Ja genau

**Comment by mrbungle64** [comment]
Wird im Log etwas wie "run: clean" ausgegeben, wenn du die Buttons betätigst?
Oder gibt es da Fehlermeldungen?

**Comment by NoOne86** [comment]
ecovacs-deebot.0 | 2019-12-11 21:35:28.236 | info | (25485) run: clean
-- | -- | -- | --
ecovacs-deebot.0 | 2019-12-11 21:33:54.390 | info | (25485) Devices:[{"did":"E0001076118608330161","name":"E0001076118608330161","class":"130","resource":"atom","nick":"Supersaugi","company":"eco-legacy"}]

Ja wird es

**Comment by mrbungle64** [comment]
Hallo @NoOne86,

es steht eine neue Version des Adapters zur Verfügung.
Ich würde mich über Feedback freuen, wie Dein Gerät damit funktioniert.

**Comment by mrbungle64** [comment]
Hallo @NoOne86,

der Adapter ist inzwischen auch über Latest Repo verfügbar.
Würde mich über Feedback freuen :)

**Comment by NoOne86** [comment]
@mrbungle64 
Also ich kann dir 100% Erfolg bescheinigen jeder Button geht und alle Werte werden angezeigt :-)

consumable | Consumable | channel |   |   |   |   | editdelete
-- | -- | -- | -- | -- | -- | -- | --
filter | Filter lifespan | state | level |   |   | 83 % | editdeletebuild
main_brush | Main brush lifespan | state | level |   |   | 83 % | editdeletebuild
side_brush | Side brush lifespan | state | level |   |   | 83 % | editdeletebuild
control | Control | channel |   |   |   |   | editdelete
charge | go back to charging station | state | button | Küche |   | room_service | editdeletebuild
clean | start automatic cleaning | state | button | Küche |   | room_service | editdeletebuild
customArea | Custom area | state | value |   |   |   | editdeletebuild
customArea_cleanings | Custom area cleanings | state | value |   |   | 1 | editdeletebuild
edge | start edge cleaning | state | button |   |   | room_service | editdeletebuild
pause | pause cleaning | state | button |   |   | room_service | editdeletebuild
playSound | play sound for locating the device | state | button |   |   | room_service | editdeletebuild
spot | start spot cleaning | state | button |   |   | room_service | editdeletebuild
spotArea | Cleaning multiple spot areas (comma-separated list) | state | value |   |   |   | editdeletebuild
stop | stop cleaning | state | button | Küche |   | room_service | editdeletebuild
waterLevel | Water level | state | level |   |   | low(1) | editdeletebuild
history | History | channel |   |   |   |   | editdelete
dateOfLastStartCharging | Human readable timestamp of last start charging | state | value.datetime |   |   | 05.02.2020 22:27:32 | editdeletebuild
dateOfLastStartCleaning | Human readable timestamp of last start cleaning | state | value.datetime |   |   | 05.02.2020 22:27:32 | editdeletebuild
dateOfLastStateChange | Human readable timestamp of last state change | state | value.datetime |   |   | 05.02.2020 22:30:31 | editdeletebuild
timestampOfLastStartCharging | Timestamp of last start charging | state | value.datetime |   |   | 1580938052 | editdeletebuild
timestampOfLastStartCleaning | Timestamp of last start cleaning | state | value.datetime |   |   | 1580938052 | editdeletebuild
timestampOfLastStateChange | Timestamp of last state change | state | value.datetime |   |   | 1580938231 | editdeletebuild
info | Information | channel |   |   |   |   | editdelete
battery | Battery status | state | value.battery |   |   | 99 % | editdeletebuild
chargestatus | Charge status | state | indicator.status | Küche |   | charging | editdeletebuild
cleanstatus | Clean status | state | indicator.status |   |   | stop | editdeletebuild
communicationProtocol | Communication protocol | state | text |   |   | XMPP | editdeletebuild
connection | Connection status | state | indicator.connected |   |   | true | editdeletebuild
deviceClass | Class number of the device | state | text |   |   | 130 | editdeletebuild
deviceName | Name of the device | state | text |   |   | Supersaugi | editdeletebuild
deviceStatus | Device status | state | indicator.status |   |   | charging | editdeletebuild
error | Error messages | state | indicator.error |   |   |  

Also von daher :-)
Viel Dank und Perfekte Arbeit :-)

**Comment by mrbungle64** [comment]
> @mrbungle64
> Also ich kann dir 100% Erfolg bescheinigen jeder Button geht und alle Werte werden angezeigt :-) 
...
> Also von daher :-)
> Viel Dank und Perfekte Arbeit :-)

Hallo @NoOne86,

das freut mich! Vielen Dank für die Info :)
Ich schließe dann diesen Issue, ok?

**Comment by NoOne86** [comment]
Erledigt :-)
