### ISSUE TITLE
Deebot 901 chargestatus und devicestatus

### ISSUE THREAD

**Issue by helfi9999** [mrbungle64/ioBroker.ecovacs-deebot#41]
Hi,
habe festgestellt das der chargestatus und der devicestatus immer gleich sind.
Normalerweise müsste doch der chargestatus nur "charging" und "idle" anzeigen aber nicht "returning" oder sehe ich das verkehrt.

> 

ecovacs-deebot.0 | 2020-03-19 10:11:53.976 | debug | (28619) system.adapter.admin.0: logging true
-- | -- | -- | --
ecovacs-deebot.0 | 2020-03-19 10:10:28.046 | debug | (28619) state change info.battery => 91
ecovacs-deebot.0 | 2020-03-19 10:08:44.676 | debug | (28619) system.adapter.admin.0: logging false
ecovacs-deebot.0 | 2020-03-19 10:08:15.040 | debug | (28619) system.adapter.admin.0: logging true
ecovacs-deebot.0 | 2020-03-19 10:05:31.327 | debug | (28619) state change info.battery => 90
ecovacs-deebot.0 | 2020-03-19 10:04:11.001 | debug | (28619) state change info.battery => 89
ecovacs-deebot.0 | 2020-03-19 10:04:09.999 | debug | (28619) state change info.battery => 90
ecovacs-deebot.0 | 2020-03-19 10:02:09.994 | debug | (28619) state change info.battery => 89
ecovacs-deebot.0 | 2020-03-19 10:02:08.991 | debug | (28619) state change info.battery => 90
ecovacs-deebot.0 | 2020-03-19 10:02:08.237 | debug | (28619) state change info.battery => 89
ecovacs-deebot.0 | 2020-03-19 10:00:07.289 | debug | (28619) state change info.battery => 88
ecovacs-deebot.0 | 2020-03-19 10:00:05.989 | debug | (28619) state change info.battery => 89
ecovacs-deebot.0 | 2020-03-19 09:58:43.993 | debug | (28619) state change info.battery => 88
ecovacs-deebot.0 | 2020-03-19 09:58:03.989 | debug | (28619) state change info.battery => 87
ecovacs-deebot.0 | 2020-03-19 09:58:02.989 | debug | (28619) state change info.battery => 88
ecovacs-deebot.0 | 2020-03-19 09:56:02.023 | debug | (28619) state change info.battery => 87
ecovacs-deebot.0 | 2020-03-19 09:56:00.979 | debug | (28619) state change info.battery => 88
ecovacs-deebot.0 | 2020-03-19 09:55:19.984 | debug | (28619) state change info.battery => 87
ecovacs-deebot.0 | 2020-03-19 09:53:58.987 | debug | (28619) state change info.battery => 86
ecovacs-deebot.0 | 2020-03-19 09:53:57.986 | debug | (28619) state change info.battery => 87
ecovacs-deebot.0 | 2020-03-19 09:51:42.999 | debug | (28619) state change info.error =>
ecovacs-deebot.0 | 2020-03-19 09:51:42.998 | debug | (28619) state change info.deviceStatus => charging
ecovacs-deebot.0 | 2020-03-19 09:51:42.991 | debug | (28619) state change info.chargestatus => charging
ecovacs-deebot.0 | 2020-03-19 09:51:02.392 | debug | (28619) state change info.deviceStatus => returning
ecovacs-deebot.0 | 2020-03-19 09:51:02.391 | debug | (28619) state change info.chargestatus => returning
ecovacs-deebot.0 | 2020-03-19 09:51:02.390 | debug | (28619) state change info.battery => 86
ecovacs-deebot.0 | 2020-03-19 09:51:02.387 | debug | (28619) state change info.deviceStatus => returning
ecovacs-deebot.0 | 2020-03-19 09:51:02.386 | debug | (28619) state change info.chargestatus => returning
ecovacs-deebot.0 | 2020-03-19 09:51:02.380 | debug | (28619) state change info.deviceStatus => stopped
ecovacs-deebot.0 | 2020-03-19 09:51:02.375 | debug | (28619) state change info.cleanstatus => stop
ecovacs-deebot.0 | 2020-03-19 09:49:52.897 | debug | (28619) state change info.battery => 87
ecovacs-deebot.0 | 2020-03-19 09:48:44.889 | debug | (28619) state change info.battery => 88
ecovacs-deebot.0 | 2020-03-19 09:47:39.607 | debug | (28619) state change info.battery => 89
ecovacs-deebot.0 | 2020-03-19 09:46:31.847 | debug | (28619) state change info.battery => 90
ecovacs-deebot.0 | 2020-03-19 09:45:55.991 | debug | (28619) state change consumable.filter => 90
ecovacs-deebot.0 | 2020-03-19 09:45:24.852 | debug | (28619) state change info.battery => 91
ecovacs-deebot.0 | 2020-03-19 09:44:18.845 | debug | (28619) state change info.battery => 92
ecovacs-deebot.0 | 2020-03-19 09:43:14.836 | debug | (28619) state change info.battery => 93
ecovacs-deebot.0 | 2020-03-19 09:42:08.800 | debug | (28619) state change info.battery => 94
ecovacs-deebot.0 | 2020-03-19 09:41:01.793 | debug | (28619) state change info.battery => 95
ecovacs-deebot.0 | 2020-03-19 09:39:57.763 | debug | (28619) state change info.battery => 96
ecovacs-deebot.0 | 2020-03-19 09:39:55.977 | debug | (28619) state change consumable.side_brush => 91
ecovacs-deebot.0 | 2020-03-19 09:38:49.791 | debug | (28619) state change info.battery => 97
ecovacs-deebot.0 | 2020-03-19 09:38:43.396 | debug | (28619) system.adapter.admin.0: logging false
ecovacs-deebot.0 | 2020-03-19 09:38:24.292 | debug | (28619) system.adapter.admin.0: logging true
ecovacs-deebot.0 | 2020-03-19 09:37:42.822 | debug | (28619) state change info.battery => 98
ecovacs-deebot.0 | 2020-03-19 09:36:37.018 | debug | (28619) state change info.battery => 99
ecovacs-deebot.0 | 2020-03-19 09:35:26.747 | debug | (28619) state change info.deviceStatus => cleaning
ecovacs-deebot.0 | 2020-03-19 09:35:26.743 | debug | (28619) state change info.chargestatus => idle
ecovacs-deebot.0 | 2020-03-19 09:35:21.705 | info | (28619) Unhandled cleanstatus: undefined
ecovacs-deebot.0 | 2020-03-19 09:35:21.612 | info | (28619) start cleaning spot area(s): 0
ecovacs-deebot.0 | 2020-03-19 09:35:21.608 | debug | (28619) state change control.spotArea => 0
ecovacs-deebot.0 | 2020-03-19 09:35:21.258 | debug | (28619) state change info.error =>
ecovacs-deebot.0 | 2020-03-19 09:35:21.256 | debug | (28619) state change info.deviceStatus => cleaning
ecovacs-deebot.0 | 2020-03-19 09:35:21.249 | debug | (28619) state change info.cleanstatus => spot_area
ecovacs-deebot.0 | 2020-03-19 09:35:21.243 | info | (28619) Unhandled cleanstatus: undefined
ecovacs-deebot.0 | 2020-03-19 09:35:20.599 | info | (28619) start cleaning spot area(s): 0
ecovacs-deebot.0 | 2020-03-19 09:35:20.592 | debug | (28619) state change control.spotArea => 0
ecovacs-deebot.0 | 2020-03-19 09:34:17.984 | debug | (28619) system.adapter.admin.0: logging false
ecovacs-deebot.0 | 2020-03-19 09:33:38.355 | debug | (28619) system.adapter.admin.0: logging tru

**Comment by mrbungle64** [comment]
> Hi,
> habe festgestellt das der chargestatus und der devicestatus immer gleich sind.

@helfi9999  
Ist das wirklich so?
Während einer Reinigung oder z.B. wenn der pausiert ist, sollte der "chargestatus" und der "devicestatus" nicht identisch sein.

> Normalerweise müsste doch der chargestatus nur "charging" und "idle" anzeigen aber nicht "returning" oder sehe ich das verkehrt.

Du siehst das nicht "verkehrt" - aber das ist halt das was Ecovacs als "ChargeState" liefert.
Genau genommen liefert Ecovacs "going" oder "Going" - wir übersetzen das in "returning".

Gibt es wirklich ein Problem, weil dieser Status vorhanden ist?

**Comment by helfi9999** [comment]
> 
> 
> > Hi,
> > habe festgestellt das der chargestatus und der devicestatus immer gleich sind.
> 
> @helfi9999
> Ist das wirklich so?
> Während einer Reinigung oder z.B. wenn der pausiert ist, sollte der "chargestatus" und der "devicestatus" nicht identisch sein.
> 
> > Normalerweise müsste doch der chargestatus nur "charging" und "idle" anzeigen aber nicht "returning" oder sehe ich das verkehrt.
> 
> Du siehst das nicht "verkehrt" - aber das ist halt das was Ecovacs als "ChargeState" liefert.
> Genau genommen liefert Ecovacs "going" oder "Going" - wir übersetzen das in "returning".
> 
> Gibt es wirklich ein Problem, weil dieser Status vorhanden ist?

Ok bis jetzt läuft alles und ich nehme das so hin mit deiner Beschreibung hoffe aber es wird sich noch einiges tun, sprich ihr entwickelt den Adapter immer weiter. Ich finde das total super was ihr für Arbeit da rein steckt.  - Alle Achtung - Habe leider nicht die Ahnung von so etwas sonst würde ich gerne meine Zeit und Arbeit mit anbieten.

Wenn es was neues gibt könnt ihr einen unterrichten ist so etwas möglich.

Bis dann

helfi9999

**Comment by mrbungle64** [comment]
@helfi9999 
> Ok bis jetzt läuft alles und ich nehme das so hin mit deiner Beschreibung hoffe aber es wird sich noch einiges tun, sprich ihr entwickelt den Adapter immer weiter. Ich finde das total super was ihr für Arbeit da rein steckt. - Alle Achtung - Habe leider nicht die Ahnung von so etwas sonst würde ich gerne meine Zeit und Arbeit mit anbieten.

Freut mich, dass Dir unser Adapter gefällt :+1: 
Wir werden den Adapter sicher noch erweitern - ich persönlich werde mich allerdings die nächste Zeit eher weniger mit neuen Features beschäftigen, denn mein OZMO 930 lädt nicht mehr auf - da ist evtl. die Ladestation defekt ... Mein anderer Ecovacs Saugroboter (Slim 2) hat ja leider nur wenige Funktionen und die sind soweit bereits alle eingebaut ;)
