### ISSUE TITLE
Raum Mittelpunkt als Koordinaten und GoToRoom

### ISSUE THREAD

**Issue by benep** [mrbungle64/ioBroker.ecovacs-deebot#417]
### The feature request

Für eine neue Steuerungsidee bräuchte ich einen Punkt in jedem Raum, daher habe ich mir überlegt, dass es für mehrere Sachen interessant sein könnte die Koordinaten vom Mittelpunkt jedes Raums zu kennen. Daher würde ich mich freuen, wenn du den Mittelpunkt einfügen könntest. `ecovacs-deebot.0.map.*.spotAreas.*.spotAreaCentralPoint` Da du die Boundaries schon verwendest, müsste das doch relativ leicht errechen bar sein.

Dann könnte man auch leicht ein button state `ecovacs-deebot.0.map.*.spotAreas.*.goToSpotArea` einführen.

Das macht natürlich vor allem dann Sinn, wenn die goTo Funktion von Ecovacs verfügbar ist, weil er dann in den Raum fährt ohne das Saugwerk zu starten. Dazu auch mein anderes Feature Request #418.

### Which model do you own?

Deebot T8 series

### Which version of the ioBroker adapter are you currently using?

1.4.11

**Comment by mrbungle64** [comment]
@benep 

Ab der gerade veröffentlichen Version 1.4.11 kannst du dir mehrere Positionen abspeichern und den Bot dann direkt mit der GoTo Funktion hinschicken. Es wird für jede Position ein separater Button erstellt.

Du musst also nur für jeden Raum den Mittelpunkt selbst ermitteln und die Positionen dann jeweils abspeichern.

**Comment by benep** [comment]
Klar, über die Funktion bin ich auch erst drauf gekommen. Das muss man halt bei jeder Maperstelltung neu machen. Daher wäre eine Standardpunkt pro Raum interessant. Und ich dacht, dass der Mittelpunkt am einfachsten zu errechnen ist und gehofft, dass den ein Plugin vielleicht schon ohne viel Arbeit errechnen kann.

**Comment by mrbungle64** [comment]
Ich denke nicht, dass das viel Sinn macht die Position automatisch zu ermitteln, da diese Position nicht in jedem Raum der gewünschte Mittelpunkt ist und der auch nicht immer erreichbar ist.

**Comment by benep** [comment]
Hm, hast du eine andere Idee, wie ich automatisiert auf irgendeinen Punkt in jedem Raum komme, der nicht auf der Grenz liegt und auch sonst sinnvoller ist?

**Comment by mrbungle64** [comment]
> Hm, hast du eine andere Idee, wie ich automatisiert auf irgendeinen Punkt in jedem Raum komme, der nicht auf der Grenz liegt und auch sonst sinnvoller ist?

Nein, das wird sicher ziemlich schwierig, weil jeder Raum wieder anders aufgebaut und gestaltet ist. 
Muss das denn unbedingt automatisiert sein?

**Comment by benep** [comment]
Nachdem ich das für das andere FR #418 bräuchte eigentlich schon. Hast du das gelesen? Vielleicht hast du auch einen bessere Idee dazu im Gesamtkontext.

**Comment by mrbungle64** [comment]
@benep 

Mein Vorschlag wäre folgender:

Seit der Version 1.4.11 gibt es ja den Button "control.extended.goToPosition_saveCurrentDeebotPosition"
Ich würde analog dazu einen Button "control.extended.goToPosition_saveSpotAreaCentralPosition" anbieten, welcher dann in der Spot Area, wo sich der Bot gerade befindet, den Button "map.*.spotAreas.*.centralGoToPosition" anlegt bzw. abändert falls schon vorhanden.

Dort steht dann die Position im Objekt drin und der Datenpunkt dient als GoTo-Funktion für die entsprechende Spot Area.

Ich möchte die Position nicht autom. versuchen zu ermitteln, da man sonst zu oft z.B. das Bett mitten im Schlafzimmer oder den Esstisch mitten im Esszimmer als GoTo-Position treffen würde...

Wie wäre es damit. Dann hätte man (im Optimalfall) einmalig pro Spot Area den Aufwand die Position zu setzen, wenn sich der Bot gerade an der Position befindet.

Hört sich das gut an? 😉

**Comment by benep** [comment]
Das wäre schon eine riesen Hilfe. Bisher aktualisiere ich da regelmaßig Punkte:

![grafik](https://user-images.githubusercontent.com/237102/212487912-139020f2-4998-4430-9d5b-cea05de5dd12.png)

Das könnte man dadurch auch fast komplett ersetzen.

Die Überlegung ist halt, ob man nicht als Initialwert so einen Mittelpunkt nimmt und wem der nicht passt oder der Mittelpunkt gar falsch ist (weil L-Raum), dann kann man ihn mit der von dir Vorgeschlagenen Funktion auf einen belibigen Ort ändern.

**Comment by mrbungle64** [comment]
@benep 

> Bisher aktualisiere ich da regelmaßig Punkte:

Wieso ändert sich bei dir regelmäßig der Mittelpunkt eines Raumes?

> Das wäre schon eine riesen Hilfe

Ich verstehe immer noch nicht, warum du den Mittelpunkt er Räume automatisiert ermittelt haben möchtest ...
Der ändert sich doch nicht ständig ...

Ich glaube, dass Du meinen Vorschlag noch nicht richtig verstanden hast ...

**Comment by mrbungle64** [comment]
@benep 

Sorry, jetzt hatte ich dich wohl falsch verstanden 😉 

> Das wäre schon eine riesen Hilfe.

Sollte wohl heißen: ja, das hört sich gut an

Richtig?

**Comment by benep** [comment]
Ja, richtig.

> Der ändert sich doch nicht ständig ...
Der Mittelpunkt ändert sich nicht. Sondern ich muss die Karte öfter mal neu erstellen, weil mein Deebot nach einer gewissen Zeit anfängt nur nur noch Kreise zu drehen. Wenn ich dann eine neue Karte erstelle gehts wieder ein paar Wochen.

**Comment by mrbungle64** [comment]
> Der Mittelpunkt ändert sich nicht. Sondern ich muss die Karte öfter mal neu erstellen, weil mein Deebot nach einer gewissen Zeit anfängt nur nur noch Kreise zu drehen. Wenn ich dann eine neue Karte erstelle gehts wieder ein paar Wochen.

Ah ok, das war eine wichtige Info - jetzt verstehe ich erst richtig, wo diese Anforderung her kommt

**Comment by mrbungle64** [comment]
@benep 

Probier mal die 1.4.12-alpha.x

Für jede Spot Area wird nun der Button "goToCalculatedCenterPosition" erzeugt 😉

**Comment by benep** [comment]
Das funktioniert bei mir auch gut. Die Punkte passen gut, aber ich hab auch keine beonderen Grundrisse. Mit der Schwerpunktberechnung müsste das meist gut gehen, außer bei lange L-Räumen.

Ich wunder mich nur, dass er die Werte im minütlichen Rhytmus aktualisiert und auch noch jeden Raum doppelt.

**Comment by mrbungle64** [comment]
> Ich wunder mich nur, dass er die Werte im minütlichen Rhytmus aktualisiert 

Das sollte aber nicht minütlich sein... Da geschieht bei dir wohl irgendwas was minütlich triggert, dass die Map-Daten bei der API abgeholt werden.  Bei mir verhält es sich in der Praxis auch quasi wie erwartet.

> und auch noch jeden Raum doppelt.

Danke für den Hinweis. Das war mir noch gar nicht aufgefallen.

**Comment by benep** [comment]
Jetzt waren es mal 6 Minuten, schau mal ob ich noch was entdecke.
Den leer Fall, solltest du wahrscheinlich noch abfangen:

<html><body>


ecovacs-deebot.0 | 2023-01-15 11:00:03.429 | info | Saving go to position values: NaN, NaN on map 1339471146
-- | -- | -- | --



</body>
</html>

**Comment by mrbungle64** [comment]
@benep 

Der Wert `NaN, NaN` wird quasi von Deinem Code (aus dem Blockly) zurückgeliefert - da habe ich nämlich Copy'n'Paste gemacht 😁

**Comment by benep** [comment]
Also alle Blocklys deaktiviert, Adaper & JS neugestartet.

ecovacs-deebot.0 | 2023-01-15 11:28:08.326 | info | Saving go to position values: -2371, 1511 on map 1339471146
-- | -- | -- | --
ecovacs-deebot.0 | 2023-01-15 11:34:08.359 | info | Saving go to position values: -2371, 1511 on map 1339471146


Jetzt sind es genau 6 Minuten.


> Ich schätze aber mal, dass die Funktion halt einfach einen leeren Wert übergeben bekommt in dem Fall

Ich hab es mal noch mit den Koordinaten von ner CustomArea versucht, das geht auch nicht. Er erwartet Grenzkoordinaten und eine geschlossene Grenze, damit er eine Fläche berechnen kann. Mit der CustomArea sind es nur zwei Koordinaten und damit eine Linie , ohne Fläche.

**Comment by mrbungle64** [comment]
> Jetzt sind es genau 6 Minuten.

Ich denke, dass ich das Problem gefunden habe:
Dadurch, dass du das wahrscheinlich relativ intensiv getestet hast, wurde jedes Mal wenn der Status `idle` wurde der Befehl `GetMaps` in die "intervalQueue" gepackt. Ich nehme mal an, dass das Intervall bei dir auf 6 Minuten eingestellt ist.

Ich denke aber, dass ich das relativ bald gefixt bekomme.

**Comment by benep** [comment]
> Ich nehme mal an, dass das Intervall bei dir auf 6 Minuten eingestellt ist.

Ist bei mir auf 60 Sekunden. Das würde es aber ganz gut erkären. Was ist denn ein guter Wert? Ich kann mich nicht erinnern, dass ich den mal geändert habe.

**Comment by mrbungle64** [comment]
> > Ich nehme mal an, dass das Intervall bei dir auf 6 Minuten eingestellt ist.
> 
> Ist bei mir auf 60 Sekunden. Das würde es aber ganz gut erkären. Was ist denn ein guter Wert? Ich kann mich nicht erinnern, dass ich den mal geändert habe.

Ah ok, ich dachte, dass daher die 6 Minuten kommen...
Ab dem T8 sollten die 6 Minuten aber ausreichen - bei älteren Modellen muss mehr gepollt werden.

Hatte dir auch gerade im anderen Issue was geschrieben 😁

**Comment by mrbungle64** [comment]
> und auch noch jeden Raum doppelt.

Das kommt einfach daher, weil es 2 Buttons pro Spot Area sind.

Die Buttons sollten mit der letzten Änderung nun auch nur noch initial und bei einer Änderung erstellt oder neu geschrieben werden.

**Comment by benep** [comment]
Ich hab die Funktion mal erweitert um spezialfälle für 1 und 2 Koordinaten. Außerdem checke ich ob der Input überhaupt passt.

```
function getCalculatedCenterForBoundary(coordinatesString) {
    if (coordinatesString.trim() === '' || !/^[\d,.-]+;[\d,.-]+([;[\d,.-]+)*$/.test(coordinatesString)) {
        return false;
    }
    const coordinates = coordinatesString.split(';').map(c => c.split(',').map(Number));
    if (coordinates.length === 1) {
        return `${coordinates[0][0]}, ${coordinates[0][1]}`;
    }
    if (coordinates.length === 2) {
        const x = Math.round((coordinates[0][0] + coordinates[1][0]) / 2);
        const y = Math.round((coordinates[0][1] + coordinates[1][1]) / 2);
        return `${x}, ${y}`;
    }
    let area = 0;
    let xSum = 0;
    let ySum = 0;
    for (let i = 0; i < coordinates.length; i++) {
        const x1 = coordinates[i][0];
        const y1 = coordinates[i][1];
        const x2 = coordinates[(i + 1) % coordinates.length][0];
        const y2 = coordinates[(i + 1) % coordinates.length][1];
        area += x1 * y2 - x2 * y1;
        xSum += (x1 + x2) * (x1 * y2 - x2 * y1);
        ySum += (y1 + y2) * (x1 * y2 - x2 * y1);
    }
    area = area / 2;
    const x = Math.round(xSum / (6 * area));
    const y = Math.round(ySum / (6 * area));
    return `${x}, ${y}`;
}
```

**Comment by benep** [comment]
Hab oft den Log-Eintrag
`Saving go to position values: NaN, NaN on map 1339471146`

Vielleicht wäre in der MSG noch der Raum gut.

Außerdem sind jetzt die Raumnahmen nur noch A oder B.

**Comment by mrbungle64** [comment]
@benep 

> Hab oft den Log-Eintrag
> Saving go to position values: NaN, NaN on map 1339471146

Um welche Uhrzeit hattest du das letzte mal installiert?

> Ich hab aber keinen Raum gefunden, bei dem er nicht an den Zentralpunkt fährt.
> Vielleicht wäre in der MSG noch der Raum gut.

Genau das hatte ich eigentlich eben schon eingebaut gehabt ...

**Comment by mrbungle64** [comment]
@benep 

Ich habe die Version nun auf 1.4.12-alpha.4 angehoben

**Comment by benep** [comment]
Mit der Alpha4 sind die NaNs weg.

> Ab dem T8 sollten die 6 Minuten aber ausreichen - bei älteren Modellen muss mehr gepollt werden.

Ich wollte das grad mal hochstellen, aber das ist ja ein Dropdown und es gibt nur 30 Sec und 60 Sec zur Auswahl.

> Achte halt mal darauf, ob das nun dauerhaft so ist.

Das ist jetzt 1,5 h so geblieben. Nach einem Neustart vom Adapter war es wieder gut. Nach kurzer Zeit ist aber wieder einer zu C geworden.

**Comment by mrbungle64** [comment]
> Ich wollte das grad mal hochstellen, aber das ist ja ein Dropdown und es gibt nur 30 Sec und 60 Sec zur Auswahl.

Das sollte eigentlich folgendermaßen aussehen:

![Abfrageintervall Adapter 2023-01-15 19 42 51](https://user-images.githubusercontent.com/37313763/212560665-c2c2cfc4-20cf-4042-81fc-450b26678c6a.png)

Du könntest mal den "Dateiupload" ausführen (Pfeil nach oben), falls das immer noch so sein sollte

![Dateiupload Adapter 2023-01-15 19 45 13](https://user-images.githubusercontent.com/37313763/212560751-ac920aad-73dc-4ff2-8ac2-3763f1724be8.png)

**Comment by mrbungle64** [comment]
> Das ist jetzt 1,5 h so geblieben. Nach einem Neustart vom Adapter war es wieder gut. Nach kurzer Zeit ist aber wieder einer zu C geworden.

Das ist bei mir auch manchmal so ... War nur bisher noch nicht so motiviert das mal intensiver zu prüfen, da es ja nicht immer auftritt. Muss da wohl doch mal ran 😉

**Comment by mrbungle64** [comment]
@benep 

Ich schließe diesen Issue mal, da das mit dem Button "goToCalculatedCenterPosition" umgesetzt ist.

**Comment by benep** [comment]
> Das sollte eigentlich folgendermaßen aussehen:

Das ist ein Problem mit der Seitenhöhe/Div-Höhe bzw. den z-Wert:
![grafik](https://user-images.githubusercontent.com/237102/212569762-fad383e5-84c0-47d5-95a2-bd43af0ec3e5.png)

Wenn ich drauf Klicke sehe ich nur 2, ohne irgendwelche Scrollleisten. Wenn ich aber trotzdem runterwheele verschiebt sich das Div unterhalb von Haupseite-Erweitert-Experimental und die anderen Optionen kommen zum vorschein:

![grafik](https://user-images.githubusercontent.com/237102/212569796-95fbf649-6c9e-4412-9295-e8271b466b92.png)
