### ISSUE TITLE
spotAreas & virtualBoundaries in neue Map übernehmen

### ISSUE THREAD

**Issue by olli0815** [mrbungle64/ioBroker.ecovacs-deebot#421]
### The question

Servus,

der ecovacs-deebot 950 hat (mal wieder) die Karte verloren und eine neue generiert.
Die Datenpunkte der alten (recht komplexen) Karte mit div. virtual Boundaries und spot Areas habe ich natürlich noch über den Adapter.

Gibt es einen Weg diese in die neue Karte (Map) zu übernehmen?
Über Import der wiederverwendeten json Files geht es nicht, die tauchen zumindest nicht in der App auf.
Austauschen der currentMapMID geht auch nicht.

Kann ich den Adapter nutzen, um die alte Karte wieder herzustellen, bzw. die Grenzen wieder zu übernehmen?

Danke
Ole

### Which model do you own?

None

**Comment by mrbungle64** [comment]
@olli0815 

Hi Ole,

> Kann ich den Adapter nutzen, um die alte Karte wieder herzustellen, bzw. die Grenzen wieder zu übernehmen?

mir ist leider keine Möglichkeit bekannt eine gespeicherte Map beim OZMO 950 wieder auf den Bot zu übertragen.

Die Virtual Boundaries könntest du aber mit ein bisschen Glück mit Hilfe des Adapters wiederherstellen.

Wenn du "Löschen, Speichern und Wiederherstellen von gespeicherten virtuellen Begrenzungen und No-Mop-Zones" in den Einstellungen aktiviert hast, kannst du den gesamten Satz an Virtual Boundaries speichern ("map.[mapID].saveVirtualBoundarySet") und später wieder herstellen ("map.savedBoundarySets.virtualBoundarySet_xxxxxxxxxx").

Ob die dann noch zur neu erstellten Map passen ist dann wohl ein bisschen Glücksache, da die Koordinaten der neuen Map wahrscheinlich nicht 100% den alten entsprechen werden.

> Über Import der wiederverwendeten json Files geht es nicht, die tauchen zumindest nicht in der App auf.

Welche JSON-Files meinst du?

**Comment by olli0815** [comment]
> Welche JSON-Files meinst du?
spot areas und boundaries - umgehängt über austauschen der MapID

> später wieder herstellen ("map.savedBoundarySets.virtualBoundarySet_xxxxxxxxxx")
ja, die sind im Adapter da, in der App allerdings nicht

**Comment by mrbungle64** [comment]
@olli0815 

> > später wieder herstellen ("map.savedBoundarySets.virtualBoundarySet_xxxxxxxxxx")
> 
> ja, die sind im Adapter da, in der App allerdings nicht

Ah ok, ich sehe das Problem:
Du musst in dem Datenpunkt (also in dem JSON) noch die `currentMapID` auf die neue ändern (also wenn eine neue Map erstellt wurde)

**Comment by mrbungle64** [comment]
> > Welche JSON-Files meinst du?
> 
> spot areas und boundaries - umgehängt über austauschen der MapID

Du meinst das Objekt vom Datenpunkt (als JSON)?

**Comment by olli0815** [comment]
> > > Welche JSON-Files meinst du?
> > 
> > 
> > spot areas und boundaries - umgehängt über austauschen der MapID
> 
> Du meinst das Objekt vom Datenpunkt (als JSON)?

nein ich meine die Datenpunkte zum Objekt als JSON File.
Indem ich die aus einem alten Zweig exportiert, die MapID getauscht habe und unter dem neuen Baum (Map) wieder importiert habe

**Comment by olli0815** [comment]
> @olli0815
> 
> > > später wieder herstellen ("map.savedBoundarySets.virtualBoundarySet_xxxxxxxxxx")
> > 
> > 
> > ja, die sind im Adapter da, in der App allerdings nicht
> 
> Ah ok, ich sehe das Problem: Du müsstest in dem Objekt vom Datenpunkt (also in dem JSON) noch die `currentMapID` auf die neue ändern (also wenn eine neue Map erstellt wurde).
> 
> Anmerkung: Ich habe das praktisch noch nie probiert, dass mit einer neu erstellten Map wiederherzustellen - könnte aber funktionieren mit dem o.g. Tipp

Genau, so habe ich es gemacht

**Comment by mrbungle64** [comment]
@olli0815 

> nein ich meine die Datenpunkte zum Objekt als JSON File.
> Indem ich die aus einem alten Zweig exportiert, die MapID getauscht habe und unter dem neuen Baum (Map) wieder importiert habe

Hier sprichst du von einem Export. Welcher "Export" ist das?

> Genau, so habe ich es gemacht

Ich bin mir da nicht sicher ...

> Du müsstest in dem Objekt vom Datenpunkt (also in dem JSON) noch die currentMapID auf die neue ändern (also wenn eine neue Map erstellt wurde).

... denn ich meine nicht in einem Export - sondern im Objekt vom Datenpunkt.
Der Datenpunkt ist ja als Button angelegt.

**Comment by olli0815** [comment]
:-) wir reden jeweils vom selben.
Im ersten Fall: Export/Import via JSON File 
I'm zweiten Fall: save und Reimport über die Adapter-Funktion triggert via boolean (map.savedBoundarySets.virtualBoundarySet_xxxxxxxxxx).

Beides funktioniert hier aber nicht. 
Ist aber auch egal, ich lasse den Roboter jetzt (zum letzten Mal) ne Karte erstellen und zieh die Grenzen wieder.
