### ISSUE TITLE
"ecovacs-deebot.0.control.cleanSpeed" which expects a string.

### ISSUE THREAD

**Issue by krobipd** [mrbungle64/ioBroker.ecovacs-deebot#43]
Hey

erstmal vielen vielen Dank für eure Mühen. Beim herumprobieren ist mir folgendes augefallen.
warum erwartet der einen string und keine number? sind ja schließlich nur nummerische werte drin.

by the way, es wäre toll überall standardwerte drin zu haben damit man besser skripte schreiben kann zB error - ist leer wenn es keinen fehler gibt vl kann man einfach null oder so als standardwert nehmen.

danke

ps: sorry fürs zuerst falsch posten 🙈

**Comment by mrbungle64** [comment]
> Hey
> 
> erstmal vielen vielen Dank für eure Mühen. Beim herumprobieren ist mir folgendes augefallen.
> warum erwartet der einen string und keine number? sind ja schließlich nur nummerische werte drin.

@krobipd 
Hattest Du [meinen Kommentar](https://github.com/mrbungle64/ecovacs-deebot.js/issues/22#issuecomment-602271469) gesehen?
Du kannst aber gerne noch mal konkretisieren was Du meinst (z.B. was ist "der").

> by the way, es wäre toll überall standardwerte drin zu haben damit man besser skripte schreiben kann zB error - ist leer wenn es keinen fehler gibt vl kann man einfach null oder so als standardwert nehmen.

Kannst Du ein Beispiel oder sogar ein konkretes Problem nennen was besteht, wenn der Wert von "error" leer ist?

> 
> danke
> 
> ps: sorry fürs zuerst falsch posten

Kein Problem ;)

**Comment by krobipd** [comment]
Ja danke sehr, wollte es derwegen richtig posten.

Ich denke das Problem kommt daher das ihr ja anfangs die Speed Einstellungen als Text hatten und dann auf Nummern umgestellt habt - was ich e als besser empfinde.

Jedenfalls steht in der Main.js

> setObjectNotExists

Also setzt er die Infos nur wenn das Objekt nicht existiert, in meinem Fall existiert es ja schon nur halt mit strings - da ja update von alten Versionen.

Bzgl Standardwerten
In meinem konkreten Fall hab ich mir eine Variable für HomeKit gebastelt wo ich via Blockly diverse Abfragen machen. Unter anderem frage ich den error ab ob da was drin steht. Was ich miteinander Text mit Inhalt „“ mache (also beide oben, also nicht leer). Wäre schöner und vl für Leute die nicht wissen das man so nicht leer abfragt leichter wenn da nein, null, keiner oder so stehen würde dann könnte man Text mit Inhalt „keiner“ abfragen.

Ich würde dir gerne einen Screenshot einfügen, nur via iPad ist das scheinbar unmöglich 😢

**Comment by krobipd** [comment]
So via GitHub app gehts ja 🥳![image](https://user-images.githubusercontent.com/27220902/77261279-ac973280-6c8d-11ea-8b35-e19c55ad0e08.jpeg)

**Comment by mrbungle64** [comment]
> Ich denke das Problem kommt daher das ihr ja anfangs die Speed Einstellungen als Text hatten und dann auf Nummern umgestellt habt - was ich e als besser empfinde.

Ja richtig - da gab es in der Zwischenzeit eine Änderung.

> 
> Jedenfalls steht in der Main.js
> 
> > setObjectNotExists
> 
> Also setzt er die Infos nur wenn das Objekt nicht existiert, ...

`setObjectNotExists` erzeugt Objects nur, wenn diese noch nicht existieren.
Bin mir nicht sicher, ob Du das Gleiche meinst ;)

> ... in meinem Fall existiert es ja schon nur halt mit strings - da ja update von alten Versionen.

Wenn Du den State manuell im Admin löschst, erzeugt der diesen nach dem nächsten Neustart vom Adapter neu, so dass Dein Problem damit gelöst sein sollte, oder?

**Comment by mrbungle64** [comment]
@krobipd 
> 
> ... Was ich miteinander Text mit Inhalt „“ mache (also beide oben, also nicht leer)...

Sorry, ich verstehe diesen Satz inkl. dem was in der Klammer steht irgendwie nicht ...
Leider verstehe ich so auch das eigentliche Problem noch nicht.

**Comment by krobipd** [comment]
Danke das manuelle löschen hat das Problem gelöst, jetzt steht in den Eigenschaften auch das zahl erwartet wird.

Bzgl den Standardwerten
Vl half schon mein Bild. Eine Anfrage nach nicht leer ist schwieriger als eine nach einem gewissen Inhalt oder nicht Inhalt.

Es ist leichter zb nach idle zu fragen (zb chargestatus) als wenn da nichts (also leer, null) drin stehen würde. 

Also bei errors wäre es toll wenn da zb keiner oder ähnliches drin stehen würde, wenn es keinen Fehler gibt und nicht einfach nichts. Ich denke das würde die Freunde von vis auch freuen.

**Comment by mrbungle64** [comment]
> 
> Also bei errors wäre es toll wenn da zb keiner oder ähnliches drin stehen würde, wenn es keinen Fehler gibt und nicht einfach nichts. Ich denke das würde die Freunde von vis auch freuen.

@boriswerner 
Ich selbst benutze VIS aktuell nicht. Was hältst Du davon immer einen Wert einzutragen?
Oder ggf. stattdessen einen weiteren State für den Error code, der dann immer einen Wert besitzt?

**Comment by boriswerner** [comment]
Es gibt ja sogar die Codes 0 bzw 100 für okay. Die geben wir nur nicht weiter. Also warum nicht. Ich wollte morgen früh Mal wieder was machen, kann ich gerne einmal schauen.

**Comment by mrbungle64** [comment]
> Es gibt ja sogar die Codes 0 bzw 100 für okay. Die geben wir nur nicht weiter. Also warum nicht. Ich wollte morgen früh Mal wieder was machen, kann ich gerne einmal schauen.

Du meinst dann als extra State für den Error Code?
Das wäre meine bevorzugte Variante. Könnte das dann auch gerade einbauen.

**Comment by boriswerner** [comment]
Achso. Das ist noch besser. Gerne

**Comment by mrbungle64** [comment]
@boriswerner 

Ich habe das Property `error_event` in `errorDescription` umbenannt (das würde ich gerne auch für sämtliche anderen Properties nachziehen diese in camelCase umzubenennen bzw. sinnvoller zu benennen). Die Benennung vom Event `Error` habe ich dafür aus Kompatibilitätsgründen beibehalten.

Zusätzlich gibt es jetzt das Property `errorCode` mit dem entsprechenden Event `ErrorCode` (erst mal nur für XMPP und MQTT/XML Geräte). Für den ErrorCode `100` (von Ecovacs) verwende ich den Wert `0`, da dieser für den Ozmo 950 verwendet wird und ich `0` passender finde als die `100`.

Du kannst das ja aus dem Commit so für den Ozmo 950 übernehmen, falls Du kein Problem dabei entdeckst.

**Comment by boriswerner** [comment]
@mrbungle64 wie ist hier eigentlich der Status? Die 950 library liefert in der neuen Version nun die Events "Error" und "ErrorCode", allerdings scheint im Adapter im Moment nur "Error" zu verarbeiten?

**Comment by mrbungle64** [comment]
> @mrbungle64 wie ist hier eigentlich der Status? Die 950 library liefert in der neuen Version nun die Events "Error" und "ErrorCode", allerdings scheint im Adapter im Moment nur "Error" zu verarbeiten?

@boriswerner 
Du hast Recht - da habe ich im Adpater noch nichts gemacht seit dem. Hole das voraussichtlich heute nach ;)

**Comment by mrbungle64** [comment]
> @mrbungle64 wie ist hier eigentlich der Status? Die 950 library liefert in der neuen Version nun die Events "Error" und "ErrorCode", allerdings scheint im Adapter im Moment nur "Error" zu verarbeiten?

@boriswerner 
Der Adapter verarbeitet nun beide Error Events

**Comment by boriswerner** [comment]
@krobipd @mrbungle64 Hier können wir zumachen, oder?

**Comment by mrbungle64** [comment]
> @krobipd @mrbungle64 Hier können wir zumachen, oder?

@boriswerner 
Ja auf jeden Fall, da der urspüngliche Issue schon länger erledigt ist.

@krobipd 
In der neusten Version auf GitHub gibt es nun die getrennten States für Error (message) und den ErrorCode. Falls Du damit noch Probleme haben solltest oder Vorschläge/Fragen dazu kannst Du ja einen neuen Issue erstellen.
