### ISSUE TITLE
Request failed with status code 502/504

### ISSUE THREAD

**Issue by senger1985** [mrbungle64/ioBroker.ecovacs-deebot#432]
### Is there an existing issue for this?

- [X] I have searched the existing issues and no issue is describing my issue

### The problem

<html>
<body>

2023-02-09 08:13:27.758 | warn | Error message received: Received error message: Request failed with status code 502 for command getWaterInfo
-- | -- | --

</body>
</html>

<html>
<body>

2023-02-09 08:43:31.879 | warn | Error message received: Received error message: Request failed with status code 502 for command getVolume
-- | -- | --

</body>
</html>

### With which model does the problem occur?

Deebot X1 series

### From which source you have installed the adapter?

Beta (latest)

### Version of the ioBroker adapter ("info.version")

1.4.12

### Version of the ecovacs-deebot.js library ("info.library.version")

0.9.2-beta.1

### Version of the JS controller

4.0.24

### Version of Node.js

v16.17.0

### Operating system

Linux

### Anything in the logs that might be useful?

```txt
Ich bekomme immer wieder folgende Fehlermeldungen:
<html>
<body>
<!--StartFragment-->

2023-02-09 08:13:27.758 | warn | Error message received: Received error message: Request failed with status code 502 for command getWaterInfo
-- | -- | --
Error message received: Received error message: Request failed with status code 502 for command getVolume
--


<!--EndFragment-->
</body>
</html>

<!--EndFragment-->
</body>
</html>
```

### Ecovacs device class ("info.deviceClass")

1b23du

### Communication protocol ("info.library.communicationProtocol")

MQTT

### Is the canvas module installed? ("info.library.canvasModuleIsInstalled")

None

**Comment by mrbungle64** [comment]
* https://github.com/mrbungle64/ioBroker.ecovacs-deebot/issues/412
* https://forum.iobroker.net/topic/52853/ecovacs-deebot-adapter-status-und-feedback

**Comment by senger1985** [comment]
taken note of

**Comment by mrbungle64** [comment]
@senger1985 

If the problem persists, please try the latest alpha version. I switched to a different API URL.

**Comment by mrbungle64** [comment]
@senger1985 

Can we close this issue?

**Comment by senger1985** [comment]
sure
