### ISSUE TITLE
Request failed with status code 502/504

### ISSUE THREAD

**Issue by Keyronics** [mrbungle64/ioBroker.ecovacs-deebot#439]
### Is there an existing issue for this?

- [X] I have searched the existing issues and no issue is describing my issue

### The problem

Few weeks ago my adapter gets alot of warnings.
First i thought about an internal network or isp fault, but the warning keeps going on.

`<html><body>

Quelle | Datum | Info | Nachricht
-- | -- | -- | --
ecovacs-deebot.0 | 2023-02-26 14:36:51.352 | warn | Error message received: Received error message: Request failed with status code 502 for command getSleep
ecovacs-deebot.0 | 2023-02-26 14:21:48.840 | warn | Error message received: Received error message: Request failed with status code 502 for command getWaterInfo
ecovacs-deebot.0 | 2023-02-26 14:20:48.998 | warn | Error message received: Received error message: Request failed with status code 502 for command getSpeed
ecovacs-deebot.0 | 2023-02-26 14:18:54.648 | warn | Error message received: Received error message: Request failed with status code 502 for command getWaterInfo
ecovacs-deebot.0 | 2023-02-26 14:17:48.780 | warn | Error message received: Received error message: Request failed with status code 502 for command getSpeed
ecovacs-deebot.0 | 2023-02-26 14:14:48.341 | warn | Error message received: Received error message: Request failed with status code 502 for command getSleep
ecovacs-deebot.0 | 2023-02-26 14:09:48.307 | warn | Error message received: Received error message: Request failed with status code 502 for command getSleep
ecovacs-deebot.0 | 2023-02-26 13:49:50.285 | warn | Error message received: Received error message: Request failed with status code 502 for command getTrueDetect
ecovacs-deebot.0 | 2023-02-26 13:22:46.231 | warn | Error message received: unknown errorCode: 4201
ecovacs-deebot.0 | 2023-02-26 13:19:47.828 | warn | Error message received: Received error message: Request failed with status code 502 for command getWaterInfo
ecovacs-deebot.0 | 2023-02-26 13:08:49.301 | warn | Error message received: Received error message: Request failed with status code 502 for command getSpeed
ecovacs-deebot.0 | 2023-02-26 12:55:49.315 | warn | Error message received: Received error message: Request failed with status code 502 for command getSpeed

</body>
</html>`

### With which model does the problem occur?

Deebot T9 series

### From which source you have installed the adapter?

Beta (latest)

### Version of the ioBroker adapter ("info.version")

1.4.12

### Version of the ecovacs-deebot.js library ("info.library.version")

0.9.2-beta.1

### Version of the JS controller

4.0.24

### Version of Node.js

18.14.2

### Operating system

Linux

### Ecovacs device class ("info.deviceClass")

ucn2xe

### Communication protocol ("info.library.communicationProtocol")

None

### Is the canvas module installed? ("info.library.canvasModuleIsInstalled")

yes (true)

**Comment by mrbungle64** [comment]
@Keyronics 

I released version 1.4.13 yesterday and switched to a different API endpoint with this version.
It should fix this problem.

**Comment by mrbungle64** [comment]
@Keyronics 

Can you please give me some feedback?
