### ISSUE TITLE
[v0.5.8] Adapter funktioniert nicht richtig (wiederholte "Connection" Log-Einträge und Memory Leak)

### ISSUE THREAD

**Issue by volkerverkamp** [mrbungle64/ioBroker.ecovacs-deebot#44]
Seitdem ich das Update auf v0.5.8 installiert habe, läuft die Adapter-Instanz Amok, was sich dadurch außert, dass die Instanz nur sporadisch auf Kommandos reagiert, im Log ständig "successfully connected" ausgibt, die RAM Nutzung anwächst bis sie dann schließlich durch wegen "Javascript out of heap memory" vom Controller gekillt wird. 

Leider weiß ich nicht, wie ich wieder auf die v0.5.7 von Github downgraden kann und wäre für einen Hinweis sehr dankbar!

So sehen die Logs aus:

![image](https://user-images.githubusercontent.com/51383556/77445578-8be5ee80-6ded-11ea-90f9-eae962190f24.png)

Seitdem sieht das Log so aus:
![image](https://user-images.githubusercontent.com/51383556/77445961-06167300-6dee-11ea-8d62-d69ff5e15280.png)

Aktuell ist die RAM-Nutzung des Adapters bei über 600MB:
![image](https://user-images.githubusercontent.com/51383556/77445720-b9329c80-6ded-11ea-8854-0b6761679c7c.png)

**Comment by mrbungle64** [comment]
Hast du schon mal neu gestartet bzw. noch mal frisch installiert?
Falls es dann wieder passiert:
Was wird im Log mit Level "debug" ausgegeben?

**Comment by volkerverkamp** [comment]
Neu gestartet habe ich schon mehrfach, frisch installiert (nach vorherigem Löschen des Adapters) noch nicht, werde ich als nächstes machen. Nach dem Neustart wird im Debug-Log folgendes ausgegeben:

![image](https://user-images.githubusercontent.com/51383556/77453130-21d24700-6df7-11ea-9671-d988bec8683f.png)

**Comment by mrbungle64** [comment]
@volkerverkamp 

Hast Du ein Multihost System am laufen?
Da kommen Meldungen wie "some hosts are offline" und "too delayed answer".

Evtl. hängt es damit zusammen.

**Comment by volkerverkamp** [comment]
@mrbungle64 Ja - habe ein Multihost-System, das war aber auch schon vor dem Update der Fall und der Ecovacs-Adapter läuft auf dem Hauptsystem. Auf dem Slave laufen nur zwei Adapter, die mit dem Ecovacs-Adapter nichts zu tun haben. Ich werde aber zur Sicherheit auch nochmal ohne Multihost testen.

Habe jetzt den Adapter samt Instanz gelöscht und komplett neu installiert, Verhalten laut Log ist  aber unverändert:
![image](https://user-images.githubusercontent.com/51383556/77461822-71b70b00-6e03-11ea-90a9-b09eb4e3bad7.png)

**Comment by mrbungle64** [comment]
@volkerverkamp 

Hier kannst Du die 0.5.7 herunterladen:
https://github.com/mrbungle64/ioBroker.ecovacs-deebot/releases/tag/0.5.7

Ich bin mir nur nicht sicher, was da der einfachste Weg ist einen Adapter aus einer .zip oder .tar.gz zu installieren. Hab das selbst noch nie gemacht.

Lieber wäre mir, wenn wir den Fehler finden könnten.

@boriswerner 
Hast Du vielleicht eine Idee, warum der Vacbot immer wieder einen "ready" Event auslöst (so scheint es mir zumindest)?
Passiert offensichtlich alle ca. 60 Sekunden. Ggf. wegen dem Intervall in der main.js.

**Comment by boriswerner** [comment]
Hm, ich installier meinen mal neu und schaue ob ich was herausfinde

**Comment by volkerverkamp** [comment]
> Hier kannst Du die 0.5.7 herunterladen:
> https://github.com/mrbungle64/ioBroker.ecovacs-deebot/releases/tag/0.5.7
> 
> Ich bin mir nur nicht sicher, was da der einfachste Weg ist einen Adapter aus einer .zip oder .tar.gz zu installieren. Hab das selbst noch nie gemacht.

Hab ich schon erfolglos versucht.

> Lieber wäre mir, wenn wir den Fehler finden könnten.

mir auch ;-)

> @boriswerner
> Hast Du vielleicht eine Idee, warum der Vacbot immer wieder einen "ready" Event auslöst (so scheint es mir zumindest)?
> Passiert offensichtlich alle ca. 60 Sekunden. Ggf. wegen dem Intervall in der main.js.

Nein, gibts ggf. ein Problem mit dem Ecovacs-Server? Ich hatte gestern mal das Problem, dass die App auch Verbindungsprobleme gemeldet hat (mehr als die üblichen...).

Gerade läuft der Bot und der Memory-Footprint geht wieder hoch:
![image](https://user-images.githubusercontent.com/51383556/77465900-b2198780-6e09-11ea-963e-76a43b7c5be7.png)

**Comment by boriswerner** [comment]
@volkerverkamp hast du den Adapter aus dem Latest oder aus dem Github installiert?
Ich hab gerade mal komplett neu installiert über das Latest und habe auf jeden Fall keinerlei Probleme. Das Log sieht normal aus (keine reconnects) und die Speicherauslastung ist auch ganz normal bei unter 50MB.
Auf was für einem System hast du das laufen? Raspberry mit anbahnendem SD-Kartenfehler (blind ins blaue geraten, noch nie gehabt, keine Ahnung was die Symptome sind ;-)?

**Comment by volkerverkamp** [comment]
Hier ein Debug-Log mit dem "JavaScript heap out of memory" samt Neustart des Adapters:

[iobroker.2020-03-24.log.txt](https://github.com/mrbungle64/ioBroker.ecovacs-deebot/files/4377162/iobroker.2020-03-24.log.txt)

**Comment by volkerverkamp** [comment]
> @volkerverkamp hast du den Adapter aus dem Latest oder aus dem Github installiert?
> Ich hab gerade mal komplett neu installiert über das Latest und habe auf jeden Fall keinerlei Probleme. Das Log sieht normal aus (keine reconnects) und die Speicherauslastung ist auch ganz normal bei unter 50MB.
> Auf was für einem System hast du das laufen? Raspberry mit anbahnendem SD-Kartenfehler (blind ins blaue geraten, noch nie gehabt, keine Ahnung was die Symptome sind ;-)?

Die SD (Sandisk Ultra) ist erst wenige Wochen alt, halte ich für unwahrscheinlich. Ist ein Raspberry 4 (mit 4GB RAM). ich kann nochmal sukzessive andere Adapter ausschalten etc.  

Hast Du den Bot mal laufen lassen und ein paar Kommandos (Pause/Resume, Custom Area Reinigung) ausgelöst? Bei mir ging der Spuk bzgl. RAM auch erst los als er lief (zuletzt als ich zum Ende der Reinigung versucht habe in anzuhalten).

**Comment by boriswerner** [comment]
Interessant. 
der "[EcoVacsAPI] problem with request" kommt, wenn der beim Verbindungsaufbau  zum Ecovacs Server hat. Warum die Nachricht so oft kommt ist eine gute Frage. 
Und dann scheint er endlos Positionsnachrichten zu bekommen, die er eigentlich vom Server nur bekommt, wenn er sich bewegt.

Ich hab auch eine custom Reinigung gestartet, ihn pausiert, weiterlaufen lassen, gestoppt, zum Charger fahren lassen, Auto Reinigung gestartet, selbes Spiel mit pause, resume, setSpeed, etc.).
Ansonsten gleiche Hardware, wie du.

Lass den Adapter am besten mal über Nacht ausgeschaltet, vielleicht hat sich tatsächlich der Server verschluckt. Die App hast du bestimmt auch schon aufgerufen und dich zum Bot verbunden? Da irgendwelche weiteren Auffälligkeiten wenn du eine Reinigung machst?

**Comment by boriswerner** [comment]
@volkerverkamp 
Okay, andersherum. Es kommen viel zu viele Positionsnachrichten, dann schmiert er ab (hab von unten nach oben gelesen, wie in der iobroker Log-Ansicht)
Die vielen `[EcoVacsAPI] problem with request` kann ich mir allerdings nicht so genau erklären. 
Besteht das Problem heute auch noch?

Wenn ja, kannst du mal folgendes auf deinem Pi machen: einmal den Pfad prüfen, das ist mein Installationspfad vom Standard iobroker Image, deine Logindaten an den Stellen eintragen (die eckigen Klammern [] müssen auch mit ersetzt werden) und in der bash ausführen:
```
cd /opt/iobroker/node_modules/ecovacs-deebot/example
sed -i 's/email@domain.com/[deineEMail]/g' app2.js
sed -i 's/a1b2c3d4/[deinPasswort]/g' app2.js
NODE_ENV=dev node app2.js
```
Das startet die library direkt und gibt mehr Meldungen aus (mit Strg-C kannst du das später dann wieder beenden). Am besten erstmal starten ohne den iobroker Adapter laufen zu haben. Wenn da nach kurzer Zeit nichts mehr passiert, bitte einmal den iobroker Adapter starten und schauen, ob da auch ungewöhnlich viele Meldungen kommen.
Erstmal keine Reinigung starten, dann wird es unübersichtlich. Erstmal würde ich gerne sicherstellen, dass der iobroker nicht unkoordiniert Kommandos sendet und der Ecovacs Server auch nicht.

@mrbungle64 hast du noch eine andere Idee anhand des logs?

**Comment by mrbungle64** [comment]
> 
> @mrbungle64 hast du noch eine andere Idee anhand des logs?

@boriswerner 
Ich habe die Vermutung, dass die Fehlermeldungen "problem with request: connect ETIMEDOUT" vom controller asynchron zu den "state change map.deebotPosition" Meldungen ausgegeben werden. Es wäre also möglich, dass aus irgendwelchen Gründen diese state changes auslöst werden, weil der Server nicht antwortet.

Ich tippe also auf ein Problem den Ecovacs Server zu erreichen + dass der Adapter (oder die Library) nicht damit klar kommt, wenn es diese Art von Problemen gibt.

@volkerverkamp 
Hast Du es noch mal probiert bzw. auch parallel mal geschaut wie sich die Mobile App verhält?

**Comment by volkerverkamp** [comment]
> @volkerverkamp
> Hast Du es noch mal probiert bzw. auch parallel mal geschaut wie sich die Mobile App verhält?

Die Mobile App scheint tatsächlich auch (noch) mehr Probleme als sonst zu haben, eine Verbindung zum Server zu bekommen, funktioniert aber "irgendwie" (nach mehreren Versuchen). Den Adapter hatte ich jetzt eine zeitlang ausgeschaltet. Habe ihn gerade mal wieder gestartet und es kommen wieder regelmäßig die "Connected" Meldungen:
![image](https://user-images.githubusercontent.com/51383556/77533546-5d245280-6e97-11ea-865e-b57a370cde68.png)

Ich habe seit der Neuinstallation gestern übrigens den Adapter aus dem "Latest" Repo installiert, vorher war es die von Github.

Ich werde nachher mal die library wie oben beschrieben direkt starten und das Ergebnis posten.

**Comment by volkerverkamp** [comment]
Nachfolgend die Ausgabe des Direktaufrufs der Library (via app2.js siehe oben), der in gefühlt 9 von 10 Fällen mit folgendem Ergebnis fehlschlägt:
`eu
[EcovacsAPI] Setting up EcovacsAPI
[EcovacsAPI] calling main api user/login with {"account":"GiHbJPOD7z3bKM6fhSZeSuOZAKPywaeaaiW+T/BTMmYZLXapVg50NAZ6i2ckl2z8ASHdBhY+8rRRqIr562b+e36tGMfpWal1POG5/rrBpW4bk2rWxzvBpNHtuSrGzgKEBV4l1sQPQxsmMNTxHo8iK2xhsK34hw4K5SU3EVGz2o8=","password":"wUr8ROgUpajlvB52XoSCrfhMvNdJK4l7b0bEk8fy0/Z9ypjNS3B+a/7FKNXjMIP+lb/PHarMdQZY4b1IPxumrtwj98GrLRNWYlbNy7Ac8fKcDpdaBUTAUsDSJqWpG8czoRvMEqOq3uFPagnnr95idKlGJTDskwaHARv80XVf03s="}
[EcoVacsAPI] Calling https://eco-de-api.ecovacs.com/v1/private/DE/en/2c3ee31e14044aba66eee9ce422b1bd9/i_eco_e/1.3.5/c_googleplay/1/user/login?account=GiHbJPOD7z3bKM6fhSZeSuOZAKPywaeaaiW%2BT%2FBTMmYZLXapVg50NAZ6i2ckl2z8ASHdBhY%2B8rRRqIr562b%2Be36tGMfpWal1POG5%2FrrBpW4bk2rWxzvBpNHtuSrGzgKEBV4l1sQPQxsmMNTxHo8iK2xhsK34hw4K5SU3EVGz2o8%3D&password=wUr8ROgUpajlvB52XoSCrfhMvNdJK4l7b0bEk8fy0%2FZ9ypjNS3B%2Ba%2F7FKNXjMIP%2Blb%2FPHarMdQZY4b1IPxumrtwj98GrLRNWYlbNy7Ac8fKcDpdaBUTAUsDSJqWpG8czoRvMEqOq3uFPagnnr95idKlGJTDskwaHARv80XVf03s%3D&requestId=1e754246d702c2bf17898a8715982326&authTimespan=1585153080082&authTimeZone=GMT-8&authAppkey=eJUWrzRv34qFSaYk&authSign=775b762b0fc871277375d153fc6d75ab
[EcovacsAPI] got {"code":"0000","msg":"操作成功","time":1585153080179,"data":{"uid":"20200325171150_6d702b77923c6409ce99f3c167a28b07","username":"EA5UVTJU","email":"ecovacs2@verkamp.de","country":"DE","accessToken":"8a9b0323a06c87a4ed494fb9067d88f2"}}
[EcovacsAPI] calling main api user/getAuthCode with {"uid":"20200325171150_6d702b77923c6409ce99f3c167a28b07","accessToken":"8a9b0323a06c87a4ed494fb9067d88f2"}
[EcoVacsAPI] Calling https://eco-de-api.ecovacs.com/v1/private/DE/en/2c3ee31e14044aba66eee9ce422b1bd9/i_eco_e/1.3.5/c_googleplay/1/user/getAuthCode?uid=20200325171150_6d702b77923c6409ce99f3c167a28b07&accessToken=8a9b0323a06c87a4ed494fb9067d88f2&requestId=1e754246d702c2bf17898a8715982326&authTimespan=1585153080334&authTimeZone=GMT-8&authAppkey=eJUWrzRv34qFSaYk&authSign=d61129b4d0d169c70398cc39e92d0edc
[EcovacsAPI] got {"code":"0002","msg":"接口鉴权失败","time":1585153080367}
[EcovacsAPI] Failure code 0002
[EcovacsAPI] Failure code 0002 calling __call_main_api('user/getAuthCode', {...})
Failure in connecting:  Failure code 0002
`

**Comment by boriswerner** [comment]
@volkerverkamp Das ist leider normal und das, was auch in der App passiert, wenn eine Zeitüberschreitung angezeigt wird.
Da hilft leider nur so lange wiederholen, bis erfolgreich verbunden wird.

**Comment by mrbungle64** [comment]
@volkerverkamp  @boriswerner 
Ich war mal so frei die Ausgabe aus dem Post zu löschen

**Comment by volkerverkamp** [comment]
@mrbungle64 @boriswerner Danke, hätte ich auch selbst dran denken können..

**Comment by mrbungle64** [comment]
@volkerverkamp 
Besteht das Problem immer noch?

**Comment by volkerverkamp** [comment]
@mrbungle64 Nein in den letzten Tagen ist das nicht mehr aufgetreten, offenbar hing das wirklich mit den serverseitigen Problemen zusammen. 

Wirklich stabil ist die Verbindung in der App leider nicht mehr, ggf. hängt das auch mit dem letzten Update zusammen. Ich hab "früher" oft mittels Trial&Error Spot-Area-Koordinaten im Adapter eingegeben und konnte live in der App sehen, wie während der Reinigung das eingezeichnete Bereichs-Rechteck aktualisiert wurde. Das geht momentan nicht mehr ohne nach einer Änderung erst die Verbindung neu aufzubauen.
