### ISSUE TITLE
Which Ecovac to choose

### ISSUE THREAD

**Issue by Sascha8** [mrbungle64/ioBroker.ecovacs-deebot#446]
### The question

Hi, could you please recomend one of the ecovacs cleaners regarding best API support with your adapter?
Thx!

### Which model do you own?

None

**Comment by mrbungle64** [comment]
@Sascha8 

I would basically recommend one that meets your requirements the most, but if you want the best support for the ioBroker adapter I  would recommend one of the [fully supported models](https://github.com/mrbungle64/ioBroker.ecovacs-deebot#fully-supported-models).

The [other supported models](https://github.com/mrbungle64/ioBroker.ecovacs-deebot#other-supported-models) should also work fine, but I would advise against the [legacy models](https://github.com/mrbungle64/ioBroker.ecovacs-deebot#legacy-models-soon-to-be-discontinued) for several reasons.

**Comment by Sascha8** [comment]
Ich switche mal auf Deutsch ;)
Danke für die detaillierte Antwort... Klar, er sollte neben SmartHome Eignung auch vernünftig saugen ;) Ich hab aktuell n Prosenic M8 Pro und der tut ganz ordentlich, doch ist er ohne Kamera auch ziemlich blind unterwegs und wickelt gerne Kabel auf... Von daher wäre einer mit AIVI schon ne Bereicherung. Und n deutlich älteres Model kommt natürlich auch nicht wirklich in Frage... 
Sehe gerade Du hast den **X1 Turbo** frisch zu fully supported hinzugefügt... Ist das knows issue zu der X1 Serie noch aktuell?
"The generation of map images does not work properly with the Deebot X1 series"

**Comment by Sascha8** [comment]
Hmpf... Hab gerade mal zu den Details zum X1 gelesen - Man muss tatsächlich die Mops demontieren, wenn man auf Teppich saugen will? Das ist leider n NoGo für mich. Dachte moderne heben mittlerweile alle die Mops automatisch an, wenn nötig.
