### ISSUE TITLE
T9 AIVI: ecovacs-deebot.0.control.spotArea_cleanings

### ISSUE THREAD

**Issue by krobipd** [mrbungle64/ioBroker.ecovacs-deebot#464]
### Is there an existing issue for this?

- [X] I have searched the existing issues and no issue is describing my issue

### The problem

der datenpunkt ecovacs-deebot.0.control.spotArea_cleanings hat keine funktion

egal was ich hier eintrage ob 1 oder 2 dies hat keine Auswirkung auf die Häufigkeit des reinigens.

der datenpunkt "ecovacs-deebot.0.control.extended.cleanCount" hingegeben ist eigentlich der erwähnte Datenpunkt.

dH wenn im cleancount 1 drin steht reinigt er einmal usw
Änderungen im cleancount werden übernommen - mit piep - und auch hin der app widdergespiegelt - und natürlich umgekehrt in der app ändern ändert diesen Datenpunkt dementsprechend.

### With which model does the problem occur?

Deebot T9 series

### From which source you have installed the adapter?

Beta (latest)

### Version of the ioBroker adapter ("info.version")

1.4.13

### Version of the ecovacs-deebot.js library ("info.library.version")

0.9.3-beta.0

### Version of the JS controller

4.0.24

### Version of Node.js

v18.15.0

### Operating system

Linux

### Communication protocol ("info.library.communicationProtocol")

MQTT

### Is the canvas module installed? ("info.library.canvasModuleIsInstalled")

None

**Comment by mrbungle64** [comment]
@krobipd 

Verstehe ich das richtig?
- "ecovacs-deebot.0.control.extended.cleanCount" funktioniert wie erwartet
- "ecovacs-deebot.0.control.spotArea_cleanings" funktioniert gar nicht

**Comment by krobipd** [comment]
genau richtig erkannt 👍

aber gut ich weiß ja jetzt das der andere datenpunkt die Leistung anpasst (cleancount) ist daher jetzt nicht sonderlich schlimm - falls das überhaupt ein falsches verhalten ist?

aber auf alle fälle macht "spotarea-cleanings" absolut nichts.

**Comment by mrbungle64** [comment]
@krobipd 

Ich habe mir das noch mal angeschaut. Es ist ein bisschen kompliziert 😉 

"control.spotArea_cleanings" ist entstanden, als Modelle wie der T9 noch kein Thema waren.
Der OZMO 920/950 war das erste Modell wo man nativ die Anzahl für die anstehende Bereichsreinigung angeben konnte (1 oder 2). Für ältere Modelle hatte ich implementiert, dass dies simuliert wird - da das per App (also per API) nicht ging.
Habe dafür also 2 Varianten implementiert.

Dann kamen die aktuellen Modelle wo man die Anzahl fest einstellen kann, so dass diese permanent bestehen bleibt. Zusätzlich gibt es seit dem ja noch die Möglichkeit das Pro Raum einzeln festzulegen.

Wie man sieht, ist das bei den aktuellen Modellen zu viel des Guten 😉 

Ich tendiere also nun dazu "control.spotArea_cleanings" für aktuelle Modelle ab dem T8 (und damit auch für den T9 AIVI) zu entfernen.

**Comment by krobipd** [comment]
mit 1.4.14-alpha.3 gelöst
