### ISSUE TITLE
(5842) getaddrinfo ENOTFOUND eco-de-api.ecovacs.com eco-de-api.ecovacs.com:443

### ISSUE THREAD

**Issue by smarteule** [mrbungle64/ioBroker.ecovacs-deebot#48]
seit Dienstag ist der Adapter --> ROT <--

(5842) getaddrinfo ENOTFOUND eco-de-api.ecovacs.com eco-de-api.ecovacs.com:443
![image](https://user-images.githubusercontent.com/61357030/78241011-0b577a00-74e0-11ea-97e5-d78142fdca10.png)

**Comment by mrbungle64** [comment]
@smarteule 
Benutzt Du einen Proxy?
https://github.com/nodejs/node/issues/5436#issuecomment-607403531

**Comment by smarteule** [comment]
Nein, aber jetzt geht er wieder. Scheint an unserer DSL Leitung zu liegen. Vodafone
