### ISSUE TITLE
Zu Viele api anfragen

### ISSUE THREAD

**Issue by Zelkin0815** [mrbungle64/ioBroker.ecovacs-deebot#495]
### Is there an existing issue for this?

- [X] I have searched the existing issues and no issue is describing my issue

### The problem

ecouser.net wird viel zu oft abgefragt!

Mir hat PiHole den Broker gesperrt wegen zu vielen Anfragen (Standardeinstellung 1000/60sek)!
Hab jetzt ne halbe Ewigkeit nach dem Problem gesucht warum der Broker nicht mehr ins netz kommt.

selbst  bei 2000/30 hat er mich jetzt noch raus geschmissen

2 Plugins kommunizieren dabei extrem häufig:
ecovac deebot und Bring

kann man die Häufigkeit der Kommunikation verringern??

### With which model does the problem occur?

Deebot OZMO 950

### From which source you have installed the adapter?

Stable (default)

### Version of the ioBroker adapter ("info.version")

1.4.13

### Version of the ecovacs-deebot.js library ("info.library.version")

0.9.3-beta.0

### Version of the JS controller

4.0.24

### Version of Node.js

v18.16.0

### Operating system

Linux

### Communication protocol ("info.library.communicationProtocol")

None

### Is the canvas module installed? ("info.library.canvasModuleIsInstalled")

None

**Comment by mrbungle64** [comment]
@Zelkin0815 

Was meinst du mit "1000/60sek" und "2000/30"?

Hast du evtl. Skripte (Blockly oder ähnliches) welche auf irgendwas triggern?

**Comment by mrbungle64** [comment]
@Zelkin0815 

Es gibt die Einstellung "Abfrage-Intervall (Sekunden)".
Da würde ich beim OZMO 950 die Einstellung 180 empfehlen.
Siehe auch [hier](https://forum.iobroker.net/post/938174).

Ich kann mir aber beim besten Willen nicht vorstellen, dass der Adapter alleine so viele Anfragen schickt, dass PiHole da in einer Standard-Konfiguration schon zu macht.

Ich selbst habe 3 Instanzen vom Ecovacs Deebot Adapter in Betrieb und auch Bring und auch PiHole.
Probleme habe ich keine...

**Comment by Zelkin0815** [comment]
@mrbungle64 

Hab die 180 jetzt mal eingestellt, waren bisher 60 (hab Ich glaub nie verändert)

1000/60 soll heißen 1000 Anfragen von einem Client pro 60 Sekunden .... bei Überschreitung wird dieser geblockt

Ich wollte auch gar nicht darauf hinaus, dass der Adapter alleine dafür verantwortlich ist, es ist mir beim check des Query Log nur aufgefallen, dass die ecosuser adresse recht häufug auftaucht!

Hab jetzt mal ein wenig genauere zahlen aus dem pihole gezogen:
Nach Umstellung hat er jetzt knapp 50 anfragen an pi-hole in 2 Sekunden raus gehauen, dann erst mal nichts mehr!
372 in den letzten 30 min

Heute waren es allerdings bereits 20088 anfragen

Scripte hab Ich eigentlich keine laufen, die visu frägt daten ab ... sonst mach Ich mit dem Adapter bisher noch nicht viel!


Ich beobachte das jetzt mal ... wenn es jetzt signifikant weniger sind, probiere ich mal aus, ob es bei 60 sek. Abfrage Intervall zu einer 3 Fachen abfragemenge kommt (das wäre ja nachvollziehbar) oder ob es extrem viel mehr werden

**Comment by mrbungle64** [comment]
@Zelkin0815 

> Nach Umstellung hat er jetzt knapp 50 anfragen an pi-hole in 2 Sekunden raus gehauen, dann erst mal nichts mehr!
372 in den letzten 30 min

Ja, nach dem Start einer Instanz holt der Adapter die gesamten Daten zu den Maps. Daher ist das in den ersten Sekunden ein bisschen mehr. 372 Anfragen in 30 Minuten sind dann doch deutlich weniger als 1000/Min. 😉 

> Heute waren es allerdings bereits 20088 anfragen

Das wären dann so im Durchschnitt "nur" 20-30 pro Minute, wenn ich das richtig sehe. Also auch deutlich weniger als 1000/Min.

> Ich beobachte das jetzt mal ...

ok 👍🏻

**Comment by Zelkin0815** [comment]
@mrbungle64 

hab es mir jetzt nochmal ganz genau angeschaut (er war heute ja die meiste zeit geblockt ;) ) 
11:24:31 --> PiHole Neu gestartet
11:24:31 bis 11:29:30 --> 5988 anfragen --> 1197 / min
11:30:30 bis 11:45:00 --> 12850 --> 856 / min --> sind immer ca. 45 sek pause zwischen den anfrage Blöcken
Umstellung Abfrage Intervall
13:00:00 bis 13:15:00 --> 100 --> 6,6 / min

13:28 nochmal umgestellt auf 60 um zu testen!

13:30 bis 13:45 -->  300 --> 20 / min

Scheint mit der einmaligen Umstellung des Intervalls irgendwas gradegerückt zu haben .... die Blöcke sind jetzt auch viel kleiner 
um 11:32 hat er einen Block von ca 1000 anfragen raus gehauen dann 1 min  pause und weitere 800 dann min pause und nochmal 900

jetzt will er pro block noch um die 20

13:46 wieder auf 180 sek umgestellt

Wiederholbarkeit in dem fall nicht gegeben, Sorry für den aufwand! Hoffe die Info hilft wenigstens irgendwo mal weiter falls jemandem mal was ähnliches auffällt
