### ISSUE TITLE
Deebot 900 funktioniert nicht !

### ISSUE THREAD

**Issue by Atze68** [mrbungle64/ioBroker.ecovacs-deebot#5]
Hallo,
also mit dem Deebot 900 fuktioniert es auch nicht.
Lediglich der Verbindungsstatus wird mit "true" angezeigt, und der Robotername steht da.
Alles andere bleibt frei, auch beim Starten von Hand ändert sich nur die Zeitanzeige, des letzten Zugriffs.
Eintrag im LOG: 

ecovacs-deebot.0 | 2019-12-18 07:50:16.058 | info | run: stop
-- | -- | -- | --
ecovacs-deebot.0 | 2019-12-18 07:50:14.240 | info | run: stop

ecovacs-deebot.0 | 2019-12-18 07:53:53.605 | info | run: edge
-- | -- | -- | --

Schade :-(

**Comment by AudidriverA4** [comment]
Bei mir geht es leider auch nicht mit Depot 900

Instanz wird Grün, Objekte werden Teilweise Angezeigt.


2019-12-18 18:51:06.118 - debug: ecovacs-deebot.0 (4034) state change: [object Object]
--
2019-12-18 18:51:06.119 - debug: ecovacs-deebot.0 (4034) state change: [object Object]
2019-12-18 18:51:06.409 - error: ecovacs-deebot.0 (4034) Failure in connecting!
2019-12-18 18:51:06.415 - debug: ecovacs-deebot.0 (4034) state change: [object Object]
2019-12-18 18:51:06.419 - debug: ecovacs-deebot.0 (4034) state change: [object Object]

**Comment by mrbungle64** [comment]
Hallo @Atze68 und @AudidriverA4,

vielen Dank schon mal für die Informationen.

Handelt es sich dabei um "Deebot 900" oder "Deebot **Ozmo** 900" Geräte?
Es scheint als würde es beide Varianten geben ;)

**Comment by Atze68** [comment]
Hallo,
ich habe einen Deebot 900.

Gruß

**Comment by AudidriverA4** [comment]
Hi,
ich hab auch einen Depot 900

**Comment by mandre1904** [comment]
Hallo,

ich habe einen ECOVACS Robotics DEEBOT OZMO 900 und bekomme es auch nicht zum Laufen. Login Daten sind korrekt, die habe ich nochmal extra überprüft.

ecovacs-deebot.0 | 2019-12-21 15:13:09.942 | error | (7282) Failure in connecting!
ecovacs-deebot.0 | 2019-12-21 15:13:09.549 | info | (7282) reconnecting ...
ecovacs-deebot.0 | 2019-12-21 15:12:39.537 | error | (7282) Failure in connecting!
ecovacs-deebot.0 | 2019-12-21 15:12:38.936 | info | (7282) starting. Version 0.2.0 in /opt/iobroker/node_modules/iobroker.ecovacs-deebot, node: v8.15.0
ecovacs-deebot.0 | 2019-12-21 15:11:27.800 | info | (7158) Terminated (START_IMMEDIATELY_AFTER_STOP): Without reason
ecovacs-deebot.0 | 2019-12-21 15:11:27.797 | info | (7158) terminating
ecovacs-deebot.0 | 2019-12-21 15:11:27.796 | info | (7158) cleaned everything up...
ecovacs-deebot.0 | 2019-12-21 15:11:27.793 | info | (7158) Got terminate signal TERMINATE_YOURSELF
ecovacs-deebot.0 | 2019-12-21 15:11:10.973 | error | (7158) Failure in connecting!
ecovacs-deebot.0 | 2019-12-21 15:11:10.593 | info | (7158) reconnecting ...

**Comment by Bandit2001** [comment]
Hallo,
ich habe ebenfalls einen "ECOVACS Robotics DEEBOT OZMO 900" im Einsatz.
Die grundsätzliche Steuerung (Reinigung Start/Stop, Laden) funktioniert mit dem entsprecheden Alexa Skill.
Den "ecovacs-deebot" Adapter habe ich richtig installiert und konfiguriert, aber leider wird keine der Funktionen ausgeführt. Es gibt zwar die entsprechenden Einträge im Log:

> ecovacs-deebot.0 | 2019-12-21 16:44:27.002 | info | (26250) run: charge
> ecovacs-deebot.0 | 2019-12-21 16:43:05.915 | info | (26250) run: stop
> ecovacs-deebot.0 | 2019-12-21 16:42:34.686 | info | (26250) run: clean

aber es passiert leider nichts.
Wie kann man hier Abhilfe schaffen bzw. das Problem lösen?

Vielen Dank schon mal!

**Comment by gruenerpanzer** [comment]
Genau das Gleiche beim Ozmo 930

IoBroker-Adapter-Objekte:
<a href="https://www.bilder-upload.eu/bild-485cd1-1576955521.png.html" target="_blank"><img src="https://www.bilder-upload.eu/thumb/485cd1-1576955521.png" border="1" alt="Bilder-Upload.eu - share DEINE Bilder" /></a>

IoBroker-Logfile:
<a href="https://www.bilder-upload.eu/bild-608e93-1576955861.png.html" target="_blank"><img src="https://www.bilder-upload.eu/thumb/608e93-1576955861.png" border="1" alt="Bilder-Upload.eu - share DEINE Bilder" /></a>

**Comment by mrbungle64** [comment]
Hallo @mandre1904, @Bandit2001 und @gruenerpanzer,
danke für die Infos.

Ich habe mir heute einen Deebot OZMO 930 gekauft - ich hoffe, dass ich die Geräte in den nächsten Wochen soweit möglichst vollständig zum Laufen bekomme ;)

**Comment by rebel1985** [comment]
ich habe auch einen deebot ozmo 900 (den weißen) und auch nur die buttons die keine aktion durchführen, ich würde abhilfe versuchen mit dem sucks adapter oder mit bespoken (brauch eine reg. und token) um den skill in alexa zu steuern, deebot start , stop, nach hause fahren.

**Comment by mrbungle64** [comment]
> ich habe auch einen deebot ozmo 900 (den weißen) und auch nur die buttons die keine aktion durchführen, ich würde abhilfe versuchen mit dem sucks adapter oder mit bespoken (brauch eine reg. und token) um den skill in alexa zu steuern, deebot start , stop, nach hause fahren.

Hallo @rebel1985,

was meinst Du mit "ich würde abhilfe versuchen mit dem sucks adapter"? bzw. "oder mit bespoken ... um den skill in alexa zu steuern"?

Die sucks library wird bereits verwendet und unterstüzt leider viele Modelle nicht. Daher habe ich einen [Fork](https://github.com/mrbungle64/ecovacs-deebot.js) erstellt und versuche die library zu erweitern und auf einen aktuelleren Stand zu bringen ([hier](https://github.com/ioBroker/AdapterRequests/issues/76#issuecomment-571336093) die Info dazu im Adapter Request Issue).

**Comment by rebel1985** [comment]
befehle über bespoken an alexa senden, die dann die befehle an den skill schickt und der skill dann den deebot startet. hab ich aber noch nciht umgesetzt, hab ich noch vor. hatte nur irgendwo gelesen das einer das darüber gelöst hat. sache ist ja schrift befehle die dann mit einem skript vordefiniert sind an alexa schicken die diese dann auch umsetzt bzw verarbeitet.

**Comment by mrbungle64** [comment]
> Genau das Gleiche beim Ecovacs Deebot OZMO 930
> 
> IoBroker-Adapter-Objekte:
> [![Bilder-Upload.eu - share DEINE Bilder](https://camo.githubusercontent.com/b3dd7f152a4ecb7f60e6618fe464143bd28c0b05/68747470733a2f2f7777772e62696c6465722d75706c6f61642e65752f7468756d622f3438356364312d313537363935353532312e706e67)](https://www.bilder-upload.eu/bild-485cd1-1576955521.png.html)
> 
> IoBroker-Logfile:
> [![Bilder-Upload.eu - share DEINE Bilder](https://camo.githubusercontent.com/e6dacf899dc31d97b1a5ffccfeec316481076b12/68747470733a2f2f7777772e62696c6465722d75706c6f61642e65752f7468756d622f6533623235652d313537363935363032362e706e67)](https://www.bilder-upload.eu/bild-e3b25e-1576956026.png.html)

Hallo @gruenerpanzer,

der Ozmo 930 sollte mit der aktuellen Version des Adapters nun funktionieren.

Die Modelle Deebot 900 und Ozmo 900 werden aber wahrscheinlich weiterhin nicht funktionieren, da diese [wohl](https://github.com/bmartin5692/bumper#Compatibility) über anderes Protokoll (MQTT) kommunizieren.

**Comment by AudidriverA4** [comment]
Wie schon angegeben läuft der Depot 900 leider nicht :-(.

ich hoffe mal weiter auf das nächste Update :-) danke das ihr da am Ball bleibt finde ich super von euch.

<img width="1027" alt="Screenshot 2020-01-19 20 19 14" src="https://user-images.githubusercontent.com/46032677/72686881-32192d80-3af9-11ea-9efe-ad53e641180c.png">
<img width="1080" alt="Screenshot 2020-01-19 20 18 07" src="https://user-images.githubusercontent.com/46032677/72686882-347b8780-3af9-11ea-90ac-e6cf41354eb0.png">

**Comment by mrbungle64** [comment]
> Wie schon angegeben läuft der Depot 900 leider nicht :-(.
> 
> ich hoffe mal weiter auf das nächste Update :-) danke das ihr da am Ball bleibt finde ich super von euch.
> 
> <img alt="Screenshot 2020-01-19 20 19 14" width="1027" src="https://user-images.githubusercontent.com/46032677/72686881-32192d80-3af9-11ea-9efe-ad53e641180c.png">
> 
> <img alt="Screenshot 2020-01-19 20 18 07" width="1080" src="https://user-images.githubusercontent.com/46032677/72686882-347b8780-3af9-11ea-90ac-e6cf41354eb0.png">

Hallo @AudidriverA4,

könnest Du den Adapter bitte noch mal (neu) starten, bis er sich erfolgreich verbindet?
Mich würde vor allem interessieren, was dann unter 'info.communicationProtocol' eingetragen wird.
Vielen Dank!

**Comment by AudidriverA4** [comment]
<img width="1003" alt="Screenshot 2020-01-21 20 01 44" src="https://user-images.githubusercontent.com/46032677/72834360-f01ef180-3c88-11ea-88ca-2cd3d59dfe84.png">

Hab nochmal Instanz neu gestartet. Instanz ist Grün.

**Comment by mrbungle64** [comment]
> <img alt="Screenshot 2020-01-21 20 01 44" width="1003" src="https://user-images.githubusercontent.com/46032677/72834360-f01ef180-3c88-11ea-88ca-2cd3d59dfe84.png">
> 
> Hab nochmal Instanz neu gestartet. Instanz ist Grün.

ok, dann wird das schon mal richtig erkannt, dass es sich beim Deebot 900 um ein Gerät handelt, welches über MQTT kommuniziert.

Vielen Dank. Das hilft mir schon mal ein bisschen weiter :)

**Comment by AudidriverA4** [comment]
Supi freut mich, helf gern wenn ich kann. 
Danke für die Bemühungen.

**Comment by mrbungle64** [comment]
Hallo @AudidriverA4,

zu Deiner Frage aus dem Adapter Request
> Gibt es eigentlich noch Chancen das es mit DEEBOT 900 auch noch klappt oder ehr nicht ?

Ja die gibt es :) Mir fehlt aber leider ein entsprechendes Gerät zum Testen, was das gleiche Protokoll wie der Ozmo 900 und auch der Ozmo 950 spricht. [Hier](https://github.com/mrbungle64/ioBroker.ecovacs-deebot/issues/7) hat mir ein Besitzer von einem Ozmo 950 Unterstützung angeboten - ich hoffe, dass wir da was gemeinsam erreichen können.

**Comment by rebel1985** [comment]
[ozmo900.txt](https://github.com/mrbungle64/ioBroker.ecovacs-deebot/files/4174572/ozmo900.txt)

**Comment by rebel1985** [comment]
grad den adapter neu installiert, darüber kann ich starten, stoppen, laden, rest leider nicht.
so langsam wirds mit dem 900 :-)

**Comment by mrbungle64** [comment]
> [ozmo900.txt](https://github.com/mrbungle64/ioBroker.ecovacs-deebot/files/4174572/ozmo900.txt)
> 
> so ein wenig in der app rumgespielt. ist ne menge log für dich, hoffe hilft dir weiter.

@rebel1985, vielen Dank! Ja das hat mir geholfen - es gibt auch schon ein Update :)
Bin gespannt auf das Ergebnis :)

**Comment by mrbungle64** [comment]
> grad den adapter neu installiert, darüber kann ich starten, stoppen, laden, rest leider nicht.
> so langsam wirds mit dem 900 :-)

Das wundert mich ein bisschen, da die aktuelle Version vom ioBroker Adapter nicht die aktuelle Version von der Library benutzt, aber das freut mich trotzdem zu hören :)

**Comment by rebel1985** [comment]
> 
> 
> > grad den adapter neu installiert, darüber kann ich starten, stoppen, laden, rest leider nicht.
> > so langsam wirds mit dem 900 :-)
> 
> Das wundert mich ein bisschen, da die aktuelle Version vom ioBroker Adapter nicht die aktuelle Version von der Library benutzt, aber das freut mich trotzdem zu hören :)

hatte ja die neuste version installiert bevor ich das vorhin ausgeführt hatte

**Comment by mrbungle64** [comment]
> > > grad den adapter neu installiert, darüber kann ich starten, stoppen, laden, rest leider nicht.
> > > so langsam wirds mit dem 900 :-)
> > 
> > 
> > Das wundert mich ein bisschen, da die aktuelle Version vom ioBroker Adapter nicht die aktuelle Version von der Library benutzt, aber das freut mich trotzdem zu hören :)
> 
> hatte ja die neuste version installiert bevor ich das vorhin ausgeführt hatte

Der ioBroker Adapter benutzt Stand jetzt (auch wenn über github installiert) noch die 2 Tage alte Version 0.1.7 der Library von [npm](https://www.npmjs.com/package/ecovacs-deebot). Ich werde das morgen oder so dann mal auf eine aktuelle Version aktualisieren, wenn wir mit den Tests und meinen Anpassungen auf einem guten Stand angekommen sind :)

Den Code der Library die Du per `git clone` (unabhängig vom Adpater) beziehst, ist aber immer der aktuellste Stand. Dieser wird aber i.d.R. noch nicht im Adapter verwendet ;)

**Comment by mrbungle64** [comment]
> > [ozmo900.txt](https://github.com/mrbungle64/ioBroker.ecovacs-deebot/files/4174572/ozmo900.txt)
> > so ein wenig in der app rumgespielt. ist ne menge log für dich, hoffe hilft dir weiter.
> 
> @rebel1985, vielen Dank! Ja das hat mir geholfen - es gibt auch schon ein Update :)
> Bin gespannt auf das Ergebnis :)

Das genannte Update sollte schon Bugfixes enthalten die ich mit Hilfe von Deinem Log gemacht hatte.
Wenn Du Zeit und Lust hast kannst Du noch mal testen :)

**Comment by rebel1985** [comment]
> 
> 
> > > [ozmo900.txt](https://github.com/mrbungle64/ioBroker.ecovacs-deebot/files/4174572/ozmo900.txt)
> > > so ein wenig in der app rumgespielt. ist ne menge log für dich, hoffe hilft dir weiter.
> > 
> > 
> > @rebel1985, vielen Dank! Ja das hat mir geholfen - es gibt auch schon ein Update :)
> > Bin gespannt auf das Ergebnis :)
> 
> Das genannte Update sollte schon Bugfixes enthalten die ich mit Hilfe von Deinem Log gemacht hatte.
> Wenn Du Zeit und Lust hast kannst Du noch mal testen :)

hi, ja teste ich nacher noch mal wieder aus

**Comment by rebel1985** [comment]
[ozmo 900.txt](https://github.com/mrbungle64/ioBroker.ecovacs-deebot/files/4180831/ozmo.900.txt)

**Comment by mrbungle64** [comment]
> [ozmo 900.txt](https://github.com/mrbungle64/ioBroker.ecovacs-deebot/files/4180831/ozmo.900.txt)

@rebel1985 

Danke Dir! In dem Log habe ich gefunden, dass der Akku einen Wert von 98% hatte :)
Das hatte ich vorher bei einem MQTT Device noch nicht dabei.

**Comment by mrbungle64** [comment]
@Atze68 @AudidriverA4 @mandre1904 @Bandit2001 @rebel1985 
Ich habe soeben die Version 0.3.10 auf GitHub veröffentlicht. Die Chancen stehen ganz gut, dass inzwischen bei den Modellen Deebot 900 und Deebot Ozmo 900 so einiges funktioniert.

@gruenerpanzer 
Der Ozmo 930 funktioniert seit einiger Zeit schon sehr gut. Kannst Du das bestätigen?

cc: @boriswerner

**Comment by oOchrisOo** [comment]
Guten Abend,
beim 900 bzw. 901 wird die info komplett angezeigt und beim steuern funktioniere  start, Pause und zurück zur Ladestation.
Verbrauchsmaterial wird leider noch nicht angezeigt.
Vielen Dank für den tollen Adapter und die Arbeit  :-D

**Comment by mrbungle64** [comment]
> Guten Abend,
> beim 900 bzw. 901 wird die info komplett angezeigt und beim steuern funktioniere start, Pause und zurück zur Ladestation.
> Verbrauchsmaterial wird leider noch nicht angezeigt.
> Vielen Dank für den tollen Adapter und die Arbeit :-D

Hallo @oOchrisOo 

vielen Dank für die Infos :)

Ich hätte 2 Fragen:
- Ist das ein "Deebot 901" (also ohne "Ozmo")?
- Welches Proptokoll steht unter 'info.communicationProtocol'?

**Comment by Atze68** [comment]
hallo zusammen, bei mir funktioniert es auch, vielen Dank für eure Arbeit.

Gruss, Atze
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit 1&1 Mail gesendet.Am 18.02.20, 21:35 schrieb Sascha <notifications@github.com>:

   
   Guten Abend, beim 900 bzw. 901 wird die info komplett angezeigt und beim steuern funktioniere start, Pause und zurück zur Ladestation. Verbrauchsmaterial wird leider noch nicht angezeigt. Vielen Dank für den tollen Adapter und die Arbeit :-D 
   
  Hallo @oOchrisOo 
  vielen Dank für die Infos :) 
  Ich hätte 2 Fragen: 
   
   Ist das ein "Deebot 901" (also ohne "Ozmo")? 
   Welches Proptokoll steht unter 'info.communicationProtocol'?

**Comment by oOchrisOo** [comment]
> > Guten Abend,
> > beim 900 bzw. 901 wird die info komplett angezeigt und beim steuern funktioniere start, Pause und zurück zur Ladestation.
> > Verbrauchsmaterial wird leider noch nicht angezeigt.
> > Vielen Dank für den tollen Adapter und die Arbeit :-D
> 
> Hallo @oOchrisOo
> 
> vielen Dank für die Infos :)
> 
> Ich hätte 2 Fragen:
> 
> * Ist das ein "Deebot 901" (also ohne "Ozmo")?
> * Welches Protokoll steht unter 'info.communicationProtocol'?

MQTT
Und es ist ein 901 ohne ozmo

**Comment by mrbungle64** [comment]
@oOchrisOo @Atze68 

Funktioniert bei Euch

- playSound
- spotArea ("Bereich" genannt in der App)
- customArea ("Benutzerdef." genannt in der App)

im Adapter?

customArea erwartet 4 komma-separierte numerische Werte für den Bereich.

Beispiel: -3975,2280,-1930,4575
0,0,0,0 ist meiner Erfahrung nach die Ladestation
Ein Wert bzw. Distanz von 1000 entspricht bei mir ca. 1 Meter

**Comment by Atze68** [comment]
Hi, Sound und Verbrauchsmaterial geht bei mir nicht, Zonenreinigung funktioniert problemlos.

**Comment by AudidriverA4** [comment]
<img width="1246" alt="Screenshot 2020-02-19 17 24 15" src="https://user-images.githubusercontent.com/46032677/74852614-1cd43080-533d-11ea-926a-c598650d0aaf.png">

Heut nach dem ich Nachhause kam war er wie jeden Tag automatisch unterwegs und er hat einige Infos da gelassen :-)

Sound geht was beim Deebot 900 bei Play Sound kommt Musik wie beim einschalten.

Verbrauchsmaterial wird bei mir auch nicht Angezeigt.

Supi wird immer besser ihr seit der Hit :-)

**Comment by mrbungle64** [comment]
Der Deebot 900 scheint jetzt weitgehend zu funktionieren.
Für den Deebot OZMO 900 bitte ich neue Issues zu erstellen.
Ebenso für neues Feedback oder Fehlermeldungen zu Deebot 900.

**Comment by mrbungle64** [comment]
Der Deebot 900 scheint jetzt weitgehend zu funktionieren.
Für den Deebot OZMO 900 bitte ich neue Issues zu erstellen.
Ebenso für neues Feedback oder Fehlermeldungen zu Deebot 900.
