### ISSUE TITLE
Robot not reachable

### ISSUE THREAD

**Issue by MotschaM** [mrbungle64/ioBroker.ecovacs-deebot#504]
### Is there an existing issue for this?

- [X] I have searched the existing issues and no issue is describing my issue

### The problem

"Object control.extended.volume is invalid: Default value has to be type "number" but received type "string""

"This object will not be created in future versions. Please report this to the developer."

Das sind die Meldungen im Log. 

### With which model does the problem occur?

Deebot OZMO 950

### From which source you have installed the adapter?

Stable (default)

### Version of the ioBroker adapter ("info.version")

1.4.13

### Version of the ecovacs-deebot.js library ("info.library.version")

 0.9.3-beta

### Version of the JS controller

4.0.24

### Version of Node.js

v16.13.0

### Operating system

Linux

### Anything in the logs that might be useful?

```txt
"Object control.extended.volume is invalid: Default value has to be type "number" but received type "string""

"This object will not be created in future versions. Please report this to the developer."
```

### Communication protocol ("info.library.communicationProtocol")

None

### Is the canvas module installed? ("info.library.canvasModuleIsInstalled")

None

**Comment by mrbungle64** [comment]
Hallo @MotschaM 

die Meldung im Text ("Default value has to be type number but received type string") kann ich nicht nachvollziehen, da der Defaultwert beim Datenpunkt "control.extended.volume" ein numerischer Wert ist (`0`).

Leider passt diese Meldung aber auch nicht zum Titel "Robot not reachable". Da müsstest Du mir noch mehr Informationen geben.

**Comment by MotschaM** [comment]
Welche Infos würdest du denn brauchen? Das ist alles was im Log gestanden hat. Jetzt hab ich den Adapter mal Pausiert und es ist weg. Die erste Instanz läuft einwandfrei nur wie gesagt bei der 2. klappt es nicht ganz so. Roboter lässt sich aber trotzdem steuern.

**Comment by mrbungle64** [comment]
@MotschaM 

Beschreibe doch bitte einfach mal dein konkretes Problem 😉 

Der Titel lautet "Robot not reachable":
* Ist das eine weitere Meldung im Log 
* oder ist das die kurze Beschreibung deines Problems?

Unter "The Problem" ist etwas aufgeführt was aktuell kein Problem ist ("... in future versions ...").
Zusätzlich kann ich das nicht nicht mal nachvollziehen, da der Defaultwert wie gesagt `0` ist (was dem Typ "number" entspricht und keinem "String").

> Jetzt hab ich den Adapter mal Pausiert und es ist weg.

Was ist "weg"?

> Die erste Instanz läuft einwandfrei nur wie gesagt bei der 2. klappt es nicht ganz so. Roboter lässt sich aber trotzdem steuern.

Das hilft mir leider gar nicht. "klappt es nicht ganz so" ist eine mehr als knappe Beschreibung eines Problems.

**Comment by mrbungle64** [comment]
@MotschaM 

Besteht das Problem weiterhin oder hat es sich erledigt?

**Comment by mrbungle64** [comment]
Problem konnte nicht ausreichend beschrieben werden und scheint sich erledigt zu haben.
