### ISSUE TITLE
Replaced Deebots data doesn't show up in iobroker

### ISSUE THREAD

**Issue by lzimmermann** [mrbungle64/ioBroker.ecovacs-deebot#509]
### The question

Hi, thank you for this cool adapter!

After replacing by deboot N8 with a new one (gurantee) the data of the new deboot does not apper in ioBroker. I still see the old data (Akku Status, Last cleaning time,...)
Any Idea how to fix this?

Regards
Lars

### Which model do you own?

Deebot N8 series

### Which version of the ioBroker adapter are you currently using?

1.4.13

**Comment by mrbungle64** [comment]
@lzimmermann 

> ### The question
> 
> Hi, thank you for this cool adapter!

Thanks for the feedback 👍🏻

> 
> After replacing by deboot N8 with a new one (gurantee) the data of the new deboot does not apper in ioBroker. I still see the old data (Akku Status, Last cleaning time,...)
> Any Idea how to fix this?

I think that you have to change the device number in the settings

> 
> Regards
> Lars
> 
> ### Which model do you own?
> 
> Deebot N8 series
> 
> ### Which version of the ioBroker adapter are you currently using?
> 
> 1.4.13
> 
> ### Additional information
> 
> _No response_

**Comment by mrbungle64** [comment]
@lzimmermann 

Did this solve your problem?

**Comment by mrbungle64** [comment]
It seems that the problem has been solved ...
