### ISSUE TITLE
...was compiled against a different Node.js version

### ISSUE THREAD

**Issue by smarteshome2020** [mrbungle64/ioBroker.ecovacs-deebot#529]
### Is there an existing issue for this?

- [X] I have searched the existing issues and no issue is describing my issue

### The problem

Hallo, ich erhalte immer wieder sehr viele Fehlermeldungen im Log.
Kann es sein das ich den Adapter neu installieren muss? Sorry, bin kein Linux Spezialist. :-)

<html>
<body>

2023-08-19 15:38:43.664 - warn: ecovacs-deebot.0 (590) The module '/opt/iobroker/node_modules/ecovacs-deebot/node_modules/canvas/build/Release/canvas.node'
--
was compiled against a different Node.js version using
NODE_MODULE_VERSION 83. This version of Node.js requires
NODE_MODULE_VERSION 108. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).

</body>
</html>

### With which model does the problem occur?

Deebot N8 series

### From which source you have installed the adapter?

Stable (default)

### Version of the ioBroker adapter ("info.version")

1.4.13

### Version of the ecovacs-deebot.js library ("info.library.version")

keine Ahnung wo ich das finde :-(

### Version of the JS controller

4.0.24

### Version of Node.js

18.17.0

### Operating system

Linux

### Communication protocol ("info.library.communicationProtocol")

None

### Is the canvas module installed? ("info.library.canvasModuleIsInstalled")

None

**Comment by mrbungle64** [comment]
Hallo @smarteshome2020 

das hier sollte dein Problem lösen:
https://github.com/mrbungle64/ioBroker.ecovacs-deebot/wiki/FAQ#nodejs-upgrade

**Comment by smarteshome2020** [comment]
Danke für die Unterstützung. Das scheint mein Problem gelöst zu haben.

**Comment by mrbungle64** [comment]
@smarteshome2020 

> Jetzt haben ich folgende Meldung im LOg:
> instance system.adapter.ecovacs-deebot.0 terminated due to SIGSEGV

Ich nehme mal an, dass Du die Instanz noch nicht neu gestartet hattest.
