### ISSUE TITLE
Status: Charging

### ISSUE THREAD

**Issue by Grizzelbee** [mrbungle64/ioBroker.ecovacs-deebot#54]
Wenn der Bot auf der Ladestation steht, zeigt sowohl der Status des Bots als auch der Charging Status immer: charging. Auch wenn der Akku bereits bei 100% ist.
* Ich hätte erwartet dass der charging status bei 100% auf idle, finished oder so wechselt. Ich persönlich fände das auch Boolean Status besser. Das Ding lädt ... oder eben nicht. Ein Charging true/false würde also vollkommen ausreichen.
* Ich hätte erwartet das es die beiden Status "Bot-Status" und "Charing Status" gibt um dort unterschiedliche Dinge anzuzeigen. Sprich: Wenn der Bot auf der Station steht und lädt ist der Bot Idle und charging true, wenn er zu 100% geladen ist, ist er Idle und Charging  false, wenn er saugt, ist er cleaning und charging false, ...
Ich fände das nachvollziehbarer. 
Ähnlich übrigens bei dem Error. Fände ich als ErrorIndicator (True/False) und ErrorMessage besser.

Wie siehst du das?

**Comment by mrbungle64** [comment]
Hi @Grizzelbee 

ich verstehe was Du meinst - wir hatten auch in verschiedenen anderen Issues schon über die versch. Status diskutiert.

Bisher wird quasi das was die Ecovacs API liefert dort eingetragen (mit kleinen Ausnahmen).
Als Beispiel hier die lookup table zum "chargestatus":

```javascript
CHARGE_MODE_FROM_ECOVACS = {
    'Going': 'returning',
    'going': 'returning',
    'SlotCharging': 'charging',
    'slot_charging': 'charging',
    'WireCharging': 'charging',
    'Idle': 'idle',
    'idle': 'idle'
};
```

Die Ecovacs API liefert keinen Wert für "finished". Das ist auch quasi das was in der Mobile App zu sehen ist. Dort wird bei 100% geladenem Akku auch weiterhin das Ladesymbol angezeigt.

Eine Erweiterung um diesen Status bei 100% hört sich jetzt erst mal nicht so aufwändig an, aber das kann auch schon mal täuschen, wenn sich die Status aus versch. Quellen und Zuständen ergeben und dann andere davon anhängig sind - wie z.B. der `deviceStatus`... der ist eine Kombination aus `chargestatus` und `cleanstatus`.

Alternative dazu wären dann zusätzliche States (z.B. als Boolean) - aber auch da kommen wir so langsam in eine Region wo mir das manchmal schon fast zu viele werden. Muss also auch alles im Rahmen bleiben.

Zuletzt waren wir auch erst mal froh, dass die Status und auch die andern Funktionen bei sämtlichen Modellen soweit korrekt funktioniert haben (schon schwierig genug ohne eine Doku für die API zu haben).

Ich finde deine Ansätze für den 'chargestatus' soweit gut und auch logisch nachvollziehbar.
Aktuell sind wir allerdings an anderen Stellen unterwegs. Die Status-Baustelle möchte ich gerne erst wieder aufmachen, wenn der erste Stable Release mal soweit gemacht ist.

Btw: Ich entferne mal das die Modellbez. aus dem Titel - das hier betrifft ja alle Modelle.

**Comment by Grizzelbee** [comment]
Freue mich, wenn ich helfen kann. Stehe mit meinem eigenen Adapter ja immer wieder vor dem gleichen Problem. ;-) Das hier hat aber keine besondere Eile.
Die Status durchzureichen, die die API liefert finde ich vom Prinzip her vollkommen OK. Mache ich auch meist so. Führe aber auch gerne schon mal spezielle ein, wenn es für die Darstellung in der VIS oder als Trigger für Skripte nützlich ist.
Das der ChargeStatus auf charging bleibt, könnte ja auch daran liegen, das der tatsächlich immer und immer weiter lädt. Das wäre zwar ein Armutszeugnis für Ecovacs, weil ich denen schon zutraue eine Akku-schonende Ladeschaltung zu bauen, aber möglich und denkbar ist es trotzdem. Was allerdings das "returning" beim Chargestatus zu suchen hat, weiß nur Ecovacs allein.
Ansonsten: Daumen hoch und vielen Dank für den Adapter! Ich hatte selber schon drüber nachgedacht einen zu schreiben.

**Comment by boriswerner** [comment]
Hi, da der Akkustand immer bei 100% bleibt, wenn er auf der Ladestation steht, lädt er schon irgendwie stetig, wenn er steht. Wenn man ihn abseits der Station stehen hat kann man ja quasi zusehen, wie der Akkustand fällt (zumindest bei meinem 950). Von daher ist der Status ja schon was anderes als ein normales "idle" abseits der Station.
In der VIS oder generell kann man sich dann ja auch recht einfach aus der Kombination von chargeStatus "charging" und dem Akkustand "100%" ein "charging completed" oder ein anderes Flag erstellen. 
Ich würde hier also auch eher möglichst nah bei den Werten aus der API bleiben, damit es nachvollziehbar (vor allem auch in der Entwicklung ;-) ) bleibt. Ich steig ehrlicherweise beim deviceStatus schon nicht mehr wirklich durch :-D

**Comment by mrbungle64** [comment]
> Hi, da der Akkustand immer bei 100% bleibt, wenn er auf der Ladestation steht, lädt er schon irgendwie stetig, wenn er steht. Wenn man ihn abseits der Station stehen hat kann man ja quasi zusehen, wie der Akkustand fällt (zumindest bei meinem 950). Von daher ist der Status ja schon was anderes als ein normales "idle" abseits der Station.

@boriswerner 
Ja Du hast recht - eine ständige WiFi Verbindung kostet ja Strom ;)
