### ISSUE TITLE
Deebot Ozmo 900: Waterbox funktioniert nicht

### ISSUE THREAD

**Issue by Grizzelbee** [mrbungle64/ioBroker.ecovacs-deebot#55]
Der Datenpunkt für die Waterbox steht immer auf "false".

**Comment by mrbungle64** [comment]
> Der Datenpunkt für die Waterbox steht immer auf "false".

Du meinst den Deebot Ozmo 900?

**Comment by Grizzelbee** [comment]
Yapp. Meine ich. Mir war nicht klar, dass Ecovacs so verrückt ist einen Deebot 900 und einen Deebot Ozmo 900 heraus zu bringen. :)

**Comment by mrbungle64** [comment]
> Yapp. Meine ich. Mir war nicht klar, dass Ecovacs so verrückt ist einen Deebot 900 und einen Deebot Ozmo 900 heraus zu bringen. :)

Die "Ozmo"-Serie ist die mit Wischfunktion ;)

**Comment by mrbungle64** [comment]
> Der Datenpunkt für die Waterbox steht immer auf "false".

- Welche Version benutzt Du?
- Hatte das bei einer voherigen Version schon mal funktioniert?
  - Und falls "ja": Welche Version war das?

**Comment by Grizzelbee** [comment]
Hatte noch eine ältere 0.5.8 instaliert.
Habe gerade mal die aktuelle von GIT genommen und siehe da - funktioniert.
Die Bezeichnung ist nur vielleicht etwas irreführend, weil der Datenpunkt auf erst dann true geht, wenn die **Wischplatte** montiert wird. ;-)
