### ISSUE TITLE
can you please add Australia for country for my ecovacs 920? 🙏

### ISSUE THREAD

**Issue by valtoree** [mrbungle64/ioBroker.ecovacs-deebot#550]
hi as above,
I think I have done correct install of iobroker and adapter via the dashboard.
but in instances the ecovacs is orange when I try to start service. last item "connected to device or service" is X'd red cross. I believe because I can't select Australia. and selected another country. thank you for all your work.

**Comment by mrbungle64** [comment]
@valtoree 

Sorry for late reply 🙏🏻  I'll add Australia with the next alpha release.

**Comment by valtoree** [comment]
❤️ ty @mrbungle64

**Comment by mrbungle64** [comment]
@valtoree 

Please try version 1.4.14-alpha.11 from GitHub.

I must apologise again for taking so long. I think I missed this issue.

**Comment by mrbungle64** [comment]
@valtoree 

Can we close this issue?

**Comment by valtoree** [comment]
hi thank you for communication, I will try to update my app soon, and try again with the Australia setting. tx again

**Comment by valtoree** [comment]
if you want to close it you can, I assume all is well. I haven't gotten around to updating the version I installed, via github instructions or youtuber. I'm a noob with this github space. but I'll figure it out how to update to the next alpha release. tx again. 👍

**Comment by mrbungle64** [comment]
@mrbungle64 

> I haven't gotten around to updating the version I installed

You can also try whether "Indonesia" works, for example.

**Comment by valtoree** [comment]
👍 with Indonesia now is green lit up so it seems like the instance is now on. next quest is how to use iobroker with this. I will close the issue. ty mrbungle64 🙏
