### ISSUE TITLE
Adapter is consuming a lot of memory

### ISSUE THREAD

**Issue by manoloxxl** [mrbungle64/ioBroker.ecovacs-deebot#56]
Hi,

Great adapter - thanks for sharing it. But i thing it's consuming a lot of memory. I just installed the adapter and it takes over 200MB Ram after a while without doing anything.

It starts with 50MB (like any other adapter) but after a while its over 200MB.

Is there something like a debug-flag active?

Recently i do a restart of the instance every day... ;)

Best Regards
Manuel

**Comment by mrbungle64** [comment]
Hi Manuel,

What model do you use?
Are you using the latest version from GitHub?

**Comment by manoloxxl** [comment]
Hi,

I'm using a Deebot 950 with v0.5.8 from GitHub. iObroker is up-to-date, expect nodejs (is v10.17.0).
Hardware is a Raspi 4 with 2GB Ram.

Manuel

**Comment by mrbungle64** [comment]
We fixed a simular issue some days ago:
https://github.com/mrbungle64/ioBroker.ecovacs-deebot/issues/53

Have you already tried with the latest version from GitHub (it's still version 0.5.8)?

**Comment by manoloxxl** [comment]
I will give a try - just watched for the open issues ;)

Und so wie ich sehe, gehts auch auf deutsch. Ich installiere die Version mal neu, denke aber es wird der gleiche Fehler wie beim verlinkten sein.

**Comment by mrbungle64** [comment]
> Und so wie ich sehe, gehts auch auf deutsch. Ich installiere die Version mal neu, denke aber es wird der gleiche Fehler wie beim verlinkten sein.

Hi @manoloxxl 

kannst Du schon Feedback dazu geben?

**Comment by manoloxxl** [comment]
> > Und so wie ich sehe, gehts auch auf deutsch. Ich installiere die Version mal neu, denke aber es wird der gleiche Fehler wie beim verlinkten sein.
> 
> Hi @manoloxxl
> 
> kannst Du schon Feedback dazu geben?

Hi @mrbungle64 ,

kann ich: der Adapter steht nun stabil bei seinen ca. 60-70MB. Also deutlich besser als vorher.
Ganz vielen Dank!

**Comment by mrbungle64** [comment]
@manoloxxl 
Freut mich :+1: 
Ich schließe den Issue dann mal
