### ISSUE TITLE
Map specific cleanSpotArea buttons not working / relocationState empty

### ISSUE THREAD

**Issue by boriswerner** [mrbungle64/ioBroker.ecovacs-deebot#57]
Bei den spots kommt nur das hier, sonst passiert rein gar nix

`	(5580) state change 0.cleanSpotArea => true `

Könnte es vl damit zusammen hängen das bei relocationState nichts drin steht? Ich sehe in der history das da mal Sachen drin standen aber seit einigen Tagen nur null oder nichts drin steht.

![image](https://user-images.githubusercontent.com/27220902/79261136-af053a80-7e8f-11ea-8623-8ee6a35d2e02.jpeg)

_Originally posted by @krobipd in https://github.com/mrbungle64/ioBroker.ecovacs-deebot/issues/53#issuecomment-613611313_

**Comment by boriswerner** [comment]
@krobipd du hattest hier ja noch Probleme. 
Ich hab heute bei mir die neueste Adapter-Version von Github testweise installiert und kann auch mit leerem relocationState eine spotReinigung starten (bei mir z.B. ecovacs-deebot.0.map.302903113.spotAreas.4.cleanSpotArea).
Der relocationState  ist leer, wenn der Adapter neu gestartet wurde und noch kein relocate ausgeführt wurde (entweder manuell in iobroker, der App oder automatisch wenn der Bot vor dem Reinigungsvorgang nicht weiß, wo er ist). Daran liegt es also nicht.
Kannst du nochmal testen? Da war zwischendurch wohl was mit dem State-Pfad nicht korrekt.
Bei mir im Log steht dann:
debug - state change map.cleanSpotArea => true
info - start cleaning spot area: 4 on map 302903113

**Comment by krobipd** [comment]
Danke für die Info, werde ich ausprobieren, danke

**Comment by krobipd** [comment]
Vielen Dank, habe das gerade mit dem aktuellen git getestet und jetzt funktioniert das wieder 👍🥳

**Comment by mrbungle64** [comment]
@boriswerner @krobipd 

Können wir den Issue schließen?

**Comment by krobipd** [comment]
Ja, close 
Tausend Dank
