### ISSUE TITLE
Consumeables don't refresh

### ISSUE THREAD

**Issue by Dragon0501** [mrbungle64/ioBroker.ecovacs-deebot#58]
Rhe consumeables of my hoover are all new. I reset them by the app but the percentage isnt correct

**Comment by mrbungle64** [comment]
> Rhe consumeables of my hoover are all new. I reset them by the app but the percentage isnt correct

Hi @Dragon0501 

I need further information:
- What model do you use?
- Which version do you have installed?
- When did you reset the values by the app?
- Have you already restarted the adpater?

**Comment by Dragon0501** [comment]
Sorry I forgot that information.
My Model is an N79T
Installed Version 0.5.9
I reset the values about three days ago
I restarted the adapter and the ioBroker (raspberry pi) already

**Comment by mrbungle64** [comment]
@Dragon0501 

Were the values correct before the reset?

**Comment by Dragon0501** [comment]
no they were not. Many weeks ago the were correct. At the Moment they say 14, 27 and 14%.
The correct percentages are 100, 50 and 100

**Comment by Dragon0501** [comment]
ecovacs-deebot.0 | 2020-04-25 18:45:28.551 | info | (2981) getGetPosInterval - deviceClass: 165
-- | -- | -- | --
ecovacs-deebot.0 | 2020-04-25 18:45:28.548 | info | (2981) [vacbot] name: DEEBOT N79T/W
ecovacs-deebot.0 | 2020-04-25 18:45:28.546 | info | (2981) Lisa successfully connected
ecovacs-deebot.0 | 2020-04-25 18:45:27.523 | info | (2981) Using device Device[0]
ecovacs-deebot.0 | 2020-04-25 18:45:27.522 | info | (2981) Device[0]: {"did":"E0001218518607503031","name":"E0001218518607503031","class":"165","resource":"atom","nick":"Lisa","company":"eco-legacy"}
ecovacs-deebot.0 | 2020-04-25 18:45:27.522 | info | (2981) Number of devices: 1
ecovacs-deebot.0 | 2020-04-25 18:45:27.521 | info | (2981) Successfully connected to Ecovacs server
ecovacs-deebot.0 | 2020-04-25 18:45:27.142 | warn | (2981) no connection to objects DB
ecovacs-deebot.0 | 2020-04-25 18:45:25.462 | info | (2981) starting. Version 0.5.9 in /opt/iobroker/node_modules/iobroker.ecovacs-deebot, node: v10.19.0
ecovacs-deebot.0 | 2020-04-25 18:45:25.085 | info | (2981) starting. Version 0.5.9 in /opt/iobroker/node_modules/iobroker.ecovacs-deebot, node: v10.19.0

**Comment by Dragon0501** [comment]
There is a warn in the Log
Is that  maybe the problem?

**Comment by mrbungle64** [comment]
> no they were not. Many weeks ago the were correct ...

Can you remember the approximate date?

**Comment by mrbungle64** [comment]
> There is a warn in the Log
> Is that maybe the problem?

No, that has nothing to do with it

**Comment by Dragon0501** [comment]
No I am sorry

**Comment by Dragon0501** [comment]
I worked with version 0.3.4 till today. updated today because I recognized it today.

**Comment by mrbungle64** [comment]
@Dragon0501 

Can you install this library on your raspberry pi?

1)
```bash
git clone https://github.com/mrbungle64/ecovacs-deebot.js.git
cd ecovacs-deebot.js
npm install
cd example
```

2) change email and password in the file `app2.js`

3) execute the example app and post the output (wait for output for 30-60 sec.)
```bash
NODE_ENV=dev node app2.js | grep -E 'LifeSpan|lifeSpan|brush|Brush|heap|Heap|total'
```

**Comment by Dragon0501** [comment]
mom

**Comment by Dragon0501** [comment]
waiting for about three minutes and the robot constantly running and changing cleaning mode

**Comment by Dragon0501** [comment]
pi@raspberrypi:~/ecovacs-deebot.js/example$ NODE_ENV=dev node app2.js | grep -E 'LifeSpan|lifeSpan|brush|Brush|heap|Heap|total'
[app2.js] hasMainBrush: true
(node:9969) [DEP0107] DeprecationWarning: tls.convertNPNProtocols() is deprecated.
[VacBot] action: GetLifeSpan
[VacBot] Sending command `GetLifeSpan`
[EcovacsXMPP] Sending xml: <iq id="3" to="E0001218518607503031@165.ecorobot.net/atom" from="dh2vb1af828d056e@ecouser.net/4f3231a5" type="set"><query xmlns="com:ctl"><ctl td="GetLifeSpan" type="Brush" id="47320914"/></query></iq>
[VacBot] action: GetLifeSpan
[VacBot] Sending command `GetLifeSpan`
[EcovacsXMPP] Sending xml: <iq id="4" to="E0001218518607503031@165.ecorobot.net/atom" from="dh2vb1af828d056e@ecouser.net/4f3231a5" type="set"><query xmlns="com:ctl"><ctl td="GetLifeSpan" type="SideBrush" id="73463288"/></query></iq>
[VacBot] action: GetLifeSpan
[VacBot] Sending command `GetLifeSpan`
[EcovacsXMPP] Sending xml: <iq id="5" to="E0001218518607503031@165.ecorobot.net/atom" from="dh2vb1af828d056e@ecouser.net/4f3231a5" type="set"><query xmlns="com:ctl"><ctl td="GetLifeSpan" type="DustCaseHeap" id="50591035"/></query></iq>
stanza: <iq to="dh2vb1af828d056e@ecouser.net/5c81662693de3b3122ea9ad123c36031" type="set" id="731" from="E0001218518607503031@165.ecorobot.net/atom" xmlns:stream="http://etherx.jabber.org/streams"><query xmlns="com:ctl"><ctl id="47320914" ret="ok" errno="" type="Brush" val="050" total="365"/></query></iq>
firstChild: <query xmlns="com:ctl"><ctl id="47320914" ret="ok" errno="" type="Brush" val="050" total="365"/></query>
secondChild: <ctl id="47320914" ret="ok" errno="" type="Brush" val="050" total="365"/>
[VacBot] lifeSpan main_brush: 13.698630136986301
[VacBot] lifespan components:  {"main_brush":13.698630136986301}
[app2.js] main_brush: 14
stanza: <iq to="dh2vb1af828d056e@ecouser.net/5c81662693de3b3122ea9ad123c36031" type="set" id="732" from="E0001218518607503031@165.ecorobot.net/atom" xmlns:stream="http://etherx.jabber.org/streams"><query xmlns="com:ctl"><ctl id="73463288" ret="ok" errno="" type="SideBrush" val="100" total="365"/></query></iq>
firstChild: <query xmlns="com:ctl"><ctl id="73463288" ret="ok" errno="" type="SideBrush" val="100" total="365"/></query>secondChild: <ctl id="73463288" ret="ok" errno="" type="Sid Brush" val="100" total="365"/>
[VacBot] lifeSpan side_brush: 27.397260273972602
[VacBot] lifespan components:  {"main_brush":13.698630136986301,"side_brush":27.397260273972602}
[app2.js] side_brush: 27
stanza: <iq to="dh2vb1af828d056e@ecouser.net/5c81662693de3b3122ea9ad123c36031" type="set" id="733" from="E0001218518607503031@165.ecorobot.net/atom" xmlns:stream="http://etherx.jabber.org/streams"><query xmlns="com:ctl"><ctl id="50591035" ret="ok" errno="" type="DustCaseHeap" val="100" total="365"/></query></iq>
firstChild: <query xmlns="com:ctl"><ctl id="50591035" ret="ok" errno="" type="DustCaseHeap" val="100" total="365"/></query>
secondChild: <ctl id="50591035" ret="ok" errno="" type="DustCaseHeap" val="100" total="365"/>
[VacBot] lifeSpan filter: 27.397260273972602
[VacBot] lifespan components:  {"main_brush":13.698630136986301,"side_brush":27.397260273972602,"filter":27.397260273972602}

**Comment by Dragon0501** [comment]
Do i need to erase the things i installed or isn't it necessary?

**Comment by mrbungle64** [comment]
> Do i need to erase the things i installed or isn't it necessary?

No, you don't need to erase things that you already installed before

**Comment by Dragon0501** [comment]
no, I ment the things I installed by your commands. Does it affect the running system?

**Comment by mrbungle64** [comment]
> no, I ment the things I installed by your commands. Does it affect the running system?

No :)

**Comment by Dragon0501** [comment]
OK, thank you. Does this information helps you? Can I do something else?

**Comment by mrbungle64** [comment]
> OK, thank you. Does this information helps you? Can I do something else?

Yes, can you please execute the follwing now:

```bash
NODE_ENV=dev node app2.js | grep -E 'left|val'
```

**Comment by Dragon0501** [comment]
pi@raspberrypi:~$ NODE_ENV=dev node app2.js | grep -E 'left|val'
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '/home/pi/app2.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
pi@raspberrypi:~$

**Comment by mrbungle64** [comment]
> pi@raspberrypi:~$ NODE_ENV=dev node app2.js | grep -E 'left|val'
> internal/modules/cjs/loader.js:638
> throw err;
> ^
> 
> Error: Cannot find module '/home/pi/app2.js'
> at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
> at Function.Module._load (internal/modules/cjs/loader.js:562:25)
> at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
> at startup (internal/bootstrap/node.js:283:19)
> at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
> pi@raspberrypi:~$

You have to change directory first ;)

```
cd ecovacs-deebot.js/example
```

**Comment by Dragon0501** [comment]
pi@raspberrypi:~$ cd ecovacs-deebot.js/example
pi@raspberrypi:~/ecovacs-deebot.js/example$ NODE_ENV=dev node app2.js | grep -E 'left|val'
(node:3588) [DEP0107] DeprecationWarning: tls.convertNPNProtocols() is deprecated.

**Comment by Dragon0501** [comment]
that's all what I got by this command.

**Comment by mrbungle64** [comment]
@Dragon0501 
I guess there are parts of the output missing:

> pi@raspberrypi:~/ecovacs-deebot.js/example$ NODE_ENV=dev node app2.js | grep -E 'LifeSpan|lifeSpan|brush|Brush|heap|Heap|total'
> ...
> firstChild:
> secondChild:

Can you please repeat that command again and check if there's some output for "secondChild"

```bash
NODE_ENV=dev node app2.js | grep -E 'LifeSpan|lifeSpan|brush|Brush|heap|Heap|total'
```

**Comment by Dragon0501** [comment]
In the post there was just an answer for second child. first child was empty

**Comment by mrbungle64** [comment]
> In the post there was just an answer for second child. first child was empty

secondChild is part of firstChild ;)

Can you please execute that command again:

```bash
NODE_ENV=dev node app2.js | grep -E 'LifeSpan|lifeSpan|brush|Brush|heap|Heap|total'
```

**Comment by Dragon0501** [comment]
pi@raspberrypi:~$ cd ecovacs-deebot.js/example
pi@raspberrypi:~/ecovacs-deebot.js/example$ NODE_ENV=dev node app2.js | grep -E 'LifeSpan|lifeSpan|brush|Brush|heap|Heap|total'
[app2.js] hasMainBrush: true
(node:2709) [DEP0107] DeprecationWarning: tls.convertNPNProtocols() is deprecated.
[VacBot] action: GetLifeSpan
[VacBot] Sending command `GetLifeSpan`
[EcovacsXMPP] Sending xml: <iq id="3" to="E0001218518607503031@165.ecorobot.net/atom" from="dh2vb1af828d056e@ecouser.net/4f3231a5" type="set"><query xmlns="com:ctl"><ctl td="GetLifeSpan" type="Brush" id="28605011"/></query></iq>
[VacBot] action: GetLifeSpan
[VacBot] Sending command `GetLifeSpan`
[EcovacsXMPP] Sending xml: <iq id="4" to="E0001218518607503031@165.ecorobot.net/atom" from="dh2vb1af828d056e@ecouser.net/4f3231a5" type="set"><query xmlns="com:ctl"><ctl td="GetLifeSpan" type="SideBrush" id="83011891"/></query></iq>
[VacBot] action: GetLifeSpan
[VacBot] Sending command `GetLifeSpan`
[EcovacsXMPP] Sending xml: <iq id="5" to="E0001218518607503031@165.ecorobot.net/atom" from="dh2vb1af828d056e@ecouser.net/4f3231a5" type="set"><query xmlns="com:ctl"><ctl td="GetLifeSpan" type="DustCaseHeap" id="81264810"/></query></iq>
^C
pi@raspberrypi:~/ecovacs-deebot.js/example$ NODE_ENV=dev node app2.js | grep -E 'LifeSpan|lifeSpan|brush|Brush|heap|Heap|total'
[app2.js] hasMainBrush: true
(node:3298) [DEP0107] DeprecationWarning: tls.convertNPNProtocols() is deprecated.
[VacBot] action: GetLifeSpan
[VacBot] Sending command `GetLifeSpan`
[EcovacsXMPP] Sending xml: <iq id="3" to="E0001218518607503031@165.ecorobot.net/atom" from="dh2vb1af828d056e@ecouser.net/4f3231a5" type="set"><query xmlns="com:ctl"><ctl td="GetLifeSpan" type="Brush" id="38456334"/></query></iq>
[VacBot] action: GetLifeSpan
[VacBot] Sending command `GetLifeSpan`
[EcovacsXMPP] Sending xml: <iq id="4" to="E0001218518607503031@165.ecorobot.net/atom" from="dh2vb1af828d056e@ecouser.net/4f3231a5" type="set"><query xmlns="com:ctl"><ctl td="GetLifeSpan" type="SideBrush" id="87290783"/></query></iq>
[VacBot] action: GetLifeSpan
[VacBot] Sending command `GetLifeSpan`
[EcovacsXMPP] Sending xml: <iq id="5" to="E0001218518607503031@165.ecorobot.net/atom" from="dh2vb1af828d056e@ecouser.net/4f3231a5" type="set"><query xmlns="com:ctl"><ctl td="GetLifeSpan" type="DustCaseHeap" id="50320437"/></query></iq>
^C
pi@raspberrypi:~/ecovacs-deebot.js/example$ NODE_ENV=dev node app2.js | grep -E 'LifeSpan|lifeSpan|brush|Brush|heap|Heap|total'
[app2.js] hasMainBrush: true
(node:3635) [DEP0107] DeprecationWarning: tls.convertNPNProtocols() is deprecated.
[VacBot] action: GetLifeSpan
[VacBot] Sending command `GetLifeSpan`
[EcovacsXMPP] Sending xml: <iq id="3" to="E0001218518607503031@165.ecorobot.net/atom" from="dh2vb1af828d056e@ecouser.net/4f3231a5" type="set"><query xmlns="com:ctl"><ctl td="GetLifeSpan" type="Brush" id="85998321"/></query></iq>
[VacBot] action: GetLifeSpan
[VacBot] Sending command `GetLifeSpan`
[EcovacsXMPP] Sending xml: <iq id="4" to="E0001218518607503031@165.ecorobot.net/atom" from="dh2vb1af828d056e@ecouser.net/4f3231a5" type="set"><query xmlns="com:ctl"><ctl td="GetLifeSpan" type="SideBrush" id="48944034"/></query></iq>
[VacBot] action: GetLifeSpan
[VacBot] Sending command `GetLifeSpan`
[EcovacsXMPP] Sending xml: <iq id="5" to="E0001218518607503031@165.ecorobot.net/atom" from="dh2vb1af828d056e@ecouser.net/4f3231a5" type="set"><query xmlns="com:ctl"><ctl td="GetLifeSpan" type="DustCaseHeap" id="33517216"/></query></iq>
stanza: <iq to="dh2vb1af828d056e@ecouser.net/9300b41f61219b2d1a479b863a7b6d73" type="set" id="20" from="E0001218518607503031@165.ecorobot.net/atom" xmlns:stream="http://etherx.jabber.org/streams"><query xmlns="com:ctl"><ctl id="85998321" ret="ok" errno="" type="Brush" val="050" total="365"/></query></iq>
firstChild: <query xmlns="com:ctl"><ctl id="85998321" ret="ok" errno="" type="Brush" val="050" total="365"/></query>
secondChild: <ctl id="85998321" ret="ok" errno="" type="Brush" val="050" total="365"/>
[VacBot] lifeSpan main_brush: 13.698630136986301
[VacBot] lifespan components:  {"main_brush":13.698630136986301}
[app2.js] main_brush: 14
stanza: <iq to="dh2vb1af828d056e@ecouser.net/9300b41f61219b2d1a479b863a7b6d73" type="set" id="23" from="E0001218518607503031@165.ecorobot.net/atom" xmlns:stream="http://etherx.jabber.org/streams"><query xmlns="com:ctl"><ctl id="48944034" ret="ok" errno="" type="SideBrush" val="100" total="365"/></query></iq>
firstChild: <query xmlns="com:ctl"><ctl id="48944034" ret="ok" errno="" type="SideBrush" val="100" total="365"/></query>
secondChild: <ctl id="48944034" ret="ok" errno="" type="SideBrush" val="100" total="365"/>
[VacBot] lifeSpan side_brush: 27.397260273972602
[VacBot] lifespan components:  {"main_brush":13.698630136986301,"side_brush":27.397260273972602}
[app2.js] side_brush: 27
stanza: <iq to="dh2vb1af828d056e@ecouser.net/9300b41f61219b2d1a479b863a7b6d73" type="set" id="24" from="E0001218518607503031@165.ecorobot.net/atom" xmlns:stream="http://etherx.jabber.org/streams"><query xmlns="com:ctl"><ctl id="33517216" ret="ok" errno="" type="DustCaseHeap" val="100" total="365"/></query></iq>
firstChild: <query xmlns="com:ctl"><ctl id="33517216" ret="ok" errno="" type="DustCaseHeap" val="100" total="365"/></query>
secondChild: <ctl id="33517216" ret="ok" errno="" type="DustCaseHeap" val="100" total="365"/>
[VacBot] lifeSpan filter: 27.397260273972602
[VacBot] lifespan components:  {"main_brush":13.698630136986301,"side_brush":27.397260273972602,"filter":27.397260273972602}

**Comment by Dragon0501** [comment]
pi@raspberrypi:~$ cd ecovacs-deebot.js/example
pi@raspberrypi:~/ecovacs-deebot.js/example$ NODE_ENV=dev node app2.js | grep -E 'LifeSpan|lifeSpan|brush|Brush|heap|Heap|total'
[app2.js] hasMainBrush: true
(node:2709) [DEP0107] DeprecationWarning: tls.convertNPNProtocols() is deprecated.
[VacBot] action: GetLifeSpan
[VacBot] Sending command `GetLifeSpan`
[EcovacsXMPP] Sending xml: <iq id="3" to="E0001218518607503031@165.ecorobot.net/atom" from="dh2vb1af828d056e@ecouser.net/4f3231a5" type="set"><query xmlns="com:ctl"><ctl td="GetLifeSpan" type="Brush" id="28605011"/></query></iq>
[VacBot] action: GetLifeSpan
[VacBot] Sending command `GetLifeSpan`
[EcovacsXMPP] Sending xml: <iq id="4" to="E0001218518607503031@165.ecorobot.net/atom" from="dh2vb1af828d056e@ecouser.net/4f3231a5" type="set"><query xmlns="com:ctl"><ctl td="GetLifeSpan" type="SideBrush" id="83011891"/></query></iq>
[VacBot] action: GetLifeSpan
[VacBot] Sending command `GetLifeSpan`
[EcovacsXMPP] Sending xml: <iq id="5" to="E0001218518607503031@165.ecorobot.net/atom" from="dh2vb1af828d056e@ecouser.net/4f3231a5" type="set"><query xmlns="com:ctl"><ctl td="GetLifeSpan" type="DustCaseHeap" id="81264810"/></query></iq>
^C
pi@raspberrypi:~/ecovacs-deebot.js/example$ NODE_ENV=dev node app2.js | grep -E 'LifeSpan|lifeSpan|brush|Brush|heap|Heap|total'
[app2.js] hasMainBrush: true
(node:3298) [DEP0107] DeprecationWarning: tls.convertNPNProtocols() is deprecated.
[VacBot] action: GetLifeSpan
[VacBot] Sending command `GetLifeSpan`
[EcovacsXMPP] Sending xml: <iq id="3" to="E0001218518607503031@165.ecorobot.net/atom" from="dh2vb1af828d056e@ecouser.net/4f3231a5" type="set"><query xmlns="com:ctl"><ctl td="GetLifeSpan" type="Brush" id="38456334"/></query></iq>
[VacBot] action: GetLifeSpan
[VacBot] Sending command `GetLifeSpan`
[EcovacsXMPP] Sending xml: <iq id="4" to="E0001218518607503031@165.ecorobot.net/atom" from="dh2vb1af828d056e@ecouser.net/4f3231a5" type="set"><query xmlns="com:ctl"><ctl td="GetLifeSpan" type="SideBrush" id="87290783"/></query></iq>
[VacBot] action: GetLifeSpan
[VacBot] Sending command `GetLifeSpan`
[EcovacsXMPP] Sending xml: <iq id="5" to="E0001218518607503031@165.ecorobot.net/atom" from="dh2vb1af828d056e@ecouser.net/4f3231a5" type="set"><query xmlns="com:ctl"><ctl td="GetLifeSpan" type="DustCaseHeap" id="50320437"/></query></iq>
^C
pi@raspberrypi:~/ecovacs-deebot.js/example$ NODE_ENV=dev node app2.js | grep -E 'LifeSpan|lifeSpan|brush|Brush|heap|Heap|total'
[app2.js] hasMainBrush: true
(node:3635) [DEP0107] DeprecationWarning: tls.convertNPNProtocols() is deprecated.
[VacBot] action: GetLifeSpan
[VacBot] Sending command `GetLifeSpan`
[EcovacsXMPP] Sending xml: <iq id="3" to="E0001218518607503031@165.ecorobot.net/atom" from="dh2vb1af828d056e@ecouser.net/4f3231a5" type="set"><query xmlns="com:ctl"><ctl td="GetLifeSpan" type="Brush" id="85998321"/></query></iq>
[VacBot] action: GetLifeSpan
[VacBot] Sending command `GetLifeSpan`
[EcovacsXMPP] Sending xml: <iq id="4" to="E0001218518607503031@165.ecorobot.net/atom" from="dh2vb1af828d056e@ecouser.net/4f3231a5" type="set"><query xmlns="com:ctl"><ctl td="GetLifeSpan" type="SideBrush" id="48944034"/></query></iq>
[VacBot] action: GetLifeSpan
[VacBot] Sending command `GetLifeSpan`
[EcovacsXMPP] Sending xml: <iq id="5" to="E0001218518607503031@165.ecorobot.net/atom" from="dh2vb1af828d056e@ecouser.net/4f3231a5" type="set"><query xmlns="com:ctl"><ctl td="GetLifeSpan" type="DustCaseHeap" id="33517216"/></query></iq>
stanza: <iq to="dh2vb1af828d056e@ecouser.net/9300b41f61219b2d1a479b863a7b6d73" type="set" id="20" from="E0001218518607503031@165.ecorobot.net/atom" xmlns:stream="http://etherx.jabber.org/streams"><query xmlns="com:ctl"><ctl id="85998321" ret="ok" errno="" type="Brush" val="050" total="365"/></query></iq>
firstChild: <query xmlns="com:ctl"><ctl id="85998321" ret="ok" errno="" type="Brush" val="050" total="365"/></query>
secondChild: <ctl id="85998321" ret="ok" errno="" type="Brush" val="050" total="365"/>
[VacBot] lifeSpan main_brush: 13.698630136986301
[VacBot] lifespan components:  {"main_brush":13.698630136986301}
[app2.js] main_brush: 14
stanza: <iq to="dh2vb1af828d056e@ecouser.net/9300b41f61219b2d1a479b863a7b6d73" type="set" id="23" from="E0001218518607503031@165.ecorobot.net/atom" xmlns:stream="http://etherx.jabber.org/streams"><query xmlns="com:ctl"><ctl id="48944034" ret="ok" errno="" type="SideBrush" val="100" total="365"/></query></iq>
firstChild: <query xmlns="com:ctl"><ctl id="48944034" ret="ok" errno="" type="SideBrush" val="100" total="365"/></query>
secondChild: <ctl id="48944034" ret="ok" errno="" type="SideBrush" val="100" total="365"/>
[VacBot] lifeSpan side_brush: 27.397260273972602
[VacBot] lifespan components:  {"main_brush":13.698630136986301,"side_brush":27.397260273972602}
[app2.js] side_brush: 27
stanza: <iq to="dh2vb1af828d056e@ecouser.net/9300b41f61219b2d1a479b863a7b6d73" type="set" id="24" from="E0001218518607503031@165.ecorobot.net/atom" xmlns:stream="http://etherx.jabber.org/streams"><query xmlns="com:ctl"><ctl id="33517216" ret="ok" errno="" type="DustCaseHeap" val="100" total="365"/></query></iq>
firstChild: <query xmlns="com:ctl"><ctl id="33517216" ret="ok" errno="" type="DustCaseHeap" val="100" total="365"/></query>
secondChild: <ctl id="33517216" ret="ok" errno="" type="DustCaseHeap" val="100" total="365"/>
[VacBot] lifeSpan filter: 27.397260273972602
[VacBot] lifespan components:  {"main_brush":13.698630136986301,"side_brush":27.397260273972602,"filter":27.397260273972602}
^^

**Comment by Dragon0501** [comment]
[Rückmeldung.pdf](https://github.com/mrbungle64/ioBroker.ecovacs-deebot/files/4533827/Ruckmeldung.pdf)

**Comment by Dragon0501** [comment]
If I post it here the interesting parts will be erased. I don't know why

**Comment by Dragon0501** [comment]
firstChild: <query xmlns="com:ctl"><ctl id="85998321" ret="ok" errno="" type="Brush" val="050" total="365"/></query>
secondChild: <ctl id="85998321" ret="ok" errno="" type="Brush" val="050" total="365"/>

**Comment by Dragon0501** [comment]
> firstChild: <query xmlns="com:ctl"><ctl id="85998321" ret="ok" errno="" type="Brush" val="050" total="365"/></query>
secondChild: <ctl id="85998321" ret="ok" errno="" type="Brush" val="050" total="365"/>

**Comment by mrbungle64** [comment]
> [Rückmeldung.pdf](https://github.com/mrbungle64/ioBroker.ecovacs-deebot/files/4533827/Ruckmeldung.pdf)

This contains the data that I need. Thank you! :)

**Comment by Dragon0501** [comment]
You are welcome. Thank you for your work and quick assistance

**Comment by mrbungle64** [comment]
That's maybe a bug again in the firmware or the Ecovacs API.

`total` = `365`. Has to be `100` I guess ;)

```
<ctl id="48944034" ret="ok" errno="" type="SideBrush" val="100" total="365"/>
<ctl id="85998321" ret="ok" errno="" type="Brush" val="050" total="365"/>
<ctl id="33517216" ret="ok" errno="" type="DustCaseHeap" val="100"
total="365"/>
```

**Comment by mrbungle64** [comment]
I'll try to implement a workaround for that model and try to include it in the next release.

**Comment by Dragon0501** [comment]
Thank you very much. I will go to bed now. Send a short message if I can do something else.
Regards

**Comment by Dragon0501** [comment]
> That's maybe another bug in the firmware or the Ecovacs API.
> 
> `total` = `365`. Has to be `100` I guess ;)
> or `val` = `365` respectively `182` or `183` (Brush)
> 
> ```
> <ctl id="48944034" ret="ok" errno="" type="SideBrush" val="100" total="365"/>
> <ctl id="85998321" ret="ok" errno="" type="Brush" val="050" total="365"/>
> <ctl id="33517216" ret="ok" errno="" type="DustCaseHeap" val="100"
> total="365"/>
> ```

Ah ok, I see what you mean. The value is correct but the total count is incorrect. 
Regards

**Comment by mrbungle64** [comment]
> > That's maybe another bug in the firmware or the Ecovacs API.
> > `total` = `365`. Has to be `100` I guess ;)
> > or `val` = `365` respectively `182` or `183` (Brush)
> > ```
> > <ctl id="48944034" ret="ok" errno="" type="SideBrush" val="100" total="365"/>
> > <ctl id="85998321" ret="ok" errno="" type="Brush" val="050" total="365"/>
> > <ctl id="33517216" ret="ok" errno="" type="DustCaseHeap" val="100"
> > total="365"/>
> > ```
> 
> Ah ok, I see what you mean. The value is correct but the total count is incorrect.
> Regards

Yes, either the value of the `value` attribute is incorrect or the value of the `total` attribute ;)

**Comment by boriswerner** [comment]
The 950 response is looking like this:
{"type":"brush","left":16798,"total":18000}
{"type":"sideBrush","left":7691,"total":9000}
{"type":"heap","left":5998,"total":7200}
So the attribute is already named "left".
That results in the following values from the library {"main_brush":93.32222222222222,"side_brush":85.45555555555555,"filter":83.30555555555556}
The app is always rounding up, so it shows 94%, 86% and 84%.

Would be interesting to know what happens after a reset of the values for all models.
For the N79T perhaps the value always shows the percentage and the total is an addition of the historic available capacities? Just an idea...

**Comment by mrbungle64** [comment]
@Dragon0501 
The "bug" should be fixed with the latest version from GitHub (but still version 0.5.9).

**Comment by Dragon0501** [comment]
![Screenshot 2020-04-28 at 23 19 53](https://user-images.githubusercontent.com/59663011/80538959-e05d2a80-89a6-11ea-9f17-22ae80750dfe.png)

**Comment by mrbungle64** [comment]
You’re welcome. Thanks for the feedback :+1:
