### ISSUE TITLE
ecovacs-deebot.0.status > status not changing

### ISSUE THREAD

**Issue by pisabird** [mrbungle64/ioBroker.ecovacs-deebot#589]
### Is there an existing issue for this?

- [X] I have searched the existing issues and no issue is describing my issue

### The problem

Hello,

The status will not change anymore since 3 days. It only change, when I restart the instance.

### With which model does the problem occur?

Deebot OZMO 950

### From which source you have installed the adapter?

Stable (default)

### Version of the ioBroker adapter ("info.version")

5.3.8 (last version with the option to get back to the perfect gui) !!! :)

### Version of the ecovacs-deebot.js library ("info.library.version")

1.4.13 

### Version of the JS controller

 4.0.23

### Version of Node.js

v16.20.2

### Operating system

Linux

### Communication protocol ("info.library.communicationProtocol")

None

### Is the canvas module installed? ("info.library.canvasModuleIsInstalled")

yes (true)

**Comment by mrbungle64** [comment]
@pisabird 

> ecovacs-deebot.0.status > status

Do you mean "ecovacs-deebot.0.status.device"?

> The status will not change anymore since 3 days. It only change, when I restart the instance.

I need more information about your case.
What about the other states and what appears in the log while the robot is cleaning?

**Comment by pisabird** [comment]
@mrbungle64 
Do you mean "ecovacs-deebot.0.status.device"?
Yes 

Other states like ecovacs-deebot.0.control.cleanSpeed will updates, but positions like 

ecovacs-deebot.0.map.deebotPosition_x
ecovacs-deebot.0.map.deebotPosition_y 

not.

Here is the log


ecovacs-deebot.0 | 2023-11-16 14:48:35.079 | info | (6992) Start cleaning spot area: 9 on map 1073712973
ecovacs-deebot.0 | 2023-11-16 14:47:41.032 | info | (6992) Run: charge

**Comment by pisabird** [comment]
Hello, I do not know if you have change anything, but it works....
