### ISSUE TITLE
Ozmo 900 geht nicht

### ISSUE THREAD

**Issue by Leprechaun91** [mrbungle64/ioBroker.ecovacs-deebot#6]
Hey,

Es wird keine Verbindung zu meinem ozmo 900 hergestellt. Die Lampe bleibt auf gelb stehen.

**Comment by mrbungle64** [comment]
Hallo @Leprechaun91,

wahrscheinlich konnte sich der Adapter in diesem Moment nicht mit der Cloud verbinden.
Mit der Einstellung 'Max. Versuche wenn die Verbindung fehlschlägt' in der Adapter Config kannst du das Verhalten beeinflussen, wie oft der Adapter es versuchen soll.

Die bisherigen [Erfahrungswerte](https://github.com/mrbungle64/ioBroker.ecovacs-deebot/issues/5) sind, dass die Verbindung bei den verschiedenen Modellen grundsätzlich funktionieren sollte - der Ozmo 900 selbst aktuell aber nur sehr eingeschränkt funktionieren wird.

In der [Readme](https://github.com/mrbungle64/ioBroker.ecovacs-deebot/blob/master/README.md) sind die bisher getesten Modelle aufgeführt. Im [Adapter Request Issue](https://github.com/ioBroker/AdapterRequests/issues/76#issuecomment-571336093) habe ich vor einer Woche ein Update zum aktuellen Stand der Entwicklung gegeben.

Da bereits ein Issue für den Deebot (Ozmo) 900 [existiert](https://github.com/mrbungle64/ioBroker.ecovacs-deebot/issues/5) werde ich diesen hier als Duplicate schließen.
