### ISSUE TITLE
Errormessage anzeigen

### ISSUE THREAD

**Issue by firechhe** [mrbungle64/ioBroker.ecovacs-deebot#60]
Hallo,

besteht die Möglichkeit die ErrorMessage auszulesen? Habe durchaus mal den Fall, dass sich etwas in den Seitenbürsten verfängt. Das zeigt die App auch an. In ioBroker kann ich das leider nicht finden. Auch das Feld "error" blieb in diesem Fall leer.

![Screenshot_20200427-145255](https://user-images.githubusercontent.com/43295016/80393931-731b9d80-88b1-11ea-8aab-2aca5f01281b.jpg)

**Comment by mrbungle64** [comment]
Hallo @firechhe 

Eigentlich sollte der Adapter das anzeigen.
Ich habe auch einen Ozmo 930 - ich teste das mal wenn ich wieder Zuhause bin.

**Comment by mrbungle64** [comment]
@firechhe 

also die ErrorMessages funktionieren grundsätzlich noch.
Wenn ich die Staubbox entferne wird das im Adapter angezeigt. 

Der ErrorCode für die Meldung bei Dir sollte die 108 sein ("SideAbnormal: Side Brushes are tangled"):
https://github.com/mrbungle64/ecovacs-deebot.js/blob/master/library/errorCodes.js

Welche Version vom Adapter hast Du installiert?

**Comment by firechhe** [comment]
Habe die 0.5.8 installiert. Habe nun nochmal einen Test gemacht und beim Saugen den Staubbehälter rausgenommen oder den Sauger auf den Kopf gedreht... Die Meldungen werden sauber in den Objekten angezeigt.
Keine Ahnung warum das heute Mittag nicht der Fall war. Habe mich da allerdings auch mit dem Smartphone auf ioBroker geschaltet... Vllt war die Darstellung einfach nicht in Ordnung.
