### ISSUE TITLE
X2 Steuerung

### ISSUE THREAD

**Issue by Stormbringer11** [mrbungle64/ioBroker.ecovacs-deebot#606]
### The feature request

Hallo MrBungle,

erst mal vielen Dank für den tollen Adapter. Hat wirklich einen sehr guten Umfang. 

Bin seit Jahren von Roborock auf Deebot umgestiegen aber schaffe es irgendwie nicht den X2 so in den Broker einzubinden wie ich es vom Roborock gewohnt bin... Vom den DPs her dürfte das eigentlich kein Problem sein. Aber entweder stelle ich mich zu blöd an oder die Steuerung mit dem X2 funktioniert noch nicht wirklich. Weiß es ist Beta, mich verwundert nur, dass es bei anderen wohl klappt.

1. Kein Wasser einstellen. Die Option gibt es bei mir gar nicht
2. Spotareas gehen gar nicht. Egal ob ich den DP 
ecovacs-deebot.0.control.spotArea_6
ecovacs-deebot.0.control.spotArea
ecovacs-deebot.0.map.X.spotAreas.6.cleanSpotArea
es steht zwar im LOG, dass er die Reinigung startet. Der Roboter macht aber nichts. 
Eigentlich funktioniert nur Starten vom Roboter bis jetzt..... 
3. Karte kriege ich auch keine
4. Der eigentliche Featurerequest, der die Punkte 1-2 fast überflüssig machen würde :-)  Das Starten von einer benutzerdefinierten Reinigung (in der App unter Anpassen). Wäre das machbar in den Adapter mit aufzunehmen?

Vielen Dank im Voraus.

### Which model do you own?

Other model

### Which version of the ioBroker adapter are you currently using?

Deebot X2 Omni

**Comment by mrbungle64** [comment]
@Stormbringer11 

Welche Version verwendest Du?
Falls noch nicht der Fall: Benutze bitte die aktuelle Version von GitHub (aktuell 1.4.14-alpha.15)

**Comment by Stormbringer11** [comment]
Oh sorry, verwende die Github 1.4.14-alpha.13

**Comment by Stormbringer11** [comment]
Muß ich den Adapter vorher löschen? Merk keinen Unterschied....

**Comment by mrbungle64** [comment]
@Stormbringer11 

> Oh sorry, verwende die Github 1.4.14-alpha.13

Ok, wenn du schon die 1.4.14-alpha.13 verwendest dann macht es keinen Unterschied mehr beim X2 (im Vergleich zur 1.4.14-alpha.15)

**Comment by mrbungle64** [comment]
@Stormbringer11 

Angeblich funktioniert der X2 Omni ja grundsätzlich:
https://github.com/mrbungle64/ioBroker.ecovacs-deebot/issues/540

Da ich keinen X2 Omni hier habe (und auch keinen T20) muss ich mich mal mit folgenden Infos auseinandersetzen:
https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/issues/434

Das kann aber noch einen Augenblick dauern.

**Comment by Stormbringer11** [comment]
Kein Stress, danke das du es dir anschaust 😉 Die Stationsbefehle funktionieren glaub ich auch, muß ich nachher mal testen. Melde mich dann wieder.

Stimmt der Airbot ist ja grad im Schnäpperangebot bei Amazon, dann viel Spaß damit soweit 😉

**Comment by mrbungle64** [comment]
@Stormbringer11 

Noch mal zur Sicherheit:
Welcher Wert ist unter "info.deviceClass" eingetragen?

**Comment by Stormbringer11** [comment]
Da ist der Wert:

e6ofmn

drinnen.

**Comment by mrbungle64** [comment]
@Stormbringer11 

> Kein Wasser einstellen. Die Option gibt es bei mir gar nicht

Gibt es den Datenpunkt "control.waterLevel" nicht?
Oder meinst du was anderes?

**Comment by Stormbringer11** [comment]
Doch den gibt es aber der hat nur die Auswahl:

 "states": {
      "1": "low",
      "2": "medium",
      "3": "high",
      "4": "max"

Und der X2 kann ja die Mops hochfahren und nur saugen. Kann auch sein, dass der Fehler bei mir liegt. Bins vom Roborock Adapter halt gewohnt, dass da als Auswahl dann noch "0-Kein Wasser" gibt. Da hat er dann nur gesaugt, ohne Wischen.

**Comment by mrbungle64** [comment]
> Doch den gibt es aber der hat nur die Auswahl:
> 
> "states": { "1": "low", "2": "medium", "3": "high", "4": "max"

Funktioniert diese Auswahl soweit?

> 
> Und der X2 kann ja die Mops hochfahren und nur saugen. Kann auch sein, dass der Fehler bei mir liegt. Bins vom Roborock Adapter halt gewohnt, dass da als Auswahl dann noch "0-Kein Wasser" gibt. Da hat er dann nur gesaugt, ohne Wischen.

Ja, Mops hochfahren und nur saugen ist noch nicht implementiert

**Comment by Stormbringer11** [comment]
Die Auswahl funktioniert ;-)

**Comment by mrbungle64** [comment]
@Stormbringer11 

Hast du schon die Version 1.4.14 aus dem Beta/Latest Repo oder eine aktuelle Alpha von GitHub getestet?
Es ist in der Zwischenzeit ein bisschen was passiert 😉

**Comment by Stormbringer11** [comment]
Sorry und danke, dass du an mich gedacht hast aber ich hab den X2 zurück geschickt.... Der ist rumgeirrt ohne Ende. Kanns leider nicht mehr testen.

**Comment by mrbungle64** [comment]
@Stormbringer11 

> Sorry und danke, dass du an mich gedacht hast aber ich hab den X2 zurück geschickt.... Der ist rumgeirrt ohne Ende. Kanns leider nicht mehr testen.

Kein Problem. Ich schließe den Issue dann mal 😉
