### ISSUE TITLE
Deebot per Script starten

### ISSUE THREAD

**Issue by firechhe** [mrbungle64/ioBroker.ecovacs-deebot#61]
Hallo,
ich habe mir ein kleines Script gebastelt welches den Deebot losschickt sofern mein Handy nicht im WLAN ist. Die Anwesenheitserkennung funktioniert soweit auch ohne Probleme. Ich habe jedoch das Problem, dass der Roboter nicht gestartet wird. Ich nutze dazu folgenden Befehl:

![2020-04-28_18-07-05](https://user-images.githubusercontent.com/43295016/80510497-171d4b80-897b-11ea-84fa-8368486cb89f.jpg)

Es handelt sich ja hierbei um den "Clean" Button im Control Ordner. Ist die vorgehensweise so korrekt? Weshalb startet der Sauger nicht?

**Comment by mrbungle64** [comment]
Hallo @firechhe 

hast Du mal eine Debug Meldung eingebaut an der Stelle, ob der überhaupt dahin gelangt?
Ich benutze Blockly eher weniger, aber ich habe das mal kurz getestet - bei mir funktioniert es...

**Comment by firechhe** [comment]
Habe mal eine Debug Meldung eingebaut, die erscheint auch im Log. Kann keinen Fehler entdecken...

![01](https://user-images.githubusercontent.com/43295016/80517595-9ca5f900-8985-11ea-81be-0eed96d8042b.jpg)

![02](https://user-images.githubusercontent.com/43295016/80517607-a0398000-8985-11ea-84ad-021c72b58085.jpg)

**Comment by mrbungle64** [comment]
@firechhe 
Kannst Du bitte mal den State "control.clean" löschen und anschließend den Adapter neu starten?
Wenn es dann funktioniert wurde der State evtl. durch ein Skript verändert.

**Comment by firechhe** [comment]
Das hat geholfen! Vielen Dank. Da wäre ich nie drauf gekommen.
Ich hoffe, dass es nun zukünftig auch läuft und der State nicht wieder zerstört wird.
