### ISSUE TITLE
Reboot möglich?

### ISSUE THREAD

**Issue by capitaenz** [mrbungle64/ioBroker.ecovacs-deebot#62]
Hallo zusammen,

unser Deebot 710 hat so seine Eigenheiten:
Irgendwann spricht er nicht mehr und bleibt stumm
Neulich habe ich den Roboter dabei entdeckt wie er auf der Stelle steht und nicht mehr reinigt, dies macht er bis der Akku leer ist und fährt dann zum laden.

Die Probleme treten nach ein paar Wochen auf und sind nach einen Reboot wieder beseitigt.
Könnte man den Roboter vielleicht per Befehl zum Reboot bringen?

VG
Leif

**Comment by mrbungle64** [comment]
> Hallo zusammen,

Hallo @capitaenz 

> 
> unser Deebot 710 hat so seine Eigenheiten:
> Irgendwann spricht er nicht mehr und bleibt stumm

das ist bei meinem Ozmo 930 auch so - von daher habe ich schon mal geschaut, ob man den per API ein- und ausschalten kann. Bisher habe ich aber noch nichts gefunden.

> Neulich habe ich den Roboter dabei entdeckt wie er auf der Stelle steht und nicht mehr reinigt, dies macht er bis der Akku leer ist und fährt dann zum laden.
> 
> Die Probleme treten nach ein paar Wochen auf und sind nach einen Reboot wieder beseitigt.
> Könnte man den Roboter vielleicht per Befehl zum Reboot bringen?

Lt. aktuellem Stand: leider nein

> 
> VG
> Leif

**Comment by capitaenz** [comment]
Schade, aber danke für die schnelle Antwort!
Die Version 0.5.8 läuft übrigens gut mit node v12.16.2 und dem JS Controller 3.0.18

VG
Leif

**Comment by mrbungle64** [comment]
> Schade, aber danke für die schnelle Antwort!
> Die Version 0.5.8 läuft übrigens gut mit node v12.16.2 und dem JS Controller 3.0.18

Freut mich zu hören :+1: 

Der `SetOnOff` Befehl wird übrigens in einer der nächsten Adapter Version drin sein.
Darüber kann man dann die folgenden Sachen steuern bzw. abfragen:
- do not disturb
- continuous cleaning
- voice report

Evtl. hilft das letztere dann ja bei Deinem Modell. 

Das entspricht dem Punkt "Sprachfunktion" bzw. "Sprachmeldungen" (Benennung unterscheidet sich je nach Modell) in der App in den Einstellungen.
Du könntest es also auch jetzt schon testen ob das was hilft es aus- und wieder einzuschalten.
