### ISSUE TITLE
GotoPosition doesn't work in 1.4.14

### ISSUE THREAD

**Issue by smotomike** [mrbungle64/ioBroker.ecovacs-deebot#634]
### Is there an existing issue for this?

- [X] I have searched the existing issues and no issue is describing my issue

### The problem

Since the update from 1.4.13 to 1.4.14 the GotoPosition function no longer works. The vacuum cleaner does not respond when a coordinate is entered. After downgrading to 1.4.13 it works again.

Deebot N8 Pro

### With which model does the problem occur?

Deebot N8 series

### From which source you have installed the adapter?

GitHub

### Version of the ioBroker adapter

1.4.14

### Version of Node.js

Node.js: v18.19.0 NPM: 10.2.3

### Operating system

Linux

**Comment by mrbungle64** [comment]
@smotomike 

I just tried to reproduce your issue but the GoToPosition function still works with my Deebot T8 AIVI and Deebot X1 Turbo

**Comment by smotomike** [comment]
Apologies for the late reply. I will test the 1.14.14 again in the next few days and report back.

**Comment by smotomike** [comment]
After another update it no longer works. How can I help get to the bottom of the error?

**Comment by mrbungle64** [comment]
@smotomike 

> After another update it no longer works. How can I help get to the bottom of the error?

What's the value of the "info.deviceClass" state?

**Comment by smotomike** [comment]
> @smotomike
> 
> > After another update it no longer works. How can I help get to the bottom of the error?
> 
> What's the value of the "info.deviceClass" state?

ecovacs-deebot.0.info.deviceClass = snxbvc

**Comment by mrbungle64** [comment]
@smotomike 

> ecovacs-deebot.0.info.deviceClass = snxbvc

Do you have a "N8 Pro" or "T8 plus"?

**Comment by smotomike** [comment]
> @smotomike
> 
> > ecovacs-deebot.0.info.deviceClass = snxbvc
> 
> Do you have a "N8 Pro" or "T8 plus"?

Oh I am sorry. We have a T8 Pro. I incorrectly stated plus above.

**Comment by mrbungle64** [comment]
@smotomike 

Please try current Alpha version from GitHub

**Comment by smotomike** [comment]
> @smotomike
> 
> Please try current Alpha version from GitHub

Thank you, it works with the current alpha :-)
