### ISSUE TITLE
Reinigungskarte auslesen / -einbinden

### ISSUE THREAD

**Issue by TJJochen** [mrbungle64/ioBroker.ecovacs-deebot#64]
Besteht bei den Deebots irgendwie die Möglichkeit, dass man nach Beendigung der Reinigung die Karte außer in der HandyApp auch in einer Visualisierung einbinden kann?
Habe dank dieses tollen Adapters eine eigene VIS Seite für meinen Deebot 900 Ozmo erstellt. Als i-Tüpfelchen fehlt jetzt eigentlich nur noch eine Darstellung der letzten Reinigung.
Schöne Grüße Jochen

**Comment by mrbungle64** [comment]
Hallo @TJJochen 

freut mich, dass Dir der Adpater gefällt. Danke für das Feedback :+1: 

> Besteht bei den Deebots irgendwie die Möglichkeit, dass man nach Beendigung der Reinigung die Karte außer in der HandyApp auch in einer Visualisierung einbinden kann?
> Habe dank dieses tollen Adapters eine eigene VIS Seite für meinen Deebot 900 Ozmo erstellt. Als i-Tüpfelchen fehlt jetzt eigentlich nur noch eine Darstellung der letzten Reinigung.

Ja das wird demnächst kommen, dass man die Karten der abgeschlossenen Reinigungen auslesen kann. In der zugrundeliegenden Library haben wir das bereits implementiert.

> Schöne Grüße Jochen

**Comment by mrbungle64** [comment]
Hallo @TJJochen 

ich habe das nun soweit implementiert und in der aktuellsten GitHub Version u.a. für den Ozmo 900 freigegeben. Unter "cleaninglog" findest Du nun u.a. "lastCleaningMapImageURL".

Freue mich auf Feedback, ob es mit dem Ozmo 900 funktioniert.

**Comment by TJJochen** [comment]
Hallo @mrbungle64 

habe jetzt einige Datenpunkte mehr (z.B. die komplett gereinigten m2 und Reinigungszeit, etc...) 
Habe gerade Testweise einen kleinen Bereich reinigen lassen. 
Leider wird aber keine Karte erstellt :-(

Schöne Grüße
Jochen

![Staubi](https://user-images.githubusercontent.com/35068587/81101787-eb680b80-8f0e-11ea-9283-ce2b50d495d2.JPG)

**Comment by mrbungle64** [comment]
> Hallo @mrbungle64
> 
> habe jetzt einige Datenpunkte mehr (z.B. die komplett gereinigten m2 und Reinigungszeit, etc...)
> Habe gerade Testweise einen kleinen Bereich reinigen lassen.
> Leider wird aber keine Karte erstellt :-(

Sind in "last20Logs" jeweils bei "imageUrl" URL's eingetragen oder sind die Einträge leer?

**Comment by TJJochen** [comment]
Hab unter "last20Logs" folgenden `Eintrag:
`[{"timestamp":1588702635,"date":"2020-05-05T18:17:15.000Z","lastTime":243,"totalTimeString":"0h 04m 03s","squareMeters":4,"stopReason":"clean_successful","trigger":"app"},{"timestamp":1587746621,"date":"2020-04-24T16:43:41.000Z","lastTime":228,"totalTimeString":"0h 03m 48s","squareMeters":4,"stopReason":"clean_successful","trigger":"app"},{"timestamp":1587663730,"date":"2020-04-23T17:42:10.000Z","lastTime":281,"totalTimeString":"0h 04m 41s","squareMeters":4,"stopReason":"clean_successful","trigger":"app"}]`
[{"timestamp":1588702635,"date":"2020-05-05T18:17:15.000Z","lastTime":243,"totalTimeString":"0h 04m 03s","squareMeters":4,"stopReason":"clean_successful","trigger":"app"},{"timestamp":1587746621,"date":"2020-04-24T16:43:41.000Z","lastTime":228,"totalTimeString":"0h 03m 48s","squareMeters":4,"stopReason":"clean_successful","trigger":"app"},{"timestamp":1587663730,"date":"2020-04-23T17:42:10.000Z","lastTime":281,"totalTimeString":"0h 04m 41s","squareMeters":4,"stopReason":"clean_successful","trigger":"app"}]

**Comment by mrbungle64** [comment]
@TJJochen 
Da wurde für diesen Fall noch die "falsche" API benutzt.
Ich habe gerade noch mal ein Update gemacht - probier bitte noch mal.

**Comment by TJJochen** [comment]
@mrbungle64 

Perfekt 👍 Funktioniert jetzt so wie es soll! Sehr geile Arbeit :-)
Kann man anstelle der *.jpg Datei auch eine *.png mit transparentem Hintergrund erstellen lassen? Dann würde die sich optisch besser in der VIS einbinden lassen...

![Reinigungskarte Staubi](https://user-images.githubusercontent.com/35068587/81104251-87474680-8f12-11ea-9410-28c36646e561.JPG)

Fat Thx, Jochen

**Comment by Maik078** [comment]
Hallo,
ich bin seit kurzem auch stolzer Besitzer eines Ozmo950 und bin hier auf den Adapter gestoßen,
der mich echt begeistert. Bisher funktioniert alles reibungslos (habe allerdings auch noch nicht alles ausprobiert). Nur leider fehlen bei mir die "last20logs" und "LastCleaningMap.." Einträge.
Alle anderen werden aktualisiert. Woran könnte das liegen?
Schöne Grüße Maik

**Comment by mrbungle64** [comment]
> Hallo,
> ich bin seit kurzem auch stolzer Besitzer eines Ozmo950 und bin hier auf den Adapter gestoßen,
> der mich echt begeistert. Bisher funktioniert alles reibungslos (habe allerdings auch noch nicht alles ausprobiert). Nur leider fehlen bei mir die "last20logs" und "LastCleaningMap.." Einträge.
> Alle anderen werden aktualisiert. Woran könnte das liegen?
> Schöne Grüße Maik

Hallo @Maik078 

freut mich, dass Dir der Adapter gefällt :+1: 

Hast Du bereits das Reinigungsprotokoll in den Einstellungen freigeschaltet?
Das ist im Tab "Features": "Zeige sämtliche Werte vom Reinigungsprotokoll"

**Comment by Maik078** [comment]
ja..ist freigeschaltet..bzw. ich hab alle akiviert.

**Comment by Maik078** [comment]
habe noch eine Warnmeldung in der Logdatei gefunden nach Adapterneustart:
ecovacs-deebot.0 | 2020-05-09 09:34:43.450 | warn | (25122) no connection to objects DB

**Comment by mrbungle64** [comment]
> habe noch eine Warnmeldung in der Logdatei gefunden nach Adapterneustart:
> ecovacs-deebot.0 | 2020-05-09 09:34:43.450 | warn | (25122) no connection to objects DB

Die ist ungefährlich

**Comment by mrbungle64** [comment]
Welche Version hast Du installiert?

**Comment by Maik078** [comment]
gestern erstmals die 0.5.9 und heute nochmal mit der 0.6.0 getestet

**Comment by Maik078** [comment]
es fehlen nur die Werte

**Comment by Maik078** [comment]
ich bin noch recht neu hier und vielleicht ist es jetzt auch nur ein dummer Hinweis:
Der Datenpunkt "last20Logs" ist in den Einstellungen unter Art als "Objects" angelegt und der Datenpunkt "lastCleaningMap.." die Art "Zeichenkette" Müsste das nicht anders herum sein?
Wurden die Datenpunkte vielleicht bei mir falsch angelegt?

**Comment by mrbungle64** [comment]
> ich bin noch recht neu hier und vielleicht ist es jetzt auch nur ein dummer Hinweis:
> Der Datenpunkt "last20Logs" ist in den Einstellungen unter Art als "Objects" angelegt und der Datenpunkt "lastCleaningMap.." die Art "Zeichenkette" Müsste das nicht anders herum sein?
> Wurden die Datenpunkte vielleicht bei mir falsch angelegt?

Das ist bei mir genauso und sollte so auch funktionieren.
Aber Du kannst gerne mal probieren die Datenpunkte zu löschen - nach einem Adapter Neustart werden die wieder autom. neu angelegt. Vielleicht hilft das ja.

**Comment by mrbungle64** [comment]
@boriswerner 
Funktionieren diese Datenpunkte bei Dir noch mit der 0.6.0?

**Comment by Maik078** [comment]
Jetzt ist mir aufgefallen, dass bei mir in der Ecovacs App gar nicht alle Reinigungsprotokolle vorhanden sind. Seit gestern nachmttg. wurde keins mehr gespeichert. Auch vorher gibt es große Lücken. Den Adapter habe ich erst gestern abd. installiert. Wahrscheinlich ist deswegen nichts im iobroker angekommen.

**Comment by mrbungle64** [comment]
> Jetzt ist mir aufgefallen, dass bei mir in der Ecovacs App gar nicht alle Reinigungsprotokolle vorhanden sind. Seit gestern nachmttg. wurde keins mehr gespeichert. Auch vorher gibt es große Lücken. Den Adapter habe ich erst gestern abd. installiert. Wahrscheinlich ist deswegen nichts im iobroker angekommen.

Ja da gibt es ja leider immer mal wieder Probleme:
https://www.roboter-forum.com/index.php?thread/40009-reinigungsprotokoll-wird-nicht-gespeichert/

Der Adapter bezieht die Daten halt auch über die gleiche API wie die Mobile App.
Wenn dort Einträge fehlen oder das Log leer ist dann ist das mit hoher Wahrscheinlichkeit leider auch im Adapter so ...

Wenn das Protokoll aber in der App "nur" lückenhaft ist sollten die Datenpunkte aber zumindest nicht leer sein.

**Comment by boriswerner** [comment]
Ich hab heute morgen die Version aus dem latest neu installiert und vorhin eine Reinigung gemacht. Gerade war dann der Datenpunkt auch leer.
Ich hab die Instanz jetzt nochmal neu gestartet und nach ca. einer Minute ist nun alles da.
@Maik078 magst du bitte auch einmal wie von @mrbungle64 vorgeschlagen den kompletten Ordner "cleaninglog" bei den Objekten löschen und dann die Instanz neustarten? Dann ein bis zwei Minuten warten und die Objekte einmal aktualisieren (refresh-Button oben links in der Objektliste)?
Sind denn in der App in der Protokoll-Ansicht trotzdem 20 Protokolle zu sehen, nur es fehlen einige, die du erwarten würdest?

Ich hab aber nochmal geschaut. Es gibt zwei Aufrufe.
GetCleanLogs gibt die letzten 20 Protokolle, so wie sie auch in der App zu finden sind.
GetLastCleanLog gibt (mittlerweile zumindest, das war vor eingier Zeit definitiv auch noch nicht so) die Infos, die in der Hauptansicht zu sehen sind.
Das Protokoll zeigt bei mir eine unvollständige Karte, die auch derzeit an den iobroker gesendet wird. GetLastCleanLog zeigt die vollständige Sicht, wird aber derzeit nicht an iobroker übertragen... Achja... die Funktion scheint denen echt große Probleme zu bereiten.
Ich hab mal einen issue in der library dafür aufgemacht, dass ich die "last"-Informationen auf GetLastCleanLog umstelle.

**Comment by Maik078** [comment]
Ordner gelöscht. Restart Adapter gemacht und Refresh Objekte.
Leider kein Erfolg. Datenpunkte immer noch leer. 
Der Datenpunkt "ecovacs-deebot.0.cleaninglog.lastCleaningTimestamp" ist übrigends auch leer. Das hatte ich noch nicht erwähnt.
In der App habe ich insgesamt 20 Protokolle mit ein paar zeitlichen Lücken.

**Comment by boriswerner** [comment]
@Maik078 ich bin gerade noch etwas ratlos. Ich hab gerade auf meinem Windows-Rechner nochmal komplett deinstalliert und neu aus dem latest installiert und bekomme die Werte genauso wie auf dem RaspberryPi angezeigt (es dauert ein bisschen länger als bei den anderen States, aber sie werden nach spätestens einer Minute angezeigt. Auf was für einem System ist denn dein iobroker installiert? Dann würde ich dich bitten die library selbst mal auszuführen und das Log zu posten (@mrbungle64 du hast da doch immer so eine schöne Anleitung mit grep parat, falls es Linux ist?)

**Comment by mrbungle64** [comment]
> @Maik078 ich bin gerade noch etwas ratlos. Ich hab gerade auf meinem Windows-Rechner nochmal komplett deinstalliert und neu aus dem latest installiert und bekomme die Werte genauso wie auf dem RaspberryPi angezeigt (es dauert ein bisschen länger als bei den anderen States, aber sie werden nach spätestens einer Minute angezeigt. Auf was für einem System ist denn dein iobroker installiert? Dann würde ich dich bitten die library selbst mal auszuführen und das Log zu posten (@mrbungle64 du hast da doch immer so eine schöne Anleitung mit grep parat, falls es Linux ist?)

1)
```bash
git clone https://github.com/mrbungle64/ecovacs-deebot.js.git
cd ecovacs-deebot.js
npm install
cd example
```

2) Email und Passwort in der Datei `app2.js` anpassen

3) Die app ausführen 
```bash
NODE_ENV=dev node app2.js | grep -E 'cleanLog|Logs'
```

4) ca. 1 Minute laufen lassen und anschließend die Ausgabe posten

**Comment by Maik078** [comment]
System ist ein RaspberryPi mit Raspbian light Stretch

**Comment by Maik078** [comment]
**@mrbungle64** danke..probier ich heute abd mal aus. muss erstmal weg.

**Comment by Michalos86** [comment]
> > Kann man anstelle der *.jpg Datei auch eine *.png mit transparentem Hintergrund erstellen lassen? Dann würde die sich optisch besser in der VIS einbinden lassen...
> 
> Nehme alles zurück. Wird direkt transparent eingefügt....
> 
> ![Staubi VIS](https://user-images.githubusercontent.com/35068587/81105677-94653500-8f14-11ea-9a9c-188f7b67d89f.JPG)

Hallo wie hast du die Karte in die Vis eingebunden?

**Comment by Dragon0501** [comment]
Html widget und als Quelle den Datenpunkte angeben.

**Comment by TJJochen** [comment]
Genau wie Dragon0501 es beschrieben hat.
html Widget und dann den Datenpunkt der Karte im Ecovacs Adapter angeben.

![image](https://user-images.githubusercontent.com/35068587/106710993-22cb2c00-65f7-11eb-8b6c-3fbf6dcc0b93.png)

**Comment by Michalos86** [comment]
Hallo,
sorry bin am verzweifeln. Ich kann bei html weitget nur htmls auswählen und keinen datenpunkt...
Vielen Dank für die Hilfe

Von meinem iPhone gesendet

**Comment by Dragon0501** [comment]
Du hast Recht... Es heißt String IMG src

**Comment by TJJochen** [comment]
> Hallo, sorry bin am verzweifeln. Ich kann bei html weitget nur htmls auswählen und keinen datenpunkt... Vielen Dank für die Hilfe Von meinem iPhone gesendet
> […](#)
> Am 03.02.2021 um 07:58 schrieb Dragon0501 ***@***.***>: ﻿ Html widget und als Quelle den Datenpunkte angeben. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

Hallo Michalos86,

sorry, ich lag da auch falsch, obwohl ich dir auch noch heute morgen einen Screenshot des Widget geschickt hatte.
Ja es ist auch bei mir das String IMG src Widget.  Aber viel Freude wirst du vermutlich eh nicht mit der Karte haben, da diese nur sporadisch mal nach einem Reinigungszyklus in der VIS als Aktualisiert dargestellt wird. 

Schöne Grüße
Jochen

**Comment by mrbungle64** [comment]
@TJJochen 

> Aber viel Freude wirst du vermutlich eh nicht mit der Karte haben, da diese nur sporadisch mal nach einem Reinigungszyklus ...

Richtig, weil das die Karte der zuletzt durchgeführten Reinigung ist ("Image URL of the last cleaning").
Das ist genau die Karte die man auch in der Mobile App unter Reinigungsprotokoll jeweils angezeigt bekommt.

Das ist keine Live Map (falls das jemand erwartet hat).

Btw.: Unter "cleaninglog.last20Logs" sind die Karten der letzten 20 Reinigungsvorgänge enthalten.

**Comment by TJJochen** [comment]
@mrbungle64 
> Richtig, weil das die Karte der zuletzt durchgeführten Reinigung ist ("Image URL of the last cleaning").
> Das ist genau die Karte die man auch in der Mobile App unter Reinigungsprotokoll jeweils angezeigt bekommt.

Hallo Sascha,
das sollte kein Angriff auf deine tolle Arbeit rund um diesen Adapter sein ;-)
Ich glaube, ich hatte mit dir diesbezüglich bereits Kontakt, aber es ist halt immer noch so, dass die Karte nur ab und an nach einem Reinigungszyklus bei mir dargestellt wird. Warum auch immer. In der Mobil-App wird sie nach Beendigung des Reinigungsprogramms dargestellt. Es hängt vermutlich mit der Verbindung des Adapters zur Cloud von Ecovacs zusammen.
Mein ioBroker Log ist ja auch voll mit "Error message received: Request Timeout" Fehlermeldungen, obwohl der Adapter grün ist.

Schöne Grüße

Jochen

**Comment by mrbungle64** [comment]
@TJJochen 

Hallo Jochen,

Danke, dass Du es noch mal erklärt hast und Danke für das positive Feedback 👍🏻 

Ja, die Timeouts und die Instabilität der Verbindung zu den Ecovacs Serven sind echt ein Problem.

Aber Du hast mich gerade indirekt auf eine Idee gebracht 😉 
Vielleicht kann ich damit die Auswirkungen ein bisschen mehr einschränken.
