### ISSUE TITLE
Map Anzeige in Iobroker

### ISSUE THREAD

**Issue by helfi9999** [mrbungle64/ioBroker.ecovacs-deebot#66]
Hallo,
erstmal ein ganz grosses Lob an Euch wie weit der Adapter ist.
Meine Frage ist es irgendwie möglich die Karte etwas dunkler zu bekommen da man nicht sieht wo der Sauger gesaugt hat.

Hoffe auf baldige Antwort
helfi9999

**Comment by mrbungle64** [comment]
> Hallo,
> erstmal ein ganz grosses Lob an Euch wie weit der Adapter ist.

Hallo @helfi9999 

vielen Dank! :+1: 

> Meine Frage ist es irgendwie möglich die Karte etwas dunkler zu bekommen da man nicht sieht wo der Sauger gesaugt hat.

Über die URL unter "cleaninglog.lastCleaningMapImageURL" ist die gleiche Karte wie im Reinigungsprotokoll der Mobile App abrufbar.

Wird die Strecke bei DIr nicht in Weiß dargestellt?
Ich finde das auch nicht so optimal, aber es sollte eigentlich zu sehen sein.

Es ist bisher nicht geplant, dass wir die noch mal verändern. Meiner Meinung nach macht das auch keinen Sinn, da man das schlecht automatisieren lässt, so dass jeder dann damit auch zufrieden ist.
Sorry, wenn ich Dich da enttäuschen muss.

> 
> Hoffe auf baldige Antwort
> helfi9999

**Comment by boriswerner** [comment]
Hi, ich denke, dass eine Anpassung der Log-Karten auch nicht sinnvoll ist.
Wo wir das auf die Liste nehmen können ist bei der Live-Map. Da muss die Karte ja erst aus den Metadaten gerendert werden. Da kann man Einstellungen für die Farben anbieten (stelle ich mir so ähnlich wie im mihome vacuum vor: https://github.com/iobroker-community-adapters/ioBroker.mihome-vacuum/blob/master/README.md#map-config)
Ich hab es in der library in den Task mit aufgenommen: https://github.com/mrbungle64/ecovacs-deebot.js/issues/10
Sollen wir es hier trotzdem offen lassen?

**Comment by mrbungle64** [comment]
> Hi, ich denke, dass eine Anpassung der Log-Karten auch nicht sinnvoll ist.
> Wo wir das auf die Liste nehmen können ist bei der Live-Map. Da muss die Karte ja erst aus den Metadaten gerendert werden. Da kann man Einstellungen für die Farben anbieten (stelle ich mir so ähnlich wie im mihome vacuum vor: https://github.com/iobroker-community-adapters/ioBroker.mihome-vacuum/blob/master/README.md#map-config)

Ja genau - daran hatte ich auch schon gedacht

> Ich hab es in der library in den Task mit aufgenommen: [mrbungle64/ecovacs-deebot.js#10](https://github.com/mrbungle64/ecovacs-deebot.js/issues/10)

Danke  :+1: 

> Sollen wir es hier trotzdem offen lassen?

Ich würde sagen, dass wir diesen Issue hier schließen sollten.

**Comment by helfi9999** [comment]
Hi,
das ihr eine Live Map macht ist super. Schliesse den Issue.

**Comment by uwe72** [comment]
> Über die URL unter "cleaninglog.lastCleaningMapImageURL" ist die gleiche Karte wie im Reinigungsprotokoll der Mobile App abrufbar.

Ich hätte auch gerne die Map, aber der genannte Datenpunkt ist bei mir leer. Was mache ich falsch?

Hätte auch gerne die Map aus der nativen App:
![image](https://user-images.githubusercontent.com/61848539/177593155-b4828119-c3d4-43e5-878d-6b7dba4d1cea.png)

**Comment by mrbungle64** [comment]
@uwe72 

> Ich hätte auch gerne die Map, aber der genannte Datenpunkt ist bei mir leer.

Ist das ein T9? Dann geht es aktuell leider nicht (siehe auch unter [Known Issues](https://github.com/mrbungle64/ioBroker.ecovacs-deebot#known-issues))

**Comment by uwe72** [comment]
Ja, ist ein T9. Weiß man, ob da Chancen bestehen, ob dies irgendwann mal funktionieren wird?

Bekam war eingebunden in Jarvis, aber bringt nicht wirklich einen Mehrwert:
![image](https://user-images.githubusercontent.com/61848539/177616805-378369fe-e1e3-4d21-a16f-887f2ebd4491.png)

Ich zeige die Map als "Base64-encoded data" Bild an, direkt aus dem Datenpunkt
ecovacs-deebot.0.map.2094596209.map64

**Comment by mrbungle64** [comment]
> Ja, ist ein T9. Weiß man, ob da Chancen bestehen, ob dies irgendwann mal funktionieren wird?

Ja, das werde ich mich früher oder später noch mal mit befassen.
Es wird bereits in [diesem Issue](https://github.com/mrbungle64/ioBroker.ecovacs-deebot/issues/270#issuecomment-1118304859) behandelt (du könntest deinen neuen Issue eigentlich wieder löschen)

> 
> Bekam was eingebunden in Jarvis, aber bringt nicht wirklich einen Mehrwert

Was heißt "aber bringt nicht wirklich einen Mehrwert"? Es ist halt eine andere Funktion 😉

**Comment by uwe72** [comment]
> Was heißt "aber bringt nicht wirklich einen Mehrwert"? Es ist halt eine andere Funktion 😉
Wir können mein Ticket gerne wieder löschen.

Kannst Du mir bitte noch den Unterschied erklären zwischen den 2 Datenpunkten:
- cleaninglog.lastCleaningMapImageURL
- ecovacs-deebot.0.map.2094596209.map64

**Comment by mrbungle64** [comment]
@uwe72 

> Kannst Du mir bitte noch den Unterschied erklären zwischen den 2 Datenpunkten:

Ja klar

> 
> * cleaninglog.lastCleaningMapImageURL

Dies ist die URL zur letzten bei Abschluss der Reinigung erstellten Map.
Diese ist identisch mit der aus der Mobile App und liegt auch bei Ecovacs in der Cloud.

Im Datenpunkt "cleaninglog.last20Logs" sind dann auch die anderen URLs zu den letzten 20 Reinigungen. Dies funktioniert aber ja leider nicht, weil die ab dem T9 irgendwas an der API geändert haben.

> * ecovacs-deebot.0.map.2094596209.map64

Dies ist das jeweils manuell zu erstellende Map Image (kann also jederzeit erstellt werden).

**Comment by uwe72** [comment]
Sorry wenn ich nochmals nachhake.
OK, den Anfang habe ich verstanden, d.h. das Thema rund um den ersten Datenpunkt.

Aber zum 2. Datenpunkt. Ja ich erstelle die Karte manuell. Denke ist auch erstellt worden weil ich 
ecovacs-deebot.0.map.2094596209.loadMapImage
auf true gesetzt habe.

Aber was sagt mir die Map aus? Das hellblaue sind alle Stellen wo jemals gereinigt wurden? Oder es ist einfach nur eine Umrisskarte der Etage?

**Comment by mrbungle64** [comment]
@uwe72 

> Aber was sagt mir die Map aus? Das hellblaue sind alle Stellen wo jemals gereinigt wurden? Oder es ist einfach nur eine Umrisskarte der Etage?

Ja, das ist nur eine Umrisskarte der Etage - allerdings mit der Position der Ladestation und er Position des Saugroboters (wenn nicht auf der Ladestation).
