### ISSUE TITLE
Piepen im Minutenrhythmus

### ISSUE THREAD

**Issue by Dragon0501** [mrbungle64/ioBroker.ecovacs-deebot#67]
Ein riesen Kompliment für diesen tollen Adapter. Wenn der Roboter läuft piept er Minutenrhythmus und "startet" das Programm neu. Ich denke, dass im Rahmen des Abfrageintervalls auch die aktuellen Stati nicht nur aus der Cloud abgerufen werden, sondern auch "automatische Reinigung" an die Cloud übertragen wird. Darum piept er jede Minute wie bei einem Druck auf die Fernbedienung. lässt sich das irgendwie abschalten? Es ist mir vorher nie aufgefallen, da der Sauger eigentlich nur läuft wenn ich nicht daheim bin. Musste aber nun leider feststellen, dass er während der gesamten Betriebsdauer im Minutentakt piept. (Mich störts ja nicht wenn ich nicht da bin, aber meine Nachbarin findets nervig)

Deebot N79
0.6.0
Raspberry Pi

**Comment by mrbungle64** [comment]
Hi @Dragon0501 

da müssen wir natürlich schnell herausfinden was das Piepsen verursacht.

Kannst Du mal bitte unter "weiteres ..." in den Adpatereinstellungen das "Abfrage Intervall" von 60 Sek. auf 15 Sek. heruntersetzen und schauen ob es dann alle 15 Sek. piepst? Aber natürlich nur, wenn Deine Nachbarin nicht zuhause ist ;)

**Comment by Dragon0501** [comment]
Genau das passiert. Wenn ich das Intervall reduziere piept er im Rhythmus des neuen Abfrageintervalls.

**Comment by mrbungle64** [comment]
> Genau das passiert. Wenn ich das Intervall reduziere piept er im Rhythmus des neuen Abfrageintervalls.

ok, dann ist es wohl eine akustische Rückmeldung auf einen dieser Befehle:

* `GetError`
* `GetSleepStatus`
* `GetCleanSum`
* `GetCleanSpeed`

Kannst Du bei Gelegenheit mal folgendes auf dem Raspberry Pi durchführen?

1)
```bash
git clone https://github.com/mrbungle64/ecovacs-deebot.js.git
cd ecovacs-deebot.js
npm install
cd example
```

2) Email und Passwort in der Datei `app2.js` anpassen

3) Die Zeilen 83-87 durch folgendes ersetzen:

```javascript
        vacbot.run('GetError');
        //vacbot.run('GetSleepStatus');
        //vacbot.run('GetCleanSum');
        //vacbot.run('GetCleanSpeed');
```

4) Die app ausführen und festhalten, ob es piepst
```bash
node app2.js
```

5) Das noch 3x wiederholen und jeweils die Slashes bei einem anderen Befehl weg nehmen (den Befehl einkommentieren) und in der Zeile davor dafür einfügen

Beim 2. Mal sieht es dann z.B. so aus

```javascript
        //vacbot.run('GetError');
        vacbot.run('GetSleepStatus');
        //vacbot.run('GetCleanSum');
        //vacbot.run('GetCleanSpeed');
```

**Comment by Dragon0501** [comment]
Was steht denn in Zeile 83-87 nur um sie zu identifizieren

**Comment by mrbungle64** [comment]
> Was steht denn in Zeile 83-87 nur um sie zu identifizieren

Sorry, ich wollte es eigentlich dazupacken ;)

```javascript
            vacbot.run('Clean');
            vacbot.run('GetLifeSpan', 'main_brush');
            vacbot.run('GetLifeSpan', 'side_brush');
            vacbot.run('GetLifeSpan', 'filter');
            vacbot.run('GetNetInfo');
```

**Comment by Dragon0501** [comment]
GetCleanSum ist das Problem, dieses verursacht das Piepen

**Comment by Dragon0501** [comment]
Es ist aber unmöglich die Reinigungsart mit der Fernbedienung zu ändern, wenn es über den Broker gestartet wurde. Dann piept er so lang bis er mit dem durchschalten der Modi wieder beim ursprünglichen ist und macht in dem Modus weiter, welcher mit dem Broker gestartet wurde.

**Comment by mrbungle64** [comment]
> GetCleanSum ist das Problem, dieses verursacht das Piepen

ok, gut dass wir das nun wissen ;)

Ich werde das dann mit der nächsten Version mal in die Adapter Einstellungen aufnehmen und für den N79 ausschalten als Standard-Einstellung.

**Comment by Dragon0501** [comment]
das ist toll! vielen dank! muss iwas wieder runterschmeißen oder kann alles so bleiben?

**Comment by mrbungle64** [comment]
> das ist toll! vielen dank! muss iwas wieder runterschmeißen oder kann alles so bleiben?

Du musst gerade nichts runterschmeißen - kann so bleiben ;)

**Comment by Dragon0501** [comment]
vielen lieben dank!

**Comment by mrbungle64** [comment]
@Dragon0501 

Wenn Du möchtest kannst Du schon mal die aktuelle Version von GitHub testen.
Das Piepsen sollte nun weg sein (wenn es wirklich alleine durch `GetCleanSum` verursacht wurde).

Bitte vor der nächsten Reinigung prüfen, ob in den Adaptereinstellungen unter "Features" der Punkt "Zeige sämtliche Werte vom Reinigungsprotokoll" auf "Vorauswahl verwenden"  oder "deaktivieren" steht.

**Comment by Dragon0501** [comment]
Sehr gut! Funktioniert! Vielen Dank für die schnelle Unterstützung!

**Comment by Andyexe** [comment]
Bei mir ist das Piepen auch ich habe das ( Zeige sämtliche Werte vom Reinigungsprotokoll ) aktivieren.
ich wollte eigentlich ein schönen Log anlegen damit ich sehen kann wann der Robi was gemacht hat.
Leider sind die Cleaning logs bei mir leer? kann man da noch was machen das Piepen ist ziemlich nervig :-D

**Comment by mrbungle64** [comment]
> Leider sind die Cleaning logs bei mir leer? kann man da noch was machen das Piepen ist ziemlich nervig :-D

Ja, wie oben angemerkt: "Zeige sämtliche Werte vom Reinigungsprotokoll" deaktivieren.

**Comment by mrbungle64** [comment]
> Leider sind die Cleaning logs bei mir leer?

Evtl. heißt der Befehl beim N79 `GetLogs` und nicht `GetCleanLogs`.
Werde das in einer der nächsten Versionen mal so einbauen für den N79.

**Comment by mrbungle64** [comment]
In der aktuellen [GitHub Version](https://github.com/mrbungle64/ioBroker.ecovacs-deebot.git) (trägt aktuell immer noch die Version 1.0.3)
habe ich den Befehl `GetCleanSum` nun für die N79 Modelle verhindert.
Es sollte also nicht mehr piepen - egal ob "Zeige sämtliche Werte vom Reinigungsprotokoll" aktiviert ist oder nicht.
`GetCleanSum` scheint einfach nicht vorgesehen zu sein für den N79...

> Evtl. heißt der Befehl beim N79 GetLogs und nicht GetCleanLogs.

Das habe ich nun mal eingebaut für die N79 Modelle.

Also bitte testet mal, ob es bei aktiviertem "Zeige sämtliche Werte vom Reinigungsprotokoll"
* nun nicht mehr piept
* und "cleaninglog.last20Logs" nun befüllt wird

**Comment by mrbungle64** [comment]
> In der aktuellen [GitHub Version](https://github.com/mrbungle64/ioBroker.ecovacs-deebot.git) (trägt aktuell immer noch die Version 1.0.3)
> habe ich den Befehl `GetCleanSum` nun für die N79 Modelle verhindert.
> Es sollte also nicht mehr piepen - egal ob "Zeige sämtliche Werte vom Reinigungsprotokoll" aktiviert ist oder nicht.
> `GetCleanSum` scheint einfach nicht vorgesehen zu sein für den N79...
> 
> > Evtl. heißt der Befehl beim N79 GetLogs und nicht GetCleanLogs.
> 
> Das habe ich nun mal eingebaut für die N79 Modelle.
> 
> Also bitte testet mal, ob es bei aktiviertem "Zeige sämtliche Werte vom Reinigungsprotokoll"
> 
> * nun nicht mehr piept
> * und "cleaninglog.last20Logs" nun befüllt wird

@Andyexe  @Dragon0501 

Es wäre gut, wenn Ihr das mal testen würdet, ob "cleaninglog.last20Logs" nun Werte enthält und das Piepsen nun weg ist.

**Comment by Dragon0501** [comment]
Werde ich morgen Vormittag sofort tun!

**Comment by Dragon0501** [comment]
![Screenshot 2020-07-24 at 10 19 26](https://user-images.githubusercontent.com/59663011/88373628-759a7000-cd98-11ea-9867-6f93c853dbcf.png)
![Screenshot 2020-07-24 at 10 20 42](https://user-images.githubusercontent.com/59663011/88373636-792df700-cd98-11ea-85f8-babde3abf53b.png)

Kein piepen mehr und funktionieren tut es auch! Vielen Dank!

**Comment by mrbungle64** [comment]
@Dragon0501 

Danke für die Rückmeldung :+1: 

Aber sind das die richtigen Screenshots?
Ich sehe "cleaninglog.last20Logs" darauf gar nicht ...

**Comment by Andyexe** [comment]
Hallo,
sorry hatte keine zeit.

Warum auch immer aber mein Robi hat sich nicht mehr ins W-LAN eingewählt??? musste ihn erst wieder mit der APP neu anmelden.
Bis jetzt ist alles Leer im Log nur der Standard mit der Zeit ist voll.
![grafik](https://user-images.githubusercontent.com/68147299/88449607-7e4a7f00-ce48-11ea-9df9-4fdfdb3f33ba.png)

ich habe leider immer noch 404 im ioBroker? 
Komischerweise kann ich den Robi über der VIS steuern?
Sobald ich zeit habe schaue ich mal genauer nach was das ist.

**Comment by mrbungle64** [comment]
> Hallo,
> sorry hatte keine zeit.
> 
> Warum auch immer aber mein Robi hat sich nicht mehr ins W-LAN eingewählt??? musste ihn erst wieder mit der APP neu anmelden.
> Bis jetzt ist alles Leer im Log nur der Standard mit der Zeit ist voll.
> 
> ich habe leider immer noch 404 im ioBroker?
> Komischerweise kann ich den Robi über der VIS steuern?
> Sobald ich zeit habe schaue ich mal genauer nach was das ist.

Ja, ich würde mal sagen, dass Du erst mal schauen solltest, dass der Saugroboter in deinem Netzwerk stabil funktioniert. Sonst sprechen wir hier ggf. über Fehler (vom Adapater) die gar keine sind.

Sollten anschließend noch Probleme mit dem Adapter bestehen würde ich Dich bitten jeweils einen neuen Issue pro Problem zu erstellen.

Den Issue "Piepen im Minutenrhythmus" sehe ich jetzt mal als endgültig gelöst an.
