### ISSUE TITLE
Adapter in restart loop

### ISSUE THREAD

**Issue by ponG86** [mrbungle64/ioBroker.ecovacs-deebot#678]
### Is there an existing issue for this?

- [X] I have searched the existing issues and no issue is describing my issue

### The problem

Since a few days, iobroker notifies me that the deebot adapter is not startet, as a restart loop was detected. The loop is always caused by the same sequence of errors in the logfile.
The error occurs in the context of "getWaterInfo". Behavior is not impacted by using or not using the waterbox.

I attached a logfile. Sorry for the format, git won't let me attach the html provided by iobroker frontend.
[log.txt](https://github.com/mrbungle64/ioBroker.ecovacs-deebot/files/15140830/log.txt)

Thanks for the adapter and your effort!

### With which model does the problem occur?

Deebot N8 series

### From which source you have installed the adapter?

Stable (default)

### Version of the ioBroker adapter ("info.version")

1.4.15

### Version of the ecovacs-deebot.js library ("info.library.version")

0.9.6-beta.3

### Version of the JS controller

4.0.24

### Version of Node.js

18.20.2

### Operating system

Linux

### Anything in the logs that might be useful?

```txt
Look for waterboxinfo
```

### Which "other" models are you using?

none

### Ecovacs device class ("info.deviceClass")

7zya6u

### Communication protocol ("info.library.communicationProtocol")

MQTT

### Is the canvas module installed? ("info.library.canvasModuleIsInstalled")

yes (true)

**Comment by mrbungle64** [comment]
@ponG86 

The problem is caused by running with JS Controller version 4.0.x
See also https://github.com/mrbungle64/ioBroker.ecovacs-deebot/issues/671
