### ISSUE TITLE
Saugroboter startet um Mitternacht

### ISSUE THREAD

**Issue by Dragon0501** [mrbungle64/ioBroker.ecovacs-deebot#68]
Der Saugroboter startet jede Nacht um Mitternacht mit der Reinigung. Ein etwas unschöner Effekt, der seit Version 0.5.9 auftritt. 

N79
mittlerweile 0.6.1
Raspberry Pi

**Comment by mrbungle64** [comment]
@Dragon0501 
Dann überprüfe doch bitte mal, ob das entweder in der Mobile App so eingestellt ist oder ob es da ein Blockly Skript o.ä. gibt, was das auslöst.

Im Adapter gibt es keinen Code der in Abhängigkeit von Uhrzeit oder Tag eine Reinigung auslöst.

**Comment by Dragon0501** [comment]
Oki. Wundert mich nur, da es erst seit dem update auf die neue Version so ist. Aber wenn du sagts es kann nicht sein, dann schaue ich mal in den Rest des Brokers.

**Comment by Dragon0501** [comment]
sorry it wasn't your fold. It was just my fold! adapter works pretty good!!!
