### ISSUE TITLE
Empty CleaningLog values

### ISSUE THREAD

**Issue by Zafford** [mrbungle64/ioBroker.ecovacs-deebot#69]
I assume it is my own stupidity, but I have the following problems.
I have a Deebot 950 and am using the version 0.6.1 of the Adapter. Everything I tried was working fine except that "last20logs", "lastCleaningMapImageURL" and "lastCleaningTimestamp". Reading through other users posts I assume that should not be the case :) What am I missing

**Comment by mrbungle64** [comment]
> I assume it is my own stupidity, but I have the following problems.
> I have a Deebot 950 and am using the version 0.6.1 of the Adapter. Everything I tried was working fine except that "last20logs", "lastCleaningMapImageURL" and "lastCleaningTimestamp". Reading through other users posts I assume that should not be the case :) What am I missing

Hi @Zafford 

I can confirm that there are currently some problems with receiving the cleaninglog values. Some are maybe caused by the Ecovacs API. We are currently analyzing that problems.

But even if there are some problems, typically the values are not empty.
* Have you already checked if the cleaning logs are currently available via mobile app?
* In some cases restarting the adapter also may help.

**Comment by Zafford** [comment]
Hi @mrbungle64 Yes, the mobile app shows the cleaning logs just fine. I just reload the instance (is this what you mean by "restarting the adapter"?) and the values are still empty

**Comment by mrbungle64** [comment]
> ... is this what you mean by "restarting the adapter"?

Yes :)

Do you have the version you are currently running installed from GitHub or the "latest" repository?

**Comment by Zafford** [comment]
from the latest repository - not sure how to do it from the github on Windows...

**Comment by Zafford** [comment]
found the cat in the adapters page, will try...

**Comment by Zafford** [comment]
checked with the version from github, still empty

**Comment by mrbungle64** [comment]
@Zafford 

Thanks for the information.
There is another report that this problem is currently occurring:
https://forum.iobroker.net/post/434042
I can just speculate at this moment., but perhaps Ecovacs has made some changes to the API.

**Comment by mrbungle64** [comment]
@Zafford 

Which version of js-controller and node.js do you use?

**Comment by Zafford** [comment]
js-controller 2.2.9 and nodejs 10.17.0

**Comment by boriswerner** [comment]
I tested with Ozmo 950 (Firmware 1.7.9) and the following configurations:
**RaspberryPi**
JS controller 2.1.1
Node.js 10.18.1

**RaspberryPi**
JS controller: 2.2.9
Node.js: v10.18.1

**Docker**
JS controller: 2.2.9
Node.js: v10.20.1

**Docker**
JS controller: 3.1.4
Node.js: v10.20.1

Docker was freshly installed and updated. The states
last20Logs
lastCleaningMapImageURL
lastCleaningTimestamp
are created and filled some seconds after instance start.

**Comment by mrbungle64** [comment]
Hi @Zafford 

if the cleaningLog values still empty you can try version 0.6.2 from GitHub.
A new option "other ..." ->  "Use alternative API call for lastCleaningMapImageURL and lastCleaningTimestamp" available in the adapter config.

**Comment by Zafford** [comment]
tried 0.6.2, unfortunately the fields are still empty.
probably related, I get now "state change info.error => unknown errorCode: 7" every polling cycle. If I remove the flag with the alternative api, that stops

**Comment by mrbungle64** [comment]
@Zafford 
Are you using Switzerland as countrycode?

**Comment by Zafford** [comment]
@mrbungle64 yes, even though it says "Switzerland (EU)" 😀

**Comment by boriswerner** [comment]
@Zafford From the error you are receiving and also a report with debug logs in the test thread in the iobroker forum we can see that there seem to be no logs delivered for your device.

Can you please install the latest version here from GitHub, set the log level to debug and start the instance? There should be a new state in the info-Channel called debugMessage. Is this giving some output?
![image](https://user-images.githubusercontent.com/25967818/82566510-4db24480-9b7c-11ea-83a5-af681b6c5db3.png)

Please leave the alternative API call deactivated.

Technical details for documentation:
error 7 received by GetLastCleanLog is:
{"ret":"fail","errno":7,"error":"log data is not found"}
This API call seems to be erroneous.
In a debug log from stefande in the iobroker forum we could see that with the standard API call (GetCleanLogs) seems to deliver no logs as the timestamp and map are explicitly set to null and the last20 value is not emitted from the library:
cleaninglog.lastCleaningTimestamp => null
cleaninglog.lastCleaningMapImageURL => null
This only happens if the call is done and also an answer is retrieved but no logs were 
It seems that they deactivated some features and logs are not being created at all or they introduced a new API call with the app version 1.4.5 from 18.5.

**Comment by Zafford** [comment]
@boriswerner ok, the data in "debugMessage" is "CleanLog is empty: {"resultCode":"0","resultCodeMessage":"ok","resultData":{"ret":"ok","logs":[]}}"

**Comment by boriswerner** [comment]
@Zafford thanks for the info.
Thats what we expected and the same as another user in the iobroker forum thread reported.
This confirms that ecovacs is responding correctly but without any log-data.
So currently there is nothing to do for us until ecovacs has finished its work on correcting their system first.
We will keep this issue open and continue to watch the issue.

**Comment by Zafford** [comment]
@boriswerner @mrbungle64 thanks guys, much appreciated - let's wait and see. One question though, that means the logs in the mobile app get passed through a different way then?

**Comment by boriswerner** [comment]
Thats what we will try to find out. Currently my logs also dont get updated. But as I had some before it seems ecovacs just delivers what they already saved at some point.

Maybe then some more questions:
How long do you have your Ozmo already? Reset at some point in time?
How many logs are shown in the app and are they complete and updated regularly?
Which version of the app are you using? (Android: most recent is 1.4.5 released on monday or iOS?)
Whcih deebot firmware version are you on?

In another forum many people report problems with the logs for the 950:
https://www.roboter-forum.com/index.php?thread/40009-reinigungsprotokoll-wird-nicht-gespeichert/

**Comment by Zafford** [comment]
And here some answers 👍 
How long do you have your Ozmo already? Reset at some point in time?: approx. 2 weeks, not reset yet
How many logs are shown in the app and are they complete and updated regularly?: 19 logs and yes
Which version of the app are you using? Android, Version 1.4.5 from 17.5.2020
Which deebot firmware version are you on? 1.7.9

**Comment by boriswerner** [comment]
Okay, that confirms also the theory that relatively new registered users are affected and for "older" users the old API call is at least somehow still working. And also that confirms there must be a new call.
Thanks.

**Comment by volkerverkamp** [comment]
> Okay, that confirms also the theory that relatively new registered users are affected and for "older" users the old API call is at least somehow still working. And also that confirms there must be a new call.

Unfortunatelyte I have to disagree to that theory since I am affected from this issue as well, but I registered in Feb 2020.

Node.js: v12.16.3
js-controller: 3.1.4
Adapter: Current Github (already tested with latest as well)

**Comment by boriswerner** [comment]
@volkerverkamp would have been a surprise if the behaviour would be consistent :-D
All 3 states are also completely empty for you?
Is the debugMessage the same?
"CleanLog is empty: {"resultCode":"0","resultCodeMessage":"ok","resultData":{"ret":"ok","logs":[]}}"

**Comment by volkerverkamp** [comment]
@boriswerner 
> All 3 states are also completely empty for you?
Yes: 
![image](https://user-images.githubusercontent.com/51383556/82660436-a809de80-9c2a-11ea-9cd6-14975a01192a.png)

> Is the debugMessage the same?
> "CleanLog is empty: {"resultCode":"0","resultCodeMessage":"ok","resultData":{"ret":"ok","logs":[]}}"
I have just restarted Instance in Debug-Mode and will report as soon as I have a result.

**Comment by volkerverkamp** [comment]
@boriswerner 
CleanLog is empty: {"resultCode":"0","resultCodeMessage":"ok","resultData":{"ret":"ok","logs":[]}}

**Comment by boriswerner** [comment]
At least it is the same picture as ecovacs is not delivering any logs for you. I will try to figure out what the new command is they are using for the app.

**Comment by smarteule** [comment]
Wie [hier](https://github.com/mrbungle64/ioBroker.ecovacs-deebot/issues/73) gewünscht, mein Inhalt von ecovacs-deebot.0.info.debugMessage.
`CleanLog is empty: {"resultCode":"0","resultCodeMessage":"ok","resultData":{"ret":"ok","logs":[]}}`

**Comment by mrbungle64** [comment]
https://github.com/mrbungle64/ioBroker.ecovacs-deebot/issues/89#issuecomment-711141897
