### ISSUE TITLE
Omni T30 Pro Room cleaning not possible

### ISSUE THREAD

**Issue by surfer-09** [mrbungle64/ioBroker.ecovacs-deebot#694]
### Is there an existing issue for this?

- [X] I have searched the existing issues and no issue is describing my issue

### The problem

Hi,
I am unable to clean a specific room with the Deebot Omni T30 Pro. There should be a Map ID, but it is not displayed for the objects in the IO-Broker.

![firefox_DWD7NpYtpY](https://github.com/mrbungle64/ecovacs-deebot.js/assets/106930606/46230b1b-0128-44f7-b05c-5dccacd4842c)

### With which model does the problem occur?

Other model (Please fill out the fields at the bottom of the form)

### From which source you have installed the library?

GitHub

### Version of the ecovacs-deebot.js library

/

### Version of Node.js

20.14.0

### Operating system

Windows

### Anything in the logs that might be useful?

```txt
Adapter Version 1.4.15
```

### Which "other" models are you using?

Deebot Omni T30 Pro

**Comment by mrbungle64** [comment]
@surfer-09 

Are you using Adapter Version 1.4.15 or 1.4.16-alpha.2?

**Comment by surfer-09** [comment]
I‘m using 1.4.15

**Comment by mrbungle64** [comment]
@surfer-09 

> I‘m using 1.4.15

Ok, like I already mentioned on the ioBroker forum, you need to install the current alpha version for the T30 series ("Für den T30 benötigst du die Alpha Version von GitHub (aktuell 1.4.16-alpha.2)")

**Comment by surfer-09** [comment]
I am now using version 1.14.16 Alpha 2, but the room IDs are still not being displayed.
The data points stay empty.

![objects_-_IOBroker-Master_–_Mozilla_Firefox-2024-07-04_19_42_37](https://github.com/mrbungle64/ioBroker.ecovacs-deebot/assets/106930606/fe559988-55f9-472f-9cbd-0a4c94552856)

**Comment by mrbungle64** [comment]
@surfer-09 

Please try version 1.4.16-alpha.3
