### ISSUE TITLE
Ozmo 950: Probleme mit der SpotArea Funktion

### ISSUE THREAD

**Issue by smarteule** [mrbungle64/ioBroker.ecovacs-deebot#73]
Hallo,
leider habe ich wiedermal ein Problem.
Seit geraumer Zeit funktionieren die Tasten unter Objekte\control\spotArea_0 bis spotArea_7 nicht mehr. Der Roboter fährt aus der Ladestation, fängt an seine Motoren einzuschalten und bleibt stehen.

![image](https://user-images.githubusercontent.com/61357030/82751274-6d34b180-9db6-11ea-93d1-595ed37ee350.png)

Die cleaninglogs bleiben ebenfalls leer und wurden noch nie angezeigt.

![image](https://user-images.githubusercontent.com/61357030/82751242-33fc4180-9db6-11ea-81e4-c28b83b35f6d.png)

Ozmo950
ioBroker Ecovacs Deebot Adapter: V 0.6.4
Android App: V 1.4.5

**Comment by mrbungle64** [comment]
Hallo @smarteule 
> 
> Die cleaninglogs bleiben ebenfalls leer und wurden noch nie angezeigt.
> 
> ![image](https://user-images.githubusercontent.com/61357030/82751242-33fc4180-9db6-11ea-81e4-c28b83b35f6d.png)

diese Problem ist bereits [bekannt](https://github.com/mrbungle64/ioBroker.ecovacs-deebot/issues/69) und wurde auch in die [Known Issues](https://github.com/mrbungle64/ioBroker.ecovacs-deebot#known-issues) aufgenommen.

Können wir uns hier auf die SpotAreas konzentrieren und auch den Titel entsprechend anpassen?
Vorschlag: "Ozmo 950: Problem mit der SpotArea Funktion"

**Comment by smarteule** [comment]
@mrbungle64  "Dieses Problem ist bereits bekannt ..."

Ist Okay, ich wollte es hiermit auch nur bei meinem Ozmo bestätigen. Alles gut.

**Comment by mrbungle64** [comment]
> @mrbungle64 "Dieses Problem ist bereits bekannt ..."
> 
> Ist Okay, ich wollte es hiermit auch nur bei meinem Ozmo bestätigen. Alles gut.

Ja, danke Dir :+1: 
Wir sollten es halt aus dem Titel rausnehmen.

**Comment by mrbungle64** [comment]
Das geschilderte Problem mit der SpotArea Funktion scheint das gleiche oder zumindest ähnlich zu sein, wie folgender Post:

https://forum.iobroker.net/post/435052

**Comment by mrbungle64** [comment]
@smarteule 

> Seit geraumer Zeit ...

Kannst Du den Zeitraum ein bisschen eingrenzen?
Hast Du dieses Problem bereits schon mal vor der Version 0.6.x gehabt?

**Comment by boriswerner** [comment]
@smarteule ich hab das bei mir mal versucht nachzuvollziehen und das beschriebene Problem bekomme ich nur, wenn es die spotArea, dessen Knopf ich gedrückt habe, in der Karte, die er gerade als aktiv erkannt hat, nicht gibt.
Kannst du bitte folgende Dinge einmal tun bzw. beantworten (gerne auch einmal einen Screenshot deiner map-Struktur schicken):
Instanz in den debug-Modus setzen (log level)
Was steht im  ecovacs-deebot.0.map.relocationState? Sollte "ok" sein, wie im Screenshot zu sehen.
Was steht in der ecovacs-deebot.0.map.currentMapMID? In meinem Beispiel 302903113
Prüfe bitte mit der entsprechenden MapID, welche spotAreas es im map-Folder gibt (hier sspotAreaID = 0) und ob spotAreaIsAvailable auf true steht (siehe Screenshot) und drücke einen der entsprechenden Buttons im control-Folder, in meinem Beispiel der state ecovacs-deebot.0.control.spotArea_0.

Fängt er mit der Reinigung an oder gleiches Verhalten?
Dann die Frage von mrbungle: Was passiert, wenn du den Button im map-Folder für die spotArea drückst oder die spotArea-ID manuell im control-Eingabefeld eingibts? 

![image](https://user-images.githubusercontent.com/25967818/82755440-bd6e3c80-9dd3-11ea-9e8f-0910b73b0958.png)

P.S.: zu den cleaninglogs: magst du in dem anderen issue (https://github.com/mrbungle64/ioBroker.ecovacs-deebot/issues/69) auch nochmal bestätigen, was bei dir im state info.debugMessage steht? Danke.

**Comment by smarteule** [comment]
> Kannst du bitte folgende Dinge einmal tun bzw. beantworten (gerne auch einmal einen Screenshot deiner map-Struktur schicken):
> Instanz in den debug-Modus setzen (log level)

Habe ich gemacht.

> Was steht im ecovacs-deebot.0.map.relocationState? Sollte "ok" sein, wie im Screenshot zu sehen.

Da steht ok drin.

> Was steht in der ecovacs-deebot.0.map.currentMapMID? In meinem Beispiel 302903113

Hier steht das drin: 1090175422

> Prüfe bitte mit der entsprechenden MapID, welche spotAreas es im map-Folder gibt (hier sspotAreaID = 0) und ob spotAreaIsAvailable auf true steht (siehe Screenshot) und drücke einen der entsprechenden Buttons im control-Folder, in meinem Beispiel der state ecovacs-deebot.0.control.spotArea_0.

Die SpotAreas stehen alle auf true. Jedoch ist die Reihenfolge 0, 11, 12, 13, 14, 5, 6, 8 irgendwie komisch (siehe Bild). 
![image](https://user-images.githubusercontent.com/61357030/82760468-f4ece100-9df3-11ea-8d52-475e801418e5.png)

> 
> Fängt er mit der Reinigung an oder gleiches Verhalten?

Gleiches Verhalten, wie oben beschrieben.
> Dann die Frage von mrbungle: Was passiert, wenn du den Button im map-Folder für die spotArea drückst oder die spotArea-ID manuell im control-Eingabefeld eingibts?

Da startet er ebenfalls seine Motoren bleibt aber auf der Stelle.
> 

> 
> P.S.: zu den cleaninglogs: magst du in dem anderen issue (#69) auch nochmal bestätigen, was bei dir im state info.debugMessage steht? Danke.

Ja, kann ich machen. Kein Problem.

PS: War gerade in der Ecovacs App und musste feststellen, dass meine Karte nicht mehr korrekt ist. Plötzlich habe ich Räume, die gar nicht zu meiner Wohnung (utopisch) gehören.

**Comment by mrbungle64** [comment]
Hallo @smarteule 
danke für die Infos :+1: 

> 
> PS: War gerade in der Ecovacs App und musste feststellen, dass meine Karte nicht mehr korrekt ist. Plötzlich habe ich Räume, die gar nicht zu meiner Wohnung (utopisch) gehören.

Wie schaut es mit den zur Wohnung gehörenden Bereichen aus?
Sind die alle noch in der App zu sehen?

Falls nicht, hätte ich eine Vermutung:
Da die Räume nicht mehr auf die SpotAreas im Adpater passen, schickst Du unbewusst den Roboter in einen Bereich, der dem Roboter inzwischen unbekannt ist.

**Comment by smarteule** [comment]
Die zur Wohnung gehörenden Bereiche sind zwar noch da, aber es sind zusätzliche Bereiche hinzugekommen bzw. ein Bereich ist gänzlich verändert.

Ich habe den Roboter jetzt komplett zurückgesetzt, abgemeldet und lasse gerade erneut eine Karte erstellen. Man müsste diese Karten abspeichern und dann wiederherstellen können. Das wäre super.

Beim Erstellen der jetzigen Karte fangen die Probleme schon wieder an. Der Roboter erkennt zwar die Räume, aber fährt nur die Hälfte der Räume ab (siehe Screenshot). Die andere obere Hälfte fährt er irgendwann wenn er in einem anderen Raum war ab. Die untere fährt er dann noch einmal zur Flächenreinigung ab. 

![image](https://user-images.githubusercontent.com/61357030/82761281-ddb0f200-9df9-11ea-9f2f-079bab95b6c0.png)

**Comment by boriswerner** [comment]
@smarteule das Verhalten ist aber normal bei der Erstellung der Karte. Das steht auch in der Anleitung, dass er sich Bereiche von soundso viel Quadratmetern zurechtlegt und dann den Rest später macht. Einfach zu Ende machen lassen

**Comment by smarteule** [comment]
Als ich ihn gekauft hatte, war das nicht so. Da hat er komplett den Wohn- und Essbereich gemacht und ist dann in die Nebenräume.

**Comment by boriswerner** [comment]
@smarteule funktioniert es nach Neuerstellung der Karte wieder?

**Comment by smarteule** [comment]
OK, jetzt geht es wieder. Ist nur blöd jedesmal neu auf zu setzen.

**Comment by mrbungle64** [comment]
> OK, jetzt geht es wieder. Ist nur blöd jedesmal neu auf zu setzen.

Hallo @smarteule 

Es ist ja schon mal erfreulich, dass der Roboter sich wieder normal verhält :+1: 

Aber was meinst Du mit "jedesmal"?

**Comment by smarteule** [comment]
Die Karte neu aufbauen. Man müsste diese Karten abspeichern und dann wiederherstellen können.

**Comment by mrbungle64** [comment]
> Die Karte neu aufbauen. Man müsste diese Karten abspeichern und dann wiederherstellen können.

Ja das wäre sicher allgemein hilfreich, wenn man das machen könnte.
Vielleicht schaffen wir das im Rahmen dieses Projektes eine Art Backup-Funktion zu implementieren, wenn Ecovacs das schon nicht anbietet ;)

Ich meine aber: das "jedesmal" hatte jetzt erst mal nichts direkt mit dem Adapter zu tun, oder?

**Comment by smarteule** [comment]
Ich meine aber: das "jedesmal" hatte jetzt erst mal nichts direkt mit dem Adapter zu tun, oder? -> Nein, nein. Eure Arbeit ist super!!!! Der Adapter ist SPITZE!!!

**Comment by mrbungle64** [comment]
> Ich meine aber: das "jedesmal" hatte jetzt erst mal nichts direkt mit dem Adapter zu tun, oder? -> Nein, nein. Eure Arbeit ist super!!!! Der Adapter ist SPITZE!!!

ok, das freut mich. Danke für das Feedback :+1:

**Comment by smarteule** [comment]
gerade gesehen im Log: ERROR


ecovacs-deebot.0 | 2020-05-26 12:55:54.426 | info | (24595) Unhandled chargestatus: null
-- | -- | -- | --
ecovacs-deebot.0 | 2020-05-26 12:55:49.222 | info | (24595) [vacbot] name: DEEBOT OZMO 950 Series
ecovacs-deebot.0 | 2020-05-26 12:55:49.217 | info | (24595) NoNo successfully connected
ecovacs-deebot.0 | 2020-05-26 12:55:47.575 | info | (24595) Using device Device[0]
ecovacs-deebot.0 | 2020-05-26 12:55:47.574 | info | (24595) Device[0]: {"did":"0b32419d-edad-47ab-9cd5-a564a3b9dea9","name":"E0001279610058180009","class":"yna5xi","resource":"4sZ6","nick":"NoNo","company":"eco-ng","bindTs":1590342681535}
ecovacs-deebot.0 | 2020-05-26 12:55:47.574 | info | (24595) Number of devices: 1
ecovacs-deebot.0 | 2020-05-26 12:55:47.573 | info | (24595) Successfully connected to Ecovacs server
ecovacs-deebot.0 | 2020-05-26 12:55:45.584 | info | (24595) starting. Version 0.6.5 in /opt/iobroker/node_modules/iobroker.ecovacs-deebot, node: v12.16.3, js-controller: 3.1.4
ecovacs-deebot.0 | 2020-05-26 12:55:45.164 | info | (24595) starting. Version 0.6.5 in /opt/iobroker/node_modules/iobroker.ecovacs-deebot, node: v12.16.3, js-controller: 3.1.4
ecovacs-deebot.0 | 2020-05-26 12:55:13.699 | info | (20341) Terminated (NO_ERROR): Without reason
ecovacs-deebot.0 | 2020-05-26 12:55:13.698 | info | (20341) terminating
ecovacs-deebot.0 | 2020-05-26 12:55:13.209 | info | (20341) Terminated (NO_ERROR): Without reason
ecovacs-deebot.0 | 2020-05-26 12:55:13.209 | info | (20341) terminating
ecovacs-deebot.0 | 2020-05-26 12:55:13.194 | info | (20341) cleaned everything up...
ecovacs-deebot.0 | 2020-05-26 12:55:13.192 | error | at Function.Module._load (internal/modules/cjs/loader.js:877:14)
ecovacs-deebot.0 | 2020-05-26 12:55:13.192 | error | at Module.load (internal/modules/cjs/loader.js:977:32)
ecovacs-deebot.0 | 2020-05-26 12:55:13.192 | error | at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
ecovacs-deebot.0 | 2020-05-26 12:55:13.192 | error | at Module._compile (internal/modules/cjs/loader.js:1133:30)
ecovacs-deebot.0 | 2020-05-26 12:55:13.192 | error | at Object.<anonymous> (/opt/iobroker/node_modules/canvas/lib/bindings.js:3:18)
ecovacs-deebot.0 | 2020-05-26 12:55:13.192 | error | at require (internal/modules/cjs/helpers.js:77:18)
ecovacs-deebot.0 | 2020-05-26 12:55:13.192 | error | at Module.require (internal/modules/cjs/loader.js:1019:19)
ecovacs-deebot.0 | 2020-05-26 12:55:13.192 | error | at Function.Module._load (internal/modules/cjs/loader.js:877:14)
ecovacs-deebot.0 | 2020-05-26 12:55:13.192 | error | at Module.load (internal/modules/cjs/loader.js:977:32)
ecovacs-deebot.0 | 2020-05-26 12:55:13.192 | error | at Object.Module._extensions..node (internal/modules/cjs/loader.js:1183:18)
ecovacs-deebot.0 | 2020-05-26 12:55:13.192 | error | the module (for instance, using `npm rebuild` or `npm install`).
ecovacs-deebot.0 | 2020-05-26 12:55:13.192 | error | NODE_MODULE_VERSION 72. Please try re-compiling or re-installing
ecovacs-deebot.0 | 2020-05-26 12:55:13.192 | error | NODE_MODULE_VERSION 64. This version of Node.js requires
ecovacs-deebot.0 | 2020-05-26 12:55:13.192 | error | was compiled against a different Node.js version using
ecovacs-deebot.0 | 2020-05-26 12:55:13.192 | error | (20341) Error: The module '/opt/iobroker/node_modules/canvas/build/Release/canvas.node'
ecovacs-deebot.0 | 2020-05-26 12:55:13.189 | error | at Function.Module._load (internal/modules/cjs/loader.js:877:14)
ecovacs-deebot.0 | 2020-05-26 12:55:13.189 | error | at Module.load (internal/modules/cjs/loader.js:977:32)
ecovacs-deebot.0 | 2020-05-26 12:55:13.189 | error | at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
ecovacs-deebot.0 | 2020-05-26 12:55:13.189 | error | at Module._compile (internal/modules/cjs/loader.js:1133:30)
ecovacs-deebot.0 | 2020-05-26 12:55:13.189 | error | at Object.<anonymous> (/opt/iobroker/node_modules/canvas/lib/bindings.js:3:18)
ecovacs-deebot.0 | 2020-05-26 12:55:13.189 | error | at require (internal/modules/cjs/helpers.js:77:18)
ecovacs-deebot.0 | 2020-05-26 12:55:13.189 | error | at Module.require (internal/modules/cjs/loader.js:1019:19)
ecovacs-deebot.0 | 2020-05-26 12:55:13.189 | error | at Function.Module._load (internal/modules/cjs/loader.js:877:14)
ecovacs-deebot.0 | 2020-05-26 12:55:13.189 | error | at Module.load (internal/modules/cjs/loader.js:977:32)
ecovacs-deebot.0 | 2020-05-26 12:55:13.189 | error | at Object.Module._extensions..node (internal/modules/cjs/loader.js:1183:18)
ecovacs-deebot.0 | 2020-05-26 12:55:13.189 | error | the module (for instance, using `npm rebuild` or `npm install`).
ecovacs-deebot.0 | 2020-05-26 12:55:13.189 | error | NODE_MODULE_VERSION 72. Please try re-compiling or re-installing
ecovacs-deebot.0 | 2020-05-26 12:55:13.189 | error | NODE_MODULE_VERSION 64. This version of Node.js requires
ecovacs-deebot.0 | 2020-05-26 12:55:13.189 | error | was compiled against a different Node.js version using
ecovacs-deebot.0 | 2020-05-26 12:55:13.189 | error | (20341) Error: The module '/opt/iobroker/node_modules/canvas/build/Release/canvas.node'
ecovacs-deebot.0 | 2020-05-26 12:55:13.191 | error | the module (for instance, using `npm rebuild` or `npm install`).
ecovacs-deebot.0 | 2020-05-26 12:55:13.191 | error | NODE_MODULE_VERSION 72. Please try re-compiling or re-installing
ecovacs-deebot.0 | 2020-05-26 12:55:13.191 | error | NODE_MODULE_VERSION 64. This version of Node.js requires
ecovacs-deebot.0 | 2020-05-26 12:55:13.191 | error | was compiled against a different Node.js version using
ecovacs-deebot.0 | 2020-05-26 12:55:13.191 | error | (20341) uncaught exception: The module '/opt/iobroker/node_modules/canvas/build/Release/canvas.node'
ecovacs-deebot.0 | 2020-05-26 12:55:13.188 | error | the module (for instance, using `npm rebuild` or `npm install`).
ecovacs-deebot.0 | 2020-05-26 12:55:13.188 | error | NODE_MODULE_VERSION 72. Please try re-compiling or re-installing
ecovacs-deebot.0 | 2020-05-26 12:55:13.188 | error | NODE_MODULE_VERSION 64. This version of Node.js requires
ecovacs-deebot.0 | 2020-05-26 12:55:13.188 | error | was compiled against a different Node.js version using
ecovacs-deebot.0 | 2020-05-26 12:55:13.188 | error | (20341) uncaught exception: The module '/opt/iobroker/node_modules/canvas/build/Release/canvas.node'
ecovacs-deebot.0 | 2020-05-26 12:28:03.003 | info | (20341) set Clean Speed: 2
ecovacs-deebot.0 | 2020-05-26 11:24:48.700 | info | (20341) Unhandled chargestatus: null
ecovacs-deebot.0 | 2020-05-26 11:24:43.704 | info | (20341) [vacbot] name: DEEBOT OZMO 950 Series
ecovacs-deebot.0 | 2020-05-26 11:24:43.702 | info | (20341) NoNo successfully connected
ecovacs-deebot.0 | 2020-05-26 11:24:41.830 | info | (20341) Using device Device[0]
ecovacs-deebot.0 | 2020-05-26 11:24:41.829 | info | (20341) Device[0]: {"did":"0b32419d-edad-47ab-9cd5-a564a3b9dea9","name":"E0001279610058180009","class":"yna5xi","resource":"4sZ6","nick":"NoNo","company":"eco-ng","bindTs":1590342681535}
ecovacs-deebot.0 | 2020-05-26 11:24:41.828 | info | (20341) Number of devices: 1
ecovacs-deebot.0 | 2020-05-26 11:24:41.827 | info | (20341) Successfully connected to Ecovacs server
ecovacs-deebot.0 | 2020-05-26 11:24:39.564 | info | (20341) starting. Version 0.6.5 in /opt/iobroker/node_modules/iobroker.ecovacs-deebot, node: v12.16.3, js-controller: 3.1.4
ecovacs-deebot.0 | 2020-05-26 11:24:39.266 | info | (20341) starting. Version 0.6.5 in /opt/iobroker/node_modules/iobroker.ecovacs-deebot, node: v12.16.3, js-controller: 3.1.4
ecovacs-deebot.0 | 2020-05-26 11:24:33.167 | info | (20970) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
ecovacs-deebot.0 | 2020-05-26 11:24:33.166 | info | (20970) terminating
ecovacs-deebot.0 | 2020-05-26 11:24:32.672 | info | (20970) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
ecovacs-deebot.0 | 2020-05-26 11:24:32.671 | info | (20970) terminating
ecovacs-deebot.0 | 2020-05-26 11:24:32.670 | info | (20970) cleaned everything up...
ecovacs-deebot.0 | 2020-05-26 11:24:32.667 | info | (20970) Got terminate signal TERMINATE_YOURSELF
ecovacs-deebot.0 | 2020-05-26 11:24:32.664 | info | (20970) Got terminate signal TERMINATE_YOURSELF

**Comment by mrbungle64** [comment]
@smarteule 

> gerade gesehen im Log: ERROR

Auch wenn ich Error Einträge sehen kann: ein bisschen mehr Kontext wäre nett :)
Btw.: Gibt es einen Zusammenhang mit diesem Issue?

**Comment by mrbungle64** [comment]
```
ecovacs-deebot.0 | 2020-05-26 12:55:13.188 | error | NODE_MODULE_VERSION 72. Please try re-compiling or re-installing
-- | -- | -- | --
ecovacs-deebot.0 | 2020-05-26 12:55:13.188 | error | NODE_MODULE_VERSION 64. This version of Node.js requires
ecovacs-deebot.0 | 2020-05-26 12:55:13.188 | error | was compiled against a different Node.js version using
```

Das wird das gleiche wie in diesem Fall hier sein:

https://github.com/mrbungle64/ioBroker.ecovacs-deebot/issues/45#issuecomment-621418014

**Comment by smarteule** [comment]
Okay Log ist sauber.
