### ISSUE TITLE
reset of map possible?

### ISSUE THREAD

**Issue by n4pstarr** [mrbungle64/ioBroker.ecovacs-deebot#740]
### The question

Hi!
Since my Deebot 950 often screws up the map and I have to reset it, I thougth about automazing this via IOBroker.
Would this be possible? Currently, I see no state that would provide this feature.
Thanks in advance!
BR
Chris

### Which model do you own?

Deebot OZMO 950

### Which version of the ioBroker adapter are you currently using?

1.4.15

**Comment by mrbungle64** [comment]
@n4pstarr 

Unfortunately, I do not know of any way to save and restore a map for this model.
