### ISSUE TITLE
warn message

### ISSUE THREAD

**Issue by rebel1985** [mrbungle64/ioBroker.ecovacs-deebot#745]
### Is there an existing issue for this?

- [X] I have searched the existing issues and no issue is describing my issue

### The problem

error calling getBase64PNG: The module '/opt/iobroker/node_modules/ecovacs-deebot/node_modules/canvas/build/Release/canvas.node'was compiled against a different Node.js version usingNODE_MODULE_VERSION 108. This version of Node.js requiresNODE_MODULE_VERSION 115. Please try re-compiling or re-installingthe module (for instance, using `npm rebuild` or `npm install`).

### With which model does the problem occur?

Deebot T10 series

### From which source you have installed the library?

GitHub

### Version of the ecovacs-deebot.js library

1.4.16-alpha.3

### Version of Node.js

v20.16.0

### Operating system

Linux

### Additional information

it is an iobroker adapter
why can i fix it?

### Which "other" models are you using?

nothing

**Comment by mrbungle64** [comment]
https://github.com/mrbungle64/ioBroker.ecovacs-deebot/wiki/FAQ#nodejs-upgrade

https://forum.iobroker.net/topic/76554/ecovacs-deebot-warnmeldung
https://forum.iobroker.net/topic/55462/ecovacs-adapter-npm-warn-meldung
