### ISSUE TITLE
Adapter installation error in ioBroker

### ISSUE THREAD

**Issue by jordaam** [mrbungle64/ioBroker.ecovacs-deebot#75]
I got this error logs while installing the adapter:

$ ./iobroker add ecovacs-deebot  --host raspberrypi
NPM version: 6.14.4
npm install iobroker.ecovacs-deebot@1.0.0 --loglevel error --prefix "/opt/iobroker" (System call)
Package pixman-1 was not found in the pkg-config search path.Perhaps you should add the directory containing `pixman-1.pc'to the PKG_CONFIG_PATH environment variableNo package 'pixman-1' found
gyp: Call to 'pkg-config pixman-1 --libs' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error gyp ERR! stack Error: `gyp` failed with exit code: 1gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)gyp ERR! stack     at ChildProcess.emit (events.js:198:13)gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)gyp ERR! System Linux 4.19.93-v7l+gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/opt/iobroker/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/opt/iobroker/node_modules/canvas/build/Release" "--napi_version=6" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v64"gyp ERR! cwd /opt/iobroker/node_modules/canvasgyp ERR! node -v v10.20.1gyp ERR! node-gyp -v v5.1.0gyp ERR! not ok 
node-pre-gyp
 ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/opt/iobroker/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/opt/iobroker/node_modules/canvas/build/Release --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/opt/iobroker/node_modules/node-pre-gyp/lib/util/compile.js:83:29)node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:198:13)node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)node-pre-gyp
 ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)node-pre-gyp ERR! System Linux 4.19.93-v7l+node-pre-gyp ERR! command "/usr/bin/node" "/opt/iobroker/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"node-pre-gyp ERR! cwd /opt/iobroker/node_modules/canvas
node-pre-gyp ERR! node -v v10.20.1node-pre-gyp ERR! node-pre-gyp -v v0.11.0node-pre-gyp ERR! not ok 
host.raspberrypi install adapter ecovacs-deebot
upload [4] ecovacs-deebot.admin /opt/iobroker/node_modules/iobroker.ecovacs-deebot/admin/words.js words.js application/javascript
upload [3] ecovacs-deebot.admin /opt/iobroker/node_modules/iobroker.ecovacs-deebot/admin/style.css style.css text/css
upload [2] ecovacs-deebot.admin /opt/iobroker/node_modules/iobroker.ecovacs-deebot/admin/index_m.html index_m.html text/html
upload [1] ecovacs-deebot.admin /opt/iobroker/node_modules/iobroker.ecovacs-deebot/admin/ecovacs-deebot.png ecovacs-deebot.png image/png
upload [0] ecovacs-deebot.admin /opt/iobroker/node_modules/iobroker.ecovacs-deebot/admin/admin.d.ts admin.d.ts video/mp2t
host.raspberrypi object system.adapter.ecovacs-deebot created/updated
host.raspberrypi create instance ecovacs-deebot
host.raspberrypi object system.adapter.ecovacs-deebot.0.sigKill created
host.raspberrypi object system.adapter.ecovacs-deebot.0.eventLoopLag created
host.raspberrypi object system.adapter.ecovacs-deebot.0.outputCount created
host.raspberrypi object system.adapter.ecovacs-deebot.0.inputCount created
host.raspberrypi object system.adapter.ecovacs-deebot.0.uptime created
host.raspberrypi object system.adapter.ecovacs-deebot.0.memRss created
host.raspberrypi object system.adapter.ecovacs-deebot.0.memHeapTotal created
host.raspberrypi object system.adapter.ecovacs-deebot.0.memHeapUsed created
host.raspberrypi object system.adapter.ecovacs-deebot.0.cputime created
host.raspberrypi object system.adapter.ecovacs-deebot.0.cpu created
host.raspberrypi object system.adapter.ecovacs-deebot.0.compactMode created
host.raspberrypi object system.adapter.ecovacs-deebot.0.connected created
host.raspberrypi object system.adapter.ecovacs-deebot.0.alive created
host.raspberrypi object system.adapter.ecovacs-deebot.0 created
process exited with code 0

Any suggestions?

**Comment by mrbungle64** [comment]
Have you already followed the installation instructions?

https://github.com/mrbungle64/ioBroker.ecovacs-deebot#Installation

**Comment by mrbungle64** [comment]
@jordaam 

Have you installed all [required packages](https://github.com/mrbungle64/ioBroker.ecovacs-deebot#Installation)?

```bash
build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev
```
