### ISSUE TITLE
link zur reinigungskarte ist alt bzw. falsch

### ISSUE THREAD

**Issue by rebel1985** [mrbungle64/ioBroker.ecovacs-deebot#76]
die karte der letzten reinigung wird nicht aktuel im adapter 1.0.0 angezeigt, es ist bei mir eine alte karte. 
ggf. ist die karte sogar noch vom alten deebot (wurde zwecks garantie ausgetauscht gegen einen neuen) laut der handy app sieht die karte etwas anders aus.
ich habe den deebot ozmo 900 ,
ich meine den eintrag unter objekte = ecovacs-deebot.0.cleaninglog.lastCleaningMapImageURL

**Comment by mrbungle64** [comment]
Hallo @rebel1985 

hatte das schon mal zuverlässig funktoniert bei deinem "alten" Gerät?
Passen die anderen Wert im Ordner "cleaninglog" oder sind die auch nicht aktuell?

**Comment by rebel1985** [comment]
jetzt nach dem ich mich nopch mal im adapter mit dem pw neu angemelödet habe, habe ich jetzt eine aktuelle reinigungskarte , auch habe ich die adapter version 1.0.1 .
es fehlen aber noch die roten speerflächen auf der map. sonst passt der ordner cleaninglog eigentlich mit den aktuellen werten.

**Comment by mrbungle64** [comment]
> jetzt nach dem ich mich nopch mal im adapter mit dem pw neu angemelödet habe, habe ich jetzt eine aktuelle reinigungskarte , auch habe ich die adapter version 1.0.1 .

Das ist ja schon mal erfreulich :)

> es fehlen aber noch die roten speerflächen auf der map. 

Auf das Aussehen dieser Map haben wir keinen Einfluss. Die wird ja von Ecovacs erstellt.

> sonst passt der ordner cleaninglog eigentlich mit den aktuellen werten.

Das ist ebenfalls erfreulich :)

Können wir das Ticket schließen?

**Comment by rebel1985** [comment]
ja könnwa schließen passt alles soweit mit den daten in der app.
