### ISSUE TITLE
Zubehör Status erst nach Adapter Restart aktualisiert

### ISSUE THREAD

**Issue by lammy000** [mrbungle64/ioBroker.ecovacs-deebot#78]
Hi,

der Adapter aktualisiert den Status am Beispiel der Seitenbürsten erst nachdem ich ihn neu gestartet habe.

**Comment by mrbungle64** [comment]
> Hi,
> 
> der Adapter aktualisiert den Status am Beispiel der Seitenbürsten erst nachdem ich ihn neu gestartet habe.

Hi @lammy000 

- ist das jetzt einmalig so gewesen oder schon mehrmals?
- wie hoch ist die Abweichung? Bei 1% Abweichung wird der Grund sein, dass die App anders rundet

Falls es mehrmals war und die Abweichungen > 1% sind:
- welches Modell ist das?
- welche Version des Adapters hast Du installiert?

**Comment by lammy000** [comment]
war eine Abweichung von 130% ;-) im iobroker wurde -31% angezeigt und ich habe gerade neue angebaut und in der app resetet. das war aber schon mehrere Tage her.
Modell ist Ozmo950
Version 1.0.3

**Comment by mrbungle64** [comment]
> war eine Abweichung von 130% ;-) im iobroker wurde -31% angezeigt und ich habe gerade neue angebaut und in der app resetet. das war aber schon mehrere Tage her.
> Modell ist Ozmo950
> Version 1.0.3

- Der Adapter Neustart war dann bisher nur 1x nach dem Reset notwendig?
- Hattest Du den Adapter schon vorher im Einsatz und war es bis zu dem Reset in Ordnung?

**Comment by lammy000** [comment]
Der Adapter Neustart war dann bisher nur 1x nach dem Reset notwendig? Ja
Hattest Du den Adapter schon vorher im Einsatz und war es bis zu dem Reset in Ordnung? vorher hatte ich ihn schon im Einsatz, bis dahin ist mir nichts aufgefallen

**Comment by mrbungle64** [comment]
> Der Adapter Neustart war dann bisher nur 1x nach dem Reset notwendig? Ja
> Hattest Du den Adapter schon vorher im Einsatz und war es bis zu dem Reset in Ordnung? vorher hatte ich ihn schon im Einsatz, bis dahin ist mir nichts aufgefallen

ok, dann gehe ich mal davon aus, dass das "nur" im Zusammenhang mit einem Reset passiert.

Ich schaue mir das aber trotzdem bei Gelegenheit mal an, ob im Code ein "offensichtlicher" Bug zu finden ist.
Ansonsten würde ich den Issue anschließend schließen, da der Aufwand unverhältnismäßig hoch ist das Szenario nachzustellen.

**Comment by lammy000** [comment]
ich teste es in einer woche noch mal
