### ISSUE TITLE
Objekte reagieren auf True und False und senden einen Befehl

### ISSUE THREAD

**Issue by lammy000** [mrbungle64/ioBroker.ecovacs-deebot#79]
Hi,

ich aktiviere z.B. den Reinigungsmodus mit einem Taster über die Vis. Dieser Sendet ein True und danach wieder ein False. Der Robby bekommt das Signal zum Reinigen zwei mal hinter einander. Kannst du ggf. nicht auf Änderungen hörchen sondern nur auf true?!

**Comment by Dragon0501** [comment]
Du kannst einen anderen Button verwenden. Meiner simuliert einfach einen Tastendruck. Dann gibt's nur ein signal

**Comment by mrbungle64** [comment]
> Dieser Sendet ein True und danach wieder ein False. Der Robby bekommt das Signal zum Reinigen zwei mal hinter einander

Ich benutze den Vis Adapter nicht, aber ich denke dass das nicht der Standard sein wird, dass 2 Signale hintereinander gesendet werden.

> Du kannst einen anderen Button verwenden. Meiner simuliert einfach einen Tastendruck. Dann gibt's nur ein signal

Danke @Dragon0501

**Comment by Dragon0501** [comment]
Hat funktioniert? Oder soll ich raussuchen welchen?

**Comment by lammy000** [comment]
> Hat funktioniert? Oder soll ich raussuchen welchen?

Gerne nehme ich den du hast. 
Ich nutze aktuell den hier
`[{"tpl":"tplVis-materialdesign-Icon-Button-Toggle","data":{"oid":"ecovacs-deebot.0.control.clean","g_fixed":false,"g_visibility":false,"g_css_font_text":false,"g_css_background":false,"g_css_shadow_padding":true,"g_css_border":true,"g_gestures":false,"g_signals":false,"g_last_change":false,"visibility-cond":"==","visibility-val":1,"visibility-groups-action":"hide","toggleType":"value","stateIfNotTrueValue":"off","vibrateOnMobilDevices":"50","signals-cond-0":"==","signals-val-0":true,"signals-icon-0":"/vis/signals/lowbattery.png","signals-icon-size-0":0,"signals-blink-0":false,"signals-horz-0":0,"signals-vert-0":0,"signals-hide-edit-0":false,"signals-cond-1":"==","signals-val-1":true,"signals-icon-1":"/vis/signals/lowbattery.png","signals-icon-size-1":0,"signals-blink-1":false,"signals-horz-1":0,"signals-vert-1":0,"signals-hide-edit-1":false,"signals-cond-2":"==","signals-val-2":true,"signals-icon-2":"/vis/signals/lowbattery.png","signals-icon-size-2":0,"signals-blink-2":false,"signals-horz-2":0,"signals-vert-2":0,"signals-hide-edit-2":false,"lc-type":"last-change","lc-is-interval":true,"lc-is-moment":false,"lc-format":"","lc-position-vert":"top","lc-position-horz":"right","lc-offset-vert":0,"lc-offset-horz":0,"lc-font-size":"12px","lc-font-family":"","lc-font-style":"","lc-bkg-color":"","lc-color":"","lc-border-width":"0","lc-border-style":"","lc-border-color":"","lc-border-radius":10,"lc-zindex":0,"image":"/icons-mfd-svg/scene_robo_vac_cleaner.svg","imageTrue":"/icons-mfd-svg/scene_robo_vac_cleaner.svg","invertImage":true,"invertImageTrue":true,"colorBgTrue":"DodgerBlue","colorBgFalse":"#404040","valueOff":"nichts","valueOn":"true","colorPress":"yellow","autoLockAfter":"10","lockIconTop":"45","lockIconLeft":"55","lockIconSize":"20","lockIconColor":"red","lockFilterGrayscale":"30","iconHeight":"80","pushButton":true},"style":{"left":"1424px","top":"402px","width":"60px","height":"60px","border-width":"4px","margin-left":"","margin-top":"","margin-right":"","margin-bottom":"","border-color":"#404040","border-style":"solid","border-radius":"45px","padding":"0","padding-left":"0","padding-top":"0","padding-right":"0","padding-bottom":"0","box-shadow":"20","z-index":"20","overflow-x":""},"widgetSet":"materialdesign"}]`

**Comment by Dragon0501** [comment]
Meiner heißt Button state. Einen Haken bei no_style
Dann hat es etwas von altem win 98. Grau und eckig, so mag ich das!

**Comment by lammy000** [comment]
Teste ich mal! Danke dir!
