### ISSUE TITLE
Deebot 710 - Grundsätzlich ja, aber...

### ISSUE THREAD

**Issue by capitaenz** [mrbungle64/ioBroker.ecovacs-deebot#8]
Eine Reinigung kann ich starten, EINE, dann geht der Adapter auf rot.
Und in den Objekten steht unter Error "reconnecting"

`
ecovacs-deebot.0 | 2020-02-09 19:31:31.433 | info | (2195) New Device 0 successfully connected
-- | -- | -- | --
ecovacs-deebot.0 | 2020-02-09 19:31:30.075 | info | (2195) Successfully connected to Ecovacs server
ecovacs-deebot.0 | 2020-02-09 19:31:28.405 | info | (2195) reconnecting (2) ...
ecovacs-deebot.0 | 2020-02-09 19:31:23.051 | info | (2195) reconnecting (1) ...
ecovacs-deebot.0 | 2020-02-09 19:31:17.558 | info | (2195) starting. Version 0.3.4 in /opt/iobroker/node_modules/iobroker.ecovacs-deebot, node: v10.18.1
host.tinkerboard | 2020-02-09 19:31:16.209 | info | instance system.adapter.ecovacs-deebot.0 started with pid 2195
host.tinkerboard | 2020-02-09 19:31:09.395 | info | Restart adapter system.adapter.ecovacs-deebot.0 because enabled
host.tinkerboard | 2020-02-09 19:31:09.395 | info | instance system.adapter.ecovacs-deebot.0 terminated with code 0 (NO_ERROR)
host.tinkerboard | 2020-02-09 19:31:09.394 | error | Caught by controller[20]:     at Writable.write (/opt/iobroker/node_modules/readable-stream/lib/_stream_writable.js:334:11)
host.tinkerboard | 2020-02-09 19:31:09.394 | error | Caught by controller[20]:     at writeOrBuffer (/opt/iobroker/node_modules/readable-stream/lib/_stream_writable.js:417:5)
host.tinkerboard | 2020-02-09 19:31:09.394 | error | Caught by controller[20]:     at doWrite (/opt/iobroker/node_modules/readable-stream/lib/_stream_writable.js:428:64)
host.tinkerboard | 2020-02-09 19:31:09.394 | error | Caught by controller[20]:     at Writable.writable._write  (/opt/iobroker/node_modules/iobroker.ecovacs-deebot/node_modules/mqtt/lib/client.js:294:5)
host.tinkerboard | 2020-02-09 19:31:09.394 | error | Caught by controller[20]:     at work  (/opt/iobroker/node_modules/iobroker.ecovacs-deebot/node_modules/mqtt/lib/client.js:283:12)
host.tinkerboard | 2020-02-09 19:31:09.394 | error | Caught by controller[20]:     at MqttClient._handlePacket  (/opt/iobroker/node_modules/iobroker.ecovacs-deebot/node_modules/mqtt/lib/client.js:351:12)
host.tinkerboard | 2020-02-09 19:31:09.394 | error | Caught by controller[20]:     at MqttClient._handlePublish  (/opt/iobroker/node_modules/iobroker.ecovacs-deebot/node_modules/mqtt/lib/client.js:1162:12)
host.tinkerboard | 2020-02-09 19:31:09.394 | error | Caught by controller[20]:     at MqttClient.emit (events.js:198:13)
host.tinkerboard | 2020-02-09 19:31:09.394 | error | Caught by controller[20]:     at MqttClient.EcovacsMQTT.client.on  (/opt/iobroker/node_modules/iobroker.ecovacs-deebot/node_modules/ecovacs-deebot/library/ecovacsMQTT.js:82:18)
host.tinkerboard | 2020-02-09 19:31:09.393 | error | Caught by controller[20]:     at EcovacsMQTT._handle_ctl_mqtt  (/opt/iobroker/node_modules/iobroker.ecovacs-deebot/node_modules/ecovacs-deebot/library/ecovacsMQTT.js:259:34)
host.tinkerboard | 2020-02-09 19:31:09.393 | error | Caught by controller[20]: TypeError: Cannot read property 'key' of undefined
host.tinkerboard | 2020-02-09 19:31:09.393 | error | Caught by controller[19]: @#[line:0,col:undefined]
host.tinkerboard | 2020-02-09 19:31:09.393 | error | Caught by controller[19]: [xmldom error]	invalid doc source
host.tinkerboard | 2020-02-09 19:31:09.393 | error | Caught by controller[18]: [EcovacsMQTT] failure code: {errno}
host.tinkerboard | 2020-02-09 19:31:09.393 | error | Caught by controller[17]: [EcovacsMQTT] failure code: {errno}
host.tinkerboard | 2020-02-09 19:31:09.393 | error | Caught by controller[16]: [EcovacsMQTT] failure code: {errno}
host.tinkerboard | 2020-02-09 19:31:09.393 | error | Caught by controller[15]: [EcovacsMQTT] failure code: {errno}
host.tinkerboard | 2020-02-09 19:31:09.393 | error | Caught by controller[14]: [EcovacsMQTT] failure code: {errno}
host.tinkerboard | 2020-02-09 19:31:09.392 | error | Caught by controller[13]: [EcovacsMQTT] failure code: {errno}
host.tinkerboard | 2020-02-09 19:31:09.392 | error | Caught by controller[12]: [EcovacsMQTT] failure code: {errno}
host.tinkerboard | 2020-02-09 19:31:09.392 | error | Caught by controller[11]: [EcovacsMQTT] failure code: {errno}
host.tinkerboard | 2020-02-09 19:31:09.392 | error | Caught by controller[10]: [EcovacsMQTT] failure code: {errno}
host.tinkerboard | 2020-02-09 19:31:09.392 | error | Caught by controller[9]: [EcovacsMQTT] failure code: {errno}
host.tinkerboard | 2020-02-09 19:31:09.392 | error | Caught by controller[8]: [EcovacsMQTT] failure code: {errno}
host.tinkerboard | 2020-02-09 19:31:09.392 | error | Caught by controller[7]: [EcovacsMQTT] failure code: {errno}
host.tinkerboard | 2020-02-09 19:31:09.392 | error | Caught by controller[6]: [EcovacsMQTT] failure code: {errno}
host.tinkerboard | 2020-02-09 19:31:09.391 | error | Caught by controller[5]: [EcovacsMQTT] failure code: {errno}
host.tinkerboard | 2020-02-09 19:31:09.391 | error | Caught by controller[4]: [EcovacsAPI] Failure code 0002
host.tinkerboard | 2020-02-09 19:31:09.391 | error | Caught by controller[3]: [EcovacsAPI] Failure code 0002
host.tinkerboard | 2020-02-09 19:31:09.391 | error | Caught by controller[2]: [EcovacsAPI] Failure code 0002
host.tinkerboard | 2020-02-09 19:31:09.390 | error | Caught by controller[1]: [EcovacsAPI] Failure code 0002
ecovacs-deebot.0 | 2020-02-09 19:31:08.858 | info | (1333) Terminated (NO_ERROR): Without reason
ecovacs-deebot.0 | 2020-02-09 19:31:08.856 | info | (1333) terminating
ecovacs-deebot.0 | 2020-02-09 19:31:08.848 | info | (1333) cleaned everything up...
ecovacs-deebot.0 | 2020-02-09 19:31:08.846 | error | at Writable.write (/opt/iobroker/node_modules/readable-stream/lib/_stream_writable.js:334:11)
ecovacs-deebot.0 | 2020-02-09 19:31:08.846 | error | at writeOrBuffer (/opt/iobroker/node_modules/readable-stream/lib/_stream_writable.js:417:5)
ecovacs-deebot.0 | 2020-02-09 19:31:08.846 | error | at doWrite (/opt/iobroker/node_modules/readable-stream/lib/_stream_writable.js:428:64)
ecovacs-deebot.0 | 2020-02-09 19:31:08.846 | error | at Writable.writable._write (/opt/iobroker/node_modules/iobroker.ecovacs-deebot/node_modules/mqtt/lib/client.js:294:5)
ecovacs-deebot.0 | 2020-02-09 19:31:08.846 | error | at work (/opt/iobroker/node_modules/iobroker.ecovacs-deebot/node_modules/mqtt/lib/client.js:283:12)
ecovacs-deebot.0 | 2020-02-09 19:31:08.846 | error | at MqttClient._handlePacket (/opt/iobroker/node_modules/iobroker.ecovacs-deebot/node_modules/mqtt/lib/client.js:351:12)
ecovacs-deebot.0 | 2020-02-09 19:31:08.846 | error | at MqttClient._handlePublish (/opt/iobroker/node_modules/iobroker.ecovacs-deebot/node_modules/mqtt/lib/client.js:1162:12)
ecovacs-deebot.0 | 2020-02-09 19:31:08.846 | error | at MqttClient.emit (events.js:198:13)
ecovacs-deebot.0 | 2020-02-09 19:31:08.846 | error | at MqttClient.EcovacsMQTT.client.on  (/opt/iobroker/node_modules/iobroker.ecovacs-deebot/node_modules/ecovacs-deebot/library/ecovacsMQTT.js:82:18)
ecovacs-deebot.0 | 2020-02-09 19:31:08.846 | error | at EcovacsMQTT._handle_ctl_mqtt  (/opt/iobroker/node_modules/iobroker.ecovacs-deebot/node_modules/ecovacs-deebot/library/ecovacsMQTT.js:259:34)
ecovacs-deebot.0 | 2020-02-09 19:31:08.846 | error | (1333) TypeError: Cannot read property 'key' of undefined
ecovacs-deebot.0 | 2020-02-09 19:31:08.845 | error | (1333) uncaught exception: Cannot read property 'key' of undefined
ecovacs-deebot.0 | 2020-02-09 19:31:08.416 | info | (1333) New Device 0 successfully connected
ecovacs-deebot.0 | 2020-02-09 19:31:07.058 | info | (1333) Successfully connected to Ecovacs server
ecovacs-deebot.0 | 2020-02-09 19:31:05.392 | info | (1333) reconnecting (5) ...
host.tinkerboard | 2020-02-09 19:31:01.630 | info | instance system.adapter.dwd.0 terminated with code 0 (NO_ERROR)
dwd.0 | 2020-02-09 19:31:01.098 | info | (403) Terminated (NO_ERROR): Without reason
ecovacs-deebot.0 | 2020-02-09 19:30:59.988 | info | (1333) reconnecting (4) ...
ecovacs-deebot.0 | 2020-02-09 19:30:54.629 | info | (1333) reconnecting (3) ...
ecovacs-deebot.0 | 2020-02-09 19:30:49.280 | info | (1333) reconnecting (2) ...
ecovacs-deebot.0 | 2020-02-09 19:30:44.133 | info | (1333) reconnecting (1) ...
ecovacs-deebot.0 | 2020-02-09 19:30:38.871 | info | (1333) starting. Version 0.3.4 in /opt/iobroker/node_modules/iobroker.ecovacs-deebot, node: v10.18.1
`
![Ecovac3](https://user-images.githubusercontent.com/1240236/74107708-29090280-4b73-11ea-81b1-ac35b04fde37.JPG)

**Comment by mrbungle64** [comment]
@capitaenz, danke schon mal für die Infos.

Es handelt sich bei dem Deebot 710 auch um ein Gerät was über MQTT kommuniziert (s. 'communicationProtocol').
Ich bin gerade dabei solche Geräte zum Laufen zu bringen (ich selber habe leider kein solches) - evtl. gibt es heute Abend noch ein Update - dann könnte das schon besser aussehen :)

**Comment by mrbungle64** [comment]
@capitaenz 
Ich habe gerade mal eine neue Version auf Github bereitgestellt :)

Falls Du die mal testen möchtest müsstest Du die diesmal aber direkt über Github installieren
("Adapter" => "Adapter aus beliebiger Quelle installieren oder aktualisieren")
https://github.com/mrbungle64/ioBroker.ecovacs-deebot.git

**Comment by capitaenz** [comment]
@mrbungle64 
Also habe jetzt den Adapter wie beschrieben installiert:
`$ ./iobroker url "https://github.com/mrbungle64/ioBroker.ecovacs-deebot.git"
install https://github.com/mrbungle64/ioBroker.ecovacs-deebot/tarball/f0e9e470a2173d39ae6deee8bc5452c31f8ce20b
NPM version: 6.13.4
npm install https://github.com/mrbungle64/ioBroker.ecovacs-deebot/tarball/f0e9e470a2173d39ae6deee8bc5452c31f8ce20b --loglevel error --prefix "/opt/iobroker" (System call)
upload [5] ecovacs-deebot.admin /opt/iobroker/node_modules/iobroker.ecovacs-deebot/admin/words.js words.js application/javascript
upload [4] ecovacs-deebot.admin /opt/iobroker/node_modules/iobroker.ecovacs-deebot/admin/tsconfig.json tsconfig.json application/json
upload [3] ecovacs-deebot.admin /opt/iobroker/node_modules/iobroker.ecovacs-deebot/admin/style.css style.css text/css
upload [2] ecovacs-deebot.admin /opt/iobroker/node_modules/iobroker.ecovacs-deebot/admin/index_m.html index_m.html text/html
upload [1] ecovacs-deebot.admin /opt/iobroker/node_modules/iobroker.ecovacs-deebot/admin/ecovacs-deebot.png ecovacs-deebot.png image/png
upload [0] ecovacs-deebot.admin /opt/iobroker/node_modules/iobroker.ecovacs-deebot/admin/admin.d.ts admin.d.ts video/mp2t
Update "system.adapter.ecovacs-deebot.0"
process exited with code 0 `

Das Verhalten ist identisch und er geht auch in der App auf dem iPhone auf offline, bis er wieder auf der Ladestationen steht.

Ich hoffe, dass die Installation der neuen Version auch geklappt hat, denn ich hatte ja von dem Problem der Installation per URL berichtet.

VG
Leif

**Comment by mrbungle64** [comment]
@capitaenz, danke schon mal :)
Kannst du den Adapter bitte noch mal installieren - der Fehler 'payloadXml is not defined' sollte inzwischen behoben sein.

**Comment by mrbungle64** [comment]
> @mrbungle64
> Also habe jetzt den Adapter wie beschrieben installiert:
> `$ ./iobroker url "https://github.com/mrbungle64/ioBroker.ecovacs-deebot.git" install https://github.com/mrbungle64/ioBroker.ecovacs-deebot/tarball/f0e9e470a2173d39ae6deee8bc5452c31f8ce20b NPM version: 6.13.4 npm install https://github.com/mrbungle64/ioBroker.ecovacs-deebot/tarball/f0e9e470a2173d39ae6deee8bc5452c31f8ce20b --loglevel error --prefix "/opt/iobroker" (System call) upload [5] ecovacs-deebot.admin /opt/iobroker/node_modules/iobroker.ecovacs-deebot/admin/words.js words.js application/javascript upload [4] ecovacs-deebot.admin /opt/iobroker/node_modules/iobroker.ecovacs-deebot/admin/tsconfig.json tsconfig.json application/json upload [3] ecovacs-deebot.admin /opt/iobroker/node_modules/iobroker.ecovacs-deebot/admin/style.css style.css text/css upload [2] ecovacs-deebot.admin /opt/iobroker/node_modules/iobroker.ecovacs-deebot/admin/index_m.html index_m.html text/html upload [1] ecovacs-deebot.admin /opt/iobroker/node_modules/iobroker.ecovacs-deebot/admin/ecovacs-deebot.png ecovacs-deebot.png image/png upload [0] ecovacs-deebot.admin /opt/iobroker/node_modules/iobroker.ecovacs-deebot/admin/admin.d.ts admin.d.ts video/mp2t Update "system.adapter.ecovacs-deebot.0" process exited with code 0 `
> ...
> Ich hoffe, dass die Installation der neuen Version auch geklappt hat, denn ich hatte ja von dem Problem der Installation per URL berichtet.

Das sieht mir nach einer erfolgreichen Installation aus :)

**Comment by capitaenz** [comment]
@mrbungle64 
Also was mich stutzig gemacht hat ist, dass ich als der Adapter von der URL installiert werden sollte, dieser nicht installiert wurde, es war einfach kein Adapter da. Den Log hatte ich ja bereits unter dem Adapter-Request gepostet.
Deswegen bin ich halt unsicher, ob dieser jetzt installiert bzw. aktualisiert wurde, denn ich kann es ja nicht überprüfen, da die Versionsnummer geblieben ist.
Müsste der Fehler mit dem Offline gehen des Roboters definitiv behoben sein?

VG
Leif

**Comment by mrbungle64** [comment]
> @mrbungle64
> Also was mich stutzig gemacht hat ist, dass ich als der Adapter von der URL installiert werden sollte, dieser nicht installiert wurde, es war einfach kein Adapter da. Den Log hatte ich ja bereits unter dem Adapter-Request gepostet.

Ja das ist dann etwas komisch, aber ich sehe dort keine Fehler im Log :)

> Müsste der Fehler mit dem Offline gehen des Roboters definitiv behoben sein?

Was meinst Du genau? Ich verstehe die Frage leider nicht, sorry

**Comment by capitaenz** [comment]
@mrbungle64 
Also das Verhalten ist so:
Ich setze den Befehl der Reinigung per ioBroker ab und anschließend ist der Roboter nach dem Befehl offline. Den Reinigungsbefehl führt er aus und ist erst wieder online, wenn er auf der Ladestation steht. Überprüfen kann ich dies mit der offiziellen App, dort steht dann „offline“

**Comment by mrbungle64** [comment]
> @mrbungle64
> Also das Verhalten ist so:
> Ich setze den Befehl der Reinigung per ioBroker ab und anschließend ist der Roboter nach dem Befehl offline. Den Reinigungsbefehl führt er aus und ist erst wieder online, wenn er auf der Ladestation steht. Überprüfen kann ich dies mit der offiziellen App, dort steht dann „offline“

@capitaenz, geht er direkt nach dem Starten über dem Button "offline" oder reinigt der vorher noch ein Stück?

**Comment by capitaenz** [comment]
@mrbungle64 Also die Reinigung führt er aus. Ich kann dann jedoch nur noch über die IR-Fernbedienung Befehle geben. Irgendetwas deaktiviert das WLAN des Roboters, wenn er per Adapter von dir Reinigen soll..?

**Comment by mrbungle64** [comment]
@capitaenz 
> Müsste der Fehler mit dem Offline gehen des Roboters definitiv behoben sein?

Jetzt verstehe ich was du meinst ;)

Der Laufzeitfehler aus Deinem Log sollte behoben sein - aber ob das Verhalten mit dem "offline" gehen damit behoben ist kann ich leider nicht sagen ...

Ist natürlich Deine Entscheidung, ob Du es noch mal "wagen" möchtest heute :)

**Comment by capitaenz** [comment]
@mrbungle64 
Ich denke der Adapter muss noch mal runter und neu installiert werden, aber das Passwort für den Ecovac-Account liegt jetzt wo anders (bin jetzt nur am iPad). Teste morgen weiter, danke dir erstmal :-)

Log der Installation:
`

ecovacs-deebot.0 | 2020-02-09 21:44:19.158 | info | (7170) New Device 0 successfully connected
-- | -- | -- | --
ecovacs-deebot.0 | 2020-02-09 21:44:17.870 | info | (7170) Successfully connected to Ecovacs server
ecovacs-deebot.0 | 2020-02-09 21:44:16.394 | info | (7170) reconnecting (2) ...
ecovacs-deebot.0 | 2020-02-09 21:44:11.114 | info | (7170) reconnecting (1) ...
ecovacs-deebot.0 | 2020-02-09 21:44:05.457 | info | (7170) starting. Version 0.3.4 in /opt/iobroker/node_modules/iobroker.ecovacs-deebot, node: v10.18.1
host.tinkerboard | 2020-02-09 21:44:03.212 | info | instance system.adapter.ecovacs-deebot.0 started with pid 7170
host.tinkerboard | 2020-02-09 21:44:01.888 | info | Update repository "default" under "http://download.iobroker.net/sources-dist.json"
host.tinkerboard | 2020-02-09 21:44:01.696 | info | iobroker exit 0
host.tinkerboard | 2020-02-09 21:44:01.219 | info | instance system.adapter.ecovacs-deebot.0 terminated with code 156 (156)
host.tinkerboard | 2020-02-09 21:44:01.219 | error | Caught by controller[1]: [EcovacsAPI] Failure code 0002
ecovacs-deebot.0 | 2020-02-09 21:44:00.693 | info | (6450) Terminated (START_IMMEDIATELY_AFTER_STOP): Without reason
ecovacs-deebot.0 | 2020-02-09 21:44:00.691 | info | (6450) terminating
ecovacs-deebot.0 | 2020-02-09 21:44:00.690 | info | (6450) cleaned everything up...
ecovacs-deebot.0 | 2020-02-09 21:44:00.689 | info | (6450) Got terminate signal TERMINATE_YOURSELF
host.tinkerboard | 2020-02-09 21:44:00.683 | info | stopInstance system.adapter.ecovacs-deebot.0 send kill signal
host.tinkerboard | 2020-02-09 21:44:00.683 | info | stopInstance system.adapter.ecovacs-deebot.0 (force=false, process=true)
host.tinkerboard | 2020-02-09 21:44:00.672 | info | iobroker Update "system.adapter.ecovacs-deebot.0"
host.tinkerboard | 2020-02-09 21:44:00.579 | info | iobroker upload [0] ecovacs-deebot.admin /opt/iobroker/node_modules/iobroker.ecovacs-deebot/admin/admin.d.ts admin.d.ts video/mp2t
host.tinkerboard | 2020-02-09 21:44:00.511 | info | iobroker upload [1] ecovacs-deebot.admin /opt/iobroker/node_modules/iobroker.ecovacs-deebot/admin/ecovacs-deebot.png ecovacs-deebot.png image/png
host.tinkerboard | 2020-02-09 21:44:00.449 | info | iobroker upload [2] ecovacs-deebot.admin /opt/iobroker/node_modules/iobroker.ecovacs-deebot/admin/index_m.html index_m.html text/html
host.tinkerboard | 2020-02-09 21:44:00.392 | info | iobroker upload [3] ecovacs-deebot.admin /opt/iobroker/node_modules/iobroker.ecovacs-deebot/admin/style.css style.css text/css
host.tinkerboard | 2020-02-09 21:44:00.335 | info | iobroker upload [4] ecovacs-deebot.admin /opt/iobroker/node_modules/iobroker.ecovacs-deebot/admin/tsconfig.json tsconfig.json application/json
host.tinkerboard | 2020-02-09 21:44:00.238 | info | iobroker upload [5] ecovacs-deebot.admin /opt/iobroker/node_modules/iobroker.ecovacs-deebot/admin/words.js words.js application/javascript
ecovacs-deebot.0 | 2020-02-09 21:43:42.478 | info | (6450) New Device 0 successfully connected
ecovacs-deebot.0 | 2020-02-09 21:43:40.951 | info | (6450) Successfully connected to Ecovacs server
ecovacs-deebot.0 | 2020-02-09 21:43:39.479 | info | (6450) reconnecting (2) ...
host.tinkerboard | 2020-02-09 21:43:36.463 | info | iobroker npm install https://github.com/mrbungle64/ioBroker.ecovacs-deebot/tarball/8b01bf33dcd16a0bad360fdb3742ef321d758028 --loglevel error --prefix "/opt/iobroker" (System call)
host.tinkerboard | 2020-02-09 21:43:36.455 | info | iobroker NPM version: 6.13.4
host.tinkerboard | 2020-02-09 21:43:35.889 | info | iobroker install https://github.com/mrbungle64/ioBroker.ecovacs-deebot/tarball/8b01bf33dcd16a0bad360fdb3742ef321d758028
ecovacs-deebot.0 | 2020-02-09 21:43:34.179 | info | (6450) reconnecting (1) ...
host.tinkerboard | 2020-02-09 21:43:33.890 | info | iobroker url "https://github.com/mrbungle64/ioBroker.ecovacs-deebot.git"
ecovacs-deebot.0 | 2020-02-09 21:43:28.508 | info | (6450) starting. Version 0.3.4 in /opt/iobroker/node_modules/iobroker.ecovacs-deebot, node: v10.18.1
host.tinkerboard | 2020-02-09 21:43:26.859 | info | instance system.adapter.ecovacs-deebot.0 started with pid 6450
host.tinkerboard | 2020-02-09 21:42:56.816 | info | Restart adapter system.adapter.ecovacs-deebot.0 because enabled
host.tinkerboard | 2020-02-09 21:42:56.816 | info | instance system.adapter.ecovacs-deebot.0 terminated with code 0 (NO_ERROR)
host.tinkerboard | 2020-02-09 21:42:56.816 | error | Caught by controller[1]: at writeOrBuffer (/opt/iobroker/node_modules/readable-stream/lib/_stream_writable.js:417:5)
host.tinkerboard | 2020-02-09 21:42:56.816 | error | Caught by controller[1]: at doWrite (/opt/iobroker/node_modules/readable-stream/lib/_stream_writable.js:428:64)
host.tinkerboard | 2020-02-09 21:42:56.816 | error | Caught by controller[1]: at Writable.writable._write (/opt/iobroker/node_modules/iobroker.ecovacs-deebot/node_modules/mqtt/lib/client.js:294:5)
host.tinkerboard | 2020-02-09 21:42:56.815 | error | Caught by controller[1]: at work (/opt/iobroker/node_modules/iobroker.ecovacs-deebot/node_modules/mqtt/lib/client.js:283:12)
host.tinkerboard | 2020-02-09 21:42:56.815 | error | Caught by controller[1]: at MqttClient._handlePacket (/opt/iobroker/node_modules/iobroker.ecovacs-deebot/node_modules/mqtt/lib/client.js:351:12)
host.tinkerboard | 2020-02-09 21:42:56.815 | error | Caught by controller[1]: at MqttClient._handlePublish (/opt/iobroker/node_modules/iobroker.ecovacs-deebot/node_modules/mqtt/lib/client.js:1162:12)
host.tinkerboard | 2020-02-09 21:42:56.815 | error | Caught by controller[1]: at MqttClient.emit (events.js:198:13)
host.tinkerboard | 2020-02-09 21:42:56.815 | error | Caught by controller[1]: at MqttClient.EcovacsMQTT.client.on (/opt/iobroker/node_modules/iobroker.ecovacs-deebot/node_modules/ecovacs-deebot/library/ecovacsMQTT.js:81:18)
host.tinkerboard | 2020-02-09 21:42:56.815 | error | Caught by controller[1]: at EcovacsMQTT._handle_message (/opt/iobroker/node_modules/iobroker.ecovacs-deebot/node_modules/ecovacs-deebot/library/ecovacsMQTT.js:306:28)
host.tinkerboard | 2020-02-09 21:42:56.815 | error | Caught by controller[1]: at EcovacsMQTT._message_to_dict (/opt/iobroker/node_modules/iobroker.ecovacs-deebot/node_modules/ecovacs-deebot/library/ecovacsMQTT.js:386:38)
host.tinkerboard | 2020-02-09 21:42:56.814 | error | Caught by controller[1]: ReferenceError: payloadXml is not defined
ecovacs-deebot.0 | 2020-02-09 21:42:56.276 | info | (30072) Terminated (NO_ERROR): Without reason
ecovacs-deebot.0 | 2020-02-09 21:42:56.274 | info | (30072) terminating
ecovacs-deebot.0 | 2020-02-09 21:42:56.255 | info | (30072) cleaned everything up...
ecovacs-deebot.0 | 2020-02-09 21:42:56.251 | error | at writeOrBuffer (/opt/iobroker/node_modules/readable-stream/lib/_stream_writable.js:417:5)
ecovacs-deebot.0 | 2020-02-09 21:42:56.251 | error | at doWrite (/opt/iobroker/node_modules/readable-stream/lib/_stream_writable.js:428:64)
ecovacs-deebot.0 | 2020-02-09 21:42:56.251 | error | at Writable.writable._write (/opt/iobroker/node_modules/iobroker.ecovacs-deebot/node_modules/mqtt/lib/client.js:294:5)
ecovacs-deebot.0 | 2020-02-09 21:42:56.251 | error | at work (/opt/iobroker/node_modules/iobroker.ecovacs-deebot/node_modules/mqtt/lib/client.js:283:12)
ecovacs-deebot.0 | 2020-02-09 21:42:56.251 | error | at MqttClient._handlePacket (/opt/iobroker/node_modules/iobroker.ecovacs-deebot/node_modules/mqtt/lib/client.js:351:12)
ecovacs-deebot.0 | 2020-02-09 21:42:56.251 | error | at MqttClient._handlePublish (/opt/iobroker/node_modules/iobroker.ecovacs-deebot/node_modules/mqtt/lib/client.js:1162:12)
ecovacs-deebot.0 | 2020-02-09 21:42:56.251 | error | at MqttClient.emit (events.js:198:13)
ecovacs-deebot.0 | 2020-02-09 21:42:56.251 | error | at MqttClient.EcovacsMQTT.client.on (/opt/iobroker/node_modules/iobroker.ecovacs-deebot/node_modules/ecovacs-deebot/library/ecovacsMQTT.js:81:18)
ecovacs-deebot.0 | 2020-02-09 21:42:56.251 | error | at EcovacsMQTT._handle_message (/opt/iobroker/node_modules/iobroker.ecovacs-deebot/node_modules/ecovacs-deebot/library/ecovacsMQTT.js:306:28)
ecovacs-deebot.0 | 2020-02-09 21:42:56.251 | error | at EcovacsMQTT._message_to_dict (/opt/iobroker/node_modules/iobroker.ecovacs-deebot/node_modules/ecovacs-deebot/library/ecovacsMQTT.js:386:38)
ecovacs-deebot.0 | 2020-02-09 21:42:56.251 | error | (30072) ReferenceError: payloadXml is not defined
ecovacs-deebot.0 | 2020-02-09 21:42:56.249 | error | (30072) uncaught exception: payloadXml is not defined

`

**Comment by capitaenz** [comment]
@mrbungle64 
Ich habe soeben versucht den Adapter zu löschen:
1. Versuch fehlgeschlagen, die Deinstallation hing fest und ich musste mich am ioBroker (web) neu anmelden.
Anschließend waren 4-5 Adapter auf gelb, die mit dem Deebot nichts zu tun hatten, unter anderem der "ble" und der hm-rpc Adapter.
Ein iobroker -stop und iobroker -start haben geholfen.
2. Versuch war erfolgreich, der Adapter wurde deinstalliert.
Anschließend war wieder ein stop/start notwendig, da mir meine Adapter nicht mehr aufgelistet wurden, auch wurden mir (überhaupt) keine Adapter mehr zum installieren angezeigt!
Der Adapter lässt sich auch über URL wieder nicht installieren... Hab dieses Problem vorher noch nicht gehabt.

**Comment by mrbungle64** [comment]
Hi @capitaenz,

danke für die Rückmeldung! Freut mich dass die Basics beim 710 nun funktionieren :)

Dein System sieht nicht danach aus, als wären die Ressourcen knapp (Speicher etc.) - das hatte  ich nämlich erst vermutet ...

Der Adapter selbst tut eigentlich bei der Installation nichts "besonderes" - also keine "magic" Skripte oder systemnahe Dinge. Ich kann leider nur spekulieren was da schief läuft ...

**Comment by capitaenz** [comment]
@mrbungle64 
Welche Infos kann ich beisteuern, damit die Verbrauchsmaterialien und der Akkustand angezeigt werden können?
Also an den Recourcen wird es vermutlich wirklich nicht liegen:
Datenträger verfügbar: 81.9 %, gesamte RAM-Nutzung: 1242 MB / Frei: 60% = 1.203 MB [Host: tinkerboard - 22 Prozesse]

**Comment by mrbungle64** [comment]
> Welche Infos kann ich beisteuern, damit die Verbrauchsmaterialien und der Akkustand angezeigt werden können?

@capitaenz 
Ich habe heute Infos dazu in einem Log von einem Ozmo 900-Besitzer gefunden und werde das nun versuchen einzubauen - evtl. funktioniert das dann beim nächsten Update.

Ich muss mich jetzt erst mal sammeln und die vielen Rückmeldungen zu den MQTT basierten Geräten (900, 950, 710 etc) aus den letzten Tage auswerten.

Ich melde mich, wenn es was Neues gibt oder ich noch Infos benötige :)

**Comment by mrbungle64** [comment]
https://github.com/mrbungle64/ioBroker.ecovacs-deebot/issues/9
