### ISSUE TITLE
kein Clean-Status mit Ozmo T8 AIVI

### ISSUE THREAD

**Issue by sirashuan** [mrbungle64/ioBroker.ecovacs-deebot#83]
Hallo, 
ich habe einen Ozmo T8 AIVI im Einsatz und versuche gerade ein Skript zur Reinigung zu schreiben. 
Leider erhalte ich keinen Status sobald der Roboter säubert.
ecovacs-deebot.0.info.cleanstatus ist immer idle, auch wärend der Reinigung.
Der Chargin-Staurs funktioniert soweit (idle/charging)
Das einzige woran ich erkennen würde ob der Bot was tut ist anhand der Positionen.

LG
Kai

**Comment by mrbungle64** [comment]
Hallo @sirashuan 

Es wäre gut, wenn Du mal folgendes auf dem ioBroker-System machen würdest (in der Annahme dass es ein Linux-basiertes System ist):

1) Im Home-Verzeichnis  (nicht im ioBroker-Verzeichnis):
```bash
git clone https://github.com/mrbungle64/ecovacs-deebot.js.git
cd ecovacs-deebot.js
npm install
cd example
```

2) Email und Passwort in der Datei `app2.js` anpassen

3) Die app ausführen 
```bash
NODE_ENV=dev node app2.js | grep -E 'clean|Clean|status|Status'
```

4) laufen lassen (30-60 Sek.) - währenddessen beim Roboter einen Reinigungsmodus starten - und anschließend die Ausgabe posten. Aber aufpassen, dass da kein Passwort o.ä. mit dabei ist.

**Comment by sirashuan** [comment]
Hallo @mrbungle64 ,
danke für die Anleitung. Habe ich so umgesetzt.
Ich habe den Bot 2 Minuten laufen lassen, abgebrochen und dann in die LS zurück geschickt.
Bitte sag mir wenn ich weiter helfen kann.

Anbei ist das Ergebnis. [result.txt](https://github.com/mrbungle64/ioBroker.ecovacs-deebot/files/4961010/result.txt)

LG
Kai

**Comment by mrbungle64** [comment]
> Hallo @mrbungle64 ,
> danke für die Anleitung. Habe ich so umgesetzt.
> Ich habe den Bot 2 Minuten laufen lassen, abgebrochen und dann in die LS zurück geschickt.
> Bitte sag mir wenn ich weiter helfen kann.
> 
> Anbei ist das Ergebnis. [result.txt](https://github.com/mrbungle64/ioBroker.ecovacs-deebot/files/4961023/result.txt)
> 
> LG
> Kai

@sirashuan 
Eigentlich sieht das gut aus:
```
[VacBot] *** clean_status = auto
[app2.js] CleanReport: auto
```

Kannst Du bitte mal den Adapter auf debug stellen und während der nächsten Reinigung schauen, was da bzgl. "info.cleanstatus" im Log auftaucht?

**Comment by sirashuan** [comment]
Hallo @mrbungle64 , ich habe schlechte Nachrichten.
Ich habe mich gestern so über den T8 geärgert das ich Ihne heute wieder verpackt und zurück geschickt habe. Die Software hat mir mehrfach die Karte in immer wieder neue Bereiche zerstückelt. Wenn dann noch beim Zusammenführen von 2 Bereichen eine geschlossene Tür dabei ist, sind dann Bereiche einfach weg ... Ich bin selbst in der Softwareentwicklung tätig und kann es nicht verstehen das ein Konzern einen Bug so lange (die ersten Posts habe ich von 07.2019 gefunden) unangetastet lässt.
Ich hätte vorher besser "hinlesen" sollen.
Ich habe einfach keine Lust auf Workarounds sondern auf Lösungen. Bitte versteh das nicht als Kritik an Dich, ich finde Du machst einen tollen Job und ich kann Dir nur nahe legen weiter so zu machen !! 
Ich versuche es mal mit einem Konkurrenten.

LG
Kai

**Comment by mrbungle64** [comment]
> Hallo @mrbungle64 , ich habe schlechte Nachrichten.

Hallo Kai,

> Ich habe mich gestern so über den T8 geärgert das ich Ihne heute wieder verpackt und zurück geschickt habe. Die Software hat mir mehrfach die Karte in immer wieder neue Bereiche zerstückelt. Wenn dann noch beim Zusammenführen von 2 Bereichen eine geschlossene Tür dabei ist, sind dann Bereiche einfach weg ... Ich bin selbst in der Softwareentwicklung tätig und kann es nicht verstehen das ein Konzern einen Bug so lange (die ersten Posts habe ich von 07.2019 gefunden) unangetastet lässt.

sind die Posts aus 2019 noch auf den OZMO 950 bezogen?

> Ich hätte vorher besser "hinlesen" sollen.
> Ich habe einfach keine Lust auf Workarounds sondern auf Lösungen. Bitte versteh das nicht als Kritik an Dich, ich finde Du machst einen tollen Job und ich kann Dir nur nahe legen weiter so zu machen !!

Ja, das sehe ich genauso. Workarounds sollten Workarounds bleiben und nicht dauerhaft als "Lösung" mißbraucht werden.
Danke für das Lob :+1: Ich verstehe das nicht als Kritik an meiner Arbeit - habe mit diesen Bugs ja nichts zu tun ;)

Ecovacs ist alles andere als ein Vorbild was die Qualität von Software angeht. Features können die - aber die Qualität hat klar Luft nach oben... Und die API ist ja auch weiterhin "geheim" ...

> Ich versuche es mal mit einem Konkurrenten.

Ich wünsche Dir viel Erfolg. Es gibt bestimmt Hersteller von Saugrobotern die weniger verbuggte Software produzieren.

> 
> LG
> Kai
