### ISSUE TITLE
Anregung: Reinigungssteuerung

### ISSUE THREAD

**Issue by Sacred-Shadow** [mrbungle64/ioBroker.ecovacs-deebot#84]
Wäre cool, wenn man eine einfache Zeitsteuerung direkt im Adapter haben könnte. 
Die muss ja nicht auf den Deboot selber übertragen werden. 

Reicht ja schon, wenn der Adapter basierend auf ner Zeitsteuerung eine Reinigung startet.

**Comment by mrbungle64** [comment]
Hallo @Sacred-Shadow 

ist das wirklich sinnvoll eine Zeitsteuerung einzubauen die nicht mit der Mobile App von Ecovacs synchronisiert wird?
Eine einfache Zeitsteuerung (ohne die Synchronisierung mit Ecovacs) wäre doch auch einfach über z.B. ein Blockly Skript zu realisieren, oder?

Ich würde das wenn dann schon "richtig" angehen und die Befehle der API benutzen. Dann wird es auch gleich mit der Mobile App synchronisiert.

**Comment by Sacred-Shadow** [comment]
Wenn du es richtig machen kannst, klar warum nicht. :D 
Mir ging es halt erstmal nur darum, es einfach zu halten.  

Klar kann man das auch mit Blockly und Co. lösen, im Adapter direkt ist halt einfacher/komfortabler.

**Comment by mrbungle64** [comment]
ok, das steht auch bereits auf unserer Roadmap - allerdings weit hinten ;)

https://github.com/mrbungle64/ioBroker.ecovacs-deebot/wiki/Roadmap

**Comment by Sacred-Shadow** [comment]
Ich muss sagen, ins Wiki habe ich nicht geschaut - dann kannst das hier ja zu machen. 
Hatte nur gesehen, dass es keine Milestones gibt.

Evtl. mal Milestones anlegen und die Ideen hineinlegen? :)

**Comment by mrbungle64** [comment]
> Ich muss sagen, ins Wiki habe ich nicht geschaut - dann kannst das hier ja zu machen.

Nee, das passt schon. War auch nicht so gemeint, dass Du das schon unbedingt gesehen haben müsstest.

> Hatte nur gesehen, dass es keine Milestones gibt.
> 
> Evtl. mal Milestones anlegen und die Ideen hineinlegen? :)

Ja das könnte man ggf. mal machen. Danke für die Anregung :+1:

**Comment by mrbungle64** [comment]
Wird in #147 weiter behandelt.
