### ISSUE TITLE
Datenpunkte können nicht angesteuert werden.

### ISSUE THREAD

**Issue by Denkra** [mrbungle64/ioBroker.ecovacs-deebot#86]
Ich habe seit ein paar Tagen das Problem, das er die Datenpunkte irgendwie falsch erstellt. Unter "Controll" erstellt er wie angegeben spotArea_0 - 7. Unter Map erstellt er auch die 7 aber dann mit den Nummern 0,10,11,2,3,7,8,9. Daher kann ich durch die oben angegebenen Spots nicht triggern. Das funktioniert dann nur bei den Nummern wie sie oben dann auch existieren wie 0,2,3 und 7. Er fängt bei allen triggern zwar an zu saugen bzw. er fährt aus der Ladestation raus und sagt "Reinigung wird gestartet" aber er wählt keinen Raum aus und bleibt dann da einfach vor der Station stehen

**Comment by mrbungle64** [comment]
Hallo @Denkra 

um welches Modell handelt es sich und welche Version vom Adapter hast Du installiert?

Unabhängig davon könntest Du schon mal folgendes probieren:
- entweder den kompletten "map"-Channel oder nur den entprechenden Channel für die Map (z.B. "1245243875") löschen
- Adapter neustarten
- prüfen, ob es sich wieder wie gewohnt verhält

**Comment by Denkra** [comment]
Ich habe den ozmo 950. Adapter Version ist die aktuelle ich glaube 103 Punkt ich habe schon mehrfach alle Datenpunkte gelöscht und neu erstellen lassen genauso wie ich den kompletten Adapter gelöscht und neu installiert habe.

**Comment by mrbungle64** [comment]
> Ich habe den ozmo 950. Adapter Version ist die aktuelle ich glaube 103 Punkt ich habe schon mehrfach alle Datenpunkte gelöscht und neu erstellen lassen genauso wie ich den kompletten Adapter gelöscht und neu installiert habe.

ok, ist die Version von GitHub oder (normal) per ioBroker Repo installiert worden?

**Comment by Denkra** [comment]
Installiert habe ich den Adapter diesmal über iobroker selber. Vorher hatte ich ihn über git installieren und die Updates immer nur dann gemacht, wenn ich die im alboka angezeigt bekommen habe. Funktioniert aber beides nicht.

**Comment by mrbungle64** [comment]
Sind die anderen Bereiche (welche aktuell im ioBroker über den "map" Channel nicht funktionieren) über die Mobile App ganz normal ansteuerbar?

**Comment by Denkra** [comment]
Ja genau. Über die App ist alles perfekt steuerbar.

**Comment by Denkra** [comment]
Er triggert ja irgendwas wenn ich die states trigger. Wie geschrieben er sagt das sagen gestartet wird und er fährt auch aus der Station aber er wählt keinen Raum an

**Comment by mrbungle64** [comment]
@Denkra 
Ist das ggf. seit dem Firmware-Update von 1.7.9 auf 1.8.2?

**Comment by Denkra** [comment]
Ne das war tatsächlich schon vorher

**Comment by mrbungle64** [comment]
Was passiert, wenn Du per "control.spotArea" einen oder mehrere Bereiche > 7 saugen lässt?

Also z.B. "10,11,8,9" oder nur einen davon?

**Comment by Denkra** [comment]
Muss ich nachher mal probieren wenn ich zu hause bin. Bin gerade arbeiten. Melde mich wenn ich dann mehr weiß

**Comment by Denkra** [comment]
> Was passiert, wenn Du per "control.spotArea" einen oder mehrere Bereiche > 7 saugen lässt?
> 
> Also z.B. "10,11,8,9" oder nur einen davon?

So gerade ausprobiert. Wenn ich das so mache dann funktioniert es.

**Comment by mrbungle64** [comment]
> > Was passiert, wenn Du per "control.spotArea" einen oder mehrere Bereiche > 7 saugen lässt?
> > Also z.B. "10,11,8,9" oder nur einen davon?
> 
> So gerade ausprobiert. Wenn ich das so mache dann funktioniert es. Ich weiß auch nicht ob es was damit zu tun hat aber in der Map erstellt er auch nicht bei allen Räumen den State das ich da saugen will.
> 
> ![Screenshot_647](https://user-images.githubusercontent.com/47492483/91614066-19bb9c00-e981-11ea-84c1-9d43f16deeae.jpg)

Hattest Du die Datenpunkte mal mit dem Button oben ("Baum neu erstellen") aktualisiert?
Hier fehlen ja eher die Buttons der Bereiche die lt. deiner Aussage keine Probleme machen...

Ansonsten könntest Du mal im Log schauen, ob da was auffälliges zu sehen ist.
Was kommt z.B. wenn Du eine der problematischen Bereiche startest?
Erscheint dann "start cleaning spot area: `areaNumber` on map `mapID`"?

**Comment by Denkra** [comment]
> > > Was passiert, wenn Du per "control.spotArea" einen oder mehrere Bereiche > 7 saugen lässt?
> > > Also z.B. "10,11,8,9" oder nur einen davon?
> > 
> > 
> > So gerade ausprobiert. Wenn ich das so mache dann funktioniert es. Ich weiß auch nicht ob es was damit zu tun hat aber in der Map erstellt er auch nicht bei allen Räumen den State das ich da saugen will.
> > ![Screenshot_647](https://user-images.githubusercontent.com/47492483/91614066-19bb9c00-e981-11ea-84c1-9d43f16deeae.jpg)
> 
> Hattest Du die Datenpunkte mal mit dem Button oben ("Baum neu erstellen") aktualisiert?
> Hier fehlen ja eher die Buttons der Bereiche die lt. deiner Aussage keine Probleme machen...
> 
> Ansonsten könntest Du mal im Log schauen, ob da was auffälliges zu sehen ist.
> Was kommt z.B. wenn Du eine der problematischen Bereiche startest?
> Erscheint dann "start cleaning spot area: `areaNumber` on map `mapID`"?

Ja habe die schon neu erstellt alles. Wenn ich einen "problematischen Bereich" starte, sagt er im log "start cleaning spot area: 6".

Er sagt dann "reinigung wird gestartet", fährt aus der Ladestation raus, der Sauger geht an, in der App wird die Karte weiß aber er wählt keinen Raum aus und würde dann so lange auf der Stelle stehen bis der Akku leer ist. Wie gesagt wenn ich über "spot Area" die Nummern eingebe wo er saugen soll macht er es.

**Comment by mrbungle64** [comment]
> ... Wie gesagt wenn ich über "spot Area" die Nummern eingebe wo er saugen soll macht er es. Da muss es dann aber die Nummer aus der Map sein und nicht die er bei "control" hat

Also bedeutet das, dass Du bei den problematischen Bereichen (als Beispiel) die Nummer 6 über "control.spotArea_6" starten kannst - bei "control.spotArea" musst Du dann aber die Nummer aus dem "map" Channel benutzen (z.B. 12)?

**Comment by Denkra** [comment]
> > ... Wie gesagt wenn ich über "spot Area" die Nummern eingebe wo er saugen soll macht er es. Da muss es dann aber die Nummer aus der Map sein und nicht die er bei "control" hat
> 
> Also bedeutet das, dass Du bei den problematischen Bereichen (als Beispiel) die Nummer 6 über "control.spotArea_6" starten kannst - bei "control.spotArea" musst Du dann aber die Nummer aus dem "map" Channel benutzen (z.B. 12)?

Jain. Problematische Bereiche startet er über "control.spotArea_6" nicht bzw er wählt den Raum nicht aus nicht aus. Er macht es nur wenn ich dann die Nummer aus der Map eingebe wie du geschrieben hast die zu dem Raum gehört.

**Comment by Denkra** [comment]
@mrbungle64 gib es da schon was neues warum es nicht gehen könnte oder hast du vielleicht noch eine Idee?

**Comment by mrbungle64** [comment]
Hallo @Denkra 
ich habe aktuell leider nicht wirklich eine Idee woran es liegen könnte.
Wenn ich es richtig verstehe ist es "einfach so" von einem Tag auf den anderen aufgetreten - ohne Update vom Adapter oder der Firmware. Falls Dir da noch was einfallen sollte würde mir das natürlich helfen.
Ich bin aktuell dabei den Code ein bisschen aufzuräumen - vielleicht kommt mir dabei ja noch eine Idee.

**Comment by Denkra** [comment]
Ja genau also ich habe nur die Karte neu eingelesen, Datenpunkte gelöschtt und neu erstellen lassen weil ein Raum dazu gekommen ist. Wenn mir irgendwas ein bzw auffällt sage ich bescheid.

**Comment by Denkra** [comment]
Habe zum Test nochmal eine neue Karte erstellt, den Adapter und die Datenpunkte gelöscht und alles komplett neu erstellen lassen. Jetzt legt er bei 8 Bereichen unter "Control" 0,1,2,3,4,5,6,7 an. Unter Map legt er 0,1,2,3,5,7,8 an. Bedeutet 0 - 3 funktioniert, 5 + 7 funktioniert aber 4 + 6 nicht.

**Comment by mrbungle64** [comment]
ok, danke schon mal für die Infos :+1: 

> Habe zum Test nochmal eine neue Karte erstellt, den Adapter und die Datenpunkte gelöscht und alles komplett neu erstellen lassen. Jetzt legt er bei 7 Bereichen unter "Control" 0,1,2,3,4,5,6 an. Unter Map legt er 0,1,2,3,5,7,8 an. Bedeutet 0 - 3 funktioniert, 5 + 7 funktioniert aber 4 + 6 nicht.

Zuerst ein paar Infos zum besseren Verständnis:
- Die spotAreas unter "control" werden über die Einstellung "Anzahl von Bereichen" im Adapter gesteuert und sind immer genau diese Anzahl hochgezählt - beginnend bei 0. Dort kann man theoretisch zu viel oder zu wenig einstellen und dann werden die Datenpunkte so erstellt - sind aber dann entsprechend wirkunglos. Diese Datenpunkte bzw. Buttons sollten eigentlich mal durch die Datenpunkte unter "map" abgelöst werden, da wir dachten dass die dann nicht mehr nötig sind. Aktuell sind die aber noch nicht überflüssig geworden, da es noch vereinzelt (wie auch bei Dir) noch "kleinere" Probleme mit den Datenpunkten unter "map" gibt. 
- Die Datenpunkte unter "map" werden autom. anhand dessen, was die Ecovacs API zurückgibt erstellt. Bei meinen beiden Geräten entspricht die Nummerierung der der spotAreas unter "control". Bisher scheint das auch ansonsten so zu sein. Bei dir (oder ggf. auch auf Seiten von Ecovacs bzw. dem Roboter) hat sich aber nun etwas verändert, was offensichtlich zu einer anderen Nummerierung der spotAreas führt.
- Leider habe ich keinen 950 basierten Saugroboter hier. Im Adapter wird zwar der gleiche Code ausgeführt, wie bei meinen beiden Geräten (Deebot 901 und Ozmo 930), aber die API ist teilweise eine andere, so dass die [Library](https://github.com/mrbungle64/ecovacs-deebot.js) einen separarten Zweig für die 950 basierten Geräte (920,950,T8) hat. Bedeutet: ich kann das bei mir nicht direkt nachstellen und testen.

Ich muss mir weiter Gedanken machen. Aktuell bin ich wie gesagt am Aufräumen des Codes und am verbesserten Handling der versch. Status.

Du kannst natürlich auch mal die aktuelle Version von GitHub testen, ob sich damit etwas verbessert. Falls die schlechter funktioniert als die 1.0.3 kannst Du ja jederzeit wieder zu der 1.0.3 zurück.

**Comment by Denkra** [comment]
Okay problem ist ja auch, das er die States das er saugen soll unter "Map" auch nicht bei jedem erstellt. Momentan erstellt bei 1,2,3 und 8 unter "Maps".

Die 1.0.4 habe ich mir bevor ich alles neu gemacht habe drauf gezogen. Bringt aber keine verbesserung.

**Comment by mrbungle64** [comment]
Stell' bitte die Instanz mal auf "debug" und poste mal was dort nach dem Adapter-Neustart ausgegeben wird, wenn du die Meldungen auf "MapSpotArea" filterst.

**Comment by Denkra** [comment]
> Stell' bitte die Instanz mal auf "debug" und poste mal was dort nach dem Adapter-Neustart ausgegeben wird, wenn du die Meldungen auf "MapSpotArea" filterst.

![Screenshot_664](https://user-images.githubusercontent.com/47492483/92305383-1b8bed80-ef87-11ea-9712-d3b9fbcc31ec.jpg)

**Comment by mrbungle64** [comment]
Hast Du zufällig ganze Bereiche/Räume über NoGo-Areas ausgeschlossen?

**Comment by Denkra** [comment]
Ja einen. Liegt aber auch nur daran weil bei mir auf dem Flur gerade ein Glastisch an der Wand steht und er denkt, das dahinter ein Raum ist.

**Comment by Denkra** [comment]
Ah ne kommando zurück. Nachdem er die Karte neu erstellt hat, habe ich den Bereich doch nicht angegeben das er da nicht rein soll.

**Comment by mrbungle64** [comment]
> Habe zum Test nochmal eine neue Karte erstellt, den Adapter und die Datenpunkte gelöscht und alles komplett neu erstellen lassen. Jetzt legt er bei 7 Bereichen unter "Control" 0,1,2,3,4,5,6 an. Unter Map legt er 0,1,2,3,5,7,8 an. Bedeutet 0 - 3 funktioniert, 5 + 7 funktioniert aber 4 + 6 nicht.

Was ist eigentlich mit der Nummer 8?

Kannst Du vielleicht mal eine Aufstellung in dieser Art machen?

|"control.spotArea_x"|funktioniert|entspricht "map.[MapID].spotAreas.x"|funktioniert|
|-|-|-|-|
|0|ja|0|ja|
|1| | | |
|2| | | |
|3| | | |
|4| | | |
|5| | | |
|6| | | |

**Comment by Denkra** [comment]
So habe mal einen Test gemacht der vielleicht erfolgreich war. Unter Control hat er ja bei 7 bereichen 0-6 erstellt. Unter Map 0-3, 5, 7-8. Also letzte Ziffer eine 8. Habe jetzt mal gesagt, das er 9 Bereiche erstellen soll, damit ich unter "control" definitiv die 8 drin habe, die er in den Maps erstellt. So funktioniert es. Ich kann jeden Raum anfahren wenn die Nummer unter control und Map gleich ist. Habe dann natürlich bei "control" 3 ungenutzte "tote" States.

**Comment by boriswerner** [comment]
Hi. Sorry, ich bekomme irgendwie keine Benachrichtigung mehr über issues hier.

Also. Unter dem Ordner map werden die Punkte mit der Nummerierung erstellt, die der Bot bzw die API liefert, wie schon erklärt.
Die "fehlenden" Nummern entstehen, wenn man Bereiche in der App zusammenführt. Hast du das gemacht? Ansonsten bitte einmal die Benennungen der Areas über die App wieder auf Standard setzen (in den einen Screenshot oben hast du Bathroom, etc). Dann mussten sich auch in den Buchstaben Lücken ergeben. Daran kann man dann ablesen, welche Areas tatsächlich existieren (0=A, 1=B, etc).

Und verstehe ich es richtig:
1) die Clean Buttons unter map funktionieren alle?
2) die Clean Buttons unter Control funktionieren nur, wenn es die Nummer auch unter map gibt?

Dann funktioniert aus meiner Sicht eigentlich alles, wie es soll. Unter Control müsstest du dann so viele Buttons anlegen lassen, wie unter map die maximale Nummer (+1) angezeigt wird, dann kannst du die jeweiligen Buttons nutzen.

Wie gesagt, die fehlenden Nummern ergeben sich aus Zusammenführungen oder löschen von areas, kann auch bei der Kartierung selbst schon passieren

**Comment by Denkra** [comment]
> Hi. Sorry, ich bekomme irgendwie keine Benachrichtigung mehr über issues hier.
> 
> Also. Unter dem Ordner map werden die Punkte mit der Nummerierung erstellt, die der Bot bzw die API liefert, wie schon erklärt.
> Die "fehlenden" Nummern entstehen, wenn man Bereiche in der App zusammenführt. Hast du das gemacht? Ansonsten bitte einmal die Benennungen der Areas über die App wieder auf Standard setzen (in den einen Screenshot oben hast du Bathroom, etc). Dann mussten sich auch in den Buchstaben Lücken ergeben. Daran kann man dann ablesen, welche Areas tatsächlich existieren (0=A, 1=B, etc).
> 
> Und verstehe ich es richtig:
> 
> 1. die Clean Buttons unter map funktionieren alle?
> 2. die Clean Buttons unter Control funktionieren nur, wenn es die Nummer auch unter map gibt?
> 
> Dann funktioniert aus meiner Sicht eigentlich alles, wie es soll. Unter Control müsstest du dann so viele Buttons anlegen lassen, wie unter map die maximale Nummer (+1) angezeigt wird, dann kannst du die jeweiligen Buttons nutzen.
> 
> Wie gesagt, die fehlenden Nummern ergeben sich aus Zusammenführungen oder löschen von areas, kann auch bei der Kartierung selbst schon passieren

Ja ich habe Abschnitte zusammengefügt da er aus einem Raum 2 gemacht hat und das 2 mal. 

1. Die clean Buttons unter "Map" erstellt er teilweise nicht alle
2. Richtig

**Comment by boriswerner** [comment]
Aber zu 1.:
Was heißt denn, nicht alle? Mach doch Mal einen screenshot von deiner Map in der Area-Ansicht. Wie viele Areas hast du da und welche Buchstaben gibt es?
Und dann noch einen Screenshot deiner aktuellen Datenpunkte im map Ordner aus dem iobroker.
Wie gesagt, fehlende Nummern zwischendurch sind völlig normal, es sollten aber genauso viele areas da sein, wie in der App und auch den Buchstaben/Namen entsprechend

**Comment by mrbungle64** [comment]
> Ja ich habe Abschnitte zusammengefügt da er aus einem Raum 2 gemacht hat und das 2 mal.
> 
> 1. Die clean Buttons unter "Map" erstellt er teilweise nicht alle
> 2. Richtig

@Denkra 

Zu 1.) Die Frage war ja, ob die Clean Buttons alle funktionieren - und nicht, ob die Anzahl mit denen unter "control" übereinstimmt.

Wie ich eben schon geschrieben hatte:

> Die spotAreas unter "control" werden über die Einstellung "Anzahl von Bereichen" im Adapter gesteuert und sind immer genau diese Anzahl hochgezählt - beginnend bei 0. Dort kann man theoretisch zu viel oder zu wenig einstellen und dann werden die Datenpunkte so erstellt - sind aber dann entsprechend wirkunglos.

**Comment by mrbungle64** [comment]
Hallo @Denkra 

mit der aktuellen Version auf GitHub sollten die Datenpunkte unter "control" mit den gleichen ID's/Nummern erzeugt werden wie unter "map".

Du müsstest aber die Ordner "spotAreas" unter "map" löschen (oder gleich den ganzen "map" Ordner) und auch die Datenpunkte "spotArea_x" unter "control". Am besten vor dem Update des Adapters. Nach dem Update sollten dann die Buttons "synchronsiert" sein.

Weitere Infos:
- Ich habe die Einstellung "Anzahl von Bereichen" in den Adapter  Einstellungen entfernt
- Vorhandene "spotArea_x" Datenpunkte unter "control" bleiben erhalten so lange man die nicht manuell löscht. Es werden bisher also keine Buttons autom. gelöscht (kommt aber vielleicht noch).

@boriswerner

**Comment by mrbungle64** [comment]
> Ja ich habe Abschnitte zusammengefügt da er aus einem Raum 2 gemacht hat und das 2 mal.
> 
> 1. Die clean Buttons unter "Map" erstellt er teilweise nicht alle

@Denkra 
Jetzt verstehe ich glaub ich was Du meinst ...
Beziehst Du Dich auf das was man auf dem Screenshot vom 29. August sieht?

> 2. Richtig

**Comment by mrbungle64** [comment]
@Denkra 
Es wäre gut, wenn wir noch mal Rückmeldung bekommen würden.
