### ISSUE TITLE
Failure at installation code 25

### ISSUE THREAD

**Issue by wracksolutionist** [mrbungle64/ioBroker.ecovacs-deebot#88]
Hi,
the installation in iobroker was terminated with following failure. Has anyone a hint to resolve it.

BR

$ ./iobroker add ecovacs-deebot  --host 30cb429c3163
NPM version: 6.14.5
npm install iobroker.ecovacs-deebot@1.0.3 --loglevel error --prefix "/opt/iobroker" (System call)
Package pixman-1 was not found in the pkg-config search path.Perhaps you should add the directory containing `pixman-1.pc'to the PKG_CONFIG_PATH environment variableNo package 'pixman-1' found
gyp: Call to 'pkg-config pixman-1 --libs' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp
 ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)gyp ERR! stack     at ChildProcess.emit (events.js:315:20)gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 4.19.69-v7+gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/opt/iobroker/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/opt/iobroker/node_modules/canvas/build/Release" "--napi_version=6" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v72"gyp ERR! cwd /opt/iobroker/node_modules/canvasgyp ERR! node -v v12.18.1gyp ERR! node-gyp -v v5.1.0gyp ERR! not ok 
node-pre-gyp
 ERR! build error node-pre-gyp
 ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/opt/iobroker/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/opt/iobroker/node_modules/canvas/build/Release --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/opt/iobroker/node_modules/node-pre-gyp/lib/util/compile.js:83:29)node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)node-pre-gyp ERR! System Linux 4.19.69-v7+node-pre-gyp ERR! command "/usr/bin/node" "/opt/iobroker/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"node-pre-gyp ERR! cwd
 /opt/iobroker/node_modules/canvasnode-pre-gyp ERR! node -v v12.18.1node-pre-gyp ERR! node-pre-gyp -v v0.11.0node-pre-gyp ERR! not ok 
npm ERR! code ELIFECYCLEnpm ERR! errno 1npm ERR! canvas@2.6.1 install: `node-pre-gyp install --fallback-to-build`npm ERR! Exit status 1npm ERR! npm ERR! Failed at the canvas@2.6.1 install script.npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:npm 
ERR!     /opt/iobroker/.npm/_logs/2020-09-07T09_27_08_903Z-debug.log
ERROR: host.30cb429c3163 Cannot install iobroker.ecovacs-deebot@1.0.3: 1
ERROR: process exited with code 25

**Comment by mrbungle64** [comment]
https://github.com/mrbungle64/ioBroker.ecovacs-deebot#installation

**Comment by mrbungle64** [comment]
> https://github.com/mrbungle64/ioBroker.ecovacs-deebot#installation

@wracksolutionist 
Did this solve your problem?

**Comment by wracksolutionist** [comment]
HI,
thank you for the hint, hence it didn't solve it. I get following failure: Thank you for help

node-pre-gyp WARN Using needle for node-pre-gyp https download
node-pre-gyp WARN Tried to download(404): https://github.com/node-gfx/node-canva                                                           s-prebuilt/releases/download/v2.6.1/canvas-v2.6.1-node-v72-linux-glibc-arm.tar.g                                                           z
node-pre-gyp WARN Pre-built binaries not found for canvas@2.6.1 and node@12.10.0                                                            (node-v72 ABI, glibc) (falling back to source compile with node-gyp)

**Comment by mrbungle64** [comment]
> HI,
> thank you for the hint, hence it didn't solve it. I get following failure: Thank you for help
> 
> node-pre-gyp WARN Using needle for node-pre-gyp https download
> node-pre-gyp WARN Tried to download(404): https://github.com/node-gfx/node-canva s-prebuilt/releases/download/v2.6.1/canvas-v2.6.1-node-v72-linux-glibc-arm.tar.g z
> node-pre-gyp WARN Pre-built binaries not found for canvas@2.6.1 and node@12.10.0 (node-v72 ABI, glibc) (falling back to source compile with node-gyp)

@wracksolutionist 
That's only a warning. Not an error.
Have you already tested if the adapter instance works?

**Comment by wracksolutionist** [comment]
Hi,
no it not works. I already get the same failure, like in my first comment. BTW: I only paste the first lines in my secound comment, there is a whole list of warnings and errors...
BR

**Comment by mrbungle64** [comment]
Did you really follow the installation instructions?
https://github.com/mrbungle64/ioBroker.ecovacs-deebot#installation

**Comment by wracksolutionist** [comment]
Hi,
yes I did it, but I get following errors:

root@loxberry:/opt/loxberry# sudo apt-get update
Hit:1 http://ftp.halifax.rwth-aachen.de/raspbian/raspbian buster InRelease
Hit:2 https://download.docker.com/linux/raspbian buster InRelease
Hit:3 https://deb.nodesource.com/node_12.x buster InRelease
Get:4 https://dl.yarnpkg.com/debian stable InRelease [17.1 kB]
Err:4 https://dl.yarnpkg.com/debian stable InRelease
  The following signatures were invalid: EXPKEYSIG 23E7166788B63E1E Yarn Packagi                                   ng <yarn@dan.cx>
Reading package lists... Done
W: An error occurred during the signature verification. The repository is not up                                   dated and the previous index files will be used. GPG error: https://dl.yarnpkg.c                                   om/debian stable InRelease: The following signatures were invalid: EXPKEYSIG 23E                                   7166788B63E1E Yarn Packaging <yarn@dan.cx>
W: Failed to fetch https://dl.yarnpkg.com/debian/dists/stable/InRelease  The fol                                   lowing signatures were invalid: EXPKEYSIG 23E7166788B63E1E Yarn Packaging <yarn@                                   dan.cx>
W: Some index files failed to download. They have been ignored, or old ones used                                    instead.

**Comment by mrbungle64** [comment]
No, this is only step 1 of the installation instructions ...
`apt-get update` only downloads the package lists from the repositories and "updates" them to get information on the newest versions of packages and their dependencies.
And that fails in your case.

You have to check the repositories used on your system and you maybe have to fix your system first before installing this adapter or other packages.

**Comment by mrbungle64** [comment]
> Hi,
> yes I did it, but I get following errors:
> 
> root@loxberry:/opt/loxberry# sudo apt-get update
> Hit:1 http://ftp.halifax.rwth-aachen.de/raspbian/raspbian buster InRelease
> Hit:2 https://download.docker.com/linux/raspbian buster InRelease
> Hit:3 https://deb.nodesource.com/node_12.x buster InRelease
> Get:4 https://dl.yarnpkg.com/debian stable InRelease [17.1 kB]
> Err:4 https://dl.yarnpkg.com/debian stable InRelease
> The following signatures were invalid: EXPKEYSIG 23E7166788B63E1E Yarn Packagi ng [yarn@dan.cx](mailto:yarn@dan.cx)
> Reading package lists... Done
> W: An error occurred during the signature verification. The repository is not up dated and the previous index files will be used. GPG error: https://dl.yarnpkg.c om/debian stable InRelease: The following signatures were invalid: EXPKEYSIG 23E 7166788B63E1E Yarn Packaging [yarn@dan.cx](mailto:yarn@dan.cx)
> W: Failed to fetch https://dl.yarnpkg.com/debian/dists/stable/InRelease The fol lowing signatures were invalid: EXPKEYSIG 23E7166788B63E1E Yarn Packaging <yarn@ dan.cx>
> W: Some index files failed to download. They have been ignored, or old ones used instead.

@wracksolutionist 
Is this the full output?
`apt-get update` only downloads the package lists from the repositories and "updates" them to get information on the newest versions of packages and their dependencies.
