### ISSUE TITLE
CleaningMapImageURL wird nicht aktualisiert Deebot Ozmo 900

### ISSUE THREAD

**Issue by TJJochen** [mrbungle64/ioBroker.ecovacs-deebot#89]
@mrbungle64 

Hallo Sascha,

mir ist in meiner ioBroker VIS aufgefallen, dass sich seit längerem die Reinigungskarte nicht mehr aktualisiert hat.
Das Objekt ecovacs-deebot.0.cleaninglog.lastCleaningMapImageURL weist ein Datum vom 03.06.2020 auf.
Hast du da eine Lösung für mich?

Schöne Grüße
Jochen

Adapter Version 1.04

**Comment by mrbungle64** [comment]
@TJJochen 

Hallo Jochen,

sind die Einträge vom Reinigungsprotokoll unter "cleaninglog.last20Logs" und in der Mobile App soweit aktuell bzw. stimmen die miteinander üebrein?
Bei meinem Deebot 900 stimmt aktuell soweit alles (inkl. "lastCleaningMapImageURL").

Du könntest den Datenpunkt mal löschen und dann den Adapter neu starten - falls der Rest auf dem aktuellen Stand ist.

**Comment by TJJochen** [comment]
@mrbungle64 

Hallo Sascha, danke für die schnelle Antwort. Leider hat das löschen der Datenpunkte nichts gebracht. 
Bei mir ist aber auch der Datenpunkt "cleaninglog.last20Logs" total veraltet gewesen. 

Ich hatte beide gelöscht und "Staubi" mal kurz was reinigen lassen. In der App wird die Karte sofort neu angezeigt.
Im ioBroker bleiben die 3 Datenpunkte  "cleaninglog.last20Logs" und "lastCleaningMapImageURL" und "lastCleaningTimestamp" leider leer...

**Comment by mrbungle64** [comment]
@TJJochen 

Ich habe gerade noch einen Issue aus dem Juni gefunden, wo es ebenfalls beim Ozmo 900 Probleme damit gab:
[#76 link zur reinigungskarte ist alt bzw. falsch](https://github.com/mrbungle64/ioBroker.ecovacs-deebot/issues/76)

Ich befürchte, dass dies eine andere Ursache als bei Dir hatte, aber evtl. kannst Du ja noch mal die Instanz neu starten und vorher noch mal die Adapter-Einstellungen checken und ggf. noch mal speichern.

Unabhängig davon gab es immer mal wieder Probleme mit den Reinigungsprotokollen
https://www.roboter-forum.com/index.php?thread/40009-reinigungsprotokoll-wird-nicht-gespeichert/
und für die API gibt es ja auch keine öffentlich zugängliche Doku. Aus diesen Gründen ist die Funktion im Adapter auch noch als "Experimental" eingestuft.

**Comment by mrbungle64** [comment]
Hallo @TJJochen 

> Ich befürchte, dass dies eine andere Ursache als bei Dir hatte, aber evtl. kannst Du ja noch mal die Instanz neu starten und vorher noch mal die Adapter-Einstellungen checken und ggf. noch mal speichern.

Hattest Du das mal probiert?

**Comment by mrbungle64** [comment]
@TJJochen 
Ich schließe den Issue jetzt.

Ich gehe mal davon aus, dass das kein Bug vom Adapter ist und das andere Faktoren dazu führen.
Da es für die Ecovacs API weiterhin keine öffentlich zugängliche Dokumentation gibt bleibt es bei der Kennzeichnung "Experimental".
