### ISSUE TITLE
cleaninglog.lastCleaningMapImageURL Datenpunkt wird nicht erstellt Deebot Ozmo 930

### ISSUE THREAD

**Issue by Domster91** [mrbungle64/ioBroker.ecovacs-deebot#90]
Guten Tag, erstmal vielen dank für dieses klasse Adapter er funktioniert bei mir wirklich super. allerdings habe ich hier jetzt gelesen das es wohl schon möglich sein soll das man in Vis auch seine Karte anzeigen lassen kann, allerdings wird der dafür benötigte datenpunkt einfach nicht erstellt und somit erhalte ich keine Karte.

gibts das schon für den Ozmo 930 ?

**Comment by mrbungle64** [comment]
Hallo @Domster91 

> Guten Tag, erstmal vielen dank für dieses klasse Adapter er funktioniert bei mir wirklich super

danke für das positive Feedback :+1: 

> gibts das schon für den Ozmo 930 ?

Leider ist es beim Ozmo 930 scheinbar nicht möglich die Karten von den letzten Reinigungen per Ecovacs API zu beziehen. Die Mobile App zeigt ja leider auch keine Karten im Reinigungsprotokoll an. Es würde erst möglich werden, wenn eine Live Map umgesetzt ist und dann entsprechend immer der letzte Stand der Karte gespeichert wird. Aktuell plane ich das aber nicht zu implementieren.

Ich habe selbst einen Ozmo 930 - falls ich da eine Möglichkeit sehe das mit angemessenen Aufwand zu realisieren werde ich es versuchen umzusetzen. Aktuell ist es aber wie gesagt nicht geplant.

**Comment by Domster91** [comment]
Achso ok 😊, dachte ich mache vielleicht irgendetwas falsch, das es den Datenpunkt bei mir nicht gibt. 

Wie gesagt vielen Dank für den Klasse Adapter :)
