### ISSUE TITLE
deebot 950, daten bleiben hängen

### ISSUE THREAD

**Issue by krobipd** [mrbungle64/ioBroker.ecovacs-deebot#92]
hallo

habe feststellen müssen das sich das modul scheinbar nach und nach aufhängt.
dH die daten kommen schön rein und alles passt und dann nach einer zeit aktualisieren sich die daten nicht mehr.
erkennt man recht schön das sich die positionsdaten und raum daten nicht mehr aktualisieren.
sehe dazu aber keine fehlermeldung oder so

**Comment by mrbungle64** [comment]
Hallo @krobipd 

wird etwas in die Datenpunkte "info.error" und "info.errorCode" (was anderes als eine 0) eingetragen wenn das passiert?
Benutzt Du zufällig eine Fritz!Box?

**Comment by krobipd** [comment]
hey ;-)

unter "info.errorCode" gibs außer der 0 nur manchmal 1 - aber nicht dann wann er saugt und nicht mehr aktualisiert sondern einfach irgendwann.

unter "info.error" gibt es auch außer "no error" manchmal "unknown errorCode:   1" - dieser fehler taugt quasi gleichzeitig mit dem errorcode 1 auf. 

naja ich habe quasi ein mesh wlan - quasi weil ich 3 apple airports verwende mit den selben wlan daten.
funktioniert einwandfrei, manchmal hat der roboter kurze probleme mit dem wechseln aber fängt sich gleich wieder.
da sich die einzelnen wlans stark überschneiden - von der abdeckung her - kommt das natürlich sehr selten vor.

hatte mit der alten modul version (1.0.3) diese probleme nicht - zumindest ist es mir nie aufgefallen.

**Comment by mrbungle64** [comment]
@krobipd 

Schon mal danke für die Infos :+1: 

> hatte mit der alten modul version (1.0.3) diese probleme nicht - zumindest ist es mir nie aufgefallen.

Welche Version benutzt Du:
- die 1.0.4 aus Latest Repo oder
- die aktuellste Version von GitHub?

**Comment by boriswerner** [comment]
Ich hab jetzt mal meinen 950 mal wieder mit der aktuellen 1.0.4 aus dem Latest laufen lassen und zweimal das komplette EG reinigen lassen. Dabei auch zwischendurch mal das WLAN ausgeschaltet. Bei ausgeschaltetem WLAN gab es natürlich keine Aktualisierung, aber sobald es wieder da war, wurde auch wieder aktualisiert. Ich muss hier sowieso noch das OG saugen und beide Geschosse mal wieder Wischen, ich schau mal ob ich das nachgestellt bekomme. Passiert das nur direkt während der Reinigung oder auch wenn der Bot länger steht und du eine Reinigung startest (sodass er dann von Beginn an nicht aktualisiert)?
Reagiert der Bot dann noch auf die Controls aus dem iobroker oder ist die ganze Instanz funktionslos? Jedes mal bei der Reinigung? Welcher Reinigungsmodus und wie gestartet?
Sorry, aber da kommen immer so viele Fragen auf, wenn man es nicht direkt nachgestellt bekommt ;-)

**Comment by krobipd** [comment]
vielen dank für eure antworten zu dem thema.

ich habe jetzt mal den adapter komplett deinstalliert und gelöscht, reboot und neu intsalliert.
mal gucken was der nächste reinigungsvorgang macht.

habe leider nie direkt drauf geschaut was der adapter macht beim saugen, ist mir nur aufgefallen da ich je nach raum gewisse sachen machen lasse und diese dann nicht funktioniert haben. mir dann aufgefallen ist das der raum und die position nicht geändert werden. nach einem neustart des adapters ging es wieder.

ich melde mich mit meiner beobachtungen.

**Comment by krobipd** [comment]
So its Feedback time ;-)

Habe jetzt einpaar Mal saugen gelassen, heute ist mir folgendes Aufgefallen:

Die Ortungsdaten x,y, angel usw wird alles schön brav upgedatet aber nicht die ID der Spotarea.

Erst nach einem Modul Neustart ging das wieder. Also gehe ich jetzt mal davon aus das es sich hier um ein Problem auf Dauer handelt.

Vl hat ja auch jemand anderes sowas beobachtet.

**Comment by mrbungle64** [comment]
> ...
> Die Ortungsdaten x,y, angel usw wird alles schön brav upgedatet aber nicht die ID der Spotarea.
> 

Ich gehe mal davon aus, dass Du den Datenpunkt "map.deebotPositionCurrentSpotAreaID" meinst.
Kann es sein, dass Du die Canvas Abhängigkeiten nicht installiert hast?
https://github.com/mrbungle64/ioBroker.ecovacs-deebot#installation

**Comment by krobipd** [comment]
Ja genau diesen Punkt meinte ich.

Doch doch, klar habe ich alles installiert - verwende ja dein Modul schon länger ;-)

Wie gesagt nachdem ich das Modul neugestartet hatte wurde der Punkt sofort und laufen aktualisiert.

**Comment by mrbungle64** [comment]
> Ja genau diesen Punkt meinte ich.
> 
> Doch doch, klar habe ich alles installiert - verwende ja dein Modul schon länger ;-)
> 
> Wie gesagt nachdem ich das Modul neugestartet hatte wurde der Punkt sofort und laufen aktualisiert.

Sorry, hatte das falsch gelesen ;)

**Comment by mrbungle64** [comment]
@krobipd 

`unknown` bedeutet i.d.R. dass er sich zwischen 2 Bereichen befindet. Da könnte man sicherlich noch etwas optimieren.

Bedeutet das jetzt, dass es doch funktioniert?

**Comment by krobipd** [comment]
Schaut so aus.
Sorry war mein Fehler, hab nur gesehen das er in der Übersicht nicht updated. Aber wohl zum falschen Zeitpunkt hingesehen.

Ich werde das weiter beobachten aber vl hat ja das neu installieren schon geholfen.

**Comment by krobipd** [comment]
im moment läuft es recht einwandfrei - bis darauf das er immer wieder unknown rein schreibt beim raum aber dazu mach ich was extra auf.

**Comment by krobipd** [comment]
Sorry für das reopening dieses Fehlers.

Habe aber nachwievor das selbe Problem. Auch mit 1.0.7 noch immer.
Manchmal hängt sich die Raum-Erkennung einfach auf - dH die positionswerte werden immer einwandfrei aktualisiert aber die Raum zu Ordnung funktioniert dann erst wieder nach einem Neustart des Moduls.

Dann funktioniert es aber, kann aber sein das es 1-2 mal später wieder nicht funktioniert und wieder ein Neustart des moduls nötig ist.

Gibt es eine Möglichkeit dies Manuel zu debuggen? Damit ich mal selbst rausfinden kann was das Problem ist bzw falls es nicht mein Problem ist euch helfen kann diesen Fehler zu finden.

**Comment by mrbungle64** [comment]
@krobipd 

Schau mal bitte, ob Du unter "map" einen Channel hast der `null` heißt.

**Comment by krobipd** [comment]
Sagen wir es mal so, bis vor einpaar Sekunden war ich mir sicher das diesen Channel gibt.
War ja auch eigentlich immer da aber im moment nicht. 
Im moment gibt nur die kryptische map Nummer und kein null.
Aber wie gesagt war da, könnte vl mit 1.0.7 weg sein

**Comment by mrbungle64** [comment]
@krobipd 
Falls es den Channel "null" nicht gibt, ist das ja sogar gut ;)

Ich hatte heute Abend beim Testen auch das Problem, dass der den Datenpunkt "map.deebotPositionCurrentSpotAreaID" nicht aktualisiert wird. Habe es auf den Channel "null" geschoben - der ist nämlich definitv ein Fehler und ich dachte eigentlich, dass das Problem schon gelöst wäre.

Wie Du auch berichtest, ging es nach einem Neustart dann jeweils wieder.
Ich muss mir das morgen mal genauer anschauen.

**Comment by mrbungle64** [comment]
@krobipd 

Ich konnte heute bei 2 Geräten keine Probleme mit "map.deebotPositionCurrentSpotAreaID" feststellen.
Muss das wohl weiter beobachten.

Welche Version benutzt Du gerade? Die 1.0.7 aus dem Latest Repo oder eine aktuelle Version von GitHub?

**Comment by krobipd** [comment]
Hey 👋 hab mir heute die aktuelle git Version installiert. Hab gesehen das jetzt einen datenpunkt fürs canvas Modul drin hast 🥳 steht auf true 🥳

Nach der Installation ging es mal, ich werde das auch mal beobachten - was die nächsten Tage bringen

**Comment by krobipd** [comment]
leider, nochimmer der selbe fehler

**Comment by krobipd** [comment]
scheint mittlerweile behoben zu sein, vielen dank - ich mach hier mal zu

**Comment by mrbungle64** [comment]
> scheint mittlerweile behoben zu sein, vielen dank - ich mach hier mal zu

Sehr gut 👍🏻 

Welche Version benutzt Du gerade bzw. seit welcher Version läuft es stabil?

**Comment by krobipd** [comment]
installiert hab ich die 1.0.9 release version.

soweit ich mich jetzt errinnern kann ging es mit den betas/alphas der 1.0.8 schon aber mit der finalen nicht, dann bin ich wieder auf die 1.0.9 git damals gewechselt und seitdem ging es. hatte aber keine zeit das vorher zu melden bzw hab ich darauf nicht so geachtet - es ging dann einfach immer.

jedenfall ich würde sagen seit der 1.0.9 release funktioniert es jedentag ob tag oder nacht ob modem reboot usw alles egal, es funktioniert jetzt.

füg doch mal einen paypal button ein ;-) wie soll ich dir sonst einen kaffee sponsorn ;-)

**Comment by mrbungle64** [comment]
> installiert hab ich die 1.0.9 release version.
> 
> soweit ich mich jetzt errinnern kann ging es mit den betas/alphas der 1.0.8 schon aber mit der finalen nicht, dann bin ich wieder auf die 1.0.9 git damals gewechselt und seitdem ging es. hatte aber keine zeit das vorher zu melden bzw hab ich darauf nicht so geachtet - es ging dann einfach immer.
> 
> jedenfall ich würde sagen seit der 1.0.9 release funktioniert es jedentag ob tag oder nacht ob modem reboot usw alles egal, es funktioniert jetzt.

Danke für die Infos 👍🏻 

> 
> füg doch mal einen paypal button ein ;-) wie soll ich dir sonst einen kaffee sponsorn ;-)

Ja so was wird früher oder später kommen 😉😁
