### ISSUE TITLE
feature idea: next spot area id

### ISSUE THREAD

**Issue by krobipd** [mrbungle64/ioBroker.ecovacs-deebot#93]
vl ist es eine überlegung wert und sofern möglich
das man die nächste spot area id auslesen kann

dH wo der roboter als nächstes hinfährt, man kann ja zB in der app eine area auswählen, dies ist ja dann auch makiert und der roboter fährt dort hin.

im adapter gibt es dazu aber keine info
klar man kann ja die zu reinigende spot area im adapter eintragen - als quasi befehl, fahr dort hin.

ich weiß nicht ob man das auslesen kann aber wäre vl ganz interessant auch als möglichkeit zu wissen wo der roboter allgemein als nächstes hinfährt - is ja nicht immer so gleich, zumindest bei meinem.

hoffe es ist halbwegs klar was ich meine

**Comment by mrbungle64** [comment]
Ich denke, dass ich verstehe was Du meinst - allerdings kann ich nicht sagen, ob man eine zuverlässige Info bekommt welche Route der Saugroboter nehmen wird. Also ob er erst das Zimmer rechts zum Flur oder das erst das linke saugen wird (als Beispiel).

Die Info, welche Bereiche man in der App ausgewählt hat, lässt sich aber auslesen - das halte ich auch für keine schlechte Idee.

**Comment by krobipd** [comment]
genau so war das gemeint ;-)
ja im grunde reicht es ja auch zu "wissen" welchen raum man in der app ausgewählt hat
am besten währe natürlich zu wissen wo der roboter als nächstes hinfährt aber zeigt die app ja auch nicht an.

**Comment by mrbungle64** [comment]
> genau so war das gemeint ;-)

:+1: 

> ja im grunde reicht es ja auch zu "wissen" welchen raum man in der app ausgewählt hat

Bei nur einem Raum ist es ja kein Problem. Bei mehreren Räumen kann ich halt (noch) nicht sagen, ob die Reihenfolge die die API liefert auch die ist die der Roboter dann auch wirklich abfährt.

> am besten währe natürlich zu wissen wo der roboter als nächstes hinfährt aber zeigt die app ja auch nicht an.

**Comment by mrbungle64** [comment]
Ich schließe den Issue mal, da ich hier wenig Chancen sehe dass man da was machen kann.
