### ISSUE TITLE
optimierung: raum erkennung

### ISSUE THREAD

**Issue by krobipd** [mrbungle64/ioBroker.ecovacs-deebot#94]
wie in meinem anderen beitrag schon erwähnt ist die raum erkennung vom adapter manchmal noch recht ungenau

siehe shreenshot im thread zum daten bleiben hängen
im spezielle habe ich das problem in zwei räumen sodass der adapter immer wieder unknown zwischen reinschreibt obwohl der roboter sowas von eindeutig in dem raum ist - auch laut app.

vl kann man sich das nochmal ansehen

**Comment by boriswerner** [comment]
Hi, das "Problem" ist, dass die Area in der App die farbige Fläche ist und nicht zwangsweise bis zu den Wänden geht. Gerade bei Übergängen zwischen zwei Räumen, aber auch beim entlangfahren der Area-Grenzen kommt der Bot öfter Mal darüber hinaus.
Zur Erkennung, wo der Bot sich befindet, wird das Polygon aufgespannt, das geliefert wird und dann geschaut ob der Punkt für die derzeitige Position sich in diesem bzw. auf dem Rand davon befindet.
Um das eine Toleranz einzubauen müsste man entweder das Polygon der Area vergrößern oder sowas wie einen Kreis um die aktuelle Position vergrößern. Dann hätte man aber das Problem bei direkt angrenzenden Areas, dass es nicht eindeutig sein könnte.
Ein Ansatz wäre dann eine ungerade Anzahl von Punkten um die aktuelle Position zu prüfen und die Mehrheit entscheidet.
Da die Position aber sehr oft aktualisiert wird, könnte das ganz schön Performance intensiv werden.
Man könnte bei unknown allerdings auch die letzte bekannte Area weitermelden, allerdings hat man dann keine Info wenn der Bot tatsächlich Mal woanders ist...
Ist irgendwie alles nicht so optimal.
Nutzt du die Info den nur zur Anzeige? Dann könntest du ja sowas wie eine Toleranz einbauen, dass wenn er z.b über 10 Aktualisierungen unknown liefer, erst dann die Anzeige geändert wird und solange die alte Area angezeigt wird.

Sonst Ideen?
:-)

**Comment by mrbungle64** [comment]
@boriswerner Danke für die ausführliche Erklärung.

> Sonst Ideen?

Ich denke wir sollten das als Option in den Einstellungen anbieten, dass man wählen kann, ob die letzte Area stehen bleibt oder "unknown" in den Datenpunkt geschrieben wird.
Was haltet Ihr davon?

**Comment by krobipd** [comment]
also ich nutzte die aktuelle spot area id zB für meine küche
da sie einen pvc-boden hat stelle ich dort den sauger per blockly auf stufe 3 und sonst stufe 2
ich habe hier einfach ein wait drin was dann nur alle paar sekunden beim ändern check ob es die selbe id ist, funktioniert soweit super.

da der roboter, wie erwähnt, gerade bei den raumgrenzen gerne mal in den anderen raum mit rein fährt. ist das verständlich etwas kompliziert zu realisieren und daher hab ich da einfach das timeout drin und warte dann einfach immer so 5-10 sekunden und fertig damit hat sich eine kurzfristige änderungen erledigt und ich schalte nicht wie verrückt hin und her.

die frage ist, gibt es für den sauger überhaupt "unknown". also im sinne ist dieser "raum" überhaupt möglich/vorhanden?
wie macht das der sauger den eigentlich?

**Comment by mrbungle64** [comment]
> ...
> die frage ist, gibt es für den sauger überhaupt "unknown". also im sinne ist dieser "raum" überhaupt möglich/vorhanden?
> wie macht das der sauger den eigentlich?

Wie der Sauger das macht - darüber könnte man nur spekulieren. Ich denke aber nicht, dass der Sauger "unknown" kennt.
Mich würde es auch nicht wundern, wenn der Sauger nicht mal "weiß" in welchem Raum bzw. Bereich er sich befindet.

Der wird nur die Koordinaten der Eckpunkte der Fläche bekommen - diesen Bereich versucht der dann abzufahren - und währenddessen meldet er regelmäßig seine Position. Und diese versucht unser Adapter wieder zuzuordnen und Bereich dazu herauszufinden.

**Comment by mrbungle64** [comment]
> wie in meinem anderen beitrag schon erwähnt ist die raum erkennung vom adapter manchmal noch recht ungenau

https://github.com/mrbungle64/ioBroker.ecovacs-deebot/issues/92

> siehe shreenshot im thread zum daten bleiben hängen

https://github.com/mrbungle64/ioBroker.ecovacs-deebot/issues/92#issuecomment-720099530

**Comment by mrbungle64** [comment]
> ...
> da sie einen pvc-boden hat stelle ich dort den sauger per blockly auf stufe 3 und sonst stufe 2

Das wollte ich übrigens auch demnächst mal im Adapter implementieren, dass man die Saugstärke pro SpotArea einstellen kann

**Comment by mrbungle64** [comment]
@krobipd 

Hast Du mal geschaut, ob sich das Verhalten seit der 1.0.6 gebessert hat?
Vor allem wenn Du unter "Weiteres ...":
* Wert "unknown" im Datenpunkt "map.deebotPositionCurrentSpotAreaID" unterdrücken

angehakt hast?

**Comment by krobipd** [comment]
Serwus,

Ja hab ja jetzt die 1.0.7 installiert und vorher schon diese neue Option gesehen und nutze sie seit dem auch. Bis jetzt gibt es keinerlei Probleme.
