### ISSUE TITLE
Ozmo T8 plus Raumreinigung funktioniert nicht

### ISSUE THREAD

**Issue by mcbirne** [mrbungle64/ioBroker.ecovacs-deebot#95]
Die Raumreinigung vom Ozmo T8  plus funktioniert nicht. Wenn ich in einem Bereich CelanSpot Area auswähle passiert leider nichts.

**Comment by mrbungle64** [comment]
Hallo @mcbirne 

* welche Version vom Adapter benutzt Du?
* benutzt Du die spotArea Funktion im "control" Channel oder die unter  "map.xxxxxxxxx.spotAreas.x"?
* funktioniert die normale Reinigung ("control.clean")?

**Comment by mcbirne** [comment]
Ich nutze die Version 1.0.3. Ich wollte die unter map.xxxx.Areas.x nutzen. Auch die Control.clean funktioniert nicht.

**Comment by mrbungle64** [comment]
@mcbirne 
Der Ozmo T8 (+) funktoniert erst ab der Version 1.0.5.

Falls Du die Stable Repo benutzt musst Du mal kurz auf die Latest Repo switchen oder die Version von GitHub installieren. Die ist (Stand jetzt) mit der Version 1.0.5 von der Latest Repo identisch.

**Comment by mrbungle64** [comment]
@mcbirne 

Hast Du es mal mit der Version 1.0.5 probiert?

**Comment by mcbirne** [comment]
Ich habe sie gerade installiert. Leider klappt es auch dort nicht. Ich kann nur den Sound abspielen. Er verlässt nicht die Station

**Comment by mrbungle64** [comment]
> Ich habe sie gerade installiert. Leider klappt es auch dort nicht. Ich kann nur den Sound abspielen. Er verlässt nicht die Station

Welche "device class" ist unter "info.deviceClass" eingetragen?

**Comment by mcbirne** [comment]
dort steht fqxoiu

**Comment by mrbungle64** [comment]
> dort steht fqxoiu

Die war mir noch gar nicht bekannt ...

Das ist dieses Modell hier, oder?
https://www.ecovacs.com/de/deebot-robotic-vacuum-cleaner/DEEBOT-OZMO-T8-Plus

**Comment by mcbirne** [comment]
ja

**Comment by mrbungle64** [comment]
Evtl. gibt es da noch eine internationale Version, von welcher ich diese hier bekommen hatte: "55aiho"

Ich werde die so bald wie möglich aufnehmen - allerdings kann das noch einige Tage dauern bis das im ioBroker Adapter integriert ist, weil gerade dabei bin die benutzte Library aufzuräumen.

Ich melde mich dann hier wieder.

**Comment by mcbirne** [comment]
Super. 
Vielen Dank!

**Comment by mrbungle64** [comment]
Hallo @mcbirne 

falls Du mutig bist kannst Du mal die aktuelle Version hier von GitHub probieren.
Da wird bereits eine Alpha Version der Library benutzt die Dein Modell erkennen sollte :)

**Comment by mcbirne** [comment]
Hallo, 
ich würde es ausprobieren, allerdings hat ein Update keine Veränderung gebracht. Es ist immer noch die Version 1.0.5 installiert. Wie komme ich an die Beta Version ran?

**Comment by mrbungle64** [comment]
Hallo @mcbirne 

das könnte schon die richtige Version gewesen sein, denn ich hatte die Version noch nicht angepasst ;)
Installiere das bitte nochmal und schaue mal bitte, ob die Version nun "1.0.6-alpha.1" ist.

Falls ja:
mach mal bitte einen Screenshot der Datenpunkte unter "info" und schau mal bitte, ob im Log etwas Auffälliges zu sehen ist.

Falls nein:
Poste mal bitte wie Du die Installation durchgeführt hast.

**Comment by mcbirne** [comment]
Ich habe jetzt die 1.0.6-alpha.1. Es klappt nun auch Control/clean. Aber die Reinigung eines Raumes bekomme ich nicht hin. Ich dachte da gehe ich auf die Karte und suche den Bereich und wähle cleanSpotArea. Da passiert aber nichts.

**Comment by mcbirne** [comment]
Aber wenn ich unter Control bei Spot Area eine Nummer eintrage, wird der richtige Bereich gereinig. Super!

**Comment by mrbungle64** [comment]
> Ich habe jetzt die 1.0.6-alpha.1. Es klappt nun auch Control/clean. Aber die Reinigung eines Raumes bekomme ich nicht hin. Ich dachte da gehe ich auf die Karte und suche den Bereich und wähle cleanSpotArea. Da passiert aber nichts.

Bitte poste doch erst mal den Screenshot um den ich dich gebeten hatte 🙂

**Comment by mcbirne** [comment]
hier der Screenshot
![Unbenannt](https://user-images.githubusercontent.com/38691204/99439585-a721e300-2915-11eb-85ec-888c70e80e77.PNG)

**Comment by mrbungle64** [comment]
@mcbirne 
Danke für den Screenshot und die Rückmeldung :+1: 

Das meiste sieht ja schon mal recht gut aus :)
Ich schaue mir das nachher mal an, ob sich bei den "cleanSpotArea" Buttons unter "map" ein Fehler eingeschlichen hat.

Du kannst mir hier gerne noch weitere Erfahrungswerte mit dem Adapter posten :)

**Comment by mcbirne** [comment]
Wie kann man eigentlich 2 Bereiche hinterinander reinigen? Unter Control SpotArea kann man scheinbar nur einen Wert eintragen. zumindest bringt es nichts dort 2 Werte mit Simikolon oder Komma getrennt einzutragen.

**Comment by mrbungle64** [comment]
> Wie kann man eigentlich 2 Bereiche hinterinander reinigen? Unter Control SpotArea kann man scheinbar nur einen Wert eintragen. zumindest bringt es nichts dort 2 Werte mit Simikolon oder Komma getrennt einzutragen.

Genau so sollte es funktionieren:
unter "control.spotArea" Komma-separiert die Nummern eintragen (z.B. 0,3,5).

Erscheinen die Nummern die Du eingetragen hast auch alle als Ordner unter "map.xxxxxxxxxx.spotAreas"?

**Comment by mcbirne** [comment]
Ja, die Nummer existieren alle. habe es kerade nochmal mit dem Komma versucht und es ging. Vielen Dank für die Hilfe und die sehr schnelle Erweiterung.
