### ISSUE TITLE
aktualisierung funktioniert nicht auf cleaninglog (hängt sich) auf

### ISSUE THREAD

**Issue by arteck** [mrbungle64/ioBroker.ecovacs-deebot#96]
die aktualisierung hängt sich nach gewisser Zeit auf.. die Werte 
![image](https://user-images.githubusercontent.com/6681528/100586509-9139f800-32ef-11eb-924f-e935610d760a.png)

werden nicht mehr aktualisiert..  ausser nach neustart des adapter

aktualiserungsintervall 60 sec.

**Comment by mrbungle64** [comment]
@arteck 

* Welches Modell ist das?
* Welche Version vom Adapter benutzt Du aktuell?
* Benutzt Du den Adapter schon länger und das Verhalten hat sich nun geändert?

> die aktualisierung hängt sich nach gewisser Zeit auf

Was bedeutet das?
* Dass es sich nach dem Neustart nur jeweils 1x aktualisiert
* oder dass es sich nach mehrmaligem Aktualisieren aufhängt und eine Neustart notwendig ist?

**Comment by arteck** [comment]
- deebot 950
- aktuell von GIT
- relativ seid september jo info.battery wird aktualisiert

- genau einmal bei Start werden die aktualisiert
- jetzt wo du es sagst. es wird nicht aktualisiert .. 
-

**Comment by mrbungle64** [comment]
> * aktuell von GIT

Warum von GitHub und welcher Stand ist das?

> * jetzt wo du es sagst. es wird nicht aktualisiert ..

Worauf beziehst Du Dich hier?

**Comment by arteck** [comment]
warum nicht.. im stable ist es auch so..

das ganze cleaninglog wird nicht permament aktualisiert.. sondern einmal bei adapter start

**Comment by mrbungle64** [comment]
> warum nicht.. 

Weil auf GitHub das Entwickler-Repository liegt und nicht die Version für den Endbenutzer.

> ...im stable ist es auch so..
> das ganze cleaninglog wird nicht permament aktualisiert.. sondern einmal bei adapter start

Ich schaue es mir später mal an

**Comment by arteck** [comment]
das problem ist die aktualisierung liegt in der connect methode

die wird nur aufgerufen bei reconnect() und bei onReady()
ich würde eine neue methode machen für cleaninglog und dies zyklisch aktualisieren

**Comment by mrbungle64** [comment]
> das problem ist die aktualisierung liegt in der connect methode Zeile 661

In Zeile 661 wird auf den Event aus der Library reagiert. Das ist ein Event Listener und der muss nur 1x registriert werden.

> kann sein das du eine exception bekommst .. bevor der die aktualisierung macht ??

Wie kommst Du darauf?

**Comment by arteck** [comment]
weil battery oben drüber aktualisiert wird und da kommt der Wert rüber

oder kann sein das der Deebot die werte nicht zyklisch liefert sondern nur wenn der fertig ist ?? und deshalb greift die 
`if (state.val !== value) {` zeile 756 nicht ??

**Comment by mrbungle64** [comment]
> weil battery oben drüber aktualisiert wird und da kommt der Wert rüber

Wie bereits gesagt: das sind Event Listener.
Das wird bei der Aktualisierung nicht in dem Sinne sequentiell hintereinander abgearbeitet (wovon Du offensichtlich gerade noch ausgehst ...)

> 
> oder kann sein das der Deebot die werte nicht zyklisch liefert sondern nur wenn der fertig ist ?? und deshalb greift die
> `if (state.val !== value) {` zeile 756 nicht ??

Nein, die Geräte liefern die Daten nicht zyklisch. Manche werden direkt bei Aktualisierung geliefert und manche müssen zyklisch abgefragt werden. Das ist auch von Modell zu Modell unterschiedlich.

Ich schaue es mir später an - ich denke ich weiß schon an welcher Ecke ich da was machen muss.

Btw: Die Werte unter "cleaninglog" sind immer noch als "Experimentell" gekennzeichnet bzw. müssen in dem entsprechend benannten Tab erst freigeschaltet werden.

**Comment by mrbungle64** [comment]
> Btw: Die Werte unter "cleaninglog" sind immer noch als "Experimentell" gekennzeichnet bzw. müssen in dem entsprechend benannten Tab erst freigeschaltet werden

Kleine Korrektur: Grundsätzlich ist das so - aber beim Ozmo 950 ist es standardmäßig bereits freigegeben. Das sollte ich aber wieder ändern.

**Comment by mrbungle64** [comment]
Die Werte für die Reinigungsstatistik werden in einem gesonderten Intervall für die Position mit abgefragt, was aber nur während der Reinigung und der Rückkehr zur Ladestation die Datenpunkte aktualisiert.
Diese Intervall wird aber nur für XMPP basierte Geräte ausgeführt (und damit nicht für den Ozmo 950)

Ich werde das entweder ein bisschen umbbauen oder die Werte für die Reinigungsstatistik nur noch bei Statusänderung (Start der Reinigung bzw. Laden) abfragen.

@arteck, was denkst Du was sinnnvoll wäre?
* Weiterhin in dem gesonderten Intervall (aktuell alle 6 Sek. während der Reinigung) - aber dann für alle entsprechenden Geräte
* Nur bei Statusänderung (Start der Reinigung bzw. Laden + Adapter Start)
* Anderer Vorschlag

cc: @boriswerner

**Comment by arteck** [comment]
ich finde den Wert kannst du getrost bei wieder Laden aktualisieren
für mich ist interessant was der Gereinigt hat.. nach seiner Runde..

**Comment by mrbungle64** [comment]
@arteck 
Danke für die Rückmeldung :+1: 

Ich baue das dann auf jeden Fall mal ein, dass der beim Start des Ladevorgangs die Werte aktualisiert und intergriere es wahrscheinlich auch zusätzlich noch in's normale Intervall.

**Comment by mrbungle64** [comment]
@arteck 

Möchtest Du nochmal die aktuelle Version von GitHub testen?

Die Werte im channel "cleaninglog" sollten damit nun alle befüllt sein und die Reinigungsstatistik sollte sich bei Beendigung der Reinigung (Statuswechsel stop, returning, charging) aktualisieren.
Eigentlich ist es auch in dem Standard-Intervall drin, aber zumindest der Ozmo 920 (ein abgespeckter 950) meldet die aktualisierten Werte offensichtlich nicht während der Reinigung (auch in der Mobile App ändern die sich so lange nicht). Der Ozmo 930 macht das im Gegensatz dazu auch während der Reinigung ...

**Comment by arteck** [comment]
ich schaumal

**Comment by arteck** [comment]
nope leider nein..

**Comment by mrbungle64** [comment]
> nope leider nein.. keine aktualisierung nach dem lauf. ich hab den 2 mal laufen lassen..

Welche Version wird unter "info.version" angezeigt?
Sollte "1.0.7-alpha.1 (0.5.1-alpha.1)" sein.

Falls das der Fall sein sollte:
* sind "cleaninglog.last20Logs" und "cleaninglog.lastCleaningMapImageURL" nun befüllt?
* taucht im Log (debug Level) "[intervalQueue] GetCleanSum" auf?

**Comment by arteck** [comment]
1.0.7-alpha.1

**Comment by mrbungle64** [comment]
> 1.0.7-alpha.1
> ja sind gefüllt
> 
> ![grafik](https://user-images.githubusercontent.com/6681528/101070016-1268e780-359b-11eb-871b-abc9e3dc23a6.png)

Das ist ja schon mal erfreulich :+1: 

"[intervalQueue] GetCleanSum" sollte im Log (debug Level) alle 60 Sek. auftauchen (bzw. dem eingestellten Intervall).
Wenn die Reinigung beendet ist sollte es dann zusätzlich noch mal auftauchen.
Ist das der Fall?

**Comment by arteck** [comment]
weiss nicht hab den nicht auf debug laufen

**Comment by mrbungle64** [comment]
> nope leider nein.. keine aktualisierung nach dem lauf. ich hab den 2 mal laufen lassen..

Hat der Roboter nach den 2 Durchläufen jeweils angefangen zu laden oder hast Du den "nur" gestoppt?

**Comment by mrbungle64** [comment]
> weiss nicht hab den nicht auf debug laufen

Dann stell den doch bitte mal auf debug ...
Wir wollen doch das Problem lösen, oder? ;)

**Comment by mrbungle64** [comment]
Ich habe es auch gerade noch mal mit dem Ozmo 920 getestet:

* Reinigung -> Stop: Werte wurden aktualisiert
* Reingiung -> Laden: Werte wurden nicht aktualisiert - sind aber identisch mit den Werten in der Mobile App und das Reinigungsprotokoll fehlt dort auch noch. Das ist ja ein bekanntest Problem bei der 950er Serie

Hattest Du heute die Werte schon mal mit denen aus der App verglichen? Evtl. ist das Verhalten ja bei Dir genauso

**Comment by arteck** [comment]
doch der gibt die ja weiter.. da bei Adapter start die werte ja auch aktuell sind.
musst du halt genauso machen

**Comment by arteck** [comment]
das könen wir so lassen
geht
![grafik](https://user-images.githubusercontent.com/6681528/101144196-3b7b8d80-3618-11eb-9a6b-3d3ea9cb6c04.png)

**Comment by mrbungle64** [comment]
> das könen wir so lassen
> geht
> ![grafik](https://user-images.githubusercontent.com/6681528/101144196-3b7b8d80-3618-11eb-9a6b-3d3ea9cb6c04.png)

Das ist aber jetzt aus dem Reinigungsprotokoll.
Ich dachte wir sprechen von den Werten aus dem ursprünglichen Screenshot ;)
Also "cleaninglog.totalSquareMeters" etc.

**Comment by arteck** [comment]
den wert errechne ich untern..aber brauche dafür die richtigen Werte...
also den letzten Wert nach der Reinigung

**Comment by mrbungle64** [comment]
> den wert errechne ich intern..aber brauche dafür die richtigen Werte...
> also den letzten Wert nach der Reinigung

ok, kannst Du mir (damit es kein Mißverständnis gibt) die Datenpunkte aufzählen, die für Deinen Berechnung relevant sind?

**Comment by arteck** [comment]
also ich nehme den totalSquareMeters
![grafik](https://user-images.githubusercontent.com/6681528/101145443-125bfc80-361a-11eb-998f-3cb6a713381e.png)
neuer Wert - alter Wart = Fläche

aber ich könnte auch aus dem json es nehmen..
aus den last20Logs

**Comment by mrbungle64** [comment]
> also ich nehme den totalSquareMeters
> ![grafik](https://user-images.githubusercontent.com/6681528/101145443-125bfc80-361a-11eb-998f-3cb6a713381e.png)
> neuer Wert - alter Wart = Fläche
> 
> aber ich könnte auch aus dem json es nehmen..
> aus den last20Logs

Ja genau, in last20Logs stehen die Werte von den letzten 20 Reinigungsvorgängen. Da ist dann offensichtlich auch genau das was Du benötigst. Das wurde ja auch recht frisch in der Library gefixt, dass die Werte überhaupt wieder bezogen werden können.

**Comment by arteck** [comment]
ok dann übernimm das so ..passt..DANKE

**Comment by arteck** [comment]
ich mach wieder hier auf.. 
der mag nicht Version 1.0.7 .. die Werte cleaninglog werden wieder nicht aktualisiert..ALLE

**Comment by mrbungle64** [comment]
> ich mach wieder hier auf..
> der mag nicht Version 1.0.7 .. die Werte cleaninglog werden wieder nicht aktualisiert..ALLE

Hallo @arteck 

bedeutet das, dass sich im Channel "cleaninglog" seit dem Update auf 1.0.7 gar kein Wert mehr aktualisiert hat - auch nach einem Neustart nicht?

Seit wann hast Du die 1.0.7 installiert?
Ich gehe mal davon aus, dass Du die Werte schon mit der App abgeglichen hast.

**Comment by mrbungle64** [comment]
@arteck 

Ich habe noch mal Optimierungen an 2 Punkten vorgenommen:
- Bei einem möglichen disconnect Event von der Library (z.B. bei Abbruch der Internetverbindung) wurde das zuständige Intervall nicht sauber neu initialisiert. Das sollte nun behoben sein.
- Das Reinigungsprotokoll wird nun häufiger abgerufen.

Ich denke, dass mit der aktuellen GitHub Version das geschilderte Problem nicht mehr auftreten sollte.

**Comment by mrbungle64** [comment]
Ich hatte heute zwischendurch einen Internetabbruch - heute Abend ergibt sich folgendes Bild:

Version 1.0.7 (Produktivsystem)
* Beim XMPP basierten OZMO 930 wurden die Befehle weiterhin im Intervall ausgeführt
* Bei den 2 MQTT basierten Geräten Deebot 901 und OZMO 920 war das Intervall beendet

Aktuelle GitHub Version (Testsystem) 
* Bei allen 3 Geräten wurden die Befehle weiterhin im Intervall ausgeführt

Sieht also so aus, als wäre das Problem damit gelöst. Ich schließe den Issue wieder.
