### ISSUE TITLE
Deebot U2 SERIE

### ISSUE THREAD

**Issue by ds-1982** [mrbungle64/ioBroker.ecovacs-deebot#97]
Hallo, ist es möglich die U2 Serie in den Adapter aufzunehmen?

Ich habe meinen U2 verbunden und teilweise werden auch die Datenpunkte angezeigt, z.B. Name, Connection und letzte Ladung. Die control-Funktionen werden aber anscheinend nicht unterstützt.

Falls du mehr Infos benötigst oder ich bezüglich dem Robotertyp was helfen kann, melde dich einfach.

Besten Dank und viele Grüße
Daniel

**Comment by mrbungle64** [comment]
@ds-1982 
Hallo Daniel,

ja ich versuche soweit es geht auch diese Serie zu unterstützen - allerdings habe ich kein solches Gerät hier und da Ecovacs keine Doku zur API veröffentlicht hat kann ich keine Garantie geben, dass das auch wirklich funktioniert.

Du könntest mir aber schon mal folgende Werte geben:
* info.communicationProtocol
* info.deviceClass
* und die genaue Bezeichnung des Modells

**Comment by ds-1982** [comment]
Hallo Sascha und schon mal vielen Dank!

Hier die Werte:

- info.communicationProtocol **MQTT**
- info.deviceClass **ipzjy0**
- und die genaue Bezeichnung des Modells **DEEBOT U2**

Es gibt noch den U2 PRO (vermutlich identisch, nur größer Akku und anderes Zubehör) und beide in Schwarz und Weiß. Daher wohl die vier Modellbezeichnungen in der Anleitung:

- DGN22-62
- DGN22-64
- DGN22-72
- DGN22-74

**Comment by mrbungle64** [comment]
@ds-1982 
Danke schon mal für die Infos :+1: 

Kartenfunktionen hat der nicht, oder?
Wahrscheinlich nur Spot, Edge/Rand- und Auto-Reinigungsmodi.

**Comment by ds-1982** [comment]
@mrbungle64

Genau, keine Kartenfunktion. In der App lassen sich Spot, Rand- und Auto-Reinigung auswählen. Und natürlich Aufladen.
Der Roboter spricht auch mit mir :-) Falls es für die control-Objekte wichtig sein sollte.

Bei info.battery wird nur "%" angezeigt, aber kein Wert. Leer sind auch:
- info.chargestatus
- info.cleanstatus

Unter history funktioniert history.dateOfLastStateChange und history.timestampOfLastStateChange. Die anderen Objekte sind ebenfalls leer.

**Comment by mrbungle64** [comment]
@ds-1982 

Möchtest Du mal die aktuelle Version von GitHub testen?
In der Annahme, dass der Deebot U2 grundsätzlich auf Basis von der mit dem Ozmo 950 eingeführten Platform funktoniert, habe ich mal eine Config für die rudimentären Funktionen angelegt.
Im besten Fall funktionieren damit schon mal die wichtigsten Funktionen vom U2 ;)

**Comment by ds-1982** [comment]
@mrbungle64 

Guten Morgen! Ich habe jetzt die 1.0.6 installiert. Keine Veränderung.

Aber in der Version steht noch 1.0.6 (0.5.0-beta.0), sollte da jetzt nicht 0.5.1 stehen? Oder habe ich eventuell bei der Installation was falsch gemacht?

**Comment by mrbungle64** [comment]
> @mrbungle64 
> 
> 
> 
> Guten Morgen! Ich habe jetzt die 1.0.6 installiert. Keine Veränderung.
> 
> 
> 
> Aber in der Version steht noch 1.0.6 (0.5.0-beta.0), sollte da jetzt nicht 0.5.1 stehen? Oder habe ich eventuell bei der Installation was falsch gemacht?

Guten Morgen,

Das ist noch die vorherige Version - du musst jetzt mind. die 1.0.7-alpha.1 (0.5.1-alpha.1) installieren.

Du musst das unter "Adapter" in der Leiste oben über den 5. Button machen.
Dort kannst du den Adapter über das Feld "Adapter" suchen und dann installieren.

**Comment by ds-1982** [comment]
@mrbungle64 

War wohl etwas früh heute morgen. Habe den Adapter jetzt nochmal neu installiert. Jetzt habe ich die 1.0.7-alpha.1 (0.5.1-alpha.1).

Es funktioniert schon sehr viel !!!
Unter consumable. und .history werden bei allen Objekten Werte angezeigt.

.info muss ich noch genauer testen, sicher funktionieren:
- info.battery
- info.deviceModel
- info.deviceName

Keine Ahnung, ob die Fehler was bedeuten.
- info.error: Request Timeout
- info.errorCode: 500

Zur Bedienung (.control):
Bei .playSound passiert nichts. Aber da habe ich auch nichts in der App gefunden. Ist das eventuell für Roboter ohne Sprachausgabe?

Ohne Probleme funktionieren:
- control.charge
- control.clean
- control.pause
- control.playIamHere
- control.spot
- control.stop

Nur die Kantenreinigung (control.edge) ist etwas merkwürdig.
1. 1.Versuch: Ein Modus wird gestartet, den ich in der App überhaupt nicht starten kann. Vermutlich so etwas wie Zonenreinigung. Habe aber nur den U2. Bekomme aber auch noch einen 920, vielleicht kann ich dann mehr sagen.

2. Weitere Versuche: Fehlermeldung im Log: undefinierter Befehl

3. Stand jetzt: Automodus wird gestartet.

Ich bin also schon sehr zufrieden, vielen Dank für die schnelle Umsetzung. Bei Anpassungen im Adapter für den U2 einfach melden, kann es dann gerne testen.

**Comment by mrbungle64** [comment]
> @mrbungle64
> 
> War wohl etwas früh heute morgen. Habe den Adapter jetzt nochmal neu installiert. Jetzt habe ich die 1.0.7-alpha.1 (0.5.1-alpha.1).
> 
> Es funktioniert schon sehr viel !!!

@ds-1982 

Hallo Daniel,

danke für die ausführliche Rückmeldung!
Freut mich, dass es schon weitgehend funktioniert :+1: 

> Unter consumable. und .history werden bei allen Objekten Werte angezeigt.
> 
> .info muss ich noch genauer testen, sicher funktionieren:
> 
> * info.battery
> * info.deviceModel
> * info.deviceName
> 
> Keine Ahnung, ob die Fehler was bedeuten.
> 
> * info.error: Request Timeout
> * info.errorCode: 500

Hast Du zufällig eine Fritz!Box als Router? Ich habe nämlich auch manchmal diesen Timeout. Als Workaround kann man die Hardware-Beschleunigung der Fritz!Box deaktivieren - dann kommt der Fehler nicht mehr. Habe ein Ticket offen bei denen - aber bisher noch keine Rückmeldung....

> 
> Zur Bedienung (.control):
> Bei .playSound passiert nichts. Aber da habe ich auch nichts in der App gefunden. Ist das eventuell für Roboter ohne Sprachausgabe?

Nein, das können auch die (meisten) Modelle mit Sprachausgabe. Das ist so eine kurze Melodie die dann abgespielt wird. Evtl. hat das aber der U2 nicht ...

> 
> Ohne Probleme funktionieren:
> 
> * control.charge
> * control.clean
> * control.pause
> * control.playIamHere
> * control.spot
> * control.stop

Sehr gut :+1: 

> 
> Nur die Kantenreinigung (control.edge) ist etwas merkwürdig.
> 
> 1. 1.Versuch: Ein Modus wird gestartet, den ich in der App überhaupt nicht starten kann. Vermutlich so etwas wie Zonenreinigung. Habe aber nur den U2. Bekomme aber auch noch einen 920, vielleicht kann ich dann mehr sagen.

Interessant, dass der eine Art Zonenreinigung startet ;) 
Der Ozmo 920 hat aber (zumindest offiziel) keine Edge Funktion - funktioniet aber sehr umfassend mit dem Adapter - habe den auch seit kurzem.

> 2. Weitere Versuche: Fehlermeldung im Log: undefinierter Befehl
> 3. Stand jetzt: Automodus wird gestartet.
> 
> Ich bin also schon sehr zufrieden, vielen Dank für die schnelle Umsetzung. Bei Anpassungen im Adapter für den U2 einfach melden, kann es dann gerne testen.

**Comment by mrbungle64** [comment]
Hi @ds-1982 

hattest Du die Frage gesehen?

> Hast Du zufällig eine Fritz!Box als Router?

**Comment by ds-1982** [comment]
@mrbungle64 

Ja, Frage habe ich gesehen. Ich bekomme heute noch einen Deebot 920, daher habe ich noch nicht geantwortet. 

Ich habe eine FritzBox. Wenn ich den 920 in Betrieb habe, melde ich mich.

**Comment by mrbungle64** [comment]
> @mrbungle64
> 
> Ja, Frage habe ich gesehen. Ich bekomme heute noch einen Deebot 920, daher habe ich noch nicht geantwortet.
> 
> Ich habe eine FritzBox. 

Welches Fritz!Box Modell ist das?

Mir ging es um diese Fehler `info.error: Request Timeout` bzw. `info.errorCode: 500` - deswegen frage ich nach der Fritz!Box.

> Wenn ich den 920 in Betrieb habe, melde ich mich.

Bekommst Du den zusätzlich oder statt dem U2?

**Comment by ds-1982** [comment]
@mrbungle64 
Fritz!Box 7530. Das mit der Hardware-Beschleunigung teste ich mal die Tage. Kann aber etwas dauern.

Bekomme den 920 zusätzlich. Haben drei Stockwerke und bald zwei Kinder. Ein einzelner Roboter wäre da wahrscheinlich immer im Dauerbetrieb. Haben schon lange zwei alte Deebots, die aber langsam ausgesondert werden müssen.

**Comment by mrbungle64** [comment]
> Haben schon lange zwei alte Deebots, die aber langsam ausgesondert werden müssen

Welche Modelle sind das?
Hast oder hattest Du die auch mit dem Adapter in Betrieb?

**Comment by mrbungle64** [comment]
@ds-1982 
Noch eine Frage:

Kann der Deebot U2 wischen - obwohl der kein OZMO in der Produktbezeichnung hat?

**Comment by ds-1982** [comment]
@mrbungle64 

Ja, der U2 kann wischen. Aber mit den Bezeichnungen ist echt nicht einfach, da gebe ich dir recht. War mir am Anfang auch nicht sicher, ob er wischen kann. 

Die Roboter sind wirklich alt (Slim und M82), da ist nichts mit WLAN und SmartHome :-D

**Comment by mrbungle64** [comment]
@ds-1982 

Mit der aktuellen Version von GitHub (0.1.7-alpha.3) sollten nun zusätzliche Datenpunkte beim U2 vorhanden sein:

* info.waterbox (Anzeige, ob der Wasserbehälter eingesetzt ist)
* control.waterLevel (Auswahl und Anzeige für die Wasserzufuhr)
* control.cleanSpeed (Auswahl und Anzeige für die Saugstärke)

Schau mal bitte, ob das beim U2 soweit funktionieren.
Anmerkungen:
* Die 2 Auswahlfelder sind initial leer. Da muss man zumindest 1x was ausgewählt haben. Danach sollten die auch die Änderungen per Mobile App anzeigen.
* Die o.g. Datenpunkte sind auch beim Ozmo 920 verfügbar. Im Idealfall verhält sich das bei den 2 Modellen quasi identisch.

**Comment by ds-1982** [comment]
@mrbungle64 
info.waterbox und control.cleanSpeed funktionieren.

Die Wischfunktion beim U2 hat nur zwei Auswahlmöglichkeiten: Standard und Hoch. Im Wasserbehälter ist auch keine Pumpe oder ähnliches verbaut. Ich vermute das Wasser läuft einfach auf die Wischplatte und es gibt eine Öffnung im Deckel die mehr oder weniger verschlossen wird, um den Durchfluss etwas zu regeln.
Bei control.waterLevel wird "Hoch" mit high(3) ausgegeben und Standard mit low(1).

**Comment by mrbungle64** [comment]
> @mrbungle64
> info.waterbox und control.cleanSpeed funktionieren.

Sehr gut. Danke für die Rückmeldung :+1: 

> 
> Die Wischfunktion beim U2 hat nur zwei Auswahlmöglichkeiten: Standard und Hoch. Im Wasserbehälter ist auch keine Pumpe oder ähnliches verbaut. Ich vermute das Wasser läuft einfach auf die Wischplatte und es gibt eine Öffnung im Deckel die mehr oder weniger verschlossen wird, um den Durchfluss etwas zu regeln.
> Bei control.waterLevel wird "Hoch" mit high(3) ausgegeben und Standard mit low(1).

Dafür muss ich mir noch was überlegen, wie man das am besten Modell-abhängig implementieren kann ohne dass man zuviel Aufwand reinstecken muss. Aktuell ist die Auswahl bei alllen Modellen identisch.
Bis dahin kannst Du ja einfach die 2 genannten benutzen :)

**Comment by ds-1982** [comment]
@mrbungle64 
Habe jetzt beim U2 noch ein wenig getestet.

Zur Info: playSound funktioniert nicht. Wird eventuell von diesem Modell nicht unterstützt. Ich benötige die Funktion auch nicht.

Bei control.edge wird nun immer die normale Reinigung und nicht die Kantenreinigung gestartet.

Alles andere funktioniert. Hast du da eventuell eine Lösung?

**Comment by mrbungle64** [comment]
> @mrbungle64
> Habe jetzt beim U2 noch ein wenig getestet.
> 
> Zur Info: playSound funktioniert nicht. Wird eventuell von diesem Modell nicht unterstützt. Ich benötige die Funktion auch nicht.

Hallo @ds-1982 

danke schon mal für die Infos 👍🏻 

> 
> Bei control.edge wird nun immer die normale Reinigung und nicht die Kantenreinigung gestartet.
> 
> Alles andere funktioniert. Hast du da eventuell eine Lösung?

Der U2 basiert ja von der API her auf dem 950 - der macht aber (lt. aktuellem Stand) kein Edge oder Spot.
Daher kann ich das auch nicht testen.

Eine Lösung habe ich also nicht direkt - ich mache mir mal Gedanken dazu ...

**Comment by mrbungle64** [comment]
Da der U2 grundlegend zu funktionieren scheint (bis auf die Edge Funktion) und ich kein solches Gerät zur Verfügung habe schließe ich diesen Issue mal.
